<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Tema 1 Regressió lineal | Matemàtiques II v.2021" />
<meta property="og:type" content="book" />


<meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
<meta name="github-repo" content="cescrossello/MatesII" />


<meta name="date" content="2021-09-17" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="Apunts Matemàtiques II bookdown::gitbook.">

<title>Tema 1 Regressió lineal | Matemàtiques II v.2021</title>

<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="libs/navigation-1.1/tabsets.js"></script>
p.caption {
  color: #777;
  margin-top: 10px;
}
p code {
  white-space: inherit;
}
pre {
  word-break: normal;
  word-wrap: normal;
}
pre code {
  white-space: inherit;
}
.rmdcaution, .rmdimportant, .rmdnote, .rmdrecordau {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/3em no-repeat;
}
.rmdmercifulgod {
  padding: 1em 1em 1em 6em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/5em no-repeat;
}
.rmdromans {
  padding: 1em 1em 2em 6em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/5em no-repeat;
}
.rmdexercici {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: #f9f9f9 5px center/3em no-repeat;
}
.rmderror {
  padding: 1em 1em 2em 7em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/6em no-repeat;
}
.rmderrorpetit {
  padding: 1em 1em 2em 4em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/3em no-repeat;
}
.rmdcorbes {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: #f9f9f9  5px center/3em  no-repeat;
}
.rmdcaution {
  background-image: url("Bioestadistica-II_files/figure-html/caution.png");
}
.rmdimportant {
  background-image: url("Bioestadistica-II_files/figure-html/important.png");
}
.rmdnote {
  background-image: url("Bioestadistica-II_files/figure-html/note.png");
}
.rmdcorbes {
  background-image: url("Bioestadistica-II_files/figure-html/corbes.png");
}
.rmdrecordau {
  background-image: url("Bioestadistica-II_files/figure-html/recordau.png");
}
.rmderror {
  background-image: url("Bioestadistica-II_files/figure-html/error.png");
}
.rmderrorpetit{
  background-image: url("Bioestadistica-II_files/figure-html/error.png");
}
.rmdmercifulgod {
  background-image: url("Bioestadistica-II_files/figure-html/mercifulgod.png");
}
.rmdromans {
  background-image: url("Bioestadistica-II_files/figure-html/romanos.png");
}
.rmdexercici {
  background-image: url("Bioestadistica-II_files/figure-html/exercici.png");
}


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
/* show arrow before summary tag as in bootstrap
TODO: remove if boostrap in updated in html_document (rmarkdown#1485) */
details > summary {
  display: list-item;
  cursor: pointer;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#presentació">Presentació</a></li>
<li><a href="1-regressió-lineal.html#regressió-lineal"><span class="toc-section-number">1</span> Regressió lineal</a>
<ul>
<li><a href="1.1-regressió-lineal-simple.html#regressió-lineal-simple"><span class="toc-section-number">1.1</span> Regressió lineal simple</a>
<ul>
<li><a href="1.1-regressió-lineal-simple.html#el-model"><span class="toc-section-number">1.1.1</span> El model</a></li>
<li><a href="1.1-regressió-lineal-simple.html#mínims-quadrats"><span class="toc-section-number">1.1.2</span> Mínims quadrats</a></li>
<li><a href="1.1-regressió-lineal-simple.html#coeficient-de-determinació"><span class="toc-section-number">1.1.3</span> Coeficient de determinació</a></li>
<li><a href="1.1-regressió-lineal-simple.html#intervals-de-confiança-dels-coeficients"><span class="toc-section-number">1.1.4</span> Intervals de confiança dels coeficients</a></li>
<li><a href="1.1-regressió-lineal-simple.html#intervals-de-confiança-per-a-les-estimacions-de-la-variable-dependent"><span class="toc-section-number">1.1.5</span> Intervals de confiança per a les estimacions de la variable dependent</a></li>
<li><a href="1.1-regressió-lineal-simple.html#té-sentit-una-regressió-lineal"><span class="toc-section-number">1.1.6</span> Té sentit una regressió lineal?</a></li>
</ul></li>
<li><a href="1.2-regressió-lineal-múltiple.html#regressió-lineal-múltiple"><span class="toc-section-number">1.2</span> Regressió lineal múltiple</a>
<ul>
<li><a href="1.2-regressió-lineal-múltiple.html#mínims-quadrats-1"><span class="toc-section-number">1.2.1</span> Mínims quadrats</a></li>
<li><a href="1.2-regressió-lineal-múltiple.html#coeficient-de-determinació-múltiple"><span class="toc-section-number">1.2.2</span> Coeficient de determinació múltiple</a></li>
<li><a href="1.2-regressió-lineal-múltiple.html#coeficient-de-determinació-ajustat"><span class="toc-section-number">1.2.3</span> Coeficient de determinació ajustat</a></li>
<li><a href="1.2-regressió-lineal-múltiple.html#intervals-de-confiança-per-als-coeficients"><span class="toc-section-number">1.2.4</span> Intervals de confiança per als coeficients</a></li>
<li><a href="1.2-regressió-lineal-múltiple.html#intervals-de-confiança-per-a-les-estimacions-de-la-variable-resposta"><span class="toc-section-number">1.2.5</span> Intervals de confiança per a les estimacions de la variable resposta</a></li>
<li><a href="1.2-regressió-lineal-múltiple.html#lanova-de-la-regressió-lineal-múltiple"><span class="toc-section-number">1.2.6</span> L’ANOVA de la regressió lineal múltiple</a></li>
</ul></li>
<li><a href="1.3-test-de-la-lliçó-11.html#test-de-la-lliçó-11"><span class="toc-section-number">1.3</span> Test de la lliçó 11</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="regressió-lineal" class="section level1" number="1">
<h1><span class="header-section-number">Tema 1</span> Regressió lineal</h1>
<p>Comencem recordant un exemple de Matemàtiques I.</p>

<div class="example">
<p><span id="exm:edats1" class="example"><strong>Exemple 1.1  </strong></span>La taula següent dóna l’alçada mitjana (en cm) dels nins a determinades edats (en anys):</p>
</div>
<table>
<thead>
<tr>
<th style="text-align:right;">
edat
</th>
<th style="text-align:right;">
alçada
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
75
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
92
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
108
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
121
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
130
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
142
</td>
</tr>
<tr>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
155
</td>
</tr>
</tbody>
</table>
<p>A Matemàtiques I aprenguéreu a calcular amb R la “millor” relació lineal
<span class="math display">\[
\text{alçada}= b_0+b_1\cdot\text{edat}
\]</span>
de la manera següent:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="1-regressió-lineal.html#cb1-1" aria-hidden="true" tabindex="-1"></a>edat<span class="ot">=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">9</span>,<span class="dv">11</span>,<span class="dv">13</span>)</span>
<span id="cb1-2"><a href="1-regressió-lineal.html#cb1-2" aria-hidden="true" tabindex="-1"></a>alçada<span class="ot">=</span><span class="fu">c</span>(<span class="dv">75</span>,<span class="dv">92</span>,<span class="dv">108</span>,<span class="dv">121</span>,<span class="dv">130</span>,<span class="dv">142</span>,<span class="dv">155</span>)</span>
<span id="cb1-3"><a href="1-regressió-lineal.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(alçada<span class="sc">~</span>edat)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = alçada ~ edat)
## 
## Coefficients:
## (Intercept)         edat  
##      72.321        6.464</code></pre>
<p>Obteníeu d’aquesta manera la recta
<span class="math display">\[
\text{alçada}=72.321+6.464x
\]</span>
i la representàveu amb:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="1-regressió-lineal.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(edat,alçada,<span class="at">pch=</span><span class="dv">20</span>)</span>
<span id="cb3-2"><a href="1-regressió-lineal.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(alçada<span class="sc">~</span>edat),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Edat&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Alçada&quot;</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-12-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Ara podíeu emprar aquesta recta per estimar l’alçada d’un nin d’una edat concreta. Per exemple, ens permet estimar que l’alçada d’un nin d’10 anys és
<span class="math display">\[
72.321+6.464\cdot 10=136.964,
\]</span>
uns 137 cm.</p>
<p>En aquest tema estudiarem com es calcula aquella recta, què vol dir que sigui “la millor recta” que explica l’alçada dels nins en funció de l’edat, com trobar intervals de confiança per a les estimacions associades a aquesta recta i com tractar el problema més general de trobar “la millor funció lineal” que explica una variable <span class="math inline">\(Y\)</span> en funció de diverses variables <span class="math inline">\(X_1,\ldots,X_k\)</span>.</p>
</div>
<p style="text-align: center;">
<a href="index.html"><button class="btn btn-default">Previous</button></a>
<a href="1.1-regressió-lineal-simple.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
