<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="2.5 Variables aleatòries normals | Matemàtiques II v.2021" />
<meta property="og:type" content="book" />


<meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
<meta name="github-repo" content="cescrossello/MatesII" />


<meta name="date" content="2021-02-20" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="description" content="Apunts Matemàtiques II bookdown::gitbook.">

<title>2.5 Variables aleatòries normals | Matemàtiques II v.2021</title>

<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
p.caption {
  color: #777;
  margin-top: 10px;
}
p code {
  white-space: inherit;
}
pre {
  word-break: normal;
  word-wrap: normal;
}
pre code {
  white-space: inherit;
}
.rmdcaution, .rmdimportant, .rmdnote, .rmdrecordau {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/3em no-repeat;
}
.rmdmercifulgod {
  padding: 1em 1em 1em 6em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/5em no-repeat;
}
.rmdromans {
  padding: 1em 1em 2em 6em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/5em no-repeat;
}
.rmdexercici {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: #f9f9f9 5px center/3em no-repeat;
}
.rmderror {
  padding: 1em 1em 2em 7em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/6em no-repeat;
}
.rmderrorpetit {
  padding: 1em 1em 2em 4em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/3em no-repeat;
}
.rmdcorbes {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: #f9f9f9  5px center/3em  no-repeat;
}
.rmdcaution {
  background-image: url("Bioestadistica-II_files/figure-html/caution.png");
}
.rmdimportant {
  background-image: url("Bioestadistica-II_files/figure-html/important.png");
}
.rmdnote {
  background-image: url("Bioestadistica-II_files/figure-html/note.png");
}
.rmdcorbes {
  background-image: url("Bioestadistica-II_files/figure-html/corbes.png");
}
.rmdrecordau {
  background-image: url("Bioestadistica-II_files/figure-html/recordau.png");
}
.rmderror {
  background-image: url("Bioestadistica-II_files/figure-html/error.png");
}
.rmderrorpetit{
  background-image: url("Bioestadistica-II_files/figure-html/error.png");
}
.rmdmercifulgod {
  background-image: url("Bioestadistica-II_files/figure-html/mercifulgod.png");
}
.rmdromans {
  background-image: url("Bioestadistica-II_files/figure-html/romanos.png");
}
.rmdexercici {
  background-image: url("Bioestadistica-II_files/figure-html/exercici.png");
}


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#presentació">Presentació</a></li>
<li><a href="1-chap-conceptes.html#chap:conceptes"><span class="toc-section-number">1</span> Alguns conceptes bàsics</a>
<ul>
<li><a href="1-1-tipus-de-dades.html#tipus-de-dades"><span class="toc-section-number">1.1</span> Tipus de dades</a></li>
<li><a href="1-2-població.html#població"><span class="toc-section-number">1.2</span> Població</a></li>
<li><a href="1-3-variable-aleatòria.html#variable-aleatòria"><span class="toc-section-number">1.3</span> Variable aleatòria</a></li>
<li><a href="1-4-mostra.html#mostra"><span class="toc-section-number">1.4</span> Mostra</a></li>
<li><a href="1-5-sec-mostreig.html#sec:mostreig"><span class="toc-section-number">1.5</span> Mostreig aleatori</a></li>
<li><a href="1-6-mostres-de-conveniència.html#mostres-de-conveniència"><span class="toc-section-number">1.6</span> Mostres de conveniència</a></li>
<li><a href="1-7-test-de-la-lliçó-1.html#test-de-la-lliçó-1"><span class="toc-section-number">1.7</span> Test de la lliçó 1</a></li>
</ul></li>
<li><a href="2-chap-varal.html#chap:varal"><span class="toc-section-number">2</span> Variables aleatòries</a>
<ul>
<li><a href="2-1-generalitats-sobre-variables-aleatòries.html#generalitats-sobre-variables-aleatòries"><span class="toc-section-number">2.1</span> Generalitats sobre variables aleatòries</a></li>
<li><a href="2-2-variables-aleatòries-discretes.html#variables-aleatòries-discretes"><span class="toc-section-number">2.2</span> Variables aleatòries discretes</a>
<ul>
<li><a href="2-2-variables-aleatòries-discretes.html#densitat-i-distribució"><span class="toc-section-number">2.2.1</span> Densitat i distribució</a></li>
<li><a href="2-2-variables-aleatòries-discretes.html#esperança"><span class="toc-section-number">2.2.2</span> Esperança</a></li>
<li><a href="2-2-variables-aleatòries-discretes.html#variància-i-desviació-típica"><span class="toc-section-number">2.2.3</span> Variància i desviació típica</a></li>
<li><a href="2-2-variables-aleatòries-discretes.html#quantils"><span class="toc-section-number">2.2.4</span> Quantils</a></li>
</ul></li>
<li><a href="2-3-famílies-importants-de-variables-aleatòries-discretes.html#famílies-importants-de-variables-aleatòries-discretes"><span class="toc-section-number">2.3</span> Famílies importants de variables aleatòries discretes</a>
<ul>
<li><a href="2-3-famílies-importants-de-variables-aleatòries-discretes.html#variables-aleatòries-binomials"><span class="toc-section-number">2.3.1</span> Variables aleatòries binomials</a></li>
<li><a href="2-3-famílies-importants-de-variables-aleatòries-discretes.html#variables-aleatòries-hipergeomètriques"><span class="toc-section-number">2.3.2</span> Variables aleatòries hipergeomètriques</a></li>
<li><a href="2-3-famílies-importants-de-variables-aleatòries-discretes.html#variables-aleatòries-de-poisson"><span class="toc-section-number">2.3.3</span> Variables aleatòries de Poisson</a></li>
</ul></li>
<li><a href="2-4-variables-aleatòries-contínues.html#variables-aleatòries-contínues"><span class="toc-section-number">2.4</span> Variables aleatòries contínues</a>
<ul>
<li><a href="2-4-variables-aleatòries-contínues.html#densitat-i-distribució-1"><span class="toc-section-number">2.4.1</span> Densitat i distribució</a></li>
<li><a href="2-4-variables-aleatòries-contínues.html#esperança-variància-quantils"><span class="toc-section-number">2.4.2</span> Esperança, variància, quantils…</a></li>
</ul></li>
<li><a href="2-5-sec-normal.html#sec:normal"><span class="toc-section-number">2.5</span> Variables aleatòries normals</a>
<ul>
<li><a href="2-5-sec-normal.html#amb-r"><span class="toc-section-number">2.5.1</span> Amb R</a></li>
<li><a href="2-5-sec-normal.html#propietats-bàsiques"><span class="toc-section-number">2.5.2</span> Propietats bàsiques</a></li>
<li><a href="2-5-sec-normal.html#intervals-de-referència"><span class="toc-section-number">2.5.3</span> Intervals de referència</a></li>
<li><a href="2-5-sec-normal.html#sec:lognormal"><span class="toc-section-number">2.5.4</span> Variables log-normals</a></li>
</ul></li>
<li><a href="2-6-test-de-la-lliçó-2.html#test-de-la-lliçó-2"><span class="toc-section-number">2.6</span> Test de la lliçó 2</a></li>
</ul></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="sec:normal" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Variables aleatòries normals</h2>
<p>Una variable aleatòria contínua <span class="math inline">\(X\)</span> és <strong>normal</strong> (o <strong>té distribució normal</strong>) <strong>de paràmetres <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span></strong> (per abreujar, <span class="math inline">\(N(\mu,\sigma)\)</span>) quan la seva funció de densitat és
<span class="math display">\[
f_{X}(x)=\frac{1}{\sqrt{2\pi}\sigma} e^{{-(x-\mu)^2}/(2\sigma^{2})}
\]</span></p>
<p>Naturalment, no us heu de saber aquesta fórmula.</p>
<p><img src="Bioestadistica-II_files/figure-html/censored.png" width="40%" style="display: block; margin: auto;" /></p>
<p>Però sí que heu de saber que:</p>
<ul>
<li><p>Una variable aleatòria normal <span class="math inline">\(X\)</span> és contínua, i per tant <span class="math inline">\(P(X=x)=0\)</span>, <span class="math inline">\(P(X\leqslant x)=P(X&lt;x)\)</span> etc.</p></li>
<li><p>Si <span class="math inline">\(X\)</span> és normal, la seva funció de distribució <span class="math inline">\(F_X\)</span> és <strong>injectiva i creixent</strong>: si <span class="math inline">\(x&lt;y\)</span>, <span class="math inline">\(F_X(x)&lt;F_X(y)\)</span>.</p></li>
<li><p>Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, aleshores <span class="math inline">\(\mu_X=\mu\)</span> i <span class="math inline">\(\sigma_X=\sigma\)</span>.</p></li>
</ul>
<p>Una variable aleatòria normal diem que és <strong>estàndard</strong> (o <strong>típica</strong>) quan és <span class="math inline">\(N(0,1)\)</span>. Normalment indicarem les variables normals estàndard amb <span class="math inline">\(Z\)</span>. Observau, doncs, que si <span class="math inline">\(Z\)</span> és normal estàndard, <span class="math inline">\(\mu_Z=0\)</span> i <span class="math inline">\(\sigma_Z=1\)</span>.</p>
<p>La gràfica de la densitat d’una variable aleatòria normal és la famosa <strong>campana de Gauss</strong>:</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-99"></span>
<img src="Bioestadistica-II_files/figure-html/unnamed-chunk-99-1.png" alt="Densitat d'una variable normal estàndard" width="50%" />
<p class="caption">
Figura 2.6: Densitat d’una variable normal estàndard
</p>
</div>
<p>La distribució normal és una distribució teòrica, no la trobareu exacta en la vida real. I malgrat el seu nom, no és més “normal” que altres distribucions contínues.</p>
<p><img src="Bioestadistica-II_files/figure-html/paranormal.png" width="40%" style="display: block; margin: auto;" /></p>
<p>Però és molt important, pel fet que moltes distribucions de la vida real són aproximadament normals. El motiu és que:</p>
<blockquote>
<p>Si una variable aleatòria consisteix a prendre un nombre <strong>molt gran</strong> <span class="math inline">\(n\)</span> de mesures independents d’una o diverses variables aleatòries i sumar-les, aleshores té distribució aproximadament normal, encara que les variables aleatòries de partida no ho siguin.</p>
</blockquote>

<div class="example">
<p><span id="exm:unnamed-chunk-101" class="example"><strong>Exemple 2.9  </strong></span>Una variable binomial <span class="math inline">\(B(n,p)\)</span> s’obté prenent <span class="math inline">\(n\)</span> mesures independents d’una variable Bernoulli <span class="math inline">\(Be(p)\)</span> i sumant-les. Per tant, per la “regla” anterior, una <span class="math inline">\(B(n,p)\)</span> hauria de ser aproximadament normal si <span class="math inline">\(n\)</span> és gran. Doncs sí, si <span class="math inline">\(n\)</span> és gran (posem a partir de 40, encara que si <span class="math inline">\(p\)</span> és molt propera a 0 o 1, la mida de les mostres ha de ser més gran), una variable <span class="math inline">\(X\)</span> binomial <span class="math inline">\(B(n,p)\)</span> és aproximadament normal <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>, on recordau que, si <span class="math inline">\(X\)</span> és <span class="math inline">\(B(n,p)\)</span>, aleshores <span class="math inline">\(\mu_X=np\)</span> i <span class="math inline">\(\sigma_X=\sqrt{np(1-p)}\)</span>. Aquest “aproximadament” significa que la densitat i la distribució de <span class="math inline">\(X\)</span> són aproximadament les de la normal.</p>
</div>
<p>Per exemple, el gràfic següent compara les funcions de distribució d’una binomial <span class="math inline">\(B(40,0.3)\)</span> i una normal <span class="math inline">\(N(40\cdot 0.3,\sqrt{40\cdot 0.3\cdot 0.7})\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-102-1.png" width="50%" style="display: block; margin: auto;" /></p>

<div class="rmdrecordau">
En els propers temes emprarem sovint que una variable <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(n\)</span> és gran és aproximadament <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>.
</div>

<div class="example">
<p><span id="exm:unnamed-chunk-104" class="example"><strong>Exemple 2.10  </strong></span>Podem entendre que, amb una variable de Poisson, observam tots els punts d’un espai o tots els instants d’un període de temps i sumam tots els Èxits que hi trobam. Doncs, un altre cop, si <span class="math inline">\(X\)</span> és una variable aleatòria de Poisson <span class="math inline">\(Po(\lambda)\)</span> i <span class="math inline">\(\lambda\)</span> és gran, aleshores <span class="math inline">\(X\)</span> és aproximadament <span class="math inline">\(N(\lambda,\sqrt{\lambda})\)</span>.</p>
</div>
<p>Per exemple, el gràfic següent compara les funcions de distribució d’una Poisson <span class="math inline">\(Po(70)\)</span> i una normal <span class="math inline">\(N(70,\sqrt{70})\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-105-1.png" width="50%" style="display: block; margin: auto;" /></p>

<div class="rmdrecordau">
<p>Quan s’aproxima per mitjà d’una variable normal <span class="math inline">\(Y\)</span> una variable discreta <span class="math inline">\(X\)</span> que només pot prendre com a valors nombres naturals, com ara una binomial o una Poisson, és convenient aplicar l’anomenada <strong>correcció de continuïtat</strong>: per a cada <span class="math inline">\(n\in \mathbb{N}\)</span>, aproximar:</p>
<ul>
<li><p><span class="math inline">\(P(X\leqslant n)\)</span> per mitjà de <span class="math inline">\(P(Y&lt; n+1/2)\)</span></p></li>
<li><p><span class="math inline">\(P(X=n)\)</span> per mitjà de <span class="math inline">\(P(n-1/2&lt; Y&lt; n+1/2)\)</span></p></li>
</ul>
Vegeu l’Exemple <a href="2-5-sec-normal.html#exm:corrcont">2.11</a> més a baix.
</div>
<div id="amb-r" class="section level3" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Amb R</h3>
<p>Per calcular probabilitats d’una <span class="math inline">\(N(\mu,\sigma)\)</span>, cal calcular les integrals a mà.</p>
<p><img src="Bioestadistica-II_files/figure-html/emorisa.png" width="20%" style="display: block; margin: auto;" /></p>
<p>O podeu emprar R, per a qui la normal és <code>norm</code>. Per tant, si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>:</p>
<ul>
<li><p><code>dnorm(x,mu,sigma)</code> dóna el valor de la densitat <span class="math inline">\(f_X(x)\)</span></p></li>
<li><p><code>pnorm(x,mu,sigma)</code> dóna el valor de la distribució <span class="math inline">\(F_X(x)=P(X\leqslant x)\)</span></p></li>
<li><p><code>qnorm(q,mu,sigma)</code> dóna el <span class="math inline">\(q\)</span>-quantil de <span class="math inline">\(X\)</span></p></li>
<li><p><code>rnorm(n,mu,sigma)</code> dóna un vector de <span class="math inline">\(n\)</span> nombres aleatoris generats amb aquesta distribució</p></li>
</ul>
<p>Així, per exemple, si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(1,2)\)</span></p>
<ul>
<li><span class="math inline">\(P(X\leqslant 1.5)\)</span> és</li>
</ul>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="2-5-sec-normal.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.5</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.5987063</code></pre>
<ul>
<li>El 0.4-quantil de <span class="math inline">\(X\)</span>, és a dir, el valor <span class="math inline">\(q\)</span> tal que <span class="math inline">\(P(X\leqslant q)=0.4\)</span> és</li>
</ul>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="2-5-sec-normal.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.4</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.4933058</code></pre>
<ul>
<li><span class="math inline">\(P(X=1.5)\)</span> és</li>
</ul>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="2-5-sec-normal.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="fl">1.5</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.1933341</code></pre>

<div class="rmderror">
No! Com que <span class="math inline">\(X\)</span> és contínua, <span class="math inline">\(P(X=1.5)=0\)</span>. El que us dóna <code>dnorm(1.5,1,2)</code> és el valor de la funció de densitat de <span class="math inline">\(X\)</span> en 1.5, que no creiem que us interessi gaire.
</div>
<p>Si la normal és estàndard, no fa falta entrar la <span class="math inline">\(\mu=0\)</span> i la <span class="math inline">\(\sigma=1\)</span> (són els valors per defecte d’aquests paràmetres per a <code>norm</code>). Així, si <span class="math inline">\(Z\)</span> és <span class="math inline">\(N(0,1)\)</span>:</p>
<ul>
<li><span class="math inline">\(P(Z\leqslant 1.5)\)</span> és</li>
</ul>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="2-5-sec-normal.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.5</span>)</span></code></pre></div>
<pre><code>## [1] 0.9331928</code></pre>
<ul>
<li>El seu 0.95-quantil és</li>
</ul>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="2-5-sec-normal.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## [1] 1.644854</code></pre>
<ul>
<li>Què val <span class="math inline">\(P(-1\leqslant Z\leqslant 1)\)</span>? Com que <span class="math inline">\(P(-1\leqslant Z\leqslant 1)=P(Z\leqslant 1)-P(Z\leqslant -1)\)</span>, és</li>
</ul>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="2-5-sec-normal.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">1</span>)<span class="sc">-</span><span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.6826895</code></pre>

<div class="example">
<p><span id="exm:corrcont" class="example"><strong>Exemple 2.11  </strong></span>A la secció anterior, us hem dit que una variable binomial <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(n\)</span> gran s’aproxima per mitjà d’una variable normal <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>. Així, per exemple, una variable <span class="math inline">\(X\)</span> binomial <span class="math inline">\(B(400,0.2)\)</span> s’aproxima per mitjà d’una variable <span class="math inline">\(Y\)</span> normal <span class="math inline">\(N(400\cdot 0.2,\sqrt{400\cdot 0.2\cdot 0.8})=N(80,8)\)</span>. Vegem amb alguns exemples que aquesta aproximació és millor aplicant-hi la correcció de continuïtat:</p>
</div>
<ul>
<li><span class="math inline">\(F_X(70)=P(X\leqslant 70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="2-5-sec-normal.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">70</span>,<span class="dv">400</span>,<span class="fl">0.2</span>)</span></code></pre></div>
<pre><code>## [1] 0.1163917</code></pre>
<ul>
<li><span class="math inline">\(F_Y(70)=P(Y\leqslant 70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="2-5-sec-normal.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.1056498</code></pre>
<ul>
<li>La correcció de continuïtat ens diu que és millor aproximar <span class="math inline">\(P(X\leqslant 70)\)</span> per mitjà de <span class="math inline">\(P(Y&lt; 70+1/2)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="2-5-sec-normal.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">70.5</span>,<span class="dv">80</span>,<span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.1175152</code></pre>
<ul>
<li><span class="math inline">\(f_X(70)=P(X=70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="2-5-sec-normal.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">70</span>,<span class="dv">400</span>,<span class="fl">0.2</span>) </span></code></pre></div>
<pre><code>## [1] 0.02338443</code></pre>
<ul>
<li><span class="math inline">\(f_Y(70)\)</span> (que <strong>no és</strong> <span class="math inline">\(P(Y=70)\)</span>):</li>
</ul>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="2-5-sec-normal.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">8</span>) </span></code></pre></div>
<pre><code>## [1] 0.02283114</code></pre>
<ul>
<li>La correcció de continuïtat ens diu que és millor aproximar <span class="math inline">\(P(X=70)\)</span> per mitjà de <span class="math inline">\(P(70-1/2&lt;Y&lt; 70+1/2)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="2-5-sec-normal.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">70.5</span>,<span class="dv">80</span>,<span class="dv">8</span>) <span class="sc">-</span><span class="fu">pnorm</span>(<span class="fl">69.5</span>,<span class="dv">80</span>,<span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.02283949</code></pre>

<div class="example">
<p><span id="exm:exhiperhipo" class="example"><strong>Exemple 2.12  </strong></span>La pressió sistòlica, mesurada en mm Hg, es distribueix com una variable normal amb valor mitjà i desviació típica que depenen del sexe i l’edat. Per a la franja d’edat 16-24 anys, aquests valors (s’estima que) són:</p>
<ul>
<li>Per a homes, <span class="math inline">\(\mu=124\)</span> i <span class="math inline">\(\sigma=13.7\)</span></li>
<li>Per a dones, <span class="math inline">\(\mu=117\)</span> i <span class="math inline">\(\sigma=13.7\)</span></li>
</ul>
<p>El model d’hipertensió-hipotensió acceptat és el descrit en la Figura <a href="2-5-sec-normal.html#fig:hiperhipo">2.7</a>. Volem calcular els límits de cada classe per a cada sexe en aquest grup d’edat.</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:hiperhipo"></span>
<img src="Bioestadistica-II_files/figure-html/hiperhipo.png" alt="Model d'hipertensió-hipotensió." width="80%" />
<p class="caption">
Figura 2.7: Model d’hipertensió-hipotensió.
</p>
</div>
<p>Vegem:</p>
<ul>
<li>El límit superior del grup d’hipotensió serà el valor que deixa a l’esquerra un 5% de les tensions: el 0.05-quantil de la distribució.</li>
<li>El límit superior del grup de risc d’hipotensió serà el valor que deixa a l’esquerra un 10% de les tensions: el 0.1-quantil de la distribució.</li>
<li>El límit inferior del grup de risc d’hipertensió serà el valor que deixa a l’esquerra un 90% de les tensions: el 0.9-quantil de la distribució.</li>
<li>El límit inferior del grup d’hipertensió serà el valor que deixa a l’esquerra un 95% de les tensions: el 0.95-quantil de la distribució.</li>
</ul>
<p>En els homes, la tensió sistòlica és una variable aleatòria <span class="math inline">\(N(124,13.7)\)</span>. Aleshores, aquests quantils són:</p>
<ul>
<li>El 0.05-quantil:</li>
</ul>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="2-5-sec-normal.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fl">0.05</span>,<span class="dv">124</span>,<span class="fl">13.7</span>),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 101.5</code></pre>
<ul>
<li>El 0.1-quantil:</li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="2-5-sec-normal.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fl">0.1</span>,<span class="dv">124</span>,<span class="fl">13.7</span>),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 106.4</code></pre>
<ul>
<li>El 0.9-quantil:</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="2-5-sec-normal.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fl">0.9</span>,<span class="dv">124</span>,<span class="fl">13.7</span>),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 141.6</code></pre>
<ul>
<li>El 0.95-quantil:</li>
</ul>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="2-5-sec-normal.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fl">0.95</span>,<span class="dv">124</span>,<span class="fl">13.7</span>),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 146.5</code></pre>
<p>En resum, per als homes de 16 a 24 anys tenim els límits de la Taula <a href="2-5-sec-normal.html#tab:tensio">2.1</a>.</p>
<table>
<caption>
<span id="tab:tensio">Taula 2.1: </span>Límits d’hipotensió-hipertensió en homes joves.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Grup
</th>
<th style="text-align:left;">
Interval
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Hipotens
</td>
<td style="text-align:left;">
&lt;101.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Prehipotens
</td>
<td style="text-align:left;">
101.5 a 106.4
</td>
</tr>
<tr>
<td style="text-align:left;">
Normotens
</td>
<td style="text-align:left;">
106.4 a 141.6
</td>
</tr>
<tr>
<td style="text-align:left;">
Prehipertens
</td>
<td style="text-align:left;">
141.6 a 146.5
</td>
</tr>
<tr>
<td style="text-align:left;">
Hipertens
</td>
<td style="text-align:left;">
&gt; 146.5
</td>
</tr>
</tbody>
</table>

<div class="rmdexercici">
Calculau els límits per a les dones.
</div>
</div>
<div id="propietats-bàsiques" class="section level3" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> Propietats bàsiques</h3>
<p>Ja hem explicat el significat dels paràmetres <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span>, però el tornam a repetir:</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, aleshores <span class="math inline">\(\mu_X=\mu\)</span> i <span class="math inline">\(\sigma_X=\sigma\)</span>.
</div>
<p>Una de les propietats clau de la distribució normal és la seva simetria:</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, la seva densitat <span class="math inline">\(f_X\)</span> és simètrica respecte de <span class="math inline">\(\mu\)</span>, és a dir,
<span class="math display">\[
f_{X}(\mu-x)=f_{X}(\mu+x),
\]</span>
i pren el valor màxim a <span class="math inline">\(x=\mu\)</span>. És a dir, <span class="math inline">\(\mu\)</span> és la <strong>moda</strong> de <span class="math inline">\(X\)</span>.
</div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-129-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Per tant, el valor al voltant del qual és més probable que una variable normal <span class="math inline">\(N(\mu,\sigma)\)</span> caigui és justament el seu valor esperat <span class="math inline">\(\mu\)</span>.</p>
<p>En particular, si <span class="math inline">\(Z\)</span> és <span class="math inline">\(N(0,1)\)</span>, llavors <span class="math inline">\(f_Z\)</span> és simètrica al voltant de 0, és a dir, <span class="math inline">\(f_{Z}(-x)=f_{Z}(x)\)</span>, i la moda de <span class="math inline">\(Z\)</span> és <span class="math inline">\(x=0\)</span>.</p>
<p>Recordau que la funció de distribució d’una variable aleatòria contínua <span class="math inline">\(X\)</span>,
<span class="math display">\[
F_X(x)=P(X\leqslant x)
\]</span>
és l’àrea compresa entre la densitat <span class="math inline">\(y=f_X(x)\)</span> i l’eix d’abscisses a l’esquerra de <span class="math inline">\(x\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-130-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Llavors, la simetria de <span class="math inline">\(f_X\)</span> fa que, per a tot <span class="math inline">\(x\geqslant 0\)</span>, les àrees a l’esquerra de <span class="math inline">\(\mu-x\)</span> i a la dreta de <span class="math inline">\(\mu+x\)</span> siguin iguals.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-131-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>És a dir,
<span class="math display">\[
P(X\leqslant \mu-x)=P(X\geqslant \mu+x)=1-P(X\leqslant \mu+x)
\]</span></p>
<p>En particular (prenent <span class="math inline">\(x=0\)</span>)
<span class="math display">\[
P(X\leqslant \mu)=1-P(X\leqslant \mu)\Rightarrow P(X\leqslant \mu)=0.5
\]</span>
i per tant, <span class="math inline">\(\mu\)</span> és també la <strong>mediana</strong> de <span class="math inline">\(X\)</span>.</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, <span class="math inline">\(\mu\)</span> és la mitjana, la mediana i la moda de <span class="math inline">\(X\)</span>.
</div>
<p>En el cas concret de la normal estàndard <span class="math inline">\(Z\)</span>, per a qualsevol <span class="math inline">\(z\geqslant 0\)</span> es té que les àrees a l’esquerra de <span class="math inline">\(-z\)</span> i a la dreta de <span class="math inline">\(z\)</span> són iguals
<span class="math display">\[
P(Z\leqslant -z)=P(Z\geqslant z)=1-P(Z\leqslant z)
\]</span>
i la mediana de <span class="math inline">\(Z\)</span> és 0.</p>

<div class="rmdnote">
<p>Ara que sabem més coses de la normal, a l’Exemple <a href="2-5-sec-normal.html#exm:exhiperhipo">2.12</a> ens haguéssim pogut estalviar la meitat de la feina. Diguem <span class="math inline">\(X\)</span> a la variable aleatòria la pressió arterial, en mm Hg, d’un home d’entre 16 i 24 anys. Ens diuen que <span class="math inline">\(X\)</span> és <span class="math inline">\(N(124,13.7)\)</span>.</p>
<p>Per la simetria de <span class="math inline">\(X\)</span> al voltant de <span class="math inline">\(\mu=124\)</span>, si escrivim el 0.05-quantil com <span class="math inline">\(124-x\)</span>, aleshores <span class="math inline">\(P(X\geqslant 124+x)=P(X\leqslant 124-x)=0.05\)</span> i per tant <span class="math inline">\(P(X\leqslant 124+x)=1-P(X\geqslant 124+x)=0.95\)</span>, és a dir, <span class="math inline">\(124+x\)</span> serà el 0.95-quantil de <span class="math inline">\(X\)</span>.</p>
<p>El 0.05-quantil ha estat 101.5. Escrivint <span class="math inline">\(101.5=124-x\)</span>, obtenim <span class="math inline">\(x=22.5\)</span>. Per tant, el 0.95-quantil ha de ser <span class="math inline">\(124+22.5=146.5\)</span>.</p>
<p>El mateix passa amb el 0.9-quantil i el 0.1-quantil, raonau-ho i comprovau-ho.</p>
</div>

<div class="rmdrecordau">
L’argument que hem desenvolupat a la nota anterior mostra en general que si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span> i el seu <span class="math inline">\(q\)</span>-quantil és <span class="math inline">\(\mu-x\)</span>, aleshores el seu <span class="math inline">\((1-q)\)</span>-quantil és <span class="math inline">\(\mu+x\)</span>.
</div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-136-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Si <span class="math inline">\(\mu\)</span> creix, desplaça a la dreta l’eix vertical de simetria de la densitat, i amb ell tota la corba.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-137-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Si <span class="math inline">\(\sigma\)</span> creix, la corba s’aplana: en augmentar la desviació típica, els valors són més variats i augmenta la probabilitat que prenguin valors més llunyans de <span class="math inline">\(\mu\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-138-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>El gràfic següent mostra l’efecte combinat:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-139-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Indicarem amb <span class="math inline">\(z_q\)</span> el <strong><span class="math inline">\(q\)</span>-quantil</strong> d’una variable normal estàndard <span class="math inline">\(Z\)</span>. És a dir, <span class="math inline">\(z_q\)</span> és el valor tal que <span class="math inline">\(P(Z\leqslant z_q)=q\)</span>.</p>
<p>A banda del fet que <span class="math inline">\(z_{0.5}=0\)</span> (la mediana de <span class="math inline">\(Z\)</span> és 0), hi ha dos quantils més de la normal estàndard <span class="math inline">\(Z\)</span> que hauríeu de recordar:</p>
<ul>
<li><p><span class="math inline">\(z_{0.95}=1.64\)</span>; és a dir, <span class="math inline">\(P(Z\leqslant 1.64)=0.95\)</span> i per tant <span class="math inline">\(P(Z\leqslant -1.64)=P(Z\geqslant 1.64)=0.05\)</span> (és a dir, <span class="math inline">\(z_{0.05}=-1.64\)</span>) i
<span class="math display">\[
P(-1.64\leqslant Z\leqslant 1.64)=0.9.
\]</span></p></li>
<li><p><span class="math inline">\(z_{0.975}=1.96\)</span>; és a dir, <span class="math inline">\(P(Z\leqslant 1.96)=0.975\)</span> i per tant <span class="math inline">\(P(Z\leqslant -1.96)=P(Z\geqslant 1.96)=0.025\)</span> (és a dir, <span class="math inline">\(z_{0.025}=-1.96\)</span>) i
<span class="math display">\[
P(-1.96\leqslant Z\leqslant 1.96)=0.95.
\]</span></p></li>
</ul>

<div class="rmdmercifulgod">
Molt sovint el valor 1.96 de <span class="math inline">\(z_{0.975}\)</span> s’aproxima per 2. Teniu permís per a fer-ho quan no disposeu de mitjans (R, aplis de mòbil) per a calcular quantils i us considereu incapaços de recordar “1.96”. Però només en aquest cas.
</div>

<div class="rmdrecordau">
Pel que hem comentat fa un moment, la simetria de la normal estàndard implica que <span class="math inline">\(z_{1-q}=-z_{q}\)</span>, perquè si <span class="math inline">\(P(Z\leqslant z_{q})=q\)</span>, aleshores <span class="math inline">\(P(Z\geqslant -z_{q})=q\)</span> i per tant <span class="math inline">\(P(Z\leqslant -z_{q})=1-q\)</span>.
</div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-142-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Una de les propietats de la distribució normal que ens faciliten molt la vida és que <strong>tota combinació lineal de variables aleatòries normals independents és normal</strong>. En concret, tenim els dos resultats següents:</p>

<div class="theorem">
<p><span id="thm:comblinnormals" class="theorem"><strong>Teorema 2.5  </strong></span>Sigui <span class="math inline">\(X\)</span> una variable <span class="math inline">\(N(\mu,\sigma)\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>Per a tots <span class="math inline">\(a,b\in \mathbb{R}\)</span>, <span class="math inline">\(aX+b\)</span> és normal <span class="math inline">\(N(a\mu+b,|a|\cdot\sigma)\)</span>.</p></li>
<li><p>En particular, la <strong>tipificada</strong> de <span class="math inline">\(X\)</span>
<span class="math display">\[
Z=\dfrac{X-\mu}{\sigma}
\]</span>
és normal estàndard.</p>
</div></li>
</ol>
<p>Més en general:</p>

<div class="theorem">
<span id="thm:comblinnormals2" class="theorem"><strong>Teorema 2.6  </strong></span>Si <span class="math inline">\(X_1,\ldots,X_n\)</span> són variables aleatòries normals <strong>independents</strong> i <span class="math inline">\(a_1,\ldots,a_n,b\in \mathbb{R}\)</span>, llavors <span class="math inline">\(a_1X_1+\cdots +a_nX_n+b\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span> amb
<span class="math display">\[
\mu=a_1\mu_1+\cdots +a_n\mu_n+b,\ 
\sigma=\sqrt{a_1^2\sigma^2_1+\cdots +a_n^2\sigma^2_n}
\]</span>
</div>

<div class="rmdnote">
Que tota combinació lineal de variables normals torni a ser del mateix tipus, és a dir, normal, és una propietat molt útil de les variables normals que poques famílies de distribucions comparteixen. Per exemple, si <span class="math inline">\(X\)</span> és una variable binomial <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(p\neq 0\)</span>, la variable <span class="math inline">\(2X\)</span> no és binomial, perquè només pren valors parells, mentre que una variable binomial <span class="math inline">\(B(m,q)\)</span> ha de poder prendre tots els valors entre 0 i <span class="math inline">\(m\)</span>.
</div>
<p>Les probabilitats de la normal tipificada determinen les de la normal original, perquè si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>:
<span class="math display">\[
\begin{array}{rl}
P(a\leqslant X\leqslant b)\!\!\!\!\! &amp; \displaystyle =P\Big( \frac{a-\mu}{\sigma}\leqslant \frac{X-\mu}{\sigma}\leqslant \frac{b-\mu}{\sigma}\Big)\\ &amp; \displaystyle =P\Big(\frac{a-\mu}{\sigma}\leqslant Z\leqslant \frac{b-\mu}{\sigma}\Big)
\end{array}
\]</span>
Això serveix per deduir fórmules o resoldre problemes com el següent, i els vostres pares ho empraven per calcular probabilitats de normals (amb taules de probabilitats de la normal estàndard), però ara és més còmode usar una apli.</p>

<div class="example">
<span id="exm:percentalcades" class="example"><strong>Exemple 2.13  </strong></span>Les alçades de les nordamericanes de 20 anys segueixen una distribució normal. S’ha estimat que un 10% d’elles fan manco de 1.55 m, i un 30.5% fan manco de 1.60 m. Per a quina alçada <span class="math inline">\(h\)</span> es té que un 95% de les nordamericanes de 18 anys fan manco de <span class="math inline">\(h\)</span> metres?
</div>
<p>Diguem <span class="math inline">\(X\)</span> a la variable “Prenc una nord americana de 20 anys i mesur la seva alçada en m”. Sabem que és <span class="math inline">\(N(\mu,\sigma)\)</span>, però desconeixem <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span>.</p>
<p>Ens diuen que
<span class="math display">\[
P(X&lt; 1.55)=0.1,\ P(X&lt; 1.60)=0.305
\]</span>
i amb això volem calcular la <span class="math inline">\(h\)</span> tal que <span class="math inline">\(P(X\leqslant h)=0.95\)</span>, és a dir, el 0.95-quantil de <span class="math inline">\(X\)</span>. El que farem serà, tipificant la <span class="math inline">\(X\)</span>, traduir la informació que ens han donat a quantils d’una normal estàndard <span class="math inline">\(Z\)</span>:
<span class="math display">\[
\begin{array}{l}
\displaystyle  0.1=P(X&lt; 1.55)=P\Big(\frac{X-\mu}{\sigma}&lt;\frac{1.55-\mu}{\sigma}\Big)=P\Big(Z&lt;\frac{1.55-\mu}{\sigma}\Big)\\
\displaystyle  \qquad \Longrightarrow \frac{1.55-\mu}{\sigma}=z_{0.1}\\
\displaystyle 0.305=P(X&lt; 1.6)=P\Big(\frac{X-\mu}{\sigma}&lt;\frac{1.6-\mu}{\sigma}\Big)=P\Big(Z&lt;\frac{1.6-\mu}{\sigma}\Big)\\
\displaystyle  \qquad \Longrightarrow \frac{1.6-\mu}{\sigma}=z_{0.305}
\end{array}
\]</span>
Ara podem calcular aquests dos quantils <span class="math inline">\(z_{0.1}\)</span> i <span class="math inline">\(z_{0.305}\)</span>:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="2-5-sec-normal.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.1</span>)</span></code></pre></div>
<pre><code>## [1] -1.281552</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="2-5-sec-normal.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.305</span>)</span></code></pre></div>
<pre><code>## [1] -0.5100735</code></pre>
<p>Obtenim d’aquesta manera el sistema d’equacions lineals
<span class="math display">\[
\left.
\begin{array}{ll}
1.55-\mu=-1.282\sigma\\
1.6-\mu=-0.51\sigma
\end{array}\right\}
\]</span>
El resolem i obtenim
<span class="math display">\[
\mu=1.633,\ \sigma=0.065
\]</span>
I ara ja podem calcular la <span class="math inline">\(h\)</span> com el 0.95-quantil d’una <span class="math inline">\(N(1.633,0.065)\)</span>:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="2-5-sec-normal.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>,<span class="fl">1.633</span>,<span class="fl">0.065</span>)</span></code></pre></div>
<pre><code>## [1] 1.739915</code></pre>
<p>Concloem que un 95% de les nord americanes de 20 anys fan manco de 1.74 m.</p>
</div>
<div id="intervals-de-referència" class="section level3" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> Intervals de referència</h3>
<p>Un <strong>interval de referència</strong> del Q% per a una variable aleatòria <span class="math inline">\(X\)</span> és un interval <span class="math inline">\([a,b]\)</span> tal que
<span class="math display">\[
P(a\leqslant X\leqslant b)=\frac{Q}{100}.
\]</span>
És a dir, un interval de referència del Q% per a <span class="math inline">\(X\)</span> és un interval que conté els valors de <span class="math inline">\(X\)</span> del Q% dels subjectes de la població.</p>
<p>Per exemple, hem vist en la secció anterior que [-1.64,1.64] i [-1.96,1.96] són intervals de referència del 90% i del 95%, respectivament, per a una variable normal estàndard <span class="math inline">\(Z\)</span>.</p>
<p>Els més comuns són els intervals de referència del 95%, que satisfan que
<span class="math display">\[
P(a\leqslant X\leqslant b)=0.95
\]</span>
i són els, que per exemple, us donen com a valors de referència en les analítiques:</p>
<p><img src="Bioestadistica-II_files/figure-html/analit.png" width="80%" style="display: block; margin: auto;" /></p>

<div class="rmdrecordau">
Quan es parla d’un <strong>interval de referència</strong> sense donar la probabilitat, se sobreentén sempre que és l’interval de referència del 95%.
</div>
<p>Quan <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, aquests intervals de referència es prenen sempre <strong>centrats en la mitjana</strong> <span class="math inline">\(\mu\)</span>, és a dir, de la forma
<span class="math display">\[
[\mu-\text{alguna cosa},\mu+\text{aquesta mateixa cosa}].
\]</span>
Es calculen amb el resultat següent:</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-148" class="theorem"><strong>Teorema 2.7  </strong></span>Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, un interval de referència del Q% per a <span class="math inline">\(X\)</span> és
<span class="math display">\[
[\mu- z_{(1+q)/2}\cdot \sigma, \mu+ z_{(1+q)/2}\cdot \sigma]
\]</span>
on <span class="math inline">\(q=Q/100\)</span> i <span class="math inline">\(z_{(1+q)/2}\)</span> és el <span class="math inline">\((1+q)/2\)</span>-quantil de la normal estàndard <span class="math inline">\(Z\)</span>. Normalment escriurem aquest interval
<span class="math display">\[
\mu\pm z_{(1+q)/2}\cdot \sigma.
\]</span></p>
</div>

<div class="rmdcorbes">
<p>La demostració és un exemple d’ús de la tipificació de la normal:
<span class="math display">\[
\begin{array}{l}
P(\mu-x\leqslant X\leqslant \mu+x)=q\\
\qquad \Longleftrightarrow \displaystyle P\Big(\frac{\mu-x-\mu}{\sigma}\leqslant \frac{X-\mu}{\sigma}\leqslant \frac{\mu+x-\mu}{\sigma}\Big)=q\\
\qquad \Longleftrightarrow \displaystyle P(-x/{\sigma}\leqslant Z\leqslant {x}/{\sigma})=q\\
\qquad \Longleftrightarrow \displaystyle P(Z\leqslant {x}/{\sigma})-P(Z\leqslant -{x}/{\sigma})=q\\
\qquad \Longleftrightarrow \displaystyle P(Z\leqslant {x}/{\sigma})-(1-P(Z\leqslant {x}/{\sigma}))=q\\
\qquad \text{(per la simetria de $f_Z$ al voltant de 0)}\\
\qquad \Longleftrightarrow \displaystyle 2P(Z\leqslant {x}/{\sigma})=q+1\\
\qquad \Longleftrightarrow P(Z\leqslant {x}/{\sigma})=(1+q)/2\\
\qquad \Longleftrightarrow x/\sigma=
z_{(1+q)/2}\\
\qquad \Longleftrightarrow x=z_{(1+q)/2}\cdot \sigma
\end{array}
\]</span></p>
</div>
<p>Si <span class="math inline">\(q=0.95\)</span>, llavors <span class="math inline">\((1+q)/2=0.975\)</span> i <span class="math inline">\(z_{0.975}=1.96\)</span>. Per tant, l’interval de referència del 95% per a una variable <span class="math inline">\(X\)</span> normal <span class="math inline">\(N(\mu,\sigma)\)</span> és
<span class="math display">\[
\mu\pm 1.96\sigma.
\]</span>
I com que aquest 1.96 sovint s’aproxima per 2, l’interval de referència del 95% d’una <span class="math inline">\(N(\mu,\sigma)\)</span> se sol simplificar a
<span class="math display">\[
\mu\pm 2\sigma.
\]</span>
Això diu, bàsicament, que</p>
<blockquote>
<p>Si una població segueix una distribució normal <span class="math inline">\(N(\mu,\sigma)\)</span>, un 95% dels seus individus tenen el seu valor de <span class="math inline">\(X\)</span> a distància com a màxim <span class="math inline">\(2\sigma\)</span> (“a dues sigmes”) de <span class="math inline">\(\mu\)</span>.</p>
</blockquote>

<div class="example">
<p><span id="exm:unnamed-chunk-150" class="example"><strong>Exemple 2.14  </strong></span>Segons l’OMS, les altures (en cm) de les dones europees de 18 anys segueixen una llei <span class="math inline">\(N(163.1,18.53)\)</span>. Quin és l’interval d’altures centrat en la mitjana que conté a la meitat de les europees de 18 anys?</p>
</div>
<p>Fixau-vos que, si diem <span class="math inline">\(X\)</span> a la variable aleatòria “Altura d’una dona europea de 18 anys en cm”, el que volem saber és l’interval centrat en la seva mitjana, 163.1, tal que la probabilitat que l’alçada d’una europea de 18 anys triada a l’atzar pertanyi a aquest interval sigui 0.5. És a dir, l’interval de referència del 50% per a <span class="math inline">\(X\)</span>.</p>
<p>Ens diuen que <span class="math inline">\(X\)</span> és <span class="math inline">\(N(163.1,18.53)\)</span>. Si <span class="math inline">\(q=0.5\)</span>, llavors <span class="math inline">\((1+q)/2=0.75\)</span>. El 0.75-quantil <span class="math inline">\(z_{0.75}\)</span> d’una normal estàndard és</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="2-5-sec-normal.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.75</span>)</span></code></pre></div>
<pre><code>## [1] 0.6744898</code></pre>
<p>Per tant, l’interval de referència demanat és <span class="math inline">\(163.1\pm 0.6745\cdot 18.53\)</span>, és a dir, arrodonint a mm, <span class="math inline">\([150.6, 175.6]\)</span>. Això ens diu que la meitat de les dones europees de 18 anys fan entre 150.6 i 175.6 cm.</p>
<p>El <strong>z-score</strong> d’un valor <span class="math inline">\(x_0\in \mathbb{R}\)</span> respecte d’una distribució <span class="math inline">\(N(\mu,\sigma)\)</span> és
<span class="math display">\[
\frac{x_0-\mu}{\sigma}
\]</span></p>
<p>És a dir, el z-score de <span class="math inline">\(x_0\)</span> és el resultat de “tipificar” <span class="math inline">\(x_0\)</span> en el sentit del Teorema <a href="2-5-sec-normal.html#thm:comblinnormals">2.5</a>.2.</p>
<p>Si la variable poblacional és normal, com més gran és el valor absolut del z-score de <span class="math inline">\(x_0\)</span>, més “rar” és <span class="math inline">\(x_0\)</span>; el signe ens diu si és més gran o més petit que el valor esperat <span class="math inline">\(\mu\)</span>.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-152" class="example"><strong>Exemple 2.15  </strong></span>Recordau que, segons l’OMS, les altures de les dones europees de 18 anys segueixen una llei <span class="math inline">\(N(163.1,18.53)\)</span>. Quin seria el z-score d’una jugadora de bàsquet de 18 anys que fes 191 cm?</p>
</div>
<p>Seria
<span class="math display">\[ 
\frac{191-163.1}{18.53}=1.5
\]</span></p>
<p>Això se sol llegir dient que l’alçada d’aquesta jugadora està <strong>1.5 sigmes per sobre de l’alçada mitjana</strong>.</p>
</div>
<div id="sec:lognormal" class="section level3" number="2.5.4">
<h3><span class="header-section-number">2.5.4</span> Variables log-normals</h3>
<p>Direm que <span class="math inline">\(X\)</span> és una variable <strong>log-normal</strong> quan el seu logaritme neperià <span class="math inline">\(\ln(X)\)</span> és una variable normal. O, si ho preferiu, quan és una variable de la forma <span class="math inline">\(e^Y\)</span> amb <span class="math inline">\(Y\)</span> normal. Moltes concentracions d’enzims o anticossos tenen distribucions aproximadament log-normals.</p>

<div class="rmdnote">
Si <span class="math inline">\(a&gt;1\)</span>, <span class="math inline">\(\log_a(X)=\ln(X)/\ln(a)\)</span> i per tant, pel Teorema <a href="2-5-sec-normal.html#thm:comblinnormals">2.5</a>.1, si <span class="math inline">\(X\)</span> és log-normal, el seu logaritme en qualsevol base <span class="math inline">\(a&gt;1\)</span> és normal.
</div>
<p>La densitat d’una variable log-normal és asimètrica, amb una cua a la dreta, com mostra la Figura <a href="2-5-sec-normal.html#fig:lognorm">2.8</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:lognorm"></span>
<img src="Bioestadistica-II_files/figure-html/lognorm-1.png" alt="Densitat de $e^Z$ amb $Z$ normal estàndard." width="50%" />
<p class="caption">
Figura 2.8: Densitat de <span class="math inline">\(e^Z\)</span> amb <span class="math inline">\(Z\)</span> normal estàndard.
</p>
</div>
<p>Recíprocament, molt sovint una variable la densitat de la qual mostri una pujada ràpida des del 0 a la moda i després una cua a la dreta, satisfà que el seu logaritme segueix una distribució aproximadament normal. Això ens serà útil més endavant.</p>
<p>Amb R, la distribució log-normal és <code>lnorm</code>. Els paràmetres que s’empren per descriure-la són els de la variable normal definida pel seu logaritme:</p>
<ul>
<li><p>La <em>mitjana en escala logarítmica</em> de <span class="math inline">\(X\)</span>: <span class="math inline">\(\mu_{\ln(X)}\)</span></p></li>
<li><p>La <em>desviació típica en escala logarítmica</em> de <span class="math inline">\(X\)</span>: <span class="math inline">\(\sigma_{\ln(X)}\)</span></p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-154" class="example"><strong>Exemple 2.16  </strong></span>La dosi letal <span class="math inline">\(Y\)</span> de la digitalina en ratolins (és la dir, la variable aleatòria que dóna la quantitat de digitalina que cal administrar a un ratolí per matar-lo) té distribució log-normal. Se sap que una injecció de 1cc de digitalina mata un 10% dels ratolins (és a dir, que la probabilitat que una dosi de 1cc o manco mati un ratolí és de 0.1: <span class="math inline">\(P(Y\leqslant 1)=0.1\)</span>) i que una injecció de 2cc mata un 75% dels ratolins (<span class="math inline">\(P(Y\leqslant 2)=0.75\)</span>).</p>
</div>
<p>Volem saber la dosi de digitalina (en cc) que és letal per al 95% dels ratolins. Aquest tipus d’experiments és la base de l’anomenat <strong>mètode probit</strong> per determinar la letalitat de substàncies.</p>
<p>Així doncs, volem calcular el valor <span class="math inline">\(a\)</span> tal que <span class="math inline">\(P(Y\leqslant a)=0.95\)</span>, que no és res més que el 0.95-quantil de <span class="math inline">\(Y\)</span>.</p>
<p>Com que el logaritme és injectiu, <span class="math inline">\(P(Y\leqslant x)=P(\ln(Y)\leqslant \ln(x))\)</span>. Per tant el pla és trobar el 0.95-quantil de <span class="math inline">\(\ln(Y)\)</span>, diguem-li <span class="math inline">\(b\)</span>, i aleshores tendrem <span class="math inline">\(a=e^b\)</span>.</p>
<p>Per simplificar, diguem <span class="math inline">\(X\)</span> a <span class="math inline">\(\ln(Y)\)</span>. Sabem que <span class="math inline">\(X\)</span> és normal, per tant només ens cal saber la seva <span class="math inline">\(\mu\)</span> i la seva <span class="math inline">\(\sigma\)</span> i podrem calcular el seu 0.95-quantil.</p>
<p>El que sabem és que
<span class="math display">\[
\begin{array}{l}
0.1=P(Y\leqslant 1)=P(X\leqslant \ln(1))=P(X\leqslant 0)\\
0.75=P(Y\leqslant 2)=P(X\leqslant \ln(2))
\end{array}
\]</span>
Com podem determinar la <span class="math inline">\(\mu\)</span> i la <span class="math inline">\(\sigma\)</span> de <span class="math inline">\(X\)</span> a partir d’aquests dos valors? Ja ens hem trobat en una situació semblant a l’Exemple <a href="2-5-sec-normal.html#exm:percentalcades">2.13</a>. El que fem és traduir aquesta informació en termes de quantils de la normal estàndard.</p>
<p><span class="math display">\[
\begin{array}{l}
\displaystyle 0.1=P(X\leqslant 0)=P\Big(\frac{X-\mu}{\sigma}\leqslant \frac{-\mu}{\sigma}\Big)=P\Big(Z\leqslant -\frac{\mu}{\sigma}\Big)\\
\displaystyle\qquad \Longrightarrow -\frac{\mu}{\sigma}=z_{0.1}=\texttt{qnorm(0.1)}=-1.2816\\
\displaystyle 0.75=P(X\leqslant \ln(2))=P\Big(\frac{X-\mu}{\sigma}\leqslant \frac{\ln(2)-\mu}{\sigma}\Big)=P\Big(Z\leqslant \frac{\ln(2)-\mu}{\sigma}\Big)\\
\displaystyle\qquad \Longrightarrow \frac{\ln(2)-\mu}{\sigma}=z_{0.75}=\texttt{qnorm(0.75)}=0.6745
\end{array}
\]</span>
Obtenim el sistema d’equacions
<span class="math display">\[
\left.
\begin{array}{l}
\mu=1.2816\sigma\\
\ln(2)-\mu=0.6745\sigma
\end{array}
\right\}
\]</span>
i resolent-lo obtenim
<span class="math display">\[
\mu=0.4541,\quad \sigma=0.3544
\]</span></p>
<p>Ara podem calcular el 0.95-quantil de <span class="math inline">\(X\)</span>:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="2-5-sec-normal.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>,<span class="fl">0.4541</span>,<span class="fl">0.3544</span>)</span></code></pre></div>
<pre><code>## [1] 1.037036</code></pre>
<p>Per tant <span class="math inline">\(P(X\leqslant 1.037)=0.95\)</span>. D’aquí deduïm que <span class="math inline">\(P(Y\leqslant e^{1.037})=0.95\)</span>. Com que <span class="math inline">\(e^{1.037}=2.82\)</span>, concloem que 2.82 cc de digitalina són suficients per matar el 95% dels ratolins.</p>
<p>Ho podem comprovar (amb R, no escabetxant ratolins, malpensats!):</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="2-5-sec-normal.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plnorm</span>(<span class="fl">2.82</span>,<span class="fl">0.4541</span>,<span class="fl">0.3544</span>)</span></code></pre></div>
<pre><code>## [1] 0.9499129</code></pre>
</div>
</div>
<p style="text-align: center;">
<a href="2-4-variables-aleatòries-contínues.html"><button class="btn btn-default">Previous</button></a>
<a href="2-6-test-de-la-lliçó-2.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
