<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tema 2 Variables aleatòries | Matemàtiques II</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Tema 2 Variables aleatòries | Matemàtiques II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 2 Variables aleatòries | Matemàtiques II" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2021-02-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-conceptes.html"/>
<link rel="next" href="estimació-puntual.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="chapter" data-level="1" data-path="chap-conceptes.html"><a href="chap-conceptes.html"><i class="fa fa-check"></i><b>1</b> Alguns conceptes bàsics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chap-conceptes.html"><a href="chap-conceptes.html#unitat-dobservació"><i class="fa fa-check"></i><b>1.1</b> Unitat d’observació</a></li>
<li class="chapter" data-level="1.2" data-path="chap-conceptes.html"><a href="chap-conceptes.html#població"><i class="fa fa-check"></i><b>1.2</b> Població</a></li>
<li class="chapter" data-level="1.3" data-path="chap-conceptes.html"><a href="chap-conceptes.html#variable-aleatòria"><i class="fa fa-check"></i><b>1.3</b> Variable aleatòria</a></li>
<li class="chapter" data-level="1.4" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostra"><i class="fa fa-check"></i><b>1.4</b> Mostra</a></li>
<li class="chapter" data-level="1.5" data-path="chap-conceptes.html"><a href="chap-conceptes.html#sec:mostreig"><i class="fa fa-check"></i><b>1.5</b> Mostreig aleatori</a></li>
<li class="chapter" data-level="1.6" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostres-de-conveniència"><i class="fa fa-check"></i><b>1.6</b> Mostres de conveniència</a></li>
<li class="chapter" data-level="1.7" data-path="chap-conceptes.html"><a href="chap-conceptes.html#test-de-la-lliçó-2"><i class="fa fa-check"></i><b>1.7</b> Test de la lliçó 2</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-varal.html"><a href="chap-varal.html"><i class="fa fa-check"></i><b>2</b> Variables aleatòries</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap-varal.html"><a href="chap-varal.html#generalitats-sobre-variables-aleatòries"><i class="fa fa-check"></i><b>2.1</b> Generalitats sobre variables aleatòries</a></li>
<li class="chapter" data-level="2.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-discretes"><i class="fa fa-check"></i><b>2.2</b> Variables aleatòries discretes</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució"><i class="fa fa-check"></i><b>2.2.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="2.2.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança"><i class="fa fa-check"></i><b>2.2.2</b> Esperança</a></li>
<li class="chapter" data-level="2.2.3" data-path="chap-varal.html"><a href="chap-varal.html#variància-i-desviació-típica"><i class="fa fa-check"></i><b>2.2.3</b> Variància i desviació típica</a></li>
<li class="chapter" data-level="2.2.4" data-path="chap-varal.html"><a href="chap-varal.html#quantils"><i class="fa fa-check"></i><b>2.2.4</b> Quantils</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chap-varal.html"><a href="chap-varal.html#famílies-importants-de-variables-aleatòries-discretes"><i class="fa fa-check"></i><b>2.3</b> Famílies importants de variables aleatòries discretes</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-binomials"><i class="fa fa-check"></i><b>2.3.1</b> Variables aleatòries binomials</a></li>
<li class="chapter" data-level="2.3.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-hipergeomètriques"><i class="fa fa-check"></i><b>2.3.2</b> Variables aleatòries hipergeomètriques</a></li>
<li class="chapter" data-level="2.3.3" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-de-poisson"><i class="fa fa-check"></i><b>2.3.3</b> Variables aleatòries de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-contínues"><i class="fa fa-check"></i><b>2.4</b> Variables aleatòries contínues</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució-1"><i class="fa fa-check"></i><b>2.4.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="2.4.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança-variància-quantils"><i class="fa fa-check"></i><b>2.4.2</b> Esperança, variància, quantils…</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chap-varal.html"><a href="chap-varal.html#sec:normal"><i class="fa fa-check"></i><b>2.5</b> Variables aleatòries normals</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i><b>2.5.1</b> Amb R</a></li>
<li class="chapter" data-level="2.5.2" data-path="chap-varal.html"><a href="chap-varal.html#propietats-bàsiques"><i class="fa fa-check"></i><b>2.5.2</b> Propietats bàsiques</a></li>
<li class="chapter" data-level="2.5.3" data-path="chap-varal.html"><a href="chap-varal.html#intervals-de-referència"><i class="fa fa-check"></i><b>2.5.3</b> Intervals de referència</a></li>
<li class="chapter" data-level="2.5.4" data-path="chap-varal.html"><a href="chap-varal.html#variables-log-normals"><i class="fa fa-check"></i><b>2.5.4</b> Variables log-normals</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="chap-varal.html"><a href="chap-varal.html#test-de-la-lliçó-1"><i class="fa fa-check"></i><b>2.6</b> Test de la lliçó 1</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estimació-puntual.html"><a href="estimació-puntual.html"><i class="fa fa-check"></i><b>3</b> Estimació puntual</a>
<ul>
<li class="chapter" data-level="3.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#definicions-bàsiques"><i class="fa fa-check"></i><b>3.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="3.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#mitjana-mostral"><i class="fa fa-check"></i><b>3.2</b> Mitjana mostral</a></li>
<li class="chapter" data-level="3.3" data-path="estimació-puntual.html"><a href="estimació-puntual.html#proporció-mostral"><i class="fa fa-check"></i><b>3.3</b> Proporció mostral</a></li>
<li class="chapter" data-level="3.4" data-path="estimació-puntual.html"><a href="estimació-puntual.html#variància-mostral"><i class="fa fa-check"></i><b>3.4</b> Variància mostral</a></li>
<li class="chapter" data-level="3.5" data-path="estimació-puntual.html"><a href="estimació-puntual.html#la-distribució-t-de-student"><i class="fa fa-check"></i><b>3.5</b> La distribució t de Student</a></li>
<li class="chapter" data-level="3.6" data-path="estimació-puntual.html"><a href="estimació-puntual.html#bons-estimadors"><i class="fa fa-check"></i><b>3.6</b> “Bons” estimadors</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-no-esbiaixats"><i class="fa fa-check"></i><b>3.6.1</b> Estimadors no esbiaixats</a></li>
<li class="chapter" data-level="3.6.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-eficients"><i class="fa fa-check"></i><b>3.6.2</b> Estimadors eficients</a></li>
<li class="chapter" data-level="3.6.3" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-màxim-versemblants"><i class="fa fa-check"></i><b>3.6.3</b> Estimadors màxim versemblants</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="estimació-puntual.html"><a href="estimació-puntual.html#sec:pobl"><i class="fa fa-check"></i><b>3.7</b> Estimació de poblacions</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimació-de-poblacions-numerades"><i class="fa fa-check"></i><b>3.7.1</b> Estimació de poblacions numerades</a></li>
<li class="chapter" data-level="3.7.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#marca-recaptura"><i class="fa fa-check"></i><b>3.7.2</b> Marca-recaptura</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="estimació-puntual.html"><a href="estimació-puntual.html#test-de-la-lliçó-3"><i class="fa fa-check"></i><b>3.8</b> Test de la lliçó 3</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html"><i class="fa fa-check"></i><b>4</b> Intervals de confiança</a>
<ul>
<li class="chapter" data-level="4.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#definicions-bàsiques"><i class="fa fa-check"></i><b>4.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="4.2" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#exemple-interval-de-confiança-del-95-per-a-la-mitjana-duna-variable-aleatòria-normal"><i class="fa fa-check"></i><b>4.2</b> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</a></li>
<li class="chapter" data-level="4.3" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#interval-de-confiança-per-a-la-mitjana-basat-en-la-t-de-student"><i class="fa fa-check"></i><b>4.3</b> Interval de confiança per a la mitjana basat en la t de Student</a>
<ul>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#la-fórmula"><i class="fa fa-check"></i>La fórmula</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#algunes-consideracions"><i class="fa fa-check"></i>Algunes consideracions</a></li>
<li class="chapter" data-level="" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i>Amb R</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#càlcul-de-la-mida-de-la-mostra-per-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#intervals-de-confiança-per-a-proporcions"><i class="fa fa-check"></i><b>4.4</b> Intervals de confiança per a proporcions</a>
<ul>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-exacte-de-clopper-pearson"><i class="fa fa-check"></i>Mètode “exacte” de Clopper-Pearson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-de-wilson"><i class="fa fa-check"></i>Mètode de Wilson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-de-laplace"><i class="fa fa-check"></i>Mètode de Laplace</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#més-exemples"><i class="fa fa-check"></i>Més exemples</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#càlcul-de-la-mida-de-la-mostra-per-a-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per a fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#intervals-de-confiança-per-a-la-variància-duna-variable-normal"><i class="fa fa-check"></i><b>4.5</b> Intervals de confiança per a la variància d’una variable normal</a></li>
<li class="chapter" data-level="4.6" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#poblacions-finites"><i class="fa fa-check"></i><b>4.6</b> “Poblacions finites”</a></li>
<li class="chapter" data-level="4.7" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#test-de-la-lliçó-4"><i class="fa fa-check"></i><b>4.7</b> Test de la lliçó 4</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html"><i class="fa fa-check"></i><b>5</b> Contrastos d’hipòtesis: Generalitats</a>
<ul>
<li class="chapter" data-level="5.1" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#hipòtesis-nulla-i-alternativa"><i class="fa fa-check"></i><b>5.1</b> Hipòtesis nul·la i alternativa</a></li>
<li class="chapter" data-level="5.2" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#sec:moneda"><i class="fa fa-check"></i><b>5.2</b> Un exemple</a></li>
<li class="chapter" data-level="5.3" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#sec:pval"><i class="fa fa-check"></i><b>5.3</b> El p-valor</a></li>
<li class="chapter" data-level="5.4" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#tipus-derrors"><i class="fa fa-check"></i><b>5.4</b> Tipus d’errors</a></li>
<li class="chapter" data-level="5.5" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#sec:exttest"><i class="fa fa-check"></i><b>5.5</b> Exemple: El test t</a></li>
<li class="chapter" data-level="5.6" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#recapitulació"><i class="fa fa-check"></i><b>5.6</b> Recapitulació</a>
<ul>
<li class="chapter" data-level="" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#interval-de-confiança-dun-contrast"><i class="fa fa-check"></i>Interval de confiança d’un contrast</a></li>
<li class="chapter" data-level="" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#la-potència"><i class="fa fa-check"></i>La potència</a></li>
<li class="chapter" data-level="" data-path="contrastos-dhipòtesis-generalitats.html"><a href="contrastos-dhipòtesis-generalitats.html#el-risc-de-positiu-fals-opcional"><i class="fa fa-check"></i>El risc de positiu fals (Opcional)</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:varal" class="section level1" number="2">
<h1><span class="header-section-number">Tema 2</span> Variables aleatòries</h1>
<div id="generalitats-sobre-variables-aleatòries" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Generalitats sobre variables aleatòries</h2>
<p>Una <strong>variable aleatòria</strong> definida sobre una població <span class="math inline">\(\Omega\)</span> és simplement una funció
<span class="math display">\[
X: \Omega\to \mathbb{R}
\]</span>
que assigna a cada subjecte de <span class="math inline">\(\Omega\)</span> un nombre real. La idea intuïtiva que hi ha al darrera d’aquesta definició és que una variable aleatòria <strong>mesura</strong> una característica dels subjectes de <span class="math inline">\(\Omega\)</span> que varia a l’atzar d’un subjecte a un altre. Per exemple:</p>
<ul>
<li><p>Prenem una persona d’una població i mesuram el seu nivell de colesterol, o la seva alçada, o el seu nombre de fills… En aquest cas, <span class="math inline">\(\Omega\)</span> és la població sota estudi, de la qual prenem la persona que mesuram.</p></li>
<li><p>Llançam una moneda equilibrada 3 vegades i comptam les cares que obtenim. En aquest cas, <span class="math inline">\(\Omega\)</span> és la població formada per totes les seqüències de 3 llançaments d’una moneda equilibrada passades, presents i futures.</p></li>
</ul>
<p>El que més ens interessarà d’una variable aleatòria són les probabilitats dels esdeveniments que defineix. I quin tipus d’esdeveniments són els que ens interessen quan mesuram característiques numèriques? Doncs bàsicament esdeveniments definits mitjançant igualtats i desigualtats. Per exemple, si <span class="math inline">\(X\)</span> és la variable aleatòria “Prenem una persona i mesuram el seu nivell de colesterol en plasma (en mg/dl)”, ens poden interessar esdeveniments de l’estil de:</p>
<ul>
<li><p>El conjunt de les persones amb nivell de colesterol entre 200 i 240. L’indicarem amb
<span class="math display">\[
200\leqslant X\leqslant 240
\]</span></p></li>
<li><p>El conjunt de les persones amb nivell de colesterol més petit o igual que 200:
<span class="math display">\[
X\leqslant 200
\]</span></p></li>
<li><p>El conjunt de les persones amb nivell de colesterol més gran que 180:
<span class="math display">\[
X&gt;180
\]</span></p></li>
<li><p>El conjunt de les persones amb nivell de colesterol exactament 180:
<span class="math display">\[
X=180
\]</span></p></li>
<li><p>Etc.</p></li>
</ul>
<p>Com dèiem, el que ens interessarà d’aquests esdeveniments serà la seva probabilitat, i llavors emprarem notacions de l’estil de les següents:</p>
<ul>
<li><p><span class="math inline">\(P(200\leqslant X\leqslant 240)\)</span>. Això indica la probabilitat que una persona tengui el nivell de colesterol entre 200 i 240. Per abreujar, ho llegirem la “probabilitat que <span class="math inline">\(X\)</span> estigui entre 200 i 240” i representa la <strong>proporció</strong> de persones (de la població <span class="math inline">\(\Omega\)</span> on hàgim definit la variable <span class="math inline">\(X\)</span>) amb nivell de colesterol entre 200 i 240.</p></li>
<li><p><span class="math inline">\(P(X\leqslant 200)\)</span>. Això indica la probabilitat que una persona tengui el nivell de colesterol més petit o igual que 200 (per abreujar, la probabilitat que “<span class="math inline">\(X\)</span> sigui més petit o igual que 200”). És a dir, la proporció de persones amb nivell de colesterol més petit o igual que 200.</p></li>
<li><p>Etc.</p></li>
</ul>
<p>En aquest context, indicarem normalment la <strong>unió</strong> amb una <strong>o</strong> i la <strong>intersecció</strong> amb una <strong>coma</strong>. Per exemple, si <span class="math inline">\(X\)</span> és la variable aleatòria “Llançam una moneda 6 vegades i comptam les cares”:</p>
<ul>
<li><p><span class="math inline">\(P(X\leqslant 2\text{ o }X\geqslant 5)\)</span>: Probabilitat de treure com a màxim 2 cares o com a mínim 5.</p></li>
<li><p><span class="math inline">\(P(2\leqslant X, X&lt; 5)\)</span>: Probabilitat de treure un nombre de cares que sigui més gran o igual que 2 i més petit que 5; és a dir, <span class="math inline">\(P(2\leqslant X&lt; 5)\)</span>.</p></li>
</ul>
<p>Dues variables aleatòries <span class="math inline">\(X,Y\)</span> són <strong>independents</strong> quan, per a tots els parells de valors <span class="math inline">\(a,b\in \mathbb{R}\)</span>, els esdeveniments
<span class="math display">\[
X\leqslant a, Y\leqslant b
\]</span>
són independents. És a dir, quan el valor que pren <span class="math inline">\(X\)</span> sobre un subjecte no afecta per res el valor que hi pren <span class="math inline">\(Y\)</span>, i viceversa.</p>
<p>Per exemple, si prenem una persona i:</p>
<ul>
<li><p><span class="math inline">\(X\)</span>: li demanam que llanci una moneda 3 vegades i comptam les cares</p></li>
<li><p><span class="math inline">\(Y\)</span>: mesuram el seu nivell de colesterol en plasma (en mg/dl)</p></li>
</ul>
<p>(segurament) <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són independents.</p>

<div class="rmdrecordau">
Recordau que els esdeveniments <span class="math inline">\(X\leqslant a\)</span> i <span class="math inline">\(Y\leqslant b\)</span> són independents quan satisfan les tres condicions equivalents següents:
<span class="math display">\[
\begin{array}{l}
P(X\leqslant a|Y\leqslant b)=P(X\leqslant a)\\
P(Y\leqslant b|X\leqslant a)=P(Y\leqslant b)\\
P(X\leqslant a, Y\leqslant b)=P(X\leqslant a)\cdot P(Y\leqslant b)
\end{array}
\]</span>
</div>
<p>Més en general, unes variables aleatòries <span class="math inline">\(X_1,X_2,\ldots,X_n\)</span> són <strong>independents</strong> quan, per a tots <span class="math inline">\(a_1,a_2,\ldots,a_n\in \mathbb{R}\)</span>, els esdeveniments
<span class="math display">\[
X_1\leqslant a_1, X_2\leqslant a_2,\ldots, X_n\leqslant a_n
\]</span>
són independents. És a dir, quan el valor que pren una d’aquestes variables sobre un subjecte no afecta per res els valors que hi prenen les altres.</p>
</div>
<div id="variables-aleatòries-discretes" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Variables aleatòries discretes</h2>
<p>Una variable aleatòria és <strong>discreta</strong> quan els seus possibles valors són dades quantitatives discretes. Per exemple,</p>
<ul>
<li>Nombre de cares en 3 llançaments d’una moneda</li>
<li>Nombre de fills d’una dona</li>
<li>Nombre de casos nous de COVID-19 en un dia a Mallorca</li>
</ul>
<div id="densitat-i-distribució" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Densitat i distribució</h3>
<p>Sigui <span class="math inline">\(X: \Omega\to \mathbb{R}\)</span> una <strong>variable aleatòria discreta</strong>.</p>
<ul>
<li><p>El seu <strong>domini</strong> <span class="math inline">\(D_X\)</span> és el conjunt dels valors que pot prendre: més concretament, és el conjunt dels <span class="math inline">\(x\in \mathbb{R}\)</span> tals que <span class="math inline">\(P(X=x)&gt;0\)</span>.</p></li>
<li><p>La seva <strong>funció de densitat</strong> és la funció <span class="math inline">\(f_X:\mathbb{R}\to [0,1]\)</span> que assigna a cada <span class="math inline">\(x\in \mathbb{R}\)</span> la probabilitat que <span class="math inline">\(X\)</span> valgui <span class="math inline">\(x\)</span>:
<span class="math display">\[ 
f_X(x)=P(X=x)
\]</span>
És a dir, <span class="math inline">\(f_X(x)\)</span> és la proporció de subjectes de la població en els quals <span class="math inline">\(X\)</span> val <span class="math inline">\(x\)</span>.</p></li>
<li><p>La seva <strong>funció de distribució</strong> és la funció <span class="math inline">\(F_X:\mathbb{R}\to [0,1]\)</span> que assigna a cada <span class="math inline">\(x\in \mathbb{R}\)</span> la probabilitat que <span class="math inline">\(X\)</span> sigui més petit o igual que <span class="math inline">\(x\)</span>:
<span class="math display">\[
F_X(x)=P(X\leqslant x)
\]</span>
És a dir, <span class="math inline">\(F_X(x)\)</span> és la proporció de subjectes de la població en els quals <span class="math inline">\(X\)</span> pren un valor <span class="math inline">\(\leqslant x\)</span>.</p>
<p>A la funció de distribució també se li sol dir <strong>funció de probabilitat acumulada</strong> per posar èmfasi en el fet que <span class="math inline">\(F_X(x)\)</span> mesura la “freqüència relativa acumulada” de <span class="math inline">\(x\)</span> en el total de la població.</p></li>
</ul>

<div class="example">
<p><span id="exm:cars" class="example"><strong>Exemple 2.1  </strong></span>Sigui <span class="math inline">\(X\)</span> la variable aleatòria “Llançam 3 vegades una moneda equilibrada i comptam les cares”. Aleshores:</p>
</div>
<ul>
<li><p>El seu <strong>domini</strong> és el conjunt dels seus possibles valors: <span class="math inline">\(D_X=\{0,1,2,3\}\)</span>.</p></li>
<li><p>La seva <strong>funció de densitat</strong> és definida per <span class="math inline">\(f_X(x)=P(X=x)\)</span>:</p>
<ul>
<li><span class="math inline">\(f_X(0)=P(X=0)=1/8\)</span> (la probabilitat de treure 0 cares en 3 llançaments)</li>
<li><span class="math inline">\(f_X(1)=P(X=1)=3/8\)</span> (la probabilitat de treure 1 cara en 3 llançaments)</li>
<li><span class="math inline">\(f_X(2)=P(X=2)=3/8\)</span> (la probabilitat de treure 2 cares en 3 llançaments)</li>
<li><span class="math inline">\(f_X(3)=P(X=3)=1/8\)</span> (la probabilitat de treure 3 cares en 3 llançaments)</li>
<li><span class="math inline">\(f_X(x)=P(X=x)=0\)</span> per a qualsevol altre valor de <span class="math inline">\(x\)</span> (si <span class="math inline">\(x\notin\{0,1,2,3\}\)</span>, la probabilitat de treure <span class="math inline">\(x\)</span> cares en 3 llançaments és 0)</li>
</ul>
<p>En resum, la funció de densitat de <span class="math inline">\(X\)</span> és
<span class="math display">\[
f_X(x) =\left\{
\begin{array}{ll}
1/8 &amp; \text{ si $x=0$}\\ 
3/8 &amp; \text{ si $x=1$}\\ 
3/8 &amp; \text{ si $x=2$}\\ 
1/8 &amp; \text{ si $x=3$}\\
0 &amp; \text{ si $x\neq 0,1,2,3$}
\end{array}
\right.
\]</span></p></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:densicares"></span>
<img src="Bioestadistica-II_files/figure-html/densicares-1.png" alt="Funció de densitat de la variable aleatòria que compta el nombre de cares en 3 llançaments" width="60%" />
<p class="caption">
Figura 2.1: Funció de densitat de la variable aleatòria que compta el nombre de cares en 3 llançaments
</p>
</div>

<div class="rmdnote">
Si <span class="math inline">\(X\)</span> és una variable aleatòria discreta, <span class="math inline">\(P(X\in A)=0\)</span> per a qualsevol subconjunt <span class="math inline">\(A\)</span> disjunt amb <span class="math inline">\(D_X\)</span>, perquè, per la definició del domini <span class="math inline">\(D_X\)</span>, <span class="math inline">\(X\)</span> no pot prendre cap valor fora de <span class="math inline">\(D_X\)</span>. Per exemple, quina és la probabilitat de treure entre 2.5 i 2.7 cares en llançar 3 vegades una moneda? 0. I la de treure <span class="math inline">\(\pi\)</span> cares? 0 un altre cop.
</div>
<ul>
<li><p>Vegem ara la seva <strong>funció de distribució</strong> <span class="math inline">\(F_X\)</span>. Recordau que <span class="math inline">\(F_X(x)=P(X\leqslant x)\)</span> i que la nostra variable només pot prendre els valors 0, 1, 2 i 3.</p>
<ul>
<li><p>Si <span class="math inline">\(x&lt;0\)</span>, <span class="math inline">\(F_X(x)=P(X\leqslant x)=0\)</span> perquè <span class="math inline">\(X\)</span> no pot prendre cap valor estrictament negatiu.</p></li>
<li><p>Si <span class="math inline">\(0\leqslant x&lt;1\)</span>, <span class="math inline">\(F_X(x)=P(X\leqslant x)=P(X=0)=f_X(0)=1/8\)</span>, perquè si <span class="math inline">\(0\leqslant x&lt;1\)</span>, l’únic valor <span class="math inline">\(\leqslant x\)</span> que pot prendre <span class="math inline">\(X\)</span> és el 0.</p></li>
<li><p>Si <span class="math inline">\(1\leqslant x&lt;2\)</span>, <span class="math inline">\(F_X(x)=P(X\leqslant x)=P(X=0\text{ o }X=1)\)</span> <span class="math inline">\(=f_X(0)+f_X(1)=4/8=1/2\)</span>, perquè si <span class="math inline">\(1\leqslant x&lt;2\)</span>, els únics valors <span class="math inline">\(\leqslant x\)</span> que pot prendre <span class="math inline">\(X\)</span> són 0 i 1.</p></li>
<li><p>Si <span class="math inline">\(2\leqslant x&lt;3\)</span>, <span class="math inline">\(F_X(x)=P(X\leqslant x)=P(X=0\text{ o }X=1\text{ o }X=2)\)</span> <span class="math inline">\(=f_X(0)+f_X(1)+f_X(2)=7/8\)</span>, perquè si <span class="math inline">\(2\leqslant x&lt;3\)</span>, els únics valors <span class="math inline">\(\leqslant x\)</span> que pot prendre <span class="math inline">\(X\)</span> són 0, 1 i 2.</p></li>
<li><p>Si <span class="math inline">\(3\leqslant x\)</span>, <span class="math inline">\(F_X(x)=P(X\leqslant x)=1\)</span>, perquè si <span class="math inline">\(x\geqslant 3\)</span>, segur que obtenim un nombre de cares <span class="math inline">\(\leqslant x\)</span>.</p></li>
</ul>
<p>Per tant, la funció <span class="math inline">\(F_X\)</span> és la funció
<span class="math display">\[
F_X(x) =\left\{
\begin{array}{ll}
0 &amp; \text{ si $x&lt;0$}\\
1/8 &amp; \text{ si $0\leqslant x&lt; 1$}\\ 
4/8 &amp; \text{ si $1\leqslant x&lt; 2$}\\ 
7/8 &amp; \text{ si $2\leqslant x&lt; 3$}\\ 
1 &amp; \text{ si $3\leqslant x$}
\end{array}
\right.
\]</span>
El seu gràfic és el següent:</p></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:districares"></span>
<img src="Bioestadistica-II_files/figure-html/districares-1.png" alt="Funció de distribució de la variable aleatòria que compta el nombre de cares en 3 llançaments" width="60%" />
<p class="caption">
Figura 2.2: Funció de distribució de la variable aleatòria que compta el nombre de cares en 3 llançaments
</p>
</div>
<p>Observau en aquest gràfic que aquesta funció de distribució <span class="math inline">\(F_X\)</span> és creixent i escalonada. Això és general. Si <span class="math inline">\(X\)</span> és una variable aleatòria discreta:</p>
<ul>
<li><p><span class="math inline">\(F_X\)</span> és una funció <strong>escalonada</strong>, amb bots en els valors de <span class="math inline">\(D_X\)</span>, que són els únics amb probabilitat estrictament més gran que 0 i per tant els únics que “sumen” probabilitat. Més en concret:</p>
<ul>
<li><p>Si <span class="math inline">\(x_0,y_0\in D_X\)</span> i <span class="math inline">\(x_0&lt;y_0\)</span>, llavors <span class="math inline">\(F_X(x_0)&lt; F_X(y_0)\)</span>, perquè, com que <span class="math inline">\(P(X=y_0)&gt;0\)</span>,
<span class="math display">\[
\begin{array}{rl}
F_X(x_0)\!\!\!\!\! &amp; =P(X\leqslant x_0)&lt;P(X\leqslant x_0)+P(X=y_0)\\
&amp; =P(X\leqslant x_0\text{ o }X=y_0)\leqslant P(X\leqslant y_0)=F_X(y_0)
\end{array}
\]</span></p></li>
<li><p>Si <span class="math inline">\(x_0\in D_X\)</span> i dins <span class="math inline">\((x_0,x]\)</span> no hi ha cap element de <span class="math inline">\(D_X\)</span>, aleshores <span class="math inline">\(F_X(x_0)=F_X(x)\)</span>, perquè
<span class="math display">\[
\begin{array}{rl}
F_X(x)\!\!\!\!\! &amp; =P(X\leqslant x)=P(X\leqslant x_0)+P(x_0&lt;X\leqslant x)\\
&amp; =P(X\leqslant x_0)+0= P(X\leqslant x_0)=F_X(x_0)
\end{array}
\]</span>
perquè, com que <span class="math inline">\((x_0,x]\cap D_X=\emptyset\)</span>, <span class="math inline">\(P(x_0&lt;X\leqslant x)=0\)</span>.</p></li>
<li><p>Si <span class="math inline">\(x_0\in D_X\)</span>, <span class="math inline">\(P(X&lt;x_0)&lt;P(X\leqslant x_0)\)</span>, perquè
<span class="math display">\[
P(X\leqslant x_0)=P(X&lt;x_0)+P(X=x_0)&gt;P(X&lt;x_0)
\]</span></p></li>
</ul></li>
<li><p><span class="math inline">\(F_X\)</span> és <strong>creixent</strong>, perquè si <span class="math inline">\(x\leqslant y\)</span>, tots els subjectes de <span class="math inline">\(X\leqslant x\)</span> també pertanyen a <span class="math inline">\(X\leqslant y\)</span>, i per tant
<span class="math display">\[
P(X\leqslant x)\leqslant P(X\leqslant y).
\]</span></p></li>
<li><p>Com que els valors que pren <span class="math inline">\(F_X\)</span> són probabilitats, no poden ser ni més petits que 0 ni més grans que 1.</p></li>
</ul>
<p>El coneixement de <span class="math inline">\(f_X\)</span>, més les regles del càlcul de probabilitats, permet calcular la probabilitat de qualsevol esdeveniment relacionat amb <span class="math inline">\(X\)</span>:
<span class="math display">\[
P(X\in A) =\sum_{x\in A} P(X=x) = \sum_{x\in A} f_X(x)
\]</span>
En particular
<span class="math display">\[
F_X(x_0)=P(X\leqslant x_0)=\sum_{x\leqslant x_0} f_X(x)
\]</span></p>
<p>La <strong>moda</strong> d’una variable aleatòria discreta <span class="math inline">\(X\)</span> és el valor (o els valors) <span class="math inline">\(x_0\)</span> tal que <span class="math inline">\(f_X(x_0)=P(X=x_0)\)</span> és màxim. Per tant, la moda és el valor de <span class="math inline">\(X\)</span> <strong>més probable</strong> o <strong>més freqüent</strong> en la població. Per exemple, per a la nostra variable aleatòria que compta el nombre de cares en 3 llançaments d’una moneda equilibrada, la moda són els valors 1 i 2.</p>
<p>Una variable aleatòria discreta <span class="math inline">\(X\)</span> és <strong>uniforme</strong> quan el seu domini <span class="math inline">\(D_X\)</span> és finit i tots els seus elements tenen la mateixa probabilitat. És a dir, si <span class="math inline">\(D_X\)</span> té <span class="math inline">\(m\)</span> elements, aleshores <span class="math inline">\(P(X=x)=1/m\)</span> per a cada <span class="math inline">\(x\in D_X\)</span>. Per exemple, el resultat de llançar un dau equilibrat és una variable aleatòria discreta. Com que tots els resultats del domini tenen la mateixa probabilitat, tots en són la moda (o cap no ho és, depèn de si veieu el tassó mig ple o mig buit).</p>

<div class="rmdexercici">
<p>Considerau la variable aleatòria <span class="math inline">\(X\)</span> “Llançam una moneda equilibrada tantes vegades com sigui necessari fins que surti una cara per primera vegada, i comptam quantes vegades l’hem haguda de llançar”.</p>
<ol style="list-style-type: decimal">
<li>Quin és el seu domini?</li>
<li>Quina és la seva funció de densitat?</li>
<li>Quina és la seva moda? Què significa?</li>
<li>Quina és la seva funció de distribució? (Indicació: Calculau primer <span class="math inline">\(P(X&gt;x)\)</span>, tenint en compte que <span class="math inline">\(X&gt;x\)</span> significa que en els primer <span class="math inline">\(x\)</span> llançaments ha sortit creu, i per això hem hagut de llançar la moneda més de <span class="math inline">\(x\)</span> vegades per obtenir una cara.)</li>
</ol>
</div>
</div>
<div id="esperança" class="section level3" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Esperança</h3>
<p>Quan prenem una mostra d’una variable aleatòria <span class="math inline">\(X\)</span> definida sobre una població, podem calcular la mitjana i la desviació típica dels seus valors a fi i efecte d’obtenir una idea de quin és el valor central de la mostra i si els seus valors estan tots molt a prop d’aquest valor central o no. Naturalment, també ens podem preguntar per aquesta mena d’informació per al total de la població: Quin és el “valor mitjà” de <span class="math inline">\(X\)</span> sobre tota la població? Aquesta variable, pren valors molt dispersos, o més aviat els pren concentrats al voltant del seu valor mitjà? La primera pregunta la responem amb la <strong>mitjana</strong>, o <strong>esperança</strong>, de <span class="math inline">\(X\)</span>, i la segona amb la seva <strong>variància</strong> i la seva <strong>desviació típica</strong>. Comencem amb la primera.</p>
<p>La <strong>mitjana</strong>, o <strong>esperança</strong> (o <strong>valor esperat</strong>, <strong>valor mitjà</strong>…), d’una variable aleatòria discreta <span class="math inline">\(X\)</span> amb densitat <span class="math inline">\(f_X:D_X\to [0,1]\)</span> és
<span class="math display">\[
E(X)=\sum_{x\in D_X} x\cdot f_X(x)
\]</span>
Sovint també la indicarem amb <span class="math inline">\(\mu_X\)</span>.</p>
<p>La interpretació natural de <span class="math inline">\(E(X)\)</span> és que és <strong>la mitjana dels valors de la variable <span class="math inline">\(X\)</span> en el total de la població <span class="math inline">\(\Omega\)</span></strong>. En efecte, com que <span class="math inline">\(P(X=x)\)</span> és la proporció de subjectes de <span class="math inline">\(\Omega\)</span> en els quals <span class="math inline">\(X\)</span> val <span class="math inline">\(x\)</span>,
<span class="math display">\[
E(X)=\sum_{x\in D_X} x\cdot P(X=x)
\]</span>
és la mitjana del valor de <span class="math inline">\(X\)</span> sobre tots els subjectes de <span class="math inline">\(\Omega\)</span>. Comparau-ho amb l’exemple següent.</p>

<div class="example">
<p><span id="exm:notes1" class="example"><strong>Exemple 2.2  </strong></span>Si, en una classe, un 10% dels estudiants han tret un 4 en un examen, un 20% un 6, un 50% un 8 i un 20% un 10, quina ha estat la nota mitjana obtinguda?</p>
</div>
<p>Segurament calcularíeu aquesta mitjana de la manera següent:
<span class="math display">\[
4\cdot 0.1+6\cdot 0.2+8\cdot 0.5+10\cdot 0.2=7.6
\]</span>
Doncs aquest valor és la <strong>mitjana</strong> de la variable aleatòria <span class="math inline">\(X\)</span> “Prenc un estudiant d’aquesta classe i mir quina nota ha tret en aquest examen”:
<span class="math display">\[
\begin{array}{rl}
E(X)\!\!\!\!\! &amp;=4\cdot P(X=4)+6\cdot P(X=6)+8\cdot P(X=8)+10\cdot P(X=10)\\
&amp; = 4\cdot 0.1+6\cdot 0.2+8\cdot 0.5+10\cdot 0.2=7.6
\end{array}
\]</span></p>
<p>A banda de la seva interpretació com a “la mitjana de <span class="math inline">\(X\)</span> en el total de la població”, <span class="math inline">\(E(X)\)</span> és també el <strong>valor esperat de <span class="math inline">\(X\)</span></strong>, en el sentit següent:</p>
<blockquote>
<p>Suposau que prenem a l’atzar una mostra de <span class="math inline">\(n\)</span> subjectes de la població, mesuram <span class="math inline">\(X\)</span> sobre ells i calculam la mitjana aritmètica dels <span class="math inline">\(n\)</span> valors obtinguts. Aleshores, quan la mida <span class="math inline">\(n\)</span> de la mostra tendeix a <span class="math inline">\(\infty\)</span>, aquesta mitjana aritmètica tendeix a valer <span class="math inline">\(E(X)\)</span> “gairebé sempre”, en el sentit que la probabilitat que el seu límit sigui <span class="math inline">\(E(X)\)</span> és 1.</p>
</blockquote>
<p>És a dir: si mesuràssim <span class="math inline">\(X\)</span> sobre <strong>molts</strong> subjectes triats a l’atzar i calculàssim la mitjana dels valors obtinguts, és <strong>gairebé segur</strong> que obtendríem un valor <strong>molt proper</strong> a <span class="math inline">\(E(X)\)</span>.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-33" class="example"><strong>Exemple 2.3  </strong></span>Seguim amb la variable aleatòria <span class="math inline">\(X\)</span> “Llançam una moneda equilibrada 3 vegades i comptam les cares”. La seva esperança és
<span class="math display">\[
E(X)= 0\cdot \frac{1}{8}+1\cdot \frac{3}{8}+2\cdot \frac{3}{8}+3\cdot \frac{1}{8}=1.5
\]</span></p>
</div>
<p>Això ens diu que:</p>
<ul>
<li><p>La <strong>mitjana</strong> de <span class="math inline">\(X\)</span> és 1.5: El valor mitjà de la variable <span class="math inline">\(X\)</span> sobre tota la població de seqüències de 3 llançaments d’una moneda equilibrada és 1.5.</p></li>
<li><p>El <strong>valor esperat</strong> de <span class="math inline">\(X\)</span> és 1.5: Si repetíssim moltes vegades l’experiment de llançar la moneda 3 vegades i comptar les cares, de mitjana obtendríem, molt probablement, un valor molt pròxim a 1.5. Abreujam això dient que si llançam la moneda 3 vegades, <strong>esperam treure 1.5 cares</strong>.</p></li>
</ul>
<p>Més en general, si <span class="math inline">\(X\)</span> és una variable aleatòria i <span class="math inline">\(g:\mathbb{R}\to \mathbb{R}\)</span> és una funció, l’<strong>esperança</strong> de <span class="math inline">\(g(X)\)</span> és
<span class="math display">\[
E(g(X))=\sum_{x\in D_X} g(x)\cdot f_X(x).
\]</span>
Un altre cop, la interpretació natural d’aquest valor és que és la mitjana de <span class="math inline">\(g(X)\)</span> sobre la població, i també que és el valor “esperat” de <span class="math inline">\(g(X)\)</span> en el sentit anterior.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-34" class="example"><strong>Exemple 2.4  </strong></span>Si llançam una moneda equilibrada 3 vegades, comptam les cares i elevam aquest nombre de cares al quadrat, quin valor esperam obtenir?</p>
</div>
<p>Serà l’esperança de <span class="math inline">\(X^2\)</span>, on <span class="math inline">\(X\)</span> és la variable aleatòria “Llançam una moneda equilibrada 3 vegades i comptam les cares” (és a dir, aquesta <span class="math inline">\(X^2\)</span> és la variable aleatòria “Llançam una moneda equilibrada 3 vegades, comptam les cares i elevam aquest número al quadrat”):</p>
<p><span class="math display">\[
E(X^2)= 0\cdot \frac{1}{8}+1\cdot \frac{3}{8}+2^2\cdot \frac{3}{8}+3^2\cdot \frac{1}{8}=3
\]</span></p>

<div class="rmdcaution">
<p>Fixau-vos que <span class="math inline">\(E(X^2) \neq E(X)^2\)</span>. Per exemple, en els dos darrers exemples hem vist que si <span class="math inline">\(X\)</span> és la variable aleatòria que compta el nombre de cares en 3 llançaments d’una moneda equilibrada, <span class="math inline">\(E(X^2)=3\)</span> però <span class="math inline">\(E(X)^2=1.5^2=2.25\)</span>.</p>
<p>En general, donades una variable aleatòria <span class="math inline">\(X\)</span> i una aplicació <span class="math inline">\(g:\mathbb{R}\to \mathbb{R}\)</span>, el més habitual és que <span class="math inline">\(E(g(X))\neq g(E(X))\)</span>.</p>
</div>
<p>L’esperança de les variables aleatòries discretes té les propietats següents, totes molt raonables si les interpretau en termes del valor mitjà de <span class="math inline">\(X\)</span> sobre la població:</p>
<ul>
<li><p>Sigui <span class="math inline">\(b\)</span> una <strong>variable aleatòria constant</strong>, que sobre tots els individus de la població pren el mateix valor <span class="math inline">\(b\in \mathbb{R}\)</span>. Aleshores, <span class="math inline">\(E(b)=b\)</span>.</p>
<p>Si en una classe tothom treu un 8 d’un examen, la nota mitjana és un 8, no?</p></li>
</ul>

<div class="rmdromans">
Sí, ja sabem que parlar de variables constants és un oxímoron, però de vegades una variable aleatòria pren el mateix valor sobre tots els subjectes d’una població. Per exemple “Prenc un estudiant de Biologia o Bioquímica del curs 2019/20 i compt el seu nombre de cames”.
</div>
<ul>
<li><p>L’esperança és <strong>lineal</strong>:</p>
<ul>
<li><p>Si <span class="math inline">\(X\)</span> és una variable aleatòria i <span class="math inline">\(a,b\in \mathbb{R}\)</span>, <span class="math inline">\(E(aX+b)=aE(X)+b\)</span></p>
<p>Si en una classe la mitjana d’un examen ha estat un 6 i decidim multiplicar per 1.2 totes les notes i sumar-les 1 punt, la mitjana de la nova nota serà 1.2·6+1=8.2, no?</p></li>
<li><p>Si <span class="math inline">\(X,Y\)</span> són dues variables aleatòries, <span class="math inline">\(E(X+Y)=E(X)+E(Y)\)</span>.</p>
<p>Si en una classe la mitjana de la part de qüestions d’un examen ha estat un 3.5 (sobre 5) i la de la part d’exercicis ha estat un 3 (sobre 5), la nota mitjana de l’examen serà un 3.5+3=6.5, no?</p></li>
<li><p>Combinant les dues propietats anteriors, si <span class="math inline">\(X_1,\ldots,X_n\)</span> són variables aleatòries i <span class="math inline">\(a_1,\ldots,a_n,b\in \mathbb{R}\)</span>,
<span class="math display">\[
  E(a_1X_1+\cdots+a_nX_n+b)=a_1E(X_1)+\cdots+a_nE(X_n)+b
  \]</span></p></li>
</ul></li>
<li><p>L’esperança és <strong>monòtona creixent</strong>: Si <span class="math inline">\(X\leqslant Y\)</span> (en el sentit que el valor de <span class="math inline">\(X\)</span> sobre cada subjecte de la població <span class="math inline">\(\Omega\)</span> és més petit o igual que el valor de <span class="math inline">\(Y\)</span> sobre ell), llavors <span class="math inline">\(E(X)\leqslant E(Y)\)</span>.</p>
<p>Si tots traieu millor nota de Matemàtiques II que de Matemàtiques I, la nota mitjana de Matemàtiques II serà més gran que la de Matemàtiques I, no?</p></li>
</ul>

<div class="rmdexercici">
Sigui <span class="math inline">\(X\)</span> una variable aleatòria discreta uniforme amb domini <span class="math inline">\(D_X=\{1,\ldots,N\}\)</span>. Què val el seu valor esperat?
</div>
</div>
<div id="variància-i-desviació-típica" class="section level3" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Variància i desviació típica</h3>
<p>La <strong>variància</strong> d’una variable aleatòria discreta <span class="math inline">\(X\)</span> és
<span class="math display">\[
\sigma(X)^2 =E((X-\mu_X)^2) =\sum_{x\in D_X} (x-\mu_X)^2\cdot f_X(x)
\]</span>
És a dir, és la mitjana del quadrat de la diferència entre <span class="math inline">\(X\)</span> i la seva mitjana <span class="math inline">\(\mu_X\)</span>. També la indicarem amb <span class="math inline">\(\sigma_X^2\)</span>.</p>
<p>Fixau-vos que es tracta de la traducció “poblacional” de la definició de variància per a una mostra, i per tant serveix per mesurar el mateix que aquella: la dispersió dels resultats de <span class="math inline">\(X\)</span> respecte de la mitjana. Només que ara és per a tota la població, i no per a una mostra.</p>
<p>La identitat següent vos pot ser útil quan hàgiu de calcular variàncies “a mà”.</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-38" class="theorem"><strong>Teorema 2.1  </strong></span><span class="math inline">\(\sigma(X)^2=E(X^2)-\mu_X^2\)</span>.</p>
</div>

<div class="rmdcorbes">
Operem (i recordau que <span class="math inline">\(E(X)=\mu_X\)</span>)
<span class="math display">\[
\begin{array}{rl}
\sigma(X)^2\!\!\!\!\! &amp; =E((X-\mu_X)^2)=E(X^2-2\mu_X\cdot X+\mu_X^2)\\
&amp; = E(X^2)-2\mu_X\cdot E(X)+\mu_X^2\\
&amp; \text{(per la linealitat d&#39;$E$)}\\
&amp; = E(X^2)-2\mu_X^2+\mu_X^2=E(X^2)-\mu_X^2
\end{array}
\]</span>
</div>
<p>La <strong>desviació típica</strong> (o <strong>desviació estàndard</strong>) d’una variable aleatòria discreta <span class="math inline">\(X\)</span> és l’arrel quadrada positiva de la seva variància:
<span class="math display">\[
\sigma(X)=+\sqrt{\sigma(X)^2}
\]</span>
També mesura la dispersió dels valors de <span class="math inline">\(X\)</span> respecte de la mitjana. Sovint la indicarem amb <span class="math inline">\(\sigma_X\)</span>.</p>

<div class="rmdcaution">
En el context de les variables aleatòries, no hi ha “variància” i “variància mostral”, només “variància”. El mateix nom us hauria de donar la pista que la “variància mostral” està definida només per a mostres.
</div>
<p>El motiu per introduir la variància <strong>i</strong> la desviació típica per mesurar la dispersió dels valors de <span class="math inline">\(X\)</span> és la mateixa que en estadística descriptiva: la variància és més fàcil de manejar (no involucra arrels quadrades) però les seves unitats són les de <span class="math inline">\(X\)</span> al quadrat, mentre que les unitats de la desviació típica són les de <span class="math inline">\(X\)</span>, i per tant el seu valor és més fàcil d’interpretar.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-41" class="example"><strong>Exemple 2.5  </strong></span>Seguim amb la variable aleatòria <span class="math inline">\(X\)</span> “Llançam una moneda equilibrada 3 vegades i comptam les cares”. Recordem que <span class="math inline">\(\mu_X=E(X)=1.5\)</span>. Aleshores, la seva variància és:</p>
</div>
<p><span class="math display">\[
\begin{array}{rl}
\sigma(X)^2 \!\!\!\!\! &amp; \displaystyle=(0-1.5)^2\cdot \frac{1}{8}+(1-1.5)^2\cdot \frac{3}{8}\\ &amp;\displaystyle\qquad +(2-1.5)^2\cdot \frac{3}{8}+(3-1.5)^2\cdot \frac{1}{8}=0.75
\end{array}
\]</span>
Si recordam que <span class="math inline">\(E(X^2)=3\)</span>, podem veure que
<span class="math display">\[
E(X^2)-\mu_X^2=3-1.5^2=0.75=\sigma(X)^2
\]</span>
La seva desviació típica és
<span class="math display">\[
\sigma(X) =\sqrt{\sigma(X)^2}=\sqrt{0.75}= 0.866
\]</span></p>
<p>Vegem algunes propietats de la variància i la desviació típica:</p>
<ul>
<li><p>Si <span class="math inline">\(b\)</span> és una variable aleatòria constant que sobre tots els individus de la població pren el valor <span class="math inline">\(b\in \mathbb{R}\)</span>, aleshores <span class="math inline">\(\sigma(b)^2=\sigma(b)=0\)</span>.</p>
<p>Una variable aleatòria constant té zero dispersió.</p></li>
<li><p><span class="math inline">\(\sigma(aX+b)^2=a^2\cdot \sigma(X)^2\)</span>.</p></li>
</ul>

<div class="rmdcorbes">
En efecte
<span class="math display">\[
\begin{array}{l}
\sigma(aX+b)^2 =E((aX+b)^2)-E(aX+b)^2\\
\quad = E(a^2X^2+2abX+b^2)-(aE(X)+b)^2\\
\quad \text{(per la linealitat de $E$)}\\
\quad = a^2E(X^2)+2abE(X)+b^2-a^2E(X)^2-2abE(X)-b^2\\
\quad \text{(una altre cop, per la linealitat de $E$)}\\
\quad = a^2(E(X^2)-E(X)^2)=a^2\sigma(X)^2
\end{array}
\]</span>
</div>
<ul>
<li><p><span class="math inline">\(\sigma(aX+b)=|a|\cdot \sigma(X)\)</span> (recordau que la desviació típica és positiva, i <span class="math inline">\(+\sqrt{a^2}=|a|\)</span>).</p></li>
<li><p>Si <span class="math inline">\(X,Y\)</span> són variables aleatòries <strong>independents</strong>,
<span class="math display">\[
\sigma(X+Y)^2=\sigma(X)^2+\sigma(Y)^2
\]</span>
i per tant
<span class="math display">\[
\sigma(X+Y)=\sqrt{\sigma(X)^2+\sigma(Y)^2}
\]</span>
Si no són independents, en general aquesta igualtat és falsa. Per posar un exemple extrem,
<span class="math display">\[
\sigma(X+X)^2=4\sigma(X)^2 \neq \sigma(X)^2+\sigma(X)^2.
\]</span></p></li>
<li><p>Més en general, si <span class="math inline">\(X_1,\ldots,X_n\)</span> són variables aleatòries <strong>independents</strong> (i, en principi, només en aquest cas) i <span class="math inline">\(a_1,\ldots,a_n,b\in \mathbb{R}\)</span>,
<span class="math display">\[
\begin{array}{l}
\sigma(a_1X_1+\cdots+a_nX_n+b)^2=a_1\cdot\sigma(X_1)^2+\cdots+a_n\cdot\sigma(X_n)^2\\
\sigma(a_1X_1+\cdots+a_nX_n+b)=\sqrt{a_1\cdot\sigma(X_1)^2+\cdots+a_n\cdot\sigma(X_n)^2}
\end{array}
\]</span></p></li>
</ul>

<div class="rmdexercici">
Sigui <span class="math inline">\(X\)</span> una variable aleatòria discreta uniforme amb domini <span class="math inline">\(D_X=\{1,\ldots,N\}\)</span>. Què val la seva desviació típica?
</div>
</div>
<div id="quantils" class="section level3" number="2.2.4">
<h3><span class="header-section-number">2.2.4</span> Quantils</h3>
<p>Sigui <span class="math inline">\(p\in [0,1]\)</span>. El <strong>quantil d’ordre <span class="math inline">\(p\)</span></strong> (o <strong><span class="math inline">\(p\)</span>-quantil</strong>) d’una variable aleatòria discreta <span class="math inline">\(X\)</span> és el valor <span class="math inline">\(x_p\in D_X\)</span> tal que <span class="math inline">\(P(X\leqslant x_p)\geqslant p\)</span> però <span class="math inline">\(P(X&lt; x_p)&lt;p\)</span>. És a dir, el valor <span class="math inline">\(x_p\in D_X\)</span> més petit tal que <span class="math inline">\(P(X\leqslant x_p)\geqslant p\)</span>.</p>
<p>Per exemple, que el 0.25-quantil d’una variable aleatòria discreta <span class="math inline">\(X\)</span> sigui, jo què sé, 8, significa que almenys un 25% de la població té un valor de <span class="math inline">\(X\)</span> més petit o igual que 8, però menys d’un 25% de la població té un valor de <span class="math inline">\(X\)</span> estrictament més petit que 8. És a dir, 8 és el valor més petit per al qual la probabilitat acumulada arriba al 25%.</p>

<div class="rmdnote">
<p>Si existeix algun <span class="math inline">\(x_p\in D_X\)</span> tal que <span class="math inline">\(P(X\leqslant x_p)=p\)</span>, llavors el <span class="math inline">\(p\)</span>-quantil és aquest <span class="math inline">\(x_p\)</span>, perquè, per a tot un altre <span class="math inline">\(x\in D_x\)</span>:</p>
<ul>
<li>Si <span class="math inline">\(x&lt;x_p\)</span>, <span class="math inline">\(P(X\leqslant x)&lt;P(X\leqslant x_p)=F_X(x_p)=p\)</span> i per tant <span class="math inline">\(x\)</span> no pot ser el <span class="math inline">\(p\)</span>-quantil de <span class="math inline">\(X\)</span>.</li>
<li>Si <span class="math inline">\(x&gt;x_p\)</span>, <span class="math inline">\(p=P(X\leqslant x_p)\leqslant P(X&lt;x)\)</span>, i per tant <span class="math inline">\(x\)</span> tampoc no pot ser el <span class="math inline">\(p\)</span>-quantil de <span class="math inline">\(X\)</span>.</li>
</ul>
</div>
<p>Com en estadística descriptiva, alguns quantils de variables aleatòries tenen noms propis. Per exemple:</p>
<ul>
<li><p>La <strong>mediana</strong> de <span class="math inline">\(X\)</span> és el seu 0.5-quantil.</p></li>
<li><p>El <strong>primer</strong> i el <strong>tercer quartils</strong> de <span class="math inline">\(X\)</span> són els seus <span class="math inline">\(0.25\)</span>-quantil i <span class="math inline">\(0.75\)</span>-quantil, respectivament.</p></li>
<li><p>Etc.</p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-45" class="example"><strong>Exemple 2.6  </strong></span>Seguim amb la variable aleatòria <span class="math inline">\(X\)</span> “Llançam una moneda equilibrada 3 vegades i comptam les cares”. Recordem que la seva funció de distribució és</p>
</div>
<p><span class="math display">\[
F_X(x)=\left\{
\begin{array}{ll}
0 &amp; \text{ si $x&lt;0$}\\
0.125 &amp; \text{ si $0\leqslant x&lt;1$}\\
0.5 &amp; \text{ si $1\leqslant x&lt;2$}\\
0.875 &amp; \text{ si $2\leqslant x&lt;3$}\\
1 &amp; \text{ si $3\leqslant x $}
\end{array}
\right.
\]</span></p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-46-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Llavors, per exemple:</p>
<ul>
<li><p>El seu 0.125-quantil és 0</p></li>
<li><p>El seu 0.25-quantil és 1</p></li>
<li><p>La seva mediana és 1</p></li>
<li><p>El seu 0.75-quantil és 2</p></li>
</ul>

<div class="rmdexercici">
Sigui <span class="math inline">\(X\)</span> una variable aleatòria discreta uniforme amb domini <span class="math inline">\(D_X=\{1,\ldots,N\}\)</span>. Què val la seva mediana?
</div>

<div class="rmdcaution">
<p>Encara que emprem “mitjana”, “variància”, “quantils”, etc. tant per a variables aleatòries com per a mostres, no heu de confondre-les.</p>
<ul>
<li><p>Una <strong>variable aleatòria</strong> representa una característica numèrica dels subjectes d’una <strong>població</strong>:</p>
<ul>
<li><p>“Prenem un estudiant de la UIB i mesuram la seva alçada en m.”</p>
<p>La <strong>mitjana</strong> i la <strong>variància</strong> d’aquesta variable són les de tota la població d’estudiants de la UIB i descriuen propietats de tota la població d’estudiants de la UIB.</p></li>
</ul></li>
<li><p>Una <strong>mostra</strong> d’una variable aleatòria són els valors de la variable sobre un <strong>subconjunt</strong> de la població.</p>
<ul>
<li><p>Mesuram les alçades (en m) de 50 estudiants de la UIB d’aquest curs.</p>
<p>La <strong>mitjana</strong> i la <strong>variància</strong> d’aquesta mostra són només les d’aquestes 50 alçades, i poden servir per descriure aquest conjunt de 50 alçades o per estimar els valors de la mitjana i la variància de la població d’estudiants de la UIB</p></li>
</ul></li>
</ul>
</div>
<p>Quan volguem destacar que una mitjana, una variància etc. són les d’una variable aleatòria sobre tota una població, els qualificarem de <strong>poblacionals</strong>.</p>
</div>
</div>
<div id="famílies-importants-de-variables-aleatòries-discretes" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Famílies importants de variables aleatòries discretes</h2>
<p>En aquesta secció descriurem tres famílies de variables aleatòries “distingides” que heu de conèixer:</p>
<ul>
<li>Binomial</li>
<li>Hipergeomètrica</li>
<li>Poisson</li>
</ul>
<p>Cadascuna d’aquestes famílies tenen un tipus específic de funció de densitat que depèn d’un o diversos <strong>paràmetres</strong>.</p>
<p>D’aquestes famílies de variables heu de saber:</p>
<ul>
<li>Les seves propietats bàsiques, com ara el seu valor esperat i si la densitat és simètrica o té una cua a qualque costat.</li>
<li>La seva densitat, el seu valor esperat i la seva variància.</li>
<li>Emprar R per calcular coses amb elles quan sigui necessari.</li>
</ul>
<div id="variables-aleatòries-binomials" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Variables aleatòries binomials</h3>
<p>Un <strong>experiment de Bernoulli</strong> és una acció amb només dos resultats possibles, que identificam amb “Èxit” (<span class="math inline">\(E\)</span>) i “Fracàs” (<span class="math inline">\(F\)</span>), i de la qual, en principi, no podem predir el seu resultat per mor de la influència de l’atzar. Per exemple, llançar un dau cúbic i mirar si ha sortit un 6 (<span class="math inline">\(E\)</span>: treure un 6; <span class="math inline">\(F\)</span>: no treure un 6).</p>
<p>La <strong>probabilitat d’èxit</strong> <span class="math inline">\(p\)</span> d’un experiment de Bernoulli és la probabilitat d’obtenir un èxit <span class="math inline">\(E\)</span>. És a dir, <span class="math inline">\(P(E)=p\)</span>. Naturalment, llavors, <span class="math inline">\(P(F)=1-p\)</span>.</p>
<p>Per exemple, són experiments de Bernoulli</p>
<ul>
<li><p>Llançar una moneda equilibrada i mirar si dóna cara.</p>
<ul>
<li><span class="math inline">\(E\)</span>: donar cara</li>
<li><span class="math inline">\(p=1/2\)</span></li>
</ul></li>
<li><p>Realitzar un test PCR de COVID-19 a una persona i mirar si dóna positiu</p>
<ul>
<li><p><span class="math inline">\(E\)</span>: donar positiu</p></li>
<li><p><span class="math inline">\(p\)</span>: la proporció de persones que donen positiu en el test a la població de la qual hem extret el nostre subjecte</p>
<p>Que no heu de confondre amb la proporció de persones de la població de la qual hem extret el nostre subjecte que tenen la COVID-19.</p></li>
</ul></li>
</ul>
<p>Una <strong>variable aleatòria de Bernoulli de paràmetre <span class="math inline">\(p\)</span></strong> (abreujadament, <span class="math inline">\(Be(p)\)</span>) és una variable aleatòria <span class="math inline">\(X\)</span> que consisteix a efectuar un experiment de Bernoulli i donar 1 si s’obté un èxit i 0 si s’obté un fracàs.</p>
<p>Una <strong>variable aleatòria binomial de paràmetres <span class="math inline">\(n\)</span> i <span class="math inline">\(p\)</span></strong> (abreujadament, <span class="math inline">\(B(n,p)\)</span>) és una variable aleatòria <span class="math inline">\(X\)</span> que compta el nombre d’èxits <span class="math inline">\(E\)</span> en una seqüència de <span class="math inline">\(n\)</span> repeticions independents d’un mateix experiment de Bernoulli de probabilitat d’èxit <span class="math inline">\(p\)</span>. <strong>Independents</strong> significa que les <span class="math inline">\(n\)</span> variables aleatòries de Bernoulli, una per a cada repetició de l’experiment de Bernoulli, són independents; és a dir, que el resultat de cada experiment en la seqüència no depèn dels resultats dels altres.</p>
<p>Direm a <span class="math inline">\(n\)</span> la <strong>mida de les mostres</strong> i a <span class="math inline">\(p\)</span> la <strong>probabilitat</strong> (<strong>poblacional</strong>) <strong>d’èxit</strong>. De vegades també direm d’una variable <span class="math inline">\(X\)</span> de tipus <span class="math inline">\(B(n,p)\)</span> que té <strong>distribució binomial de paràmetres <span class="math inline">\(n\)</span> i <span class="math inline">\(p\)</span></strong>.</p>
<p>Per exemple:</p>
<ul>
<li><p>Una variable de Bernoulli <span class="math inline">\(Be(p)\)</span> és una variable binomial <span class="math inline">\(B(1,p)\)</span>.</p></li>
<li><p>Llançar una moneda equilibrada 10 vegades i comptar les cares és una variable binomial <span class="math inline">\(B(10,0.5)\)</span>.</p></li>
<li><p>Triar 20 estudiants de la UIB a l’atzar, l’un rere l’altre, permetent repeticions i cada tria independent de les altres, i mirar si al primer semestre han aprovat totes les assignatures o no, és una variable binomial <span class="math inline">\(B(20,p)\)</span> amb <span class="math inline">\(p\)</span> la proporció d’estudiants de la UIB que han aprovat totes les assignatures del primer semestre.</p></li>
</ul>
<p>El tipus més comú de variables binomials que ens interessaran és aquest darrer:</p>

<div class="rmdimportant">
Tenim un subconjunt <span class="math inline">\(A\)</span> d’una població <span class="math inline">\(\Omega\)</span> (per exemple, <span class="math inline">\(\Omega\)</span> els estudiants de la UIB i <span class="math inline">\(A\)</span> els que han aprovat totes les assignatures del primer semestre). Sigui <span class="math inline">\(p\)</span> la proporció poblacional d’individus de la població que pertanyen a <span class="math inline">\(A\)</span>, és a dir <span class="math inline">\(p=P(A)\)</span>. Prenem <strong>mostres aleatòries simples</strong> de mida <span class="math inline">\(n\)</span> de la població i comptam quants subjectes de la mostra són de <span class="math inline">\(A\)</span>. Aquesta variable aleatòria és <strong>binomial</strong> <span class="math inline">\(B(n,p)\)</span>.
</div>
<p>Tenim el resultat següent.</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-50" class="theorem"><strong>Teorema 2.2  </strong></span>Si <span class="math inline">\(X\)</span> és una variable <span class="math inline">\(B(n,p)\)</span>:</p>
<ul>
<li><p>El seu domini és <span class="math inline">\(D_X=\{0,1,\ldots,n\}\)</span></p></li>
<li><p>La seva funció de densitat és
<span class="math display">\[
f_X(k)=\left\{\begin{array}{ll}
\displaystyle\binom{n}{k}p^k(1-p)^{n-k} &amp; \text{ si $k\in D_X$}\\
0 &amp; \text{ si $k \notin D_X$}
\end{array}
\right.
\]</span></p></li>
<li><p>El seu valor esperat és <span class="math inline">\(E(X)=np\)</span></p></li>
<li><p>La seva variància és <span class="math inline">\(\sigma(X)^2=np(1-p)\)</span></p></li>
</ul>
</div>

<div class="rmdimportant">
<p>Recordau que:</p>
<ul>
<li><p>El <strong>factorial</strong> <span class="math inline">\(m!\)</span> d’un nombre natural <span class="math inline">\(m\)</span> és <span class="math inline">\(m!=m(m-1)\cdots 2\cdot 1\)</span> si <span class="math inline">\(m\geqslant 1\)</span>. Si <span class="math inline">\(m=0\)</span>, es pren <span class="math inline">\(0!=1\)</span>.</p></li>
<li><p>El <strong>nombre combinatori</strong> <span class="math inline">\(\binom{n}{k}\)</span> és
<span class="math display">\[
\binom{n}{k}=\frac{\overbrace{n\cdot (n-1)\cdots (n-k+1)}^k}{k\cdot (k-1)\cdots 2\cdot 1}=\frac{n!}{k!(n-k)!}
\]</span>
i ens dóna el nombre de subconjunts de <span class="math inline">\(k\)</span> elements de <span class="math inline">\(\{1,\ldots,n\}\)</span>.</p>
</div></li>
</ul>

<div class="rmdcorbes">
<p>Suposem que efectuam <span class="math inline">\(n\)</span> repeticions consecutives i independents d’un experiment de Bernoulli de probabilitat d’èxit <span class="math inline">\(p\)</span> i comptam el nombre d’èxits <span class="math inline">\(E\)</span>; direm <span class="math inline">\(X\)</span> a la variable aleatòria resultant. Per seguir la demostració, si no us sentiu molt còmodes amb el raonament amb enes i kas abstractes, anau repetint-lo prenent, per exemple, <span class="math inline">\(n=4\)</span>.</p>
<p>Els possibles resultats són totes les paraules possibles de <span class="math inline">\(n\)</span> lletres formades per <span class="math inline">\(E\)</span>’s i <span class="math inline">\(F\)</span>’s. Com que els experiments successius són independents, la probabilitat de cadascuna d’aquestes paraules és el producte de les probabilitats dels seus resultats individuals. Per tant, si una paraula concreta té <span class="math inline">\(k\)</span> lletres <span class="math inline">\(E\)</span> i <span class="math inline">\(n-k\)</span> lletres <span class="math inline">\(F\)</span> (s’han obtingut <span class="math inline">\(k\)</span> èxits i <span class="math inline">\(n-k\)</span> fracassos), la seva probabilitat és <span class="math inline">\(p^k(1-p)^{n-k}\)</span>, independentment de l’ordre en el qual hàgim obtingut els resultats.</p>
<p>Per calcular la probabilitat d’obtenir una seqüència amb <span class="math inline">\(k\)</span> èxits, sumarem les probabilitats d’obtenir cadascuna de les seqüències de <span class="math inline">\(n\)</span> lletres amb <span class="math inline">\(k\)</span> <span class="math inline">\(E\)</span>’s. Com que totes tenen la mateixa probabilitat, el resultat serà la probabilitat d’una paraula amb <span class="math inline">\(k\)</span> <span class="math inline">\(E\)</span>’s i <span class="math inline">\(n-k\)</span> <span class="math inline">\(F\)</span>’s multiplicada pel nombre total de paraules diferents amb <span class="math inline">\(k\)</span> <span class="math inline">\(E\)</span>’s i <span class="math inline">\(n-k\)</span> <span class="math inline">\(F\)</span>’s.</p>
<p>Ara, quantes paraules hi ha amb <span class="math inline">\(k\)</span> <span class="math inline">\(E\)</span>’s i <span class="math inline">\(n-k\)</span> <span class="math inline">\(F\)</span>’s? Cada una d’elles queda caracteritzada per les posicions de les <span class="math inline">\(k\)</span> <span class="math inline">\(E\)</span>’s, per tant és el nombre de possibles eleccions de conjunts de <span class="math inline">\(k\)</span> posicions per a les <span class="math inline">\(E\)</span>’s. Això darrer és el nombre de possibles subconjunts de <span class="math inline">\(k\)</span> elements (les posicions on hi haurà les <span class="math inline">\(E\)</span>’s) de <span class="math inline">\(\{1,\ldots,n\}\)</span>, que és el nombre combinatori <span class="math inline">\(\binom{n}{k}\)</span>.
Per tant ja tenim
<span class="math display">\[
P(X=k)=\binom{n}{k}p^k(1-p)^{n-k}.
\]</span></p>
<p>A partir d’aquí, el càlcul del valor esperat i la variància és sumar
<span class="math display">\[
\begin{array}{l}
\displaystyle E(X)=\sum_{k=0}^n k\cdot \binom{n}{k}p^k(1-p)^{n-k}\\
\displaystyle \sigma(X)^2=\sum_{k=0}^n k^2\cdot \binom{n}{k}p^k(1-p)^{n-k}-\Big(\sum_{k=0}^n k\cdot \binom{n}{k}p^k(1-p)^{n-k})^2
\end{array}
\]</span>
Us podeu fiar de nosaltres, donen <span class="math inline">\(np\)</span> i <span class="math inline">\(np(1-p)\)</span>, respectivament.</p>
<p>Si ho pensau, veureu que el valor de <span class="math inline">\(E(X)\)</span> és l’“esperat”. Vegem, si preneu una mostra aleatòria de <span class="math inline">\(n\)</span> subjectes d’una població en la qual la proporció de subjectes <span class="math inline">\(E\)</span> és <span class="math inline">\(p\)</span>, quants subjectes <span class="math inline">\(E\)</span> “esperau” obtenir en la vostra mostra? Doncs una proporció <span class="math inline">\(p\)</span> de la mostra, és a dir <span class="math inline">\(p\cdot n\)</span>, no?</p>
</div>

<div class="rmdnote">
La funció de distribució d’una variable binomial no té una fórmula explícita. Només podem dir que si <span class="math inline">\(X\)</span> és <span class="math inline">\(B(n,p)\)</span>,
<span class="math display">\[
F_X(x)=\sum_{k=0}^{\min\{n,x\}} \binom{n}{k}p^k(1-p)^{n-k}
\]</span>
</div>

<div class="rmdimportant">
És un doi, però, per si de cas, us volem fer observar que si <span class="math inline">\(X\)</span> és <span class="math inline">\(B(n,p)\)</span>, <span class="math inline">\(P(X=k)\)</span> no només depèn de <span class="math inline">\(k\)</span> sinó també dels paràmetres <span class="math inline">\(n\)</span> i <span class="math inline">\(p\)</span>. Això serà general. Totes les variables aleatòries d’una mateixa família tenen la funció de densitat de la mateixa forma, i només hi varien els valors dels paràmetres.
</div>
<p>El tipus de teorema anterior és el que fa que ens interessi conèixer algunes famílies distingides freqüents de variables aleatòries. Si, per exemple, reconeixem que una variable aleatòria és binomial i coneixem els seus valors de <span class="math inline">\(n\)</span> i <span class="math inline">\(p\)</span> i sabem el teorema anterior, automàticament sabem la seva funció de densitat, i amb ella la seva funció de distribució, el seu valor esperat, la seva variància etc., sense necessitat de deduir tota aquesta informació cada vegada que trobem una variable d’aquestes.</p>

<div class="rmdrecordau">
Saber coses estalvia temps.
</div>
<p>Naturalment, conèixer les propietats de les variables aleatòries binomials només és útil si sabem reconèixer quan estam davant d’una. Fixau-vos que en una variable aleatòria binomial:</p>
<ul>
<li><p>Comptam quantes vegades ocorre un esdeveniment (l’èxit <span class="math inline">\(E\)</span>) en una seqüència d’intents.</p></li>
<li><p>En cada intent, l’esdeveniment que ens interessa passa o no passa, sense grisos.</p></li>
<li><p>El nombre d’intents és fix, <span class="math inline">\(n\)</span>.</p></li>
<li><p>Cada intent és independent dels altres.</p></li>
<li><p>En cada intent, la probabilitat que passi l’esdeveniment que ens interessa és sempre la mateixa, <span class="math inline">\(p\)</span>.</p></li>
</ul>
<p>Així, per exemple:</p>
<ul>
<li><p>Una dona té 4 fills. La probabilitat que un fill sigui nina és fixa, 0.51. El sexe de cada fill és independent dels altres. Comptam quantes filles té.</p>
<p>És una variable binomial <span class="math inline">\(B(4,0.51)\)</span>.</p></li>
<li><p>En una aula hi ha 5 homes i 45 dones. Triam 10 estudiants, un rere l’altre i sense repetir-los, per fer-los una pregunta. Cada elecció és independent de les altres. Comptam quants homes hem interrogat.</p>
<p><strong>No és una variable binomial</strong>: com que no podem repetir estudiants, en cada ronda la probabilitat de triar un home depèn del sexe dels estudiants triats abans que ell. Per tant la <span class="math inline">\(p\)</span> no és la mateixa en cada elecció.</p>
<p>Per exemple, en la primera ronda la probabilitat de triar un home és 5/50=0.1. Ara, si en la primera ronda surt triat un home, la probabilitat que en la segona ronda tornem a triar un home es redueix a 4/49=0.0816, mentre que si en la primera elecció surt una dona, la probabilitat de triar un home en la segona ronda puja a 5/49=0.102.</p></li>
<li><p>En una aula hi ha 5 homes i 45 dones. Triam 10 estudiants, un rere l’altre però cada estudiant pot ser triat més d’una vegada, per a fer-los una pregunta. Cada elecció és independent de les altres. Comptam quants homes hem interrogat.</p>
<p>Ara sí que és una variable binomial <span class="math inline">\(B(10,0.9)\)</span>.</p></li>
<li><p>En una aula hi ha 5 homes i 45 dones. Triam estudiants un rere l’altre i cada estudiant pot ser triat més d’una vegada, per fer-los una pregunta. Cada elecció és independent de les altres. Comptam quants estudiants hem hagut de triar per arribar a interrogar 5 homes.</p>
<p>No és una variable binomial: no compta el nombre d’èxits en una seqüència d’un nombre fix d’intents, sinó quants intents hem necessitat per arribar a un nombre fix d’èxits.</p></li>
<li><p>En una aula hi ha 5 homes i 45 dones. Llançam una moneda equilibrada: si surt cara triam 10 estudiants i si surt creu en triam 20, per a fer-los una pregunta. Tant en un cas com en l’altre, els triarem un rere l’altre, cada estudiant podrà ser triat més d’una vegada i cada elecció serà independent de les altres. Comptam quants homes hem interrogat.</p>
<p>No és una variable binomial: el nombre d’intents no és fix.</p></li>
<li><p>La probabilitat que un dia de novembre plogui és d’un 32%. Triam una setmana de novembre i comptam quants dies ha plogut.</p>
<p>No és d’una variable binomial. Encara que <em>a priori</em> cada dia tengui la mateixa probabilitat de pluja, que plogui un dia no és independent que plogui l’anterior. Per què fos binomial, hauríem d’haver triat 7 dies de novembre a l’atzar, permetent que sortissin repetits.</p></li>
<li><p>A Espanya hi ha 46,700,000 persones, de les quals un 11.7% són diabètics. Triam 100 espanyols diferents a l’atzar (de manera independent els uns dels altres) i comptam quants són diabètics.</p>
<p>No és binomial, pel mateix motiu que no ho era quan elegíem estudiants sense permetre repeticions. Però <strong>pràcticament</strong> sí que ho és, perquè les probabilitats gairebé no varien d’una elecció a la següent.</p>
<p>Per exemple, quan ja duim 99 individus escollits, la probabilitat de triar un individu concret dels que queden és <span class="math inline">\(1/(46700000-99)=2.141332\times 10^{-8}\)</span> mentre que si permetem repeticions, aquesta probabilitat és <span class="math inline">\(1/46700000=2.141328\times 10^{-8}\)</span>. Conicdeixen fins la dotzena xifra decimal.</p>
<p>En aquest cas farem la trampa de considerar-la binomial.</p></li>
</ul>
<p>Vegem alguns gràfics de la funció densitat de variables aleatòries binomials. Primer, per a <span class="math inline">\(n=10\)</span> i diferents valors de <span class="math inline">\(p\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-56-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Ara per a <span class="math inline">\(n=100\)</span>:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-57-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Com podeu veure, la moda d’una binomial <span class="math inline">\(B(n,p)\)</span> és la seva mitjana <span class="math inline">\(np\)</span> o, si aquest nombre no és enter, un dels dos enters que l’envolten.</p>
<p>Si <span class="math inline">\(p=0.5\)</span>, la funció densitat és simètrica respecte de <span class="math inline">\(n/2\)</span>: com que <span class="math inline">\(E\)</span> i <span class="math inline">\(F\)</span> tenen la mateixa probabilitat, 0.5, la probabilitat de treure <span class="math inline">\(k\)</span> <span class="math inline">\(E\)</span>’s és la mateixa que la de treure <span class="math inline">\(k\)</span> <span class="math inline">\(F\)</span>’s, és a dir, la de treure <span class="math inline">\(n-k\)</span> <span class="math inline">\(E\)</span>’s.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-58-1.png" width="90%" style="display: block; margin: auto;" /></p>
<p>En canvi, si <span class="math inline">\(p\neq 0.5\)</span>, la funció densitat no és simètrica, com podeu veure als gràfics de més a dalt.</p>

<div class="rmdexercici">
<p>Per a agilitar els tests de COVID-19, s’ha proposat l’estratègia següent (anomenada <em>pooled sample testing</em> o simplement <em>pooling</em>). Unim grups de 10 mostres en una sola mostra i l’analitzam. Si dóna negatiu, serà senyal que totes la mostres originals eren negatives. Declararem llavors negatius els 10 subjectes de les mostres originals. Si dóna positiu, serà perquè almenys una de les mostres originals era positiva. En aquest cas, analitzarem les 10 mostres per separat.</p>
<p>Observau llavors que si les 10 mostres eren negatives, fem un sol test, mentre que si alguna mostra és positiva, en fem 11. Amb l’enfocament tradicional, un test per mostra, sense complicacions, faríem sempre 10 tests.</p>
Suposem que el test té una especificitat i una sensibilitat del 100%. Sigui <span class="math inline">\(p\)</span> la prevalença de la COVID-19 en un moment i població donats. Donades 10 mostres preses en aquest moment en aquesta població, quin és el valor esperat de tests que hem de realitzar? Per a <span class="math inline">\(p\)</span> petita, de l’ordre de l’1% al 5%, significaria el <em>pooling</em> un estalvi “esperat” considerable de tests?
</div>
<div id="com-efectuar-càlculs-amb-una-variable-aleatòria-duna-família-donada" class="section level4 unnumbered">
<h4>Com efectuar càlculs amb una variable aleatòria d’una família donada?</h4>
<p>Una possibilitat és usar una aplicació de mòbil o tauleta. La nostra preferida és <em>Probability distributions</em>, disponible tant per a Android com per a iOS.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-60"></span>
<img src="Bioestadistica-II_files/figure-html/appprobdistr.png" alt="L'apli *Probability Distributions*." width="80%" />
<p class="caption">
Figura 2.3: L’apli <em>Probability Distributions</em>.
</p>
</div>
<p>Una altra possibilitat és usar R. R coneix totes la distribucions de variables aleatòries importants; per exemple, per a R la binomial és <code>binom</code>. Aleshores</p>
<ul>
<li><p>Afegint al nom de la distribució el prefix <code>d</code>, tenim la seva funció de <strong>densitat</strong>: de la binomial serà <code>dbinom</code>.</p></li>
<li><p>Afegint al nom de la distribució el prefix <code>p</code>, tenim la seva funció de <strong>distribució</strong>: de la binomial, <code>pbinom</code>.</p></li>
<li><p>Afegint al nom de la distribució el prefix <code>q</code>, tenim els seus <strong>quantils</strong>: per a la binomial, <code>qbinom</code>.</p></li>
<li><p>Afegint al nom de la distribució el prefix <code>r</code>, tenim una funció que produeix <strong>mostres aleatòries</strong> de nombres amb aquesta distribució de probabilitat: per a la binomial, <code>rbinom</code>.</p></li>
</ul>
<p>Aquestes funcions s’apliquen a l’argument de la funció i els paràmetres de la variable aleatòria en el seu ordre usual. Per exemple, per a la binomial, s’apliquen a (argument, <span class="math inline">\(n\)</span>, <span class="math inline">\(p\)</span>). Per a més detalls sobre tot això, consultau la <a href="https://aprender-uib.github.io/AprendeR1/chap-distr.html">lliçó de R sobre el tema</a>.</p>
<p>Vegem alguns exemples.</p>
<ul>
<li><p>Si llançam 20 vegades un dau cúbic equilibrat, quina és la probabilitat de treure exactament 5 uns?</p>
<p>Diguem <span class="math inline">\(X\)</span> a la variable aleatòria que compta el nombre d’uns en seqüències de 20 llançaments d’un dau equilibrat. És una variable binomial <span class="math inline">\(B(20,1/6)\)</span>. Ens demanen <span class="math inline">\(P(X=5)\)</span>, i aquesta probabilitat ens la dóna la funció de densitat de <span class="math inline">\(X\)</span>. És <span class="math inline">\(f_X(5)\)</span>:</p></li>
</ul>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="chap-varal.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">5</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.1294103</code></pre>
<ul>
<li><p>Si llançam 20 vegades un dau cúbic equilibrat, quina és la probabilitat de treure com a màxim 5 uns?</p>
<p>Amb les notacions anteriors, ens demanen <span class="math inline">\(P(X\leqslant 5)\)</span>, i aquesta probabilitat ens la dóna la funció de distribució de <span class="math inline">\(X\)</span>. És <span class="math inline">\(F_X(5)\)</span>:</p></li>
</ul>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="chap-varal.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">5</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.8981595</code></pre>
<ul>
<li><p>Si llançam 20 vegades un dau cúbic equilibrat, quina és la probabilitat de treure menys de 5 uns?</p>
<p>Amb les notacions anteriors, ens demanen <span class="math inline">\(P(X&lt; 5)\)</span>, és a dir, <span class="math inline">\(P(X\leqslant 4)=F_X(4)\)</span>:</p></li>
</ul>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="chap-varal.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">4</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.7687492</code></pre>
<ul>
<li><p>Si llançam 20 vegades un dau cúbic equilibrat, quina és la probabilitat de treure 8 uns o més?</p>
<p>Amb les notacions anteriors, ens demanen <span class="math inline">\(P(X\geqslant 8)\)</span>. Com que el contrari de treure 8 uns o més és treure 7 uns o menys, tenim que <span class="math inline">\(P(X\geqslant 8)=1-P(X\leqslant 7)=1-F_X(7)\)</span>:</p></li>
</ul>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="chap-varal.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pbinom</span>(<span class="dv">7</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.01125328</code></pre>
<ul>
<li>Si llançam 20 vegades un dau equilibrat, quin és el més petit nombre <span class="math inline">\(N\)</span> d’uns per al qual la probabilitat de treure com a màxim <span class="math inline">\(N\)</span> uns arriba al 25%? Ens demanen el més petit valor <span class="math inline">\(N\)</span> tal que <span class="math inline">\(P(X\leqslant N)\geqslant 0.25\)</span>, i això per definició és el 0.25-quantil de <span class="math inline">\(X\)</span>:</li>
</ul>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="chap-varal.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qbinom</span>(<span class="fl">0.25</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>Vegem que en efecte <span class="math inline">\(N=2\)</span> compleix el demanat: la probabilitat de treure com a màxim 2 uns és</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="chap-varal.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">2</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.3286591</code></pre>
<p>i la probabilitat de treure com a màxim 1 un és</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="chap-varal.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">1</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.1304203</code></pre>
<p>Veiem per tant que amb 1 un no arribam al 25% de probabilitat i amb 2 sí.</p>
<ul>
<li>Volem simular 50 rondes de llançar 20 vegades un dau equilibrat i comptar els uns, és a dir, volem una mostra aleatòria de mida 50 de la nostra variable <span class="math inline">\(X\)</span>:</li>
</ul>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="chap-varal.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="dv">50</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>##  [1] 8 4 1 2 0 8 1 4 3 0 2 2 2 1 4 1 1 5 6 2 7 3 4 2 3 3 2 3 2 6 7 4 5 3 3 3 9 5
## [39] 1 4 4 4 4 4 5 0 3 2 2 5</code></pre>
<p>Cada vegada que repetim aquesta instrucció segurament obtendrem una mostra aleatòria nova:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="chap-varal.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="dv">50</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>##  [1] 5 3 1 4 4 7 3 1 3 1 3 5 6 1 3 2 4 1 4 5 4 5 3 1 2 4 1 2 2 3 1 6 0 2 3 6 2 6
## [39] 3 3 5 3 5 3 4 3 4 2 4 4</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="chap-varal.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="dv">50</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>##  [1] 5 5 5 1 3 1 8 1 5 7 5 1 5 5 5 3 4 2 6 2 4 4 5 5 1 1 4 2 5 5 3 4 5 3 3 5 4 5
## [39] 2 1 3 7 5 2 5 0 6 5 2 2</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="chap-varal.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="dv">50</span>,<span class="dv">20</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>##  [1] 4 3 4 5 4 7 3 1 4 4 3 4 2 3 2 1 3 4 2 9 3 4 4 4 6 3 3 5 4 4 4 2 2 2 2 2 4 2
## [39] 4 5 4 3 9 3 4 4 4 3 3 4</code></pre>
</div>
</div>
<div id="variables-aleatòries-hipergeomètriques" class="section level3" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Variables aleatòries hipergeomètriques</h3>
<p>Recordau que el paradigma de variable aleatòria binomial és: tenc una població amb una proporció <span class="math inline">\(p\)</span> de subjectes que satisfan una condició <span class="math inline">\(E\)</span>, en prenc una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> i compt el nombre de subjectes <span class="math inline">\(E\)</span> en la meva mostra. Si canviam “mostra aleatòria simple” per “mostra aleatòria sense reposició”, la distribució de la variable aleatòria que obtenim és una altra: és <strong>hipergeomètrica</strong>.</p>
<p>Una variable aleatòria és <strong>hipergeomètrica</strong> (o té <strong>distribució hipergeomètrica</strong>) <strong>de paràmetres <span class="math inline">\(N\)</span>, <span class="math inline">\(M\)</span> i <span class="math inline">\(n\)</span></strong> (abreujadament, <span class="math inline">\(H(N,M,n)\)</span>) quan es pot identificar amb el procés següent: Tenim una població formada per <span class="math inline">\(N\)</span> subjectes que satisfan una condició <span class="math inline">\(E\)</span> i <span class="math inline">\(M\)</span> subjectes que no la satisfan (per tant, en total, <span class="math inline">\(N+M\)</span> subjectes en la població), prenem una mostra aleatòria <strong>sense reposició</strong> de mida <span class="math inline">\(n\)</span> i comptam el nombre de subjectes <span class="math inline">\(E\)</span> en aquesta mostra.</p>
<p>Direm a <span class="math inline">\(N\)</span> el <strong>nombre poblacional d’èxits</strong>, a <span class="math inline">\(M\)</span> el <strong>nombre poblacional de fracassos</strong> i a <span class="math inline">\(n\)</span> la <strong>mida de les mostres</strong>. Fixau-vos llavors que <span class="math inline">\(N+M\)</span> és la <strong>mida total de la població</strong> i que <span class="math inline">\(N/(N+M)\)</span> és la <strong>probabilitat poblacional d’èxit</strong> (la fracció de subjectes que satisfan <span class="math inline">\(E\)</span> en el total de la població). Amb R, igual que la distribució binomial era <code>binom</code>, la distribució hipergeomètrica és <code>hyper</code>.</p>
<p>Tenim el resultat següent:</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-70" class="theorem"><strong>Teorema 2.3  </strong></span>Si <span class="math inline">\(X\)</span> és una variable <span class="math inline">\(H(N,M,n)\)</span>:</p>
<ul>
<li><p>El seu domini és <span class="math inline">\(D_X=\{0,1,\ldots,\text{min}(N,n)\}\)</span></p></li>
<li><p>La seva funció de densitat és
<span class="math display">\[
f_X(k)=\left\{\begin{array}{ll}
\displaystyle\dfrac{\binom{N}{k}\cdot \binom{M}{n-k}}{\binom{N+M}{n}} &amp; \text{ si $k\in D_X$}\\
0 &amp; \text{ si $k\notin D_X$}
\end{array}
\right.
\]</span></p></li>
<li><p>El seu valor esperat és <span class="math inline">\(E(X)=\dfrac{nN}{N+M}\)</span></p></li>
<li><p>La seva variància és <span class="math inline">\(\sigma(X)^2=\dfrac{nNM(N+M-n)}{(N+M)^2(N+M-1)}\)</span></p></li>
</ul>
</div>

<div class="rmdcorbes">
<p>La demostració de la fórmula per a la densitat és senzilla, en termes de casos favorables partit per casos possibles. Vegem: <span class="math inline">\(f_X(k)\)</span> és la probabilitat que un subconjunt de <span class="math inline">\(n\)</span> subjectes (diferents) de la població contingui <span class="math inline">\(k\)</span> subjectes <span class="math inline">\(E\)</span> i <span class="math inline">\(n-k\)</span> subjectes dels altres (en direm <span class="math inline">\(F\)</span>).</p>
<ul>
<li><p>Casos possibles: Tots els possibles subconjunts de <span class="math inline">\(n\)</span> elements de la població. El nombre de tots els subconjunts de <span class="math inline">\(n\)</span> elements d’una població de mida <span class="math inline">\(N+M\)</span> és <span class="math inline">\(\binom{N+M}{n}\)</span>. Ja tenim el denominador.</p></li>
<li><p>Casos favorables: Tots els possibles subconjunts formats per <span class="math inline">\(k\)</span> subjectes <span class="math inline">\(E\)</span> i <span class="math inline">\(n-k\)</span> subjectes <span class="math inline">\(F\)</span>. Cada un d’aquests subconjunts s’obté</p>
<ul>
<li>Triant un subconjunt de <span class="math inline">\(k\)</span> subjectes <span class="math inline">\(E\)</span>: com que n’hi ha <span class="math inline">\(N\)</span>, d’aquests subconjunts n’hi ha <span class="math inline">\(\binom{N}{k}\)</span></li>
<li>Triant un subconjunt de <span class="math inline">\(n-k\)</span> subjectes <span class="math inline">\(F\)</span>: com que n’hi ha <span class="math inline">\(M\)</span>, d’aquests subconjunts n’hi ha <span class="math inline">\(\binom{M}{n-k}\)</span></li>
<li>Per cada tria d’un subconjunt de <span class="math inline">\(k\)</span> subjectes <span class="math inline">\(E\)</span> i un subconjunt de <span class="math inline">\(n-k\)</span> subjectes<span class="math inline">\(F\)</span>, obtenim un subconjunt “favorable” diferent. Per tant, el seu nombre és el producte <span class="math inline">\(\binom{N}{k}\cdot\binom{M}{n-k}\)</span></li>
</ul>
<p>Això ens dóna el numerador.</p></li>
</ul>
</div>
<p>Fixau-vos que si diem <span class="math inline">\(p\)</span> a la probabilitat poblacional d’èxit, <span class="math inline">\(p=N/(N+M)\)</span>, llavors
<span class="math display">\[
E(X)=np.
\]</span>
És la mateixa fórmula que per a les variables binomials <span class="math inline">\(B(n,p)\)</span> (i si ho pensau una estona veureu que, un altre cop i pel mateix argument, és el que la intuïció ens diu que ha de valer). D’altra banda, si diem <span class="math inline">\(\mathbf{P}\)</span> a la mida total de la població, <span class="math inline">\(\mathbf{P}=N+M\)</span>, llavors
<span class="math display">\[
\sigma(X)^2=n\cdot\dfrac{N}{N+M}\cdot\dfrac{M}{N+M}\cdot\frac{N+M-n}{N+M-1}=np(1-p)\cdot\dfrac{\mathbf{P}-n}{\mathbf{P}-1}
\]</span>
que és la variància d’una variable <span class="math inline">\(B(n,p)\)</span> multiplicada per un factor de correcció a causa del fet que ara prenem mostres sense repetició i la variància és més petita que si les prenem amb repetició. A aquest factor <span class="math inline">\((\mathbf{P}-n)/(\mathbf{P}-1)\)</span> se’n diu <strong>factor de població finita</strong>.</p>
<p>Fixau-vos que si <span class="math inline">\(\mathbf{P}\)</span> és moltíssim més gran que <span class="math inline">\(n\)</span>, tendrem que <span class="math inline">\(\mathbf{P}-n\approx \mathbf{P}-1\)</span> i per tant <span class="math inline">\((\mathbf{P}-n)/(\mathbf{P}-1)\approx 1\)</span> i la variància de la hipergeomètrica serà aproximadament la de la binomial. Això és consistent amb el que ja hem comentat: si la població és molt més gran que la mostra, prendre les mostres amb o sense reposició no afecta massa a les mostres obtingudes, per la qual cosa la distribució de probabilitat ha de ser molt semblant.
Recordau els exemples següents:</p>
<ul>
<li><p>A Espanya hi ha 46,700,000 persones, de les quals un 11.7% són diabètics. Triam 100 espanyols i comptam quants són diabètics.</p>
<p>Aquesta variable és, en realitat, hipergeomètrica amb <span class="math inline">\(N=0.117\cdot 46700000=5463900\)</span>, <span class="math inline">\(M=46700000-N=41236100\)</span> i <span class="math inline">\(n=100\)</span>, però en la pràctica la consideram binomial <span class="math inline">\(B(100,0.117)\)</span>. El factor de població finita és
<span class="math display">\[
\frac{46700000-100}{46700000-1}=0.9999979
\]</span>
Pràcticament 1. En canvi:</p></li>
<li><p>En una aula hi ha 5 homes i 45 dones. Triam 10 estudiants, un rere l’altre i sense repetir-los, per fer-los una pregunta. Cada elecció és independent de les altres. Comptam quants homes hem interrogat.</p>
<p>Aquesta variable és hipergeomètrica <span class="math inline">\(H(5,45,10)\)</span>. El factor de població finita en aquesta cas no és aproximadament 1: dóna
<span class="math display">\[
\frac{50-10}{50-1}=0.8163
\]</span>
No és correcte aproximar-la per una binomial <span class="math inline">\(B(10,0.1)\)</span>.</p></li>
</ul>
<p>El gràfic següent compara la funció de densitat d’una variable <span class="math inline">\(B(10,0.1)\)</span> amb les de variables hipergeomètriques <span class="math inline">\(H(5,45,10)\)</span>, <span class="math inline">\(H(50,450,10)\)</span> i <span class="math inline">\(H(5000,45000,10)\)</span> perquè vegeu com a mesura que la mida de la població creix (mantenint constant la proporció poblacional d’èxits), la distribució hipergeomètrica s’aproxima a la binomial.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-72-1.png" width="50%" style="display: block; margin: auto;" /></p>
</div>
<div id="variables-aleatòries-de-poisson" class="section level3" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Variables aleatòries de Poisson</h3>
<p>Una variable aleatòria <span class="math inline">\(X\)</span> és <strong>de Poisson</strong> (o té distribució de Poisson) <strong>de paràmetre <span class="math inline">\(\lambda&gt;0\)</span></strong> (abreujadament, <span class="math inline">\(Po(\lambda)\)</span>) quan:</p>
<ul>
<li><p>El seu <strong>domini</strong> és <span class="math inline">\(D_X=\mathbb{N}\)</span>, el conjunt de tots els nombres naturals (és a dir, pot prendre com a valor qualsevol nombre natural).</p></li>
<li><p>La seva <strong>funció de densitat</strong> és
<span class="math display">\[
f_X(k)=\left\{\begin{array}{ll}
e^{-\lambda}\cdot \dfrac{\lambda^k}{k!} &amp; \text{ si $k\in \mathbb{N}$}\\
0 &amp; \text{ si $k
\notin \mathbb{N}$}
\end{array}
\right.
\]</span></p></li>
</ul>
<p>Per a R, la distribució de Poisson és <code>pois</code>.</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-73" class="theorem"><strong>Teorema 2.4  </strong></span>Si <span class="math inline">\(X\)</span> és una variable <span class="math inline">\(Po(\lambda)\)</span>, aleshores <span class="math inline">\(E(X)= \sigma(X)^2= \lambda\)</span>.</p>
</div>
<p>És a dir, el paràmetre <span class="math inline">\(\lambda\)</span> d’una variable de Poisson és el seu valor esperat, i coincideix amb la seva variància.</p>
<p>Us deveu estar demanant: per a què ens serveix definir una variable de Poisson mitjançant la seva densitat, si el que ens interessa és poder classificar una variable com a Poisson (o binomial, o hipergeomètrica etc.) per a així saber “gratis” la seva densitat? La resposta és que la família de Poisson inclou un tipus de variables aleatòries molt freqüent</p>
<p>Suposem que tenim un tipus d’objectes que poden donar-se en una regió contínua de temps o espai. Per exemple, defuncions de persones per una determinada malaltia en el decurs del temps, exemplars d’una espècie de planta en un terreny, mutacions en bocins de cromosoma, o nombres de bacteris en bocins d’una superfície.</p>
<p>Suposem a més que les aparicions d’aquests objectes satisfan les propietats següents (per simplificar el llenguatge, hi suposarem que observam aparicions d’aquests objectes en el temps; si es tracta d’una variable que compta objectes en regions de l’espai, canviau-hi “instant” per “punt”):</p>
<ul>
<li><p>Les aparicions dels objectes són <strong>aleatòries</strong>: en cada instant, un objecte es dóna, o no, a l’atzar, amb una probabilitat fixa i constant.</p></li>
<li><p>Les aparicions dels objectes són <strong>independents</strong>: que es doni un objecte en un instant concret, no depèn per a res que s’hagi donat o no un objecte en un altre instant.</p></li>
<li><p>Les aparicions dels objectes no són <strong>simultànies</strong>: és pràcticament impossible que dos objectes d’aquests es donin en el mateix instant exacte, mesurat amb precisió infinita.</p></li>
</ul>

<div class="rmdimportant">
En aquesta situació, la variable <span class="math inline">\(X_t\)</span> que pren un interval de temps de durada <span class="math inline">\(t\)</span> i compta el nombre d’objectes que s’hi donen és de Poisson <span class="math inline">\(Po(\lambda_t)\)</span>, amb <span class="math inline">\(\lambda_t\)</span> el nombre esperat d’objectes en aquest interval de temps (és a dir, el nombre mitjà d’objectes en intervals de temps d’aquesta mida).
</div>
<p>Per exemple, quan el que compten ocorre a l’atzar, són variables de Poisson:</p>
<ul>
<li><p>El nombre de malalts admesos en urgències en un dia (o en 12 hores, o en una setmana…)</p></li>
<li><p>El nombre de defuncions per una malaltia concreta en un dia (o en una setmana, o en un any…)</p></li>
<li><p>El nombre d’albiraments de dofins en una hora durant un vol d’inspecció</p></li>
<li><p>El nombre de bacteris en un quadrat d’1 cm de costat (o d’1 m de costat…)</p></li>
</ul>
<p>Fixau-vos que aquest tipus de coneixement ens serveix per a dues coses:</p>
<ul>
<li><p>Si sabem que aquestes variables són de Poisson, coneixem la seva densitat i per tant podem calcular el que volguem per a elles.</p></li>
<li><p>Si les dades que observam haurien de seguir una distribució de Poisson però sembla que no (per exemple, perquè la seva variància sigui molt diferent de la seva mitjana, tan diferent que sigui difícil de creure que la mitjana i la variància poblacionals siguin iguals), llavors és senyal que qualque cosa “estranya” està passant que afecta la seva aparició.</p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-75" class="example"><strong>Exemple 2.7  </strong></span>Observau la diferència entre les dues variables següents:</p>
<ul>
<li><p>Nombres mensuals de defuncions per un tipus de càncer en un país. El moment exacte de les defuncions es produeix a l’atzar, segurament mai no es donen dues defuncions exactament en el mateix instant, si els poguéssim mesurar amb precisió infinita, i les defuncions es produeixen de manera independent. És de Poisson.</p></li>
<li><p>Nombres mensuals de defuncions per una malatia infecciosa en un país. Un altre cop, el moment exacte de les defuncions es produeix a l’atzar i segurament mai no es donen dues defuncions exactament en el mateix instant, si els poguéssim mesurar amb precisió infinita. Però les infeccions no són independents, precisament perquè es tracta d’una malaltia infecciosa, i per tant les defuncions tampoc: com ens hem cansat d’observar amb la COVID-19, en un mateix <em>cluster</em> de la malaltia es poden produir diverses morts associades. No és de Poisson.</p></li>
</ul>
</div>

<div class="rmdnote">
Com que les aparicions dels objectes que compta una variable de Poisson són aleatòries i independents, el nombre mitjà d’objectes és lineal en la mida de la regió. És a dir, per exemple, en un interval de dos dies esperam veure el doble d’objectes que en un dia. O per exemple, si es diagnostiquen de mitjana 32,240 casos de càncer de còlon anuals a Espanya (i segueixen una llei de Poisson), esperam que de mitjana es diagnostiquin 32240/52=620 casos setmanals.
</div>
<p>Vegem alguns gràfics de la funció densitat de variables aleatòries de Poisson.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-77-1.png" width="90%" style="display: block; margin: auto;" />
Com veieu, la densitat d’una variable Poisson és asimètrica, amb un màxim al voltant de <span class="math inline">\(\lambda\)</span> i una cua a la dreta, però a mida que <span class="math inline">\(\lambda\)</span> creix, l’asimetria va minvant.</p>

<div class="rmdexercici">
El nombre d’estudiants que entren en el bar de l’edifici en un interval de 5 minuts, creieu que segueix una distribució de Poisson?
</div>
</div>
</div>
<div id="variables-aleatòries-contínues" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Variables aleatòries contínues</h2>
<p>Una variable aleatòria és <strong>contínua</strong> quan els seus possibles valors són dades quantitatives contínues. Per exemple:</p>
<ul>
<li>Pes</li>
<li>Nivell de colesterol en sang</li>
<li>Diàmetre d’un tumor</li>
</ul>
<p>En aquest curs ens restringirem a variables aleatòries contínues <span class="math inline">\(X: \Omega\to \mathbb{R}\)</span> que satisfan la propietat extra següent: la seva <strong>funció de distribució</strong>
<span class="math display">\[
\begin{array}{rcl}
F_X: \mathbb{R} &amp; \to &amp; [0,1]\\
x &amp;\mapsto &amp;P(X\leqslant x)
\end{array}
\]</span>
és contínua. Totes les variables aleatòries contínues que us puguin interessar en algun moment satisfan aquesta propietat, així que no perdem res imposant-la. I el que hi guanyam és que:</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és una variable aleatòria contínua amb funció de distribució contínua, <strong>la probabilitat que prengui cada valor concret és 0</strong>:
<span class="math display">\[
P(X=a)=0 \text{ per a tot $a \in \mathbb{R}$}.
\]</span>
</div>

<div class="rmdcorbes">
Per si passa per aquí qualcú que en necessiti una demostració:
<span class="math display">\[
\begin{array}{l}
\displaystyle P(X=a) = P(X\leqslant a)-P(X&lt;a)=P(X\leqslant a)-P\Big(\bigcup_{n\geqslant 1} \Big(X\leqslant a-\frac{1}{n}\Big)\Big)\\
\displaystyle \qquad= P(X\leqslant a)-\lim_{n\geqslant 1}P\Big(X\leqslant a-\frac{1}{n}\Big)\\
\displaystyle \qquad= F_X(a)-\lim_{n\geqslant 1}F_X\Big(a-\frac{1}{n}\Big)=0
\end{array}
\]</span>
perquè <span class="math inline">\(F_X\)</span> és contínua.
</div>
<p>En particular:</p>

<div class="rmdrecordau">
Per a una variable aleatòria contínua, <strong>probabilitat 0 no significa impossible.</strong>
</div>
<p>Cada valor de <span class="math inline">\(X\)</span> té probabilitat 0, però si prenem un subjecte de la població, <span class="math inline">\(X\)</span> tendrà qualque valor sobre ell, no? Per tant, aquest valor de <span class="math inline">\(X\)</span> és possible, malgrat tengui probabilitat 0.</p>
<p>De <span class="math inline">\(P(X=a)=0\)</span> es dedueix que la probabilitat d’un esdeveniment definit amb una desigualtat és exactament la mateixa que la de l’esdeveniment corresponent definit amb una desigualtat estricta. En particular, contràriament al que passava a les variables aleatòries discretes, per a una variable aleatòria contínua <strong>sempre</strong> tenim que
<span class="math display">\[
P(X\leqslant a)=P(X&lt;a)
\]</span>
perquè
<span class="math display">\[
P(X\leqslant a)=P(X&lt;a)+P(X=a)=P(X&lt;a)+0=P(X&lt;a).
\]</span></p>
<p>Més exemples:</p>
<ul>
<li><span class="math inline">\(P(X\geqslant a)=P(X&gt; a)+P(X=a)=P(X&gt; a)\)</span></li>
<li><span class="math inline">\(P(a \leqslant X\leqslant b)=P(a&lt;X &lt;b)+P(X=a)+P(X=b)\)</span> <span class="math inline">\(=P(a&lt;X &lt;b)\)</span></li>
</ul>
<div id="densitat-i-distribució-1" class="section level3" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Densitat i distribució</h3>
<p>Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua. Com ja hem dit, la seva <strong>funció de distribució</strong> <span class="math inline">\(F_X\)</span> torna a ser
<span class="math display">\[
x\mapsto F_X(x)=P(X\leqslant x)
\]</span></p>
<p>Però com que ara tenim que <span class="math inline">\(P(X=x)=0\)</span> per a tot <span class="math inline">\(x\in \mathbb{R}\)</span>, no podem definir la funció de densitat de <span class="math inline">\(X\)</span> com a <span class="math inline">\(f_X(x)=P(X=x)\)</span>. Què podem fer?</p>
<p>Recordau que, a les variables aleatòries discretes,
<span class="math display">\[
F_X(a)=\sum_{x\leqslant a} f_X(x)
\]</span></p>
<p>En el context de matemàtiques “contínues”, la suma <span class="math inline">\(\sum\)</span> es tradueix en una integral <span class="math inline">\(\int\)</span>. Definim aleshores la <strong>funció de densitat</strong> d’una variable aleatòria contínua <span class="math inline">\(X\)</span> com la funció <span class="math inline">\(f_X:\mathbb{R}\to \mathbb{R}\)</span> tal que:</p>
<ul>
<li><p><span class="math inline">\(f_X(x)\geqslant 0\)</span>, per a tot <span class="math inline">\(x\in \mathbb{R}\)</span></p></li>
<li><p><span class="math inline">\(\displaystyle F_X(a)=\int_{-\infty}^a f_{X}(x)\, dx\)</span> per a tot <span class="math inline">\(a \in \mathbb{R}\)</span>.</p></li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/dontpanic.png" width="20%" style="display: block; margin: auto;" /></p>
<p>Recordau que la integral té una interpretació senzilla en termes d’àrees. En concret, donats <span class="math inline">\(a \in \mathbb{R}\)</span> i una funció <span class="math inline">\(f(x)\)</span>, el valor de la integral
<span class="math display">\[
\int_{-\infty}^a f(x)\, dx
\]</span>
és igual a l’àrea de la regió compresa entre la corba <span class="math inline">\(y=f(x)\)</span> i l’eix d’abscisses <span class="math inline">\(y=0\)</span> a l’esquerra de la recta vertical <span class="math inline">\(x=a\)</span>. Per tant, la funció de densitat <span class="math inline">\(f_X\)</span> de <span class="math inline">\(X\)</span> és la funció positiva tal que, per a tot <span class="math inline">\(a\in \mathbb{R}\)</span>, <span class="math inline">\(F_X(a)\)</span> és igual a <strong>l’àrea sota la corba</strong> <span class="math inline">\(y=f_X(x)\)</span> (és a dir, entre aquesta corba i l’eix d’abscisses) a l’esquerra de <span class="math inline">\(x=a\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/graficadensidad3.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Quina és la idea intuïtiva que hi ha al darrere d’aquesta definició de densitat? Suposau que dibuixam histogrames de freqüències relatives dels valors de <span class="math inline">\(X\)</span> sobre tota la població. Recordau que, en un histograma de freqüències relatives, la freqüència relativa de cada classe (ara la <strong>probabilitat</strong>, ja que parlam de tota la població) és l’àrea de la seva barra, és a dir, l’amplada de la classe per l’alçada de la barra. I que diem a aquesta alçada la <strong>densitat</strong> de la classe (i per tant, qualque cosa tendrà a veure amb la densitat de <span class="math inline">\(X\)</span>, no ho trobau?).</p>
<p>Si dibuixam els histogrames de <span class="math inline">\(X\)</span> prenent classes cada vegada més estretes, els seus polígons de freqüències tendeixen a dibuixar una corba, que hem acolorit en vermell en el darrer histograma de la seqüència següent:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-84-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Quan l’amplada de les classes tendeix a 0, obtenim una corba que és el límit d’aquests polígons de freqüències:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-85-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Aquesta corba és precisament <span class="math inline">\(y=f_X(x)\)</span>.</p>

<div class="rmdimportant">
La <strong>funció de densitat</strong> <span class="math inline">\(f_X\)</span> d’una variable aleatòria contínua <span class="math inline">\(X\)</span> és la funció límit dels polígons de freqüències d’histogrames de <span class="math inline">\(X\)</span> quan l’amplada de les classes tendeix a 0.
</div>
<p>Vegem algunes propietats que es dedueixen del fet que <span class="math inline">\(F_X(a)=P(X\leqslant a)\)</span> sigui igual a <strong>l’àrea sota la corba</strong> <span class="math inline">\(y=f_X(x)\)</span> a l’esquerra de <span class="math inline">\(x=a\)</span>:</p>
<ul>
<li><p>Com que <span class="math inline">\(P(X&lt;\infty)=P(\Omega)=1\)</span>, <strong>l’àrea sota tota la corba <span class="math inline">\(y=f_X(x)\)</span> és 1.</strong></p></li>
<li><p><span class="math inline">\(P(a\leqslant X\leqslant b)=P(X\leqslant b)-P(X&lt;a)\)</span> és l’àrea sota la corba <span class="math inline">\(y=f_X(x)\)</span> a l’esquerra de <span class="math inline">\(x=b\)</span> <strong>menys</strong> l’àrea sota la corba <span class="math inline">\(y=f_X(x)\)</span> a l’esquerra de <span class="math inline">\(x=a\)</span>. Per tant, <span class="math inline">\(P(a\leqslant X\leqslant b)\)</span> és igual a <strong>l’àrea sota la corba <span class="math inline">\(y=f_X(x)\)</span> entre <span class="math inline">\(x=a\)</span> i <span class="math inline">\(x=b\)</span>.</strong></p></li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/entreaib.png" width="60%" style="display: block; margin: auto;" /></p>
<ul>
<li><p>Si <span class="math inline">\(\varepsilon&gt;0\)</span> és molt, molt petit, l’àrea sota la corba <span class="math inline">\(y=f_X(x)\)</span> entre <span class="math inline">\(a-\varepsilon\)</span> i <span class="math inline">\(a+\varepsilon\)</span> és aproximadament igual a la del rectangle de base l’interval <span class="math inline">\([a-\varepsilon,a+\varepsilon]\)</span> i alçada <span class="math inline">\(f_X(a)\)</span>, és a dir, a <span class="math inline">\(2\varepsilon\cdot f_X(a)\)</span> (vegeu la Figura <a href="chap-varal.html#fig:epsilon">2.4</a>). És a dir,
<span class="math display">\[
P(a-\varepsilon\leqslant X\leqslant a+\varepsilon)\approx 2\varepsilon\cdot f_X(a).
\]</span></p>
<p>Per tant, <span class="math inline">\(f_X(a)\)</span> ens dóna una indicació de la probabilitat que <span class="math inline">\(X\)</span> valgui aproximadament <span class="math inline">\(a\)</span> (però <strong>no és</strong> <span class="math inline">\(P(X=a)\)</span>, que val 0). És a dir, per exemple, si <span class="math inline">\(f_X(a)=0.1\)</span> i <span class="math inline">\(f_X(b)=0.5\)</span>, la probabilitat que <span class="math inline">\(X\)</span> prengui un valor al voltant de <span class="math inline">\(b\)</span> és 5 vegades més gran que la probabilitat que prengui un valor al voltant d’<span class="math inline">\(a\)</span>.</p></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:epsilon"></span>
<img src="Bioestadistica-II_files/figure-html/density.png" alt="L'àrea sota la corba al voltant d'$a$ és aproximadament igual a la del rectangle d'alçada f~X~(a)" width="60%" />
<p class="caption">
Figura 2.4: L’àrea sota la corba al voltant d’<span class="math inline">\(a\)</span> és aproximadament igual a la del rectangle d’alçada f<sub>X</sub>(a)
</p>
</div>

<div class="rmdrecordau">
Però <span class="math inline">\(P(X=a)=P(X=b)=0\)</span>, així que, per favor, evitau dir que “la probabilitat que <span class="math inline">\(X\)</span> valgui <span class="math inline">\(b\)</span> <strong>és 5 vegades més gran</strong> que la probabilitat que valgui <span class="math inline">\(a\)</span>”. Sí, ja sabem que <span class="math inline">\(5\cdot 0=0\)</span>, però la frase és enganyosa: la probabilitat que <span class="math inline">\(X\)</span> valgui <span class="math inline">\(b\)</span> no més gran que la probabilitat que valgui <span class="math inline">\(a\)</span>.
</div>
<p>A les variables aleatòries discretes, definíem la moda com el valor (o els valors) més probable. Però ara no té sentit definir la moda d’una variable contínua <span class="math inline">\(X\)</span> com el valor <span class="math inline">\(x_0\)</span> tal que <span class="math inline">\(P(X=x_0)\)</span> sigui màxim, perquè… <span class="math inline">\(P(X=x)=0\)</span> per a tot <span class="math inline">\(x\in \mathbb{R}\)</span>. Aleshores, es defineix la <strong>moda</strong> d’una variable aleatòria contínua <span class="math inline">\(X\)</span> com el valor (o els valors) <span class="math inline">\(x_0\)</span> tal que <span class="math inline">\(f_X(x_0)\)</span> és màxim. Com que <span class="math inline">\(f_X(x_0)\)</span> mesura la probabilitat que <span class="math inline">\(X\)</span> valgui “aproximadament” <span class="math inline">\(x_0\)</span>, tenim que la moda de <span class="math inline">\(X\)</span> és el valor prop del qual és més probable que caigui el valor de <span class="math inline">\(X\)</span>.</p>
<p>Unes consideracions finals:</p>
<ul>
<li>Ho hem dit en la definició, i ho hem emprat implícitament en tota la secció, però ho tornam a repetir: <span class="math inline">\(f_X(x)\geqslant 0\)</span> per a tot <span class="math inline">\(x\in \mathbb{R}\)</span>.</li>
</ul>

<div class="rmdcorbes">
En realitat, que <span class="math inline">\(f_X(x)\)</span> sigui <span class="math inline">\(\geqslant 0\)</span> per a tot <span class="math inline">\(x\in \mathbb{R}\)</span> és conseqüència del fet que la funció <span class="math inline">\(F_X(x)\)</span> sigui positiva i creixent (les funcions de distribució són sempre creixents, perquè si <span class="math inline">\(x&lt;y\)</span>, <span class="math inline">\(F_X(x)=P(X\leqslant x)\leqslant P(X\leqslant y)=F_X(y)\)</span>) i coincideixi amb <span class="math inline">\(\int_{-\infty}^x f_X(x)\,dx\)</span>. Però és més senzill donar-ho com a part de la definició i així ens estalviam la demostració.
</div>
<ul>
<li><span class="math inline">\(f_X(x)\)</span> no és una probabilitat, i per tant pot ser més gran que 1. Per exemple, el gràfic següent mostra la densitat d’una variable normal <span class="math inline">\(N(0,0.01)\)</span> (vegeu la Secció <a href="chap-varal.html#sec:normal">2.5</a>), que arriba a valer gairebé 40.</li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-90-1.png" width="60%" style="display: block; margin: auto;" /></p>
<ul>
<li>La funció de densitat <span class="math inline">\(f_X\)</span> no té per què ser contínua, malgrat la funció de distribució <span class="math inline">\(F_X\)</span> ho sigui.</li>
</ul>
</div>
<div id="esperança-variància-quantils" class="section level3" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Esperança, variància, quantils…</h3>
<p>L’esperança i la variància d’una variable aleatòria contínua <span class="math inline">\(X\)</span>, amb funció de densitat <span class="math inline">\(f_X\)</span>, es defineixen com en el cas discret, substituint la suma <span class="math inline">\(\sum_{x\in D_x}\)</span> per una integral, i tenen les mateixes propietats.</p>
<p>La <strong>mitjana</strong>, o <strong>esperança</strong> (o <strong>valor mitjà</strong>, <strong>valor esperat</strong>…), de <span class="math inline">\(X\)</span> és
<span class="math display">\[
E(X)=\int_{-\infty}^{\infty}x \cdot f_{X}(x)\, dx
\]</span>
És a dir, és l’àrea compresa entre l’eix d’abscisses i la corba <span class="math inline">\(y=xf_X(x)\)</span>.
Com en el cas discret, també la indicarem de vegades amb <span class="math inline">\(\mu_X\)</span>.</p>
<p>Aquest valor té la mateixa interpretació que en el cas discret:</p>
<ul>
<li><p>Representa el valor mitjà de <span class="math inline">\(X\)</span> sobre el total de la població.</p></li>
<li><p>És (amb probabilitat 1) el límit de les mitjanes aritmètica de mostres aleatòries de mida <span class="math inline">\(n\)</span> de valors de <span class="math inline">\(X\)</span>, quan <span class="math inline">\(n\to \infty\)</span>.</p></li>
</ul>
<p>Si <span class="math inline">\(g:\mathbb{R}\to \mathbb{R}\)</span> és una funció contínua, l’<strong>esperança</strong> de <span class="math inline">\(g(X)\)</span> és
<span class="math display">\[
E(g(X))=\int_{-\infty}^{+\infty} g(x) f_X(x)dx
\]</span></p>
<p>La <strong>variància</strong> de <span class="math inline">\(X\)</span> és
<span class="math display">\[
\sigma(X)^2=E((X-\mu_X)^2)=\int_{-\infty}^{+\infty} (x-\mu_X)^2 f_X(x)dx
\]</span>
i es pot demostrar que és igual a
<span class="math display">\[
\sigma(X)^2=E(X^2)-\mu_X^2.
\]</span>
També la indicarem de vegades amb <span class="math inline">\(\sigma_X^2\)</span>.</p>
<p>La <strong>desviació típica</strong> de <span class="math inline">\(X\)</span> és
<span class="math display">\[
\sigma(X)=+\sqrt{\sigma(X)^2}
\]</span>
i també la indicarem de vegades amb <span class="math inline">\(\sigma_X\)</span>.</p>
<p>Com en el cas discret, la variància i la desviació típica quantifiquen la variabilitat dels resultats de <span class="math inline">\(X\)</span> respecte del seu valor mitjà <span class="math inline">\(\mu_X\)</span>.</p>
<p>Aquests paràmetres de <span class="math inline">\(X\)</span> tenen les <strong>mateixes propietats</strong> en el cas continu que en el discret. Les recordam:</p>
<ul>
<li><p>Si <span class="math inline">\(b\)</span> és una variable aleatòria constant, <span class="math inline">\(E(b)=b\)</span> i <span class="math inline">\(\sigma(b)^2=0\)</span>.</p></li>
<li><p>Si <span class="math inline">\(X_1,\ldots,X_n\)</span> són variables aleatòries i <span class="math inline">\(a_1,\ldots,a_n,b\in \mathbb{R}\)</span>,
<span class="math display">\[
E(a_1X_1+\cdots+a_nX_n+b)=a_1E(X_1)+\cdots+a_nE(X_n)+b
\]</span></p></li>
<li><p>Si <span class="math inline">\(X\leqslant Y\)</span>, aleshores <span class="math inline">\(E(X)\leqslant E(Y)\)</span>.</p></li>
<li><p>Si <span class="math inline">\(a,b\in \mathbb{R}\)</span>, <span class="math inline">\(\sigma(aX+b)^2=a^2 \sigma(X)^2\)</span> i <span class="math inline">\(\sigma(aX+b)=|a|\cdot \sigma(X)\)</span>.</p></li>
<li><p>Si <span class="math inline">\(X_1,\ldots,X_n\)</span> són variables aleatòries <strong>independents</strong> (i, en principi, només en aquest cas) i <span class="math inline">\(a_1,\ldots,a_n,b\in \mathbb{R}\)</span>,
<span class="math display">\[
\begin{array}{l}
\sigma(a_1X_1+\cdots+a_nX_n+b)^2=a_1\cdot\sigma(X_1)^2+\cdots+a_n\cdot\sigma(X_n)^2\\
\sigma(a_1X_1+\cdots+a_nX_n+b)=\sqrt{a_1\cdot\sigma(X_1)^2+\cdots+a_n\cdot\sigma(X_n)^2}
\end{array}
\]</span>
Si no són independents, aquestes igualtats poden ser falses.</p></li>
</ul>
<p>El <strong>quantil d’ordre <span class="math inline">\(p\)</span></strong> (o <strong><span class="math inline">\(p\)</span>-quantil</strong>) d’una variable aleatòria contínua <span class="math inline">\(X\)</span> és el valor <span class="math inline">\(x_p\in \mathbb{R}\)</span> més petit tal que
<span class="math display">\[
F_X(x_p)=P(X\leqslant x_p)=p
\]</span></p>

<div class="rmdcorbes">
Observau que, com que <span class="math inline">\(F_X(x)\)</span> és contínua, tendeix a 0 (la probabilitat del conjunt buit) quan <span class="math inline">\(x\to -\infty\)</span>, i tendeix a 1 (la probabilitat de tot <span class="math inline">\(\mathbb{R}\)</span>) quan <span class="math inline">\(x\to +\infty\)</span>, pel Teorema del Valor Mitjà de les funcions contínues (que diu, bàsicament, que les funcions contínues no peguen bots) pren tots els valors de l’interval <span class="math inline">\((0,1)\)</span> i per tant, per a qualsevol <span class="math inline">\(p\in (0,1)\)</span>, existeix qualque <span class="math inline">\(x\)</span> tal que <span class="math inline">\(F_X(x)=p\)</span>.
</div>
<p>La <strong>mediana</strong> de <span class="math inline">\(X\)</span> és el seu 0.5-quantil, el <strong>primer</strong> i <strong>tercer quartils</strong> són el seu 0.25-quantil i el seu 0.75-quantil, etc.</p>
</div>
</div>
<div id="sec:normal" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Variables aleatòries normals</h2>
<p>Una variable aleatòria contínua <span class="math inline">\(X\)</span> és <strong>normal</strong> (o <strong>té distribució normal</strong>) <strong>de paràmetres <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span></strong> (per abreujar, <span class="math inline">\(N(\mu,\sigma)\)</span>) quan la seva funció de densitat és
<span class="math display">\[
f_{X}(x)=\frac{1}{\sqrt{2\pi}\sigma} e^{{-(x-\mu)^2}/{2\sigma^{2}}}
\]</span></p>
<p>Naturalment, no us heu de saber aquesta fórmula.</p>
<p><img src="Bioestadistica-II_files/figure-html/censored.png" width="35%" style="display: block; margin: auto;" /></p>
<p>Però sí que heu de saber que:</p>
<ul>
<li><p>Una variable aleatòria normal <span class="math inline">\(X\)</span> és contínua, i per tant <span class="math inline">\(P(X=x)=0\)</span>, <span class="math inline">\(P(X\leqslant x)=P(X&lt;x)\)</span> etc.</p></li>
<li><p>Si <span class="math inline">\(X\)</span> és normal, la seva funció de distribució <span class="math inline">\(F_X\)</span> és <strong>injectiva i creixent</strong>: si <span class="math inline">\(x&lt;y\)</span>, <span class="math inline">\(F_X(x)&lt;F_X(y)\)</span>.</p></li>
<li><p>Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, aleshores <span class="math inline">\(\mu_X=\mu\)</span> i <span class="math inline">\(\sigma_X=\sigma\)</span>.</p></li>
</ul>
<p>Una variable aleatòria normal diem que és <strong>estàndard</strong> (o <strong>típica</strong>) quan és <span class="math inline">\(N(0,1)\)</span>. Normalment indicarem les variables normals estàndard amb <span class="math inline">\(Z\)</span>. Observau, doncs, que si <span class="math inline">\(Z\)</span> és normal estàndard, <span class="math inline">\(\mu_Z=0\)</span> i <span class="math inline">\(\sigma_Z=1\)</span>.</p>
<p>La gràfica de la densitat d’una variable aleatòria normal és la famosa <strong>campana de Gauss</strong>:</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-93"></span>
<img src="Bioestadistica-II_files/figure-html/unnamed-chunk-93-1.png" alt="Densitat d'una variable normal estàndard" width="50%" />
<p class="caption">
Figura 2.5: Densitat d’una variable normal estàndard
</p>
</div>
<p>La distribució normal és una distribució teòrica, no la trobareu exacta en la vida real. I malgrat el seu nom, no és més “normal” que altres distribucions contínues.</p>
<p><img src="Bioestadistica-II_files/figure-html/paranormal.png" width="40%" style="display: block; margin: auto;" /></p>
<p>Però és molt important, pel fet que moltes distribucions de la vida real són aproximadament normals. El motiu és que:</p>
<blockquote>
<p>Si una variable aleatòria consisteix a prendre un nombre <strong>molt gran</strong> <span class="math inline">\(n\)</span> de mesures independents d’una o diverses variables aleatòries i sumar-les, aleshores té distribució aproximadament normal, encara que les variables aleatòries de partida no ho siguin.</p>
</blockquote>

<div class="example">
<p><span id="exm:unnamed-chunk-95" class="example"><strong>Exemple 2.8  </strong></span>Una variable binomial <span class="math inline">\(B(n,p)\)</span> s’obté prenent <span class="math inline">\(n\)</span> mesures independents d’una variable Bernoulli <span class="math inline">\(Be(p)\)</span> i sumant-les. Per tant, per la “regla” anterior, una <span class="math inline">\(B(n,p)\)</span> hauria de ser aproximadament normal si <span class="math inline">\(n\)</span> és gran. Doncs sí, si <span class="math inline">\(n\)</span> és gran (posem a partir de 40, encara que si <span class="math inline">\(p\)</span> és molt propera a 0 o 1, la mida de les mostres ha de ser més gran), una variable <span class="math inline">\(X\)</span> binomial <span class="math inline">\(B(n,p)\)</span> és aproximadament normal <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>, on recordau que, si <span class="math inline">\(X\)</span> és <span class="math inline">\(B(n,p)\)</span>, aleshores <span class="math inline">\(\mu_X=np\)</span> i <span class="math inline">\(\sigma_X=\sqrt{np(1-p)}\)</span>. Aquest “aproximadament” significa que la densitat i la distribució de <span class="math inline">\(X\)</span> són aproximadament les de la normal.</p>
</div>
<p>Per exemple, el gràfic següent compara les funcions de distribució d’una binomial <span class="math inline">\(B(40,0.3)\)</span> i una normal <span class="math inline">\(N(40\cdot 0.3,\sqrt{40\cdot 0.3\cdot 0.7})\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-96"></span>
<img src="Bioestadistica-II_files/figure-html/unnamed-chunk-96-1.png" alt="Funcions de distribució de B(40,0.3) i N(400.3,sqrt(500.30.7)" width="50%" />
<p class="caption">
Figura 2.6: Funcions de distribució de B(40,0.3) i N(400.3,sqrt(500.30.7)
</p>
</div>

<div class="rmdrecordau">
En els propers temes emprarem sovint que una variable <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(n\)</span> és gran és aproximadament <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>.
</div>

<div class="example">
<p><span id="exm:unnamed-chunk-98" class="example"><strong>Exemple 2.9  </strong></span>Podem entendre que, amb una variable de Poisson, observam tots els punts d’un espai o tots els instants d’un període de temps i sumam tots els Èxits que hi trobam. Doncs, un altre cop, si <span class="math inline">\(X\)</span> és una variable aleatòria de Poisson <span class="math inline">\(Po(\lambda)\)</span> i <span class="math inline">\(\lambda\)</span> és gran, aleshores <span class="math inline">\(X\)</span> és aproximadament <span class="math inline">\(N(\lambda,\sqrt{\lambda})\)</span>.</p>
</div>
<p>Per exemple, el gràfic següent compara les funcions de distribució d’una Poisson <span class="math inline">\(Po(70)\)</span> i una normal <span class="math inline">\(N(70,\sqrt{70})\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-99"></span>
<img src="Bioestadistica-II_files/figure-html/unnamed-chunk-99-1.png" alt="Funcions de distribució de Pois(70) i N(70,sqrt(70))" width="50%" />
<p class="caption">
Figura 2.7: Funcions de distribució de Pois(70) i N(70,sqrt(70))
</p>
</div>

<div class="rmdcaution">
<p>Quan s’aproxima una variable discreta <span class="math inline">\(X\)</span> que només pot prendre com a valors nombres naturals, com ara una binomial o una Poisson, per mitjà d’una variable normal <span class="math inline">\(Y\)</span>, és convenient aplicar l’anomenada <strong>correcció de continuïtat</strong>: per a cada <span class="math inline">\(n\in \mathbb{N}\)</span>, aproximar:</p>
<ul>
<li><p><span class="math inline">\(P(X\leqslant n)\)</span> per mitjà de <span class="math inline">\(P(Y&lt; n+1/2)\)</span></p></li>
<li><p><span class="math inline">\(P(X=n)\)</span> per mitjà de <span class="math inline">\(P(n-1/2&lt; Y&lt; n+1/2)\)</span></p></li>
</ul>
Vegeu l’Exemple <a href="chap-varal.html#exm:corrcont">2.10</a> més a baix.
</div>
<div id="amb-r" class="section level3" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Amb R</h3>
<p>Per calcular probabilitats d’una <span class="math inline">\(N(\mu,\sigma)\)</span>, cal calcular les integrals a mà.</p>
<p><img src="Bioestadistica-II_files/figure-html/emorisa.png" width="20%" style="display: block; margin: auto;" /></p>
<p>O podeu usar R, per a qui la normal és <code>norm</code>. Per tant, si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>:</p>
<ul>
<li><p><code>dnorm(x,mu,sigma)</code> dóna el valor de la densitat <span class="math inline">\(f_X(x)\)</span></p></li>
<li><p><code>pnorm(x,mu,sigma)</code> dóna el valor de la distribució <span class="math inline">\(F_X(x)=P(X\leqslant x)\)</span></p></li>
<li><p><code>qnorm(q,mu,sigma)</code> dóna el <span class="math inline">\(q\)</span>-quantil de <span class="math inline">\(X\)</span></p></li>
<li><p><code>rnorm(n,mu,sigma)</code> dóna un vector de <span class="math inline">\(n\)</span> nombres aleatoris generats amb aquesta distribució</p></li>
</ul>
<p>Així, per exemple, si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(1,2)\)</span></p>
<ul>
<li><span class="math inline">\(P(X\leqslant 1.5)\)</span> és</li>
</ul>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="chap-varal.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.5</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.5987063</code></pre>
<ul>
<li>El 0.4-quantil de <span class="math inline">\(X\)</span>, és a dir, el valor <span class="math inline">\(q\)</span> tal que <span class="math inline">\(P(X\leqslant q)=0.4\)</span> és</li>
</ul>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="chap-varal.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.4</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.4933058</code></pre>
<ul>
<li><span class="math inline">\(P(X=1.5)\)</span> és</li>
</ul>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="chap-varal.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="fl">1.5</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.1933341</code></pre>

<div class="rmderror">
No! Com que <span class="math inline">\(X\)</span> és contínua, <span class="math inline">\(P(X=1.5)=0\)</span>. El que us dóna <code>dnorm(1.5,1,2)</code> és el valor de la funció de densitat de <span class="math inline">\(X\)</span> en 1.5, que no creiem que us interessi gaire.
</div>
<p>Si la normal és estàndard, no fa falta entrar la <span class="math inline">\(\mu=0\)</span> i la <span class="math inline">\(\sigma=1\)</span> (són els valors per defecte d’aquests paràmetres per a <code>norm</code>). Així, si <span class="math inline">\(Z\)</span> és <span class="math inline">\(N(0,1)\)</span>:</p>
<ul>
<li><span class="math inline">\(P(Z\leqslant 1.5)\)</span> és</li>
</ul>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="chap-varal.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.5</span>)</span></code></pre></div>
<pre><code>## [1] 0.9331928</code></pre>
<ul>
<li>El seu 0.95-quantil és</li>
</ul>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="chap-varal.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## [1] 1.644854</code></pre>
<ul>
<li>Què val <span class="math inline">\(P(-1\leqslant Z\leqslant 1)\)</span>? Com que <span class="math inline">\(P(-1\leqslant Z\leqslant 1)=P(Z\leqslant 1)-P(Z\leqslant -1)\)</span>, és</li>
</ul>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="chap-varal.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">1</span>)<span class="sc">-</span><span class="fu">pnorm</span>(<span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.6826895</code></pre>

<div class="example">
<p><span id="exm:corrcont" class="example"><strong>Exemple 2.10  </strong></span>A la secció anterior, us hem dit que una variable binomial <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(n\)</span> gran s’aproxima per mitjà d’una variable normal <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>. Així, per exemple, una variable <span class="math inline">\(X\)</span> binomial <span class="math inline">\(B(400,0.2)\)</span> s’aproxima per mitjà d’una variable <span class="math inline">\(Y\)</span> normal <span class="math inline">\(N(400\cdot 0.2,\sqrt{400\cdot 0.2\cdot 0.8})=N(80,8)\)</span>. Vegem amb alguns exemples que aquesta aproximació és millor aplicant-hi la correcció de continuïtat:</p>
</div>
<ul>
<li><span class="math inline">\(F_X(70)=P(X\leqslant 70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="chap-varal.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">70</span>,<span class="dv">400</span>,<span class="fl">0.2</span>)</span></code></pre></div>
<pre><code>## [1] 0.1163917</code></pre>
<ul>
<li><span class="math inline">\(F_Y(70)=P(Y\leqslant 70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="chap-varal.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.1056498</code></pre>
<ul>
<li>La correcció de continuïtat ens diu que és millor aproximar <span class="math inline">\(P(X\leqslant 70)\)</span> per mitjà de <span class="math inline">\(P(Y&lt; 70+1/2)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="chap-varal.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">70.5</span>,<span class="dv">80</span>,<span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.1175152</code></pre>
<ul>
<li><span class="math inline">\(f_X(70)=P(X=70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="chap-varal.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">70</span>,<span class="dv">400</span>,<span class="fl">0.2</span>) </span></code></pre></div>
<pre><code>## [1] 0.02338443</code></pre>
<ul>
<li><span class="math inline">\(f_Y(70)\)</span> (que <strong>no és</strong> <span class="math inline">\(P(Y=70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="chap-varal.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">8</span>) </span></code></pre></div>
<pre><code>## [1] 0.02283114</code></pre>
<ul>
<li>La correcció de continuïtat ens diu que és millor aproximar <span class="math inline">\(P(X=70)\)</span> per mitjà de <span class="math inline">\(P(70-1/2&lt;Y&lt; 70+1/2)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="chap-varal.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">70.5</span>,<span class="dv">80</span>,<span class="dv">8</span>) <span class="sc">-</span><span class="fu">pnorm</span>(<span class="fl">69.5</span>,<span class="dv">80</span>,<span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.02283949</code></pre>

<div class="example">
<p><span id="exm:exhiperhipo" class="example"><strong>Exemple 2.11  </strong></span>La pressió sistòlica, mesurada en mm Hg, es distribueix com una variable normal amb valor mitjà i desviació típica que depenen del sexe i l’edat. Per a la franja d’edat 16-24 anys, aquests valors (s’estima que) són:</p>
<ul>
<li>Per a homes, <span class="math inline">\(\mu=124\)</span> i <span class="math inline">\(\sigma=13.7\)</span></li>
<li>Per a dones, <span class="math inline">\(\mu=117\)</span> i <span class="math inline">\(\sigma=13.7\)</span></li>
</ul>
<p>El model d’hipertensió-hipotensió acceptat és el descrit en la Figura <a href="chap-varal.html#fig:hiperhipo">2.8</a>. Volem calcular els límits de cada classe per a cada sexe en aquest grup d’edat.</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:hiperhipo"></span>
<img src="Bioestadistica-II_files/figure-html/hiperhipo.png" alt="Model d'hipertensió-hipotensió." width="80%" />
<p class="caption">
Figura 2.8: Model d’hipertensió-hipotensió.
</p>
</div>
<p>Vegem:</p>
<ul>
<li>El límit superior del grup d’hipotensió serà el valor que deixa a l’esquerra un 5% de les tensions: el 0.05-quantil de la distribució.</li>
<li>El límit superior del grup de risc d’hipotensió serà el valor que deixa a l’esquerra un 10% de les tensions: el 0.1-quantil de la distribució.</li>
<li>El límit inferior del grup de risc d’hipertensió serà el valor que deixa a l’esquerra un 90% de les tensions: el 0.9-quantil de la distribució.</li>
<li>El límit inferior del grup d’hipertensió serà el valor que deixa a l’esquerra un 95% de les tensions: el 0.95-quantil de la distribució.</li>
</ul>
<p>En els homes, la tensió sistòlica és una variable aleatòria <span class="math inline">\(N(124,13.7)\)</span>. Aleshores, aquests quantils són:</p>
<ul>
<li>El 0.05-quantil:</li>
</ul>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="chap-varal.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fl">0.05</span>,<span class="dv">124</span>,<span class="fl">13.7</span>),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 101.5</code></pre>
<ul>
<li>El 0.1-quantil:</li>
</ul>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="chap-varal.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fl">0.1</span>,<span class="dv">124</span>,<span class="fl">13.7</span>),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 106.4</code></pre>
<ul>
<li>El 0.9-quantil:</li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="chap-varal.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fl">0.9</span>,<span class="dv">124</span>,<span class="fl">13.7</span>),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 141.6</code></pre>
<ul>
<li>El 0.95-quantil:</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="chap-varal.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">qnorm</span>(<span class="fl">0.95</span>,<span class="dv">124</span>,<span class="fl">13.7</span>),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 146.5</code></pre>
<p>En resum, per als homes de 16 a 24 anys tenim els límits de la Taula <a href="chap-varal.html#tab:tensio">2.1</a>.</p>
<table>
<caption><span id="tab:tensio">Taula 2.1: </span>Límits d’hipotensió-hipertensió en homes joves.</caption>
<thead>
<tr class="header">
<th align="left">Grup</th>
<th align="left">Interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Hipotens</td>
<td align="left">&lt;101.5</td>
</tr>
<tr class="even">
<td align="left">Prehipotens</td>
<td align="left">101.5 a 106.4</td>
</tr>
<tr class="odd">
<td align="left">Normotens</td>
<td align="left">106.4 a 141.6</td>
</tr>
<tr class="even">
<td align="left">Prehipertens</td>
<td align="left">141.6 a 146.5</td>
</tr>
<tr class="odd">
<td align="left">Hipertens</td>
<td align="left">&gt; 146.5</td>
</tr>
</tbody>
</table>

<div class="rmdexercici">
Calculau els límits per a les dones.
</div>
</div>
<div id="propietats-bàsiques" class="section level3" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> Propietats bàsiques</h3>
<p>Ja hem explicat el significat dels paràmetres <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span>, però el tornam a repetir:</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, aleshores <span class="math inline">\(\mu_X=\mu\)</span> i <span class="math inline">\(\sigma_X=\sigma\)</span>.
</div>
<p>Una de les propietats clau de la distribució normal és la seva simetria:</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, la seva densitat <span class="math inline">\(f_X\)</span> és simètrica respecte de <span class="math inline">\(\mu\)</span>, és a dir,
<span class="math display">\[
f_{X}(\mu-x)=f_{X}(\mu+x),
\]</span>
i pren el valor màxim a <span class="math inline">\(x=\mu\)</span>. És a dir, <span class="math inline">\(\mu\)</span> és la <strong>moda</strong> de <span class="math inline">\(X\)</span>.
</div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-123-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Per tant, el valor al voltant del qual és més probable que una variable normal <span class="math inline">\(N(\mu,\sigma)\)</span> caigui és justament el seu valor esperat <span class="math inline">\(\mu\)</span>.</p>
<p>En particular, si <span class="math inline">\(Z\)</span> és <span class="math inline">\(N(0,1)\)</span>, llavors <span class="math inline">\(f_Z\)</span> és simètrica al voltant de 0, és a dir, <span class="math inline">\(f_{Z}(-x)=f_{Z}(x)\)</span>, i la moda de <span class="math inline">\(Z\)</span> és <span class="math inline">\(x=0\)</span>.</p>
<p>Recordau que la funció de distribució d’una variable aleatòria contínua <span class="math inline">\(X\)</span>,
<span class="math display">\[
F_X(x)=P(X\leqslant x)
\]</span>
és l’àrea compresa entre la densitat <span class="math inline">\(y=f_X(x)\)</span> i l’eix d’abscisses a l’esquerra de <span class="math inline">\(x\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-124-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Llavors, la simetria de <span class="math inline">\(f_X\)</span> fa que, per a tot <span class="math inline">\(x\geqslant 0\)</span>, les àrees a l’esquerra de <span class="math inline">\(\mu-x\)</span> i a la dreta de <span class="math inline">\(\mu+x\)</span> siguin iguals.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-125-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>És a dir,
<span class="math display">\[
P(X\leqslant \mu-x)=P(X\geqslant \mu+x)=1-P(X\leqslant \mu+x)
\]</span></p>
<p>En particular (prenent <span class="math inline">\(x=0\)</span>)
<span class="math display">\[
P(X\leqslant \mu)=1-P(X\leqslant \mu)\Rightarrow P(X\leqslant \mu)=0.5
\]</span>
i per tant, <span class="math inline">\(\mu\)</span> és també la <strong>mediana</strong> de <span class="math inline">\(X\)</span>.</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, <span class="math inline">\(\mu\)</span> és la mitjana, la mediana i la moda de <span class="math inline">\(X\)</span>.
</div>
<p>En el cas concret de la normal estàndard <span class="math inline">\(Z\)</span>, per a qualsevol <span class="math inline">\(z\geqslant 0\)</span> es té que les àrees a l’esquerra de <span class="math inline">\(-z\)</span> i a la dreta de <span class="math inline">\(z\)</span> són iguals
<span class="math display">\[
P(Z\leqslant -z)=P(Z\geqslant z)=1-P(Z\leqslant z)
\]</span>
i la mediana de <span class="math inline">\(Z\)</span> és 0.</p>

<div class="rmdnote">
Ara que sabem més coses de la normal, a l’Exemple <a href="chap-varal.html#exm:exhiperhipo">2.11</a> ens haguéssim pogut estalviar la meitat de la feina: per la simetria, el 0.95-quantil ha d’estar a la mateixa distància de <span class="math inline">\(\mu\)</span> que el 0.05-quantil, però a la dreta. És a dir, com que <span class="math inline">\(\mu=124\)</span> i el 0.05-quantil havia estat 101.5, el 0.95-quantil ha de ser el valor a la dreta de 124 i a la mateixa distància d’aquest que 101.5:
<span class="math display">\[
124+(124-101.5)=146.5
\]</span>
El mateix passa amb el 0.9-quantil i el 0.1-quantil, comprovau-ho.
</div>
<p>Si <span class="math inline">\(\mu\)</span> creix, desplaça a la dreta l’eix vertical de simetria de la densitat, i amb ell tota la corba.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-129-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Si <span class="math inline">\(\sigma\)</span> creix, la corba s’aplana: en augmentar la desviació típica, els valors són més variats i augmenta la probabilitat que prenguin valors més llunyans de <span class="math inline">\(\mu\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-130-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>El gràfic següent mostra l’efecte combinat:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-131-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Indicarem amb <span class="math inline">\(z_q\)</span> el <strong><span class="math inline">\(q\)</span>-quantil</strong> d’una variable normal estàndard <span class="math inline">\(Z\)</span>. És a dir, <span class="math inline">\(z_q\)</span> és el valor tal que <span class="math inline">\(P(Z\leqslant z_q)=q\)</span>.</p>
<p>A banda del fet que <span class="math inline">\(z_{0.5}=0\)</span> (la mediana de <span class="math inline">\(Z\)</span> és 0), hi ha dos quantils més de la normal estàndard <span class="math inline">\(Z\)</span> que hauríeu de recordar:</p>
<ul>
<li><p><span class="math inline">\(z_{0.95}=1.64\)</span>; és a dir, <span class="math inline">\(P(Z\leqslant 1.64)=0.95\)</span> i per tant <span class="math inline">\(P(Z\leqslant -1.64)=P(Z\geqslant 1.64)=0.05\)</span> (és a dir, <span class="math inline">\(z_{0.05}=-1.64\)</span>) i
<span class="math display">\[
P(-1.64\leqslant Z\leqslant 1.64)=0.9.
\]</span></p></li>
<li><p><span class="math inline">\(z_{0.975}=1.96\)</span>; és a dir, <span class="math inline">\(P(Z\leqslant 1.96)=0.975\)</span> i per tant <span class="math inline">\(P(Z\leqslant -1.96)=P(Z\geqslant 1.96)=0.025\)</span> (és a dir, <span class="math inline">\(z_{0.025}=-1.96\)</span>) i
<span class="math display">\[
P(-1.96\leqslant Z\leqslant 1.96)=0.95.
\]</span></p></li>
</ul>

<div class="rmdmercifulgod">
Molt sovint el valor 1.96 de <span class="math inline">\(z_{0.975}\)</span> s’aproxima per 2. Teniu permís per a fer-ho quan no disposeu de mitjans (R, aplis de mòbil) per a calcular quantils i us considereu incapaços de recordar “1.96”. Però només en aquest cas.
</div>
<p>Una de les propietats de la distribució normal que ens faciliten molt la vida és que <strong>tota combinació lineal de variables aleatòries normals independents és normal</strong>. En concret, tenim els dos resultats següents:</p>

<div class="theorem">
<p><span id="thm:comblinnormals" class="theorem"><strong>Teorema 2.5  </strong></span>Sigui <span class="math inline">\(X\)</span> una variable <span class="math inline">\(N(\mu,\sigma)\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>Per a tots <span class="math inline">\(a,b\in \mathbb{R}\)</span>, <span class="math inline">\(aX+b\)</span> és normal <span class="math inline">\(N(a\mu+b,|a|\cdot\sigma)\)</span>.</p></li>
<li><p>En particular, la <strong>tipificada</strong> de <span class="math inline">\(X\)</span>
<span class="math display">\[
Z=\dfrac{X-\mu}{\sigma}
\]</span>
és normal estàndard.</p>
</div></li>
</ol>
<p>Més en general:</p>

<div class="theorem">
<span id="thm:comblinnormals2" class="theorem"><strong>Teorema 2.6  </strong></span>Si <span class="math inline">\(X_1,\ldots,X_n\)</span> són variables aleatòries normals <strong>independents</strong> i <span class="math inline">\(a_1,\ldots,a_n,b\in \mathbb{R}\)</span>, llavors <span class="math inline">\(a_1X_1+\cdots +a_nX_n+b\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span> amb
<span class="math display">\[
\mu=a_1\mu_1+\cdots +a_n\mu_n+b,\ 
\sigma=\sqrt{a_1^2\sigma^2_1+\cdots +a_n^2\sigma^2_n}
\]</span>
</div>

<div class="rmdnote">
Que tota combinació lineal de variables normals torni a ser del mateix tipus, és a dir, normal, és una propietat molt útil de les variables normals que poques famílies de distribucions comparteixen. Per exemple, si <span class="math inline">\(X\)</span> és una variable binomial <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(p\neq 0\)</span>, la variable <span class="math inline">\(2X\)</span> no és binomial, perquè només pren valors parells, mentre que una variable binomial <span class="math inline">\(B(m,q)\)</span> ha de poder prendre tots els valors entre 0 i <span class="math inline">\(m\)</span>.
</div>
<p>Les probabilitats de la normal tipificada determinen les de la normal original, perquè si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>:
<span class="math display">\[
\begin{array}{rl}
P(a\leqslant X\leqslant b)\!\!\!\!\! &amp; \displaystyle =P\Big( \frac{a-\mu}{\sigma}\leqslant \frac{X-\mu}{\sigma}\leqslant \frac{b-\mu}{\sigma}\Big)\\ &amp; \displaystyle =P\Big(\frac{a-\mu}{\sigma}\leqslant Z\leqslant \frac{b-\mu}{\sigma}\Big)
\end{array}
\]</span>
Això serveix per deduir fórmules o resoldre problemes com el següent, i els vostres pares ho empraven per calcular probabilitats de normals (amb taules de probabilitats de la normal estàndard); ara és més còmode usar una apli.</p>

<div class="example">
<p><span id="exm:percentalcades" class="example"><strong>Exemple 2.12  </strong></span>Les alçades de les nordamericanes de 20 anys segueixen una distribució normal. S’ha estimat que un 10% d’elles fan menys de 1.55 m, i un 30.5% fan menys de 1.60 m. Per a quina alçada <span class="math inline">\(h\)</span> es té que un 95% de les nordamericanes de 18 anys fan menys de <span class="math inline">\(h\)</span> metres?</p>
<pre><code>&lt;/div&gt;\EndKnitrBlock{example}</code></pre>
<p>Diguem <span class="math inline">\(X\)</span> a la variable “Prenc una nord americana de 20 anys i mesur la seva alçada en m”. Sabem que és <span class="math inline">\(N(\mu,\sigma)\)</span>, però desconeixíem <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span>.</p>
<p>Ens diuen que
<span class="math display">\[
P(X&lt; 1.55)=0.1,\ P(X&lt; 1.60)=0.305
\]</span>
i amb això volem calcular la <span class="math inline">\(h\)</span> tal que <span class="math inline">\(P(X\leqslant h)=0.95\)</span>, és a dir, el 0.95-quantil de <span class="math inline">\(X\)</span>. El que farem serà, tipificant la <span class="math inline">\(X\)</span>, traduir la informació que ens han donat a quantils d’una normal estàndard <span class="math inline">\(Z\)</span>:
<span class="math display">\[
\begin{array}{l}
\displaystyle  0.1=P(X&lt; 1.55)=P\Big(\frac{X-\mu}{\sigma}&lt;\frac{1.55-\mu}{\sigma}\Big)=P\Big(Z&lt;\frac{1.55-\mu}{\sigma}\Big)\\
\displaystyle  \qquad \Longrightarrow \frac{1.55-\mu}{\sigma}=z_{0.1}\\
\displaystyle 0.305=P(X&lt; 1.6)=P\Big(\frac{X-\mu}{\sigma}&lt;\frac{1.6-\mu}{\sigma}\Big)=P\Big(Z&lt;\frac{1.6-\mu}{\sigma}\Big)\\
\displaystyle  \qquad \Longrightarrow \frac{1.6-\mu}{\sigma}=z_{0.305}
\end{array}
\]</span>
Ara podem calcular aquests dos quantils <span class="math inline">\(z_{0.1}\)</span> i <span class="math inline">\(z_{0.305}\)</span>:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="chap-varal.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.1</span>)</span></code></pre></div>
<pre><code>## [1] -1.281552</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="chap-varal.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.305</span>)</span></code></pre></div>
<pre><code>## [1] -0.5100735</code></pre>
<p>Obtenim d’aquesta manera el sistema d’equacions lineals
<span class="math display">\[
\left.
\begin{array}{ll}
1.55-\mu=-1.282\sigma\\
1.6-\mu=-0.51\sigma
\end{array}\right\}
\]</span>
El resolem i obtenim
<span class="math display">\[
\mu=1.633,\ \sigma=0.065
\]</span>
I ara ja podem calcular la <span class="math inline">\(h\)</span> com el 0.95-quantil d’una <span class="math inline">\(N(1.633,0.065)\)</span>:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="chap-varal.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>,<span class="fl">1.633</span>,<span class="fl">0.065</span>)</span></code></pre></div>
<pre><code>## [1] 1.739915</code></pre>
<p>Concloem que un 95% de les nord americanes de 20 anys fan menys de 1.74 m.</p>
</div>
<div id="intervals-de-referència" class="section level3" number="2.5.3">
<h3><span class="header-section-number">2.5.3</span> Intervals de referència</h3>
<p>Un <strong>interval de referència</strong> del <span class="math inline">\(100q\%\)</span> per a una variable aleatòria <span class="math inline">\(X\)</span> és un interval <span class="math inline">\([a,b]\)</span> tal que
<span class="math display">\[
P(a\leqslant X\leqslant b)=q.
\]</span>
És a dir, un interval de referència del <span class="math inline">\(100q\%\)</span> per a <span class="math inline">\(X\)</span> és un interval que conté els valors de <span class="math inline">\(X\)</span> del <span class="math inline">\(100q\%\)</span> dels subjectes de la població.</p>
<p>Per exemple, hem vist en la secció anterior que [-1.64,1.64] i [-1.96,1.96] són intervals de referència del 90% i del 95%, respectivament, per a una variable normal estàndard <span class="math inline">\(Z\)</span>.</p>
<p>Els més comuns són els intervals de referència del 95% (<span class="math inline">\(q=0.95\)</span>), que satisfan que
<span class="math display">\[
P(a\leqslant X\leqslant b)=0.95
\]</span>
i són els, que per exemple, us donen com a valors de referència en les analítiques:</p>
<p><img src="Bioestadistica-II_files/figure-html/analit.png" width="80%" style="display: block; margin: auto;" /></p>

<div class="rmdnote">
Quan es parla d’un <strong>interval de referència</strong> sense donar la probabilitat, se sobreentén sempre que és l’interval de referència del 95%.
</div>
<p>Quan <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, aquests intervals de referència es prenen sempre <strong>centrats en la mitjana</strong> <span class="math inline">\(\mu\)</span>, és a dir, de la forma
<span class="math display">\[
[\mu-\text{alguna cosa},\mu+\text{aquesta mateixa cosa}].
\]</span>
Es calculen amb el resultat següent:</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-138" class="theorem"><strong>Teorema 2.7  </strong></span>Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, un interval de referència del <span class="math inline">\(100q\%\)</span> per a <span class="math inline">\(X\)</span> és
<span class="math display">\[
[\mu- z_{(1+q)/2}\cdot \sigma, \mu+ z_{(1+q)/2}\cdot \sigma]
\]</span>
on <span class="math inline">\(z_{(1+q)/2}\)</span> indica el <span class="math inline">\((1+q)/2\)</span>-quantil de la normal estàndard <span class="math inline">\(Z\)</span>. Normalment escriurem aquest interval
<span class="math display">\[
\mu\pm z_{(1+q)/2}\cdot \sigma.
\]</span></p>
</div>

<div class="rmdcorbes">
<p>La demostració és un exemple d’ús de la tipificació de la normal:
<span class="math display">\[
\begin{array}{l}
P(\mu-x\leqslant X\leqslant \mu+x)=q\\
\qquad \Longleftrightarrow \displaystyle P\Big(\frac{\mu-x-\mu}{\sigma}\leqslant \frac{X-\mu}{\sigma}\leqslant \frac{\mu+x-\mu}{\sigma}\Big)=q\\
\qquad \Longleftrightarrow \displaystyle P(-x/{\sigma}\leqslant Z\leqslant {x}/{\sigma})=q\\
\qquad \Longleftrightarrow \displaystyle P(Z\leqslant {x}/{\sigma})-P(Z\leqslant -{x}/{\sigma})=q\\
\qquad \Longleftrightarrow \displaystyle P(Z\leqslant {x}/{\sigma})-(1-P(Z\leqslant {x}/{\sigma}))=q\\
\qquad \text{(per la simetria de $f_Z$ al voltant de 0)}\\
\qquad \Longleftrightarrow \displaystyle 2P(Z\leqslant {x}/{\sigma})=q+1\\
\qquad \Longleftrightarrow P(Z\leqslant {x}/{\sigma})=(1+q)/2\\
\qquad \Longleftrightarrow x/\sigma=
z_{(1+q)/2}\\
\qquad \Longleftrightarrow x=z_{(1+q)/2}\cdot \sigma
\end{array}
\]</span></p>
</div>
<p>Si <span class="math inline">\(q=0.95\)</span>, llavors <span class="math inline">\((1+q)/2=0.975\)</span> i <span class="math inline">\(z_{0.975}=1.96\)</span>. Per tant, l’interval de referència del 95% per a una variable <span class="math inline">\(X\)</span> normal <span class="math inline">\(N(\mu,\sigma)\)</span> és
<span class="math display">\[
\mu\pm 1.96\sigma.
\]</span>
I com que aquest 1.96 sovint s’aproxima per 2, l’interval de referència del 95% d’una <span class="math inline">\(N(\mu,\sigma)\)</span> se sol simplificar a
<span class="math display">\[
\mu\pm 2\sigma.
\]</span>
Això diu, bàsicament, que</p>
<blockquote>
<p>Si una població segueix una distribució normal <span class="math inline">\(N(\mu,\sigma)\)</span>, un 95% dels seus individus tenen el seu valor de <span class="math inline">\(X\)</span> a distància com a màxim <span class="math inline">\(2\sigma\)</span> (“a dues sigmes”) de <span class="math inline">\(\mu\)</span>.</p>
</blockquote>

<div class="example">
<p><span id="exm:unnamed-chunk-140" class="example"><strong>Exemple 2.13  </strong></span>Segons l’OMS, les altures (en cm) de les dones europees de 18 anys segueixen una llei <span class="math inline">\(N(163.1,18.53)\)</span>. Quin és l’interval d’altures centrat en la mitjana que conté a la meitat les europees de 18 anys?</p>
</div>
<p>Fixau-vos que, si diem <span class="math inline">\(X\)</span> a la variable aleatòria “Altura d’una dona europea de 18 anys en cm”, el que volem saber és l’interval centrat en la seva mitjana, 163.1, tal que la probabilitat que l’alçada d’una europea de 18 anys triada a l’atzar pertanyi a aquest interval sigui 0.5. És a dir, l’interval de referència del 50% per a <span class="math inline">\(X\)</span>.</p>
<p>Ens diuen que <span class="math inline">\(X\)</span> és <span class="math inline">\(N(163.1,18.53)\)</span>. Si <span class="math inline">\(q=0.5\)</span>, llavors <span class="math inline">\((1+q)/2=0.75\)</span>. El 0.75-quantil <span class="math inline">\(z_{0.75}\)</span> d’una normal estàndard és</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="chap-varal.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.75</span>)</span></code></pre></div>
<pre><code>## [1] 0.6744898</code></pre>
<p>Per tant, l’interval de referència demanat és <span class="math inline">\(163.1\pm 0.6745\cdot 18.53\)</span>, és a dir, arrodonint a mm, <span class="math inline">\([150.6, 175.6]\)</span>. Això ens diu que la meitat de les dones europees de 18 anys fan entre 150.6 i 175.6 cm.</p>
<p>El <strong>z-score</strong> d’un valor <span class="math inline">\(x_0\in \mathbb{R}\)</span> respecte d’una distribució <span class="math inline">\(N(\mu,\sigma)\)</span> és
<span class="math display">\[
\frac{x_0-\mu}{\sigma}
\]</span></p>
<p>És a dir, el z-score de <span class="math inline">\(x_0\)</span> és el resultat de “tipificar” <span class="math inline">\(x_0\)</span> en el sentit del Teorema <a href="chap-varal.html#thm:comblinnormals">2.5</a>.2.</p>
<p>Si la variable poblacional és normal, com més gran és el valor absolut del z-score de <span class="math inline">\(x_0\)</span>, més “rar” és <span class="math inline">\(x_0\)</span>; el signe ens diu si és més gran o més petit que el valor esperat <span class="math inline">\(\mu\)</span>.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-142" class="example"><strong>Exemple 2.14  </strong></span>Recordau que, segons l’OMS, les altures de les dones europees de 18 anys segueixen una llei <span class="math inline">\(N(163.1,18.53)\)</span>. Quin seria el z-score d’una jugadora de bàsquet de 18 anys que fes 191 cm?</p>
</div>
<p>Seria
<span class="math display">\[ 
\frac{191-163.1}{18.53}=1.5
\]</span></p>
<p>Això se sol llegir dient que l’alçada d’aquesta jugadora està <strong>1.5 sigmes per sobre de l’alçada mitjana</strong>.</p>
</div>
<div id="variables-log-normals" class="section level3" number="2.5.4">
<h3><span class="header-section-number">2.5.4</span> Variables log-normals</h3>
<p>Direm que <span class="math inline">\(X\)</span> és una variable  quan el seu logaritme neperià <span class="math inline">\(\ln(X)\)</span> és una variable normal. O, si ho preferiu, és una variable de la forma <span class="math inline">\(e^Y\)</span> amb <span class="math inline">\(Y\)</span> normal. Moltes concentracions d’enzims o anticossos tenen distribució aproximadament log-normal.</p>
<p>La densitat d’una variable log-normal és asimètrica, amb una cua a la dreta, com mostra la Figura <a href="chap-varal.html#fig:lognorm">2.9</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:lognorm"></span>
<img src="Bioestadistica-II_files/figure-html/lognorm-1.png" alt="Densitat de $e^Z$ amb $Z$ normal estàndard." width="50%" />
<p class="caption">
Figura 2.9: Densitat de <span class="math inline">\(e^Z\)</span> amb <span class="math inline">\(Z\)</span> normal estàndard.
</p>
</div>
<p>Recíprocament, molt sovint una variable la densitat de la qual mostri una pujada ràpida des del 0 a la moda i després una cua a la dreta, satisfà que el seu logaritme segueix una distribució aproximadament normal. Això serà útil més endavant.</p>
<p>Amb R, la distribució log-normal és <code>lnorm</code>. Els paràmetres que s’empren per descriure-la són els de la variable normal definida pel seu logaritme:</p>
<ul>
<li><p>La <em>mitjana en escala logarítmica</em> de <span class="math inline">\(X\)</span>: <span class="math inline">\(\mu_{\ln(X)}\)</span></p></li>
<li><p>La <em>desviació típica en escala logarítmica</em> de <span class="math inline">\(X\)</span>: <span class="math inline">\(\sigma_{\ln(X)}\)</span></p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-143" class="example"><strong>Exemple 2.15  </strong></span>La dosi letal <span class="math inline">\(Y\)</span> de la digitalina en ratolins (és la dir, la variable aleatòria que dóna la quantitat de digitalina que cal administrar a un ratolí per matar-lo) té distribució log-normal. Se sap que una injecció de 1cc de digitalina mata un 10% dels ratolins (és a dir, que la probabilitat que una dosi de 1cc o menys mati un ratolí és de 0.1: <span class="math inline">\(P(Y\leqslant 1)=0.1\)</span>) i que una injecció de 2cc mata un 75% dels ratolins (<span class="math inline">\(P(Y\leqslant 2)=0.75\)</span>).</p>
</div>
<p>Volem saber la dosi de digitalina (en cc) que és letal per al 95% dels ratolins. Aquest tipus d’experiments és la base de l’anomenat <strong>mètode probit</strong> per determinar la letalitat de substàncies.</p>
<p>Així doncs, volem calcular el valor <span class="math inline">\(a\)</span> tal que <span class="math inline">\(P(Y\leqslant a)=0.95\)</span>, que no és res més que el 0.95-quantil de <span class="math inline">\(Y\)</span>.</p>
<p>Com que el logaritme és injectiu, <span class="math inline">\(P(Y\leqslant x)=P(\ln(Y)\leqslant \ln(x))\)</span>. Per tant el pla és trobar el 0.95-quantil de <span class="math inline">\(\ln(Y)\)</span>, diguem-li <span class="math inline">\(b\)</span>, i aleshores tendrem <span class="math inline">\(a=e^b\)</span>.</p>
<p>Per simplificar, diguem <span class="math inline">\(X\)</span> a <span class="math inline">\(\ln(Y)\)</span>. Sabem que <span class="math inline">\(X\)</span> és normal, per tant només ens cal saber la seva <span class="math inline">\(\mu\)</span> i la seva <span class="math inline">\(\sigma\)</span> i podrem calcular el seu 0.95-quantil.</p>
<p>El que sabem és que
<span class="math display">\[
\begin{array}{l}
0.1=P(Y\leqslant 1)=P(X\leqslant \ln(1))=P(X\leqslant 0)\\
0.75=P(Y\leqslant 2)=P(X\leqslant \ln(2))
\end{array}
\]</span>
Com podem determinar la <span class="math inline">\(\mu\)</span> i la <span class="math inline">\(\sigma\)</span> de <span class="math inline">\(X\)</span> a partir d’aquests dos valors? Ja ens hem trobat en una situació semblant a l’Exemple <a href="chap-varal.html#exm:percentalcades">2.12</a>. El que fem és traduir aquesta informació en termes de quantils de la normal estàndard.</p>
<p><span class="math display">\[
\begin{array}{l}
\displaystyle 0.1=P(X\leqslant 0)=P\Big(\frac{X-\mu}{\sigma}\leqslant \frac{-\mu}{\sigma}\Big)=P\Big(Z\leqslant -\frac{\mu}{\sigma}\Big)\\
\displaystyle\qquad \Longrightarrow -\frac{\mu}{\sigma}=z_{0.1}=\texttt{qnorm(0.1)}=-1.2816\\
\displaystyle 0.75=P(X\leqslant \ln(2))=P\Big(\frac{X-\mu}{\sigma}\leqslant \frac{\ln(2)-\mu}{\sigma}\Big)=P\Big(Z\leqslant \frac{\ln(2)-\mu}{\sigma}\Big)\\
\displaystyle\qquad \Longrightarrow \frac{\ln(2)-\mu}{\sigma}=z_{0.75}=\texttt{qnorm(0.75)}=0.6745
\end{array}
\]</span>
Obtenim per tant el sistema d’equacions
<span class="math display">\[
\left.
\begin{array}{l}
\mu=1.2816\sigma\\
\ln(2)-\mu=0.6745\sigma
\end{array}
\right\}
\]</span>
i resolent-lo obtenim
<span class="math display">\[
\mu=0.4541,\quad \sigma=0.3544
\]</span></p>
<p>Ara podem calcular el 0.95-quantil de <span class="math inline">\(X\)</span>:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="chap-varal.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="fl">0.95</span>,<span class="fl">0.4541</span>,<span class="fl">0.3544</span>)</span></code></pre></div>
<pre><code>## [1] 1.037036</code></pre>
<p>Per tant <span class="math inline">\(P(X\leqslant 1.037)=0.95\)</span>. Per tant
<span class="math inline">\(P(Y\leqslant e^{1.037})=0.95\)</span>. Com que <span class="math inline">\(e^{1.037}=2.82\)</span>, concloem que 2.82 cc de digitalina són suficients per matar el 95% dels ratolins.</p>
<p>Ho podem comprovar (amb R, no escabetxant ratolins, malpensats!):</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="chap-varal.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plnorm</span>(<span class="fl">2.82</span>,<span class="fl">0.4541</span>,<span class="fl">0.3544</span>)</span></code></pre></div>
<pre><code>## [1] 0.9499129</code></pre>
</div>
</div>
<div id="test-de-la-lliçó-1" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> Test de la lliçó 1</h2>
<p><strong>(1)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria de mitjana <span class="math inline">\(\mu\)</span> i desviació típica <span class="math inline">\(\sigma\)</span>. Quina o quines de les afirmacions següents són sempre vertaderes?</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(E(X+2)=\mu+2\)</span>.</li>
<li><span class="math inline">\(\sigma(X+2)=\sigma+2\)</span>.</li>
<li><span class="math inline">\(\sigma(-X)=-\sigma\)</span>.</li>
<li><span class="math inline">\(\sigma(-X)=\sigma\)</span>.</li>
<li><span class="math inline">\(\sigma(X/2)=\sigma/2\)</span>.</li>
<li>Cap de les altres afirmacions és vertadera.</li>
</ol>
<p><strong>(2)</strong> La funció de distribució <span class="math inline">\(F_X(x)\)</span> d’una variable aleatòria <span class="math inline">\(X\)</span> ens dóna:</p>
<ol style="list-style-type: decimal">
<li>La probabilitat d’obtenir el valor <span class="math inline">\(x\)</span>.</li>
<li>La probabilitat d’obtenir un valor entre <span class="math inline">\(-x\)</span> i <span class="math inline">\(x\)</span>, tots dos extrems inclosos.</li>
<li>La probabilitat d’obtenir un valor entre <span class="math inline">\(0\)</span> i <span class="math inline">\(x\)</span>, tots dos extrems inclosos.</li>
<li>La probabilitat d’obtenir un valor més petit o igual que <span class="math inline">\(x\)</span>.</li>
<li>La probabilitat d’obtenir un valor estrictament més petit que <span class="math inline">\(x\)</span>.</li>
</ol>
<p><strong>(3)</strong> Quina o quines de les variables següents tenen distribució binomial?</p>
<ol style="list-style-type: decimal">
<li>El pes d’una persona triada a l’atzar.</li>
<li>Triam un nombre de llançaments a l’atzar, llançam aquest nombre de vegades una moneda, i comptam el nombre de cares.</li>
<li>El nombre de glòbuls vermells en 1 mm<sup>3</sup> de sang.</li>
<li>La proporció d’hipertensos en una mostra aleatòria de 50 individus.</li>
<li>Triam 10 estudiants diferents en una classe de 20, i comptam quantes dones han sortit.</li>
<li>Cap d’elles.</li>
</ol>
<p><strong>(4)</strong> Quina o quines de les variables següents tenen una distribució de Poisson?</p>
<ol style="list-style-type: decimal">
<li>El pes d’una persona triada a l’atzar.</li>
<li>El nombre de casos diaris de COVID-19 a Mallorca.</li>
<li>El nombre de glòbuls vermells en 1 mm<sup>3</sup> de sang.</li>
<li>La proporció d’hipertensos en una mostra aleatòria de 50 individus.</li>
<li>Triam 10 estudiants diferents en una classe de 20, i comptam quantes dones han sortit.</li>
</ol>
<p><strong>(5)</strong> El nombre anual d’accidents laborals d’un tipus concret segueix una distribució de Poisson. Al llarg del temps s’ha observat que el 55% dels anys no es produeix cap accident d’aquests. Quin valor estimes que té el paràmetre <span class="math inline">\(\lambda\)</span> d’aquesta distribució de Poisson?</p>
<ol style="list-style-type: decimal">
<li>0.55</li>
<li><span class="math inline">\(e^{-0.55}\)</span></li>
<li><span class="math inline">\(\ln(0.55)\)</span></li>
<li><span class="math inline">\(-\ln(0.55)\)</span></li>
<li>Un valor que no és cap dels proposats en les altres respostes.</li>
</ol>
<p><strong>(6)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua de funció de densitat:
<span class="math display">\[
f_X(x)=\left\{\begin{array}{ll}
0 &amp; \mbox{si $x&lt;0$}\\
\frac{2\sqrt{2}}{\sqrt{\pi}} e^{-2x^2} &amp; \mbox{si $x\geqslant 0$}
\end{array}
\right.
\]</span>
És cert que <span class="math inline">\(P(X=1)=2\sqrt{2}e^{-2}/\sqrt{\pi}\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No: en realitat <span class="math inline">\(P(X=1)=\int_{-\infty}^1 \frac{2\sqrt{2}}{\sqrt{\pi}} e^{-2x^2}\,dx\)</span> però no sé calcular aquesta integral, o sí que sé calcular-la, però em fa mandra fer-ho.</li>
<li>Això no és la funció de densitat d’una variable aleatòria contínua, perquè no és una funció contínua (en el 0 bota de 0 a <span class="math inline">\(2\sqrt{2}/\sqrt{\pi}\)</span>)</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(7)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua de mitjana <span class="math inline">\(\mu\)</span>. Què val <span class="math inline">\(P(X=\mu)\)</span>?</p>
<ol style="list-style-type: decimal">
<li>0.5</li>
<li><span class="math inline">\(\mu\)</span></li>
<li>0</li>
<li>Depèn de la variable aleatòria</li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(8)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua de moda <span class="math inline">\(M\)</span>. Què val <span class="math inline">\(P(X=M)\)</span>?</p>
<ol style="list-style-type: decimal">
<li>1</li>
<li>0.5</li>
<li>0</li>
<li>Depèn de la variable aleatòria, però és més gran que tots els altres valors de <span class="math inline">\(P(X=x)\)</span></li>
<li>Depèn de la variable aleatòria, però és el valor màxim de la funció de densitat de <span class="math inline">\(X\)</span>.</li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(9)</strong> Sigui <span class="math inline">\(Z\)</span> una variable aleatòria normal estàndard. Marca les afirmacions vertaderes.</p>
<ol style="list-style-type: decimal">
<li>És asimètrica a l’esquerra.</li>
<li>La seva mitjana és 1.</li>
<li>La seva desviació típica és 0.</li>
<li>La seva variància és 1.</li>
<li>La seva mediana és 0.</li>
</ol>
<p><strong>(10)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria <span class="math inline">\(N(\mu,\sigma)\)</span> i <span class="math inline">\(f_X\)</span> la seva funció de densitat. Què val l’àrea entre la corba <span class="math inline">\(y=f_X(x)\)</span> i l’eix d’abscisses?</p>
<ol style="list-style-type: decimal">
<li>0</li>
<li><span class="math inline">\(\mu\)</span></li>
<li><span class="math inline">\(\sigma\)</span></li>
<li>En general, no és ni <span class="math inline">\(\mu\)</span> ni <span class="math inline">\(\sigma\)</span>, però sí que depèn de <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span></li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(11)</strong> Siguin <span class="math inline">\(X\)</span> una variable aleatòria <span class="math inline">\(N(\mu,\sigma)\)</span>. Quina de les afirmacions següents és vertadera?</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\mu\)</span> és la mitjana de <span class="math inline">\(X\)</span>, però no la seva mediana</li>
<li><span class="math inline">\(\mu\)</span> és la mitjana i la mediana de <span class="math inline">\(X\)</span>, però no la seva moda</li>
<li><span class="math inline">\(\mu\)</span> és la mitjana, la mediana i la moda de <span class="math inline">\(X\)</span>, però no és veritat que <span class="math inline">\(P(X=\mu)&gt;P(X=a)\)</span> per a tot <span class="math inline">\(a\neq \mu\)</span></li>
<li><span class="math inline">\(\mu\)</span> és la mitjana, la mediana i la moda de <span class="math inline">\(X\)</span> i <span class="math inline">\(P(X=\mu)&gt;P(X=a)\)</span> per a tot <span class="math inline">\(a\neq \mu\)</span></li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(12)</strong> El FME (Flux Màxim d’Expiració) de les al·lotes d’11 anys segueix una distribució aproximadament normal de mitjana 300 l/min i desviació típica 20 l/min. Marca les afirmacions vertaderes:</p>
<ol style="list-style-type: decimal">
<li>Aproximadament la meitat de les al·lotes d’11 anys tenen un FME entre 280 l/min i 320 l/min.</li>
<li>Al voltant del 95% de les al·lotes d’11 anys tenen un FME entre 280 l/min i 320 l/min.</li>
<li>Al voltant del 95% de les al·lotes d’11 anys tenen un FME entre 260 l/min i 340 l/min.</li>
<li>Al voltant del 5% de les al·lotes d’11 anys tenen un FME inferior a 260 l/min.</li>
<li>Cap al·lota d’11 anys té FME superior a 360 l/min.</li>
</ol>
<p><strong>(13)</strong> Se sap que una variable bioquímica té com a mitjana 90 i desviació típica 10. Si prenem una mostra d’individus sans, és raonable esperar que aproximadament el 95% d’ells tenguin un valor d’aquesta variable comprès entre 70 i 110? (marca totes les respostes correctes):</p>
<ol style="list-style-type: decimal">
<li>Sí, sempre.</li>
<li>No, mai.</li>
<li>Si la variable té distribució normal, sí.</li>
<li>Si la mostra és prou gran, sí.</li>
<li>Si la variable té distribució normal i la mostra és prou gran, sí.</li>
</ol>
<p><strong>(14)</strong> En una variable aleatòria contínua, la seva funció de densitat (marca una sola resposta):</p>
<ol style="list-style-type: decimal">
<li>És sempre contínua</li>
<li>Mesura com és de dens el seu domini.</li>
<li>Aplicada a un nombre real, ens dóna la probabilitat d’obtenir-lo.</li>
<li>Aplicada a un nombre real, ens dóna la probabilitat d’obtenir un valor menor o igual que ell.</li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(15)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua de desviació típica <span class="math inline">\(\sigma\)</span>. Què val la variància de la variable aleatòria <span class="math inline">\(-X/2\)</span>?</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\sigma(-X/2)^2=-\sigma^2/2\)</span>.</li>
<li><span class="math inline">\(\sigma(-X/2)^2=\sigma^2/2\)</span>.</li>
<li><span class="math inline">\(\sigma(-X/2)^2=-\sigma^2/4\)</span>.</li>
<li><span class="math inline">\(\sigma(-X/2)^2=\sigma^2/4\)</span>.</li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(16)</strong> El temps que tarda a produir-se una determinada reacció bioquímica es distribueix segons una variable normal de mitjana 17 minuts i desviació típica 3 minuts. Sense fer cap càlcul, què podem deduir d’aquesta afirmació? Marca totes les respostes correctes:</p>
<ol style="list-style-type: decimal">
<li>Tots aquests temps se situen entre 8 i 26 minuts.</li>
<li>Gairebé tots aquests temps se situen entre 11 i 23 minuts.</li>
<li>És estrictament més probable que una reacció d’aquestes tardi entre 16 i 18 minuts que tardi entre 18 i 20 minuts.</li>
<li>És estrictament més probable que una reacció d’aquestes tardi entre 18 i 20 minuts que tardi entre 16 i 18 minuts.</li>
<li>És estrictament més probable que una reacció d’aquestes tardi entre 18 i 20 minuts que tardi entre 14 i 16 minuts.</li>
<li>Cap de les afirmacions anteriors és correcta.</li>
</ol>
<p><strong>(17)</strong> El temps que tarda a produir-se una determinada reacció bioquímica es distribueix segons una variable normal de mitjana 17 minuts i desviació típica 3 minuts. Quina és la probabilitat que tardi menys de 17 minuts?</p>
<ol style="list-style-type: decimal">
<li>0</li>
<li>0.5</li>
<li>1</li>
<li>17/3</li>
<li>17/2</li>
<li>Cap de les afirmacions anteriors és correcta.</li>
</ol>
<p><strong>(18)</strong> El temps que tarda a produir-se una determinada reacció bioquímica es distribueix segons una variable normal de mitjana 17 minuts i desviació típica 3 minuts. Quina o quines de les afirmacions següents són vertaderes?</p>
<ol style="list-style-type: decimal">
<li>Si poguéssim mesurar els temps amb precisió infinita, observaríem que el temps que tarda més sovint és exactament 17 minuts.</li>
<li>Arrodonint a segons, el temps que tarda més sovint és 17 minuts.</li>
<li>En un 95% de les ocasions tarda aproximadament entre 14 i 20 minuts</li>
<li>Tarda més de 20 minuts amb la mateixa freqüència amb la qual tarda menys de 14 minuts</li>
<li>Tarda més de 20 minuts amb la mateixa freqüència amb la qual tarda menys de 20 minuts</li>
<li>En un 95% de les ocasions tarda 23 minuts o menys</li>
</ol>
<p><strong>(19)</strong> Quina de les tres afirmacions és vertadera per a les tres distribucions normals de la figura inferior? (<span class="math inline">\(\sigma_1\)</span>, <span class="math inline">\(\sigma_2\)</span> i <span class="math inline">\(\sigma_3\)</span> indiquen les desviacions típiques de les corbes 1, 2 i 3, respectivament).</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\sigma_1&gt; \sigma_2&gt; \sigma_3\)</span></li>
<li><span class="math inline">\(\sigma_1&lt; \sigma_2&lt; \sigma_3\)</span></li>
<li><span class="math inline">\(\sigma_1= \sigma_2= \sigma_3\)</span></li>
<li>Del gràfic no es pot deduir la relació entre les tres desviacions típiques</li>
<li>Cap de les altres afirmacions és veritable.</li>
</ol>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-146-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p><strong>(20)</strong> El pes mitjà d’una bossa de patates d’una determinada marca és de 150 grams amb una desviació típica de 5.6 grams. Quin és el z-score d’una bossa que pesa 147 grams (arrodonit a 2 xifres decimals)?</p>
<ol style="list-style-type: decimal">
<li>-0.54</li>
<li>0.30</li>
<li>0.54</li>
<li>0.70</li>
<li>Cap de les respostes anteriors és correcta</li>
</ol>
<p><strong>(21)</strong> Si una variable aleatòria normal té mitjana 18.1 i desviació típica 1.2, què val el seu 3er quartil (arrodonit a una xifra decimal)? (Has d’emprar R o una apli per calcular-lo)</p>
<ol style="list-style-type: decimal">
<li>18.1</li>
<li>18.9</li>
<li>19.3</li>
<li>20.5</li>
<li>Cap de les respostes anteriors és correcta</li>
</ol>
<p><strong>(23)</strong> L’interval de referència (del 95%) de la concentració de creatinina en sèrum és 0.66-1.09 mg/dl. Què en podem deduir? (Marca només una resposta.)</p>
<ol style="list-style-type: decimal">
<li><p>Que la probabilitat que la concentració mitjana de creatinina en sèrum estigui entre 0.66 i 1.09 mg/dl és del 95%.</p></li>
<li><p>Que si prenem una mostra aleatòria d’individus i calculam la mitjana de les seves concentracions de creatinina, en un 95% de les ocasions aquesta mitjana estarà entre 0.66 i 1.09 mg/dl.</p></li>
<li><p>Que un 5% dels individus tenen una concentració de creatinina en sèrum superior a 1.09 mg/dl.</p></li>
<li><p>Que un 95% dels individus tenen una concentració de creatinina en sèrum entre 0.66 i 1.09 mg/dl.<br />
</p></li>
<li><p>Que si prenem una mostra aleatòria d’individus, en un 95% de les ocasions tots els valors estaran entre 0.66 i 1.09 mg/dl.</p></li>
<li><p>Cap de les altres respostes és correcta.</p></li>
</ol>
<p><strong>(24)</strong> Quin és l’efecte sobre la mitjana, la desviació típica i la mediana d’una variable aleatòria si sumam 1 al seu valor sobre tots els individus de la població?</p>
<ol style="list-style-type: decimal">
<li>Cap d’aquests paràmetres varia.</li>
<li>La mitjana i la mediana canvien, la desviació típica no.<br />
</li>
<li>La mitjana varia, la resta no.</li>
<li>La mitjana no varia, la resta sí.</li>
<li>Tots tres paràmetres varien.</li>
<li>Cap de les altres respostes és correcta.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-conceptes.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="estimació-puntual.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
