<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tema 2 Contrastos de bondat d’ajust | Matemàtiques II v.2021</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Tema 2 Contrastos de bondat d’ajust | Matemàtiques II v.2021" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 2 Contrastos de bondat d’ajust | Matemàtiques II v.2021" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2021-03-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"/>
<link rel="next" href="contrastos-dindependència-i-homogeneïtat.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="chapter" data-level="1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><i class="fa fa-check"></i><b>1</b> Contrastos d’hipòtesis d’un i dos paràmetres</a>
<ul>
<li class="chapter" data-level="1.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-de-mitjanes"><i class="fa fa-check"></i><b>1.1</b> Contrastos de mitjanes</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-una-mitjana"><i class="fa fa-check"></i><b>1.1.1</b> Test t per a una mitjana</a></li>
<li class="chapter" data-level="1.1.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-dues-mitjanes"><i class="fa fa-check"></i><b>1.1.2</b> Test t per a dues mitjanes</a></li>
<li class="chapter" data-level="1.1.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-t-amb-r"><i class="fa fa-check"></i><b>1.1.3</b> Tests t amb R</a></li>
<li class="chapter" data-level="1.1.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exemples"><i class="fa fa-check"></i><b>1.1.4</b> Exemples</a></li>
<li class="chapter" data-level="1.1.5" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics"><i class="fa fa-check"></i><b>1.1.5</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#sec:contrvar"><i class="fa fa-check"></i><b>1.2</b> Contrastos de variàncies</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-chi2-duna-variància"><i class="fa fa-check"></i><b>1.2.1</b> Test <span class="math inline">\(\chi^2\)</span> d’una variància</a></li>
<li class="chapter" data-level="1.2.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-f-per-a-dues-variàncies"><i class="fa fa-check"></i><b>1.2.2</b> Test F per a dues variàncies</a></li>
<li class="chapter" data-level="1.2.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics-1"><i class="fa fa-check"></i><b>1.2.3</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-proporcions"><i class="fa fa-check"></i><b>1.3</b> Contrastos per a proporcions</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-una-proporció"><i class="fa fa-check"></i><b>1.3.1</b> Contrastos per a una proporció</a></li>
<li class="chapter" data-level="1.3.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-independents"><i class="fa fa-check"></i><b>1.3.2</b> Contrastos per a 2 proporcions emprant mostres independents</a></li>
<li class="chapter" data-level="1.3.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-aparellades"><i class="fa fa-check"></i><b>1.3.3</b> Contrastos per a 2 proporcions emprant mostres aparellades</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-de-la-lliçó-6"><i class="fa fa-check"></i><b>1.4</b> Test de la lliçó 6</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-bondat.html"><a href="chap-bondat.html"><i class="fa fa-check"></i><b>2</b> Contrastos de bondat d’ajust</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap-bondat.html"><a href="chap-bondat.html#bondat-dajust"><i class="fa fa-check"></i><b>2.1</b> Bondat d’ajust</a></li>
<li class="chapter" data-level="2.2" data-path="chap-bondat.html"><a href="chap-bondat.html#test-chi2-de-pearson"><i class="fa fa-check"></i><b>2.2</b> Test <span class="math inline">\(\chi^2\)</span> de Pearson</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chap-bondat.html"><a href="chap-bondat.html#el-test-bàsic"><i class="fa fa-check"></i><b>2.2.1</b> El test bàsic</a></li>
<li class="chapter" data-level="2.2.2" data-path="chap-bondat.html"><a href="chap-bondat.html#mètode-de-montecarlo"><i class="fa fa-check"></i><b>2.2.2</b> Mètode de Montecarlo</a></li>
<li class="chapter" data-level="2.2.3" data-path="chap-bondat.html"><a href="chap-bondat.html#test-chi2-amb-paràmetres-poblacionals-desconeguts"><i class="fa fa-check"></i><b>2.2.3</b> Test <span class="math inline">\(\chi^2\)</span> amb paràmetres poblacionals desconeguts</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chap-bondat.html"><a href="chap-bondat.html#test-de-kolmogorov-smirnov"><i class="fa fa-check"></i><b>2.3</b> Test de Kolmogorov-Smirnov</a></li>
<li class="chapter" data-level="2.4" data-path="chap-bondat.html"><a href="chap-bondat.html#test-de-kolmogorov-smirnov-lilliefors"><i class="fa fa-check"></i><b>2.4</b> Test de Kolmogorov-Smirnov-Lilliefors</a></li>
<li class="chapter" data-level="2.5" data-path="chap-bondat.html"><a href="chap-bondat.html#test-de-la-lliçó-7"><i class="fa fa-check"></i><b>2.5</b> Test de la lliçó 7</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html"><i class="fa fa-check"></i><b>3</b> Contrastos d’independència i homogeneïtat</a>
<ul>
<li class="chapter" data-level="3.1" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dindependència"><i class="fa fa-check"></i><b>3.1</b> Test <span class="math inline">\(\chi^2\)</span> d’independència</a></li>
<li class="chapter" data-level="3.2" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dhomogeneïtat"><i class="fa fa-check"></i><b>3.2</b> Test <span class="math inline">\(\chi^2\)</span> d’homogeneïtat</a></li>
<li class="chapter" data-level="3.3" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-de-tendència-opcional"><i class="fa fa-check"></i><b>3.3</b> Test <span class="math inline">\(\chi^2\)</span> de tendència (Opcional)</a></li>
<li class="chapter" data-level="3.4" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-de-la-lliçó-8"><i class="fa fa-check"></i><b>3.4</b> Test de la lliçó 8</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II v.2021</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:bondat" class="section level1" number="2">
<h1><span class="header-section-number">Tema 2</span> Contrastos de bondat d’ajust</h1>
<p>Els contrastos d’un paràmetre del tema anterior els empràvem bàsicament per cercar evidència que a un paràmetre poblacional (una mitjana, una proporció) “li passava qualque cosa”:</p>
<ul>
<li><p>Tenim evidència que la mitjana poblacional és diferent de 2?</p></li>
<li><p>Tenim evidència que la proporció poblacional d’èxits és més gran que el 10%?</p></li>
</ul>
<p>Però també podem entendre que hi cercàvem si podem acceptar que el paràmetre poblacional de la variable que havia produït la mostra era igual a qualque cosa:</p>
<ul>
<li><p>Podem acceptar que la mitjana poblacional és igual a 2?</p></li>
<li><p>Podem acceptar que la proporció poblacional d’èxits és del 10%?</p></li>
</ul>
<p>Als contrastos de bondat d’ajust anam una passa més enllà, i ens demanam si podem acceptar que la variable poblacional té una distribució concreta, o si per contra seria molt estrany que la nostra mostra hagués estat produïda per una variable amb aquella distribució. Per exemple:</p>
<ul>
<li><p>Llençam un dau en l’aire moltes vegades, apuntam els resultats, i ens demanam si podem acceptar que el dau està equilibrat (és a dir, que totes les cares tenen la mateixa probabilitat de sortir) o si per contra hi ha evidència que està trucat.</p></li>
<li><p>Anotam els ingressos diaris per una determinada malaltia en un hospital i ens demanam si podem acceptar que segueixen una distribució de Poisson o si per contra hi ha evidència que no és el cas, la qual cosa seria senyal que hi ha un brot estrany de la malaltia.</p></li>
<li><p>Volem emprar una mostra petita en un t-test. Podem acceptar que prové d’una distribució normal?</p></li>
</ul>
<p>De fet, ja hem estudiat un tipus de contrast de bondat d’ajust: els contrastos bilaterals d’una proporció, on ens demanàvem si podem acceptar que la mostra prové de tal variable Bernoulli o si per contra hi ha evidència que no.</p>

<div class="rmdcaution">
En els temes anteriors, les variables aleatòries eren sempre <strong>quantitatives</strong>: aplicacions que a cada subjecte d’una població li assignen una dada quantitativa, és a dir, un nombre real. En aquest tema i el següent relaxarem aquesta definició, i també considerarem variables aleatòries que assignen a cada subjecte d’una població una dada de qualsevol tipus: no necessàriament quantitativa, també podrà ser qualitativa o ordinal. En aquest context, parlarem de variables aleatòries <strong>qualitatives</strong>, <strong>ordinals</strong> o <strong>quantitatives</strong>, segons el tipus de dada que mesurin.
</div>
<div id="bondat-dajust" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Bondat d’ajust</h2>
<p>Considerau l’exemple següent:</p>

<div class="example">
<p><span id="exm:grossa" class="example"><strong>Exemple 2.1  </strong></span>Les freqüències de les darreres xifres dels primers premis de la Grossa de la loteria de Nadal als 212 sortejos de la seva història (fins el de 2020, inclòs) han estat les següents:</p>
</div>
<p><span class="math display">\[
\begin{array}{r|cccccccccc}
\hline
\text{xifra}        &amp; 0 &amp; 1 &amp; 2 &amp; 3 &amp; 4 &amp; 5 &amp; 6 &amp; 7 &amp; 8 &amp; 9 \\ \hline
\text{freqüència} &amp;  22 &amp; 8 &amp; 13 &amp; 21 &amp; 27 &amp; 31 &amp; 27 &amp; 23 &amp; 23 &amp; 17\\
\hline
\end{array}
\]</span></p>
<p>Hi ha evidència que no totes les xifres tenen la mateixa probabilitat de sortir com a darrera xifra de la Grossa?</p>
<p>Aquesta és la típica pregunta d’un contrast de bondat d’ajust.</p>
<ul>
<li><p>En principi, estam disposats a acceptar que la nostra mostra prové d’una variable amb una certa distribució:</p>
<p>Que totes les darreres xifres de la Grossa tenen la mateixa probabilitat d’aparèixer.</p></li>
<li><p>Rebutjarem aquesta hipòtesi si seria molt estrany haver obtingut la nostra mostra en el cas que la variable seguís aquesta distribució:</p>
<p>Si les darreres xifres tenguessin totes la mateixa probabilitat d’aparèixer, esperaríem una certa uniformitat en les seves freqüències a la nostra mostra. Si les freqüències reals se separen molt d’aquesta uniformitat, tendrem motius per dubtar que tots els dígits tenien la mateixa probabilitat d’aparèixer.</p></li>
</ul>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="chap-bondat.html#cb113-1" aria-hidden="true" tabindex="-1"></a>Grossa<span class="ot">=</span><span class="fu">c</span>(<span class="dv">22</span>,<span class="dv">8</span>,<span class="dv">13</span>,<span class="dv">21</span>,<span class="dv">27</span>,<span class="dv">31</span>,<span class="dv">27</span>,<span class="dv">23</span>,<span class="dv">23</span>,<span class="dv">17</span>)</span>
<span id="cb113-2"><a href="chap-bondat.html#cb113-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(Grossa,<span class="at">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="at">names=</span><span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>, </span>
<span id="cb113-3"><a href="chap-bondat.html#cb113-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Darreres xifres  de la Grossa de Nadal&quot;</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-114-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Més en general, un <strong>contrast de bondat d’ajust</strong> té la forma següent:
<span class="math display">\[
\left\{
\begin{array}{l}
H_0: \text{la mostra prové de la distribució esperada}\\
H_1: \text{la mostra NO prové de la distribució esperada}
\end{array}
\right.
\]</span>
I, com sempre,</p>
<ul>
<li><p>Si obtenim evidència que ens permeti rebutjar la hipòtesi nul·la, conclourem que la mostra no prové de la distribució esperada</p></li>
<li><p>Si no obtenim evidència que ens permeti rebutjar la hipòtesi nul·la, donarem per bo que la mostra prové de la distribució esperada</p></li>
</ul>
<p>Els tests de bondat d’ajust es basen bàsicament en:</p>
<ol style="list-style-type: decimal">
<li><p>Comparar les <strong>freqüències observades</strong> amb les <strong>freqüències esperades</strong> si la distribució fos la que contrastam</p></li>
<li><p>Determinar si les freqüències observades són prou diferents de les esperades com per fer inversemblant la hipòtesi nul·la</p></li>
</ol>
<p>Per exemple, continuant amb el nostre exemple de la Grossa, si totes les darreres xifres tinguessin la mateixa probabilitat d’aparèixer, la seva probabilitat seria 1/10, i per tant el nombre esperat d’aparicions de cadascuna d’elles seria 212/10=21.2.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="chap-bondat.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(Grossa, <span class="at">col=</span><span class="st">&quot;light blue&quot;</span>, <span class="at">names=</span><span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>, </span>
<span id="cb114-2"><a href="chap-bondat.html#cb114-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Darreres xifres de  la Grossa de Nadal&quot;</span>)</span>
<span id="cb114-3"><a href="chap-bondat.html#cb114-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fl">21.2</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="st">&quot;dashed&quot;</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-115-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Les desviacions observades respecte d’aquest valor esperat, representat per la línia vermella al gràfic anterior, són prou grans com per fer-nos dubtar que les darreres xifres de les Grosses de Nadal tenguin totes la mateixa probabilitat d’aparèixer? O, pel contrari, entren dins el que és raonable esperar per mor de l’atzar?</p>
</div>
<div id="test-chi2-de-pearson" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Test <span class="math inline">\(\chi^2\)</span> de Pearson</h2>
<div id="el-test-bàsic" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> El test bàsic</h3>
<p>El test més popular per a variables aleatòries qualitatives, ordinals i quantitatives discretes (o contínues agrupades) és el <strong>test <span class="math inline">\(\chi^2\)</span> de Pearson</strong>.</p>
<p>Suposem que tenim una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> de la variable poblacional <span class="math inline">\(X\)</span>. Agrupam tots els resultats possibles en <span class="math inline">\(k\geqslant 2\)</span> <strong>classes</strong>, <span class="math inline">\(C_1,\ldots,C_k\)</span> (poden ser tots els resultats individuals possibles, si només n’hi ha un conjunt finit). Així, al nostre exemple de les terminacions de la loteria, hi emprarem 10 classes, definides pels 10 valors possibles de la darrera xifra: <span class="math inline">\(C_1=\{0\}\)</span>, <span class="math inline">\(C_2=\{1\}\)</span>,…, <span class="math inline">\(C_{10}=\{9\}\)</span>.</p>
<p>Volem contrastar si les observacions segueixen una <em>distribució totalment coneguda</em>, per a la qual poguem calcular la probabilitat que una observació caigui dins cada una de les classes.</p>
<p>El contrast és, recordem,
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}: \text{La v.a. poblacional té aquesta distribució }\\
H_{1}: \text{La v.a. poblacional no té aquesta distribució}
\end{array}
\right.
\]</span></p>
<p>Per a cada classe <span class="math inline">\(C_i\)</span>, diguem</p>
<ul>
<li><p><span class="math inline">\(obs_i\)</span>: la freqüència absoluta <strong>observada</strong> d’aquesta classe. Per exemple, en el nostre exemple de la loteria, <span class="math inline">\(obs_1\)</span> és el nombre de vegades que la Grossa ha acabat en 0: 21; <span class="math inline">\(obs_2\)</span> és el nombre de vegades que la Grossa ha acabat en 1: 8; etc.</p></li>
<li><p><span class="math inline">\(p_i\)</span>: la probabilitat <strong>teòrica</strong> que una observació pertanyi a aquesta classe si <span class="math inline">\(H_0\)</span> és vertadera. En el nostre exemple de la loteria, totes les probabilitats <span class="math inline">\(p_i\)</span> valen el mateix, 1/10.</p></li>
<li><p><span class="math inline">\(esp_i\)</span>: la freqüència absoluta <strong>esperada</strong> d’aquesta classe si <span class="math inline">\(H_0\)</span> és vertadera: <span class="math inline">\(esp_i=p_i\cdot n\)</span>. En el nostre exemple de la loteria, totes aquestes freqüències esperades <span class="math inline">\(esp_i\)</span> valen el mateix, 212/10=21.2.</p></li>
</ul>
<p>Rebutjarem <span class="math inline">\(H_0\)</span> si les <span class="math inline">\(obs_i\)</span> són prou diferents de les <span class="math inline">\(esp_i\)</span>. Per mesurar-ho, empram el teorema següent:</p>

<div class="theorem">
<p><span id="thm:khi2BA" class="theorem"><strong>Teorema 2.1  </strong></span>Suposem que la distribució contrastada està completament determinada i que se satisfan les condicions següents:</p>
<ul>
<li><p>La mida <span class="math inline">\(n\)</span> de la mostra és gran (ho fixarem en <span class="math inline">\(n\geqslant 30\)</span>)</p></li>
<li><p>Les classes cobreixen tots els resultats possibles: <span class="math inline">\(\sum\limits_{i=1}^kesp_i= n\)</span></p></li>
<li><p>Totes les classes tenen prou probabilitat teòrica com per tenir-les en compte (nosaltres emprarem la <strong>Regla de Cochran</strong>: totes les <span class="math inline">\(esp_i\geqslant 5\)</span>)</p></li>
</ul>
<p>Aleshores, si <span class="math inline">\(H_0\)</span> és vertadera, l’estadístic de contrast
<span class="math display">\[
\chi^2=\sum_{i=1}^k \frac{(obs_{i}-esp_{i})^2}{esp_{i}}
\]</span>
té (aproximadament) una distribució <span class="math inline">\(\chi_{k-1}^2\)</span>.</p>
<p>Si la distribució contrastada no estava completament determinada i se n’han estimat <span class="math inline">\(m\)</span> paràmetres a partir de la mostra, s’ha de prendre com a distribució de l’estadístic de contrast una <span class="math inline">\(\chi_{k-1-m}^2\)</span>.</p>
</div>

<div class="rmdnote">
<p>Fixau-vos que l’estadístic de contrast <span class="math inline">\(\chi^2\)</span> s’obté de la manera següent:</p>
<ol style="list-style-type: decimal">
<li><p>Per cada classe <span class="math inline">\(C_i\)</span>:</p>
<ol style="list-style-type: lower-alpha">
<li>Se resta <span class="math inline">\(obs_{i}-esp_{i}\)</span></li>
<li>S’eleva el resultat al quadrat: <span class="math inline">\((obs_{i}-esp_{i})^2\)</span></li>
<li>Es divideix el resultat per <span class="math inline">\(esp_i\)</span>: <span class="math inline">\((obs_{i}-esp_{i})^2/esp_{i}\)</span></li>
</ol></li>
<li><p>Se sumen aquests valors per a totes les classes <span class="math inline">\(C_i\)</span>.</p></li>
</ol>
</div>
<p>Aleshores, el contrast se fa de la manera següent:</p>
<ol style="list-style-type: decimal">
<li><p>Se calcula el valor que pren l’estadístic de contrast sobre la nostra mostra, diguem-li <span class="math inline">\(\chi_0^2\)</span></p></li>
<li><p>El p-valor del contrast és <span class="math inline">\(P(\chi^2\geqslant \chi_0^2)\)</span>, calculada tenint en compte que <span class="math inline">\(\chi^2\)</span> té distribució <span class="math inline">\(\chi^2\)</span> amb nombre de graus de llibertat:</p>
<ul>
<li><p>Si no s’ha hagut d’estimar cap paràmetre de la distribució amb la mostra, el nombre de classes menys 1: <span class="math inline">\(\chi^2_{k-1}\)</span></p></li>
<li><p>Si s’ha estimat qualque paràmetre de la distribució amb la mostra, el nombre de classes menys 1 i menys el nombre de paràmetres estimats: <span class="math inline">\(\chi^2_{k-1-m}\)</span> amb <span class="math inline">\(m\)</span> el nombre de paràmetres estimats</p></li>
</ul></li>
</ol>

<div class="rmdimportant">
Com més gran sigui el nombre de classes emprades, més potència té el contrast, per tant procurau emprar-ne el màxim nombre possible tot respectant la regla de Cochran.
</div>

<div class="example">
<p><span id="exm:grossa2" class="example"><strong>Exemple 2.2  </strong></span>Tornem a l’Exemple <a href="chap-bondat.html#exm:grossa">2.1</a>. Recordem que la nostra mostra era</p>
</div>
<p><span class="math display">\[
\begin{array}{r|cccccccccc}
\hline
\text{xifra}        &amp; 0 &amp; 1 &amp; 2 &amp; 3 &amp; 4 &amp; 5 &amp; 6 &amp; 7 &amp; 8 &amp; 9 \\ \hline
\text{freqüència} &amp;  22 &amp; 8 &amp; 13 &amp; 21 &amp; 27 &amp; 31 &amp; 27 &amp; 23 &amp; 23 &amp; 17\\
\hline
\end{array}
\]</span>
Com que totes les freqüències esperades valen 21.2, el valor de l’estadístic de contrast sobre aquesta mostra és
<span class="math display">\[
\begin{array}{rl}
 \chi_0^2&amp; \displaystyle=\frac{(22-21.2)^2}{21.2}+\frac{(8-21.2)^2}{21.2}+\cdots\\[2ex]
 &amp; \qquad\quad\displaystyle +\frac{(23-21.2)^2}{21.2} +\frac{(17-21.2)^2}{21.2}=20.264
\end{array}
\]</span></p>
<p>Calculat amb R:</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="chap-bondat.html#cb115-1" aria-hidden="true" tabindex="-1"></a>X2<span class="ot">=</span><span class="fu">sum</span>((Grossa<span class="fl">-21.2</span>)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="fl">21.2</span>)</span>
<span id="cb115-2"><a href="chap-bondat.html#cb115-2" aria-hidden="true" tabindex="-1"></a>X2</span></code></pre></div>
<pre><code>## [1] 20.26415</code></pre>
<p>En resum, per resoldre la qüestió plantejada en l’Exemple <a href="chap-bondat.html#exm:grossa">2.1</a> procedim de la manera següent:</p>
<p><em>Variable aleatòria d’interès</em>, <span class="math inline">\(X\)</span>: Faig un sorteig de la Grossa de Nadal i anot la darrera xifra del nombre guanyador.</p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}: \text{$X$ és uniforme}\\
H_{1}: \text{$X$ no és uniforme}
\end{array}
\right.
\]</span>
(Recordau que una variable aleatòria discreta és <strong>uniforme</strong> quan tots els elements del seu domini tenen la mateixa probabilitat.)</p>
<p><em>Estadístic de contrast</em>:
<span class="math display">\[
\chi^2=\sum_{i=1}^k \frac{(obs_{i}-esp_{i})^2}{esp_{i}}
\]</span></p>
<p>Estam en les condicions del Teorema <a href="chap-bondat.html#thm:khi2BA">2.1</a>:</p>
<ul>
<li><p><span class="math inline">\(n=212\)</span>, gran</p></li>
<li><p>Les classes, que corresponen als dígits 0,…,9, cobreixen tots els resultats possibles; <span class="math inline">\(k=10\)</span></p></li>
<li><p>Cada <span class="math inline">\(esp_i=21.2\geqslant 5\)</span></p></li>
</ul>
<p>Per tant, com que no estimam cap paràmetre de la distribució, aquest estadístic de contrast segueix una llei <span class="math inline">\(\chi^2_9\)</span>.</p>
<p><em>Valor de l’estadístic de contrast</em>: Ja l’hem calculat, 20.264.</p>
<p><em>p-valor</em>: <span class="math inline">\(P(\chi_9^2\geqslant 20.264)=\texttt{1-pchisq(20.264,9)}= 0.0164\)</span></p>
<p><em>Conclusió</em>: Hem obtingut evidència estadísticament significativa que les darreres xifres de la Grossa no apareixen de manera equiprobable (test <span class="math inline">\(\chi^2\)</span> de Pearson, p-valor 0.0164).</p>
<p><img src="Bioestadistica-II_files/figure-html/oops.png" width="50%" style="display: block; margin: auto;" /></p>

<div class="example">
<p><span id="exm:grossasim" class="example"><strong>Exemple 2.3  </strong></span>Anem a confirmar amb una simulació aquest p-valor. El que farem serà el següent: Repetirem 10000 vegades, amb un <code>replicate</code>, el procés de generar a l’atzar i de manera equiprobable 212 dígits, calcular la taula de freqüències de cada una d’aquestes mostres i calcular l’estadístic de contrast <span class="math inline">\(\chi^2\)</span> sobre cada una d’aquestes taules. Finalment, calcularem la fracció de vegades que <span class="math inline">\(\chi^2\)</span> ha valgut més que a la nostra mostra.</p>
</div>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="chap-bondat.html#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb117-2"><a href="chap-bondat.html#cb117-2" aria-hidden="true" tabindex="-1"></a>X2sim<span class="ot">=</span><span class="fu">replicate</span>(<span class="dv">10000</span>,<span class="fu">sum</span>((<span class="fu">table</span>(<span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>,<span class="dv">212</span>,<span class="at">rep=</span><span class="cn">TRUE</span>))<span class="sc">-</span><span class="fl">21.2</span>)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="fl">21.2</span>))</span>
<span id="cb117-3"><a href="chap-bondat.html#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(X2sim<span class="sc">&gt;=</span>X2))<span class="sc">/</span><span class="dv">10000</span></span></code></pre></div>
<pre><code>## [1] 0.0145</code></pre>
<p>Només un 1.45% de les 10000 simulacions han donat un valor de <span class="math inline">\(\chi^2\)</span> més gran o igual que el de la mostra de Grosses de Nadal. Per tant, el valor de la <span class="math inline">\(\chi^2\)</span> de la mostra de Grosses de Nadal és anormalment gran si les darreres xifres tenen totes la mateixa probabilitat d’aparèixer. Naturalment, anormal no vol dir impossible. Sense anar més enfora, algunes de les mostres de la nostra simulació han donat un valor més gran, i alguna fins i tot ha arribat a:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="chap-bondat.html#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(X2sim)</span></code></pre></div>
<pre><code>## [1] 34.98113</code></pre>
<p>Però tenim evidència estadística per dubtar que les darreres xifres de la Grossa surtin equiprobablement. Naturalment, podria ser un error de tipus I.</p>
<p>La nota següent us pot ser útil si qualque dia heu de decidir a ull si el valor de l’estadístic d’un test <span class="math inline">\(\chi^2\)</span> és molt gran.</p>

<div class="rmdimportant">
Recordau que la distribució d’una <span class="math inline">\(\chi^2_n\)</span> és la de la suma de <span class="math inline">\(n\)</span> normals estàndard al quadrat independents, i que l’interval de referència d’una normal estàndard és <span class="math inline">\([-1.69,1.69]\)</span>. Això implica que en un 95% de les ocasions una normal estàndard val entre -1.69 i 1.69, i per tant el seu quadrat és més petit que <span class="math inline">\(1.69^2=2.856\leqslant 3\)</span>. Ara fixau-vos que si sumam <span class="math inline">\(n\)</span> numeros més petits que 3, la suma dóna més petita que <span class="math inline">\(3n\)</span>. Per tant, si una variable <span class="math inline">\(\chi_n^2\)</span> pren un valor més gran que <span class="math inline">\(3n\)</span>, algun dels quadrats de normal estàndard que hi sumam ha de donar més gran que 3. Això implica que la probabilitat que una <span class="math inline">\(\chi_n^2\)</span> doni un valor més gran que <span class="math inline">\(3n\)</span> ha de ser molt petita, com podeu observar a la Figura <a href="chap-bondat.html#fig:chisq3n">2.1</a>.
</div>
<div class="figure" style="text-align: center"><span id="fig:chisq3n"></span>
<img src="Bioestadistica-II_files/figure-html/chisq3n-1.png" alt="Algunes probabilitats per a una distribució khi quadrat" width="50%" />
<p class="caption">
Figura 2.1: Algunes probabilitats per a una distribució khi quadrat
</p>
</div>
<p>La funció per realitzar un test <span class="math inline">\(\chi^2\)</span> amb R és</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="chap-bondat.html#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(obs, <span class="at">p=</span>...)</span></code></pre></div>
<p>on <code>obs</code> és el vector de les freqüències observades de les classes, <span class="math inline">\((obs_i)_i\)</span> i <code>p</code> s’ha d’igualar al vector de les probabilitats teòriques de les classes, <span class="math inline">\((p_i)_i\)</span>.</p>

<div class="rmdcaution">
Si no s’especifica aquest paràmetre <code>p</code>, R entén que totes les probabilitats són iguals.
</div>

<div class="rmdcaution">
La suma de les probabilitats entrades a <code>p</code> ha de ser igual a 1. Recordau que les classes han de cobrir tots els casos possibles.
</div>
<p>Al nostre exemple de la Grossa de Nadal, entraríem simplement</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="chap-bondat.html#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(Grossa)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  Grossa
## X-squared = 20.264, df = 9, p-value = 0.01635</code></pre>
<p>Obtenim el valor de <span class="math inline">\(\chi^2\)</span>, <code>X-squared</code>, els graus de llibertat, <code>df</code>, i el p-valor, <code>p-value</code>.</p>

<div class="example">
<p><span id="exm:industrial" class="example"><strong>Exemple 2.4  </strong></span>Un tècnic de medi ambient vol estudiar l’augment de temperatura de l’aigua a dos quilòmetres dels abocaments d’aigua autoritzats d’una
planta industrial.</p>
</div>
<p>El responsable de l’empresa afirma que</p>
<blockquote>
<p>aquests augments de temperatura segueixen una llei normal amb <span class="math inline">\(\mu=3.5\)</span> dècimes de grau C i <span class="math inline">\(\sigma=0.7\)</span> dècimes de grau C.</p>
</blockquote>
<p>El tècnic ho posa en dubte. Per decidir-ho, pren una mostra aleatòria d’observacions de l’augment de les temperatures (en dècimes de grau). Les dades són les de la taula següent, ja agrupades en classes:</p>
<p><span class="math display">\[
\begin{array}{c|c}
\text{Rang d&#39;augments} &amp; \text{Freqüències}\\
\hline
1.45\text{ a }1.95 &amp; 2 \\
1.95\text{ a }2.45 &amp; 1 \\
2.45\text{ a }2.95 &amp; 4 \\
2.95\text{ a }3.45 &amp; 15 \\
3.45\text{ a }3.95 &amp; 10 \\
3.95\text{ a }4.45 &amp; 5 \\
4.45\text{ a }4.95 &amp; 3 \\
\hline
\text{Total} &amp; 40\\ 
\end{array}
\]</span></p>
<p>Hi ha evidència que la sospita del tècnic sigui vertadera, amb un nivell de significació del 5%?</p>
<p><em>Variable aleatòria d’interès</em>, <span class="math inline">\(X\)</span>: Prenc un lloc a 2 km dels abocaments d’aigua autoritzats d’una planta industrial i hi mesur l’augment de temperatura (en dècimes de grau).</p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{
\begin{array}{l}
H_{0}:\text{$X$ és $N(3.5,0.7)$}\\ 
H_{1}: \text{$X$ no és $N(3.5,0.7)$}
\end{array}
\right.
\]</span></p>
<p><em>Estadístic de contrast</em>: Volem emprar el test <span class="math inline">\(\chi^2\)</span>, així que l’estadístic de contrast serà
<span class="math display">\[
\chi^2=\sum_{i=1}^k \frac{(obs_{i}-esp_{i})^2}{esp_{i}}
\]</span></p>
<p>Cal comprovar que se satisfan les condicions del Teorema <a href="chap-bondat.html#thm:khi2BA">2.1</a>.</p>
<ul>
<li><p>La mida de la mostra és <span class="math inline">\(n=40\)</span>, suficient.</p></li>
<li><p>Les classes, cobreixen tots els resultats possibles?</p></li>
</ul>
<p>No, perquè els possible valors d’una variable normal són tots els nombres reals, i les nostres classes només cobreixen l’interval [1.45,4.95]. El que farem serà afegir les cues a les dues classes dels extrems, i considerar les classes
<span class="math display">\[
\begin{array}{l|c}
\text{Rang d&#39;augments} &amp; \text{Freqüències}\\
\hline
\text{menys de 1.95} &amp; 2 \\
1.95 \text{ a } 2.45 &amp; 1 \\
2.45\text{ a }2.95 &amp; 4 \\
2.95\text{ a }3.45 &amp; 15 \\
3.45\text{ a }3.95 &amp; 10 \\
3.95\text{ a }4.45 &amp; 5 \\
\text{més de 4.45} &amp; 3 \\
\hline
\text{Total} &amp; 40\\  
\end{array}
\]</span>
Ara ja cobreixen tots els resultats possibles.</p>
<ul>
<li>Totes les freqüències esperades són com a mínim 5?</li>
</ul>
<p>Doncs no ho sabem, les haurem de calcular. Recordem que són les freqüències esperades de cada classe suposant que la variable poblacional és <span class="math inline">\(N(3.5,0.7)\)</span>, i s’obtenen multiplicant la probabilitat de cada interval (amb aquesta distribució) per la mida de la mostra, 40.</p>
<p>La probabilitat de la 1<sup>a</sup> classe és
<span class="math display">\[
            p_1 =P(X\leqslant 1.95)=\texttt{pnorm(1.95,3.5,0.7)}=0.0134
\]</span>
i la seva freqüència esperada és
<span class="math display">\[
esp_1=p_1\cdot n= 0.0134\cdot 40=0.536
\]</span></p>
<p>La probabilitat de la 2<sup>a</sup> classe és
<span class="math display">\[
    \begin{array}{rl}
    p_2 &amp; =P(1.95\leqslant X\leqslant 2.45)\\
    &amp; =\texttt{pnorm(2.45,3.5,0.7)-pnorm(1.95,3.5,0.7)}=0.0534
    \end{array}
\]</span>
i per tant la seva freqüència esperada és
<span class="math display">\[
    esp_2=p_2\cdot n= 0.0534\cdot 40= 2.136
\]</span></p>
<p>Calcularem amb R totes les freqüències esperades d’aquesta manera i d’un sol cop:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="chap-bondat.html#cb124-1" aria-hidden="true" tabindex="-1"></a>freq.obs<span class="ot">=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">15</span>,<span class="dv">10</span>,<span class="dv">5</span>,<span class="dv">3</span>)</span>
<span id="cb124-2"><a href="chap-bondat.html#cb124-2" aria-hidden="true" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">sum</span>(freq.obs)</span>
<span id="cb124-3"><a href="chap-bondat.html#cb124-3" aria-hidden="true" tabindex="-1"></a>lims<span class="ot">=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>,<span class="fl">1.95</span>,<span class="fl">2.45</span>,<span class="fl">2.95</span>,<span class="fl">3.45</span>,<span class="fl">3.95</span>,<span class="fl">4.45</span>,<span class="cn">Inf</span>)</span>
<span id="cb124-4"><a href="chap-bondat.html#cb124-4" aria-hidden="true" tabindex="-1"></a>lim.esq<span class="ot">=</span>lims[<span class="sc">-</span><span class="fu">length</span>(lims)]  <span class="co">#Els límits inferiors de les classes</span></span>
<span id="cb124-5"><a href="chap-bondat.html#cb124-5" aria-hidden="true" tabindex="-1"></a>lim.dret<span class="ot">=</span>lims[<span class="sc">-</span><span class="dv">1</span>]  <span class="co">#Els límits superiors de les classes</span></span>
<span id="cb124-6"><a href="chap-bondat.html#cb124-6" aria-hidden="true" tabindex="-1"></a>mu<span class="ot">=</span><span class="fl">3.5</span></span>
<span id="cb124-7"><a href="chap-bondat.html#cb124-7" aria-hidden="true" tabindex="-1"></a>sigma<span class="ot">=</span><span class="fl">0.7</span></span>
<span id="cb124-8"><a href="chap-bondat.html#cb124-8" aria-hidden="true" tabindex="-1"></a>prob.esp<span class="ot">=</span><span class="fu">pnorm</span>(lim.dret,mu,sigma)<span class="sc">-</span><span class="fu">pnorm</span>(lim.esq,mu,sigma)</span>
<span id="cb124-9"><a href="chap-bondat.html#cb124-9" aria-hidden="true" tabindex="-1"></a>freq.esp<span class="ot">=</span>n<span class="sc">*</span>prob.esp</span>
<span id="cb124-10"><a href="chap-bondat.html#cb124-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(freq.esp,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1]  0.536  2.136  5.968 10.220 10.733  6.912  3.495</code></pre>
<p>Per tant, tenim la taula
<span class="math display">\[
    \begin{array}{r|c|c}
    \text{Rang de temperatures} &amp; obs_i &amp; esp_i\\
    \hline
    \text{menys de 1.95} &amp; 2 &amp;  0.536 \\
    1.95\text{ a }2.45 &amp; 1 &amp; 2.136 \\
    2.45\text{ a }2.95 &amp; 4  &amp; 5.968 \\
    2.95\text{ a }3.45 &amp; 15 &amp; 10.220 \\
    3.45\text{ a }3.95 &amp; 10 &amp; 10.733  \\
    3.95\text{ a }4.45 &amp; 5 &amp; 6.912 \\
    \text{més de 4.45} &amp; 3  &amp; 3.495
    \end{array}
\]</span>
Tenim freqüències esperades per davall de 5, per tant no podem aplicar el test <span class="math inline">\(\chi^2\)</span> tal qual. El que farem serà agrupar classes contigües a fi d’obtenir freqüències esperades més grans o iguals que 5 amb el màxim de classes. En concret, haurem d’agrupar per un costat les tres primeres classes, i per un altre costat les dues darreres classes
<span class="math display">\[
    \begin{array}{r|c|c}
    \text{Rang de temperatures} &amp; obs_i &amp; esp_i\\\hline
\text{menys de  2.95} &amp; 7  &amp;  8.64\\
2.95\text{ a }3.45 &amp; 15 &amp;  10.22 \\
3.45\text{ a }3.95 &amp; 10 &amp;  10.733  \\
\text{més de 3.95}  &amp; 8&amp; 10.407
\end{array}
\]</span></p>
<p>Ara ja podem aplicar el text <span class="math inline">\(\chi^2\)</span> amb aquestes <span class="math inline">\(k=4\)</span> classes. Com que no hem estimat cap paràmetre, prendrem com a distribució de l’estadístic de contrast una <span class="math inline">\(\chi^2_3\)</span>.</p>
<p><em>Valor de l’estadístic de contrast</em>:
<span class="math display">\[
\begin{array}{rl} 
\chi_0^2 &amp;\displaystyle=\frac{(7-8.64)^2}{8.64}+\frac{(15-10.22)^2}{10.22}\\
&amp;\displaystyle\qquad\quad +\frac{(10-10.733)^2}{10.733}+\frac{(8-10.407)^2}{10.407}=3.154
\end{array}
\]</span></p>
<p><em>p-valor</em>:
<span class="math display">\[
P(\chi_{3}^2\geqslant 3.154)=\texttt{1-pchisq(3.154,3)}=0.37
\]</span></p>
<p><em>Conclusió</em>: Podem acceptar que els augments de temperatures observats segueixen una llei normal <span class="math inline">\(N(3.5,0.7)\)</span> (test <span class="math inline">\(\chi^2\)</span> de Pearson, p-valor=0.37).</p>
<p>Amb R, si aplicam directament la funció <code>chisq-test</code> als vectors de freqüències i probabilitats de les classes originals (bé, de les esteses per cobrir tot <span class="math inline">\(\mathbb{R}\)</span>) R ens avisa que el resultat no és de fiar:</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="chap-bondat.html#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freq.obs,<span class="at">p=</span>prob.esp)</span></code></pre></div>
<pre><code>## Warning in chisq.test(freq.obs, p = prob.esp): Chi-squared approximation may be
## incorrect</code></pre>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  freq.obs
## X-squared = 8.1337, df = 6, p-value = 0.2285</code></pre>
<p>Haurem d’agrupar primer a mà les classes, abans d’aplicar <code>chisq.test</code>:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="chap-bondat.html#cb129-1" aria-hidden="true" tabindex="-1"></a>freq.obs.agrup<span class="ot">=</span><span class="fu">c</span>(<span class="fu">sum</span>(freq.obs[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]),</span>
<span id="cb129-2"><a href="chap-bondat.html#cb129-2" aria-hidden="true" tabindex="-1"></a>   freq.obs[<span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>], <span class="fu">sum</span>(freq.obs[<span class="dv">6</span><span class="sc">:</span><span class="dv">7</span>]))</span>
<span id="cb129-3"><a href="chap-bondat.html#cb129-3" aria-hidden="true" tabindex="-1"></a>prob.esp.agrup<span class="ot">=</span><span class="fu">c</span>(<span class="fu">sum</span>(prob.esp[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]),</span>
<span id="cb129-4"><a href="chap-bondat.html#cb129-4" aria-hidden="true" tabindex="-1"></a>  prob.esp[<span class="dv">4</span><span class="sc">:</span><span class="dv">5</span>], <span class="fu">sum</span>(prob.esp[<span class="dv">6</span><span class="sc">:</span><span class="dv">7</span>]))</span>
<span id="cb129-5"><a href="chap-bondat.html#cb129-5" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freq.obs.agrup, <span class="at">p=</span>prob.esp.agrup)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  freq.obs.agrup
## X-squared = 3.1531, df = 3, p-value = 0.3686</code></pre>
</div>
<div id="mètode-de-montecarlo" class="section level3" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Mètode de Montecarlo</h3>
<p>Quan volem realitzar un test <span class="math inline">\(\chi^2\)</span> i no es compleixen les condicions perquè el p-valor tengui sentit, es pot emprar el <strong>mètode de Montecarlo</strong> (o <strong>basat en simulacions</strong>) per estimar el p-valor:</p>
<ul>
<li><p>Es genera un conjunt molt gran de mostres aleatòries amb la distribució esperada i de la mateixa mida que la nostra mostra</p></li>
<li><p>Es calcula l’estadístic de contrast <span class="math inline">\(\chi^2\)</span> sobre cada mostra</p></li>
<li><p>S’estima el p-valor mitjançant la fracció de mostres que han donat un <span class="math inline">\(\chi^2\)</span> més gran que el de la nostra mostra</p></li>
</ul>
<p>Recordau que ja hem emprat aquest mètode a l’Exemple <a href="chap-bondat.html#exm:grossasim">2.3</a> per “comprovar” el p-valor obtingut a l’Exemple <a href="chap-bondat.html#exm:grossa2">2.2</a> amb el test <span class="math inline">\(\chi^2\)</span> “exacte”. Però no cal complicar-se tant la vida per realitzar-lo.
La funció <code>chisq.test</code> també permet usar el mètode de Montecarlo, entrant-hi el paràmetre <code>simulate.p.value=TRUE</code> i, si es vol, igualant el paràmetre <code>B</code> al nombre de simulacions desitjat (per defecte, en farà 2000). Naturalment, com que es basa en una simulació aleatòria, pot ser que en cada execució doni un p-valor diferent.</p>
<p>Per exemple, podíem emprar el mètode de Montecarlo per realitzar el contrast de l’Exemple <a href="chap-bondat.html#exm:industrial">2.4</a> amb les classes originals esteses, sense agrupar-les.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="chap-bondat.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb131-2"><a href="chap-bondat.html#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(freq.obs, <span class="at">p=</span>prob.esp, <span class="at">simulate.p.value=</span><span class="cn">TRUE</span>, <span class="at">B=</span><span class="dv">5000</span>)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities with simulated p-value (based
## 	on 5000 replicates)
## 
## data:  freq.obs
## X-squared = 8.1337, df = NA, p-value = 0.2206</code></pre>
<p><em>Conclusió</em>: Podem acceptar que els augments de temperatures observats segueixen una llei normal <span class="math inline">\(N(3.5,0.7)\)</span> (test <span class="math inline">\(\chi^2\)</span> de Montecarlo, p-valor=0.22).</p>
<p>Arribam, doncs, a la mateixa conclusió que amb el test <span class="math inline">\(\chi^2\)</span> aplicat a les dades agrupades.</p>
</div>
<div id="test-chi2-amb-paràmetres-poblacionals-desconeguts" class="section level3" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Test <span class="math inline">\(\chi^2\)</span> amb paràmetres poblacionals desconeguts</h3>
<p>De vegades ens interessarà contrastar si les observacions segueixen algun tipus determinat de distribució (Poisson, normal…) amb algun paràmetre indeterminat. En aquest cas, primer estimam els paràmetres desconeguts a partir de les observacions i a continuació contrastam l’ajustament de la mostra a la distribució amb aquests paràmetres. El test és exactament el mateix que el de les seccions anteriors, excepte que ara cal restar al nombre <span class="math inline">\(k-1\)</span> de graus de llibertat de la <span class="math inline">\(\chi^2\)</span> el nombre <span class="math inline">\(m\)</span> de paràmetres que hem estimat.</p>

<div class="rmdimportant">
L’estimació dels paràmetres s’ha de realitzar amb els estimadors màxim versemblants, que són els que maximitzen la probabilitat de la nostra mostra. D’aquesta manera, si amb els paràmetres que fan màxima la probabilitat de la nostra mostra, aquesta encara ens surt molt rara, més evidència tenim que el tipus de distribució no és el correcte.
</div>

<div class="example">
<p><span id="exm:gataca" class="example"><strong>Exemple 2.5  </strong></span>Volem determinar si el nombre de vegades que apareix la seqüència GATACA en una
cadena d’ADN humà de longitud 1000 segueix una llei de Poisson.</p>
</div>
<p>Per fer-ho, prenem 576 mostres de cadenes d’ADN humà de longitud 1000 i hi comptam els nombres de GATACA. Els resultats són els de la taula següent:
<span class="math display">\[
\begin{array}{r|rrrrrr}
\hline
\text{nombre $x_i$ de vegades} &amp; 0 &amp; 1 &amp; 2 &amp; 3 &amp; 4 &amp; 5 \\[-1ex]
\text{que hi apareix GATACA} &amp; &amp; &amp; &amp; &amp; &amp; \\
\hline
\text{freqüència $obs_{i}$} &amp; 229 &amp; 211 &amp; 93 &amp; 35 &amp; 7 &amp; 1 \\
\hline
\end{array}
\]</span></p>
<p><em>Variable aleatòria d’interès</em>, <span class="math inline">\(X\)</span>: Prenc una cadena d’ADN humà de 1000 bases i hi compt el nombre de seqüències GATACA.</p>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{ 
\begin{array}{ll}
H_0: \text{$X$ és de Poisson}\\
H_1: \text{$X$ no és de Poisson}
\end{array}
\right.
\]</span></p>
<p>Per poder calcular les probabilitats de les classes, necessitam estimar el paràmetre <span class="math inline">\(\lambda\)</span> de la variable de Poisson. El seu estimador màxim versemblant és la mitjana mostral:
<span class="math display">\[
\lambda  =\dfrac{229 + 211 +  93 + 35 +7 + 1 }{576}=\dfrac{576}{576}=1
\]</span></p>

<div class="rmderror">
Aquesta no és la mitjana de la mostra!
</div>
<p>Ara sí:
<span class="math display">\[
\begin{array}{rl}
\lambda &amp; =\dfrac{229\cdot 0+ 211\cdot 1+  93\cdot 2+ 35\cdot 3+7\cdot 4+ 1\cdot 5}{576}\\
 &amp; =\dfrac{535}{576}=0.929
 \end{array}
\]</span></p>
<p><em>Estadístic de contrast</em>: Volem emprar el test <span class="math inline">\(\chi^2\)</span>, així que l’estadístic de contrast serà
<span class="math display">\[
\chi^2=\sum_{i=1}^k \frac{(obs_{i}-esp_{i})^2}{esp_{i}}
\]</span></p>
<p>Cal comprovar que se satisfan les condicions del Teorema <a href="chap-bondat.html#thm:khi2BA">2.1</a>.</p>
<ul>
<li><p>La mida de la mostra és <span class="math inline">\(n=576\)</span>, ben gran.</p></li>
<li><p>Per veure si les freqüències esperades són totes més grans o iguals que 5, les hem de calcular.</p></li>
</ul>
<p>Recordem que, si <span class="math inline">\(X\)</span> és una variable aleatòria de Poisson <span class="math inline">\(Po(\lambda)\)</span>,
<span class="math display">\[
P(X=k)=e^{-\lambda}\cdot \frac{\lambda^k}{k!}=\texttt{dpois(k,lambda)}
\]</span></p>
<p>Les probabilitats <span class="math inline">\(p_i\)</span> d’obtenir <span class="math inline">\(i=0,1,2,3,4,5\)</span> són</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="chap-bondat.html#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>,<span class="fl">0.929</span>),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.395 0.367 0.170 0.053 0.012 0.002</code></pre>
<p>i les freqüències esperades <span class="math inline">\(esp_i=p_i\cdot n\)</span> d’aquests valors són</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="chap-bondat.html#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>,<span class="fl">0.929</span>)<span class="sc">*</span><span class="dv">576</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 227.49 211.34  98.17  30.40   7.06   1.31</code></pre>
<p>Obtenim la taula
<span class="math display">\[
\begin{array}{l|rrrrrr}
\hline
x_i &amp; 0 &amp; 1 &amp; 2 &amp; 3 &amp; 4 &amp; 5 \\
\hline
obs_{i} &amp; 229 &amp; 211 &amp; 93 &amp; 35 &amp; 7 &amp; 1 \\
\hline
p_i &amp;0.395 &amp;  0.367  &amp;0.170 &amp; 0.053 &amp; 0.012 &amp; 0.002 \\ \hline
esp_i &amp;  227.49 &amp; 211.34 &amp; 98.17 &amp; 30.40  &amp; 7.06 &amp;  1.31\\ \hline
\end{array}
\]</span></p>

<div class="rmderror">
Aquestes classes estan malament! Recordau que les classes han de cobrir tots els resultats possibles! Els resultats possibles d’una variable Poisson són tots els nombres naturals.
</div>
<p>Per cobrir tots els resultats possibles, cal canviar el 5 per “5 o més” i recalcular la probabilitat i la freqüència esperada d’aquesta classe: la seva probabilitat és <span class="math inline">\(P(X\geqslant 5)=1-P(X\leqslant 4)\)</span></p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="chap-bondat.html#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">ppois</span>(<span class="dv">4</span>,<span class="fl">0.929</span>),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.003</code></pre>
<p>i la seva freqüència esperada és</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="chap-bondat.html#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>((<span class="dv">1</span><span class="sc">-</span><span class="fu">ppois</span>(<span class="dv">4</span>,<span class="fl">0.929</span>))<span class="sc">*</span><span class="dv">576</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1.55</code></pre>
<p>Obtenim la taula
<span class="math display">\[
\begin{array}{l|rrrrrr}
\hline
x_i &amp; 0 &amp; 1 &amp; 2 &amp; 3 &amp; 4 &amp; \geqslant 5 \\
\hline
obs_{i}&amp; 229 &amp; 211 &amp; 93 &amp; 35 &amp; 7 &amp; 1 \\
\hline
p_i &amp;0.395 &amp;  0.367  &amp;0.170 &amp; 0.053 &amp; 0.012 &amp; 0.003 \\ \hline
esp_i &amp;  227.49 &amp; 211.34 &amp; 98.17 &amp; 30.40  &amp; 7.06 &amp;  1.55\\ \hline
\end{array}
\]</span></p>
<p>Perquè totes les classes tenguin freqüència esperada més gran o igual que 5, agruparem les dues darreres classes</p>
<p><span class="math display">\[
\begin{array}{l|rrrrr}
\hline
x_i &amp; 0 &amp; 1 &amp; 2 &amp; 3 &amp; \geqslant 4 \\
\hline
obs_{i}&amp; 229 &amp; 211 &amp; 93 &amp; 35 &amp; 8 \\
\hline
p_i &amp;0.395 &amp;  0.367  &amp;0.170 &amp; 0.053 &amp; 0.015 \\ \hline
esp_i &amp;  227.49 &amp; 211.34 &amp; 98.17 &amp; 30.40  &amp; 8.61\\ \hline
\end{array}
\]</span></p>
<p>Ara totes les freqüències esperades són prou grans i les classes cobreixen tots els valors possibles de la variable. L’estadístic de contrast té distribució <span class="math inline">\(\chi_{k-1}^2\)</span> amb <span class="math inline">\(k=5\)</span>, per tant <span class="math inline">\(\chi_{4}^2\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/batman.png" width="40%" style="display: block; margin: auto;" /></p>

<div class="rmderror">
Com que hem estimat la <span class="math inline">\(\lambda\)</span>, hem de considerar l’estadístic de contrast amb distribució <span class="math inline">\(\chi_{k-1-m}^2\)</span> amb <span class="math inline">\(k\)</span> el nombre de classes i <span class="math inline">\(m\)</span> el nombre de paràmetres estimats, en aquest cas 1.
</div>
<p>Perdó. L’estadístic de contrast té distribució <span class="math inline">\(\chi_{3}^2\)</span>. Podem continuar.</p>
<p><em>Valor de l’estadístic de contrast</em>:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="chap-bondat.html#cb141-1" aria-hidden="true" tabindex="-1"></a>obs.gataca<span class="ot">=</span><span class="fu">c</span>(<span class="dv">229</span>,<span class="dv">211</span>,<span class="dv">93</span>,<span class="dv">35</span>,<span class="dv">8</span>)</span>
<span id="cb141-2"><a href="chap-bondat.html#cb141-2" aria-hidden="true" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">sum</span>(obs.gataca)</span>
<span id="cb141-3"><a href="chap-bondat.html#cb141-3" aria-hidden="true" tabindex="-1"></a>probs.gataca<span class="ot">=</span><span class="fu">c</span>(<span class="fu">dpois</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">3</span>,<span class="fl">0.929</span>),<span class="dv">1</span><span class="sc">-</span><span class="fu">ppois</span>(<span class="dv">3</span>,<span class="fl">0.929</span>))</span>
<span id="cb141-4"><a href="chap-bondat.html#cb141-4" aria-hidden="true" tabindex="-1"></a>esp.gataca<span class="ot">=</span>probs.gataca<span class="sc">*</span>n</span>
<span id="cb141-5"><a href="chap-bondat.html#cb141-5" aria-hidden="true" tabindex="-1"></a>X02<span class="ot">=</span><span class="fu">sum</span>((obs.gataca<span class="sc">-</span>esp.gataca)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>esp.gataca)</span>
<span id="cb141-6"><a href="chap-bondat.html#cb141-6" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(X02,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1.02</code></pre>
<p><em>p-valor</em>: <span class="math inline">\(P(\chi_3^2\geqslant 1.02)=\texttt{1-pchisq(1.02,3)}=0.796\)</span></p>
<p><em>Conclusió</em>: Podem acceptar que les observacions trobades segueixen una llei de Poisson (test <span class="math inline">\(\chi^2\)</span> de Pearson, p-valor 0.796).</p>
<p>Amb R simplement ens estalviam el càlcul explícit de <span class="math inline">\(\chi_0^2\)</span> i del p-valor, perquè tota la saragata de calcular freqüències esperades i agrupar a fi que se satisfaci la llei de Cochran no ens la podem estalviar.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="chap-bondat.html#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(obs.gataca,<span class="at">p=</span>probs.gataca)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  obs.gataca
## X-squared = 1.0215, df = 4, p-value = 0.9065</code></pre>
<p><em>Conclusió</em>: No podem rebutjar que les observacions trobades segueixin una llei de Poisson (test <span class="math inline">\(\chi^2\)</span> de Pearson, p-valor <strong>0.9065????</strong>).</p>

<div class="rmderror">
No havíem quedat que el nombre de graus de llibertat era 3? R n’ha emprat 4, <code>df=4</code>, perquè no sap que hem estimat un paràmetre
</div>
<p>R ha calculat el p-valor prenent <span class="math inline">\(\chi_4^2\)</span>, nosaltres l’hem de calcular amb <span class="math inline">\(\chi_3^2\)</span>:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="chap-bondat.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">pchisq</span>(<span class="fl">1.0215</span>,<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.7960498</code></pre>
<p>Ara ja tenim el mateix p-valor que abans.</p>
</div>
</div>
<div id="test-de-kolmogorov-smirnov" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Test de Kolmogorov-Smirnov</h2>
<p>El <strong>test de Kolgomorov-Smirnov</strong> (<strong>test K-S</strong>, per abreviar) és el test més popular per contrastar si una mostra segueix o no una distribució <strong>contínua</strong> completament determinada, <strong>sense restriccions sobre la mida de la mostra</strong>. Es pot emprar amb tota distribució contínua sempre que estigui completament especificada.</p>

<div class="rmdnote">
Per a distribucions concretes, mides de mostres dins marges concrets o quan hem d’estimar els paràmetres, existeixen mètodes específics millors que el K-S, però no els veurem aquí. Estan a la <a href="https://aprender-uib.github.io/AprendeR2/chap-bondad.html#tests-de-normalidad">lliçó corresponent de R</a>.
</div>
<p>Tot seguit explicam com funciona aquest test.</p>
<p>Partim d’una mostra <span class="math inline">\(x_1,x_2,\ldots,x_n\)</span> <em>amb tots els valors diferents</em> i volem contrastar si ha estat produïda per una variable <span class="math inline">\(X\)</span> contínua amb funció de distribució <span class="math inline">\(F_X\)</span>.</p>
<p>Per exemple, suposem que volem contrastar si podem acceptar que els valors del vector següent provenen d’una distribució normal <span class="math inline">\(N(3,1.5)\)</span>.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="chap-bondat.html#cb147-1" aria-hidden="true" tabindex="-1"></a>valors<span class="ot">=</span><span class="fu">c</span>(<span class="fl">5.84</span>,<span class="fl">4.57</span>,<span class="fl">1.34</span>,<span class="fl">3.58</span>,<span class="fl">1.54</span>,<span class="fl">2.25</span>)</span></code></pre></div>
<p>Sigui <span class="math inline">\(X\)</span> la variable aleatòria que ha produït aquest conjunt de números. Aleshores, el <em>contrast</em> és
<span class="math display">\[
\left\{
\begin{array}{l}
H_0: \text{$X$ és $N(3,1.5)$}\\
H_0: \text{$X$ no és $N(3,1.5)$}
\end{array}
\right.
\]</span></p>
<ol style="list-style-type: decimal">
<li>Ordenam la mostra: <span class="math inline">\(x_{(1)}&lt; x_{(2)}&lt;\cdots&lt; x_{(n)}\)</span>.</li>
</ol>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="chap-bondat.html#cb148-1" aria-hidden="true" tabindex="-1"></a>valors<span class="ot">=</span><span class="fu">sort</span>(valors)</span>
<span id="cb148-2"><a href="chap-bondat.html#cb148-2" aria-hidden="true" tabindex="-1"></a>valors</span></code></pre></div>
<pre><code>## [1] 1.34 1.54 2.25 3.58 4.57 5.84</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><p>Consideram la <strong>funció de distribució mostral</strong> <span class="math inline">\(F_{n}\)</span>
d’aquesta mostra: la funció de distribució d’una variable <span class="math inline">\(n\)</span> amb domini tot <span class="math inline">\(\mathbb{R}\)</span> per a la qual cada <span class="math inline">\(x_{(i)}\)</span> tingués probabilitat <span class="math inline">\(1/n\)</span> i la resta de reals tingués probabilitat 0:
<span class="math display">\[
F_n(x)=\left\{\begin{array}{ll}
0 &amp;\text{ si } x&lt; x_{(1)} \\
\dfrac{k}{n}&amp;\text{ si } x_{(k)}\leqslant x &lt; x_{(k+1)}\\
1 &amp; \text{ si } x_{(n)} \leqslant x
\end{array}
\right.
\]</span></p>
<p>A la nostra mostra ja ordenada, seria
<span class="math display">\[
F_6(x)=\left\{\begin{array}{ll}
0 &amp;\text{ si } x&lt; 1.34 \\
1/6 &amp;\text{ si } 1.34\leqslant x &lt;1.54\\
2/6 &amp;\text{ si } 1.54\leqslant x &lt;2.25\\
3/6 &amp;\text{ si } 2.25\leqslant x &lt;3.58\\
4/6 &amp;\text{ si } 3.58\leqslant x &lt;4.57\\
5/6 &amp;\text{ si } 4.57\leqslant x &lt;5.84\\
1 &amp;\text{ si } 5.84\leqslant x 
\end{array}
\right.
\]</span>
El gràfic d’aquesta distribució és el següent:</p></li>
</ol>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="chap-bondat.html#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">c</span>(<span class="dv">1</span>,valors,<span class="dv">7</span>), <span class="fu">c</span>(<span class="dv">0</span>,(<span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>)<span class="sc">/</span><span class="dv">5</span>,<span class="dv">1</span>), <span class="at">type=</span><span class="st">&quot;s&quot;</span>, <span class="at">lwd=</span><span class="fl">1.5</span>, </span>
<span id="cb150-2"><a href="chap-bondat.html#cb150-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-147-1.png" width="50%" style="display: block; margin: auto;" /></p>
<ol start="3" style="list-style-type: decimal">
<li>Comparam la funció <span class="math inline">\(F_n(x)\)</span> amb la funció de distribució <span class="math inline">\(F_X(x)\)</span> que tendria la variable aleatòria <span class="math inline">\(X\)</span> si satisfés la hipòtesi nul·la. Si són molt diferents, rebutjarem que la variable <span class="math inline">\(X\)</span> que ha produït la mostra tengui funció de distribució <span class="math inline">\(F_X\)</span>.</li>
</ol>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="chap-bondat.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">c</span>(<span class="dv">1</span>,valors,<span class="dv">6</span>),<span class="fu">c</span>(<span class="dv">0</span>,(<span class="dv">0</span><span class="sc">:</span><span class="dv">5</span>)<span class="sc">/</span><span class="dv">5</span>,<span class="dv">1</span>),<span class="at">type=</span><span class="st">&quot;s&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;&quot;</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)</span>
<span id="cb151-2"><a href="chap-bondat.html#cb151-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">pnorm</span>(x,<span class="dv">3</span>,<span class="fl">1.5</span>),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lwd=</span><span class="fl">1.5</span>,<span class="at">add=</span><span class="cn">TRUE</span>)</span>
<span id="cb151-3"><a href="chap-bondat.html#cb151-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>),<span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb151-4"><a href="chap-bondat.html#cb151-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend=</span><span class="fu">c</span>(<span class="fu">expression</span>(F[<span class="dv">6</span>]),<span class="st">&quot;N(3,1.5)&quot;</span>),<span class="at">cex=</span><span class="fl">0.7</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-148-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Per comparar <span class="math inline">\(F_n(x)\)</span> amb <span class="math inline">\(F_X(x)\)</span>, calcularem
<span class="math display">\[
\max\{|F_n(x)-F_X(x)|\mid x\in \mathbb{R}\}
\]</span>
Com que <span class="math inline">\(F_X\)</span> és creixent, aquest màxim s’assoleix a qualque escaló.
Per tant, per calcular aquest màxim primer calculam, per a cada <span class="math inline">\(x_{(i)}\)</span>, la seva <strong>discrepància</strong>: la distància entre <span class="math inline">\(F_X(x_{(i)})\)</span> i els extrems de l’escaló corresponent,
<span class="math display">\[
D_n(x_{(i)})=\max\Big\{\Big| F_X(x_{(i)})-\frac{i-1}{n}\Big|, \Big|F_{X}(x_{(i)})-\frac{i}{n}\Big|\Big\}
\]</span>
i prenem la <strong>discrepància màxima</strong>, és a dir, el màxim d’aquestes discrepàncies:
<span class="math display">\[
D_n=\max\big\{D_n(x_{(i)})\mid i=1,\ldots, n\big\}
\]</span></p>
<p>Al nostre exemple, els valors <span class="math inline">\(F_X(x_{(i)})\)</span> són:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="chap-bondat.html#cb152-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">pnorm</span>(valors,<span class="dv">3</span>,<span class="fl">1.5</span>),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.134 0.165 0.309 0.650 0.852 0.971</code></pre>
<p>i per tant les discrepàncies són
<span class="math display">\[
\begin{array}{rl}
D_6(x_{(1)}) &amp; =\max\{| F_X(1.34)-0|, |F_X(1.34)-1/6|\}\\
&amp; =\max\{|0.134-0|, |0.134-1/6|\}\\
&amp; =\max\{ 0.134, 0.033\}=0.134\\[2ex]
D_6(x_{(2)}) &amp; =\max\{| F_X(1.54)-1/6|, |F_X(1.54)-2/6|\}\\
&amp; =\max\{| 0.165-1/6|, |0.165-2/6|\}\\
&amp; =\max\{ 0.002, 0.168\}=0.168\\[2ex]
D_6(x_{(3)}) &amp; =\max\{| F_X(2.25)-2/6|, |F_X(2.25)-3/6|\}\\
&amp; =\max\{|0.309-2/6|, |0.309-3/6|\}\\
&amp; =\max\{ 0.024, 0.191\}=0.191\\[2ex]
D_6(x_{(4)}) &amp; =\max\{| F_X(3.58)-3/6|, |F_X(3.58)-4/6|\}\\
&amp; =\max\{| 0.65-3/6|, |0.65-4/6|\}\\
&amp; =\max\{ 0.15, 0.017\}=0.15\\[2ex]
D_6(x_{(5)})  &amp; =\max\{| F_X(4.57)-4/6|, |F_X(4.57)-5/6|\}\\
&amp; =\max\{|0.852-4/6|, |0.852-5/6|\}\\
&amp; =\max\{ 0.185, 0.019\}=0.185\\[2ex]
D_6(x_{(6)}) &amp; =\max\{| F_X(5.84)-5/6|, |F_X(5.84)-6/6|\}\\
&amp; =\max\{| 0.971-5/6|, |0.971-1|\}\\
&amp; =\max\{ 0.138, 0.029\}=0.138
\end{array}
\]</span>
i la discrepància màxima és
<span class="math display">\[
D_6=\max\{0.134,0.168,0.191,0.15,0.185,0.138\}=0.191
\]</span></p>
<ol start="4" style="list-style-type: decimal">
<li><p>Aquesta discrepància màxima segueix una distribució coneguda (que no depèn de la <span class="math inline">\(X\)</span> mentre sigui contínua) que permet calcular el p-valor com la probabilitat que <span class="math inline">\(D_n\)</span> prengui un valor més gran o igual que l’obtingut sobre la nostra mostra. Al nostre exemple, seria <span class="math inline">\(P(D_6\geqslant 0.191)\)</span>.</p>
<p>La corresponent funció de distribució acumulada és donada per la funció <code>pkolm</code> del paquet <strong>kolmim</strong>. Per tant, el p-valor és</p></li>
</ol>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="chap-bondat.html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kolmim)</span>
<span id="cb154-2"><a href="chap-bondat.html#cb154-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pkolm</span>(<span class="fl">0.191</span>,<span class="dv">6</span>),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>## [1] 0.951</code></pre>
<p><em>Conclusió</em>: Podem acceptar que la mostra prové d’una variable aleatòria normal amb <span class="math inline">\(\mu=3\)</span> i <span class="math inline">\(\sigma=1.5\)</span> (test de Kolmogorov-Smirnov, p-valor 0.95)</p>
<p>Per realitzar un test K-S amb R, disposam de la instrucció</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="chap-bondat.html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(x,<span class="st">&quot;pdistribució&quot;</span>,paràmetres)</span></code></pre></div>
<p>on <code>x</code> és el vector que conté la mostra, la <code>pdistribució</code> és la funció de distribució que contrastam, i els <code>paràmetres</code> són els de la distribució tal i com els entraríem a la funció <code>pdistribució</code>. Al nostre exemple, simplement entraríem</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="chap-bondat.html#cb157-1" aria-hidden="true" tabindex="-1"></a>valors<span class="ot">=</span><span class="fu">c</span>(<span class="fl">5.84</span>,<span class="fl">4.57</span>,<span class="fl">1.34</span>,<span class="fl">3.58</span>,<span class="fl">1.54</span>,<span class="fl">2.25</span>)</span>
<span id="cb157-2"><a href="chap-bondat.html#cb157-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ks.test</span>(valors,<span class="st">&quot;pnorm&quot;</span>,<span class="dv">3</span>,<span class="fl">1.5</span>)</span></code></pre></div>
<pre><code>## 
## 	One-sample Kolmogorov-Smirnov test
## 
## data:  valors
## D = 0.19146, p-value = 0.95
## alternative hypothesis: two-sided</code></pre>
<p>Dóna el valor de l’estadístic (la <code>D</code>) i el p-valor</p>
</div>
<div id="test-de-kolmogorov-smirnov-lilliefors" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Test de Kolmogorov-Smirnov-Lilliefors</h2>
<p>Quan es vol emprar el test K-S per contrastar si una mostra prové de <strong>qualque</strong> distribució normal, i no d’una concreta, l’opció més popular és:</p>
<ul>
<li><p>Estimar els paràmetres de la normal a partir de la mostra</p></li>
<li><p>Calcular l’estadístic del test K-S amb aquests paràmetres</p></li>
<li><p>Emprar la distribució del <strong>test K-S-Lilliefors</strong> per calcular el p-valor</p></li>
</ul>
<p>Amb R, aquest test està implementat en la funció <code>lillie.test</code> del paquet <strong>nortest</strong>.</p>
<p>Per exemple, si ens haguéssim demanat d’entrada si la nostra mostra prové de <strong>qualque variable normal</strong>, haguéssim entrat</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="chap-bondat.html#cb159-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb159-2"><a href="chap-bondat.html#cb159-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(valors)</span></code></pre></div>
<pre><code>## 
## 	Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  valors
## D = 0.19912, p-value = 0.6425</code></pre>

<div class="rmdnote">
L’estadístic de contrast no val el mateix que abans, perquè ara la variable normal que contrasta té paràmetres
<span class="math inline">\(\mu=\texttt{mean(valors)}=3.187\)</span> i <span class="math inline">\(\sigma=\texttt{sd(valors)}=1.795\)</span>.
</div>

<div class="example">
<p><span id="exm:tempsnormals" class="example"><strong>Exemple 2.6  </strong></span>Podem acceptar que les variables <span class="math inline">\(X_d\)</span> i <span class="math inline">\(X_h\)</span> de l’Exemple <a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exm:temphomesdones">1.4</a> són normals?</p>
</div>
<p>Apliquem el test K-S-Lilliefors a les dues mostres:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="chap-bondat.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(X_d)</span></code></pre></div>
<pre><code>## 
## 	Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  X_d
## D = 0.08289, p-value = 0.04842</code></pre>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="chap-bondat.html#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(X_h)</span></code></pre></div>
<pre><code>## 
## 	Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  X_h
## D = 0.055977, p-value = 0.5128</code></pre>
<p>Podem acceptar que les temperatures dels homes tenen distribució normal, però essent rigorosos, amb nivell de significació 0.05 no podem acceptar que <span class="math inline">\(X_d\)</span> sigui normal.</p>
</div>
<div id="test-de-la-lliçó-7" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Test de la lliçó 7</h2>
<p><strong>(1)</strong> Quina o quines de les afirmacions següents són vertaderes sobre un test <span class="math inline">\(\chi^2\)</span> de bondat d’ajust?</p>
<ol style="list-style-type: decimal">
<li>Si la mostra és de mida com a mínim 30, segur que podem aplicar-lo</li>
<li>Si la mida de la mostra és menor que 30, no podem aplicar-lo</li>
<li>Si la mostra és de mida com a mínim 30, i empram 4 classes, segur que podem aplicar-lo</li>
<li>Si alguna freqüència observada és més petita que 5, no podem aplicar-lo</li>
<li>Si alguna freqüència esperada és més petita que 5, no podem aplicar-lo</li>
<li>Cap de les altres afirmacions és vertadera</li>
</ol>
<p><strong>(2)</strong> Quina o quines de les afirmacions següents són vertaderes sobre un test <span class="math inline">\(\chi^2\)</span> de bondat d’ajust?</p>
<ol style="list-style-type: decimal">
<li>Si totes les freqüències observades són més grans o iguals que 5, segur que podem aplicar-lo</li>
<li>Si totes les freqüències esperades són més grans o iguals que 5, segur que podem aplicar-lo</li>
<li>Si totes les freqüències observades són més grans o iguals que 5, i empram 10 classes, segur que podem aplicar-lo</li>
<li>Si totes les freqüències esperades són més grans o iguals que 5, i empram 10 classes, segur que podem aplicar-lo</li>
<li>Cap de les altres afirmacions és vertadera</li>
</ol>
<p><strong>(3)</strong> En un contrast de bondat d’ajust, volem contrastar a partir d’una sèrie de llançaments d’un dau si aquest dau està equilibrat o trucat. Quina de les afirmacions següents és correcta?</p>
<ol style="list-style-type: decimal">
<li>La hipòtesi nul·la és que el dau està equilibrat</li>
<li>La hipòtesi nul·la és que el dau podria estar equilibrat</li>
<li>La hipòtesi nul·la és que el dau podria estar trucat</li>
<li>La hipòtesi nul·la és que el dau està trucat</li>
<li>Cap de les altres respostes és correcta</li>
</ol>
<p><strong>(4)</strong> En un contrast de bondat d’ajust on volem emprar un test <span class="math inline">\(\chi^2\)</span> per contrastar a partir d’una sèrie de llançaments d’un dau de 10 cares si aquest dau està equilibrat o trucat, quina o quines de les afirmacions següents són correctes?</p>
<ol style="list-style-type: decimal">
<li>Si a la nostra mostra no hi obtenim cap 4, no cal considerar aquest valor a l’hora de fer el test <span class="math inline">\(\chi^2\)</span></li>
<li>Si a la nostra mostra no hi obtenim cap 4, no podem aplicar un test <span class="math inline">\(\chi^2\)</span></li>
<li>Si la nostra mostra és de 40 llançaments segur que podem aplicar un test <span class="math inline">\(\chi^2\)</span></li>
<li>Si la nostra mostra és de 40 llançaments segur que no podem aplicar un test <span class="math inline">\(\chi^2\)</span></li>
<li>Si la nostra mostra és de 40 llançaments, pot ser que poguem aplicar un test <span class="math inline">\(\chi^2\)</span> i pot ser que no el poguem aplicar</li>
<li>Si la nostra mostra és de 50 llançaments segur que no podem aplicar un test <span class="math inline">\(\chi^2\)</span></li>
<li>Si la nostra mostra és de 50 llançaments, pot ser que poguem aplicar un test <span class="math inline">\(\chi^2\)</span> i pot ser que no el poguem aplicar</li>
<li>Si la nostra mostra és de 50 llançaments, segur que podem aplicar un test <span class="math inline">\(\chi^2\)</span></li>
<li>Cap de les altres afirmacions és correcta</li>
</ol>
<p><strong>(5)</strong> Tenim una variable aleatòria <span class="math inline">\(X\)</span> que pot prendre els valors 1, 2, 3 o 4. En prenem una mostra, i a partir d’aquesta mostra volem contrastar si la densitat d’aquesta variable és <span class="math inline">\(P(X=1)=P(X=2)=0.2\)</span>, <span class="math inline">\(P(X=3)=P(X=4)=0.3\)</span>. Quina o quines de les afirmacions següents són correctes?</p>
<ol style="list-style-type: decimal">
<li>La hipòtesi nul·la és que X pren els valors 1,2,3,4 de manera equiprobable</li>
<li>La hipòtesi nul·la és que X pren els valors 1,2,3,4 amb probabilitats <span class="math inline">\(P(X=1)=P(X=2)=0.2\)</span>, <span class="math inline">\(P(X=3)=P(X=4)=0.3\)</span></li>
<li>La hipòtesi alternativa és que X pren els valors 1,2,3,4 amb probabilitats <span class="math inline">\(P(X=1)=P(X=2)=0.2\)</span>, <span class="math inline">\(P(X=3)=P(X=4)=0.3\)</span></li>
<li>La hipòtesi alternativa és que X pren els valors 1,2,3,4 de manera equiprobable</li>
<li>La hipòtesi alternativa és que X no pren els valors 1,2,3,4 de manera equiprobable</li>
<li>Cap de les altres respostes és correcta</li>
</ol>
<p><strong>(6)</strong> Volem contrastar si una mostra de 35 valors s’ajusta a una certa distribució usant un test <span class="math inline">\(\chi^2\)</span>. Quina de les afirmacions següents és vertadera?</p>
<ol style="list-style-type: decimal">
<li>Pot ser que puguem emprar 5 classes, però segur que no en podrem emprar 6</li>
<li>Pot ser que puguem emprar 6 classes, però segur que no en podrem emprar 7</li>
<li>Pot ser que puguem emprar 7 classes, però segur que no en podrem emprar 8</li>
<li>Pot ser que puguem emprar 8 classes, però segur que no en podrem emprar 9</li>
<li>Pot ser que puguem emprar 9 classes, però segur que no en podrem emprar 10</li>
<li>Cap de les altres afirmacions és vertadera</li>
</ol>
<p><strong>(7)</strong> Volem contrastar si una mostra de nombres de malalts prové d’una variable aleatòria amb alguna distribució de Poisson usant un test <span class="math inline">\(\chi^2\)</span>. Quina o quines de les afirmacions següents són correctes?</p>
<ol style="list-style-type: decimal">
<li>Podem prendre com a classes tots els valors possibles de la variable</li>
<li>Si la mostra és de 30 o més individus, segur que podem fer servir el test <span class="math inline">\(\chi^2\)</span>, independentment de les classes que prenguem</li>
<li>Si la freqüència esperada de cada classe que prenguem és com a mínim 5, segur que podem fer servir el test <span class="math inline">\(\chi^2\)</span></li>
<li>Si la mostra és de 30 o més individus i empram classes que tenguin freqüències observades com a mínim 5, segur que podem fer servir el test <span class="math inline">\(\chi^2\)</span></li>
<li>Alguna classe haurà de contenir un nombre infinit de valors possibles</li>
<li>No fa falta estimar la lambda per emprar un test <span class="math inline">\(\chi^2\)</span></li>
<li>Totes les altres afirmacions són falses</li>
</ol>
<p><strong>(8)</strong> Volem contrastar si una mostra de nombres de malalts prové d’una variable aleatòria amb alguna distribució de Poisson usant un test <span class="math inline">\(\chi^2\)</span>. Quina o quines de les afirmacions següents són correctes?</p>
<ol style="list-style-type: decimal">
<li>El nombre de graus de llibertat de la distribució de l’estadístic que hauríem d’emprar per calcular el p-valor és el nombre de classes menys 1</li>
<li>El nombre de graus de llibertat de la distribució de l’estadístic que hauríem d’emprar per calcular el p-valor és el nombre de classes menys 2</li>
<li>El nombre de graus de llibertat de la distribució de l’estadístic que hauríem d’emprar per calcular el p-valor és el nombre de classes menys 3</li>
<li>Totes les altres afirmacions són falses</li>
</ol>
<p><strong>(9)</strong> En un contrast de bondat d’ajust per decidir si una mostra s’ajusta a una variable normal o no, obtenim un p-valor més gran que el nivell de significació. Quina o quines de les afirmacions següents són correctes?</p>
<ol style="list-style-type: decimal">
<li>Concloem que la variable no segueix una distribució normal</li>
<li>Acceptam que la variable segueix una distribució normal.</li>
<li>Hem obtingut evidència estadísticament significativa que la variable és normal.</li>
<li>No hem obtingut evidència estadísticament significativa que la variable sigui normal.</li>
<li>No hem obtingut evidència estadísticament significativa que la variable no sigui normal.</li>
<li>Podria tractar-se d’un error de tipus I</li>
<li>Podria tractar-se d’un error de tipus II</li>
<li>Totes les altres afirmacions són falses.</li>
</ol>
<p><strong>(10)</strong> En un test <span class="math inline">\(\chi^2\)</span> on contrastau si la mostra s’ajusta a alguna variable normal hi emprau 10 classes. Quants graus de llibertat tendrà l’estadístic de contrast que heu d’emprar per calcular el p-valor?</p>
<ol style="list-style-type: decimal">
<li>12</li>
<li>11</li>
<li>10</li>
<li>9</li>
<li>8</li>
<li>7</li>
<li>6</li>
</ol>
<p><strong>(11)</strong> Va, vegem si llegiu els apunts. Si <span class="math inline">\(X\)</span> és variable<span class="math inline">\(\chi_n^2\)</span>, quin dels valors següents és el més petit d’aquesta llista que <strong>us diem</strong> en una nota que la probabilitat que <span class="math inline">\(X\)</span> sigui més gran que ell és molt petita?</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(n\)</span></li>
<li><span class="math inline">\(2n\)</span></li>
<li><span class="math inline">\(3n\)</span></li>
<li><span class="math inline">\(4n\)</span></li>
<li><span class="math inline">\(5n\)</span></li>
<li>42</li>
</ol>
<p><strong>(12)</strong> Podem emprar un test de Kolgomorov-Smirnov per contrastar a partir d’una mostra si una variable poblacional és de Poisson?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="contrastos-dindependència-i-homogeneïtat.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
