<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tema 9 Introducció a l’estadística multidimensional | Matemàtiques II v.2021</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Tema 9 Introducció a l’estadística multidimensional | Matemàtiques II v.2021" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 9 Introducció a l’estadística multidimensional | Matemàtiques II v.2021" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2021-03-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="contrastos-dindependència-i-homogeneïtat.html"/>

<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="chapter" data-level="1" data-path="chap-conceptes.html"><a href="chap-conceptes.html"><i class="fa fa-check"></i><b>1</b> Alguns conceptes bàsics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chap-conceptes.html"><a href="chap-conceptes.html#tipus-de-dades"><i class="fa fa-check"></i><b>1.1</b> Tipus de dades</a></li>
<li class="chapter" data-level="1.2" data-path="chap-conceptes.html"><a href="chap-conceptes.html#població"><i class="fa fa-check"></i><b>1.2</b> Població</a></li>
<li class="chapter" data-level="1.3" data-path="chap-conceptes.html"><a href="chap-conceptes.html#variable-aleatòria"><i class="fa fa-check"></i><b>1.3</b> Variable aleatòria</a></li>
<li class="chapter" data-level="1.4" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostra"><i class="fa fa-check"></i><b>1.4</b> Mostra</a></li>
<li class="chapter" data-level="1.5" data-path="chap-conceptes.html"><a href="chap-conceptes.html#sec:mostreig"><i class="fa fa-check"></i><b>1.5</b> Mostreig aleatori</a></li>
<li class="chapter" data-level="1.6" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostres-de-conveniència"><i class="fa fa-check"></i><b>1.6</b> Mostres de conveniència</a></li>
<li class="chapter" data-level="1.7" data-path="chap-conceptes.html"><a href="chap-conceptes.html#test-de-la-lliçó-1"><i class="fa fa-check"></i><b>1.7</b> Test de la lliçó 1</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-varal.html"><a href="chap-varal.html"><i class="fa fa-check"></i><b>2</b> Variables aleatòries</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap-varal.html"><a href="chap-varal.html#generalitats-sobre-variables-aleatòries"><i class="fa fa-check"></i><b>2.1</b> Generalitats sobre variables aleatòries</a></li>
<li class="chapter" data-level="2.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-discretes"><i class="fa fa-check"></i><b>2.2</b> Variables aleatòries discretes</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució"><i class="fa fa-check"></i><b>2.2.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="2.2.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança"><i class="fa fa-check"></i><b>2.2.2</b> Esperança</a></li>
<li class="chapter" data-level="2.2.3" data-path="chap-varal.html"><a href="chap-varal.html#variància-i-desviació-típica"><i class="fa fa-check"></i><b>2.2.3</b> Variància i desviació típica</a></li>
<li class="chapter" data-level="2.2.4" data-path="chap-varal.html"><a href="chap-varal.html#quantils"><i class="fa fa-check"></i><b>2.2.4</b> Quantils</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chap-varal.html"><a href="chap-varal.html#famílies-importants-de-variables-aleatòries-discretes"><i class="fa fa-check"></i><b>2.3</b> Famílies importants de variables aleatòries discretes</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-binomials"><i class="fa fa-check"></i><b>2.3.1</b> Variables aleatòries binomials</a></li>
<li class="chapter" data-level="2.3.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-hipergeomètriques"><i class="fa fa-check"></i><b>2.3.2</b> Variables aleatòries hipergeomètriques</a></li>
<li class="chapter" data-level="2.3.3" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-de-poisson"><i class="fa fa-check"></i><b>2.3.3</b> Variables aleatòries de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-contínues"><i class="fa fa-check"></i><b>2.4</b> Variables aleatòries contínues</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució-1"><i class="fa fa-check"></i><b>2.4.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="2.4.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança-variància-quantils"><i class="fa fa-check"></i><b>2.4.2</b> Esperança, variància, quantils…</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chap-varal.html"><a href="chap-varal.html#sec:normal"><i class="fa fa-check"></i><b>2.5</b> Variables aleatòries normals</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i><b>2.5.1</b> Amb R</a></li>
<li class="chapter" data-level="2.5.2" data-path="chap-varal.html"><a href="chap-varal.html#propietats-bàsiques"><i class="fa fa-check"></i><b>2.5.2</b> Propietats bàsiques</a></li>
<li class="chapter" data-level="2.5.3" data-path="chap-varal.html"><a href="chap-varal.html#intervals-de-referència"><i class="fa fa-check"></i><b>2.5.3</b> Intervals de referència</a></li>
<li class="chapter" data-level="2.5.4" data-path="chap-varal.html"><a href="chap-varal.html#sec:lognormal"><i class="fa fa-check"></i><b>2.5.4</b> Variables log-normals</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="chap-varal.html"><a href="chap-varal.html#test-de-la-lliçó-2"><i class="fa fa-check"></i><b>2.6</b> Test de la lliçó 2</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-estim.html"><a href="chap-estim.html"><i class="fa fa-check"></i><b>3</b> Estimació puntual</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap-estim.html"><a href="chap-estim.html#estimadors"><i class="fa fa-check"></i><b>3.1</b> Estimadors</a></li>
<li class="chapter" data-level="3.2" data-path="chap-estim.html"><a href="chap-estim.html#mitjana-mostral"><i class="fa fa-check"></i><b>3.2</b> Mitjana mostral</a></li>
<li class="chapter" data-level="3.3" data-path="chap-estim.html"><a href="chap-estim.html#proporció-mostral"><i class="fa fa-check"></i><b>3.3</b> Proporció mostral</a></li>
<li class="chapter" data-level="3.4" data-path="chap-estim.html"><a href="chap-estim.html#variància-mostral"><i class="fa fa-check"></i><b>3.4</b> Variància mostral</a></li>
<li class="chapter" data-level="3.5" data-path="chap-estim.html"><a href="chap-estim.html#la-distribució-t-de-student"><i class="fa fa-check"></i><b>3.5</b> La distribució t de Student</a></li>
<li class="chapter" data-level="3.6" data-path="chap-estim.html"><a href="chap-estim.html#biaix-i-precisió"><i class="fa fa-check"></i><b>3.6</b> Biaix i precisió</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="chap-estim.html"><a href="chap-estim.html#estimadors-no-esbiaixats"><i class="fa fa-check"></i><b>3.6.1</b> Estimadors no esbiaixats</a></li>
<li class="chapter" data-level="3.6.2" data-path="chap-estim.html"><a href="chap-estim.html#sec:precis"><i class="fa fa-check"></i><b>3.6.2</b> Estimadors precisos</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="chap-estim.html"><a href="chap-estim.html#estimadors-màxim-versemblants"><i class="fa fa-check"></i><b>3.7</b> Estimadors màxim versemblants</a></li>
<li class="chapter" data-level="3.8" data-path="chap-estim.html"><a href="chap-estim.html#sec:pobl"><i class="fa fa-check"></i><b>3.8</b> Estimació de poblacions</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="chap-estim.html"><a href="chap-estim.html#estimació-de-poblacions-numerades"><i class="fa fa-check"></i><b>3.8.1</b> Estimació de poblacions numerades</a></li>
<li class="chapter" data-level="3.8.2" data-path="chap-estim.html"><a href="chap-estim.html#marca-recaptura"><i class="fa fa-check"></i><b>3.8.2</b> Marca-recaptura</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="chap-estim.html"><a href="chap-estim.html#test-de-la-lliçó-3"><i class="fa fa-check"></i><b>3.9</b> Test de la lliçó 3</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-IC.html"><a href="chap-IC.html"><i class="fa fa-check"></i><b>4</b> Intervals de confiança</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chap-IC.html"><a href="chap-IC.html#definició-dinterval-de-confiança"><i class="fa fa-check"></i><b>4.1</b> Definició d’interval de confiança</a></li>
<li class="chapter" data-level="4.2" data-path="chap-IC.html"><a href="chap-IC.html#exemple-interval-de-confiança-del-95-per-a-la-mitjana-duna-variable-aleatòria-normal"><i class="fa fa-check"></i><b>4.2</b> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</a></li>
<li class="chapter" data-level="4.3" data-path="chap-IC.html"><a href="chap-IC.html#interval-de-confiança-per-a-la-mitjana-basat-en-la-t-de-student"><i class="fa fa-check"></i><b>4.3</b> Interval de confiança per a la mitjana basat en la t de Student</a>
<ul>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#la-fórmula"><i class="fa fa-check"></i>La fórmula</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#algunes-consideracions"><i class="fa fa-check"></i>Algunes consideracions</a></li>
<li class="chapter" data-level="" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i>Amb R</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#càlcul-de-la-mida-de-la-mostra-per-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chap-IC.html"><a href="chap-IC.html#intervals-de-confiança-per-a-proporcions"><i class="fa fa-check"></i><b>4.4</b> Intervals de confiança per a proporcions</a>
<ul>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#mètode-exacte-de-clopper-pearson"><i class="fa fa-check"></i>Mètode “exacte” de Clopper-Pearson</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#mètode-de-wilson"><i class="fa fa-check"></i>Mètode de Wilson</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#mètode-de-laplace"><i class="fa fa-check"></i>Mètode de Laplace</a></li>
<li><a href="chap-IC.html#quan-podem-calcular-més-dun-interval-per-a-p_x-quin-calculam">Quan podem calcular més d’un interval per a <span class="math inline">\(p_X\)</span>, quin calculam?</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#càlcul-de-la-mida-de-la-mostra-per-a-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per a fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chap-IC.html"><a href="chap-IC.html#intervals-de-confiança-per-a-la-variància-i-la-desviació-típica-duna-variable-normal"><i class="fa fa-check"></i><b>4.5</b> Intervals de confiança per a la variància i la desviació típica d’una variable normal</a></li>
<li class="chapter" data-level="4.6" data-path="chap-IC.html"><a href="chap-IC.html#poblacions-finites"><i class="fa fa-check"></i><b>4.6</b> “Poblacions finites”</a></li>
<li class="chapter" data-level="4.7" data-path="chap-IC.html"><a href="chap-IC.html#test-de-la-lliçó-4"><i class="fa fa-check"></i><b>4.7</b> Test de la lliçó 4</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-chgen.html"><a href="chap-chgen.html"><i class="fa fa-check"></i><b>5</b> Contrastos d’hipòtesis: Generalitats</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap-chgen.html"><a href="chap-chgen.html#les-hipòtesis-nulla-i-alternativa"><i class="fa fa-check"></i><b>5.1</b> Les hipòtesis nul·la i alternativa</a></li>
<li class="chapter" data-level="5.2" data-path="chap-chgen.html"><a href="chap-chgen.html#sec:moneda"><i class="fa fa-check"></i><b>5.2</b> Un exemple</a></li>
<li class="chapter" data-level="5.3" data-path="chap-chgen.html"><a href="chap-chgen.html#sec:pval"><i class="fa fa-check"></i><b>5.3</b> El p-valor</a></li>
<li class="chapter" data-level="5.4" data-path="chap-chgen.html"><a href="chap-chgen.html#tipus-derrors"><i class="fa fa-check"></i><b>5.4</b> Tipus d’errors</a></li>
<li class="chapter" data-level="5.5" data-path="chap-chgen.html"><a href="chap-chgen.html#sec:exttest"><i class="fa fa-check"></i><b>5.5</b> Exemple: El test t</a></li>
<li class="chapter" data-level="5.6" data-path="chap-chgen.html"><a href="chap-chgen.html#recapitulació"><i class="fa fa-check"></i><b>5.6</b> Recapitulació</a>
<ul>
<li class="chapter" data-level="" data-path="chap-chgen.html"><a href="chap-chgen.html#interval-de-confiança-dun-contrast"><i class="fa fa-check"></i>Interval de confiança d’un contrast</a></li>
<li class="chapter" data-level="" data-path="chap-chgen.html"><a href="chap-chgen.html#la-potència"><i class="fa fa-check"></i>La potència</a></li>
<li class="chapter" data-level="" data-path="chap-chgen.html"><a href="chap-chgen.html#el-risc-de-positiu-fals-opcional"><i class="fa fa-check"></i>El risc de positiu fals (Opcional)</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="chap-chgen.html"><a href="chap-chgen.html#test-de-la-lliçó-5"><i class="fa fa-check"></i><b>5.7</b> Test de la lliçó 5</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><i class="fa fa-check"></i><b>6</b> Contrastos d’hipòtesis d’un i dos paràmetres</a>
<ul>
<li class="chapter" data-level="6.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-de-mitjanes"><i class="fa fa-check"></i><b>6.1</b> Contrastos de mitjanes</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-una-mitjana"><i class="fa fa-check"></i><b>6.1.1</b> Test t per a una mitjana</a></li>
<li class="chapter" data-level="6.1.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-dues-mitjanes"><i class="fa fa-check"></i><b>6.1.2</b> Test t per a dues mitjanes</a></li>
<li class="chapter" data-level="6.1.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-t-amb-r"><i class="fa fa-check"></i><b>6.1.3</b> Tests t amb R</a></li>
<li class="chapter" data-level="6.1.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exemples"><i class="fa fa-check"></i><b>6.1.4</b> Exemples</a></li>
<li class="chapter" data-level="6.1.5" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics"><i class="fa fa-check"></i><b>6.1.5</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#sec:contrvar"><i class="fa fa-check"></i><b>6.2</b> Contrastos de variàncies</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-chi2-duna-variància"><i class="fa fa-check"></i><b>6.2.1</b> Test <span class="math inline">\(\chi^2\)</span> d’una variància</a></li>
<li class="chapter" data-level="6.2.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-f-per-a-dues-variàncies"><i class="fa fa-check"></i><b>6.2.2</b> Test F per a dues variàncies</a></li>
<li class="chapter" data-level="6.2.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics-1"><i class="fa fa-check"></i><b>6.2.3</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-proporcions"><i class="fa fa-check"></i><b>6.3</b> Contrastos per a proporcions</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-una-proporció"><i class="fa fa-check"></i><b>6.3.1</b> Contrastos per a una proporció</a></li>
<li class="chapter" data-level="6.3.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-independents"><i class="fa fa-check"></i><b>6.3.2</b> Contrastos per a 2 proporcions emprant mostres independents</a></li>
<li class="chapter" data-level="6.3.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-aparellades"><i class="fa fa-check"></i><b>6.3.3</b> Contrastos per a 2 proporcions emprant mostres aparellades</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-de-la-lliçó-6"><i class="fa fa-check"></i><b>6.4</b> Test de la lliçó 6</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-bondat.html"><a href="chap-bondat.html"><i class="fa fa-check"></i><b>7</b> Contrastos de bondat d’ajust</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chap-bondat.html"><a href="chap-bondat.html#bondat-dajust"><i class="fa fa-check"></i><b>7.1</b> Bondat d’ajust</a></li>
<li class="chapter" data-level="7.2" data-path="chap-bondat.html"><a href="chap-bondat.html#test-chi2-de-pearson"><i class="fa fa-check"></i><b>7.2</b> Test <span class="math inline">\(\chi^2\)</span> de Pearson</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="chap-bondat.html"><a href="chap-bondat.html#el-test-bàsic"><i class="fa fa-check"></i><b>7.2.1</b> El test bàsic</a></li>
<li class="chapter" data-level="7.2.2" data-path="chap-bondat.html"><a href="chap-bondat.html#mètode-de-montecarlo"><i class="fa fa-check"></i><b>7.2.2</b> Mètode de Montecarlo</a></li>
<li class="chapter" data-level="7.2.3" data-path="chap-bondat.html"><a href="chap-bondat.html#test-chi2-amb-paràmetres-poblacionals-desconeguts"><i class="fa fa-check"></i><b>7.2.3</b> Test <span class="math inline">\(\chi^2\)</span> amb paràmetres poblacionals desconeguts</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="chap-bondat.html"><a href="chap-bondat.html#test-de-kolmogorov-smirnov"><i class="fa fa-check"></i><b>7.3</b> Test de Kolmogorov-Smirnov</a></li>
<li class="chapter" data-level="7.4" data-path="chap-bondat.html"><a href="chap-bondat.html#test-de-kolmogorov-smirnov-lilliefors"><i class="fa fa-check"></i><b>7.4</b> Test de Kolmogorov-Smirnov-Lilliefors</a></li>
<li class="chapter" data-level="7.5" data-path="chap-bondat.html"><a href="chap-bondat.html#test-de-la-lliçó-7"><i class="fa fa-check"></i><b>7.5</b> Test de la lliçó 7</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html"><i class="fa fa-check"></i><b>8</b> Contrastos d’independència i homogeneïtat</a>
<ul>
<li class="chapter" data-level="8.1" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dindependència"><i class="fa fa-check"></i><b>8.1</b> Test <span class="math inline">\(\chi^2\)</span> d’independència</a></li>
<li class="chapter" data-level="8.2" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dhomogeneïtat"><i class="fa fa-check"></i><b>8.2</b> Test <span class="math inline">\(\chi^2\)</span> d’homogeneïtat</a></li>
<li class="chapter" data-level="8.3" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-de-tendència-opcional"><i class="fa fa-check"></i><b>8.3</b> Test <span class="math inline">\(\chi^2\)</span> de tendència (Opcional)</a></li>
<li class="chapter" data-level="8.4" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-de-la-lliçó-8"><i class="fa fa-check"></i><b>8.4</b> Test de la lliçó 8</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-ED.html"><a href="chap-ED.html"><i class="fa fa-check"></i><b>9</b> Introducció a l’estadística multidimensional</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chap-ED.html"><a href="chap-ED.html#poblacions-vectors-aleatoris"><i class="fa fa-check"></i><b>9.1</b> Poblacions: vectors aleatoris</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="chap-ED.html"><a href="chap-ED.html#covariància"><i class="fa fa-check"></i><b>9.1.1</b> Covariància</a></li>
<li class="chapter" data-level="9.1.2" data-path="chap-ED.html"><a href="chap-ED.html#correlació"><i class="fa fa-check"></i><b>9.1.2</b> Correlació</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="chap-ED.html"><a href="chap-ED.html#estadística-descriptiva-mostres"><i class="fa fa-check"></i><b>9.2</b> Estadística descriptiva: Mostres</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="chap-ED.html"><a href="chap-ED.html#covariàncies"><i class="fa fa-check"></i><b>9.2.1</b> Covariàncies</a></li>
<li class="chapter" data-level="9.2.2" data-path="chap-ED.html"><a href="chap-ED.html#correlació-de-pearson"><i class="fa fa-check"></i><b>9.2.2</b> Correlació de Pearson</a></li>
<li class="chapter" data-level="9.2.3" data-path="chap-ED.html"><a href="chap-ED.html#estimació"><i class="fa fa-check"></i><b>9.2.3</b> Estimació</a></li>
<li class="chapter" data-level="9.2.4" data-path="chap-ED.html"><a href="chap-ED.html#correlació-de-spearman"><i class="fa fa-check"></i><b>9.2.4</b> Correlació de Spearman</a></li>
<li class="chapter" data-level="9.2.5" data-path="chap-ED.html"><a href="chap-ED.html#contrastos-de-correlació"><i class="fa fa-check"></i><b>9.2.5</b> Contrastos de correlació</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="chap-ED.html"><a href="chap-ED.html#test-de-la-lliçó-9"><i class="fa fa-check"></i><b>9.3</b> Test de la lliçó 9</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II v.2021</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:ED" class="section level1" number="9">
<h1><span class="header-section-number">Tema 9</span> Introducció a l’estadística multidimensional</h1>
<p>En general, les dades que es recullen en experiments són multidimensionals: mesuram diverses variables aleatòries sobre una mateixa mostra d’individus i organitzam aquesta informació en taules de dades on les fileres representen els individus observats i cada columna correspon a una variable diferent. És a dir, el que fem és avaluar un vector de variables aleatòries (en direm un <strong>vector aleatori</strong>) sobre els individus d’una població. En aquesta lliçó introduïm alguns conceptes nous sobre vectors de variables aleatòries i taules multidimensionals de dades quantitatives.</p>
<div id="poblacions-vectors-aleatoris" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Poblacions: vectors aleatoris</h2>
<p>Un <strong>vector aleatori de dimensió <span class="math inline">\(p\)</span></strong> és un vector format per <span class="math inline">\(p\)</span> variables aleatòries
<span class="math display">\[
\underline{X}=(X_1,X_2,\ldots,X_p).
\]</span>
Una <strong>realització</strong> de <span class="math inline">\(\underline{X}\)</span> és un vector <span class="math inline">\((x_1,\ldots,x_p)\)</span> format pels valors de <span class="math inline">\(X_1,\ldots,X_p\)</span> sobre un individu. Una <strong>mostra</strong> de <span class="math inline">\(\underline{X}\)</span> és un conjunt de realitzacions. Usualment, organitzam una mostra de <span class="math inline">\(\underline{X}\)</span> per mitjà d’una taula de dades amb les columnes definides per les variables <span class="math inline">\(X_1,\ldots,X_p\)</span> i on cada filera és una realització d’aquestes variables, és a dir, un vector format pels valors de <span class="math inline">\(X_1,\ldots,X_p\)</span> sobre un individu de la mostra.</p>

<div class="example">
<span id="exm:unnamed-chunk-569" class="example"><strong>Exemple 9.1  </strong></span>Si diem <span class="math inline">\(\textit{BMI}\)</span> a la variable aleatòria que dóna l’Índex de Massa Corporal (BMI) d’una persona, <span class="math inline">\(C\)</span> a la variable aleatòria que dóna el nivell de colesterol en mg/dl d’una persona i <span class="math inline">\(E\)</span> a la variable aleatòria que dóna l’edat d’una persona en anys, llavors
<span class="math display">\[
\underline{X}=(\textit{BMI},C,E)
\]</span>
és un <strong>vector aleatori</strong> de dimensió 3. Cada cop que prenem una persona i n’anotam el BMI, el nivell de colesterol i l’edat i organitzam aquestes mesures en aquest ordre en un vector, obtenim una <strong>realització</strong> d’aquest vector aleatori <span class="math inline">\(\underline{X}\)</span>. Llavors,una <strong>mostra</strong> de <span class="math inline">\(\underline{X}\)</span> serà un conjunt de vectors amb el BMI, el nivell de colesterol i l’edat d’un grup de persones de la població. Per exemple
</div>
<table>
<thead>
<tr>
<th style="text-align:right;">
BMI
</th>
<th style="text-align:right;">
C
</th>
<th style="text-align:right;">
E
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
18.3
</td>
<td style="text-align:right;">
170
</td>
<td style="text-align:right;">
49
</td>
</tr>
<tr>
<td style="text-align:right;">
24.4
</td>
<td style="text-align:right;">
202
</td>
<td style="text-align:right;">
39
</td>
</tr>
<tr>
<td style="text-align:right;">
24.6
</td>
<td style="text-align:right;">
215
</td>
<td style="text-align:right;">
50
</td>
</tr>
<tr>
<td style="text-align:right;">
24.4
</td>
<td style="text-align:right;">
218
</td>
<td style="text-align:right;">
44
</td>
</tr>
<tr>
<td style="text-align:right;">
22.2
</td>
<td style="text-align:right;">
210
</td>
<td style="text-align:right;">
40
</td>
</tr>
<tr>
<td style="text-align:right;">
19.5
</td>
<td style="text-align:right;">
210
</td>
<td style="text-align:right;">
36
</td>
</tr>
</tbody>
</table>
<p>Siguin <span class="math inline">\(\underline{X}=(X_1,X_2,\ldots,X_p)\)</span> un vector aleatori i <span class="math inline">\(\mu_i\)</span> i <span class="math inline">\(\sigma_i\)</span> la mitjana i la desviació típica, respectivament, de cada <span class="math inline">\(X_i\)</span>.</p>
<ul>
<li><p>El <strong>valor esperat</strong>, o <strong>vector de mitjanes</strong>, de <span class="math inline">\(\underline{X}\)</span> és el vector format pels valors esperats, o mitjanes, de les seves components:
<span class="math display">\[
E(\underline{X})=(\mu_1,\ldots,\mu_p).
\]</span>
Per abreviar, de vegades indicarem aquest vector simplement amb <span class="math inline">\(\boldsymbol\mu\)</span>.</p></li>
<li><p>El <strong>vector de variàncies</strong> de <span class="math inline">\(\underline{X}\)</span> és el vector format per les variàncies de les seves components:
<span class="math display">\[
\sigma^2(\underline{X})=(\sigma_1^2,\ldots,\sigma_p^2).
\]</span></p></li>
<li><p>El <strong>vector de desviacions típiques</strong> de <span class="math inline">\(\underline{X}\)</span> és el vector format per les desviacions típiques de les seves components:
<span class="math display">\[
\sigma(\underline{X})=(\sigma_1,\ldots,\sigma_p).
\]</span></p></li>
</ul>
<div id="covariància" class="section level3" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Covariància</h3>
<p>La <strong>covariància</strong> de dues variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> és una mesura del seu comportament conjunt.
Formalment, donades dues variables aleatòries <span class="math inline">\(X,Y\)</span> de mitjanes <span class="math inline">\(\mu_X\)</span> i <span class="math inline">\(\mu_Y\)</span>, respectivament, la seva <strong>covariància</strong> és
<span class="math display">\[
\sigma_{X,Y}=E((X-\mu_X)\cdot ( Y-\mu_Y)).
\]</span>
És fàcil comprovar que
<span class="math display">\[
\sigma_{X,Y}=E(X\cdot Y) -\mu_X\cdot \mu_Y.
\]</span></p>

<div class="rmdcorbes">
En efecte,
<span class="math display">\[
\begin{array}{rl}
\sigma_{X,Y} &amp; =E((X-\mu_X) ( Y-\mu_Y))=
E(XY-\mu_XY-\mu_YX+\mu_X\mu_Y)\\ &amp;
=E(XY)-\mu_XE(Y)-\mu_YE(X)+\mu_X\mu_Y\\ &amp;=
E(XY)-\mu_X\mu_Y-\mu_Y\mu_X+\mu_X\mu_Y
=E(XY)-\mu_X\mu_Y
\end{array}
\]</span>
</div>
<p>La covariància de <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> pot prendre qualsevol valor real (no com la variància, que sempre és positiva), i mesura el grau de variació conjunta de les variables en el sentit següent.</p>
<ul>
<li><p><span class="math inline">\(\sigma_{X,Y}&gt;0\)</span> significa que</p>
<ul>
<li><p>Quan <span class="math inline">\(X\)</span> és més gran en un individu 1 que en un individu 2, <span class="math inline">\(Y\)</span> tendeix a ser més gran en l’individu 1 que en l’individu 2</p></li>
<li><p>Quan <span class="math inline">\(X\)</span> és més petit en un individu 1 que en un individu 2, <span class="math inline">\(Y\)</span> tendeix a ser més petit en l’ individu 1 que en l’individu 2</p></li>
</ul></li>
<li><p><span class="math inline">\(\sigma_{X,Y}&lt;0\)</span> significa que</p>
<ul>
<li><p>Quan <span class="math inline">\(X\)</span> és més gran en un individu 1 que en un individu 2, <span class="math inline">\(Y\)</span> tendeix a ser més petit en l’individu 1 que en l’individu 2</p></li>
<li><p>Quan <span class="math inline">\(X\)</span> és més petit en un individu 1 que en un individu 2, <span class="math inline">\(Y\)</span> tendeix a ser més gran en l’individu 1 que en l’individu 2</p></li>
</ul></li>
<li><p><span class="math inline">\(\sigma_{X,Y}=0\)</span> significa que no hi ha cap tendència en aquest sentit</p></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-572"></span>
<img src="Bioestadistica-II_files/figure-html/unnamed-chunk-572-1.png" alt="Significat del signe de la covariància" width="90%" />
<p class="caption">
Figura 9.1: Significat del signe de la covariància
</p>
</div>

<div class="rmdimportant">
<p>El signe de la covariància reflecteix la “tendència del creixement conjunt” de les variables:</p>
<ul>
<li>Covariància positiva: Si <span class="math inline">\(X\)</span> creix, <span class="math inline">\(Y\)</span> tendeix a créixer, i si <span class="math inline">\(X\)</span> decreix, <span class="math inline">\(Y\)</span> tendeix a decréixer</li>
<li>Covariància negativa: Si <span class="math inline">\(X\)</span> creix, <span class="math inline">\(Y\)</span> tendeix a decréixer, i si <span class="math inline">\(X\)</span> decreix, <span class="math inline">\(Y\)</span> tendeix a créixer</li>
</ul>
</div>
<p><strong>Si <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són variables independents, la seva covariància es 0</strong>, perquè en aquest cas <span class="math inline">\(E(X\cdot Y) =\mu_X\mu_Y\)</span> i per tant
<span class="math display">\[
\sigma_{X,Y}=E(X\cdot Y) -\mu_X\cdot \mu_Y=\mu_X\cdot \mu_Y-\mu_X\cdot \mu_Y=0.
\]</span></p>

<div class="rmdcorbes">
<p>Ups, aquesta és nova! Per què, si <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són independents, <span class="math inline">\(E(X\cdot Y) =\mu_X\mu_Y\)</span>? Us ho demostrarem en el cas discret; l’argument en el cas continu és el mateix canviant sumatoris per integrals.
<span class="math display">\[
\begin{array}{rl}
E(X\cdot Y)\!\!\! &amp;\displaystyle =\sum_{x\in D_X,y\in D_Y} xyP(X=x,Y=y)\\
&amp;\displaystyle =\sum_{x\in D_X,y\in D_Y} xyP(X=x)P(Y=y)\\
&amp;\text{(per la independència de $X$ i $Y$)}\\
&amp;\displaystyle =\Big(\sum_{x\in D_X}xP(X=x)\Big)\Big(\sum_{y\in D_Y} yP(Y=y)\Big)=E(X)E(Y)
\end{array}
\]</span></p>
<p>És important remarcar que la igualtat <span class="math inline">\(E(X\cdot Y) =\mu_X\mu_Y\)</span> és equivalent a la igualtat
<span class="math inline">\(\sigma(X+Y)^2 =\sigma(X)^2+\sigma(Y)^2\)</span> que dèiem al Tema <a href="chap-varal.html#chap:varal">2</a> que satisfan les variables independents. En efecte
<span class="math display">\[
\begin{array}{l}
\sigma(X+Y)^2 -(\sigma(X)^2+\sigma(Y)^2)\\
\quad = E((X+Y)^2)-E(X+Y)^2-(E(X^2)-E(X)^2+E(Y^2)-E(Y)^2)\\
\quad = E(X^2+2XY+Y^2)-(E(X)+E(Y))^2\\
\qquad\qquad -E(X^2)+E(X)^2-E(Y^2)+E(Y)^2\\
\quad = E(X^2)+2E(XY)+E(Y^2)-E(X)^2-2E(X)E(Y)-E(Y)^2\\
\qquad\qquad -E(X^2)+E(X)^2-E(Y^2)+E(Y)^2\\
\quad = 2E(XY)-2E(X)E(Y)=2(E(XY)-\mu_X\mu_Y)
\end{array}
\]</span>
i per tant
<span class="math display">\[
\sigma(X+Y)^2 -(\sigma(X)^2+\sigma(Y)^2)=0 \Longleftrightarrow E(XY)-\mu_X\mu_Y=0
\]</span></p>
</div>

<div class="rmdimportant">
<strong>Si <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són variables independents, la seva covariància es 0</strong>, però la implicació a l’inrevés és falsa: <strong>Dues variables aleatòries poden tenir covariància 0 i no ser independents</strong>.
</div>
<p>Vegem un exemple d’aquest darrer fet:</p>

<div class="example">
<p><span id="exm:nocorr" class="example"><strong>Exemple 9.2  </strong></span>Suposem que tenim un dau tetraèdric no trucat amb les cares marcades amb els valors -2, -1, 1 i 2. Siguin <span class="math inline">\(X\)</span> la variable aleatòria que consisteix a llançar el dau i anotar el resultat, i <span class="math inline">\(Y\)</span> la variable aleatòria que consisteix a llançar el dau i anotar el <em>quadrat</em> del resultat obtingut. Com que les quatre cares del dau són equiprobables,
<span class="math display">\[
\begin{array}{l}
\displaystyle P(X=-2)=P(X=-1)=P(X=1)=P(X=2)=\frac{1}{4}\\
\displaystyle P(Y=1)=P(Y=4)=\frac{1}{2}
\end{array}
\]</span></p>
</div>
<p>Com que <span class="math inline">\(Y\)</span> és funció de <span class="math inline">\(X\)</span>, ja que <span class="math inline">\(Y=X^2\)</span>, <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> no poden ser mai independents. Vegem que, en efecte, no ho són. Observau que els únics possibles valors per al vector <span class="math inline">\((X,Y)\)</span> en una tirada del dau són (-2,4), (-1,1), (1,1) i (2,4), cadascun amb probabilitat 1/4. Llavors, per exemple, la probabilitat d’obtenir en una tirada <span class="math inline">\(X=-1\)</span> i <span class="math inline">\(Y=4\)</span> és 0, perquè és impossible, mentre que
<span class="math display">\[
P(X=-1)\cdot P(Y=4)=\frac{1}{4}\cdot\frac{1}{2}=\frac{1}{8}\neq 0.
\]</span></p>
<p>Vegem ara que la covariància de <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> es 0. Per calcular-la, primer necessitam calcular els valors esperats de les variables:
<span class="math display">\[
\begin{array}{l}
\displaystyle \mu_X=(-2)\cdot \frac{1}{4}+(-1)\cdot \frac{1}{4}+1\cdot \frac{1}{4}+2\cdot \frac{1}{4}=0\\
\displaystyle \mu_Y=1\cdot \frac{1}{2}+4\cdot \frac{1}{2}=2.5
\end{array}
\]</span>
Per tant
<span class="math display">\[
\begin{array}{l}
\sigma_{X,Y}=E\big(X\cdot Y\big)-\mu_X\cdot \mu_Y=E\big(X\cdot Y\big)-0\cdot 2.5=E\big(X\cdot Y\big)\\
\qquad =P\big(X=-2,Y=4\big)\cdot (-2\cdot 4)+P\big(X=-1,Y=1\big)\cdot (-1\cdot 1)\\
\qquad\qquad\qquad +P\big(X=1,Y=1\big)\cdot (1\cdot 1)+P\big(X=2,Y=4\big)\cdot (2\cdot 4)\\
\qquad =\displaystyle \frac{1}{4}\cdot (-8)+\frac{1}{4}\cdot (-1)+\frac{1}{4}\cdot 1+\frac{1}{4}\cdot 8=0.
\end{array}
\]</span>
Així doncs, <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són variables dependents, però la seva covariància és 0.</p>
<p>Dues propietats importants més de la covariància:</p>
<ul>
<li><p>La covariància és simètrica:
<span class="math display">\[
\begin{array}{rl}
\sigma_{X,Y}\!\!\! &amp; =E((X-\mu_X)\cdot ( Y-\mu_Y))\\
&amp; =E(( Y-\mu_Y)\cdot (X-\mu_X))=\sigma_{Y,X}
\end{array}
\]</span></p></li>
<li><p>La covariància d’una variable aleatòria amb ella mateixa és la seva variància:
<span class="math display">\[
\sigma_{X,X}=E((X-\mu_X)^2)=\sigma^2(X)
\]</span></p></li>
</ul>
<p>La <em>matriu de covariàncies</em> d’un vector aleatori <span class="math inline">\(\underline{X}=(X_1,\ldots,X_p)\)</span> és la matriu formada per les covariàncies dels parells de variables que la formen:
<span class="math display">\[
\sigma_{\underline{X},\underline{X}}=\begin{pmatrix} \sigma_{X_1,X_1} &amp; \sigma_{X_1,X_2} &amp; \ldots &amp; \sigma_{X_1,X_p}\\
\sigma_{X_2,X_1} &amp; \sigma_{X_2,X_2} &amp; \ldots &amp; \sigma_{X_2,X_p}\\
\vdots &amp; \vdots &amp;\ddots  &amp; \vdots\\
\sigma_{X_p,X_1} &amp; \sigma_{X_p,X_2} &amp; \ldots &amp; \sigma_{X_p,X_p}\\
 \end{pmatrix}
\]</span></p>
<p>Aquesta matriu és simètrica i les entrades de la diagonal són les variàncies de les variables del vector, perquè <span class="math inline">\(\sigma_{X_i,X_i}=\sigma^2_{X_i}\)</span>.</p>
</div>
<div id="correlació" class="section level3" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Correlació</h3>
<p>Com hem dit, el signe de la covariància té una interpretació senzilla, ja que reflecteix la tendència del creixement conjunt de les variables.
Emperò, la seva magnitud no té una interpretació senzilla. Aleshores, per mesurar la tendència que hi hagi una <strong>relació lineal</strong> entre dues variables aleatòries contínues s’usa l’anomenat <strong>coeficient de correlació lineal de Pearson</strong> (o <strong>correlació</strong> a seques), que ve a ser una versió normalitzada de la covariància. En concret, la <strong>correlació</strong> de les variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> es defineix com el quocient de la seva covariància pel producte de les seves desviacions típiques:
<span class="math display">\[
\rho_{X,Y}=\frac{\sigma_{X,Y}}{\sigma_{X} \sigma_{Y}}
\]</span></p>
<p>La correlació té les propietats importants següents:</p>
<ol style="list-style-type: decimal">
<li><p>No té unitats (perquè les unitats de <span class="math inline">\(\sigma_X\)</span> són les de <span class="math inline">\(X\)</span>, les unitats de <span class="math inline">\(\sigma_Y\)</span> són les de <span class="math inline">\(Y\)</span>, i les unitats de <span class="math inline">\(\sigma_{X,Y}\)</span> són les de <span class="math inline">\(X\)</span> per les de <span class="math inline">\(Y\)</span>)</p></li>
<li><p>Pren valors entre -1 i 1: <span class="math inline">\(-1\leqslant \rho_{X,Y}\leqslant 1\)</span></p></li>
<li><p>És simètrica, <span class="math inline">\(\rho_{X,Y}= \rho_{Y,X}\)</span></p></li>
<li><p>La correlació d’una variable amb ella mateixa és 1: <span class="math inline">\(\rho_{X,X}=1\)</span></p></li>
<li><p><span class="math inline">\(\rho_{X,Y}=\pm 1\)</span> si, i només si, les variables <span class="math inline">\(X,Y\)</span> tenen una <strong>relació lineal perfecta</strong>. És a dir, <span class="math inline">\(\rho_{X,Y}=\pm 1\)</span> si, i només si, existeixen <span class="math inline">\(a,b\in \mathbb{R}\)</span> tals que <span class="math inline">\(Y=a X+b\)</span>. La pendent <span class="math inline">\(a\)</span> d’aquesta recta té el mateix signe que <span class="math inline">\(\rho_{X,Y}\)</span>.</p></li>
<li><p>Com més s’acosta <span class="math inline">\(|\rho_{X,Y}|\)</span> a 1, més s’acosta <span class="math inline">\(Y\)</span> a ser funció lineal de <span class="math inline">\(X\)</span></p>
<ul>
<li>Si <span class="math inline">\(\rho_{X,Y}&gt;0\)</span>, la funció és creixent</li>
<li>Si <span class="math inline">\(\rho_{X,Y}&lt;0\)</span>, la funció és decreixent</li>
</ul></li>
<li><p>Si <span class="math inline">\(\rho_{X,Y}=0\)</span>, diem que les variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són <strong>incorrelades</strong>. Notem que la correlació és 0 si, i només si, la covariància és 0. Per tant, <strong>si <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són independents, també són incorrelades. El recíproc en general és fals</strong>, com mostra l’Exemple <a href="chap-ED.html#exm:nocorr">9.2</a>.</p></li>
</ol>
<p>La <em>matriu de correlacions</em> d’un vector aleatori <span class="math inline">\(\underline{X}=(X_1,\ldots,X_p)\)</span> és la matriu formada per les correlacions de parells de les seves variables:
<span class="math display">\[
\rho(\underline{X})
=\begin{pmatrix} 1 &amp; \rho_{X_1,X_2} &amp; \ldots &amp; \rho_{X_1,X_p}\\
\rho_{X_2,X_1} &amp; 1 &amp; \ldots &amp; \rho_{X_2,X_p}\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
\rho_{X_p,X_1} &amp; \rho_{X_p,X_2} &amp; \ldots &amp; 1\\
 \end{pmatrix}.
\]</span>
Aquesta matriu és simètrica per la simetria de la correlació.</p>

<div class="rmdimportant">
<p>La correlació de Pearson de dues variables mesura la tendència de dues variables a variar conjuntament de manera lineal. Per tant, per exemple, si <span class="math inline">\(\rho_{X,Y}&gt;0\)</span>, implica que <span class="math inline">\(Y\)</span> tendeix a créixer si <span class="math inline">\(X\)</span>. Però no significa que un augment del valor de <span class="math inline">\(X\)</span> <strong>causi</strong> un augment del valor de <span class="math inline">\(Y\)</span>: <strong>Correlació no implica causalitat!</strong>. La tendencia al criexement simultani de <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> es pot deure a una tercera variable que les faci créixer totes dues, o pot ser purament espúria.</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-577"></span>
<img src="http://imgs.xkcd.com/comics/correlation.png" alt="Correlació no implica causalitat (https://xkcd.com/552/ (CC-BY-NC 2.5))" width="80%" />
<p class="caption">
Figura 9.2: Correlació no implica causalitat (<a href="https://xkcd.com/552/" class="uri">https://xkcd.com/552/</a> (CC-BY-NC 2.5))
</p>
</div>
<p>O millor:</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-578"></span>
<img src="Bioestadistica-II_files/figure-html/Dilbertcorr.png" alt="Correlació no implica causalitat, segons Dilbert" width="80%" />
<p class="caption">
Figura 9.3: Correlació no implica causalitat, segons Dilbert
</p>
</div>

<div class="rmdnote">
Si entrau a la pàgina web <a href="https://tylervigen.com/spurious-correlations">Spurious Correlations</a> podreu explorar un munt de correlacions espúries molt grans. La nostra preferida és una correlació de 0.947 entre la variable <span class="math inline">\(X\)</span> “Prenc un any i anot el consum <em>per capita</em> de formatge als EEUU” i <span class="math inline">\(Y\)</span> “Prenc un any i anot el nombre de morts per estrangulament accidental amb els llençols del llit als EEUU”.
</div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-580"></span>
<img src="Bioestadistica-II_files/figure-html/spurcorr1.png" alt="Correlació no implica causalitat, segons &quot;Spurious Correlations&quot;" width="80%" />
<p class="caption">
Figura 9.4: Correlació no implica causalitat, segons “Spurious Correlations”
</p>
</div>
<p>Vegem un exemple de correlació negativa que és important tenir present per no deixar-se enganar.</p>

<div class="theorem">
<span id="thm:unnamed-chunk-581" class="theorem"><strong>Teorema 9.1  </strong></span>Si <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span> són dues còpies independents d’una mateixa variable aleatòria <span class="math inline">\(X\)</span>,
<span class="math display">\[
\rho_{X_1,X_2-X_1}=-\frac{1}{\sqrt{2}}\approx 0.7
\]</span>
</div>
<p>Això ens diu que, sigui quina sigui la variable <span class="math inline">\(X\)</span>, si la mesuram en dos moments diferents o sobre dos individus diferents, la diferència entre els dos valors <strong>té una tendència destacada a decréixer linealment</strong> en el primer valor. Per exemple:</p>
<ul>
<li><p>Feu un test i traieu una nota molt baixa (<span class="math inline">\(X_1\)</span>). L’endemà feu un altre test similar (<span class="math inline">\(X_2\)</span>) sense haver estudiat més. El més probable és que, per pur atzar, tengueu una nota més alta (que <span class="math inline">\(X_2-X_1\)</span> sigui gran, per tant positiu).</p></li>
<li><p>Feu un test i traieu una nota molt alta (<span class="math inline">\(X_1\)</span>). L’endemà feu un altre test (<span class="math inline">\(X_2\)</span>) sense haver estudiat més. El més probable és que, per pur atzar, tengueu una nota més baixa (que <span class="math inline">\(X_2-X_1\)</span> sigui petit, per tant negatiu).</p></li>
</ul>

<div class="rmdcorbes">
<p>Per si qualcú necessita una demostració del teorema anterior, recordem que
<span class="math display">\[
\rho_{X_1,X_2-X_1}=\dfrac{\sigma_{X_1,X_2-X_1}}{\sigma_{X_1}\sigma_{X_2-X_1}}
\]</span>
Ara
<span class="math display">\[
\begin{array}{l}
\sigma_{X_2-X_1}=\sqrt{\sigma^2_{X_2-X_1}}\\[2ex]
\quad =\sqrt{\sigma^2_{X_1}+\sigma^2_{X_2}}\ \text{(perquè són independents)}\\[2ex]
\quad =\sqrt{\sigma^2_{X}+\sigma^2_{X}}\ \text{(perquè $X_1,X_2$ són còpies de $X$)}\\[2ex]
\quad =\sqrt{2\sigma^2_{X}}=\sigma_{X}\sqrt{2}
\end{array}
\]</span>
I
<span class="math display">\[
\begin{array}{l}
\sigma_{X_1,X_2-X_1}=E(X_1(X_2-X_1))-E(X_1)E(X_2-X_1)\\[1ex]
\quad =E(X_1X_2-X_1^2)-E(X_1)(E(X_2-E(X_1))\\[1ex]
\quad =E(X_1X_2)-E(X_1^2)-E(X_1)E(X_2)+E(X_1)E(X_1)\\[1ex]
\quad =E(X_1)E(X_2)-E(X_1^2)-E(X_1)E(X_2)+E(X_1)E(X_1)\\[1ex]
\quad \text{(perquè  $X_1,X_2$ són independents)}\\[1ex]
\quad =-E(X_1^2)+E(X_1)E(X_1)=-\sigma^2_{X_1}=-\sigma^2_{X}
\end{array}
\]</span>
Combinant-ho:
<span class="math display">\[
\rho_{X_1,X_2-X_1}=\dfrac{\sigma_{X_1,X_2-X_1}}{\sigma_{X_1}\sigma_{X_2-X_1}}=\dfrac{-\sigma^2_{X}}{\sigma_{X}\cdot \sigma_{X}\sqrt{2}} =-\frac{1}{\sqrt{2}}
\]</span></p>
</div>
</div>
</div>
<div id="estadística-descriptiva-mostres" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> Estadística descriptiva: Mostres</h2>
<div id="covariàncies" class="section level3" number="9.2.1">
<h3><span class="header-section-number">9.2.1</span> Covariàncies</h3>
<p>Siguin <span class="math inline">\(x=(x_1,\ldots,x_n)\)</span> i <span class="math inline">\(y=(y_1,\ldots,y_n)\)</span> dos vectors obtinguts mesurant dues variables aleatòries <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> sobre una mateixa mostra ordenada d’individus de mida <span class="math inline">\(n\)</span> d’una població. Siguin <span class="math inline">\(\overline{X}\)</span> i <span class="math inline">\(\overline{Y}\)</span> les seves mitjanes mostrals. Aleshores la seva <strong>covariància mostral</strong> és
<span class="math display">\[
\widetilde{S}_{X,Y} =\frac{1}{n-1} \sum_{i =1}^n\big((x_{i}-\overline{{X}})(y_i-\overline{Y})\big)
\]</span>
i la seva <strong>covariància</strong> (<strong>a seques</strong>) és
<span class="math display">\[
{S}_{X,Y} =\frac{1}{n} \sum_{i =1}^n\big((x_{i}-\overline{{X}})(y_i-\overline{Y})\big)=\frac{n-1}{n}\widetilde{S}_{X,Y}.
\]</span>
És a dir, com sempre, la diferència entre la versió “mostral” i la versió “a seques” rau en el denominador, <span class="math inline">\(n-1\)</span> i <span class="math inline">\(n\)</span> respectivament.</p>

<div class="rmdimportant">
La covariància de dos vectors només té sentit quan aquests vectors representen els valors de dues variables quantitatives sobre els mateixos individus i en el mateix ordre. En particular, els dos vectors han de tenir la mateixa longitud.
</div>
<p>Com en el cas poblacional, la <strong>covariància</strong> entre dos vectors mesura la tendència que tenen les seves dades a variar conjuntament:</p>
<ul>
<li><p>Quan <span class="math inline">\(\widetilde{S}_{X,Y}&gt;0\)</span>, si <span class="math inline">\(x_i&gt;x_j\)</span>, <span class="math inline">\(y_i\)</span> tendeix a ser més gran que <span class="math inline">\(y_j\)</span></p></li>
<li><p>Quan <span class="math inline">\(\widetilde{S}_{X,Y}&gt;0\)</span>, si <span class="math inline">\(x_i&gt;x_j\)</span>, <span class="math inline">\(y_i\)</span> tendeix a ser més petit que <span class="math inline">\(y_j\)</span></p></li>
<li><p>Quan <span class="math inline">\(\widetilde{S}=0\)</span>, no hi ha cap tendència en aquest sentit</p></li>
</ul>
<p>És fàcil comprovar que:</p>
<ul>
<li>Les dues covariàncies són simètriques
<span class="math display">\[
\widetilde{S}_{X,Y}=\widetilde{S}_{y,x},\ {S}_{X,Y}={S}_{Y,X}
\]</span></li>
<li>La variància d’un vector és la seva covariància amb ell mateix
<span class="math display">\[
\widetilde{S}_{X,X}=\widetilde{S}^2_{x},\ {S}_{X,X}={S}^2_{X}.
\]</span></li>
</ul>

<div class="example">
<p><span id="exm:multex1" class="example"><strong>Exemple 9.3  </strong></span>Hem mesurat l’índex de massa corporal, BMI, i el nivell de colesterol en 5 individus sans. Guardam els resultats en un <em>data frame</em> i en calculam les mitjanes:</p>
</div>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="chap-ED.html#cb435-1" aria-hidden="true" tabindex="-1"></a>BMI<span class="ot">=</span> <span class="fu">c</span>(<span class="fl">18.3</span>,<span class="fl">24.4</span>,<span class="fl">24.6</span>,<span class="fl">24.4</span>,<span class="fl">22.2</span>,<span class="fl">19.5</span>)</span>
<span id="cb435-2"><a href="chap-ED.html#cb435-2" aria-hidden="true" tabindex="-1"></a>Chol<span class="ot">=</span><span class="fu">c</span>(<span class="dv">170</span>,<span class="dv">202</span>,<span class="dv">215</span>,<span class="dv">218</span>,<span class="dv">210</span>,<span class="dv">210</span>)</span>
<span id="cb435-3"><a href="chap-ED.html#cb435-3" aria-hidden="true" tabindex="-1"></a>DF<span class="ot">=</span><span class="fu">data.frame</span>(BMI,Chol)</span>
<span id="cb435-4"><a href="chap-ED.html#cb435-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(BMI)</span></code></pre></div>
<pre><code>## [1] 22.23333</code></pre>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="chap-ED.html#cb437-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Chol)</span></code></pre></div>
<pre><code>## [1] 204.1667</code></pre>
<p>Aleshores la covariància mostral d’aquests dos vectors és
<span class="math display">\[
\begin{array}{l}
\dfrac{1}{5}\Big((18.3-22.23)(170-204.17)+(24.4-22.23)(202-204.17)\\
\qquad +(24.6-22.23)(215-204.17)+(24.4-22.23)(218-204.17)\\
\qquad +(22.2-22.23)(210-204.17)+(19.5-22.23)(210-204.17)\Big)=33.8333
\end{array}
\]</span></p>
<p>i la seva covariància a seques és
<span class="math display">\[
\begin{array}{l}
\dfrac{1}{6}\Big((18.3-22.23)(170-204.17)+(24.4-22.23)(202-204.17)\\
\qquad +(24.6-22.23)(215-204.17) +(24.4-22.23)(218-204.17)\\
\qquad +(22.2-22.23)(210-204.17)+(19.5-22.23)(210-204.17)\Big)=27.0667
\end{array}
\]</span></p>
<p>La covariància <strong>mostral</strong> de dos vectors numèrics de la mateixa longitud <span class="math inline">\(n\)</span> es calcula amb R amb la funció <code>cov</code>. Per obtenir la seva covariància <em>a seques</em>, cal multiplicar el resultat de <code>cov</code> per <span class="math inline">\((n-1)/n\)</span>.</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="chap-ED.html#cb439-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(BMI,Chol)</span></code></pre></div>
<pre><code>## [1] 33.83333</code></pre>
<p>Considerem una taula de dades de la forma
<span class="math display">\[
\begin{array}{cccc}
X_1 &amp; X_2 &amp; \ldots &amp; X_p\\ \hline
x_{1 1} &amp; x_{1 2} &amp;\ldots &amp; x_{1 p}\\
x_{2 1} &amp; x_{2 2} &amp;\ldots &amp; x_{2 p}\\
\vdots &amp; \vdots   &amp;   \ddots    &amp;\vdots\\ 
x_{n 1} &amp; x_{n 2} &amp;\ldots &amp; x_{n p}
\end{array}
\]</span>
on cada columna representa els valors d’una certa variable <span class="math inline">\(X_i\)</span> i cada filera un individu d’una mostra de la població, de manera que l’entrada <span class="math inline">\(x_{ij}\)</span> d’aquesta taula és el valor de <span class="math inline">\(X_j\)</span> sobre l’individu <span class="math inline">\(i\)</span>-èssim de la mostra.</p>
<p>La <strong>matriu de covariàncies mostrals</strong> d’aquesta taula és la matriu
<span class="math display">\[
\widetilde{{S}}=
\begin{pmatrix}  
 \widetilde{S}^2_{X_1} &amp; \widetilde{S}_{X_1,X_2} &amp; \ldots &amp; \widetilde{S}_{X_1,X_p}\\
 \widetilde{S}_{X_2,X_1} &amp;  \widetilde{S}^2_{X_2} &amp; \ldots &amp; \widetilde{S}_{X_2,X_p}\\
  \vdots &amp; \vdots  &amp;  \ddots      &amp; \vdots\\
\widetilde{S}_{X_p,X_1} &amp; \widetilde{S}_{X_p,X_2} &amp; \ldots &amp;  \widetilde{S}^2_{X_p}
\end{pmatrix}
\]</span>
i la <strong>matriu de covariàncies</strong> (<strong>a seques</strong>) es defineix de manera similar, però amb les covariàncies a seques:
<span class="math display">\[
{S}=
\begin{pmatrix}  
 s^2_{X_1} &amp; s_{X_1,X_2} &amp; \ldots &amp; s_{X_1,X_p}\\
 s_{X_2,X_1} &amp; s^2_{X_2} &amp; \ldots &amp; s_{X_2,X_p}\\
  \vdots &amp; \vdots  &amp;  \ddots      &amp; \vdots\\
s_{X_p,X_1} &amp; s_{X_p,X_2} &amp; \ldots &amp; s^2_{X_p}
\end{pmatrix}
\]</span>
Totes dues són simètriques.</p>
<p>La matriu de covariàncies mostrals es calcula amb la funció <code>cov</code> aplicada a la matriu o el <em>data frame</em> de variables numèriques que emmagatzema la taula de dades. Per calcular la matriu de covariàncies a seques, es multiplica el resultat de <code>cov</code> per <span class="math inline">\((n-1)/n\)</span>, on <span class="math inline">\(n\)</span> és el nombre de fileres de la taula.</p>

<div class="example">
<p><span id="exm:multex2" class="example"><strong>Exemple 9.4  </strong></span>Afegirem a la taula de dades de l’Exemple <a href="chap-ED.html#exm:multex1">9.3</a> una tercera variable amb les edats dels 6 individus representats en ella.</p>
</div>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="chap-ED.html#cb441-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>Edats<span class="ot">=</span><span class="fu">c</span>(<span class="dv">49</span>,<span class="dv">39</span>,<span class="dv">50</span>,<span class="dv">44</span>,<span class="dv">40</span>,<span class="dv">36</span>)</span>
<span id="cb441-2"><a href="chap-ED.html#cb441-2" aria-hidden="true" tabindex="-1"></a>DF</span></code></pre></div>
<pre><code>##    BMI Chol Edats
## 1 18.3  170    49
## 2 24.4  202    39
## 3 24.6  215    50
## 4 24.4  218    44
## 5 22.2  210    40
## 6 19.5  210    36</code></pre>
<p>La matriu de covariàncies mostrals d’aquesta taula és</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="chap-ED.html#cb443-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(DF)</span></code></pre></div>
<pre><code>##             BMI      Chol  Edats
## BMI    7.586667  33.83333   1.14
## Chol  33.833333 309.76667 -33.00
## Edats  1.140000 -33.00000  32.00</code></pre>
<p>Podreu observar que és simètrica, que a la diagonal hi obtenim les variàncies mostrals de les variables de la taula:</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="chap-ED.html#cb445-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(DF,<span class="at">MARGIN=</span><span class="dv">2</span>,<span class="at">FUN=</span>var)</span></code></pre></div>
<pre><code>##        BMI       Chol      Edats 
##   7.586667 309.766667  32.000000</code></pre>
<p>i que l’entrada (2,1) coincideix amb la covariància de <code>BMI</code> i <code>Chol</code> que hem calculat abans.</p>
</div>
<div id="correlació-de-pearson" class="section level3" number="9.2.2">
<h3><span class="header-section-number">9.2.2</span> Correlació de Pearson</h3>
<p>Siguin <span class="math inline">\(x=(x_1,\ldots,x_n)\)</span> i <span class="math inline">\(y=(y_1,\ldots,y_n)\)</span> dos vectors obtinguts mesurant dues variables aleatòries <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> sobre una mateixa mostra d’individus de mida <span class="math inline">\(n\)</span> d’una població.</p>
<p>La <strong>correlació de Pearson</strong> de <span class="math inline">\(x\)</span> i <span class="math inline">\(y\)</span> és la seva covariància mostral dividida pel producte de les seves desviacions típiques mostrals:
<span class="math display">\[
R_{X,Y}=\frac{\widetilde{S}_{X,Y}}{\widetilde{S}_X\cdot \widetilde{S}_Y}.
\]</span></p>
<p>La <strong>correlació de Pearson</strong> de <span class="math inline">\(x\)</span> i <span class="math inline">\(y\)</span> també és igual a la seva covariància a seques dividida pel producte de les seves desviacions típiques a seques, perquè els canvis de denominador se cancel·len:
<span class="math display">\[
R_{X,Y}=\frac{\widetilde{S}_{X,Y}}{\widetilde{S}_X\cdot \widetilde{S}_Y}=
\frac{\frac{n}{n-1}\cdot {S}_{X,Y}}{\sqrt{\frac{n}{n-1}}\cdot {S}_X \cdot\sqrt{\frac{n}{n-1}}\cdot{S}_Y}=
\frac{s_{x,y}}{S_X \cdot S_Y}=R_{X,Y}.
\]</span></p>

<div class="example">
<p><span id="exm:multex1rev" class="example"><strong>Exemple 9.5  </strong></span>Tornem a la situació de l’Exemple <a href="chap-ED.html#exm:multex1">9.3</a>. La covariància mostral i les desviacions típiques mostrals dels vectors <code>BMI</code> i <code>Chol</code> són</p>
</div>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="chap-ED.html#cb447-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(BMI)</span></code></pre></div>
<pre><code>## [1] 2.75439</code></pre>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="chap-ED.html#cb449-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(Chol)</span></code></pre></div>
<pre><code>## [1] 17.60019</code></pre>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="chap-ED.html#cb451-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(BMI,Chol)</span></code></pre></div>
<pre><code>## [1] 33.83333</code></pre>
<p>i per tant la seva correlació de Pearson és
<span class="math display">\[
R_{BMI,Chol}=\frac{33.833}{2.754\cdot 17.6}= 0.698
\]</span></p>
<p>Algunes propietats importants de la correlació de Pearson:</p>
<ul>
<li><p>La correlació de Pearson és simètrica: <span class="math inline">\(R_{X,Y}=R_{y,x}\)</span></p></li>
<li><p>La correlació de Pearson pren valors només entre -1 i 1: <span class="math inline">\(-1\leqslant R_{X,Y}\leqslant 1\)</span></p></li>
<li><p>La correlació de Pearson d’un vector amb ell mateix és 1: <span class="math inline">\(R_{X,X}=1\)</span></p></li>
<li><p><span class="math inline">\(R_{X,Y}\)</span> té el mateix signe que <span class="math inline">\(S_{X,Y}\)</span></p></li>
<li><p><span class="math inline">\(R_{X,Y}=\pm 1\)</span> si, i només si, existeixen <span class="math inline">\(a, b\in \mathbb{R}\)</span> tals que <span class="math inline">\(y=ax+b\)</span>, és a dir, <span class="math inline">\(y_i=ax_i+b\)</span> per a cada <span class="math inline">\(i=1,\ldots,n\)</span>. La pendent <span class="math inline">\(a\)</span> d’aquesta relació lineal té el mateix signe que <span class="math inline">\(R_{X,Y}\)</span>.</p></li>
<li><p>El coeficient de determinació <span class="math inline">\(R^2\)</span> de la regressió lineal per mínims quadrats de <span class="math inline">\(y\)</span> respecte de <span class="math inline">\(x\)</span> és igual al quadrat de la seva correlació de Pearson:
<span class="math display">\[
R^2=R_{X,Y}^2
\]</span></p></li>
</ul>

<div class="rmdimportant">
Per tant, com més s’acosta la correlació de Pearson de <span class="math inline">\(x\)</span> i <span class="math inline">\(y\)</span>, en valor absolut, a 1, més s’acosten els vectors <span class="math inline">\(x,y\)</span> a dependre linealment l’un de l’altre, és a dir, més s’acosten els punts <span class="math inline">\((x_i,y_i)\)</span> a estar sobre una recta. El signe de <span class="math inline">\(R_{X,Y}\)</span> indica si aquesta dependència és creixent (<span class="math inline">\(R_{X,Y}&gt;0\)</span>) o decreixent (<span class="math inline">\(R_{X,Y}&lt;0\)</span>).
</div>
<p>Amb R, la correlació de Pearson de dos vectors es pot calcular amb la funció <code>cor</code>. Per exemple, la correlació del Pearson dels vectors <code>BMI</code> i <code>Chol</code> s’obté amb</p>
<div class="sourceCode" id="cb453"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb453-1"><a href="chap-ED.html#cb453-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(BMI,Chol)</span></code></pre></div>
<pre><code>## [1] 0.6979141</code></pre>
<p>Vegem que el seu quadrat és igual al <span class="math inline">\(R^2\)</span> de la regressió lineal de <code>Chol</code> en funció de <code>BMI</code>:</p>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="chap-ED.html#cb455-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(BMI,Chol)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 0.487084</code></pre>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="chap-ED.html#cb457-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Chol<span class="sc">~</span>BMI))<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.487084</code></pre>
<p>Per fer-nos una idea de què representa aquest valor de la correlació, vegem el gràfic dels punts (BMI,Chol) amb la seva recta de regressió lineal:</p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="chap-ED.html#cb459-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(BMI,Chol,<span class="at">pch=</span><span class="dv">20</span>)</span>
<span id="cb459-2"><a href="chap-ED.html#cb459-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(Chol<span class="sc">~</span>BMI),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-593-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Hi podem observar com <code>Chol</code> tendeix a créixer quan <code>BMI</code> creix, però els punts (BMI,Chol) no tendeixen a estar sobre una recta.</p>

<div class="rmdnote">
<p>Les funcions del paquet <strong>datasaurus</strong> us permeten crear conjunts de punts de “formes” diferents i mateixos estadístics, i en particular la mateixa correlació. Per exemple, tots els conjunts de punts del gràfic següent tenen la mateixa correlació.</p>
</div>
<p><img src="Bioestadistica-II_files/figure-html/datasaurus.png" width="90%" style="display: block; margin: auto;" /></p>
<p>Suposem ara que tenim una taula de dades numèriques de la forma
<span class="math display">\[
\begin{array}{cccc}
X_1 &amp; X_2 &amp; \ldots &amp; X_p\\ \hline
x_{1 1} &amp; x_{1 2} &amp;\ldots &amp; x_{1 p}\\
x_{2 1} &amp; x_{2 2} &amp;\ldots &amp; x_{2 p}\\
\vdots &amp; \vdots   &amp;   \ddots    &amp;\vdots\\ 
x_{n 1} &amp; x_{n 2} &amp;\ldots &amp; x_{n p}
\end{array}
\]</span>
on cada columna representa els valors d’una certa variable <span class="math inline">\(X_i\)</span> i cada filera un individu d’una mostra de la població, de manera que l’entrada <span class="math inline">\(x_{ij}\)</span> d’aquesta taula és el valor de <span class="math inline">\(X_j\)</span> sobre l’individu <span class="math inline">\(i\)</span>-èssim de la mostra.</p>
<p>La seva <strong>matriu de correlacions de Pearson</strong> és la matriu simètrica
<span class="math display">\[
\begin{pmatrix}  
 1 &amp; R_{X_1,X_2} &amp; \ldots &amp; R_{X_1,X_p}\\
 R_{X_2,X_1} &amp; 1 &amp; \ldots &amp; R_{X_2,X_p}\\
  \vdots &amp; \vdots  &amp;  \ddots      &amp; \vdots\\
R_{X_p,X_1} &amp; R_{X_p,X_2} &amp; \ldots &amp; 1
\end{pmatrix}
\]</span></p>
<p>Aquesta matriu de correlacions es calcula amb la funció <code>cor</code> aplicada a la matriu o el <em>data frame</em> de variables numèriques que emmagatzema la taula de dades. Per exemple, la matriu de correlacions de Pearson de la taula de dades <code>DF</code> de l’Exemple <a href="chap-ED.html#exm:multex2">9.4</a> és</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="chap-ED.html#cb460-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(DF)</span></code></pre></div>
<pre><code>##              BMI       Chol       Edats
## BMI   1.00000000  0.6979141  0.07316517
## Chol  0.69791406  1.0000000 -0.33145274
## Edats 0.07316517 -0.3314527  1.00000000</code></pre>
</div>
<div id="estimació" class="section level3" number="9.2.3">
<h3><span class="header-section-number">9.2.3</span> Estimació</h3>
<p>Les covariàncies de dos vectors, aplicades a mostres aleatòries simples de subjectes, estimen la covariància poblacional de les variables que han produït els vectors:</p>
<ul>
<li><p>La covariància mostral <span class="math inline">\(\widetilde{S}_{X,Y}\)</span> sempre és un estimador no esbiaixat de la covariància poblacional <span class="math inline">\(\sigma_{X,Y}\)</span></p></li>
<li><p>La covariància a seques <span class="math inline">\(S_{X,Y}\)</span> és l’estimador màxim versemblant de <span class="math inline">\(\sigma_{X,Y}\)</span> quan la distribució conjunta de les variables <span class="math inline">\(X,Y\)</span> és el que s’anomena <a href="http://es.wikipedia.org/wiki/Distribución_normal_multivariante%7D">normal bivariant</a>.</p></li>
</ul>
<p>La correlació de Pearson de dos vectors estima la correlació de les variables poblacionals que els han produït. En concret:</p>
<ul>
<li><span class="math inline">\(R_{X,Y}\)</span> és un estimador màxim versemblant de <span class="math inline">\(\rho_{X,Y}\)</span> quan la distribució conjunta de <span class="math inline">\(X,Y\)</span> és normal bivariant. N’és un estimador esbiaixat, però el seu biaix tendeix a 0.</li>
</ul>
</div>
<div id="correlació-de-spearman" class="section level3" number="9.2.4">
<h3><span class="header-section-number">9.2.4</span> Correlació de Spearman</h3>
<p>La correlació de Pearson mesura específicament la tendència de dues variables contínues a dependre linealment l’una de l’altra. En circumstàncies en les quals no esperem aquesta dependència lineal, o en les quals les nostres variables siguin quantitatives discretes o simplement ordinals, emprar la correlació de Pearson per a analitzar la relació entre dues variables no és el més adequat. Entre les propostes alternatives, la més popular és la <strong>correlació de Spearman</strong>.</p>
<p>Intuïtivament, la correlació de Spearman mesura la tendència que si <span class="math inline">\(x_i&gt;x_j\)</span>, passi que <span class="math inline">\(y_i&gt;y_j\)</span>. El seu valor és 1 si, per a tots <span class="math inline">\(i,j\)</span>,
<span class="math display">\[
x_i&gt;x_j\Longleftrightarrow y_i&gt;y_j
\]</span>
i el seu valor és -1 si, per a tots <span class="math inline">\(i,j\)</span>,
<span class="math display">\[
x_i&gt;x_j\Longleftrightarrow y_i&lt;y_j
\]</span>
Com més s’acosta la correlació de Spearman a valer 1 (o -1), per a més parelles d’índexs <span class="math inline">\((i,j)\)</span> tals que <span class="math inline">\(x_i&gt;x_j\)</span> es té que <span class="math inline">\(y_i&gt;y_j\)</span> (<span class="math inline">\(y_i&lt;y_j\)</span>, si s’acosta a -1).</p>
<p>Formalment, la correlació de Spearman de dos vectors <span class="math inline">\(x\)</span> i <span class="math inline">\(y\)</span> se defineix com la correlació de Pearson dels vectors de <strong>rangs</strong> de <span class="math inline">\(x\)</span> i <span class="math inline">\(y\)</span>. El vector de rangs d’un vector <span class="math inline">\(x\)</span> s’obté substituint cada valor de <span class="math inline">\(x\)</span> per la seva posició en el vector ordenat de menor a major, i en cas d’empats assigna la mitjana de les posicions que ocuparien tots els empats (aquests rangs ja han sortit, al <a href="https://aprender-uib.github.io/MatesII/contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics">test de Wilcoxon</a> i al <a href="https://aprender-uib.github.io/MatesII/contrastos-de-bondat-dajust.html#test-de-kolmogorov-smirnov">test de bondat d’ajust de Kolmogorov-Smirnov</a>). Per exemple, el vector de rangs de
<span class="math display">\[
x=(4,5,1,5,1,3,4,4)
\]</span>
és
<span class="math display">\[
(5,7.5,1.5,7.5,1.5,3,5,5)
\]</span>
Com hem calculat aquest vector?</p>
<ul>
<li>Als dos elements 1 de <span class="math inline">\(x\)</span> els tocarien les posicions 1, 2 del vector ordenat, i per tant el seu rang és la mitjana d’aquestes dues posicions: 1.5.</li>
<li>A l’element 3 li tocaria la posició 3 del vector ordenat, i com que només n’hi ha un, aquest és el seu rang.</li>
<li>Als tres elements 4 els tocarien les posicions 4, 5 i 6 del vector ordenat, i per tant el seu rang és la mitjana d’aquestes tres posicions: 5.</li>
<li>Finalment, als dos elements 5 els tocarien les posicions 7, 8 del vector ordenat, i per tant el seu rang és la mitjana d’aquestes dues posicions: 7.5.</li>
</ul>

<div class="rmdnote">
Per cert, amb R els rangs es calculen amb la funció <code>rank</code>:
</div>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="chap-ED.html#cb462-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rank</span>(<span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">4</span>))</span></code></pre></div>
<pre><code>## [1] 5.0 7.5 1.5 7.5 1.5 3.0 5.0 5.0</code></pre>
<p>Amb R, la correlació de Spearman es calcula directament amb la funció <code>cor</code> entrant-li el paràmetre <code>method="spearman"</code>. (El valor per defecte del paràmetre <code>method</code> és <code>"pearson"</code> i per això no l’indicam quan calculam la correlació de Pearson.)</p>

<div class="example">
<p><span id="exm:unnamed-chunk-599" class="example"><strong>Exemple 9.6  </strong></span>Calculem a mà la correlació de Spearman dels vectors <code>BMI</code> i <code>Chol</code>. El primer que farem serà calcular els rangs dels valors</p>
</div>
<p><span class="math display">\[
\begin{array}{|c|c||c|c|}
\hline
\mathit{BMI} &amp; \mathit{Rang} &amp; \mathit{Chol}&amp;  \mathit{Rang}
\\\hline\hline
18.3&amp; 1 &amp; 170&amp; 1 \\
24.4&amp;4.5 &amp; 202 &amp; 2\\
24.6&amp;6 &amp; 215&amp; 5 \\
24.4&amp;4.5 &amp; 218&amp;  6\\ 
22.2&amp;3 &amp; 210&amp;  3.5\\
19.5&amp;2 &amp; 210&amp;  3.5\\\hline
\end{array}
\]</span></p>
<p>Per tant, la correlació de Spearman de
<span class="math display">\[
\mathit{BMI}=(18.3, 24.4, 24.6, 24.4, 22.2, 19.5)\mbox{ i }\mathit{Chol}=(170, 202, 215, 218, 210, 210)
\]</span>
és la correlació de Pearson de
<span class="math display">\[
(1, 4.5, 6, 4.5, 3, 2)\mbox{ i }(1, 2, 5, 6, 3.5, 3.5)
\]</span></p>
<p>Comprovem-ho:</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="chap-ED.html#cb464-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(BMI,Chol,<span class="at">method=</span><span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 0.6470588</code></pre>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="chap-ED.html#cb466-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">4.5</span>,<span class="dv">6</span>,<span class="fl">4.5</span>,<span class="dv">3</span>,<span class="dv">2</span>),<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="fl">3.5</span>,<span class="fl">3.5</span>))</span></code></pre></div>
<pre><code>## [1] 0.6470588</code></pre>
</div>
<div id="contrastos-de-correlació" class="section level3" number="9.2.5">
<h3><span class="header-section-number">9.2.5</span> Contrastos de correlació</h3>
<p>En un <strong>contrast de correlació</strong> de dues variables poblacionals <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span>, la hipòtesi nul·la és que no hi ha correlació entre les dues variables, la qual cosa s’entén que tradueix que no hi ha cap relació entre elles.
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: &amp; \rho_{XY}=0\\
H_1: &amp; \rho_{XY}&gt; 0\text{ o }\rho_{XY}&lt; 0\text{ o }\rho_{XY}\neq 0
\end{array}\right.
\]</span></p>

<div class="rmdimportant">
Si en un contrast de correlació rebutjam la hipòtesi nul·la, en particular concloem que les variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són dependents (perquè si fossin independents, la seva correlació seria 0).
</div>
<p>No explicarem com es fa a mà aquest contrast ni quines hipòtesis han de satisfer les variables poblacionals per que el resultat sigui fiable. Si estau interessats en el detall, podeu consultar la <a href="https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#Testing_using_Student&#39;s_t-distribution">corresponent entrada de la Wikipedia</a>. Simplement heu de saber que s’efectua amb la funció <code>cor.test</code>. La seva sintaxi és similar a la de les altres funcions que efectuen contrastos.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-602" class="example"><strong>Exemple 9.7  </strong></span>Volem contrastar si hi ha correlació positiva entre el BMI i el nivell de colesterol d’un adult sa, amb un nivell de significació del 5%.</p>
</div>
<p><em>Variables poblacionals d’interès</em>:</p>
<ul>
<li><span class="math inline">\(\mathit{BMI}\)</span>: “Prenem un adult sa i anotam el seu BMI”</li>
<li><span class="math inline">\(\mathit{Chol}\)</span>: “Prenem un adult sa i anotam el nivell de colesterol en mg/dl”</li>
</ul>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: &amp; \rho_{\textit{BMI,Chol}}=0\\
H_1: &amp; \rho_{\textit{BMI,Chol}}&gt;0
\end{array}\right.
\]</span></p>
<p>Emprarem les mostres <code>BMI</code> i <code>Chol</code> de l’Exemple<a href="chap-ED.html#exm:multex1">9.3</a>.</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="chap-ED.html#cb468-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(BMI,Chol,<span class="at">alternative=</span><span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>## 
## 	Pearson&#39;s product-moment correlation
## 
## data:  BMI and Chol
## t = 1.949, df = 4, p-value = 0.06155
## alternative hypothesis: true correlation is greater than 0
## 95 percent confidence interval:
##  -0.08621998  1.00000000
## sample estimates:
##       cor 
## 0.6979141</code></pre>
<p><em>Conclusió</em>: No hem obtingut evidència estadísticament significativa que el BMI i el nivell de colesterol d’un adult sa tenguin correlació positiva (test de correlació, p-valor 0.06, IC 95% per a la correlació de -0.086 a 1).</p>

<div class="rmdcaution">
La conclusió és que no hem obtingut evidència que el BMI i el nivell de colesterol tenguin correlació positiva <strong>a la població dels adults sans</strong>. No a la nostra mostra, que sí que ha donat correlació positiva. Recordau que els contrastos sempre refereixen a la població.
</div>
</div>
</div>
<div id="test-de-la-lliçó-9" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> Test de la lliçó 9</h2>
<p><strong>(1)</strong> La covariància de dues variables aleatòries (marcau totes les continuacions correctes)</p>
<ol style="list-style-type: decimal">
<li>És sempre més gran o igual que 0</li>
<li>Mesura la tendència general de les dues variables a créixer (o decréixer) conjuntament</li>
<li>Mesura la tendència de les dues variables a créixer (o decréixer) conjuntament segons una funció lineal</li>
<li>Si val 0, les dues variables són independents</li>
<li>És el quocient de les variàncies de les dues variables aleatòries</li>
<li>Si les dues variables són independents, val 0</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(2)</strong> La correlació de Pearson de dues variables aleatòries (marcau totes les continuacions correctes)</p>
<ol style="list-style-type: decimal">
<li>Mesura la tendència general de les dues variables a créixer (o decréixer) conjuntament</li>
<li>Mesura la tendència de les dues variables a créixer (o decréixer) conjuntament segons una funció lineal</li>
<li>És l’arrel quadrada de la covariància</li>
<li>Si val 0, les dues variables són independents</li>
<li>Si les dues variables són independents, val 0</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(3)</strong> Quins valors pot prendre el coeficient de correlació de Pearson de dues variables?</p>
<ol style="list-style-type: decimal">
<li>Qualsevol valor real</li>
<li>Qualsevol valor real, i també <span class="math inline">\(\pm\infty\)</span></li>
<li>Qualsevol valor real més gran o igual que 0</li>
<li>Qualsevol valor real entre -1 i 1</li>
<li>Qualsevol valor real entre 0 i 1</li>
<li>Els valors 0, -1 i 1</li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(4)</strong> Quina, o quines, de les mesures següents serveix per quantificar la dispersió d’una variable aleatòria?</p>
<ol style="list-style-type: decimal">
<li>La covariància amb una variable constant</li>
<li>El p-valor d’un test khi quadrat</li>
<li>La variància mostral</li>
<li>La mitjana</li>
<li>La desviació típica</li>
<li>La variància</li>
<li>La correlació de Pearson amb una variable constant</li>
</ol>
<p><strong>(5)</strong> Una covariància -0.7 entre dues variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> indica (marcau una sola resposta):</p>
<ol style="list-style-type: decimal">
<li>Que un augment de <span class="math inline">\(X\)</span> sol anar associat a un augment de <span class="math inline">\(Y\)</span></li>
<li>Que un augment de <span class="math inline">\(X\)</span> sol causar un augment de <span class="math inline">\(Y\)</span></li>
<li>Que un augment de <span class="math inline">\(X\)</span> sol anar associat a una disminució de <span class="math inline">\(Y\)</span></li>
<li>Que un augment de <span class="math inline">\(X\)</span> sol causar una disminució de <span class="math inline">\(Y\)</span></li>
<li>Que les variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són independents</li>
</ol>
<p><strong>(6)</strong> La covariància mostral de dos vectors (marcau totes les continuacions correctes):</p>
<ol style="list-style-type: decimal">
<li>Només està definida per a vectors de la mateixa longitud</li>
<li>Pot prendre qualsevol valor real</li>
<li>Només pot prendre valors entre -1 i 1</li>
<li>És la correlació de Pearson dividida pel producte de les desviacions típiques mostrals dels vectors</li>
<li>Si els vectors són <span class="math inline">\((x_1,\ldots ,x_n)\)</span> i <span class="math inline">\((y_1,\ldots ,y_n)\)</span>, mesura la tendència dels punts <span class="math inline">\((x_i,y_i)\)</span> a estar sobre una recta</li>
<li>S’obté multiplicant per <span class="math inline">\(n-1\)</span> i dividint per <span class="math inline">\(n\)</span> la covariància “a seques” dels vectors</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(7)</strong> La correlació de Pearson de dos vectors (marcau totes les continuacions correctes):</p>
<ol style="list-style-type: decimal">
<li>Només està definida per a vectors de la mateixa longitud</li>
<li>Pot prendre qualsevol valor real</li>
<li>Només pot prendre valors entre -1 i 1</li>
<li>És la covariància mostral dividida pel producte de les desviacions típiques dels vectors</li>
<li>Si els vectors són <span class="math inline">\((x_1,\ldots ,x_n)\)</span> i <span class="math inline">\((y_1,\ldots ,y_n)\)</span>, mesura la tendència dels punts <span class="math inline">\((x_i,y_i)\)</span> a estar sobre una recta</li>
<li>S’obté multiplicant per <span class="math inline">\(n\)</span> i dividint per <span class="math inline">\(n-1\)</span> la correlació mostral de Pearson dels vectors</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(8)</strong> Quines de les matrius següents són matrius de correlacions de Pearson d’alguna parella de vectors?
<span class="math display">\[
\begin{array}{ccccc}
\left(\begin{array}{ccc} 1 &amp; 1\cr 1 &amp; 1  \end{array}\right) &amp; 
\left(\begin{array}{ccc} 1 &amp; 1.2   \cr  1.2 &amp; 1  \end{array}\right) &amp; 
\left(\begin{array}{ccc} 1 &amp; 0.8\cr -0.8 &amp; 1  \end{array}\right) &amp;
\left(\begin{array}{ccc} 0.6 &amp; 0.8\cr 0.8 &amp; 0.6  \end{array}\right) &amp; 
\left(\begin{array}{ccc} 1 &amp; 0\cr 0 &amp; 1  \end{array}\right)\\
\text{(a)} &amp; \text{(b)} &amp; \text{(c)} &amp; \text{(d)} &amp; \text{(e)}
\end{array}
\]</span>
Marcau totes les respostes correctes:</p>
<ol style="list-style-type: decimal">
<li>La (a)</li>
<li>La (b)</li>
<li>La (c)</li>
<li>La (d)</li>
<li>La (e)</li>
<li>Cap</li>
</ol>
<p><strong>(9)</strong> La correlació de Pearson de dos vectors (marcau totes les continuacions correctes, haureu de pensar un poc):</p>
<ol style="list-style-type: decimal">
<li>No varia si sumam a un dels vectors una constant</li>
<li>No varia si multiplicam un dels vectors per una constant <span class="math inline">\(&gt;0\)</span></li>
<li>No varia si multiplicam un dels vectors per una constant diferent de 0</li>
<li>No varia si multiplicam els dos vectors per la mateixa constant diferent de 0</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(10)</strong> Un contrast de correlació de Pearson (marcau totes les continuacions correctes):</p>
<ol style="list-style-type: decimal">
<li>Té sempre com a hipòtesi nul·la que les dues variables tenen correlació de Pearson 0</li>
<li>Té sempre com a hipòtesi nul·la que les dues variables tenen correlació de Pearson positiva</li>
<li>Té sempre com a hipòtesi alternativa que els dos vectors tenen correlació de Pearson 0</li>
<li>Té sempre com a hipòtesi alternativa que els dos vectors tenen correlació de Pearson positiva</li>
<li>També es pot usar per comparar amb 0 la covariància poblacional</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(11)</strong> Volem contrastar si el nivell mitjà de colesterol en sang (mesurat en mg/dl) és igual, o no, en els pacients que presenten accidents cardiovasculars que en els pacients que no en presenten a partir de dues mostres independents de 100 individus cadascuna. Quina prova estadística és la més apropiada? Marcau una sola resposta.</p>
<ol style="list-style-type: decimal">
<li>Un contrast de correlació de Spearman</li>
<li>Un test t</li>
<li>Un test khi quadrat</li>
<li>Un contrast de correlació de Pearson</li>
<li>Un test exacte de Fisher</li>
</ol>
<p><strong>(12)</strong> En un contrast de correlació entre xifres de colesterol lligat a lipoproteïnes de baixa densitat i la reducció del diàmetre de les artèries coronàries s’ha observat una <span class="math inline">\(R\)</span> de 0.14, amb un p-valor menor de 0.01. Quina és la interpretació més correcta?</p>
<ol style="list-style-type: decimal">
<li>Existeix una correlació forta entre els dos vectors, però no és estadísticament significativa</li>
<li>Existeix una correlació feble positiva entre els dos vectors, però és estadísticament significativa</li>
<li>Existeix una correlació forta entre els dos vectors i és estadísticament significativa</li>
<li>L’augment de les xifres de colesterol lligat a proteïnes de baixa densitat provoca l’augment del diàmetre de les artèries coronàries</li>
<li>L’augment del diàmetre de les artèries coronàries causa l’augment de les xifres de colesterol lligat a proteïnes de baixa densitat</li>
</ol>
<p><strong>(13)</strong> En els 10 naixements que van tenir lloc en un hospital en un dia determinat, es va anotar el pes del nadó (<span class="math inline">\(X\)</span>) i l’edat de la mare (<span class="math inline">\(Y\)</span>). Curiosament, tots els nadons van pesar el mateix: 2.6 kg. Quina va ser la covariància entre els pesos i les edats?</p>
<ol style="list-style-type: decimal">
<li>1</li>
<li>0</li>
<li>-1</li>
<li>2.6</li>
<li>0.26</li>
<li>És impossible saber-ho sense conèixer les edats de les mares</li>
</ol>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-605"></span>
<img src="Bioestadistica-II_files/figure-html/test9.png" alt="Gràfics de dispersió de les preguntes (14) a (18)" width="100%" />
<p class="caption">
Figura 9.5: Gràfics de dispersió de les preguntes (14) a (18)
</p>
</div>
<p><strong>(14)</strong> Dels gràfics de dispersió de la figura, quin correspon a <span class="math inline">\(R=-0.5\)</span></p>
<ol style="list-style-type: decimal">
<li>El (a)</li>
<li>El (b)</li>
<li>El (c)</li>
<li>El (d)</li>
<li>El (e)</li>
</ol>
<p><strong>(15)</strong> Dels gràfics de dispersió de la figura, quin correspon a <span class="math inline">\(R=-0.1\)</span></p>
<ol style="list-style-type: decimal">
<li>El (a)</li>
<li>El (b)</li>
<li>El (c)</li>
<li>El (d)</li>
<li>El (e)</li>
</ol>
<p><strong>(16)</strong> Dels gràfics de dispersió de la figura, quin correspon a <span class="math inline">\(R=0.1\)</span></p>
<ol style="list-style-type: decimal">
<li>El (a)</li>
<li>El (b)</li>
<li>El (c)</li>
<li>El (d)</li>
<li>El (e)</li>
</ol>
<p><strong>(17)</strong> Dels gràfics de dispersió de la figura, quin correspon a <span class="math inline">\(R=0.5\)</span></p>
<ol style="list-style-type: decimal">
<li>El (a)</li>
<li>El (b)</li>
<li>El (c)</li>
<li>El (d)</li>
<li>El (e)</li>
</ol>
<p><strong>(18)</strong> Dels gràfics de dispersió de la figura, quin correspon a <span class="math inline">\(R=0.9\)</span></p>
<ol style="list-style-type: decimal">
<li>El (a)</li>
<li>El (b)</li>
<li>El (c)</li>
<li>El (d)</li>
<li>El (e)</li>
</ol>
<p><strong>(19)</strong> Quin és el rang dels valors 2 al vector <span class="math inline">\((-1, -1, 1, -2, -1, 1, 3, 1, 1, 2, 1, 2, 1, 3)\)</span>?</p>
<ol style="list-style-type: decimal">
<li>4</li>
<li>11</li>
<li>11.5</li>
<li>12</li>
<li>11 i 12</li>
<li>Cap dels anteriors</li>
</ol>
<p><strong>(20)</strong> Quines de les afirmacions següents sobre les correlacions de Pearson i Spearman de dos vectors són correctes?</p>
<ol style="list-style-type: decimal">
<li>Valen el mateix si els vectors són mostres de variables ordinals</li>
<li>Valen el mateix si els valors dels dos vectors són nombres enters</li>
<li>La correlació de Spearman no es pot emprar amb mostres de variables quantitatives</li>
<li>Si la correlació de Pearson de dos vectors és 1, la de Spearman també</li>
<li>Si la correlació de Spearman de dos vectors és 0, la de Pearson també</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="contrastos-dindependència-i-homogeneïtat.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
