<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tema 5 Contrastos d’hipòtesis: Generalitats | Matemàtiques II v.2021</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Tema 5 Contrastos d’hipòtesis: Generalitats | Matemàtiques II v.2021" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 5 Contrastos d’hipòtesis: Generalitats | Matemàtiques II v.2021" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2021-03-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-IC.html"/>
<link rel="next" href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="chapter" data-level="1" data-path="chap-conceptes.html"><a href="chap-conceptes.html"><i class="fa fa-check"></i><b>1</b> Alguns conceptes bàsics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chap-conceptes.html"><a href="chap-conceptes.html#tipus-de-dades"><i class="fa fa-check"></i><b>1.1</b> Tipus de dades</a></li>
<li class="chapter" data-level="1.2" data-path="chap-conceptes.html"><a href="chap-conceptes.html#població"><i class="fa fa-check"></i><b>1.2</b> Població</a></li>
<li class="chapter" data-level="1.3" data-path="chap-conceptes.html"><a href="chap-conceptes.html#variable-aleatòria"><i class="fa fa-check"></i><b>1.3</b> Variable aleatòria</a></li>
<li class="chapter" data-level="1.4" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostra"><i class="fa fa-check"></i><b>1.4</b> Mostra</a></li>
<li class="chapter" data-level="1.5" data-path="chap-conceptes.html"><a href="chap-conceptes.html#sec:mostreig"><i class="fa fa-check"></i><b>1.5</b> Mostreig aleatori</a></li>
<li class="chapter" data-level="1.6" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostres-de-conveniència"><i class="fa fa-check"></i><b>1.6</b> Mostres de conveniència</a></li>
<li class="chapter" data-level="1.7" data-path="chap-conceptes.html"><a href="chap-conceptes.html#test-de-la-lliçó-1"><i class="fa fa-check"></i><b>1.7</b> Test de la lliçó 1</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-varal.html"><a href="chap-varal.html"><i class="fa fa-check"></i><b>2</b> Variables aleatòries</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap-varal.html"><a href="chap-varal.html#generalitats-sobre-variables-aleatòries"><i class="fa fa-check"></i><b>2.1</b> Generalitats sobre variables aleatòries</a></li>
<li class="chapter" data-level="2.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-discretes"><i class="fa fa-check"></i><b>2.2</b> Variables aleatòries discretes</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució"><i class="fa fa-check"></i><b>2.2.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="2.2.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança"><i class="fa fa-check"></i><b>2.2.2</b> Esperança</a></li>
<li class="chapter" data-level="2.2.3" data-path="chap-varal.html"><a href="chap-varal.html#variància-i-desviació-típica"><i class="fa fa-check"></i><b>2.2.3</b> Variància i desviació típica</a></li>
<li class="chapter" data-level="2.2.4" data-path="chap-varal.html"><a href="chap-varal.html#quantils"><i class="fa fa-check"></i><b>2.2.4</b> Quantils</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chap-varal.html"><a href="chap-varal.html#famílies-importants-de-variables-aleatòries-discretes"><i class="fa fa-check"></i><b>2.3</b> Famílies importants de variables aleatòries discretes</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-binomials"><i class="fa fa-check"></i><b>2.3.1</b> Variables aleatòries binomials</a></li>
<li class="chapter" data-level="2.3.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-hipergeomètriques"><i class="fa fa-check"></i><b>2.3.2</b> Variables aleatòries hipergeomètriques</a></li>
<li class="chapter" data-level="2.3.3" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-de-poisson"><i class="fa fa-check"></i><b>2.3.3</b> Variables aleatòries de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-contínues"><i class="fa fa-check"></i><b>2.4</b> Variables aleatòries contínues</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució-1"><i class="fa fa-check"></i><b>2.4.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="2.4.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança-variància-quantils"><i class="fa fa-check"></i><b>2.4.2</b> Esperança, variància, quantils…</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chap-varal.html"><a href="chap-varal.html#sec:normal"><i class="fa fa-check"></i><b>2.5</b> Variables aleatòries normals</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i><b>2.5.1</b> Amb R</a></li>
<li class="chapter" data-level="2.5.2" data-path="chap-varal.html"><a href="chap-varal.html#propietats-bàsiques"><i class="fa fa-check"></i><b>2.5.2</b> Propietats bàsiques</a></li>
<li class="chapter" data-level="2.5.3" data-path="chap-varal.html"><a href="chap-varal.html#intervals-de-referència"><i class="fa fa-check"></i><b>2.5.3</b> Intervals de referència</a></li>
<li class="chapter" data-level="2.5.4" data-path="chap-varal.html"><a href="chap-varal.html#sec:lognormal"><i class="fa fa-check"></i><b>2.5.4</b> Variables log-normals</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="chap-varal.html"><a href="chap-varal.html#test-de-la-lliçó-2"><i class="fa fa-check"></i><b>2.6</b> Test de la lliçó 2</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-estim.html"><a href="chap-estim.html"><i class="fa fa-check"></i><b>3</b> Estimació puntual</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap-estim.html"><a href="chap-estim.html#estimadors"><i class="fa fa-check"></i><b>3.1</b> Estimadors</a></li>
<li class="chapter" data-level="3.2" data-path="chap-estim.html"><a href="chap-estim.html#mitjana-mostral"><i class="fa fa-check"></i><b>3.2</b> Mitjana mostral</a></li>
<li class="chapter" data-level="3.3" data-path="chap-estim.html"><a href="chap-estim.html#proporció-mostral"><i class="fa fa-check"></i><b>3.3</b> Proporció mostral</a></li>
<li class="chapter" data-level="3.4" data-path="chap-estim.html"><a href="chap-estim.html#variància-mostral"><i class="fa fa-check"></i><b>3.4</b> Variància mostral</a></li>
<li class="chapter" data-level="3.5" data-path="chap-estim.html"><a href="chap-estim.html#la-distribució-t-de-student"><i class="fa fa-check"></i><b>3.5</b> La distribució t de Student</a></li>
<li class="chapter" data-level="3.6" data-path="chap-estim.html"><a href="chap-estim.html#biaix-i-precisió"><i class="fa fa-check"></i><b>3.6</b> Biaix i precisió</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="chap-estim.html"><a href="chap-estim.html#estimadors-no-esbiaixats"><i class="fa fa-check"></i><b>3.6.1</b> Estimadors no esbiaixats</a></li>
<li class="chapter" data-level="3.6.2" data-path="chap-estim.html"><a href="chap-estim.html#sec:precis"><i class="fa fa-check"></i><b>3.6.2</b> Estimadors precisos</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="chap-estim.html"><a href="chap-estim.html#estimadors-màxim-versemblants"><i class="fa fa-check"></i><b>3.7</b> Estimadors màxim versemblants</a></li>
<li class="chapter" data-level="3.8" data-path="chap-estim.html"><a href="chap-estim.html#sec:pobl"><i class="fa fa-check"></i><b>3.8</b> Estimació de poblacions</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="chap-estim.html"><a href="chap-estim.html#estimació-de-poblacions-numerades"><i class="fa fa-check"></i><b>3.8.1</b> Estimació de poblacions numerades</a></li>
<li class="chapter" data-level="3.8.2" data-path="chap-estim.html"><a href="chap-estim.html#marca-recaptura"><i class="fa fa-check"></i><b>3.8.2</b> Marca-recaptura</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="chap-estim.html"><a href="chap-estim.html#test-de-la-lliçó-3"><i class="fa fa-check"></i><b>3.9</b> Test de la lliçó 3</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-IC.html"><a href="chap-IC.html"><i class="fa fa-check"></i><b>4</b> Intervals de confiança</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chap-IC.html"><a href="chap-IC.html#definició-dinterval-de-confiança"><i class="fa fa-check"></i><b>4.1</b> Definició d’interval de confiança</a></li>
<li class="chapter" data-level="4.2" data-path="chap-IC.html"><a href="chap-IC.html#exemple-interval-de-confiança-del-95-per-a-la-mitjana-duna-variable-aleatòria-normal"><i class="fa fa-check"></i><b>4.2</b> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</a></li>
<li class="chapter" data-level="4.3" data-path="chap-IC.html"><a href="chap-IC.html#interval-de-confiança-per-a-la-mitjana-basat-en-la-t-de-student"><i class="fa fa-check"></i><b>4.3</b> Interval de confiança per a la mitjana basat en la t de Student</a>
<ul>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#la-fórmula"><i class="fa fa-check"></i>La fórmula</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#algunes-consideracions"><i class="fa fa-check"></i>Algunes consideracions</a></li>
<li class="chapter" data-level="" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i>Amb R</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#càlcul-de-la-mida-de-la-mostra-per-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chap-IC.html"><a href="chap-IC.html#intervals-de-confiança-per-a-proporcions"><i class="fa fa-check"></i><b>4.4</b> Intervals de confiança per a proporcions</a>
<ul>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#mètode-exacte-de-clopper-pearson"><i class="fa fa-check"></i>Mètode “exacte” de Clopper-Pearson</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#mètode-de-wilson"><i class="fa fa-check"></i>Mètode de Wilson</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#mètode-de-laplace"><i class="fa fa-check"></i>Mètode de Laplace</a></li>
<li><a href="chap-IC.html#quan-podem-calcular-més-dun-interval-per-a-p_x-quin-calculam">Quan podem calcular més d’un interval per a <span class="math inline">\(p_X\)</span>, quin calculam?</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#càlcul-de-la-mida-de-la-mostra-per-a-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per a fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chap-IC.html"><a href="chap-IC.html#intervals-de-confiança-per-a-la-variància-i-la-desviació-típica-duna-variable-normal"><i class="fa fa-check"></i><b>4.5</b> Intervals de confiança per a la variància i la desviació típica d’una variable normal</a></li>
<li class="chapter" data-level="4.6" data-path="chap-IC.html"><a href="chap-IC.html#poblacions-finites"><i class="fa fa-check"></i><b>4.6</b> “Poblacions finites”</a></li>
<li class="chapter" data-level="4.7" data-path="chap-IC.html"><a href="chap-IC.html#test-de-la-lliçó-4"><i class="fa fa-check"></i><b>4.7</b> Test de la lliçó 4</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-chgen.html"><a href="chap-chgen.html"><i class="fa fa-check"></i><b>5</b> Contrastos d’hipòtesis: Generalitats</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap-chgen.html"><a href="chap-chgen.html#les-hipòtesis-nulla-i-alternativa"><i class="fa fa-check"></i><b>5.1</b> Les hipòtesis nul·la i alternativa</a></li>
<li class="chapter" data-level="5.2" data-path="chap-chgen.html"><a href="chap-chgen.html#sec:moneda"><i class="fa fa-check"></i><b>5.2</b> Un exemple</a></li>
<li class="chapter" data-level="5.3" data-path="chap-chgen.html"><a href="chap-chgen.html#sec:pval"><i class="fa fa-check"></i><b>5.3</b> El p-valor</a></li>
<li class="chapter" data-level="5.4" data-path="chap-chgen.html"><a href="chap-chgen.html#tipus-derrors"><i class="fa fa-check"></i><b>5.4</b> Tipus d’errors</a></li>
<li class="chapter" data-level="5.5" data-path="chap-chgen.html"><a href="chap-chgen.html#sec:exttest"><i class="fa fa-check"></i><b>5.5</b> Exemple: El test t</a></li>
<li class="chapter" data-level="5.6" data-path="chap-chgen.html"><a href="chap-chgen.html#recapitulació"><i class="fa fa-check"></i><b>5.6</b> Recapitulació</a>
<ul>
<li class="chapter" data-level="" data-path="chap-chgen.html"><a href="chap-chgen.html#interval-de-confiança-dun-contrast"><i class="fa fa-check"></i>Interval de confiança d’un contrast</a></li>
<li class="chapter" data-level="" data-path="chap-chgen.html"><a href="chap-chgen.html#la-potència"><i class="fa fa-check"></i>La potència</a></li>
<li class="chapter" data-level="" data-path="chap-chgen.html"><a href="chap-chgen.html#el-risc-de-positiu-fals-opcional"><i class="fa fa-check"></i>El risc de positiu fals (Opcional)</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="chap-chgen.html"><a href="chap-chgen.html#test-de-la-lliçó-5"><i class="fa fa-check"></i><b>5.7</b> Test de la lliçó 5</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><i class="fa fa-check"></i><b>6</b> Contrastos d’hipòtesis d’un i dos paràmetres</a>
<ul>
<li class="chapter" data-level="6.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-de-mitjanes"><i class="fa fa-check"></i><b>6.1</b> Contrastos de mitjanes</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-una-mitjana"><i class="fa fa-check"></i><b>6.1.1</b> Test t per a una mitjana</a></li>
<li class="chapter" data-level="6.1.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-dues-mitjanes"><i class="fa fa-check"></i><b>6.1.2</b> Test t per a dues mitjanes</a></li>
<li class="chapter" data-level="6.1.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-t-amb-r"><i class="fa fa-check"></i><b>6.1.3</b> Tests t amb R</a></li>
<li class="chapter" data-level="6.1.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exemples"><i class="fa fa-check"></i><b>6.1.4</b> Exemples</a></li>
<li class="chapter" data-level="6.1.5" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics"><i class="fa fa-check"></i><b>6.1.5</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#sec:contrvar"><i class="fa fa-check"></i><b>6.2</b> Contrastos de variàncies</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-chi2-duna-variància"><i class="fa fa-check"></i><b>6.2.1</b> Test <span class="math inline">\(\chi^2\)</span> d’una variància</a></li>
<li class="chapter" data-level="6.2.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-f-per-a-dues-variàncies"><i class="fa fa-check"></i><b>6.2.2</b> Test F per a dues variàncies</a></li>
<li class="chapter" data-level="6.2.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics-1"><i class="fa fa-check"></i><b>6.2.3</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-proporcions"><i class="fa fa-check"></i><b>6.3</b> Contrastos per a proporcions</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-una-proporció"><i class="fa fa-check"></i><b>6.3.1</b> Contrastos per a una proporció</a></li>
<li class="chapter" data-level="6.3.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-independents"><i class="fa fa-check"></i><b>6.3.2</b> Contrastos per a 2 proporcions emprant mostres independents</a></li>
<li class="chapter" data-level="6.3.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-aparellades"><i class="fa fa-check"></i><b>6.3.3</b> Contrastos per a 2 proporcions emprant mostres aparellades</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-de-la-lliçó-6"><i class="fa fa-check"></i><b>6.4</b> Test de la lliçó 6</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II v.2021</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap:chgen" class="section level1" number="5">
<h1><span class="header-section-number">Tema 5</span> Contrastos d’hipòtesis: Generalitats</h1>
<p>En moltes situacions, hem de prendre una <strong>decisió</strong> sobre si es pot acceptar o rebutjar una <strong>hipòtesi</strong> relativa al valor d’un paràmetre d’una població o diverses poblacions. Per prendre aquesta decisió, prenem una mostra de la població i hi mesuram qualque cosa. Per exemple:</p>
<ul>
<li><p>Volem saber si una moneda està trucada a favor de cara. Per decidir-ho, la llançam una sèrie de vegades, i comptam quantes cares surten.</p></li>
<li><p>Volem decidir si un tractament nou A és més efectiu que el tractament vell B en la curació d’una malaltia X. Per decidir-ho, portam a terme un assaig clínic, tractant amb A un grup de malalts i amb B un altre grup de malalts, i comparam la taxa de curació dels tractaments sobre aquests dos grups.</p></li>
</ul>
<p>El mètode estadístic que s’empra per acceptar o rebutjar una hipòtesi rep el nom de <strong>contrast d’hipòtesis</strong>.</p>
<div id="les-hipòtesis-nulla-i-alternativa" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Les hipòtesis nul·la i alternativa</h2>
<p>En un contrast d’hipòtesis, es comparen sempre dues hipòtesis alternatives: la <strong>hipòtesi nul·la</strong> <em>H</em><sub>0</sub> i la <strong>hipòtesi
alternativa</strong> <em>H</em><sub>1</sub>. Se sol plantejar formalment
<span class="math display">\[
\left\{\begin{array}{ll}
H_{0}:\text{hipòtesi nul·la}\\ 
H_{1}:\text{hipòtesi alternativa}
\end{array}
\right.
\]</span></p>
<ul>
<li><p>Típicament, la <strong>hipòtesi nul·la</strong> <em>H</em><sub>0</sub> és “no hi ha diferència”, “no passa res”, “no hi ha res d’estrany” o l’equivalent en el context del contrast:</p>
<ul>
<li><p>La moneda és equilibrada (50% de probabilitat de cara)</p></li>
<li><p>Els tractaments A i B són igual d’efectius en la curació de la malaltia X</p></li>
</ul></li>
<li><p>La <strong>hipòtesi alternativa</strong> <em>H</em><sub>1</sub> planteja la diferència de la qual cercam evidència:</p>
<ul>
<li><p>La moneda està trucada a favor de cara (més del 50% de probabilitat de cara)</p></li>
<li><p>A és més efectiu que B en la curació de la malaltia X</p></li>
</ul></li>
<li><p>Per defecte, estam disposats a acceptar <em>H</em><sub>0</sub>: que no hi ha diferència, que no passa res.</p>
<ul>
<li><p>Per defecte, estam disposats a acceptar que la moneda és equilibrada (la majoria ho són, no?)</p></li>
<li><p>Per defecte, estam disposats a acceptar que els dos tractaments són igual d’efectius (en general, si preneu dos tractaments qualssevol, a l’atzar, i els aplicau a malalts de X, els dos seran igual de (in)efectius)</p></li>
</ul></li>
<li><p>Si obtenim evidència suficient que <em>H</em><sub>0</sub> és falsa, rebutjarem <em>H</em><sub>0</sub> a favor de <em>H</em><sub>1</sub> i conclourem que <em>H</em><sub>1</sub> és vertadera.</p>
<p>Què vol dir “obtenir evidència suficient que <em>H</em><sub>0</sub> és falsa”? Doncs que les dades obtengudes fan que <em>H</em><sub>0</sub> sigui <strong>inversemblant</strong> (mala de creure) per comparació amb <em>H</em><sub>1</sub>:</p>
<ul>
<li><p>Tendrem evidència que la moneda està trucada a favor de cara si a la nostra sèrie de llançaments la proporció de cares és tan i tan gran que fa mal de creure que la probabilitat de cara sigui del 50%</p></li>
<li><p>Tendrem evidència que el tractament A és més efectiu que B en la curació de la malaltia X si en el nostre assaig la taxa de curació de la malaltia X amb el tractament A és tan i tan més gran que la de B que fa mal de creure que els dos tractaments siguin igual d’efectius</p></li>
</ul></li>
<li><p>Si no obtenim evidència suficient que <em>H</em><sub>0</sub> és falsa, és a dir, si les nostres dades són raonablement compatibles amb <em>H</em><sub>0</sub>, no podrem rebutjar-la. En aquest cas direm que <strong>acceptam la hipòtesi nul·la</strong> com a sinònim de <em>no rebutjam la hipòtesi nul·la</em>.</p>
<ul>
<li><p>Acceptarem que la moneda no està trucada a favor de cara si a la nostra sèrie de llançaments la proporció de cares no és prou gran com per fer mal de creure que sigui equilibrada</p></li>
<li><p>Acceptarem que el tractament A és igual d’efectiu que B en la curació de la malaltia X si en el nostre assaig la taxa de curació de la malaltia X amb el tractament A no és prou més gran que la de B com per fer mal de creure que els dos tractaments siguin igual d’efectius</p></li>
</ul></li>
</ul>

<div class="rmdcaution">
Si rebutjam <em>H</em><sub>0</sub> en favor de <em>H</em><sub>1</sub> <em>no</em> serà perquè hàgim demostrat que <em>H</em><sub>0</sub> sigui impossible, ni tan sols que sigui improbable: tan sols haurem observat que és <em>mala de creure vists els resultats del nostre experiment</em>
</div>
<p>Per exemple, si en una seqüència de 30 llançaments d’una moneda obtenim totes les vegades cara, segurament ho considerarem evidència que la moneda està trucada, però <strong>no demostrarà que la moneda estigui trucada</strong>. Sí, farà mal de creure que sigui equilibrada, però no és impossible: la moneda podria ser equilibrada i per pur atzar nosaltres haver tengut aquesta ratxa de cares. Feu els comptes. La probabilitat de treure 30 cares en 30 llançaments d’una moneda equilibrada és 0.5<sup>30</sup>=9.3· 10<sup>-10</sup>. Per tant, de mitjana, aproximadament en un de cada mil milions de pics que s’efectuen 30 llançaments seguits d’una moneda equilibrada, s’obtenen 30 cares. Al món hi ha actualment més de 7700 milions de persones. És a dir que, si tots ens posàssim d’acord i llançàssim una moneda equilibrada 30 vegades, esperaríem que entre 7 i 8 treguessin 30 cares.</p>
<p>I tampoc podem dir que sigui improbable que la moneda sigui equilibrada, ja que nosaltres sabem calcular
<span class="math display">\[
P(\text{30 cares en 30 llançaments}\mid \text{La moneda és equilibrada})
\]</span>
però no sabem calcular
<span class="math display">\[
P(\text{La moneda és equilibrada}\mid\text{30 cares en 30 llançaments}).
\]</span></p>

<div class="rmdcaution">
Si acceptam la hipòtesi nul·la és perquè no la podem rebutjar ja que no trobam motius per dubtar d’ella, però no haurem trobat evidència que sigui vertadera ni haurem demostrat que sigui probable (i possible en principi ho és sempre).
</div>
<p>Per exemple, si en una seqüència de 4 llançaments d’una moneda obtenim 2 cares, no tendrem motiu per dubtar que la probabilitat de cara sigui 0.5: no podrem rebutjar que aquesta probabilitat sigui 0.5. Però tampoc no tendrem motiu per dubtar que la probabilitat de cara sigui, jo què sé, 0.5001: no podrem rebutjar que aquesta probabilitat sigui 0.5001. Però el que no pot ser és que diguem que hem obtingut evidència que la probabilitat de cara és 0.5 i que hem obtingut evidència que la probabilitat de cara és 0.5001. No es pot obtenir evidència simultàniament de dues coses que s’excloguin una a l’altra.</p>

<div class="rmdimportant">
<p>La millor manera de no entendre malament el resultat d’un contrast d’hipòtesis és sempre redactar la conclusió en la forma</p>
<ul>
<li>Hem trobat evidència de la hipotesi alternativa</li>
<li>No hem trobat evidència de la hipotesi alternativa</li>
</ul>
<p>segons quin sigui el cas.</p>
</div>

<div class="example">
<p><span id="exm:judici" class="example"><strong>Exemple 5.1  </strong></span>En un judici (on l’acusat és innocent si no es demostra el contrari, i per tant estam disposats a acceptar per defecte que és innocent), se cerca evidència que l’acusat és culpable, per tant aquesta és la hipòtesi alternativa:</p>
</div>
<ul>
<li><p>El contrast és
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:\text{L&#39;acusat és innocent}\\ 
H_{1}:\text{L&#39;acusat és culpable}
\end{array}
\right.
\]</span></p></li>
<li><p>S’aporten proves</p></li>
<li><p>Si el jurat les troba prou incriminatòries, “més enllà de tot dubte raonable”, declara <strong>culpable</strong> l’acusat (rebutja <em>H</em><sub>0</sub> en favor de <em>H</em><sub>1</sub>)</p></li>
<li><p>Si el jurat no les troba prou incriminatòries, el considera <strong>no culpable</strong> (no rebutja <em>H</em><sub>0</sub>)</p></li>
</ul>
<p>Fixau-vos que considerar no culpable no és el mateix que demostrar que és innocent: pot ser que es consideri que l’acusat no és culpable simplement perquè no s’hagi trobat prou evidència per declarar-lo culpable.</p>

<div class="example">
<p><span id="exm:examen" class="example"><strong>Exemple 5.2  </strong></span>Un examen és un contrast d’hipòtesis. En aquest cas, “no passa res” significa que l’estudiant és com si no hagués anat al curs, no ha après res, i per tant aquesta és la hipòtesi nul·la. Amb l’examen cercam evidència que l’estudiant ha après la matèria, per tant aquesta serà la hipòtesi alternativa:</p>
</div>
<ul>
<li><p>El contrast és:
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:\text{L&#39;estudiant no sap la matèria}\\ 
H_{1}:\text{L&#39;estudiant sap la matèria}
\end{array}
\right.
\]</span></p></li>
<li><p>Prenem una mostra del coneixement de l’estudiant (l’estudiant fa l’examen)</p></li>
<li><p>Si hi ha prou evidència a favor de <em>H</em><sub>1</sub> (si l’examen li surt prou bé), rebutjam <em>H</em><sub>0</sub>: decidim que l’estudiant sap la matèria, aprova l’assignatura</p></li>
<li><p>Si no hi ha prou evidència a favor de <em>H</em><sub>1</sub> (si l’examen no li surt prou bé), ens quedam amb <em>H</em><sub>0</sub>: concloem que l’estudiant no ha après la matèria, suspèn l’assignatura</p></li>
</ul>

<div class="example">
<p><span id="exm:esport1" class="example"><strong>Exemple 5.3  </strong></span>Ens trobam amb la notícia següent al diari, i ens demanam si les dones practiquen realment menys esport que els homes.</p>
</div>
<p><img src="Bioestadistica-II_files/figure-html/mujeresdeporte.png" width="75%" style="display: block; margin: auto;" /></p>
<p>Aquesta pregunta la podem plantejar de moltes maneres:</p>
<ul>
<li><p>Totes les dones fan cada dia menys hores d’esport que tots els homes?</p></li>
<li><p>Si prenc una dona i un home a l’atzar, hi ha més d’un 50% de probabilitat que ella practiqui menys esport que ell?</p></li>
<li><p>La majoria de les dones fan cada dia menys hores d’esport que la majoria dels homes?</p></li>
<li><p>La proporció de practicants d’esport entre les dones és més petita que entre els homes?</p></li>
<li><p>La mitjana setmanal de vegades que les dones practiquen esport és més petita que la dels homes?</p></li>
<li><p>La mitjana setmanal d’hores que les dones practiquen esport és més petita que la dels homes?</p></li>
<li><p>…</p></li>
</ul>
<p>Cada una d’aquestes preguntes es traduiria en un contrast d’hipòtesis diferent. Com que aquí estam tractant contrastos sobre paràmetres poblacionals (mitjanes, proporcions, etc.), podríem plantejar algun dels quatre darrers. Anem a centrar-nos en la darrera qüestió, sobre mitjanes setmanals d’hores d’esport.</p>
<p>Aquí, les variables poblacionals d’interès són:</p>
<ul>
<li><p><span class="math inline">\(X_d\)</span>: “Prenc una dona i anot el seu nombre mitjà d’hores setmanals d’esport”, amb mitjana <span class="math inline">\(\mu_d\)</span>: la mitjana d’hores setmanals d’esport de les dones (la mitjana de les mitjanes d’hores setmanals d’esport de totes les dones és la mitjana d’hores setmanals d’esport de les dones).</p></li>
<li><p><span class="math inline">\(X_h\)</span>: “Prenc un home i anot el seu nombre mitjà d’hores setmanals d’esport”, amb mitjana <span class="math inline">\(\mu_h\)</span>: la mitjana d’hores setmanals d’esport dels homes</p></li>
</ul>
<p>El contrast que volem realitzar és</p>
<ul>
<li><p><em>Hipòtesi nul·la</em>: no hi ha diferència entre les mitjanes d’hores setmanals d’esport d’homes i dones</p></li>
<li><p><em>Hipòtesi alternativa</em>: la mitjana d’hores setmanals d’esport de les dones és més petita que la dels homes</p></li>
</ul>
<p>És a dir
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}: \mu_d=\mu_h\\ 
H_{1}:\mu_d&lt;\mu_h
\end{array}
\right.
\]</span></p>
<p>El procediment per realitzar-lo serà:</p>
<ul>
<li><p>Prenem mostres aleatòries de dones i d’homes i els demanam pels seus hàbits de pràctica d’esport</p></li>
<li><p>Calculam la mitjana mostral <span class="math inline">\(\overline{X}_d\)</span> d’hores setmanals d’esport de les dones de la mostra</p></li>
<li><p>Calculam la mitjana mostral <span class="math inline">\(\overline{X}_h\)</span> d’hores setmanals d’esport dels homes de la mostra</p></li>
<li><p>Si <span class="math inline">\(\overline{X}_d\)</span> és molt més petita que <span class="math inline">\(\overline{X}_h\)</span>, ho prendrem com a evidència que <span class="math inline">\(\mu_d&lt;\mu_h\)</span></p></li>
<li><p>Si <span class="math inline">\(\overline{X}_d\)</span> no és molt més petita que <span class="math inline">\(\overline{X}_h\)</span>, no haurem trobat evidència que <span class="math inline">\(\mu_d&lt;\mu_h\)</span> i per tant acceptarem que <span class="math inline">\(\mu_d=\mu_h\)</span></p></li>
</ul>
<p>Què significa “<span class="math inline">\(\overline{X}_d\)</span> molt més petita que <span class="math inline">\(\overline{X}_h\)</span>”? Una opció, que podríem importar del tema anterior, seria calcular un interval de confiança del 95% per a <span class="math inline">\(\mu_d-\mu_h\)</span> a partir de la mostra:</p>
<ul>
<li><p>Si estigués totalment a l’esquerra del 0, amb un 95% de confiança podríem concloure que <span class="math inline">\(\mu_d&lt;\mu_h\)</span> (perquè tendríem un 95% de seguretat que el valor real de la diferència <span class="math inline">\(\mu_d-\mu_h\)</span> pertany a un interval de nombres estrictament negatius).</p></li>
<li><p>En cas contrari, és a dir, si contengués el 0 o si estigués totalment a la dreta del 0, amb un 95% de confiança no podríem concloure que <span class="math inline">\(\mu_d&lt;\mu_h\)</span> (perquè l’interval on estam molt segurs que cau el valor real de la diferència <span class="math inline">\(\mu_d-\mu_h\)</span> contendria valors <span class="math inline">\(\geqslant 0\)</span> i per tant podria ser, dins el nostre marge de seguretat, que <span class="math inline">\(\mu_d-\mu_h\geqslant 0\)</span>).</p></li>
</ul>
<p>Com que aquí voldrem filar més prim que això del “nivell de confiança”, el procediment serà una mica més complicat (bàsicament, emprarem diferents fórmules per calcular els intervals de confiança segons la forma que tengui la hipòtesi alternativa).</p>
<p>Abans de tancar aquesta secció, volem emfatitzar algunes advertències.</p>

<div class="rmdcaution">
Les hipòtesis dels contrastos són sobre paràmetres de les poblacions, NO sobre estadístics de les mostres.
</div>
<p>A l’exemple anterior les hipòtesis del contrast comparaven les mitjanes <strong>poblacionals</strong> d’hores setmanals d’esport de les dones i els homes, no les mitjanes mostrals d’hores setmanals d’esport de les dones i els homes de la nostra mostra.</p>
<p>Per comparar les mitjanes mostrals no ens fa falta un contrast d’hipòtesis: les calculam i punt. En canvi, com que no podem calcular les mitjanes d’hores setmanals d’esport de totes les dones i de tots els homes, ens veiem obligats a emprar estadística i fer un contrast d’hipòtesis.</p>

<div class="rmdcaution">
Recordau que la falta d’evidència a favor de <em>H</em><sub>1</sub> no és evidència a favor de <em>H</em><sub>0</sub>.
</div>
<p>Si no podem concloure que les dones practiquin menys esport que els homes (perquè no hàgim trobat evidència a favor d’aquesta hipòtesi), això no significarà que hàgim trobat evidència que els homes i les dones practiquin la mateixa quantitat d’esport o que les dones en practiquin més. Simplement, significarà que <em>l’evidència a favor de </em>H<em><sub>1</sub> no ha estat prou forta com per poder afirmar que és vertadera</em> i per tant acceptam que tothom practica la mateixa quantitat d’esport.</p>

<div class="rmdcaution">
En general, mai no podrem trobar evidència de la hipòtesi nul·la.
</div>
<p>Si per exemple al nostre estudi haguéssim trobat que <span class="math inline">\(\overline{X}_d=\overline{X}_h\)</span>, això seria compatible amb la hipòtesi nul·la <span class="math inline">\(\mu_d=\mu_h\)</span>, naturalment, i per això no la podríem rebutjar. Però no podem dir que aporti evidència que <span class="math inline">\(\mu_d=\mu_h\)</span>, perquè <span class="math inline">\(\overline{X}_d=\overline{X}_h\)</span> segurament també seria compatible, per exemple, amb <span class="math inline">\(\mu_d=\mu_h+0.0007\)</span> (les dones fan, de mitjana, un minut més d’esport a la setmana que els homes), per tant tampoc no podríem rebutjar com a hipòtesi nul·la que <span class="math inline">\(\mu_d=\mu_h+0.0007\)</span>. I el que no podem dir és que un mateix conjunt de dades aporti simultàniament evidència que <span class="math inline">\(\mu_d=\mu_h\)</span> i que <span class="math inline">\(\mu_d=\mu_h+0.0007\)</span>.</p>

<div class="rmdcaution">
La pregunta (el contrast) us la plantejau <em>a priori</em> a partir d’hipòtesis o suposicions prèvies.
No val canviar de contrast a la vista de les dades.
</div>
<p>La pregunta la plantejam abans d’obtenir la mostra. Si estam interessats en el contrast
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}: \mu_d=\mu_h\\ 
H_{1}:\mu_d&lt;\mu_h
\end{array}
\right.
\]</span>
i obtenim que <span class="math inline">\(\overline{X}_d\)</span> és molt més gran que <span class="math inline">\(\overline{X}_h\)</span> en la nostra mostra, concloem que no tenim evidència que <span class="math inline">\(\mu_d&lt;\mu_h\)</span> i punt. És fer <em>trampes</em> dir: “No hem trobat evidència que les dones practiquin menys esport que els homes, però si amb aquestes mateixes dades realitzam el contrast
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}: \mu_d=\mu_h\\ 
H_{1}:\mu_d&gt;\mu_h
\end{array}
\right.
\]</span>
sí que obtenim evidència que elles practiquen més esport que ells.”</p>
<p>D’això se’n diu “anar a pescar” o també “torturar les dades”: obtenir unes dades i cercar de què donen evidència. És mala praxis científica. Qualsevol conjunt de dades, si el torturam prou, acaba donant evidència de qualque cosa.</p>

<div class="rmdcaution">
Triau la hipòtesi alternativa en funció d’allò que cercau evidència.
</div>
<p>No confongueu
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}: \mu_d=\mu_h\\ 
H_{1}:\mu_d&lt;\mu_h
\end{array}
\right.
\]</span>
amb
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}: \mu_d=\mu_h\\ 
H_{1}:\mu_d\neq \mu_h
\end{array}
\right.
\]</span>
que tradueix la pregunta "Els homes i les dones, de mitjana, practiquen esport un nombre diferent d’hores a la setmana?’’</p>

<div class="rmdimportant">
<p><strong>Regles per triar <em>H</em><sub>0</sub> i <em>H</em><sub>1</sub> en aquest curs</strong>:</p>
<ul>
<li><p><em>H</em><sub>0</sub> sempre ha de significar “no hi ha diferència” i s’ha de definir formalment mitjançant una igualtat</p></li>
<li><p><em>H</em><sub>1</sub> és la hipòtesi de la que cercam evidència, i s’ha de definir formalment mitjançant alguna cosa “estricta”:</p>
<ul>
<li><p><strong>Hipòtesi unilateral</strong> (<em>one-sided</em>; també <strong>d’una cua</strong>, <em>one-tailed</em>): definida amb <strong>&lt;</strong> o amb <strong>&gt;</strong></p></li>
<li><p><strong>Hipòtesi bilateral</strong> (<em>two-sided</em>; també <strong>de dues cues</strong>, <em>two-tailed</em>): definida amb <span class="math inline">\(\neq\)</span></p>
</div></li>
</ul></li>
</ul>
<p>Els contrastos prenen el nom del tipus d’hipòtesi alternativa: <strong>contrast unilateral</strong>, <strong>de dues cues</strong>, etc.</p>
</div>
<div id="sec:moneda" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Un exemple</h2>
<p>Tenc una moneda, i crec que està trucada a favor de cara. Vull contrastar-ho.</p>
<p>Aquí la variable aleatòria <span class="math inline">\(X\)</span> que ens interessa és “Llanç la moneda i anot 1 si surt cara”, que és de Bernoulli amb probabilitat d’èxit (és a dir, probabilitat de treure cara amb la meva moneda) <span class="math inline">\(p_{\mathit{Cara}}\)</span>.</p>
<p>La hipòtesi nul·la serà que la moneda no està trucada (no li passa res a la meva moneda), i l’alternativa (de la que cerc evidència) que la moneda està trucada a favor de cara. En termes de <span class="math inline">\(p_{\mathit{Cara}}\)</span>, el contrast és
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:p_{\mathit{Cara}}= 0.5\\ 
H_{1}:p_{\mathit{Cara}}&gt; 0.5
\end{array}
\right.
\]</span></p>

<div class="example">
<p><span id="exm:unnamed-chunk-349" class="example"><strong>Exemple 5.4  </strong></span>Suposem que llanç la moneda 3 vegades i obtenc 3 cares. És evidència suficient que està trucada?</p>
</div>
<p>Diguem <span class="math inline">\(S_3\)</span> a la variable aleatòria “Nombre de cares en 3 llançaments d’aquesta moneda.”</p>
<p>Si la moneda no està trucada, <span class="math inline">\(S_3\)</span> és binomial B(3,0.5) i per tant
<span class="math display">\[
P(S_3=3)=0.5^{3}=0.125
\]</span></p>
<p>El resultat obtengut no és molt improbable amb una moneda equilibrada: passaria en 1 de cada 8 seqüències de 3 llançaments. Per tant, no és evidència suficient que estigui trucada. No podem rebutjar que sigui equilibrada.</p>

<div class="rmdrecordau">
D’aquest tipus de procediment, emprant la distribució binomial del nombre d’èxits en una mostra aleatòria simple per contrastar un valor de la probabilitat poblacional d’èxit, en direm un <strong>test binomial</strong>.
</div>

<div class="example">
<p><span id="exm:unnamed-chunk-351" class="example"><strong>Exemple 5.5  </strong></span>Suposem que ara llanç la moneda 10 vegades i obtenc 10 cares. És evidència suficient que està trucada?</p>
</div>
<p>Diguem ara <span class="math inline">\(S_{10}\)</span> a la variable aleatòria “Nombre de cares en 10 llançaments.”</p>
<p>Si la moneda no està trucada, <span class="math inline">\(S_{10}\)</span> és B(10,0.5) i per tant
<span class="math display">\[
P(S_{10}=10)=0.5^{10}=0.001
\]</span></p>
<p>El resultat obtengut és molt improbable si la moneda no està trucada: si la moneda fos equilibrada, només en 1 de cada 1000 seqüències de 10 llançaments obtendríem 10 cares. És a dir:</p>
<blockquote>
<p>El resultat del nostre experiment seria molt estrany si la moneda fos equilibrada, per tant és <strong>inversemblant</strong> que sigui equilibrada.</p>
</blockquote>
<p>Ho consideram evidència que està trucada.</p>

<div class="rmdnote">
<p>Fixau-vos en el raonament. Tenim la hipòtesi nul·la i realitzam un experiment per a contrastar-la. Si obtenim un resultat que sembla que la contradiu, una de dues:</p>
<ul>
<li>O la hipòtesi nul·la és falsa.</li>
<li>O la hipòtesi nul·la és vertadera i ha passat una cosa molt rara.</li>
</ul>
<p>Què és el més assenyat concloure? Tenint en compte que les coses molt rares no solen passar, el més assenyat és concloure que la hipòtesi nul·la és falsa.</p>
</div>
<p>Fixau-vos en el procediment:</p>
<ol style="list-style-type: decimal">
<li><p>Hem plantejat el contrast:
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:p_{\mathit{Cara}}= 0.5\\ 
H_{1}:p_{\mathit{Cara}}&gt; 0.5
\end{array}
\right.
\]</span></p></li>
<li><p>Hem recollit una mostra aleatòria: la seqüència de llançaments</p></li>
<li><p>Hem triat un <strong>estadístic de contrast</strong> amb distribució mostral coneguda quan <em>H</em><sub>0</sub> és vertadera: al nostre cas, el nombre de cares</p></li>
<li><p>Hem calculat el valor d’aquest estadístic sobre la nostra mostra</p></li>
<li><p>Hem calculat la probabilitat que l’estadístic prengui el valor observat si <em>H</em><sub>0</sub> és vertadera</p></li>
<li><p>Si aquesta probabilitat és molt petita, ho consideram evidència que <em>H</em><sub>1</sub> és vertadera</p></li>
<li><p>Si no és prou petita, no podem rebutjar que <em>H</em><sub>0</sub> sigui la vertadera</p></li>
</ol>
<p>Bé, això és el que hem fet, però no és del tot correcte. Als punts (5) i (6) diem que: “Calculam la probabilitat que l’estadístic prengui el valor observat si <em>H</em><sub>0</sub> és vertadera; si és molt petita, ho consideram evidència que <em>H</em><sub>1</sub> és vertadera.” <em>Segur que això està bé?</em></p>
<ul>
<li><p>Suposem que, al contrast anterior, llançam la moneda 10 vegades i ara obtenim <em>10 creus</em>. És evidència suficient que està trucada a favor de cara? Òbviament no ho pot ser, però la probabilitat que passi si <em>H</em><sub>0</sub> és vertadera és la mateixa que abans:
<span class="math display">\[
P(S_{10}=0)=0.5^{10}=0.001
\]</span></p></li>
<li><p>En molts casos, <em>la probabilitat d’obtenir exactament el que hem obtengut pot ser molt petita, independentment del que hàgim obtengut</em>. Per exemple, suposem que llançam la moneda 10000 vegades i obtenim 5000 cares. Si la moneda és equilibrada, el nombre de cares seguirà una distribució binomial B(10000,0.5) i la probabilitat d’obtenir 5000 cares serà <code>dbinom(5000,10000,0.5)</code>=0.008, ben petita, però clarament si la meitat de llançaments donen cara, no podem tenir mai evidència que la moneda estigui trucada.</p>
<p>O, encara més exagerat, si l’estadístic de contrast té distribució contínua, la probabilitat que prengui un valor concret és 0. Més petit impossible, però no sempre rebutjarem la hipòtesi nu·la.</p></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-353"></span>
<img src="https://imgs.xkcd.com/comics/null_hypothesis.png" alt="&quot;Null hypothesis&quot; (https://xkcd.com/892/ (CC-BI-NC 2.5))" width="40%" />
<p class="caption">
Figura 5.1: “Null hypothesis” (<a href="https://xkcd.com/892/" class="uri">https://xkcd.com/892/</a> (CC-BI-NC 2.5))
</p>
</div>
<p>Així que:</p>

<div class="rmdrecordau">
En realitat, el que es calcula a (5) és la probabilitat que, si <em>H</em><sub>0</sub> és vertadera, l’estadístic prengui un valor <em>tan extrem o més</em> (en el sentit de <em>H</em><sub>1</sub>) que l’obtengut. A aquesta probabiitat li diem el <strong>p-valor</strong>.
</div>
<p>Al nostre exemple de la moneda, com que la hipòtesi nul·la és <span class="math inline">\(p_{\mathit{Cara}}= 0.5\)</span> i la hipòtesi alternativa és <span class="math inline">\(p_{\mathit{Cara}}&gt; 0.5\)</span>, el p-valor és la probabilitat que, si <span class="math inline">\(p_{\mathit{Cara}}= 0.5\)</span>, el nombre de cares sigui més gran o igual que l’obtengut a la nostra mostra.</p>
<p>En els dos exemples anteriors concrets, on obteníem 3 cares en 3 llançaments i 10 cares en 10 llançaments, és el mateix demanar que el nombre de cares sigui igual a l’obtengut i demanar que el nombre de cares sigui més gran o igual que l’obtengut, perquè en els dos experiments hem obtengut el nombre màxim possible de cares; per exemple, treure 3 o més cares en 3 llançaments és exactament el mateix que treure 3 cares en 3 llançaments. Però en general aquest no serà el cas.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-355" class="example"><strong>Exemple 5.6  </strong></span>Tornem al nostre contrast
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:p_{\mathit{Cara}}= 0.5\\ 
H_{1}:p_{\mathit{Cara}}&gt; 0.5
\end{array}
\right.
\]</span>
Suposem que llanç la moneda 10 vegades i obtenc 7 cares. És evidència suficient que està trucada?</p>
</div>
<p>Seguim dient <span class="math inline">\(S_{10}\)</span> a la variable aleatòria “Nombre de cares en 10 llançaments”, que, si la moneda no està trucada, és B(10,0.5).
Com que la hipòtesi alternativa és <span class="math inline">\(p_{\mathit{Cara}}&gt; 0.5\)</span>, “obtenir un nombre de cares tan extrem o més que el que hem obtengut en el sentit de la hipòtesi alternativa” és <strong>treure tantes cares com les que hem obtengut o més</strong>, és a dir treure 7 o més cares.<br />
Per tant
<span class="math display">\[
\text{p-valor}=P(S_{10}\geqslant 7)=\texttt{1-pbinom(6,10,0.5)}=0.172
\]</span>
Un resultat tan extrem o més que l’obtengut no és molt improbable si la moneda no està trucada: passaria al voltant d’1 de cada 6 ocasions. Per tant, com que és bastant compatible amb el fet que la moneda sigui equilibrada, no ho podem considerar evidència que estigui trucada a favor de cara.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-356" class="example"><strong>Exemple 5.7  </strong></span>Tenc una moneda, i ara crec que està trucada a favor de creu. Vull contrastar-ho. Plantejat en termes de <span class="math inline">\(p_{\mathit{Cara}}\)</span>, el contrast que vull realitzar és
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:p_{\mathit{Cara}}= 0.5\\ 
H_{1}: p_{\mathit{Cara}}&lt; 0.5
\end{array}
\right.
\]</span>
Suposem que llanç la moneda 10 vegades i obtenc 1 cara. És evidència suficient que <span class="math inline">\(p_{\mathit{Cara}}&lt; 0.5\)</span>?</p>
</div>
<p>Seguim dient <span class="math inline">\(S_{10}\)</span> a la variable aleatòria “Nombre de cares en 10 llançaments d’aquesta moneda”, que, si <em>H</em><sub>0</sub> és vertadera, és B(10,0.5).</p>
<p>Ara, com que <em>H</em><sub>1</sub> és <span class="math inline">\(p_{\mathit{Cara}}&lt; 0.5\)</span>, “obtenir un nombre de cares tan extrem o més que el que hem obtengut en el sentit de la hipòtesi alternativa” és <strong>treure tantes cares com les que hem obtengut o menys</strong>, és a dir treure 1 cara o cap. Per tant
<span class="math display">\[
\text{p-valor}=P(S_{10}\leqslant 1)=\texttt{pbinom(1,10,0.5)}=0.01
\]</span>
Un resultat tan extrem o més que l’obtengut és bastant improbable si <span class="math inline">\(p_{\mathit{Cara}}= 0.5\)</span>: passaria en 1 de cada 100 seqüències de 10 llançaments. Ho podem considerar evidència que la moneda està trucada a favor de creu.</p>
</div>
<div id="sec:pval" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> El p-valor</h2>
<p>El <strong>p-valor</strong> d’un contrast és la probabilitat que, si la hipòtesi nul·la és vertadera, l’estadístic de contrast prengui en una mostra aleatòria simple de la mateixa mida que la nostra un valor tan o més extrem, en el sentit de la hipòtesi alternativa, que l’obtengut amb la nostra mostra.</p>
<p>Ho tornarem a repetir, posant èmfasi en els components fonamentals de la definició. El <strong>p-valor</strong> és:</p>
<ul>
<li>La probabilitat que,</li>
<li>si la hipòtesi nul·la és vertadera,</li>
<li>l’estadístic de contrast prengui en una mostra aleatòria simple de la mateixa mida que la nostra</li>
<li>un valor tan o més extrem, en el sentit de la hipòtesi alternativa,</li>
<li>que l’obtengut amb la nostra mostra.</li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-357" class="example"><strong>Exemple 5.8  </strong></span>Suposem que al contrast de les mitjanes d’hores setmanals d’esport d’homes i dones de l’Exemple <a href="chap-chgen.html#exm:esport1">5.3</a> hi empram com a estadístic de contrast la diferència entre les mitjanes mostrals <span class="math inline">\(\overline{X}_d-\overline{X}_h\)</span> (<strong>que no serà el cas: només és com a exemple!</strong>) i que hem pres mostres de 50 dones i de 50 homes, i que la diferència de mitjanes mostrals ha estat -1.2. Aleshores, el p-valor del contrast és</p>
</div>
<ul>
<li><p>La probabilitat que,</p></li>
<li><p>si la hipòtesi nul·la és vertadera,</p>
<p><em>si <span class="math inline">\(\mu_d=\mu_h\)</span>, és a dir, si els homes i les dones practiquen de mitjana el mateix nombre d’hores d’esport a la setmana,</em></p></li>
<li><p>l’estadístic de contrast prengui en una mostra aleatòria simple de la mateixa mida que la nostra</p>
<p><em>el valor de <span class="math inline">\(\overline{X}_d-\overline{X}_h\)</span>, és a dir, de la mitjana mostral d’hores setmanals d’esport en les dones menys la mitjana mostral d’hores setmanals d’esport en els homes, d’una mostra aleatòria formada per 50 dones i 50 homes, sigui</em></p></li>
<li><p>un valor tan o més extrem, en el sentit de la hipòtesi alternativa,</p>
<p><em>més petit o igual</em> (perquè la hipòtesi alternativa és <span class="math inline">\(\mu_d&lt;\mu_h\)</span>, és a dir <span class="math inline">\(\mu_d-\mu_h&lt;0\)</span>)</p></li>
<li><p>que l’obtengut amb la nostra mostra.</p>
<p><em>que el de la nostra mostra, -1.2</em></p></li>
</ul>
<p>En resum, el p-valor seria en aquest cas</p>
<blockquote>
<p>La probabilitat, si <span class="math inline">\(\mu_d=\mu_h\)</span>, que, si prenem una mostra aleatòria de 50 dones i 50 homes, el valor de <span class="math inline">\(\overline{X}_d-\overline{X}_h\)</span> que obtenguem sigui més petit o igual que -1.2:
<span class="math display">\[
P(\overline{X}_d-\overline{X}_h\leqslant -1.2\mid \mu_d=\mu_h)
\]</span></p>
</blockquote>
<p>Si aquesta probabilitat és molt petita, la mostra obtenguda és poc consistent amb la hipòtesi nul·la i per tant conclourem que la hipòtesi alternativa és vertadera. Si, en canvi, aquesta probabilitat no és molt petita, la mostra obtenguda és consistent amb la hipòtesi nul·la i per tant no podrem rebutjar que <em>H</em><sub>0</sub> sigui vertadera.</p>

<div class="rmdimportant">
<p>El p-valor no és:</p>
<ul>
<li><p>La probabilitat que <em>H</em><sub>0</sub> sigui vertadera condicionada al nostre resultat</p></li>
<li><p>La probabilitat que <em>H</em><sub>1</sub> sigui falsa condicionada al nostre resultat</p></li>
</ul>
</div>
<p>És a l’inrevés: El p-valor és la probabilitat del nostre resultat (o quelcom més extrem en el sentit del qual cercam evidència) condicionada al fet que <em>H</em><sub>0</sub> sigui vertadera. Per tant, el p-valor és una <strong>evidencia indirecta inversa</strong> de <em>H</em><sub>1</sub>:</p>
<blockquote>
<p>Com més petit sigui el p-valor, més rar seria el que hem obtengut si <em>H</em><sub>0</sub> fos vertadera i <em>H</em><sub>1</sub> falsa, i per tant més evidència tenim que <em>H</em><sub>0</sub> no pot ser vertadera i que la vertadera és <em>H</em><sub>1</sub>.</p>
</blockquote>
<p>Per exemple, que el p-valor d’un contrast doni 0.03</p>
<ul>
<li><p><strong>Significa</strong> que, si <em>H</em><sub>0</sub> és vertadera, la probabilitat que l’estadístic de contrast prengui sobre una mostra un valor tan extrem o més que el que hem obtengut és 0.03</p>
<ul>
<li><p><em>La trobau petita?</em> Ho preneu com a evidència que <em>H</em><sub>0</sub> és falsa i <em>H</em><sub>1</sub> vertadera</p></li>
<li><p><em>No la trobau petita?</em> No teniu evidència per rebutjar que <em>H</em><sub>0</sub> sigui vertadera</p></li>
</ul></li>
<li><p><strong>No significa</strong> que:</p>
<ul>
<li><p>La probabilitat que <em>H</em><sub>0</sub> sigui vertadera és 0.03</p></li>
<li><p><em>H</em><sub>0</sub> és vertadera un 3% de les vegades</p></li>
</ul></li>
</ul>

<div class="rmdimportant">
En un contrast d’hipòtesis no obtenim cap informació directa sobre la probabilitat de <em>H</em><sub>0</sub> o de <em>H</em><sub>1</sub>.
</div>

<div class="example">
<p><span id="exm:unnamed-chunk-360" class="example"><strong>Exemple 5.9  </strong></span>Tenc una moneda i vull saber si està trucada; a favor de cara o a favor de creu, m’és igual, només vull saber si està trucada. Ho decidiré amb un contrast.</p>
</div>
<p>Plantejat en termes de la probabilitat de treure cara <span class="math inline">\(p_{\mathit{Cara}}\)</span>, el contrast que vull realitzar ara és
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:p_{\mathit{Cara}}= 0.5\\ 
H_{1}:p_{\mathit{Cara}}\neq 0.5
\end{array}
\right.
\]</span>
Suposem que la llanç 10 vegades i obtenc 8 cares. És evidència suficient que està trucada?</p>
<p>Com a la secció anterior, diguem <span class="math inline">\(S_{10}\)</span> a la variable “Nombre de cares en 10 llançaments”. Si <span class="math inline">\(p_{\mathit{Cara}}= 0.5\)</span>, <span class="math inline">\(S_{10}\)</span> és B(10,0.5).</p>
<p>Si la hipòtesi nul·la fos vertadera, esperaríem treure 5 cares i 5 creus. Com que la hipòtesi alternativa és <span class="math inline">\(H_{1}:p_{\mathit{Cara}}\neq 0.5\)</span>, ara “obtenir un resultat tan o més extrem, en el sentit de la hipòtesi alternativa, que l’obtengut” és treure un resultat <em>tant o més diferent de 5 cares i 5 creus que l’obtengut</em>: és a dir, treure almenys 8 cares o almenys 8 creus, o el que és el mateix, treure com a mínim 8 cares o com a màxim 2 cares. Per tant, el p-valor és
<span class="math display">\[
\begin{array}{l}
P(S_{10}\geqslant 8\text{ o }S_{10}\leqslant 2) =P(S_{10}\geqslant 8) + P(S_{10}\leqslant 2)\\
\qquad =1-P(S_{10}\leqslant 7) + P(S_{10}\leqslant 2)\\
\qquad =\texttt{1-pbinom(7,10,0.5)+pbinom(2,10,0.5)}\\
\qquad =0.11
\end{array}
\]</span></p>
<p>Per tant, si la moneda no està trucada, un resultat com l’obtengut o més llunyà de “meitat cares, meitat creus” és improbable, però no gaire (1 de cada 9 vegades passaria). És evidència suficient que estigui trucada? Quin p-valor marca el llindar de l’inversemblança de <em>H</em><sub>0</sub>?</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-361"></span>
<img src="Bioestadistica-II_files/figure-html/worship.png" alt="No adorareu falsos déus." width="50%" />
<p class="caption">
Figura 5.2: No adorareu falsos déus.
</p>
</div>
<p>La resposta és que depèn de quant estiguem disposats a equivocar-nos.</p>
</div>
<div id="tipus-derrors" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Tipus d’errors</h2>
<p>La comparació entre la realitat i la decisió resultant d’un contrast dóna lloc a quatre situacions possibles, resumides en la taula següent:</p>
<p><img src="Bioestadistica-II_files/figure-html/errors.png" width="75%" style="display: block; margin: auto;" /></p>
<ul>
<li><p><em>H</em><sub>0</sub> és la vertadera a la realitat i nosaltres decidim que <em>H</em><sub>1</sub> és vertadera*.</p>
<ul>
<li><p>La conclusió del contrast és errònia. En diem <strong>error de tipus I</strong> o <strong>positiu fals</strong>.</p></li>
<li><p>Indicarem amb <span class="math inline">\(\alpha\)</span> la probabilitat de cometre un error de tipus I, és a dir, de rebutjar <em>H</em><sub>0</sub> si és vertadera, i en direm el <strong>nivell de significació</strong>:
<span class="math display">\[
\alpha=P(\text{Rebutjar } H_0| H_0\text{ vertadera}).
\]</span></p></li>
</ul></li>
<li><p><em>H</em><sub>1</sub> és vertadera a la realitat i nosaltres acceptam <em>H</em><sub>0</sub>*.</p>
<ul>
<li><p>La conclusió del contrast és errònia. En diem <strong>error de tipus II</strong> o <strong>negatiu fals</strong>.</p></li>
<li><p>Indicarem amb <span class="math inline">\(\beta\)</span> la probabilitat de cometre un error de tipus II, és a dir, d’acceptar <em>H</em><sub>0</sub> si <em>H</em><sub>1</sub> és vertadera,:
<span class="math display">\[
\beta=P(\text{Acceptar } H_0| H_1\text{ vertadera}).
\]</span></p></li>
</ul></li>
<li><p><em>H</em><sub>1</sub> és vertadera a la realitat i nosaltres decidim que <em>H</em><sub>1</sub> és vertadera*.</p>
<ul>
<li><p>La conclusió del contrast és correcta. En diem un <strong>positiu vertader</strong>.</p></li>
<li><p>La probabilitat d’encertar amb un positiu vertader és <span class="math inline">\(1-\beta\)</span> i en direm la <strong>potència</strong>:</p></li>
</ul></li>
</ul>
<p><span class="math display">\[
1-\beta=P(\text{Rebutjar } H_0| H_1\text{ vertadera}).
\]</span></p>
<ul>
<li><p><em>H</em><sub>0</sub> és la vertadera a la realitat i nosaltres l’acceptam*.</p>
<ul>
<li><p>La conclusió del contrast és correcta. En diem un <strong>negatiu vertader</strong>.</p></li>
<li><p>La probabilitat d’encertar amb un negatiu vertader és <span class="math inline">\(1-\alpha\)</span> i en direm el <strong>nivell de confiança</strong>:
<span class="math display">\[
1-\alpha=P(\text{Acceptar } H_0| H_0\text{ vertadera}).
\]</span></p></li>
</ul></li>
</ul>

<div class="rmdrecordau">
<p>En el context d’un contrast d’hipòtesis,</p>
<ul>
<li><p>un resultat <strong>positiu</strong> és rebutjar la hipòtesi nul·la i decidir que l’alternativa és la vertadera (hem trobat qualque cosa)</p></li>
<li><p>un resultat <strong>negatiu</strong> és acceptar la hipòtesi nul·la (no hem trobat res i ens hem de conformar amb la hipòtesi nul·la)</p></li>
</ul>
</div>
<p>Ho tornam a repetir:</p>
<ul>
<li><p>El <strong>nivell de significació</strong>, <span class="math inline">\(\alpha\)</span>, d’un contrast és la probabilitat que, <strong>si</strong> la hipòtesi nul·la és vertadera, nosaltres ens equivoquem i la rebutgem a favor de l’alternativa:
<span class="math display">\[
\alpha=P(\text{Rebutjar } H_0| H_0\text{ vertadera}).
\]</span>
Per tant, és una probabilitat d’error.</p></li>
<li><p>La <strong>potència</strong>, <span class="math inline">\(1-\beta\)</span>, d’un contrast és la probabilitat que, <strong>si</strong> la hipòtesi alternativa és vertadera, nosaltres ho detectem i rebutgem la hipòtesi nul·la a favor de l’alternativa:
<span class="math display">\[
1-\beta=P(\text{Rebutjar } H_0| H_1\text{ vertadera}).
\]</span>
Per tant, és una probabilitat d’encert.</p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-364" class="example"><strong>Exemple 5.10  </strong></span>En un test d’embaràs, el contrast que es realitza és:
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:\text{No estàs embarassada}\\ 
H_{1}:\text{Estàs embarassada}
\end{array}
\right.
\]</span></p>
</div>
<p><img src="Bioestadistica-II_files/figure-html/types.png" width="60%" style="display: block; margin: auto;" /></p>

<div class="example">
<p><span id="exm:unnamed-chunk-366" class="example"><strong>Exemple 5.11  </strong></span>En un judici, on s’ha de declarar un acusat innocent o culpable, el contrast era
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:\text{L&#39;acusat és innocent}\\ 
H_{1}:\text{L&#39;acusat és culpable}
\end{array}
\right.
\]</span></p>
</div>
<p>Es poden cometre dos errors:</p>
<ul>
<li><p><em>Error de tipus I</em>: Declarar culpable un innocent</p></li>
<li><p><em>Error de tipus II</em>: Declarar no culpable un culpable</p></li>
</ul>
<p>És pitjor l’error de tipus I, convé minimitzar-lo. Per això només es declara qualcú culpable quan les proves ho demostren més enllà de qualsevol dubte raonable.</p>

<div class="example">
<span id="exm:unnamed-chunk-367" class="example"><strong>Exemple 5.12  </strong></span>En un examen, el contrast era
<span class="math display">\[
\left\{\begin{array}{ll} 
H_{0}:\text{L&#39;estudiant no sap la matèria}\\ 
H_{1}:\text{L&#39;estudiant sap la matèria}
\end{array}
\right.
\]</span>
</div>
<p>Es poden donar dos errors:</p>
<ul>
<li><p>Que l’estudiant aprovi sense saber la matèria</p></li>
<li><p>Que l’estudiant suspengui sabent la matèria</p></li>
</ul>

<div class="rmdexercici">
Quin és el de tipus I i quin el de tipus II? Quin creieu que és pitjor?
</div>
<p>Normalment, es considera pitjor cometre un error de tipus I que cometre un error de tipus II. Per tant, l’objectiu primari en un contrast és trobar una regla de rebuig de <em>H</em><sub>0</sub> que tengui poca probabilitat <span class="math inline">\(\alpha\)</span> d’error de tipus I. Però també voldríem minimitzar la probabilitat <span class="math inline">\(\beta\)</span> d’error de tipus II. El problema és que quan fem disminuir <span class="math inline">\(\alpha\)</span>, sol augmentar <span class="math inline">\(\beta\)</span>. Per disminuir <span class="math inline">\(\alpha\)</span>, fem més difícil rebutjar la hipòtesi nul·la, i això fa que augmenti la probabilitat d’acceptar-la encara que sigui falsa.</p>
<p><img src="Bioestadistica-II_files/figure-html/columpio.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Què se sol fer?</p>
<ol style="list-style-type: decimal">
<li>Donar una regla de decisió per a un <span class="math inline">\(\alpha\)</span> màxim fixat.</li>
</ol>

<div class="rmdimportant">
És costum prendre <span class="math inline">\(\alpha=0.05\)</span>: una mica menys que la probabilitat de treure 4 cares seguides amb una moneda equilibrada.
</div>
<ol start="2" style="list-style-type: decimal">
<li>Després, augmentar la mida <span class="math inline">\(n\)</span> de la mostra per arribar a la <span class="math inline">\(\beta\)</span> desitjada.</li>
</ol>
<p>Abans d’acabar amb els errors, fixau-vos que si efectuam <span class="math inline">\(M\)</span> contrastos (independents) emprant una regla de decisió que garanteixi un nivell de significació <span class="math inline">\(\alpha\)</span> fixat, i a tots aquests contrastos la <em>H</em><sub>0</sub> és vertadera, el nombre de contrastos d’aquests on ens equivocarem i rebutjarem <em>H</em><sub>0</sub> té distribució binomial B(M,<span class="math inline">\(\alpha\)</span>). En concret, prenent el nivell de significació usual <span class="math inline">\(\alpha=0.05\)</span>, acceptam una probabilitat d’equivocar-nos rebutjant <em>H</em><sub>0</sub> a favor de <em>H</em><sub>1</sub> de 0.05. És a dir, assumim que, de mitjana, la nostra conclusió serà equivocada en 1 de cada 20 pics que la hipòtesi nul·la sigui vertadera.</p>

<div class="rmdcaution">
Si efectuam molts contrastos, augmenta la probabilitat de “trobar qualque cosa” encara que no hi hagi res que trobar, i acabar dient que les gominoles verdes curen l’acné:
</div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-372"></span>
<img src="http://imgs.xkcd.com/comics/significant.png" alt="&quot;Significant&quot; (https://xkcd.com/882/ (CC-BY-NC 2.5))" width="50%" />
<p class="caption">
Figura 5.3: “Significant” (<a href="https://xkcd.com/882/" class="uri">https://xkcd.com/882/</a> (CC-BY-NC 2.5))
</p>
</div>
</div>
<div id="sec:exttest" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Exemple: El test t</h2>
<p>La concentració mitjana de calci en plasma en homes sans de 22 a 44 anys és de 2.5 mmol/l. Ens demanam si els homes joves amb diabetis tenen una concentració de calci en plasma superior a la dels homes joves sans. Ho traduirem en un contrast d’hipòtesis sobre la concentració mitjana de calci en plasma en els homes joves diabètics, diguem-li <span class="math inline">\(\mu\)</span>:</p>
<ul>
<li><p>La hipòtesi nul·la serà que no hi ha diferència entre <span class="math inline">\(\mu\)</span> i la concentració mitjana de calci en plasma en els homes joves sans, és a dir, que <span class="math inline">\(\mu=2.5\)</span>.</p></li>
<li><p>La hipòtesi alternativa és d’allò que cercam evidència: que <span class="math inline">\(\mu\)</span> és més gran que la concentració mitjana de calci en plasma en els homes joves sans, és a dir, que <span class="math inline">\(\mu&gt;2.5\)</span>.</p></li>
</ul>
<p>Per tant, el contrast que volem realitzar és
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=2.5\\ 
H_{1}:\mu &gt;2.5
\end{array}
\right.
\]</span></p>
<p>Diguem <span class="math inline">\(X\)</span> a la variable aleatòria “Prenem un home diabètic de 22 a 44 anys i li mesuram la concentració de calci en plasma en mmol/l”. Se sap que la concentració de calci en plasma en homes sans segueix una llei aproximadament normal, així que suposarem que la nostra <span class="math inline">\(X\)</span> també és normal.</p>
<p>En una mostra de 20 diabètics d’aquesta franja d’edat, es va obtenir una concentració mitjana de calci <span class="math inline">\(\overline{X}=3.2\)</span> mmol/l amb una desviació típica mostral <span class="math inline">\(\widetilde{S}_X=1.5\)</span>. Suposem que aquesta mostra de diabètics joves és representativa i que la podem considerar aleatòria.</p>
<p>La nostra situació, doncs, és un cas particular del cas general següent. Tenim una variable aleatòria poblacional <span class="math inline">\(X\)</span> normal de mitjana <span class="math inline">\(\mu\)</span> i plantejam el contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu &gt;\mu_0
\end{array}
\right.
\]</span>
per a un valor concret <span class="math inline">\(\mu_0\)</span>. Volem prendre una decisió a partir d’una mostra aleatòria simple.</p>
<p>En aquesta situació, si <em>H</em><sub>0</sub> és vertadera, és a dir, si la mitjana de <span class="math inline">\(X\)</span> és <span class="math inline">\(\mu_0\)</span>, sabem que
<span class="math display">\[
T=\frac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}
\]</span>
té distribució <span class="math inline">\(t_{n-1}\)</span>.</p>
<p>La idea que guiarà el procediment per prendre una decisió en aquest contrast serà:</p>
<blockquote>
<p>Rebutjarem <em>H</em><sub>0</sub> a favor de <em>H</em><sub>1</sub> si aquest <em>estadístic de contrast</em> <span class="math inline">\(T\)</span> pren un valor “molt gran” sobre la mostra, és a dir, si <span class="math inline">\(\overline{X}\)</span> és “molts errors típics” més gran que <span class="math inline">\(\mu_0\)</span>.</p>
</blockquote>
<p>La definició precisa de “molt gran” dependrà del valor d’<span class="math inline">\(\alpha\)</span> que volguem prendre, és a dir, de la probabilitat de cometre un error de tipus I que estiguem disposats a assumir: quant més petit volguem que sigui <span class="math inline">\(\alpha\)</span>, més gran haurà de ser l’evidència a favor de <span class="math inline">\(\mu&gt;\mu_0\)</span>, és a dir, més gran haurà de ser <span class="math inline">\(T\)</span>. Aquí prendrem el valor usual <span class="math inline">\(\alpha=0.05\)</span>: acceptam que tenim una probabilitat del 5% que, si la hipòtesi nul·la és vertadera, la nostra conclusió sigui que és falsa.</p>
<p>Sigui <span class="math inline">\(T_0\)</span> el valor que pren l’estadístic de contrast <span class="math inline">\(T\)</span> en la nostra mostra. Rebutjarem <em>H</em><sub>0</sub> si <span class="math inline">\(T_0\)</span> és més gran que un cert llindar <span class="math inline">\(L_0\)</span>, que determinam a partir de <span class="math inline">\(\alpha\)</span>. Per fer-ho, igualarem a <span class="math inline">\(\alpha\)</span> la probabilitat que <span class="math inline">\(T&gt; L_0\)</span> si la hipòtesi nul·la és vertadera, cas en el qual <span class="math inline">\(T\)</span> té distribució <span class="math inline">\(t_{n-1}\)</span>, i aïllarem <span class="math inline">\(L_0\)</span>.</p>
<p><span class="math display">\[
\begin{array}{l}
\alpha = P(\text{Rebutjar } H_{0}| H_{0} \text{ certa})=P(T&gt; L_0)\\
\qquad\quad \Longleftrightarrow 1-\alpha= P(T\leqslant L_0)\Longleftrightarrow 
L_0= t_{n-1,1-\alpha}
\end{array}
\]</span></p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-373-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Per tant, a fi que el nivell de significació del contrast sigui <span class="math inline">\(\alpha\)</span>,</p>
<blockquote>
<p>Rebutjarem <em>H</em><sub>0</sub> si <span class="math inline">\(T_0&gt;t_{n-1,1-\alpha}\)</span></p>
</blockquote>
<p>En direm una <strong>regla de rebuig</strong> per aquest tipus de contrast.</p>
<p>Tornem al nostre exemple dels diabètics
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=2.5\\ 
H_{1}:\mu &gt; 2.5
\end{array}
\right.
\]</span>
Si <span class="math inline">\(\alpha=0.05\)</span> i <span class="math inline">\(n=20\)</span>, el llindar a partir del qual rebutjam <em>H</em><sub>0</sub> és <span class="math inline">\(t_{n-1,1-\alpha}=t_{19,0.95}=\texttt{qt(0.95,19)}=1.73\)</span>.</p>
<p>A la nostra mostra hi tenim que <span class="math inline">\(\overline{X}=3.2\)</span>, <span class="math inline">\(\widetilde{S}_X=1.5\)</span> i <span class="math inline">\(n=20\)</span>, per tant l’estadístic de contrast val
<span class="math display">\[
T_0=\frac{3.2-2.5}{1.5/\sqrt{20}}=2.09
\]</span></p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-374-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Com que <span class="math inline">\(2.09&gt;1.73\)</span>, <em>concloem amb un nivell de significació de 0.05 que el nivell mitjà de calci en sang en els joves diabètics és més gran que en els joves sans.</em></p>
<p>Vegem ara com entra en joc el p-valor. Recordem que rebutjarem <em>H</em><sub>0</sub> quan <span class="math inline">\(T_0&gt;t_{n-1,1-\alpha}\)</span>:
<span class="math display">\[
\begin{array}{l}
\text{Rebutjarem } H_0 \Longleftrightarrow T_0&gt; t_{n-1,1-\alpha}\\
\qquad \Longleftrightarrow P(T\geqslant T_0)&lt; P(T\geqslant t_{n-1,1-\alpha})\\
\qquad \Longleftrightarrow P(T\geqslant T_0)&lt; 1-P(T\leqslant t_{n-1,1-\alpha})=1-(1-\alpha)=\alpha\\
\qquad \Longleftrightarrow P(T\geqslant T_0)&lt;\alpha
\end{array}
\]</span></p>
<p>I ara observau que <span class="math inline">\(P(T\geqslant T_0)\)</span> és la probabilitat que, si <em>H</em><sub>0</sub> és vertadera, l’estadístic de contrast <span class="math inline">\(T\)</span> prengui un valor tan extrem o més, en el sentit de <span class="math inline">\(H_1: \mu&gt;2.5\)</span>, que l’obtengut en la nostra mostra, <span class="math inline">\(T_0\)</span>: és el <strong>p-valor</strong> del contrast. Per tant, tenim una altra regla de rebuig (equivalent a l’anterior):</p>
<blockquote>
<p>Rebutjarem <em>H</em><sub>0</sub> quan el p-valor sigui més petit que <span class="math inline">\(\alpha\)</span></p>
</blockquote>
<p>En el nostre exemple, ja hem calculat <span class="math inline">\(T_0=2.09\)</span>. Llavors,
<span class="math display">\[
\text{p-valor}  =P(T\geqslant 2.09)=\texttt{1-pt(2.09,19)} =0.025
\]</span>
Com que el p-valor és més petit que 0.05,</p>
<blockquote>
<p>Concloem amb un nivell de significació de 0.05 que el nivell mitjà de calci en sang en els joves diabètics és més gran que en els sans.</p>
</blockquote>
<p>Això se sol expressar dient que:</p>
<blockquote>
<p>Hem obtengut evidència estadísticament significativa que el nivell mitjà de calci en plasma en els joves diabètics és més gran que en els joves sans.</p>
</blockquote>
<p><img src="Bioestadistica-II_files/figure-html/pfm.png" width="35%" style="display: block; margin: auto;" /></p>

<div class="rmdrecordau">
D’aquest tipus de procediment per comparar la <span class="math inline">\(\mu\)</span> d’una variable amb un valor donat <span class="math inline">\(\mu_0\)</span>, emprant que
<span class="math display">\[
T=\frac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}
\]</span>
té distribució t de Student amb <span class="math inline">\(n-1\)</span> graus de llibertat, <span class="math inline">\(t_{n-1}\)</span>, se’n diu un <strong>test t</strong>. Com explicarem al pròxim tema, podem emprar un test t per contrastar una mitjana quan la variable poblacional és normal i també quan la variable poblacional no és normal però la mostra és prou gran (posem, <span class="math inline">\(n\geqslant 40\)</span>).
</div>
<p>Fixau-vos que la nostra conclusió ha estat que “concloem amb un <em>nivell de significació de 0.05</em> que el nivell mitjà de calci en sang en els joves diabètics és més gran que en els joves sans.”</p>
<p>Per tant, <em>reconeixem una probabilitat d’haver-nos equivocat del 5%</em>: Si en realitat el nivell mitjà de calci en sang en els joves diabètics és el mateix que en els sans, la probabilitat que teníem d’equivocar-nos i concloure que el nivell mitjà de calci en sang en els joves diabètics és més gran que en els sans és del 5%.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-377" class="example"><strong>Exemple 5.13  </strong></span>Anem a estudiar aquesta taxa d’encerts per mitjà d’una simulació.</p>
</div>
<p>Primer suposarem que el nivell mitjà real és 2.5, i simularem la probabilitat d’error de tipus I. Com que estam fent el contrast amb nivell de significació 0.05, esperam al voltant d’un 5% d’errors de tipus I. Per fixar idees, modelarem la població de joves diabètics per mitjà d’una variable aleatòria <span class="math inline">\(N(2.5,0.5)\)</span>. La <span class="math inline">\(\sigma=0.5\)</span> ens l’hem inventada. Aprofitam per fixar la llavor d’aleatorietat.</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="chap-chgen.html#cb222-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb222-2"><a href="chap-chgen.html#cb222-2" aria-hidden="true" tabindex="-1"></a>mu0<span class="ot">=</span><span class="fl">2.5</span></span>
<span id="cb222-3"><a href="chap-chgen.html#cb222-3" aria-hidden="true" tabindex="-1"></a>sigma0<span class="ot">=</span><span class="fl">0.5</span></span></code></pre></div>
<p>El llindar <span class="math inline">\(L_0\)</span> per <span class="math inline">\(n=20\)</span> i <span class="math inline">\(\alpha=0.05\)</span> és</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="chap-chgen.html#cb223-1" aria-hidden="true" tabindex="-1"></a>L0<span class="ot">=</span><span class="fu">qt</span>(<span class="fl">0.95</span>,<span class="dv">19</span>)</span>
<span id="cb223-2"><a href="chap-chgen.html#cb223-2" aria-hidden="true" tabindex="-1"></a>L0</span></code></pre></div>
<pre><code>## [1] 1.729133</code></pre>
<p>La funció <code>estadístic</code> següent pren una mostra aleatòria de mida <span class="math inline">\(n\)</span> d’una variable <span class="math inline">\(N(\mu, \sigma)\)</span> i en calcula l’estadístic de contrast <span class="math inline">\(T\)</span>:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="chap-chgen.html#cb225-1" aria-hidden="true" tabindex="-1"></a>estadístic<span class="ot">=</span><span class="cf">function</span>(n,mu,sigma){</span>
<span id="cb225-2"><a href="chap-chgen.html#cb225-2" aria-hidden="true" tabindex="-1"></a>mostra<span class="ot">=</span><span class="fu">rnorm</span>(n,mu,sigma) </span>
<span id="cb225-3"><a href="chap-chgen.html#cb225-3" aria-hidden="true" tabindex="-1"></a>(<span class="fu">mean</span>(mostra)<span class="sc">-</span>mu0)<span class="sc">/</span>(<span class="fu">sd</span>(mostra)<span class="sc">/</span><span class="fu">sqrt</span>(n))</span>
<span id="cb225-4"><a href="chap-chgen.html#cb225-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Ara, repetim 200 vegades el procés de prendre una mostra aleatòria de mida 20 de la nostra població i calcular la <span class="math inline">\(T\)</span> corresponent. Després miram la proporció de vegades que això ha donat més gran que el llindar <span class="math inline">\(L_0\)</span>, és a dir, la proporció de vegades que rebutjam la hipòtesi nul·la <span class="math inline">\(\mu=2.5\)</span> i que per tant cometem un error de tipus I.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="chap-chgen.html#cb226-1" aria-hidden="true" tabindex="-1"></a>Tes<span class="ot">=</span><span class="fu">replicate</span>(<span class="dv">200</span>,estadístic(<span class="dv">20</span>,mu0,sigma0))</span>
<span id="cb226-2"><a href="chap-chgen.html#cb226-2" aria-hidden="true" tabindex="-1"></a>p.error.Tipus.I<span class="ot">=</span><span class="fu">length</span>(Tes[Tes<span class="sc">&gt;</span>L0])<span class="sc">/</span><span class="dv">200</span></span>
<span id="cb226-3"><a href="chap-chgen.html#cb226-3" aria-hidden="true" tabindex="-1"></a>p.error.Tipus.I</span></code></pre></div>
<pre><code>## [1] 0.05</code></pre>
<p>Hem comès exactament un 5% d’errors de tipus I!</p>
<p>Ara suposarem que el nivell mitjà real és estrictament més gran que 2.5, i anam a simular els errors de tipus II, per veure amb quina freqüència els cometem. Per començar, generam un vector de 100 <span class="math inline">\(\mu\)</span>’s entre 2.6 i 3, de manera que tots els valors tenguin la mateixa probabilitat de sortir.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="chap-chgen.html#cb228-1" aria-hidden="true" tabindex="-1"></a>mus<span class="ot">=</span><span class="fu">runif</span>(<span class="dv">100</span>,<span class="fl">2.6</span>,<span class="dv">3</span>)</span></code></pre></div>
<p>I ara el que farem serà el següent. Per a cada <span class="math inline">\(\mu_i\)</span> d’aquest vector, prendrem com a “població de diabètics” una variable <span class="math inline">\(N(\mu_i,0.5)\)</span>. A continuació, per a cada una d’aquestes poblacions, repetirem 200 vegades el procés de prendre una mostra aleatòria simple de mida 20 d’aquesta població i calcular la <span class="math inline">\(T\)</span> corresponent. Després, per a cada població, calcularem la proporció de vegades que això ha donat més petit o igual que el llindar, és a dir, la proporció de vegades que acceptam la hipòtesi nul·la <span class="math inline">\(\mu=2.5\)</span> i que per tant cometem un error de tipus II. Organitzarem totes aquestes proporcions en un vector <strong>p.error.Tipus.II</strong>.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="chap-chgen.html#cb229-1" aria-hidden="true" tabindex="-1"></a>p.error.Tipus.II<span class="ot">=</span><span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">100</span>)</span>
<span id="cb229-2"><a href="chap-chgen.html#cb229-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb229-3"><a href="chap-chgen.html#cb229-3" aria-hidden="true" tabindex="-1"></a>  Tes<span class="ot">=</span><span class="fu">replicate</span>(<span class="dv">200</span>,estadístic(<span class="dv">20</span>,mus[j],sigma0))    </span>
<span id="cb229-4"><a href="chap-chgen.html#cb229-4" aria-hidden="true" tabindex="-1"></a>  p.error.Tipus.II[j]<span class="ot">=</span><span class="fu">round</span>(<span class="fu">length</span>(Tes[Tes<span class="sc">&lt;=</span>L0])<span class="sc">/</span><span class="dv">200</span>,<span class="dv">2</span>)</span>
<span id="cb229-5"><a href="chap-chgen.html#cb229-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb229-6"><a href="chap-chgen.html#cb229-6" aria-hidden="true" tabindex="-1"></a>p.error.Tipus.II</span></code></pre></div>
<pre><code>##   [1] 0.24 0.36 0.52 0.53 0.31 0.04 0.08 0.09 0.78 0.68 0.62 0.00 0.10 0.12 0.65
##  [16] 0.01 0.04 0.62 0.57 0.10 0.58 0.25 0.30 0.00 0.29 0.48 0.26 0.00 0.09 0.66
##  [31] 0.07 0.08 0.79 0.03 0.03 0.00 0.00 0.56 0.52 0.23 0.72 0.04 0.70 0.77 0.74
##  [46] 0.70 0.06 0.15 0.06 0.48 0.00 0.04 0.10 0.01 0.01 0.00 0.35 0.60 0.58 0.64
##  [61] 0.08 0.38 0.09 0.40 0.78 0.02 0.03 0.66 0.47 0.27 0.18 0.05 0.59 0.01 0.04
##  [76] 0.44 0.33 0.34 0.66 0.01 0.10 0.68 0.73 0.74 0.21 0.07 0.18 0.69 0.01 0.32
##  [91] 0.06 0.64 0.66 0.27 0.08 0.49 0.20 0.01 0.10 0.42</code></pre>
<p>En alguns casos no hem comès cap error, i en uns altres la majoria de conclusions han estat errònies. La proporció mitjana d’errors de tipus II ha estat:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="chap-chgen.html#cb231-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(p.error.Tipus.II)</span></code></pre></div>
<pre><code>## [1] 0.3092</code></pre>
<p>Si prenem mostres més grans, la probabilitat d’error de tipus II disminueix. Comprovem-ho repetint aquest segon experiment amb mostres de mida 200.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="chap-chgen.html#cb233-1" aria-hidden="true" tabindex="-1"></a>p.error.Tipus.II<span class="fl">.200</span><span class="ot">=</span><span class="fu">rep</span>(<span class="dv">1</span>,<span class="dv">100</span>)</span>
<span id="cb233-2"><a href="chap-chgen.html#cb233-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>){</span>
<span id="cb233-3"><a href="chap-chgen.html#cb233-3" aria-hidden="true" tabindex="-1"></a>Tes<span class="ot">=</span><span class="fu">replicate</span>(<span class="dv">200</span>,estadístic(<span class="dv">200</span>,mus[j],sigma0))    </span>
<span id="cb233-4"><a href="chap-chgen.html#cb233-4" aria-hidden="true" tabindex="-1"></a>  p.error.Tipus.II<span class="fl">.200</span>[j]<span class="ot">=</span><span class="fu">round</span>(<span class="fu">length</span>(<span class="fu">which</span>((Tes<span class="sc">&lt;=</span>L0)<span class="sc">==</span><span class="cn">TRUE</span>))<span class="sc">/</span><span class="dv">200</span>,<span class="dv">2</span>)</span>
<span id="cb233-5"><a href="chap-chgen.html#cb233-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb233-6"><a href="chap-chgen.html#cb233-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(p.error.Tipus.II<span class="fl">.200</span>)</span></code></pre></div>
<pre><code>## [1] 0.0078</code></pre>
<p>Multiplicant per 10 la mida de les mostres, hem baixat d’una taxa d’errors de tipus II del 30.92% al 0.78%.</p>
<p>Recordau que la <strong>potència</strong> d’un contrast és la probabilitat de <em>no</em> cometre un error de tipus II. Hem vist que prenent mostres més grans, la proporció d’errors de tipus II ha disminuït. Això és general:</p>

<div class="rmdimportant">
Si fixam el nivell de significació, com més grans són les mostres, més gran és la potència del contrast.
</div>
<p>Tornem a la situació general en la que tenim una variable aleatòria <span class="math inline">\(X\)</span> normal i volem comparar la seva mitjana <span class="math inline">\(\mu\)</span> amb un cert valor <span class="math inline">\(\mu_0\)</span> i suposem que ara cercam evidència que <span class="math inline">\(\mu&lt;\mu_0\)</span>, de manera que el contrast és
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu &lt; \mu_0
\end{array}
\right.
\]</span>
En aquest cas, el p-valor és <span class="math inline">\(P(T\leqslant T_0)\)</span> i, raonant exactament igual com abans, obtenim les dues regles de rebuig equivalents següents:</p>
<blockquote>
<p>Rebutjarem <em>H</em><sub>0</sub> si <span class="math inline">\(T_0&lt; t_{n-1,\alpha}\)</span><br />
Rebutjarem <em>H</em><sub>0</sub> si el p-valor és més petit que <span class="math inline">\(\alpha\)</span></p>
</blockquote>
<p>I què passa si ara cercam evidència que <span class="math inline">\(\mu\)</span> és <em>diferent</em> de <span class="math inline">\(\mu_0\)</span>? És a dir, si tenim el contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu\ \neq  \mu_0
\end{array}
\right.
\]</span></p>
<p>En aquest cas, rebutjarem <em>H</em><sub>0</sub> quan <span class="math inline">\(\overline{X}\)</span> és prou diferent de <span class="math inline">\(\mu_0\)</span>, per damunt o per davall de <span class="math inline">\(\mu_0\)</span>, i això ho traduïm en que rebutjarem <em>H</em><sub>0</sub> quan <span class="math inline">\(|T_0|\)</span> (el valor absolut de <span class="math inline">\(T_0\)</span>) sigui més gran que un cert llindar <span class="math inline">\(L_0\)</span>, que determinam a partir de <span class="math inline">\(\alpha\)</span> com abans:</p>
<p><span class="math display">\[
\begin{array}{l}
\alpha = P(\text{Rebutjar } H_{0}| H_{0} \text{ certa})=P(|T|&gt; L_0)\\
\hphantom{\alpha} = P(T&lt; -L_0\text{ o } T&gt;L_0)= P(T&lt; -L_0)+P(T&gt;L_0)\\
\hphantom{\alpha} =2P(T&gt;L_0) \text{ (per la simetria de $t_{n-1}$)}\\
 \Longleftrightarrow \alpha/2=P(T&gt;L_0)= 1-P(T\leqslant L_0) \\
\Longleftrightarrow P(T\leqslant L_0)=1-\alpha/2\Longleftrightarrow 
L_0= t_{n-1,1-\alpha/2}
\end{array}
\]</span></p>
<p>Per tant, en un contrast bilateral amb nivell de significació <span class="math inline">\(\alpha\)</span>, tenim la regla de rebuig següent:</p>
<blockquote>
<p>Rebutjarem <em>H</em><sub>0</sub> si <span class="math inline">\(|T_0|&gt;t_{n-1,1-\alpha/2}\)</span></p>
</blockquote>
<p>En aquest cas, el p-valor serà la probabilitat que <span class="math inline">\(T\)</span> prengui un valor tant o més extrem que <span class="math inline">\(T_0\)</span>, en el sentit de la hipòtesi alternativa, és a dir, més enfora de 0 que <span class="math inline">\(T_0\)</span>: més gran que <span class="math inline">\(|T_0|\)</span> o més petit que <span class="math inline">\(-|T_0|\)</span>:
<span class="math display">\[
\text{p-valor} =P(T\leqslant -|T_0|)+P(T\geqslant |T_0|)=2 P(T\geqslant |T_0|).
\]</span>
Observau que tornam a emprar que, per la simetria de les variables t de Student, <span class="math inline">\(P(T\leqslant -|T_0|)=P(T\geqslant |T_0|)\)</span>.</p>
<p>Per tant,
<span class="math display">\[
\begin{array}{l}
 \text{Rebutjam }H_0  \Longleftrightarrow |T_0|&gt;t_{n-1,1-\alpha/2}\\
\qquad \Longleftrightarrow P(T\geqslant |T_0|)&lt;{\alpha}/{2}\\
\qquad\Longleftrightarrow 2 P(T\geqslant |T_0|)&lt;\alpha\\
\qquad \Longleftrightarrow \text{p-valor} &lt; \alpha 
\end{array}
\]</span></p>
<p>Per tant, en un contrast bilateral amb nivell de significació <span class="math inline">\(\alpha\)</span> també tenim la regla de rebuig:</p>
<blockquote>
<p>Rebutjarem <em>H</em><sub>0</sub> si el p-valor és més petit que <span class="math inline">\(\alpha\)</span></p>
</blockquote>

<div class="rmdimportant">
<p>En resum, en un contrast d’una mitjana <span class="math inline">\(\mu\)</span> emprant un test t i nivell de significació <span class="math inline">\(\alpha\)</span>:</p>
<ul>
<li><p>Si <span class="math inline">\(H_1:\mu&gt; \mu_0\)</span>:</p>
<ul>
<li>Rebutjam <em>H</em><sub>0</sub> si <span class="math inline">\(T_0&gt;t_{n-1,1-\alpha}\)</span></li>
<li>El p-valor és <span class="math inline">\(P(T\geqslant T_0)\)</span> i rebutjam <em>H</em><sub>0</sub> si aquest p-valor és més petit que <span class="math inline">\(\alpha\)</span></li>
</ul></li>
<li><p>Si <span class="math inline">\(H_1:\mu&lt; \mu_0\)</span>:</p>
<ul>
<li>Rebutjam <em>H</em><sub>0</sub> si <span class="math inline">\(T_0&lt; t_{n-1,\alpha}\)</span></li>
<li>El p-valor és <span class="math inline">\(P(T\leqslant T_0)\)</span> i rebutjam <em>H</em><sub>0</sub> si aquest p-valor és més petit que <span class="math inline">\(\alpha\)</span></li>
</ul></li>
<li><p>Si <span class="math inline">\(H_1:\mu\neq \mu_0\)</span>:</p>
<ul>
<li>Rebutjam <em>H</em><sub>0</sub> si <span class="math inline">\(|T_0|&gt;t_{n-1,1-\alpha/2}\)</span></li>
<li>El p-valor és <span class="math inline">\(2P(T\geqslant |T_0|)\)</span> i rebutjam <em>H</em><sub>0</sub> si aquest p-valor és més petit que <span class="math inline">\(\alpha\)</span></li>
</ul></li>
</ul>
</div>

<div class="example">
<p><span id="exm:ttestmu20" class="example"><strong>Exemple 5.14  </strong></span>Sigui <span class="math inline">\(X\)</span> una població normal. Volem fer el contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu&gt;20
\end{array}
\right.
\]</span>
amb un nivell de significació de 0.05. Prenem una mostra aleatòria simple de <span class="math inline">\(n=25\)</span> observacions i obtenim <span class="math inline">\(\overline{X}=20.7\)</span> i <span class="math inline">\(\widetilde{S}_X=1.8\)</span>. Què decidim?</p>
</div>
<ul>
<li><p>Estadístic de contrast:
<span class="math inline">\(T=\dfrac{\overline{X}-\mu_0}{\widetilde{S}_X/\sqrt{n}}\)</span></p></li>
<li><p>Pren el valor
<span class="math display">\[
T_0=\dfrac{20.7-20}{{1.8}/{\sqrt{25}}}=1.944
\]</span></p></li>
<li><p>p-valor
<span class="math display">\[
P(T\geqslant 1.944)=\texttt{1-pt(1.944,24)}=0.032
\]</span></p></li>
<li><p><strong>Decisió</strong>: Com que el p-valor és més petit que 0.05, rebutjam <em>H</em><sub>0</sub> i concloem (amb <span class="math inline">\(\alpha=0.05\)</span>) que <span class="math inline">\(\mu&gt;20\)</span>.</p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-388" class="example"><strong>Exemple 5.15  </strong></span>Sigui <span class="math inline">\(X\)</span> una població normal. Volem fer el contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu&gt;20
\end{array}
\right.
\]</span>
amb un nivell de significació de 0.01. Amb la mateixa mostra aleatòria simple de l’exemple anterior, què decidim?</p>
</div>
<p>El p-valor és el mateix que abans, 0.032, perquè el contrast i la mostra són els mateixos. Com que aquest p-valor és més gran que 0.01, amb <span class="math inline">\(\alpha=0.01\)</span> no podem rebutjar que <span class="math inline">\(\mu=20\)</span>.</p>

<div class="example">
<p><span id="exm:ttestmu20petit" class="example"><strong>Exemple 5.16  </strong></span>Sigui <span class="math inline">\(X\)</span> una població normal. Volem fer el contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu&lt; 20
\end{array}
\right.
\]</span>
amb un nivell de significació de 0.05. Amb la mateixa mostra aleatòria simple dels exemples anteriors (<span class="math inline">\(n=25\)</span>, <span class="math inline">\(\overline{X}=20.7\)</span>, <span class="math inline">\(\widetilde{S}_X=1.8\)</span>), què decidim?</p>
</div>
<ul>
<li><p>L’estadístic de contrast i el seu valor <span class="math inline">\(T_0\)</span> són el mateixos que abans.</p></li>
<li><p>p-valor
<span class="math display">\[
P(T\leqslant 1.944)=\texttt{pt(1.944,24)}=0.968
\]</span></p></li>
<li><p><strong>Decisió</strong>: Com que el p-valor és més gran que 0.05, amb <span class="math inline">\(\alpha=0.05\)</span> no podem rebutjar que <span class="math inline">\(\mu=20\)</span>.</p></li>
</ul>

<div class="rmdromans">
Vegem, com volíeu que concloguéssim que <span class="math inline">\(\mu&lt;20\)</span> si ens ha sortit una mitjana mostral 20.7, més gran que 20? No feia falta fer cap càlcul (i exposar-nos a equivocar-nos), bastava raonar una mica.
</div>

<div class="example">
<p><span id="exm:ttest1bis" class="example"><strong>Exemple 5.17  </strong></span>Sigui <span class="math inline">\(X\)</span> una població normal. Volem fer el contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu\neq 20
\end{array}
\right.
\]</span>
amb un nivell de significació de 0.05. Amb la mateixa mostra aleatòria simple dels exemples anteriors, què decidim?</p>
</div>
<p>Recordem que <span class="math inline">\(n=25\)</span>, <span class="math inline">\(\overline{X}=20.7\)</span> i <span class="math inline">\(\widetilde{S}_X=1.8\)</span>. L’estadístic de contrast prenia el valor <span class="math inline">\(T_0=1.944\)</span>.</p>
<p>Ara el p-valor és
<span class="math display">\[
2\cdot P(T\geqslant 1.944)=\texttt{2*(1-pt(1.944,24))}=0.064
\]</span></p>
<p>Com que el p-valor és més gran que 0.05, amb <span class="math inline">\(\alpha=0.05\)</span> no podem rebutjar que <span class="math inline">\(\mu=20\)</span>, i per tant no podem concloure que <span class="math inline">\(\mu\neq 20\)</span>.</p>

<div class="rmdromans">
Com pot ser que amb la mateixa mostra i mateix nivell de significació poguem concloure que <span class="math inline">\(\mu&gt; 20\)</span> però no poguem concloure que <span class="math inline">\(\mu\neq 20\)</span>? O és que <span class="math inline">\(\mu&gt; 20\)</span> no implica que <span class="math inline">\(\mu\neq 20\)</span>?
</div>
<p>Vegem, si haguéssim demostrat que segur que <span class="math inline">\(\mu&gt; 20\)</span>, està clar que això implicaria que <span class="math inline">\(\mu\neq 20\)</span>. Però hem arribat a la conclusió <span class="math inline">\(\mu&gt; 20\)</span> assumint un cert marge d’error, una probabilitat d’error de tipus I de 0.05, i ens demanam si <span class="math inline">\(\mu\neq 20\)</span> assumint el mateix marge d’error. En aquesta situació les regles de la lògica aristotèlica ja no funcionen.</p>
<p>Fixau-vos que, en realitat, el que passa és que trobarem evidència que <span class="math inline">\(\mu\neq 20\)</span> si <span class="math inline">\(T\)</span> és molt gran o molt petit, i per tant al contrast bilateral hi tenim dues fonts d’error de tipus I: que per pur atzar <span class="math inline">\(T\)</span> ens surti molt gran o que ens surti molt petit.
En canvi, només trobarem evidència que <span class="math inline">\(\mu&gt; 20\)</span> si <span class="math inline">\(T\)</span> és molt gran, i per tant hi tenim una sola font d’error de tipus I. Aleshores, per garantir una mateixa probabilitat d’error de tipus I, hem de ser molt més exigents al contrast bilateral, on ens podem equivocar de dues maneres diferents, que a l’unilateral.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-391" class="example"><strong>Exemple 5.18  </strong></span>Sigui <span class="math inline">\(X\)</span> una població normal. Volem fer el contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=20\\ H_{1}:\mu\neq 20
\end{array}
\right.
\]</span>
amb un nivell de significació de 0.05. Prenem una mostra aleatòria simple de <span class="math inline">\(n=25\)</span> observacions i obtenim <span class="math inline">\(\overline{X}=19\)</span> i <span class="math inline">\(\widetilde{S}_X=1.8\)</span>. Què decidim?</p>
</div>
<ul>
<li><p>Estadístic de contrast:
<span class="math inline">\(T=\dfrac{\overline{X}-\mu_0}{\widetilde{S}_X/\sqrt{n}}\)</span></p></li>
<li><p>Pren el valor
<span class="math display">\[
T_0=\dfrac{19-20}{{1.8}/{\sqrt{25}}}=-2.778
\]</span></p></li>
<li><p>p-valor
<span class="math display">\[
2P(T\geqslant -2.778)=\texttt{2*(1-pt(-2.778,24))}=1.99
\]</span></p></li>
<li><p>Decisió: com que el p-valor és més gran que <span class="math inline">\(\alpha\)</span>, no podem rebutjar <em>H</em><sub>0</sub>.</p></li>
</ul>

<div class="rmderror">
El p-valor és una probabiitat. Com voleu que doni 1.99?
</div>
<p><strong>NO!</strong> El p-valor no és <span class="math inline">\(2\cdot P(T\geqslant T_0)\)</span>, sinó <span class="math inline">\(2\cdot P(T\geqslant |T_0|)\)</span>. Per tant, el p-valor és
<span class="math display">\[
2\cdot P(T\geqslant 2.778)=\texttt{2*(1-pt(2.778,24))}=0.01
\]</span>
i com que p-valor és més petit que <span class="math inline">\(\alpha\)</span>, podem rebutjar <em>H</em><sub>0</sub> i concloure, amb nivell de significació 0.05, que <span class="math inline">\(\mu\neq 20\)</span>.</p>
</div>
<div id="recapitulació" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Recapitulació</h2>
<p>Repassem els conceptes introduïts fins ara, i posem nom a alguns altres:</p>
<ul>
<li><p><strong>Nivell de significació</strong>, <span class="math inline">\(\alpha\)</span>: probabilitat de rebutjar <em>H</em><sub>0</sub> si aquesta és vertadera (<em>probabilitat d’error de tipus I</em>, <em>de positiu fals</em>).</p></li>
<li><p><strong>Nivell de confiança</strong>, <span class="math inline">\(1-\alpha\)</span>: probabilitat d’acceptar <em>H</em><sub>0</sub> si aquesta és vertadera (<em>probabilitat de negatiu vertader</em>).</p></li>
<li><p><strong>Potència</strong>, <span class="math inline">\(1-\beta\)</span>: probabilitat de rebutjar <em>H</em><sub>0</sub> si <em>H</em><sub>1</sub> és vertadera (<em>probabilitat de positiu vertader</em>).</p></li>
<li><p><strong>Estadístic de contrast</strong>: el que calculam sobre una mostra aleatòria simple i del qual coneixem la distribució de probabilitat si <em>H</em><sub>0</sub> és vertadera.</p></li>
<li><p><strong>Regió crítica o de rebuig</strong>: el rang de valors de l’estadístic de contrast per als quals rebutjam <em>H</em><sub>0</sub> amb un nivell de significació <span class="math inline">\(\alpha\)</span> donat.</p></li>
<li><p><strong>Regió d’acceptació</strong>: el complementari de la regió de rebuig, és a dir, el rang de valors de l’estadístic de contrast per als quals acceptam <em>H</em><sub>0</sub> amb un nivell de significació <span class="math inline">\(\alpha\)</span> donat.</p></li>
<li><p><strong>p-valor</strong>: la probabilitat que, si <em>H</em><sub>0</sub> és vertadera, l’estadístic de contrast prengui sobre una mostra aleatòria simple de la mateixa mida que la nostra un valor tan o més extrem (en el sentit de <em>H</em><sub>1</sub>) que l’obtengut sobre la nostra mostra.</p></li>
</ul>

<div class="rmdrecordau">
L’estadístic de contrast pertany a la regió de rebuig si, i només si, el p-valor és més petit que el nivell de significació.
</div>

<div class="example">
<p><span id="exm:unnamed-chunk-394" class="example"><strong>Exemple 5.19  </strong></span>Si realitzam un test t per efectuar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu &gt; \mu_0
\end{array}
\right.
\]</span>
rebutjam <em>H</em><sub>0</sub> amb nivell de significació <span class="math inline">\(\alpha\)</span> quan
<span class="math display">\[
T=\dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}&gt;t_{n-1,1-\alpha}
\]</span></p>
</div>
<p>Per tant:</p>
<ul>
<li><p><em>Estadístic de contrast</em>: aquest <span class="math inline">\(T\)</span></p></li>
<li><p><em>Regió de rebuig</em> per aquest <span class="math inline">\(\alpha\)</span>: l’interval <span class="math inline">\((t_{n-1,1-\alpha},\infty)\)</span></p></li>
<li><p><em>Regió d’acceptació</em> per aquest <span class="math inline">\(\alpha\)</span>: l’interval <span class="math inline">\((-\infty,t_{n-1,1-\alpha}]\)</span></p></li>
<li><p><em>p-valor</em>: <span class="math inline">\(P(T\geqslant T_0)\)</span>, on <span class="math inline">\(T_0\)</span> indica el valor de <span class="math inline">\(T\)</span> sobre la nostra mostra</p></li>
</ul>
<p>Si en canvi el contrast que volem efectuar és
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu &lt; \mu_0
\end{array}
\right.
\]</span>
rebutjam <em>H</em><sub>0</sub> amb nivell de significació <span class="math inline">\(\alpha\)</span> quan
<span class="math display">\[
T=\dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}&lt;t_{n-1,\alpha}
\]</span></p>
<p>Per tant:</p>
<ul>
<li><p><em>Estadístic de contrast</em>: el mateix <span class="math inline">\(T\)</span> que abans</p></li>
<li><p><em>Regió de rebuig</em> per aquest <span class="math inline">\(\alpha\)</span>: l’interval <span class="math inline">\((-\infty,t_{n-1,\alpha})\)</span></p></li>
<li><p><em>Regió d’acceptació</em> per aquest <span class="math inline">\(\alpha\)</span>: l’interval <span class="math inline">\([t_{n-1,\alpha},\infty)\)</span></p></li>
<li><p><em>p-valor</em>: <span class="math inline">\(P(T\leqslant T_0)\)</span></p></li>
</ul>
<p>Finalment, si el contrast que volem realitzar és
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu \neq \mu_0
\end{array}
\right.
\]</span>
rebutjam <em>H</em><sub>0</sub> amb nivell de significació <span class="math inline">\(\alpha\)</span> quan
<span class="math display">\[
|T|=\left|\dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}\right|&gt;t_{n-1,1-\alpha/2}
\]</span>
Per tant:</p>
<ul>
<li><p><em>Estadístic de contrast</em>: el mateix <span class="math inline">\(T\)</span> que abans</p></li>
<li><p><em>Regió de rebuig</em> per aquest <span class="math inline">\(\alpha\)</span>: la unió d’intervals <span class="math inline">\((-\infty,-t_{n-1,1-\alpha/2})\cup (t_{n-1,1-\alpha/2},\infty)\)</span></p></li>
<li><p><em>Regió d’acceptació</em> per aquest <span class="math inline">\(\alpha\)</span>: l’interval <span class="math inline">\([-t_{n-1,1-\alpha/2},t_{n-1,1-\alpha/2}]\)</span></p></li>
<li><p><em>p-valor</em>: <span class="math inline">\(2P(T\geqslant |T_0|)\)</span></p></li>
</ul>
<div id="interval-de-confiança-dun-contrast" class="section level3 unnumbered">
<h3>Interval de confiança d’un contrast</h3>
<p>L’<strong>interval de confiança de nivell de confiança <span class="math inline">\(1-\alpha\)</span></strong> d’un contrast és un interval que té probabilitat <span class="math inline">\(1-\alpha\)</span> de contenir el valor real del paràmetre poblacional que contrastam, en el sentit dels intervals de confiança del tema anterior: es calcula amb una fórmula que en una fracció <span class="math inline">\(1-\alpha\)</span> de les ocasions que l’aplicam a una mostra aleatòria simple, dóna un interval que conté el paràmetre d’interès.</p>
<p>Aquest interval de confiança s’obté imposant que l’estadístic de contrast pertanyi a la regió d’acceptació per al nivell de significació <span class="math inline">\(\alpha\)</span> i aïllant el paràmetre poblacional.</p>
<ul>
<li><p>Quan <em>H</em><sub>1</sub> és bilateral, coincideix amb l’interval de confiança donat en el tema anterior.</p></li>
<li><p>Quan <em>H</em><sub>1</sub> és unilateral, dóna un interval infinit al costat definit per la hipòtesi alternativa.</p></li>
</ul>
<p>Per exemple, considerem el cas de un test t per efectuar un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu &gt; \mu_0
\end{array}
\right.
\]</span>
Acceptam <em>H</em><sub>0</sub> amb nivell de significació <span class="math inline">\(\alpha\)</span> quan
<span class="math display">\[
\dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}\leqslant t_{n-1,1-\alpha}
\]</span>
Aïllant <span class="math inline">\(\mu_0\)</span>, obtenim
<span class="math display">\[
\overline{X}- t_{n-1,1-\alpha}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\leqslant \mu_0
\]</span>
Per tant, l’<strong>interval de confiança de nivell de confiança <span class="math inline">\(1-\alpha\)</span> per a aquest contrast</strong> és
<span class="math display">\[
\Bigg[\overline{X}- t_{n-1,1-\alpha}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}},\infty\Bigg)
\]</span>
Si la <span class="math inline">\(\mu_0\)</span> que contrastam pertany a aquest interval, no podem concloure que la <span class="math inline">\(\mu\)</span> poblacional sigui més gran que <span class="math inline">\(\mu_0\)</span>, i per tant no podem rebutjar que <span class="math inline">\(\mu=\mu_0\)</span>. Els valors de <span class="math inline">\(\mu_0\)</span> en aquest interval són tan grans que amb la nostra mostra no hem obtengut evidència que la <span class="math inline">\(\mu\)</span> real sigui encara més gran que ells.</p>
<p>En l’exemple dels diabètics de la Secció <a href="chap-chgen.html#sec:exttest">5.5</a>, dóna l’interval
<span class="math display">\[
\Bigg[3.2- 1.73\cdot \dfrac{1.5}{\sqrt{20}},\infty\Bigg)=[2.62,\infty)
\]</span></p>
<p>Concloem que, amb un nivell de confiança del 95%, la concentració mitjana de calci en sang en els joves diabètics és com a mínim 2.62, i que per tant, amb aquest nivell de confiança, és més gran que 2.5, encara que per poc.</p>
<p>Si efectuam un contrast bilateral amb un test t
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_0\\ 
H_{1}:\mu\neq  \mu_0
\end{array}
\right.
\]</span>
acceptam <em>H</em><sub>0</sub> amb nivell de significació <span class="math inline">\(\alpha\)</span> quan
<span class="math display">\[
-t_{n-1,1-\alpha/2}\leqslant \dfrac{\overline{X}-\mu_0}{{\widetilde{S}_X}/{\sqrt{n}}}\leqslant t_{n-1,1-\alpha/2}
\]</span>
Aïllant <span class="math inline">\(\mu_0\)</span>, obtenim:
<span class="math display">\[
\overline{X}- t_{n-1,1-\alpha/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\leqslant \mu_0 \leqslant \overline{X}+ t_{n-1,1-\alpha/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}
\]</span>
Per tant, l’<strong>interval de confiança de nivell de confiança <span class="math inline">\(1-\alpha\)</span> per a aquest contrast</strong> és
<span class="math display">\[
\Bigg[\overline{X}- t_{n-1,1-\alpha/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}},\overline{X}+ t_{n-1,1-\alpha/2}\cdot \dfrac{\widetilde{S}_X}{\sqrt{n}}\Bigg]
\]</span>
Us sona? Fent <span class="math inline">\(q=1-\alpha\)</span>, de manera que <span class="math inline">\(1-\alpha/2=(1+q)/2\)</span>, és el del tema anterior.</p>

<div class="rmdimportant">
<p>Donat un contrast d’hipòtesis, podem decidir si rebutjam <em>H</em><sub>0</sub> a favor de <em>H</em><sub>1</sub> amb nivell de significació <span class="math inline">\(\alpha\)</span> emprant:</p>
<ul>
<li><p><strong>La regió de rebuig</strong>: Si l’<em>estadístic de contrast</em> cau dins la regió de rebuig per al nivell de significació <span class="math inline">\(\alpha\)</span>, rebutjam <em>H</em><sub>0</sub></p></li>
<li><p><strong>El p-valor</strong>: Si el p-valor és més petit que el nivell de significació <span class="math inline">\(\alpha\)</span>, rebutjam <em>H</em><sub>0</sub></p></li>
<li><p><strong>L’interval de confiança</strong>: Si el valor que contrastam del <em>paràmetre poblacional</em> no pertany a l’interval de confiança de nivell de confiança <span class="math inline">\(1-\alpha\)</span>, rebutjam <em>H</em><sub>0</sub></p></li>
</ul>
<p>Els tres mètodes són equivalents. El més adequat és donar el p-valor i l’interval de confiança: el p-valor perquè el lector el pugui comparar amb el nivell de significació que consideri oportú i l’interval de confiança perquè mostra el marge amb el qual hem acceptat o rebutjat la hipòtesi nul·la amb el nostre nivell de significació.</p>
</div>
<p>Si no establim un nivell de significació <span class="math inline">\(\alpha\)</span>, el que és habitual en Biologia i Bioquímica és:</p>
<ul>
<li><p>Acceptar <em>H</em><sub>0</sub> si el p-valor és més gran que 0.1: es diu que el p-valor <strong>no és estadísticament significatiu</strong>.</p></li>
<li><p>Rebutjar <em>H</em><sub>0</sub> si el p-valor és més petit que 0.05: es diu que el p-valor <strong>és estadísticament significatiu</strong>.</p></li>
<li><p>Si el p-valor està entre 0.05 i 0.1 i no s’ha fixat nivell de significació, el millor que podeu fer és no concloure res.</p></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-396"></span>
<img src="https://imgs.xkcd.com/comics/p_values.png" alt="&quot;P-values&quot; (https://xkcd.com/1478/ (CC-BI-NC 2.5))" width="40%" />
<p class="caption">
Figura 5.4: “P-values” (<a href="https://xkcd.com/1478/" class="uri">https://xkcd.com/1478/</a> (CC-BI-NC 2.5))
</p>
</div>
<p>Quan el p-valor és més petit que 0.05, se solen distingir tres franges:</p>
<ul>
<li><strong>Significatiu</strong> si està entre 0.01 i 0.05</li>
<li><strong>Fortament significatiu</strong> si està entre 0.001 i 0.01</li>
<li><strong>Molt significatiu</strong> si és més petit que 0.001</li>
</ul>
<p>R marca aquestes franges amb un codi d’asteriscs</p>
<pre><code>Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-397"></span>
<img src="Bioestadistica-II_files/figure-html/emojis.png" alt="Emoticones per representar els nivells de significació estadística (BMJ 2018; 363, doi: https://doi.org/10.1136/bmj.k5033)" width="80%" />
<p class="caption">
Figura 5.5: Emoticones per representar els nivells de significació estadística (BMJ 2018; 363, doi: <a href="https://doi.org/10.1136/bmj.k5033" class="uri">https://doi.org/10.1136/bmj.k5033</a>)
</p>
</div>
<p>Per favor, acostumau-vos a donar el p-valor, i no la franja de significació on cau. D’aquesta manera el lector el pot comparar amb el nivell de significació que ell consideri l’adient.</p>
<p>Atès que rebutjam <em>H</em><sub>0</sub> si, i només si, el p-valor és més petit que <span class="math inline">\(\alpha\)</span>, el p-valor d’un contrast és el nivell de significació més petit per al qual rebutjaríem la hipòtesi nul·la. És a dir:</p>

<div class="rmdimportant">
El p-valor obtengut en un contrast és la probabilitat mínima que assumim d’equivocar-nos rebutjant la hipòtesi nul·la si és vertadera.
</div>
</div>
<div id="la-potència" class="section level3 unnumbered">
<h3>La potència</h3>
<p>Recordau que la <strong>potència</strong> <span class="math inline">\(1-\beta\)</span> és la probabilitat de rebutjar <em>H</em><sub>0</sub> quan <em>H</em><sub>1</sub> és vertadera.</p>
<p>Per exemple, en l’exemple del calci en diabètics de la Secció <a href="chap-chgen.html#sec:exttest">5.5</a>, la regla de rebuig era
<span class="math display">\[
T=\frac{\overline{X}-2.5}{\widetilde{S}_X/\sqrt{n}}&gt;1.73,
\]</span>
per tant la potència era
<span class="math display">\[
1-\beta=P(\text{Rebutjar } H_0| H_1\text{ vertadera})=P(T&gt;1.73| \mu&gt;2.5).
\]</span>
Aquesta probabilitat és impossible de calcular, però hi ha paquets de R que la saben estimar.</p>
<p>Per a cada tipus de contrast es té una relació numèrica entre:</p>
<ul>
<li><p>La <strong>potència</strong> <span class="math inline">\(1-\beta\)</span></p></li>
<li><p>La <strong>mida</strong> de la mostra <span class="math inline">\(n\)</span>: la potència creix amb <span class="math inline">\(n\)</span></p></li>
<li><p>El <strong>nivell de significació</strong> <span class="math inline">\(\alpha\)</span>: la potència decreix amb <span class="math inline">\(\alpha\)</span></p></li>
<li><p>La <strong>mida de l’efecte</strong>, un valor que quantifica la diferència entre el valor de l’estimador del paràmetre sobre la mostra i el valor que contrastam del paràmetre poblacional. La potència creix amb el valor absolut de la mida de l’efecte (ja que, quant més gran és la diferència entre l’estimació i el valor contrastat, més fàcil és que sigui estadísticament significativa i per tant rebutgem la hipòtesi nul·la).</p></li>
</ul>
<p>Aquesta relació permet calcular qualsevol dels quatre valors a partir dels altres tres; amb R, el paquet <strong>pwr</strong> permet fer-ho amb els contrastos més usuals. Al pròxim tema en veurem alguns exemples.</p>
<p>A l’hora de planejar un experiment per realitzar un contrast, el que s’ha de fer és:</p>
<ul>
<li><p>Fixar el nivell de significació desitjat</p></li>
<li><p>Fixar la potència desitjada</p></li>
<li><p>Estimar la mida de l’efecte esperat (a partir de la nostra teoria, de la nostra experiència, dels resultats d’altres estudis…) o que volguem detectar (per rebutjar la hipòtesi nul·la ens bastarà una mida de l’efecte petita o la requerirem grossa?)</p></li>
</ul>
<p>i emprar la relació anterior per calcular la mida de la mostra necessària per assolir la potència desitjada.</p>

<div class="rmdcaution">
Desconfiau dels treballs on això no es faci. Podria ser que la potència fos molt baixa i hi hagués un <strong>biaix de infrapotència</strong> (<em>underpower</em>): es necessitava un efecte molt gran per poder rebutjar la hipòtesi nul·la i publicar l’article.
</div>
</div>
<div id="el-risc-de-positiu-fals-opcional" class="section level3 unnumbered">
<h3>El risc de positiu fals (Opcional)</h3>
<p>El paquet <strong>statcheck</strong> de R permet revisar de manera automàtica tots els càlculs d’un article escrit en un format concret en psicologia i comprovar-ne els p-valors. Els autors analitzaren 30,000 articles i varen concloure que <a href="https://link.springer.com/article/10.3758/s13428-015-0664-2">(<em>Behavior research methods</em> 48 (2016), 1205-1226)</a>:</p>
<blockquote>
<p>“Hem trobat que la meitat dels articles contenen almenys un p-valor erroni. I un de cada vuit articles conté un p-valor erroni que a més afecta la conclusió estadística.”</p>
</blockquote>
<p>Per tant,</p>
<ul>
<li>Qualsevol article pot donar un p-valor petit que estigui equivocat</li>
</ul>
<p>No us en refieu. A més, teniu present que:</p>
<ul>
<li><p>Qualsevol estudi mal dissenyat o mal realitzat pot donar un p-valor petit… que no signifiqui absolutament res</p></li>
<li><p>Qualsevol estudi perfectament dissenyat i realitzat pot donar per pur atzar un p-valor petit… que impliqui un positiu fals</p></li>
</ul>
<p>En resum, a qualsevol estudi us podeu trobar amb un fals positiu. Sigau escèptics.</p>
<p>El <strong>risc de positiu fals</strong>, <strong>FPR</strong>, en un contrast és
<span class="math display">\[
P(H_0\text{ vertadera}|H_0\text{ rebutjada}).
\]</span>
Pel teorema de Bayes (notau que interpretam <span class="math inline">\(H_1= \text{no }H_0\)</span>)
<span class="math display">\[
\begin{array}{rl}
FPR&amp;=\dfrac{P(H_0)\cdot P(H_0\text{ reb.}|H_0)}{P(H_0)\cdot P(H_0\text{ reb.}|H_0)+P(H_1)\cdot P(H_0\text{ reb.}|H_1)}\\
&amp; =\dfrac{P(H_0)\cdot \alpha}{P(H_0)\cdot \alpha+(1-P(H_0))\cdot (1-\beta)}\\
&amp; =\dfrac{(1-P(H_1))\cdot \alpha}{(1-P(H_1))\cdot \alpha+ P(H_1)\cdot (1-\beta)}
\end{array}
\]</span></p>
<p>Per calcular-lo, hem de saber el nivell de significació i la potència i hem de decidir <em>a priori</em> quina probabilitat assignam al fet que <em>H</em><sub>1</sub> sigui vertadera.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-400" class="example"><strong>Exemple 5.20  </strong></span>En un estudi (publicat a <a href="https://journals.sagepub.com/doi/abs/10.1177/0956797611414726"><em>Psychological Science</em> 22 (2011), pp. 1011-1018</a>) es repartiren 66 participants en dos grups de 33, als que direm grup Bandera i grup Control, i els mostraren les mateixes 4 fotos d’edificis. En les del grup Bandera, dues mostraven una bandera dels EUA, i en les del grup Control, aquestes banderes havien estat eliminades digitalment. Un exemple d’aquestes fotos es mostra a la Figura <a href="chap-chgen.html#fig:fotoflag">5.6</a>. Per emmascarar l’estudi, se’ls demanà que endevinassin l’hora del dia en què varen ser preses les fotos.</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:fotoflag"></span>
<img src="Bioestadistica-II_files/figure-html/fotoflag.png" alt="Una de les fotos emprades a l'experiment de les banderes" width="80%" />
<p class="caption">
Figura 5.6: Una de les fotos emprades a l’experiment de les banderes
</p>
</div>
<p>Després de mirar les fotos, els participants emplenaren un qüestionari sobre idees polítiques, a partir del qual es pot calcular un cert “índex de republicanisme” (en el sentit nord americà del terme) <span class="math inline">\(M\)</span>. Resulta que <span class="math inline">\(M\)</span> va ser significativament més gran en el grup Bandera que en el grup Control, i amb un nivell de significació <span class="math inline">\(\alpha=0.05\)</span> els autors de l’estudi conclogueren que mirar fotos amb banderes estatals et “dretitza” (almenys a curt termini) les idees polítiques. Vaig a estimar el risc que aquest positiu sigui fals.</p>
<p>Com que <em>a priori</em>, trob molt improbable que la conclusió sigui certa, li assignaré <span class="math inline">\(P(H_1)=0.1\)</span> i gràcies. Emprarem el seu <span class="math inline">\(\alpha=0.05\)</span>, i si es calcula la potència del contrast publicat, dóna 0.5.</p>
<p>Llavors
<span class="math display">\[
FPR =\dfrac{0.9\cdot 0.05}{0.9\cdot 0.05+0.1\cdot 0.5}=0.47
\]</span>
Per tant, <em>a posteriori</em>, crec que hi ha un 47% de probabilitats que <em>H</em><sub>1</sub> sigui falsa i un 53% de probabilitats que <em>H</em><sub>1</sub> sigui vertadera.</p>
</div>
</div>
<div id="test-de-la-lliçó-5" class="section level2" number="5.7">
<h2><span class="header-section-number">5.7</span> Test de la lliçó 5</h2>
<p><strong>(1)</strong> Quan escrivim formalment un contrast d’hipòtesis, què significa <em>H</em><sub>1</sub>?</p>
<ol style="list-style-type: decimal">
<li>És la primera hipòtesi que fem i que després ja modificarem en funció de les dades obtingudes</li>
<li>És la hipòtesi nul·la</li>
<li>És la hipòtesi alternativa</li>
<li>És la variable aleatòria poblacional d’interès</li>
<li>Cap de les altres respostes és la correcta</li>
</ol>
<p><strong>(2)</strong> Tenc un dau cúbic de 6 cares i sospit que està trucat a favor de 1. Amb un experiment cercaré evidència que confirmi la meva sospita. Sigui <span class="math inline">\(p\)</span> la probabilitat de treure un 1 amb el meu dau. Quin dels contrastos d’hipòtesis següents tradueix la pregunta que vull resoldre amb aquest experiment?</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0: p=1/6; H_1: p \neq 1/6\)</span></li>
<li><span class="math inline">\(H_0: p=1/6; H_1: p &gt; 1/6\)</span></li>
<li><span class="math inline">\(H_0: p=1/6; H_1: p \geqslant 1/6\)</span></li>
<li><span class="math inline">\(H_0: p=1/6; H_1: p&lt;1/6\)</span></li>
<li><span class="math inline">\(H_0: p&gt;1/6; H_1: p=1/6\)</span></li>
<li><span class="math inline">\(H_0: p&gt;1/6; H_1: p \leqslant 1/6\)</span></li>
<li><span class="math inline">\(H_0: p \leqslant 1/6; H_1: p &gt; 1/6\)</span></li>
<li><span class="math inline">\(H_0: p = 1/2; H_1: p &gt; 1/2\)</span></li>
<li>Cap dels anteriors</li>
</ol>
<p><strong>(3)</strong> Tenc un dau cúbic de 6 cares i sospit que està trucat a favor de 1. Sigui <span class="math inline">\(p\)</span> la probabilitat de treure un 1 amb el meu dau. He llançat el dau 100 vegades, he obtengut 28 uns. Això m’ha donat un p-valor de 0.0015. Quina és la conclusió correcta d’aquest contrast?</p>
<ol style="list-style-type: decimal">
<li>Es confirma la meva sospita, perquè la probabilitat que el meu dau no estigui trucat a favor d’1 és 0.0015</li>
<li>No es confirma la meva sospita, perquè la probabilitat que el meu dau estigui trucat a favor d’1 és 0.0015</li>
<li>Es confirma la meva sospita, perquè la probabilitat d’obtenir, si el dau fos equilibrat, exactament 28 uns en 100 llançaments és molt improbable (0.0015), i això fa difícil de creure que el dau sigui equilibrat</li>
<li>No es confirma la meva sospita, perquè la probabilitat d’obtenir, si el dau estigués trucat a favor d’1, exactament 28 uns en 100 llançaments és molt improbable (0.0015), i això fa difícil de creure que el dau estigui trucat</li>
<li>Es confirma la meva sospita, perquè la probabilitat d’obtenir, si el dau fos equilibrat, 28 o més uns en 100 llançaments és molt improbable (0.0015), i això fa difícil de creure que el dau sigui equilibrat</li>
<li>Es confirma la meva sospita, perquè la probabilitat d’obtenir, si el dau fos equilibrat, 28 o menys uns en 100 llançaments és molt improbable (0.0015), i això fa difícil de creure que el dau sigui equilibrat</li>
<li>No es confirma la meva sospita, perquè la probabilitat d’obtenir, si el dau estigués trucat a favor de 1, 28 o menys uns en 100 llançaments és molt improbable (0.0015), i això fa difícil de creure que el dau estigui trucat</li>
<li>Cap de les altres respostes és correcta</li>
</ol>
<p><strong>(4)</strong> Volem contrastar si la proporció d’estudiants universitaris que rebutjaran la vacuna de la COVID-19 és inferior al 5.6% (la proporció estimada de la població espanyola que pensa rebutjar-la). Per a això, prenem una mostra raonablement aleatòria de 100 estudiants i els ho demanam. Quina és la hipòtesi nul·la d’aquest contrast?</p>
<ol style="list-style-type: decimal">
<li>La proporció poblacional d’estudiants universitaris que rebutjaran la vacuna de la COVID-19 és més petita que el 5.6%</li>
<li>La proporció poblacional d’estudiants universitaris que rebutjaran la vacuna de la COVID-19 és més petita o igual que el 5.6%</li>
<li>La proporció poblacional d’estudiants universitaris que rebutjaran la vacuna de la COVID-19 és del 5.6%</li>
<li>La proporció poblacional d’estudiants universitaris que rebutjaran la vacuna de la COVID-19 és més gran o igual que el 5.6%</li>
<li>La proporció d’estudiants de la nostra mostra que rebutjaran la vacuna de la COVID-19 és més petita que el 5.6%</li>
<li>La proporció d’estudiants de la nostra mostra que rebutjaran la vacuna de la COVID-19 és més petita o igual que el 5.6%</li>
<li>La proporció d’estudiants de la nostra mostra que rebutjaran la vacuna de la COVID-19 és del 5.6%</li>
<li>La proporció d’estudiants de la nostra mostra que rebutjaran la vacuna de la COVID-19 és més gran o igual que el 5.6%</li>
</ol>
<p><strong>(5)</strong> Un test del COVID-19 no és res més que un contrast d’hipòtesis: prens una mostra de l’individu i decideixes si està malalt o no. Quin contrast és?</p>
<ol style="list-style-type: decimal">
<li><em>H</em><sub>0</sub>: L’individu està infectat; <em>H</em><sub>1</sub>: L’individu no està infectat</li>
<li><em>H</em><sub>0</sub>: L’individu no està infectat; <em>H</em><sub>1</sub>: L’individu està infectat</li>
<li><em>H</em><sub>0</sub>: L’individu no està infectat; <em>H</em><sub>1</sub>: L’individu podria estar infectat</li>
<li><em>H</em><sub>0</sub>: No sé si l’individu està infectat; <em>H</em><sub>1</sub>: L’individu està infectat</li>
</ol>
<p><strong>(6)</strong> Quan en un contrast d’hipòtesis rebutjam la hipòtesi nul·la i decidim que l’alternativa és la vertadera (marcau la resposta correcta)</p>
<ol style="list-style-type: decimal">
<li>És perquè els resultats de la nostra mostra demostren que la hipòtesi alternativa és vertadera</li>
<li>És perquè els resultats de la nostra mostra demostren que la hipòtesi nul·la és falsa</li>
<li>És perquè els resultats de la nostra mostra demostren que la hipòtesi alternativa és més probable que la nul·la</li>
<li>És perquè els resultats de la nostra mostra demostren que la hipòtesi nul·la és impossible</li>
<li>És perquè els resultats de la nostra mostra ens fan dubtar que la hipòtesi nul·la sigui vertadera</li>
</ol>
<p><strong>(7)</strong> Volem investigar si prendre un suplement diari de vitamina B fa que les ungles de les mans creixin més ràpid que si no es pren. Quina és la hipòtesi nul·la?</p>
<ol style="list-style-type: decimal">
<li>Prendre un suplement de vitamina B accelera el creixement de les ungles.</li>
<li>No se sap si prendre un suplement de vitamina B accelera o retarda el creixement de les ungles.</li>
<li>Prendre un suplement de vitamina B retarda el creixement de les ungles.</li>
<li>Prendre un suplement de vitamina B no té cap efecte en el creixement de les ungles.</li>
</ol>
<p><strong>(8)</strong> Suposem que en un contrast d’hipòtesis NO s’ha rebutjat la hipòtesi nul·la. Quina de les següents afirmacions és la més correcta?</p>
<ol style="list-style-type: decimal">
<li>S’ha demostrat que la hipòtesi nul·la és vertadera.</li>
<li>S’ha demostrat que la hipòtesi alternativa és falsa.</li>
<li>S’ha trobat evidència que la hipòtesi nul·la és vertadera.</li>
<li>S’ha trobat evidència que la hipòtesi alternativa és falsa.</li>
<li>Totes les altres afirmacions són uns dois.</li>
</ol>
<p><strong>(9)</strong> En un estudi on es va contrastar si la proporció d’adolescents mallorquins que són miops és més gran que el 40%, es va prendre una mostra de 50 adolescents i s’hi observaren 22 miops. El p-valor del contrast va ser 0.33. Què vol dir això? Marcau una sola resposta.</p>
<ol style="list-style-type: decimal">
<li>La probabilitat que un adolescent mallorquí sigui miop és 0.33</li>
<li>La probabilitat que la proporció d’adolescents mallorquins que són miops sigui més gran que el 50% és 0.67</li>
<li>La probabilitat que la proporció d’adolescents mallorquins que són miops sigui més gran que el 50% és 0.33</li>
<li>És un error, perquè 22 de 50 no és un 33%</li>
<li>Si la proporció d’adolescents mallorquins que són miops fos més gran que el 40%, la probabilitat d’obtenir 22 miops en una mostra aleatòria de 50 adolescents mallorquins és 0.33</li>
<li>Si la proporció d’adolescents mallorquins que són miops fos més gran que el 40%, la probabilitat d’obtenir 22 o més miops en una mostra aleatòria de 50 adolescents mallorquins és 0.33</li>
<li>Si la proporció d’adolescents mallorquins que són miops fos del 40%, la probabilitat d’obtenir 22 miops en una mostra aleatòria de 50 adolescents mallorquins és 0.33</li>
<li>Si la proporció d’adolescents mallorquins que són miops fos del 40%, la probabilitat d’obtenir 22 o més miops en una mostra aleatòria de 50 adolescents mallorquins és 0.33</li>
<li>Si la proporció d’adolescents mallorquins que són miops fos més petita o igual que el 40%, la probabilitat d’obtenir 22 miops en una mostra aleatòria de 50 adolescents mallorquins és 0.33</li>
<li>Si la proporció d’adolescents mallorquins que són miops fos més petita o igual que el 40%, la probabilitat d’obtenir 22 o més miops en una mostra aleatòria de 50 adolescents mallorquins és 0.33</li>
<li>Cap de les altres respostes és correcta</li>
</ol>
<p><strong>(10)</strong> En una assaig clínic d’una vacuna de la COVID-19 se cerca evidència que la vacuna redueix la probabilitat d’infecció. Digau <span class="math inline">\(p_v\)</span> a la probabilitat d’infectar-se si s’ha rebut la vacuna i <span class="math inline">\(p_n\)</span> a la probabilitat d’infectar-se si no s’ha rebut la vacuna. Quin contrast tradueix la pregunta que es pretén resoldre amb aquest assaig?</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0:p_v&lt;p_n\)</span>; <span class="math inline">\(H_1: p_v&gt;p_n\)</span></li>
<li><span class="math inline">\(H_0:p_v&lt;p_n\)</span>; <span class="math inline">\(H_1: p_v \leqslant p_n\)</span></li>
<li><span class="math inline">\(H_0:p_v&lt;p_n\)</span>; <span class="math inline">\(H_1: p_v =p_n\)</span></li>
<li><span class="math inline">\(H_0:p_v=p_n\)</span>; <span class="math inline">\(H_1: p_v \leqslant p_n\)</span></li>
<li><span class="math inline">\(H_0:p_v=p_n\)</span>; <span class="math inline">\(H_1: p_v &lt; p_n\)</span></li>
<li><span class="math inline">\(H_0:p_v=p_n\)</span>; <span class="math inline">\(H_1: p_v &gt; p_n\)</span></li>
<li><span class="math inline">\(H_0:p_v&gt;p_n\)</span>; <span class="math inline">\(H_1: p_v = p_n\)</span></li>
<li><span class="math inline">\(H_0:p_v \geqslant p_n\)</span>; <span class="math inline">\(H_1: p_v &lt; p_n\)</span></li>
<li><span class="math inline">\(H_0:p_v &gt; p_n\)</span>; <span class="math inline">\(H_1: p_v \leqslant p_n\)</span></li>
<li>Cap dels anteriors</li>
</ol>
<p><strong>(11)</strong> Suposem que, un cop s’hagi realitzat l’assaig anterior, en analitzar les dades recollides, s’obtengui evidència que <span class="math inline">\(p_v\)</span> és més petita que <span class="math inline">\(p_n\)</span>, amb un p-valor 0.034. Quina de les interpretacions següents d’aquest valor és la més correcta?</p>
<ol style="list-style-type: decimal">
<li>Que hi ha un 3.4% de probabilitat que, si es repeteix l’estudi, no es trobin diferències significatives entre les proporcions d’infectats entre els vacunats i els no vacunats</li>
<li>Que hi ha un 3.4% de probabilitat que la probabilitat d’infectar-se dels vacunats i dels no vacunats sigui la mateixa</li>
<li>Que hi ha un 3.4% de diferència, o més, entre la probabilitat que un no vacunat s’infecti i la probabilitat que un vacunat s’infecti</li>
<li>Que a la mostra considerada, hi ha hagut almenys un 3.4% de diferència entre la proporció dels no vacunats que s’han infectat i la proporció dels vacunats que s’han infectat</li>
<li>Que si la vacuna no redueix la probabilitat d’infectar-se, hi ha un 3.4% de probabilitat que, si es repeteix l’estudi, la diferència que s’obtengui entre les proporcions d’infectats entre els vacunats i els no vacunats sigui com l’obtenguda en aquest assaig, o més gran.</li>
<li>Que hi ha un 3.4% de probabilitat que, si es repeteix l’estudi, la diferència que s’obtengui entre les proporcions d’infectats entre els vacunats i els no vacunats sigui com l’obtenguda en aquest assaig, o més gran.</li>
</ol>
<p><strong>(12)</strong> Un científic publica un article on afirma que les persones que consumeixen un determinat medicament tenen una major probabilitat de formació de càlculs renals. Més tard es descobreix que en realitat aquesta associació no existeix. Quin tipus d’error va cometre el científic i per què?</p>
<ol style="list-style-type: decimal">
<li>Tipus I, perquè va afirmar que la hipòtesi nul·la és certa quan en realitat és falsa.</li>
<li>Tipus I, perquè va afirmar que la hipòtesi nul·la és falsa quan en realitat és certa.</li>
<li>Tipus II, perquè va afirmar que la hipòtesi nul·la és certa quan en realitat és falsa.</li>
<li>Tipus II, perquè va afirmar que la hipòtesi nul·la és falsa quan en realitat és certa.</li>
</ol>
<p><strong>(13)</strong> Què significa que en un contrast d’hipòtesis prenguem un nivell de significació del 1%?</p>
<ol style="list-style-type: decimal">
<li>Que si la hipòtesi nul·la és falsa, hi ha un 1% de probabilitats que la rebutgem a favor de l’alternativa.</li>
<li>Que si la hipòtesi nul·la és falsa, hi ha un 1% de probabilitats que l’acceptem.</li>
<li>Que si la hipòtesi nul·la és vertadera, hi ha un 1% de probabilitats que la rebutgem a favor de l’alternativa.</li>
<li>Que si la hipòtesi nul·la és vertadera, hi ha un 1% de probabilitats que l’acceptem.</li>
<li>Que hi ha un 1% de probabilitats que rebutgem la hipòtesi nul·la.</li>
<li>Que hi ha un 1% de probabilitats que acceptem la hipòtesi nul·la.</li>
<li>Cap de les altres respostes és correcta.</li>
</ol>
<p><strong>(14)</strong> En un estudi no es va obtenir evidència estadísticament significativa que la proporció de rosses naturals entre les estudiants de ciències de la UIB fos més petita que la proporció d’espanyoles rosses. Quina o quines de les afirmacions següents sobre el contrast d’hipòtesis que es va realitzar són vertaderes?</p>
<ol style="list-style-type: decimal">
<li>El contrast va ser unilateral.</li>
<li>És segur que la proporció de rosses naturals entre les estudiants de ciències de la UIB és més gran o igual que la proporció d’espanyoles rosses.</li>
<li>Es va obtenir evidència estadísticament significativa que la proporció de rosses naturals entre les estudiants de ciències de la UIB és més gran o igual que la proporció d’espanyoles rosses.</li>
<li>Pot ser que la conclusió es degués a un error de tipus I.</li>
<li>Pot ser que la conclusió es degués a un error de tipus II.</li>
<li>Totes les altres respostes són falses.</li>
</ol>
<p><strong>(15)</strong> En un examen considerat com un contrast (marcau totes les respostes
correctes)</p>
<ol style="list-style-type: decimal">
<li>Que l’estudiant aprovi sense saber la matèria és un error de tipus I</li>
<li>Que l’estudiant aprovi sense saber la matèria és un error de tipus II</li>
<li>Que l’estudiant aprovi sense saber la matèria és simultàniament un error de tipus I i de tipus II</li>
<li>El nivell de significació és la probabilitat que l’estudiant aprovi sense saber la matèria</li>
<li>El nivell de significació és la probabilitat que l’estudiant suspengui si no sap la matèria</li>
</ol>
<p><strong>(16)</strong> En un estudi on es va contrastar si els individus amb hipertensió arterial tenen un major risc de sofrir un infart de miocardi que els individus normotensos, es va obtenir un p-valor de 0.02. Què vol dir això?</p>
<ol style="list-style-type: decimal">
<li>La probabilitat que els hipertensos tenguin més risc de sofrir un infart de miocardi que els normotensos és 0.02</li>
<li>La probabilitat que els hipertensos tenguin més risc de sofrir un infart de miocardi que els normotensos és 0.98</li>
<li>Un hipertens té una probabilitat de sofrir un infart de miocardi un 2% major que un normotens.</li>
<li>En les mostres que hem emprat en l’estudi, la proporció d’hipertensos que han sofert un infart de miocardi és un 2% major que la de normotensos que han sofert un infart de miocardi</li>
<li>Cap de les altres respostes és correcta.</li>
</ol>
<p><strong>(17)</strong> En un contrast amb <span class="math inline">\(\alpha=0.05\)</span> rebutjam la hipòtesi nul·la. Què passaria si, amb la mateixa mostra, prenguéssim <span class="math inline">\(\alpha=0.1\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Segur que també rebutjaríem la hipòtesi nul·la</li>
<li>Segur que no rebutjaríem la hipòtesi nul·la</li>
<li>Pot passar qualsevol cosa</li>
</ol>
<p><strong>(18)</strong> En un contrast amb <span class="math inline">\(\alpha=0.05\)</span> no rebutjam la hipòtesi nul·la. Què passaria si, amb la mateixa mostra, prenguéssim <span class="math inline">\(\alpha=0.1\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Segur que tampoc rebutjaríem la hipòtesi nul·la</li>
<li>Segur que sí que rebutjaríem la hipòtesi nul·la</li>
<li>Pot passar qualsevol cosa</li>
</ol>
<p><strong>(19)</strong> Suposem que hem realitzat un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_{0}\\
H_{1}:\mu&gt;\mu_{0}
\end{array}
\right.
\]</span>
amb <span class="math inline">\(\alpha=0.05\)</span> amb un test t sobre una mostra de mida 50 i el resultat ha estat que no podem rebutjar la hipòtesi nul·la. Quina seria la conclusió si, amb la mateixa mostra, canviàssim <em>H</em><sub>1</sub> per <span class="math inline">\(\mu\neq \mu_0\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Segur que tampoc rebutjaríem la hipòtesi nul·la</li>
<li>Segur que sí que rebutjaríem la hipòtesi nul·la</li>
<li>Pot passar qualsevol cosa</li>
</ol>
<p><strong>(20)</strong> Suposem que hem realitzat un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_{0}\\
H_{1}:\mu&gt;\mu_{0}
\end{array}
\right.
\]</span>
amb <span class="math inline">\(\alpha=0.05\)</span> amb un test t sobre una mostra de mida 50 i el resultat ha estat que podem rebutjar la hipòtesi nul·la. Quina seria la conclusió si, amb la mateixa mostra, canviàssim <em>H</em><sub>1</sub> per <span class="math inline">\(\mu\neq \mu_0\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Segur que tampoc rebutjaríem la hipòtesi nul·la</li>
<li>Segur que sí que rebutjaríem la hipòtesi nul·la</li>
<li>Pot passar qualsevol cosa</li>
</ol>
<p><strong>(21)</strong> Suposem que hem realitzat un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_{0}\\
H_{1}:\mu\neq \mu_{0}
\end{array}
\right.
\]</span>
amb <span class="math inline">\(\alpha=0.05\)</span> amb un test t sobre una mostra de mida 50 i el resultat ha estat que no podem rebutjar la hipòtesi nul·la. Quina seria la conclusió si, amb la mateixa mostra, canviàssim <em>H</em><sub>1</sub> per <span class="math inline">\(\mu&gt; \mu_0\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Segur que tampoc rebutjaríem la hipòtesi nul·la</li>
<li>Segur que sí que rebutjaríem la hipòtesi nul·la</li>
<li>Pot passar qualsevol cosa</li>
</ol>
<p><strong>(22)</strong> Suposem que hem realitzat un contrast
<span class="math display">\[
\left\{\begin{array}{l}
H_{0}:\mu=\mu_{0}\\
H_{1}:\mu\neq\mu_{0}
\end{array}
\right.
\]</span>
amb <span class="math inline">\(\alpha=0.05\)</span> amb un test t sobre una mostra de mida 50 i el resultat ha estat que podem rebutjar la hipòtesi nul·la. Quina seria la conclusió si, amb la mateixa mostra, canviàssim <em>H</em><sub>1</sub> per <span class="math inline">\(\mu&gt; \mu_0\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Segur que tampoc rebutjaríem la hipòtesi nul·la</li>
<li>Segur que sí que rebutjaríem la hipòtesi nul·la</li>
<li>Pot passar qualsevol cosa</li>
</ol>
<p><strong>(23)</strong> Hem realitzat un contrast d’hipòtesis per determinar si hi ha evidència que el temps mitjà d’eliminació <span class="math inline">\(\mu\)</span> d’un cert compost en les persones amb funció renal normal és superior a les 5 hores. Sobre una mostra de 100 persones, hem emprat un test t i hem obtengut un valor per a l’estadístic de contrast <span class="math inline">\(T\)</span> d’1.4 i un p-valor 0.01. Què significa això? Marcau la resposta correcta.</p>
<ol style="list-style-type: decimal">
<li>Si <span class="math inline">\(\mu=5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T\leqslant 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu=5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T\geqslant 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu=5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T= 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu&gt; 5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T\leqslant 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu&gt; 5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T\geqslant 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu&gt; 5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T= 1.4\)</span> és 0.01.</li>
<li>Totes les altres respostes són incorrectes.</li>
</ol>
<p><strong>(24)</strong> Hem realitzat un contrast d’hipòtesis per determinar si hi ha evidència que el temps mitjà d’eliminació <span class="math inline">\(\mu\)</span> d’un cert compost en les persones amb funció renal normal és diferent de 5 hores. Sobre una mostra de 100 persones, hem emprat un test t i hem obtengut un valor per a l’estadístic de contrast d’1.4 i un p-valor 0.01. Què significa això? Marcau la resposta correcta.</p>
<ol style="list-style-type: decimal">
<li>Si <span class="math inline">\(\mu=5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T\leqslant 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu=5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T\geqslant 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu=5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T= 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu\neq 5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T\leqslant 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu\neq 5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T\geqslant 1.4\)</span> és 0.01.</li>
<li>Si <span class="math inline">\(\mu\neq 5\)</span>, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem <span class="math inline">\(T= 1.4\)</span> és 0.01.</li>
<li>Totes les altres respostes són incorrectes.</li>
</ol>
<p><strong>(25)</strong> En un contrast d’una mitjana emprant un test t, l’augment de la mida d’aquesta mostra (marcau totes les respostes correctes):</p>
<ol style="list-style-type: decimal">
<li>Millora l’aproximació de l’estadístic de contrast a una distribució normal.</li>
<li>Esperam que disminueixi la probabilitat d’error de tipus I.</li>
<li>Esperam que disminueixi la probabilitat d’error de tipus II.</li>
<li>Esperam que disminueixi la potència del contrast.</li>
<li>Fa menys probable que la hipòtesi nul·la sigui vertadera.</li>
<li>Totes les altres respostes són incorrectes.</li>
</ol>
<p><strong>(26)</strong> En un contrast d’hipòtesis en el qual la hipòtesi nul·la és vertadera (marcau una sola resposta):</p>
<ol style="list-style-type: decimal">
<li>Només podem cometre un error de tipus I.</li>
<li>Només podem cometre un error de tipus II.</li>
<li>Podem cometre tant un error de tipus I com un error de tipus II, però no tots dos.</li>
<li>Podem cometre tant un error de tipus I com un error de tipus II, i podem cometre’ls tots dos.</li>
<li>Com que la hipòtesi nul·la és vertadera, no podem cometre ni un error de tipus I ni un error de tipus II.</li>
<li>Totes les altres respostes són falses.</li>
</ol>
<p><strong>(27)</strong> Hem realitzat un contrast d’hipòtesis per determinar si hi ha evidència que la concentració mitjana d’un cert metabòlit en sang és diferent en pacients amb dues malalties diferents. Sobre dues mostres de 100 subjectes, hem obtengut un valor per a l’estadístic de contrast de -3.2 i un p-valor <span class="math inline">\(0.0015\)</span>. Què significa això? Marcau la resposta correcta.</p>
<ol style="list-style-type: decimal">
<li>Si les concentracions mitjanes són iguals, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem un valor per a l’estadístic de contrast menor que -3.2 és 0.0015.</li>
<li>Si les concentracions mitjanes són iguals, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem un valor per a l’estadístic de contrast major que -3.2 és 0.0015.</li>
<li>Si les concentracions mitjanes són iguals, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem un valor per a l’estadístic de contrast major que 3.2 és 0.0015.</li>
<li>Si les concentracions mitjanes són iguals, la probabilitat que en un altre estudi per realitzar aquest contrast obtenguem un valor per a l’estadístic de contrast menor que -3.2 o major que 3.2 és 0.0015.</li>
<li>La probabilitat que les concentracions mitjanes siguin iguals quan s’obté aquest valor de l’estadístic de contrast és 0.0015.</li>
<li>Cap de les altres afirmacions és correcta.</li>
</ol>
<p><strong>(28)</strong> Hem realitzat dos contrastos d’hipòtesis diferents amb dues mostres diferents, al primer hem obtengut un p-valor 0.02 i al segon un p-valor 0.01. Quina de les conclusions següents és la correcta?</p>
<ol style="list-style-type: decimal">
<li>És més probable que sigui vertadera la hipòtesi alternativa del primer contrast que la del segon</li>
<li>És més probable que sigui vertadera la hipòtesi alternativa del segon contrast que la del primer</li>
<li>Cap de les conclusions anteriors és correcta.</li>
</ol>
<p><strong>(29)</strong> En un contrast d’hipòtesis sobre la mitjana <span class="math inline">\(\mu\)</span> d’una variable aleatòria normal <span class="math inline">\(X\)</span> amb hipòtesi alternativa <span class="math inline">\(H_1: \mu&lt;2\)</span> hem pres una mostra aleatòria simple de <span class="math inline">\(X\)</span> de mida 25 i hem obtengut una mitjana mostral de 1.6 amb una desviació típica mostral de 1.1. Volem realitzar el contrast amb nivell de significació 0.05. Quina de les regles següents genèriques hem d’aplicar?</p>
<ol style="list-style-type: decimal">
<li>Acceptarem la hipòtesi nul·la si l’estadístic de contrast és més petit que un cert llindar <span class="math inline">\(L_0\)</span></li>
<li>Rebutjarem la hipòtesi nul·la si l’estadístic de contrast és més petit que un cert llindar <span class="math inline">\(L_0\)</span></li>
<li>Rebutjarem la hipòtesi nul·la si l’estadístic de contrast és igual a un cert llindar <span class="math inline">\(L_0\)</span></li>
</ol>
<p><strong>(30)</strong> Què és la regió d’acceptació d’un contrast sobre un paràmetre poblacional?</p>
<ol style="list-style-type: decimal">
<li>El conjunt dels valors del paràmetre poblacional pels quals hem d’acceptar la hipòtesi nul·la</li>
<li>El conjunt dels valors del paràmetre poblacional pels quals hem d’acceptar la hipòtesi alternativa</li>
<li>El conjunt dels valors de l’estadístic de contrast pels quals hem d’acceptar la hipòtesi nul·la</li>
<li>El conjunt dels valors de l’estadístic de contrast pels quals hem d’acceptar la hipòtesi alternativa</li>
<li>El conjunt de les estimacions acceptables del paràmetre poblacional a partir de la mostra</li>
</ol>
<p><strong>(31)</strong> Si efectuam un mateix contrast amb el mateix nivell de significació dues vegades amb dues mostres diferents de la mateixa mida (marcau les continuacions correctes)</p>
<ol style="list-style-type: decimal">
<li>La regió d’acceptació del contrast serà les dues vegades la mateixa</li>
<li>La regió d’acceptació del contrast pot donar diferent amb cada mostra<br />
</li>
<li>L’interval de confiança del contrast serà les dues vegades el mateix<br />
</li>
<li>L’interval de confiança del contrast pot donar diferent amb cada mostra</li>
</ol>
<p><strong>(32)</strong> En un contrast d’hipòtesis hem rebutjat la hipòtesi nul·la a favor de l’alternativa amb nivell de significació del 10%. El contrast ha tengut una potència del 60%. Quina de les afirmacions següents és correcta en aquesta situació?</p>
<ol style="list-style-type: decimal">
<li>La probabilitat que la hipòtesi nul·la sigui vertadera és 0.1</li>
<li>La probabilitat que la hipòtesi nul·la sigui vertadera és 0.4</li>
<li>La probabilitat que la hipòtesi alternativa sigui vertadera és 0.1</li>
<li>La probabilitat que la hipòtesi alternativa sigui vertadera és 0.4</li>
<li>Cap de les altres respostes és correcta.</li>
</ol>
<p><strong>(33)</strong> Hem efectuat el mateix contrast amb dues mostres: amb la primera hem obtengut un p-valor de 0.1 i amb la segona un p-valor de 0.01. Quina o quines de les afirmacions següents són correctes?</p>
<ol style="list-style-type: decimal">
<li>És més probable que sigui vertadera la hipòtesi nul·la del contrast amb la primera mostra que la hipòtesi nul·la del contrast amb la segona mostra</li>
<li>És més probable que sigui vertadera la hipòtesi nul·la del contrast amb la segona mostra que la hipòtesi nul·la del contrast amb la primera mostra</li>
<li>No hi ha manera de saber si la hipòtesi nul·la del contrast amb la primera mostra és més probable o menys probable que la hipòtesi nul·la del contrast amb la primera mostra</li>
<li>Cap de les altres respostes és correcta</li>
</ol>
<p><strong>(34)</strong> Suposem que hem realitzat un contrast <span class="math inline">\(H_0: \mu=\mu_0\)</span> contra <span class="math inline">\(H_1: \mu\neq\mu_0\)</span> amb <span class="math inline">\(\alpha=0.05\)</span> amb un test t sobre una determinada mostra. Què li passaria a l’interval de confiança del contrast si canviàssim <em>H</em><sub>1</sub> per <span class="math inline">\(\mu&lt;\mu_0\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Seria el mateix, perquè no hem canviat de mostra</li>
<li>Seria més ample</li>
<li>Seria més estret</li>
<li>Pot passar qualsevol cosa</li>
</ol>
<p><strong>(35)</strong> Suposem que hem realitzat un contrast <span class="math inline">\(H_0: \mu=\mu_0\)</span> contra <span class="math inline">\(H_1: \mu\neq \mu_0\)</span> amb <span class="math inline">\(\alpha=0.05\)</span> amb un test t sobre una determinada mostra. Què li passaria a l’interval de confiança del contrast obtengut amb aquesta mateixa mostra si augmentàssim el nivell de significació a <span class="math inline">\(\alpha=0.1\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Seria més ample</li>
<li>Seria més estret<br />
</li>
<li>Seria exactament igual, perquè no hem canviat de mostra</li>
<li>Pot passar qualsevol cosa</li>
</ol>
<p><strong>(36)</strong> Hem efectuat un test t d’una mitjana, amb hipòtesi alternativa <span class="math inline">\(\mu\neq 2\)</span>. És possible que hàgim obtengut (amb la mateixa mostra) un interval de confiança del contrast del 95% [2.1,3.2] i un p-valor 0.13?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>
<p><strong>(37)</strong> Hem efectuat un test t d’una mitjana, amb hipòtesi alternativa <span class="math inline">\(\mu\neq 2\)</span>. És possible que hàgim obtengut (amb la mateixa mostra) un interval de confiança del contrast del 95% [1.8,3.2] i un p-valor 0.13?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>
<p><strong>(38)</strong> Hem efectuat un test t de dues mitjanes, amb hipòtesi alternativa <span class="math inline">\(\mu&lt;2\)</span>. És possible que hàgim obtengut (amb la mateixa mostra) un interval de confiança del contrast del 95% [1.8,3.2] i un p-valor 0.13?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>
<p><strong>(39)</strong> Hem efectuat un test t de dues mitjanes, amb hipòtesi alternativa <span class="math inline">\(\mu_1\neq \mu_2\)</span>. És possible que hàgim obtengut (amb la mateixa mostra) un interval de confiança del contrast del 95% [2.1,3.2] i un p-valor 0.13?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>
<p><strong>(40)</strong> Hem efectuat dues vegades, amb dues mostres diferents, un mateix test t de dues mitjanes, amb hipòtesi alternativa <span class="math inline">\(\mu\neq 2\)</span>. És possible que amb una mostra hàgim obtengut un interval de confiança del contrast del 95% [2.1,3.2] i amb l’altra mostra un p-valor 0.13?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-IC.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
