<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tema 8 Contrastos d’independència i homogeneïtat | Matemàtiques II v.2021</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Tema 8 Contrastos d’independència i homogeneïtat | Matemàtiques II v.2021" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 8 Contrastos d’independència i homogeneïtat | Matemàtiques II v.2021" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2021-05-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-bondat.html"/>
<link rel="next" href="chap-ED.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="chapter" data-level="1" data-path="chap-conceptes.html"><a href="chap-conceptes.html"><i class="fa fa-check"></i><b>1</b> Alguns conceptes bàsics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="chap-conceptes.html"><a href="chap-conceptes.html#tipus-de-dades"><i class="fa fa-check"></i><b>1.1</b> Tipus de dades</a></li>
<li class="chapter" data-level="1.2" data-path="chap-conceptes.html"><a href="chap-conceptes.html#població"><i class="fa fa-check"></i><b>1.2</b> Població</a></li>
<li class="chapter" data-level="1.3" data-path="chap-conceptes.html"><a href="chap-conceptes.html#variable-aleatòria"><i class="fa fa-check"></i><b>1.3</b> Variable aleatòria</a></li>
<li class="chapter" data-level="1.4" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostra"><i class="fa fa-check"></i><b>1.4</b> Mostra</a></li>
<li class="chapter" data-level="1.5" data-path="chap-conceptes.html"><a href="chap-conceptes.html#sec:mostreig"><i class="fa fa-check"></i><b>1.5</b> Mostreig aleatori</a></li>
<li class="chapter" data-level="1.6" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostres-de-conveniència"><i class="fa fa-check"></i><b>1.6</b> Mostres de conveniència</a></li>
<li class="chapter" data-level="1.7" data-path="chap-conceptes.html"><a href="chap-conceptes.html#test-de-la-lliçó-1"><i class="fa fa-check"></i><b>1.7</b> Test de la lliçó 1</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chap-varal.html"><a href="chap-varal.html"><i class="fa fa-check"></i><b>2</b> Variables aleatòries</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chap-varal.html"><a href="chap-varal.html#generalitats-sobre-variables-aleatòries"><i class="fa fa-check"></i><b>2.1</b> Generalitats sobre variables aleatòries</a></li>
<li class="chapter" data-level="2.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-discretes"><i class="fa fa-check"></i><b>2.2</b> Variables aleatòries discretes</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució"><i class="fa fa-check"></i><b>2.2.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="2.2.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança"><i class="fa fa-check"></i><b>2.2.2</b> Esperança</a></li>
<li class="chapter" data-level="2.2.3" data-path="chap-varal.html"><a href="chap-varal.html#variància-i-desviació-típica"><i class="fa fa-check"></i><b>2.2.3</b> Variància i desviació típica</a></li>
<li class="chapter" data-level="2.2.4" data-path="chap-varal.html"><a href="chap-varal.html#quantils"><i class="fa fa-check"></i><b>2.2.4</b> Quantils</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chap-varal.html"><a href="chap-varal.html#famílies-importants-de-variables-aleatòries-discretes"><i class="fa fa-check"></i><b>2.3</b> Famílies importants de variables aleatòries discretes</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-binomials"><i class="fa fa-check"></i><b>2.3.1</b> Variables aleatòries binomials</a></li>
<li class="chapter" data-level="2.3.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-hipergeomètriques"><i class="fa fa-check"></i><b>2.3.2</b> Variables aleatòries hipergeomètriques</a></li>
<li class="chapter" data-level="2.3.3" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-de-poisson"><i class="fa fa-check"></i><b>2.3.3</b> Variables aleatòries de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-contínues"><i class="fa fa-check"></i><b>2.4</b> Variables aleatòries contínues</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució-1"><i class="fa fa-check"></i><b>2.4.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="2.4.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança-variància-quantils"><i class="fa fa-check"></i><b>2.4.2</b> Esperança, variància, quantils…</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="chap-varal.html"><a href="chap-varal.html#sec:normal"><i class="fa fa-check"></i><b>2.5</b> Variables aleatòries normals</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i><b>2.5.1</b> Amb R</a></li>
<li class="chapter" data-level="2.5.2" data-path="chap-varal.html"><a href="chap-varal.html#propietats-bàsiques"><i class="fa fa-check"></i><b>2.5.2</b> Propietats bàsiques</a></li>
<li class="chapter" data-level="2.5.3" data-path="chap-varal.html"><a href="chap-varal.html#intervals-de-referència"><i class="fa fa-check"></i><b>2.5.3</b> Intervals de referència</a></li>
<li class="chapter" data-level="2.5.4" data-path="chap-varal.html"><a href="chap-varal.html#sec:lognormal"><i class="fa fa-check"></i><b>2.5.4</b> Variables log-normals</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="chap-varal.html"><a href="chap-varal.html#test-de-la-lliçó-2"><i class="fa fa-check"></i><b>2.6</b> Test de la lliçó 2</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-estim.html"><a href="chap-estim.html"><i class="fa fa-check"></i><b>3</b> Estimació puntual</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chap-estim.html"><a href="chap-estim.html#estimadors"><i class="fa fa-check"></i><b>3.1</b> Estimadors</a></li>
<li class="chapter" data-level="3.2" data-path="chap-estim.html"><a href="chap-estim.html#mitjana-mostral"><i class="fa fa-check"></i><b>3.2</b> Mitjana mostral</a></li>
<li class="chapter" data-level="3.3" data-path="chap-estim.html"><a href="chap-estim.html#proporció-mostral"><i class="fa fa-check"></i><b>3.3</b> Proporció mostral</a></li>
<li class="chapter" data-level="3.4" data-path="chap-estim.html"><a href="chap-estim.html#variància-mostral"><i class="fa fa-check"></i><b>3.4</b> Variància mostral</a></li>
<li class="chapter" data-level="3.5" data-path="chap-estim.html"><a href="chap-estim.html#la-distribució-t-de-student"><i class="fa fa-check"></i><b>3.5</b> La distribució t de Student</a></li>
<li class="chapter" data-level="3.6" data-path="chap-estim.html"><a href="chap-estim.html#biaix-i-precisió"><i class="fa fa-check"></i><b>3.6</b> Biaix i precisió</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="chap-estim.html"><a href="chap-estim.html#estimadors-no-esbiaixats"><i class="fa fa-check"></i><b>3.6.1</b> Estimadors no esbiaixats</a></li>
<li class="chapter" data-level="3.6.2" data-path="chap-estim.html"><a href="chap-estim.html#sec:precis"><i class="fa fa-check"></i><b>3.6.2</b> Estimadors precisos</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="chap-estim.html"><a href="chap-estim.html#estimadors-màxim-versemblants"><i class="fa fa-check"></i><b>3.7</b> Estimadors màxim versemblants</a></li>
<li class="chapter" data-level="3.8" data-path="chap-estim.html"><a href="chap-estim.html#sec:pobl"><i class="fa fa-check"></i><b>3.8</b> Estimació de poblacions</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="chap-estim.html"><a href="chap-estim.html#estimació-de-poblacions-numerades"><i class="fa fa-check"></i><b>3.8.1</b> Estimació de poblacions numerades</a></li>
<li class="chapter" data-level="3.8.2" data-path="chap-estim.html"><a href="chap-estim.html#marca-recaptura"><i class="fa fa-check"></i><b>3.8.2</b> Marca-recaptura</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="chap-estim.html"><a href="chap-estim.html#test-de-la-lliçó-3"><i class="fa fa-check"></i><b>3.9</b> Test de la lliçó 3</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chap-IC.html"><a href="chap-IC.html"><i class="fa fa-check"></i><b>4</b> Intervals de confiança</a>
<ul>
<li class="chapter" data-level="4.1" data-path="chap-IC.html"><a href="chap-IC.html#definició-dinterval-de-confiança"><i class="fa fa-check"></i><b>4.1</b> Definició d’interval de confiança</a></li>
<li class="chapter" data-level="4.2" data-path="chap-IC.html"><a href="chap-IC.html#exemple-interval-de-confiança-del-95-per-a-la-mitjana-duna-variable-aleatòria-normal"><i class="fa fa-check"></i><b>4.2</b> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</a></li>
<li class="chapter" data-level="4.3" data-path="chap-IC.html"><a href="chap-IC.html#interval-de-confiança-per-a-la-mitjana-basat-en-la-t-de-student"><i class="fa fa-check"></i><b>4.3</b> Interval de confiança per a la mitjana basat en la t de Student</a>
<ul>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#la-fórmula"><i class="fa fa-check"></i>La fórmula</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#algunes-consideracions"><i class="fa fa-check"></i>Algunes consideracions</a></li>
<li class="chapter" data-level="" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i>Amb R</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#càlcul-de-la-mida-de-la-mostra-per-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="chap-IC.html"><a href="chap-IC.html#intervals-de-confiança-per-a-proporcions"><i class="fa fa-check"></i><b>4.4</b> Intervals de confiança per a proporcions</a>
<ul>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#mètode-exacte-de-clopper-pearson"><i class="fa fa-check"></i>Mètode “exacte” de Clopper-Pearson</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#mètode-de-wilson"><i class="fa fa-check"></i>Mètode de Wilson</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#mètode-de-laplace"><i class="fa fa-check"></i>Mètode de Laplace</a></li>
<li><a href="chap-IC.html#quan-podem-calcular-més-dun-interval-per-a-p_x-quin-calculam">Quan podem calcular més d’un interval per a <span class="math inline">\(p_X\)</span>, quin calculam?</a></li>
<li class="chapter" data-level="" data-path="chap-IC.html"><a href="chap-IC.html#càlcul-de-la-mida-de-la-mostra-per-a-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per a fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="chap-IC.html"><a href="chap-IC.html#intervals-de-confiança-per-a-la-variància-i-la-desviació-típica-duna-variable-normal"><i class="fa fa-check"></i><b>4.5</b> Intervals de confiança per a la variància i la desviació típica d’una variable normal</a></li>
<li class="chapter" data-level="4.6" data-path="chap-IC.html"><a href="chap-IC.html#poblacions-finites"><i class="fa fa-check"></i><b>4.6</b> “Poblacions finites”</a></li>
<li class="chapter" data-level="4.7" data-path="chap-IC.html"><a href="chap-IC.html#test-de-la-lliçó-4"><i class="fa fa-check"></i><b>4.7</b> Test de la lliçó 4</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chap-chgen.html"><a href="chap-chgen.html"><i class="fa fa-check"></i><b>5</b> Contrastos d’hipòtesis: Generalitats</a>
<ul>
<li class="chapter" data-level="5.1" data-path="chap-chgen.html"><a href="chap-chgen.html#les-hipòtesis-nulla-i-alternativa"><i class="fa fa-check"></i><b>5.1</b> Les hipòtesis nul·la i alternativa</a></li>
<li class="chapter" data-level="5.2" data-path="chap-chgen.html"><a href="chap-chgen.html#sec:moneda"><i class="fa fa-check"></i><b>5.2</b> Un exemple</a></li>
<li class="chapter" data-level="5.3" data-path="chap-chgen.html"><a href="chap-chgen.html#sec:pval"><i class="fa fa-check"></i><b>5.3</b> El p-valor</a></li>
<li class="chapter" data-level="5.4" data-path="chap-chgen.html"><a href="chap-chgen.html#tipus-derrors"><i class="fa fa-check"></i><b>5.4</b> Tipus d’errors</a></li>
<li class="chapter" data-level="5.5" data-path="chap-chgen.html"><a href="chap-chgen.html#sec:exttest"><i class="fa fa-check"></i><b>5.5</b> Exemple: El test t</a></li>
<li class="chapter" data-level="5.6" data-path="chap-chgen.html"><a href="chap-chgen.html#recapitulació"><i class="fa fa-check"></i><b>5.6</b> Recapitulació</a>
<ul>
<li class="chapter" data-level="" data-path="chap-chgen.html"><a href="chap-chgen.html#interval-de-confiança-dun-contrast"><i class="fa fa-check"></i>Interval de confiança d’un contrast</a></li>
<li class="chapter" data-level="" data-path="chap-chgen.html"><a href="chap-chgen.html#la-potència"><i class="fa fa-check"></i>La potència</a></li>
<li class="chapter" data-level="" data-path="chap-chgen.html"><a href="chap-chgen.html#el-risc-de-positiu-fals-opcional"><i class="fa fa-check"></i>El risc de positiu fals (Opcional)</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="chap-chgen.html"><a href="chap-chgen.html#test-de-la-lliçó-5"><i class="fa fa-check"></i><b>5.7</b> Test de la lliçó 5</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><i class="fa fa-check"></i><b>6</b> Contrastos d’hipòtesis d’un i dos paràmetres</a>
<ul>
<li class="chapter" data-level="6.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-de-mitjanes"><i class="fa fa-check"></i><b>6.1</b> Contrastos de mitjanes</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-una-mitjana"><i class="fa fa-check"></i><b>6.1.1</b> Test t per a una mitjana</a></li>
<li class="chapter" data-level="6.1.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-t-per-a-dues-mitjanes"><i class="fa fa-check"></i><b>6.1.2</b> Test t per a dues mitjanes</a></li>
<li class="chapter" data-level="6.1.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-t-amb-r"><i class="fa fa-check"></i><b>6.1.3</b> Tests t amb R</a></li>
<li class="chapter" data-level="6.1.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#exemples"><i class="fa fa-check"></i><b>6.1.4</b> Exemples</a></li>
<li class="chapter" data-level="6.1.5" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics"><i class="fa fa-check"></i><b>6.1.5</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#sec:contrvar"><i class="fa fa-check"></i><b>6.2</b> Contrastos de variàncies</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-chi2-duna-variància"><i class="fa fa-check"></i><b>6.2.1</b> Test <span class="math inline">\(\chi^2\)</span> d’una variància</a></li>
<li class="chapter" data-level="6.2.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-f-per-a-dues-variàncies"><i class="fa fa-check"></i><b>6.2.2</b> Test F per a dues variàncies</a></li>
<li class="chapter" data-level="6.2.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#tests-no-paramètrics-1"><i class="fa fa-check"></i><b>6.2.3</b> Tests no paramètrics</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-proporcions"><i class="fa fa-check"></i><b>6.3</b> Contrastos per a proporcions</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-una-proporció"><i class="fa fa-check"></i><b>6.3.1</b> Contrastos per a una proporció</a></li>
<li class="chapter" data-level="6.3.2" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-independents"><i class="fa fa-check"></i><b>6.3.2</b> Contrastos per a 2 proporcions emprant mostres independents</a></li>
<li class="chapter" data-level="6.3.3" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#contrastos-per-a-2-proporcions-emprant-mostres-aparellades"><i class="fa fa-check"></i><b>6.3.3</b> Contrastos per a 2 proporcions emprant mostres aparellades</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="contrastos-dhipòtesis-dun-i-dos-paràmetres.html"><a href="contrastos-dhipòtesis-dun-i-dos-paràmetres.html#test-de-la-lliçó-6"><i class="fa fa-check"></i><b>6.4</b> Test de la lliçó 6</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chap-bondat.html"><a href="chap-bondat.html"><i class="fa fa-check"></i><b>7</b> Contrastos de bondat d’ajust</a>
<ul>
<li class="chapter" data-level="7.1" data-path="chap-bondat.html"><a href="chap-bondat.html#bondat-dajust"><i class="fa fa-check"></i><b>7.1</b> Bondat d’ajust</a></li>
<li class="chapter" data-level="7.2" data-path="chap-bondat.html"><a href="chap-bondat.html#test-chi2-de-pearson"><i class="fa fa-check"></i><b>7.2</b> Test <span class="math inline">\(\chi^2\)</span> de Pearson</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="chap-bondat.html"><a href="chap-bondat.html#el-test-bàsic"><i class="fa fa-check"></i><b>7.2.1</b> El test bàsic</a></li>
<li class="chapter" data-level="7.2.2" data-path="chap-bondat.html"><a href="chap-bondat.html#mètode-de-montecarlo"><i class="fa fa-check"></i><b>7.2.2</b> Mètode de Montecarlo</a></li>
<li class="chapter" data-level="7.2.3" data-path="chap-bondat.html"><a href="chap-bondat.html#test-chi2-amb-paràmetres-poblacionals-desconeguts"><i class="fa fa-check"></i><b>7.2.3</b> Test <span class="math inline">\(\chi^2\)</span> amb paràmetres poblacionals desconeguts</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="chap-bondat.html"><a href="chap-bondat.html#test-de-kolmogorov-smirnov"><i class="fa fa-check"></i><b>7.3</b> Test de Kolmogorov-Smirnov</a></li>
<li class="chapter" data-level="7.4" data-path="chap-bondat.html"><a href="chap-bondat.html#test-de-kolmogorov-smirnov-lilliefors"><i class="fa fa-check"></i><b>7.4</b> Test de Kolmogorov-Smirnov-Lilliefors</a></li>
<li class="chapter" data-level="7.5" data-path="chap-bondat.html"><a href="chap-bondat.html#test-de-la-lliçó-7"><i class="fa fa-check"></i><b>7.5</b> Test de la lliçó 7</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html"><i class="fa fa-check"></i><b>8</b> Contrastos d’independència i homogeneïtat</a>
<ul>
<li class="chapter" data-level="8.1" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dindependència"><i class="fa fa-check"></i><b>8.1</b> Test <span class="math inline">\(\chi^2\)</span> d’independència</a></li>
<li class="chapter" data-level="8.2" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-dhomogeneïtat"><i class="fa fa-check"></i><b>8.2</b> Test <span class="math inline">\(\chi^2\)</span> d’homogeneïtat</a></li>
<li class="chapter" data-level="8.3" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-chi2-de-tendència-opcional"><i class="fa fa-check"></i><b>8.3</b> Test <span class="math inline">\(\chi^2\)</span> de tendència (Opcional)</a></li>
<li class="chapter" data-level="8.4" data-path="contrastos-dindependència-i-homogeneïtat.html"><a href="contrastos-dindependència-i-homogeneïtat.html#test-de-la-lliçó-8"><i class="fa fa-check"></i><b>8.4</b> Test de la lliçó 8</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chap-ED.html"><a href="chap-ED.html"><i class="fa fa-check"></i><b>9</b> Introducció a l’estadística multidimensional</a>
<ul>
<li class="chapter" data-level="9.1" data-path="chap-ED.html"><a href="chap-ED.html#poblacions-vectors-aleatoris"><i class="fa fa-check"></i><b>9.1</b> Poblacions: vectors aleatoris</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="chap-ED.html"><a href="chap-ED.html#covariància"><i class="fa fa-check"></i><b>9.1.1</b> Covariància</a></li>
<li class="chapter" data-level="9.1.2" data-path="chap-ED.html"><a href="chap-ED.html#correlació"><i class="fa fa-check"></i><b>9.1.2</b> Correlació</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="chap-ED.html"><a href="chap-ED.html#estadística-descriptiva-mostres"><i class="fa fa-check"></i><b>9.2</b> Estadística descriptiva: Mostres</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="chap-ED.html"><a href="chap-ED.html#covariàncies"><i class="fa fa-check"></i><b>9.2.1</b> Covariàncies</a></li>
<li class="chapter" data-level="9.2.2" data-path="chap-ED.html"><a href="chap-ED.html#correlació-de-pearson"><i class="fa fa-check"></i><b>9.2.2</b> Correlació de Pearson</a></li>
<li class="chapter" data-level="9.2.3" data-path="chap-ED.html"><a href="chap-ED.html#estimació"><i class="fa fa-check"></i><b>9.2.3</b> Estimació</a></li>
<li class="chapter" data-level="9.2.4" data-path="chap-ED.html"><a href="chap-ED.html#correlació-de-spearman"><i class="fa fa-check"></i><b>9.2.4</b> Correlació de Spearman</a></li>
<li class="chapter" data-level="9.2.5" data-path="chap-ED.html"><a href="chap-ED.html#contrastos-de-correlació"><i class="fa fa-check"></i><b>9.2.5</b> Contrastos de correlació</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="chap-ED.html"><a href="chap-ED.html#test-de-la-lliçó-9"><i class="fa fa-check"></i><b>9.3</b> Test de la lliçó 9</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html"><i class="fa fa-check"></i><b>10</b> ANOVA</a>
<ul>
<li class="chapter" data-level="10.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#nocions-bàsiques"><i class="fa fa-check"></i><b>10.1</b> Nocions bàsiques</a></li>
<li class="chapter" data-level="10.2" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#anova-d1-via"><i class="fa fa-check"></i><b>10.2</b> ANOVA d’1 via</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#contrast-bàsic"><i class="fa fa-check"></i><b>10.2.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="10.2.2" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i><b>10.2.2</b> Amb R</a></li>
<li class="chapter" data-level="10.2.3" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#comparacions-posteriors-per-parelles"><i class="fa fa-check"></i><b>10.2.3</b> Comparacions posteriors per parelles</a></li>
<li class="chapter" data-level="10.2.4" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#comprovació-de-les-condicions"><i class="fa fa-check"></i><b>10.2.4</b> Comprovació de les condicions</a></li>
<li class="chapter" data-level="10.2.5" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#test-no-paramètric"><i class="fa fa-check"></i><b>10.2.5</b> Test no paramètric</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#anova-de-blocs"><i class="fa fa-check"></i><b>10.3</b> ANOVA de blocs</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#contrast-bàsic-1"><i class="fa fa-check"></i><b>10.3.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="10.3.2" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#amb-r-1"><i class="fa fa-check"></i><b>10.3.2</b> Amb R</a></li>
<li class="chapter" data-level="10.3.3" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#comparacions-posteriors-per-parelles-1"><i class="fa fa-check"></i><b>10.3.3</b> Comparacions posteriors per parelles</a></li>
<li class="chapter" data-level="10.3.4" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#contrast-no-paramètric"><i class="fa fa-check"></i><b>10.3.4</b> Contrast no paramètric</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#anova-de-2-vies"><i class="fa fa-check"></i><b>10.4</b> ANOVA de 2 vies</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#contrast-bàsic-2"><i class="fa fa-check"></i><b>10.4.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="10.4.2" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#amb-r-2"><i class="fa fa-check"></i><b>10.4.2</b> Amb R</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="chap-ANOVA.html"><a href="chap-ANOVA.html#test-de-la-lliçó-10"><i class="fa fa-check"></i><b>10.5</b> Test de la lliçó 10</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="regressió-lineal.html"><a href="regressió-lineal.html"><i class="fa fa-check"></i><b>11</b> Regressió lineal</a>
<ul>
<li class="chapter" data-level="11.1" data-path="regressió-lineal.html"><a href="regressió-lineal.html#regressió-lineal-simple"><i class="fa fa-check"></i><b>11.1</b> Regressió lineal simple</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="regressió-lineal.html"><a href="regressió-lineal.html#el-model"><i class="fa fa-check"></i><b>11.1.1</b> El model</a></li>
<li class="chapter" data-level="11.1.2" data-path="regressió-lineal.html"><a href="regressió-lineal.html#mínims-quadrats"><i class="fa fa-check"></i><b>11.1.2</b> Mínims quadrats</a></li>
<li class="chapter" data-level="11.1.3" data-path="regressió-lineal.html"><a href="regressió-lineal.html#coeficient-de-determinació"><i class="fa fa-check"></i><b>11.1.3</b> Coeficient de determinació</a></li>
<li class="chapter" data-level="11.1.4" data-path="regressió-lineal.html"><a href="regressió-lineal.html#intervals-de-confiança-dels-coeficients"><i class="fa fa-check"></i><b>11.1.4</b> Intervals de confiança dels coeficients</a></li>
<li class="chapter" data-level="11.1.5" data-path="regressió-lineal.html"><a href="regressió-lineal.html#intervals-de-confiança-per-a-les-estimacions-de-la-variable-dependent"><i class="fa fa-check"></i><b>11.1.5</b> Intervals de confiança per a les estimacions de la variable dependent</a></li>
<li class="chapter" data-level="11.1.6" data-path="regressió-lineal.html"><a href="regressió-lineal.html#té-sentit-una-regressió-lineal"><i class="fa fa-check"></i><b>11.1.6</b> Té sentit una regressió lineal?</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="regressió-lineal.html"><a href="regressió-lineal.html#regressió-lineal-múltiple"><i class="fa fa-check"></i><b>11.2</b> Regressió lineal múltiple</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="regressió-lineal.html"><a href="regressió-lineal.html#mínims-quadrats-1"><i class="fa fa-check"></i><b>11.2.1</b> Mínims quadrats</a></li>
<li class="chapter" data-level="11.2.2" data-path="regressió-lineal.html"><a href="regressió-lineal.html#coeficient-de-determinació-múltiple"><i class="fa fa-check"></i><b>11.2.2</b> Coeficient de determinació múltiple</a></li>
<li class="chapter" data-level="11.2.3" data-path="regressió-lineal.html"><a href="regressió-lineal.html#coeficient-de-determinació-ajustat"><i class="fa fa-check"></i><b>11.2.3</b> Coeficient de determinació ajustat</a></li>
<li class="chapter" data-level="11.2.4" data-path="regressió-lineal.html"><a href="regressió-lineal.html#intervals-de-confiança-per-als-coeficients"><i class="fa fa-check"></i><b>11.2.4</b> Intervals de confiança per als coeficients</a></li>
<li class="chapter" data-level="11.2.5" data-path="regressió-lineal.html"><a href="regressió-lineal.html#intervals-de-confiança-per-a-les-estimacions-de-la-variable-resposta"><i class="fa fa-check"></i><b>11.2.5</b> Intervals de confiança per a les estimacions de la variable resposta</a></li>
<li class="chapter" data-level="11.2.6" data-path="regressió-lineal.html"><a href="regressió-lineal.html#lanova-de-la-regressió-lineal-múltiple"><i class="fa fa-check"></i><b>11.2.6</b> L’ANOVA de la regressió lineal múltiple</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="regressió-lineal.html"><a href="regressió-lineal.html#test-de-la-lliçó-11"><i class="fa fa-check"></i><b>11.3</b> Test de la lliçó 11</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II v.2021</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="contrastos-dindependència-i-homogeneïtat" class="section level1" number="8">
<h1><span class="header-section-number">Tema 8</span> Contrastos d’independència i homogeneïtat</h1>
<p>En els <strong>contrastos d’independència</strong> de dues variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span>, la hipòtesi nul·la és</p>
<blockquote>
<p>no hi ha cap relació entre <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span>,</p>
</blockquote>
<p>és a dir, que <strong>són independents</strong>. Quan traduïm la independència de dues variables en termes de</p>
<blockquote>
<p>“la probabilitat de la intersecció és el producte de probabilitats”,</p>
</blockquote>
<p>resulta que un contrast d’independència és un tipus concret de contrast de bondat d’ajust.</p>
<p>En els <strong>contrastos d’homogeneïtat</strong> de dues variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span>, la hipòtesi nul·la és</p>
<blockquote>
<p>la distribució de <span class="math inline">\(Y\)</span> condicionada a cada un dels valors que pot prendre <span class="math inline">\(X\)</span> és sempre la mateixa,</p>
</blockquote>
<p>que és una altra manera de dir que <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> <strong>són independents</strong>. Per tant, els contrastos d’homogeneïtat són formalment contrastos d’independència, però difereixen en la forma com s’hi recull la mostra:</p>
<ul>
<li><p>En un contrast d’independència, la mostra és <strong>transversal</strong>: es pren una mostra de la població on estan definides <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> i es mesuren les dues variables sobre els individus de la mostra.</p></li>
<li><p>En un contrast d’homogeneïtat, la mostra és <strong>estratificada</strong>: es classifiquen els individus de la població segons el seu valor de <span class="math inline">\(X\)</span>, es pren una mostra independent de cada una d’aquestes classes definides pels valors de <span class="math inline">\(X\)</span>, amb totes aquestes mostres de mides fixades d’antuvi, i es mesura <span class="math inline">\(Y\)</span> sobre tots aquests individus.</p></li>
</ul>
<div id="test-chi2-dindependència" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> Test <span class="math inline">\(\chi^2\)</span> d’independència</h2>
<p>Suposem que tenim dues variables aleatòries <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> que només poden prendre valors <span class="math inline">\(X_{1},\ldots,X_{s}\)</span> i <span class="math inline">\(Y_{1},\ldots,Y_{t}\)</span>, respectivament. Les considerarem qualitatives i direm a aquests <span class="math inline">\(X_i\)</span> i <span class="math inline">\(Y_j\)</span> els seus nivells, però poden ser ordinals o quantitatives discretes. L’important és que només poden prendre un conjunt finit de valors cadascuna.</p>
<p>Volem contrastar si <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són independents, és a dir
<span class="math display">\[
\begin{array}{l}
\hspace{-2ex}P(X=X_i\mid Y=Y_j)=P(X=X_i\mid Y=Y_{j&#39;})=P(X=X_i)\text{ per a tots $i,j,j&#39;$}\\ 
\hspace{-2ex}P(Y=Y_j\mid X=X_i)=P(Y=Y_j\mid X=X_{i&#39;})=P(Y=Y_j)\text{ per a tots $i,i&#39;,j$}
\end{array}
\]</span>
o equivalentment
<span class="math display">\[
P(X=X_i,Y=Y_j)=P(X=X_i)\cdot P(Y=Y_j)\text{ per a tots $i,j$}
\]</span></p>
<p>El contrast serà
<span class="math display">\[
\left\{\begin{array}{l}
H_0: \mbox{$X$ i $Y$ són independents}\\
H_1: \mbox{$X$ i $Y$ no són independents}
\end{array}
\right.
\]</span></p>
<p>Sovint en lloc de dir que “<span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> no són independents” o “<span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són dependents”, es diu que “hi ha <strong>associació</strong> entre <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span>”.</p>

<div class="rmdnote">
Recordau que, en general, la hipòtesi nul·la representa, en el context del contrast, que “no passa res”. En els contrastos d’independència això correspon a “no hi ha cap relació entre <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span>”, és a dir, que són independents.
</div>
<p>Fixem-nos ara que la caracterització de la independència com a
<span class="math display">\[
P(X=X_i,Y=Y_j)=P(X=X_i)\cdot P(Y=Y_j)\text{ per a tots $i,j$}
\]</span>
ens permet entendre el contrast d’independència com un contrast de bondat d’ajust, amb hipòtesi nul·la
<span class="math display">\[
H_0: P(X=X_i,Y=Y_j)=P(X=X_i)\cdot P(Y=Y_j)\text{ per a tots $i,j$}
\]</span>
i hipòtesi alternativa
<span class="math display">\[
H_1: P(X=X_i,Y=Y_j)\neq P(X=X_i)\cdot P(Y=Y_j)\text{ per a alguns $i,j$}
\]</span></p>

<div class="rmdcaution">
<p>De la mateixa manera que el contrari d’aprovar totes les assignatures no és suspendre totes les assignatures, sinó suspendre’n almenys una, el contrari de</p>
<blockquote>
<p>per a tots els valors de <span class="math inline">\(i\)</span> i <span class="math inline">\(j\)</span>, <span class="math inline">\(P(X=X_i,Y=Y_j)=P(X=X_i)\cdot P(Y=Y_j)\)</span></p>
</blockquote>
<p>no és</p>
<blockquote>
<p>per a tots els valors de <span class="math inline">\(i\)</span> i <span class="math inline">\(j\)</span>, <span class="math inline">\(P(X=X_i,Y=Y_j)\neq P(X=X_i)\cdot P(Y=Y_j)\)</span></p>
</blockquote>
<p>sinó</p>
<blockquote>
<p>per almenys un <span class="math inline">\(i\)</span> i un <span class="math inline">\(j\)</span>, <span class="math inline">\(P(X=X_i,Y=Y_j)\neq P(X=X_i)\cdot P(Y=Y_j)\)</span></p>
</blockquote>
</div>
<p>Hi farem servir un test <span class="math inline">\(\chi^2\)</span>.</p>

<div class="rmdnote">
El contrast d’igualtat de dues proporcions és un cas particular de contrast d’independència: que l’esdeveniment “Èxit” sigui independent de la variable.
</div>

<div class="example">
<p><span id="exm:tosfumar" class="example"><strong>Exemple 8.1  </strong></span>En un estudi es volgué determinar si hi ha associació entre l’hàbit de fumar i patir tos nocturna entre els nins.</p>
</div>
<p>S’entrevistà una mostra de 2847 nins i nines de 12 anys i es recollí informació sobre el seu estatus de fumador i si patien de tos nocturna o no. S’obtingueren els resultats següents:
<span class="math display">\[
\begin{array}{l}
\hphantom{No fumador ocasional un }\text{Fumador}\\
\begin{array}{l|ccc|c}
&amp; \text{No fumador} &amp; \text{Ocasional} &amp; \text{Regular} &amp; \text{Total} \\\hline
\text{Tos} &amp; 266 &amp; 395 &amp; 80 &amp; 741\\
\text{No tos}&amp; 1037 &amp; 977 &amp; 92 &amp; 2106\\\hline
\text{Total} &amp;1303 &amp; 1372 &amp; 172 &amp; 2847
\end{array}
\end{array}
\]</span></p>
<p>En aquesta situació:</p>
<p><em>Variables aleatòries d’interès</em>:</p>
<ul>
<li><span class="math inline">\(X\)</span>: “Prenem un nin i anotam si té tos nocturna o no”</li>
<li><span class="math inline">\(Y\)</span>: “Prenem un nin i anotam el seu estatus de fumador”</li>
</ul>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_0: \mbox{$X$ i $Y$ són independents}\\
H_1: \mbox{Hi ha associació entre $X$ i $Y$}
\end{array}
\right.
\]</span></p>
<p>Anem a traduir ara un contrast d’independència com l’anterior en un contrast d’igualtat de distribucions de probabilitat. Diguem
<span class="math display">\[
\begin{array}{c}
p_{ij}=P(X=X_i, Y=Y_j)\\
p_i=P(X=X_i)\quad
q_{j}=P(Y=Y_j)
\end{array}
\]</span>
El test d’independència equival a contrastar
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: p_{ij}=p_i \cdot q_j \text{ per a tots } 1\leqslant i \leqslant s,\ 1\leqslant j\leqslant t \\
H_1: \mbox{No totes aquestes igualtats són vertaderes}
\end{array}
\right.
\]</span></p>
<p>El decidirem amb un test <span class="math inline">\(\chi^2\)</span>. Els passos concrets seran els següents:</p>
<ol style="list-style-type: decimal">
<li>Mesuram les variables aleatòries sobre una mostra aleatòria simple de <span class="math inline">\(n\)</span> subjectes, i obtenim una taula de contingència de freqüències absolutes com la següent (on cada <span class="math inline">\(n_{i,j}\)</span> indica el nombre de subjectes amb <span class="math inline">\(X=X_i\)</span> i <span class="math inline">\(Y=Y_j\)</span>; <span class="math inline">\(n_{i\bullet}\)</span> indica el nombre de subjectes amb <span class="math inline">\(X=X_i\)</span>, és a dir, el nombre total de subjectes de la filera <span class="math inline">\(i\)</span>; i <span class="math inline">\(n_{\bullet j}\)</span> indica el nombre de subjectes amb <span class="math inline">\(Y=Y_j\)</span>, és a dir, el nombre total de subjectes de la columna <span class="math inline">\(j\)</span>):</li>
</ol>
<p><span class="math display">\[
\begin{array}{c|cccccc|c}
X\backslash Y &amp; Y_1 &amp; Y_2 &amp; \ldots &amp; Y_j &amp; \ldots
&amp; Y_t &amp; \text{Total} \\
\hline X_1 &amp; n_{11} &amp; n_{12} &amp; \ldots &amp; n_{1j} &amp; \ldots &amp; n_{1t} &amp;
n_{1
\bullet} \\ X_2 &amp; n_{21} &amp; n_{22} &amp; \ldots &amp; n_{2j} &amp; \ldots &amp;
n_{2t} &amp;
n_{2 \bullet} \\ \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp;
\vdots &amp;
\vdots &amp; \vdots \\ X_i &amp; n_{i1} &amp; n_{i2} &amp; \ldots &amp; n_{ij} &amp;
\ldots &amp;
n_{it} &amp; n_{i \bullet} \\ \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp;
\vdots &amp;
\vdots &amp; \vdots &amp; \vdots \\ X_s &amp; n_{s1} &amp; n_{s2} &amp; \ldots &amp;
n_{sj} &amp;
\ldots &amp; n_{st} &amp; n_{s \bullet} \\ \hline \text{Total} &amp; n_{\bullet
1} &amp;
n_{\bullet 2} &amp; \ldots &amp; n_{\bullet j} &amp; \ldots &amp; n_{\bullet t} &amp;
n 
\end{array}
\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li><p>Estimam cada <span class="math inline">\(p_i\)</span> amb <span class="math inline">\({n_{i\bullet}}/{n}\)</span> i cada <span class="math inline">\(q_j\)</span> amb <span class="math inline">\({n_{\bullet j}}/{n}\)</span></p></li>
<li><p>Si les variables aleatòries fossin independents, les probabilitats teòriques serien
<span class="math display">\[
p_{ij}=\frac{n_{i\bullet}}{n}\cdot \frac{n_{\bullet j}}{n}
\]</span>
i per tant la freqüència esperada de cada parell <span class="math inline">\((X_i,Y_j)\)</span> si les variables aleatòries són independents és
<span class="math display">\[
esp_{ij}=p_{ij}\cdot n=\dfrac{n_{i\bullet}}{n}\cdot \dfrac{n_{\bullet j}}{n}\cdot n=\dfrac{n_{i\bullet}\cdot n_{\bullet j}}{n}
\]</span></p></li>
<li><p>L’estadístic del test <span class="math inline">\(\chi^2\)</span> és doncs
<span class="math display">\[
\chi^2=\sum\limits_{i=1}^s\sum\limits_{j=1}^t \frac{ ( n_{ij}- esp_{ij})^2 } {esp_{ij}}
\]</span></p>
<p>Arribats en aquest punt, el Teorema <a href="chap-bondat.html#thm:khi2BA">7.1</a> ens diu que:</p></li>
</ol>

<div class="theorem">
<p><span id="thm:khi2indep" class="theorem"><strong>Teorema 8.1  </strong></span>Suposem que <span class="math inline">\(n\)</span> és gran (diguem <span class="math inline">\(n\geqslant 30\)</span>) i que se satisfà la <strong>Regla de Cochran</strong>: per a cada <span class="math inline">\(i,j\)</span>,
<span class="math display">\[
esp_{ij}=\frac{n_{i\bullet}\cdot n_{\bullet j}}{n}\geqslant 5
\]</span>
Aleshores, si les variables <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són independents, l’estadístic
<span class="math display">\[
\chi^2=\sum\limits_{i=1}^s\sum\limits_{j=1}^t \frac{ ( n_{ij}- esp_{ij})^2 } {esp_{ij}}
\]</span>
segueix (aproximadament) una llei <span class="math inline">\(\chi^2\)</span> amb <span class="math inline">\((s-1) \cdot (t -1)\)</span> graus de llibertat.</p>
</div>

<div class="rmdnote">
D’on surt aquest nombre de graus de llibertat? Vegem, hem estimat les <span class="math inline">\(p_i\)</span> i les <span class="math inline">\(q_j\)</span>, i per tant hem estimat <span class="math inline">\(s+t-2\)</span> paràmetres (fixau-vos que en realitat només hem estimat <span class="math inline">\(p_1,\ldots,p_{s-1}\)</span> i <span class="math inline">\(q_1,\ldots,q_{t-1}\)</span>, ja que <span class="math inline">\(p_s\)</span> i <span class="math inline">\(q_t\)</span> queden fixats per la regla “suma de probabilitats igual a 1”). Per tant
el nombre de graus de llibertat és el nombre de classes, <span class="math inline">\(st\)</span> (una per cada combinació <span class="math inline">\((X_i,Y_j)\)</span> d’un possible valor de <span class="math inline">\(X\)</span> i un possible valor de <span class="math inline">\(Y\)</span>) menys 1 i menys el nombre de paràmetres estimats:
<span class="math display">\[
\mbox{graus de llibertat}=st-1-(s+t-2)=(s-1)(t-1)
\]</span>
</div>

<div class="rmdimportant">
Fixau-vos que el Teorema <a href="contrastos-dindependència-i-homogeneïtat.html#thm:khi2indep">8.1</a> és un cas particular del Teorema <a href="chap-bondat.html#thm:khi2BA">7.1</a>, i per tant les hipòtesis per poder emprar el test <span class="math inline">\(\chi^2\)</span> en aquest context són les mateixes que en el cas general: mostra de mida com a mínim 30 i totes les freqüències esperades més grans o iguals que 5.
</div>
<ol start="5" style="list-style-type: decimal">
<li>Si <span class="math inline">\(\chi_0^2\)</span> és el valor que pren l’estadístic de contrast a la nostra mostra, el p-valor del contrast és
<span class="math display">\[
\text{p-valor}=P(\chi_{(s-1) \cdot (t -1)}^2\geqslant \chi_0^2)
\]</span></li>
</ol>

<div class="example">
<p><span id="exm:tosfumar2" class="example"><strong>Exemple 8.2  </strong></span>Continuem amb l’Exemple <a href="contrastos-dindependència-i-homogeneïtat.html#exm:tosfumar">8.1</a>. Ja teníem les variables i el contrast. Les freqüències observades són</p>
</div>
<p><span class="math display">\[
\begin{array}{l}
\hphantom{No fumador ocasional un }\text{Fumador}\\
\begin{array}{l|ccc|c}
&amp; \text{No fumador} &amp; \text{Ocasional} &amp; \text{Regular} &amp; \text{Total} \\\hline
\text{Tos} &amp; 266 &amp; 395 &amp; 80 &amp; 741\\
\text{No tos}&amp; 1037 &amp; 977 &amp; 92 &amp; 2106\\\hline
\text{Total} &amp;1303 &amp; 1372 &amp; 172 &amp; 2847
\end{array}
\end{array}
\]</span></p>
<p>La mida de la mostra és gran. Calculem les freqüències esperades, per veure si són totes més grans o iguals que 5.</p>
<p><span class="math display">\[
\begin{array}{l|ccc}
&amp; \text{No fumador} &amp; \text{Ocasional} &amp; \text{Regular}  \\\hline
\text{Tos} &amp; 741\cdot 1303/2847 &amp; 741\cdot 1372/2847 &amp; 741\cdot 172/2847  \\
\text{No tos}&amp; 2106\cdot 1303/2847 &amp; 2106\cdot 1372/2847 &amp; 2106\cdot 172/2847 
\end{array}
\]</span>
Operant:
<span class="math display">\[
\begin{array}{l|ccc}
&amp; \text{No fumador} &amp; \text{Ocasional} &amp; \text{Regular}  \\\hline
\text{Tos} &amp; 339.14 &amp;  357.1 &amp; 44.77  \\
\text{No tos}&amp; 963.86 &amp; 1014.9 &amp; 127.23 
\end{array}
\]</span></p>
<p>Són totes prou grans. Per tant l’estadístic de contrast
<span class="math display">\[
\chi^2=\sum_{i=1}^s\sum_{j=1}^t \frac{(n_{ij}-esp_{ij})^2}{esp_{ij}}
\]</span></p>
<p>(on <span class="math inline">\(s=2\)</span> i <span class="math inline">\(t=3\)</span>) seguirà una distribució <span class="math inline">\(\chi^2_{(s-1)(t-1)}=\chi^2_2\)</span>.</p>
<p><em>Valor de l’estadístic de contrast</em>:</p>
<p><span class="math display">\[
\chi_0^2=\frac{(266-339.14)^2}{339.14}+\frac{(395-357.1)^2}{357.1}+\cdots=64.25
\]</span></p>
<p>Calculem-lo amb R:</p>
<ul>
<li>Entram la taula:</li>
</ul>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb406-1" aria-hidden="true" tabindex="-1"></a>Taula<span class="ot">=</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">266</span>,<span class="dv">395</span>,<span class="dv">80</span>,<span class="dv">1037</span>,<span class="dv">977</span>,<span class="dv">92</span>),<span class="at">nrow=</span><span class="dv">2</span>,<span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb406-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb406-2" aria-hidden="true" tabindex="-1"></a>Taula</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]  266  395   80
## [2,] 1037  977   92</code></pre>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb408-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">sum</span>(Taula)</span>
<span id="cb408-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb408-2" aria-hidden="true" tabindex="-1"></a>n</span></code></pre></div>
<pre><code>## [1] 2847</code></pre>
<ul>
<li>Les <span class="math inline">\(n_{i\bullet}\)</span> són les sumes de les fileres:</li>
</ul>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb410-1" aria-hidden="true" tabindex="-1"></a>n.i.bolla<span class="ot">=</span><span class="fu">rowSums</span>(Taula)</span>
<span id="cb410-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb410-2" aria-hidden="true" tabindex="-1"></a>n.i.bolla</span></code></pre></div>
<pre><code>## [1]  741 2106</code></pre>
<ul>
<li>Les <span class="math inline">\(n_{\bullet j}\)</span> són les sumes de les columnes:</li>
</ul>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb412-1" aria-hidden="true" tabindex="-1"></a>n.bolla.j<span class="ot">=</span><span class="fu">colSums</span>(Taula)</span>
<span id="cb412-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb412-2" aria-hidden="true" tabindex="-1"></a>n.bolla.j</span></code></pre></div>
<pre><code>## [1] 1303 1372  172</code></pre>
<ul>
<li>La matriu de les <span class="math inline">\((n_{i\bullet}n_{\bullet j}/n)_{i,j}\)</span> s’obté fent el producte matricial
<span class="math display">\[
\begin{array}{l}
\displaystyle \frac{1}{n}\left(\begin{array}{c}
n_{1\bullet}\\
n_{2\bullet}\\
\vdots\\
n_{s\bullet}
\end{array}\right)\cdot
\big(n_{\bullet 1},n_{\bullet 2},\ldots,n_{\bullet t}\big)\\
\qquad
\displaystyle =
\left(
\begin{array}{cccc}
\frac{n_{1\bullet}n_{\bullet 1}}{n} &amp; \frac{n_{1\bullet}n_{\bullet 2}}{n} &amp; \ldots &amp; \frac{n_{1\bullet}n_{\bullet t}}{n}\\
\frac{n_{2\bullet}n_{\bullet 1}}{n} &amp; \frac{n_{2\bullet}n_{\bullet 2}}{n} &amp; \ldots &amp; \frac{n_{2\bullet}n_{\bullet t}}{n}\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
\frac{n_{s\bullet}n_{\bullet 1}}{n} &amp; \frac{n_{s\bullet}n_{\bullet 2}}{n} &amp; \ldots &amp; \frac{n_{s\bullet}n_{\bullet t}}{n}
\end{array}
\right)
\end{array}
\]</span></li>
</ul>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb414-1" aria-hidden="true" tabindex="-1"></a>Freqs.Esp<span class="ot">=</span>(<span class="dv">1</span><span class="sc">/</span>n)<span class="sc">*</span>n.i.bolla<span class="sc">%*%</span><span class="fu">t</span>(n.bolla.j)</span>
<span id="cb414-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb414-2" aria-hidden="true" tabindex="-1"></a>Freqs.Esp</span></code></pre></div>
<pre><code>##         [,1]      [,2]      [,3]
## [1,] 339.137  357.0959  44.76712
## [2,] 963.863 1014.9041 127.23288</code></pre>
<ul>
<li>L’estadístic de contrast:</li>
</ul>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb416-1" aria-hidden="true" tabindex="-1"></a>X2<span class="ot">=</span><span class="fu">sum</span>((Taula<span class="sc">-</span>Freqs.Esp)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>Freqs.Esp)</span>
<span id="cb416-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb416-2" aria-hidden="true" tabindex="-1"></a>X2</span></code></pre></div>
<pre><code>## [1] 64.24672</code></pre>
<p><em>p-valor</em>: <span class="math inline">\(P(\chi^2_2\geqslant 64.25)=\texttt{1-pchisq(64.25,2)}=1.1\cdot 10^{-14}\)</span></p>
<p><em>Conclusió</em>: Hem trobat evidència estadísticament significativa que hi ha associació entre l’estatus de fumador d’un nin i que pateixi tos nocturna (test <span class="math inline">\(\chi^2\)</span>, p-valor 10<sup>-14</sup>).</p>
<p>Podem efectuar un test <span class="math inline">\(\chi^2\)</span> d’independència aplicant la funció <code>chisq.test</code> a la taula de freqüències absolutes:</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb418-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(Taula)</span></code></pre></div>
<pre><code>## 
## 	Pearson&#39;s Chi-squared test
## 
## data:  Taula
## X-squared = 64.247, df = 2, p-value = 1.119e-14</code></pre>

<div class="example">
<p><span id="exm:CCV" class="example"><strong>Exemple 8.3  </strong></span>Volem contrastar si hi ha associació entre el grau de compliment del calendari de vacunacions (CCV) dels fills i el nivell sociocultural dels pares.</p>
</div>
<p>La taula següent mostra la classificació d’una mostra de 444 nins i nines segons el seu CCV i el nivell sociocultural dels pares:
<span class="math display">\[
\begin{array}{l}
\hphantom{Compli CCV BaixBB}\text{Nivell sociocultural}\\
\begin{array}{r|ccc|l}
\text{Compliment CCV} &amp;\text{Baix}&amp; \text{Mitjà} &amp;\text{Alt} &amp;\text{Total}\\ \hline
\text{Baix} &amp;38 &amp;76 &amp;79 &amp; 193\\
\text{Mitjà-baix}&amp; 2&amp; 41&amp; 92 &amp; 135\\
\text{Mitjà-alt}&amp; 2&amp; 21&amp; 50 &amp; 73\\
\text{Alt}&amp; 0 &amp;12&amp; 31 &amp; 43\\ \hline
\text{Total} &amp; 42 &amp; 150 &amp; 252 &amp; 444
\end{array}
\end{array}
\]</span></p>
<p><em>Variable aleatòries d’interès</em>:</p>
<ul>
<li><span class="math inline">\(X\)</span>: “Prenem un nin i anotam el seu grau de compliment del CCV”</li>
<li><span class="math inline">\(Y\)</span>: “Prenem un nin i anotam el nivell sociocultural dels pares”</li>
</ul>
<p><em>Contrast</em>:
<span class="math display">\[
\left\{\begin{array}{l}
H_0: \mbox{$X$ i $Y$ són independents}\\
H_1: \mbox{Hi ha associació entre $X$ i $Y$}
\end{array}
\right.
\]</span></p>
<p>Fem un test <span class="math inline">\(\chi^2\)</span> amb R:</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb420-1" aria-hidden="true" tabindex="-1"></a>TaulaCCV<span class="ot">=</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">38</span>,<span class="dv">76</span>,<span class="dv">79</span>,<span class="dv">2</span>,<span class="dv">41</span>,<span class="dv">92</span>,<span class="dv">2</span>,<span class="dv">21</span>,<span class="dv">50</span>,<span class="dv">0</span>,<span class="dv">12</span>,<span class="dv">31</span>), </span>
<span id="cb420-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb420-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">nrow=</span><span class="dv">4</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb420-3"><a href="contrastos-dindependència-i-homogeneïtat.html#cb420-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(TaulaCCV)</span></code></pre></div>
<pre><code>## Warning in chisq.test(TaulaCCV): Chi-squared approximation may be incorrect</code></pre>
<pre><code>## 
## 	Pearson&#39;s Chi-squared test
## 
## data:  TaulaCCV
## X-squared = 56.378, df = 6, p-value = 2.441e-10</code></pre>
<p>R ens avisa que no es compleixen les condicions per usar el test <span class="math inline">\(\chi^2\)</span>; segurament hi ha freqüències esperades petites. Vegem-ho, i aprofitarem per comprovar-ho amb R:</p>
<ul>
<li>Les <span class="math inline">\(n_{i\bullet}\)</span> són les sumes de les fileres:</li>
</ul>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb423-1" aria-hidden="true" tabindex="-1"></a>Freq.CCV<span class="ot">=</span><span class="fu">rowSums</span>(TaulaCCV)</span>
<span id="cb423-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb423-2" aria-hidden="true" tabindex="-1"></a>Freq.CCV</span></code></pre></div>
<pre><code>## [1] 193 135  73  43</code></pre>
<ul>
<li>Les <span class="math inline">\(n_{\bullet j}\)</span> són les sumes de les columnes:</li>
</ul>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb425-1" aria-hidden="true" tabindex="-1"></a>Freq.NSC<span class="ot">=</span><span class="fu">colSums</span>(TaulaCCV)</span>
<span id="cb425-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb425-2" aria-hidden="true" tabindex="-1"></a>Freq.NSC</span></code></pre></div>
<pre><code>## [1]  42 150 252</code></pre>
<ul>
<li>La matriu de les <span class="math inline">\(n_{i\bullet}n_{\bullet j}/n\)</span>:</li>
</ul>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb427-1" aria-hidden="true" tabindex="-1"></a>Freqs.Esp<span class="ot">=</span>(<span class="dv">1</span><span class="sc">/</span><span class="fu">sum</span>(TaulaCCV))<span class="sc">*</span>Freq.CCV<span class="sc">%*%</span><span class="fu">t</span>(Freq.NSC)</span>
<span id="cb427-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb427-2" aria-hidden="true" tabindex="-1"></a>Freqs.Esp</span></code></pre></div>
<pre><code>##           [,1]     [,2]      [,3]
## [1,] 18.256757 65.20270 109.54054
## [2,] 12.770270 45.60811  76.62162
## [3,]  6.905405 24.66216  41.43243
## [4,]  4.067568 14.52703  24.40541</code></pre>
<p>Efectivament, l’entrada (4,1) és menor que 5.</p>
<p>Farem servir el mètode de Montecarlo:</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb429-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb429-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb429-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(TaulaCCV,<span class="at">simulate.p.value=</span><span class="cn">TRUE</span>,<span class="at">B=</span><span class="dv">5000</span>)</span></code></pre></div>
<pre><code>## 
## 	Pearson&#39;s Chi-squared test with simulated p-value (based on 5000
## 	replicates)
## 
## data:  TaulaCCV
## X-squared = 56.378, df = NA, p-value = 2e-04</code></pre>
<p><em>Conclusió</em>: Hem trobat evidència estadísticament significativa que hi ha associació entre el grau de compliment del
calendari de vacunacions d’un nin i el nivell sociocultural dels seus pares (test <span class="math inline">\(\chi^2\)</span> de Montecarlo, p-valor 0.0002).</p>
</div>
<div id="test-chi2-dhomogeneïtat" class="section level2" number="8.2">
<h2><span class="header-section-number">8.2</span> Test <span class="math inline">\(\chi^2\)</span> d’homogeneïtat</h2>
<p>En un <strong>contrast d’homogeneïtat de proporcions</strong>, tenim una variable aleatòria <span class="math inline">\(X\)</span> que pot prendre els valors <span class="math inline">\(X_1,\ldots,X_k\)</span> i una variable aleatòria de Bernoulli <span class="math inline">\(Y\)</span> que pot prendre els valors “Èxit” i “Fracàs”. Per a cada <span class="math inline">\(i=1,\ldots,k\)</span>, diguem <span class="math inline">\(p_i=P(Y=\text{Èxit}|X=X_i)\)</span>. És a dir, <span class="math inline">\(p_i\)</span> és la probabilitat que <span class="math inline">\(Y\)</span> doni Èxit sobre un individu per al qual <span class="math inline">\(X\)</span> val <span class="math inline">\(X_i\)</span>.</p>
<p>Volem contrastar si aquestes probabilitats <span class="math inline">\(p_1,\ldots,p_k\)</span> són totes iguals o no. El contrast és, doncs,
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: \text{ $p_1=\cdots=p_k$}\\
H_1: \text{ No totes les $p_i$ són iguals}
\end{array} 
\right.
\]</span></p>
<p>Per efectuar el contrast, per a cada <span class="math inline">\(i=1,\ldots,k\)</span> prenem una mostra aleatòria simple d’individus per als quals <span class="math inline">\(X\)</span> val <span class="math inline">\(X_i\)</span>, independents cada una de les altres.</p>
<p>Com que dir que
<span class="math display">\[
P(Y=\text{Èxit}|X=X_1)=\cdots=P(Y=\text{Èxit}|X=X_k)
\]</span>
és exactament el mateix que dir que <span class="math inline">\(X\)</span> i <span class="math inline">\(Y\)</span> són independents, el contrast d’homogeneïtat que hem plantejat és equivalent a
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: \text{ $X$ i $Y$ són independents}\\
H_1: \text{ $X$ i $Y$ no són independents}
\end{array} 
\right.
\]</span></p>
<p>Però el disseny de l’experiment és diferent:</p>

<div class="rmdimportant">
<ul>
<li><p>En un <strong>contrast d’independència</strong> prenem una mostra <strong>transversal</strong> de la població, sense controlar el nombre de subjectes que hi surten de cada nivell <span class="math inline">\(X_i\)</span>.</p></li>
<li><p>En un <strong>contrast d’homogeneïtat</strong> prenem una mostra <strong>estratificada</strong>, és a dir, una mostra independent de cada nivell <span class="math inline">\(X_i\)</span> de <span class="math inline">\(X\)</span>, triant <em>a priori</em> el nombre de subjectes de cada un d’aquests nivells; per exemple, imposant que totes aquestes mostres tenguin la mateixa mida, o que la mida de cada mostra sigui proporcional al nombre d’individus de la població sobre els que <span class="math inline">\(X\)</span> val <span class="math inline">\(X_i\)</span>.</p></li>
</ul>
</div>

<div class="example">
<p><span id="exm:colesterolhom" class="example"><strong>Exemple 8.4  </strong></span>Volem comparar 3 tractaments per baixar el nivell de colesterol, A, B i C, per veure si tenen taxes d’èxit diferents. En una primera aproximació, entendrem com a “Èxit” que el nivell de colesterol baixi dels 240 mg/dl a les 5 setmanes de tractament. En un assaig clínic, assignam cada tractament a 100 pacients amb colesterol alt escollits de manera independent uns dels altres, i anotam si el tractament ha tengut èxit.</p>
</div>
<p>Els resultats són</p>
<p><span class="math display">\[
\begin{array}{l}
\hphantom{FracasAAa}\text{Tractament}\\
\begin{array}{l|ccc|c}
&amp; A &amp; B &amp; C &amp; \text{Total} \\\hline
\text{Èxit} &amp; 43 &amp; 61 &amp; 53 &amp; 157\\
\text{Fracàs} &amp; 57 &amp; 39 &amp; 47 &amp; 143\\\hline
\text{Total} &amp; 100 &amp; 100 &amp; 100 &amp; 300 
\end{array}
\end{array}
\]</span></p>
<p>Volem contrastar si la probabilitat d’èxit de cada tractament és la mateixa o no. Fixem-nos que és un contrast d’homogeneïtat, perquè hem pres una mostra de mida prefixada de cada tractament.</p>

<div class="rmdnote">
Seria un contrast d’independència si haguéssim pres 300 malalts d’hipercolesterolèmia que estiguessin prenent algun d’aquests tractaments i haguéssim anotat de cada un quin tractament pren i si ha tengut èxit. Amb una mostra transversal obtinguda d’aquesta darrera manera, hi havia el risc que algun tractament fos seguit per molt pocs, o fins i tot cap, malalt.
</div>
<p><em>Variables aleatòries</em>: En realitat, aquí tendríem dues interpretacions correctes. Per una banda, la usual, en termes de dues variables mesurades sobre els mateixos individus:</p>
<ul>
<li><p><span class="math inline">\(X\)</span>: “Prenem un pacient i anotam quin tractament segueix”</p></li>
<li><p><span class="math inline">\(Y\)</span>: “Prenem un pacient i anotam si al cap de 5 setmanes el seu nivell de colesterol està per davall dels 240 mg/dl”</p></li>
</ul>
<p>Però d’altra banda, tal i com hem pres la mostra, seria perfectament vàlid entendre que les variables aleatòries en joc són:</p>
<ul>
<li><p><span class="math inline">\(Y_A\)</span>: “Prenem un pacient tractat amb A i anotam si al cap de 5 setmanes el seu nivell de colesterol està per davall dels 240 mg/dl”</p></li>
<li><p><span class="math inline">\(Y_B\)</span>: “Prenem un pacient tractat amb B i anotam si al cap de 5 setmanes el seu nivell de colesterol està per davall dels 240 mg/dl”</p></li>
<li><p><span class="math inline">\(Y_C\)</span>: “Prenem un pacient tractat amb C i anotam si al cap de 5 setmanes el seu nivell de colesterol està per davall dels 240 mg/dl”</p></li>
</ul>
<p>En aquest cas, les variables estan definides sobre poblacions diferents.</p>

<div class="rmdnote">
<p>Dos comentaris:</p>
<ul>
<li><p>Als contrastos d’independència com el de l’Exemple <a href="contrastos-dindependència-i-homogeneïtat.html#exm:tosfumar">8.1</a>, la segona interpretació és incorrecta, ja que allà sí que preníem una mostra transversal de nins i sobre cada un d’ells miràvem dues coses. En canvi, aquí podem entendre que prenem malalts de tres poblacions diferents i mesuram sobre ells una cosa, la qual cosa defineix tres variables diferents.</p></li>
<li><p>Si volguéssim comparar taxes d’èxit de coses diferents sobre poblacions diferents per mitjà d’un contrast d’homogeneïtat, la interpretació en termes de dues variables <span class="math inline">\(X,Y\)</span> mesurades sobre una mateixa població quedaria una mica artificial.</p>
<p>Imaginau per exemple que us deman que contrasteu si són iguals o diferents les proporcions de</p>
<ul>
<li>Estudiants de Matemàtiques I que enguany aprovaren l’assignatura</li>
<li>Malalts d’hipercolesterolèmia sobre els quals el tractament A és efectiu</li>
<li>Nins fumadors ocasionals amb tos nocturna</li>
</ul>
<p>A veure com vos ho faríeu per plantejar-ho en termes de dues variables, una <span class="math inline">\(X\)</span> que digui què miram i una <span class="math inline">\(Y\)</span> que doni “Èxit” o “Fracàs”, i que no us quedàs un nyap de redacció.<br />
</p></li>
</ul>
</div>
<p><em>Contrast</em>: Si diem <span class="math inline">\(p_A\)</span>, <span class="math inline">\(p_B\)</span> i <span class="math inline">\(p_C\)</span> a les probabilitats que un pacient tractat amb A, B o C, respectivament, davalli dels 240 mg/dl de colesterol al cap de 5 setmanes de tractament,</p>
<p><span class="math display">\[
\left\{\begin{array}{l}
H_0: p_A=p_B=p_C\\
H_1: \mbox{No és veritat que $p_A=p_B=p_C$}
\end{array}\right.
\]</span></p>
<ul>
<li>Emprarem un test <span class="math inline">\(\chi^2\)</span>:</li>
</ul>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb431-1" aria-hidden="true" tabindex="-1"></a>TaulaC<span class="ot">=</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">43</span>,<span class="dv">61</span>,<span class="dv">53</span>,<span class="dv">57</span>,<span class="dv">39</span>,<span class="dv">47</span>), <span class="at">nrow=</span><span class="dv">2</span> ,<span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb431-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb431-2" aria-hidden="true" tabindex="-1"></a>TaulaC</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]   43   61   53
## [2,]   57   39   47</code></pre>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb433-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(TaulaC)</span></code></pre></div>
<pre><code>## 
## 	Pearson&#39;s Chi-squared test
## 
## data:  TaulaC
## X-squared = 6.5209, df = 2, p-value = 0.03837</code></pre>
<p><em>Conclusió</em>: Hem trobat evidència significativa que els tres tractaments no tenen la mateixa taxa d’èxit (test <span class="math inline">\(\chi^2\)</span> d’homogeneïtat, p-valor 0.04).</p>
<p>Ara seria necessari efectuar 3 contrastos de parelles de proporcions per trobar quines parelles de tractaments tenen taxes d’èxit diferents. Us ho deixam com a exercici.</p>
<p>De la mateixa manera que les dues variables involucrades en un contrast d’independència podien tenir més de dos nivells, podem efectuar contrastos d’homogeneïtat en situacions més generals que la comparació de proporcions.</p>
<p>Suposem doncs que tenim una variable aleatòria qualitativa <span class="math inline">\(X\)</span> de nivells <span class="math inline">\(X_1,\ldots,X_k\)</span>, i una variable aleatòria qualitativa <span class="math inline">\(Y\)</span> de nivells <span class="math inline">\(Y_1,\ldots,Y_l\)</span>, i volem contrastar si la probabilitat que <span class="math inline">\(Y\)</span> prengui els seus diferents valors sobre un individu depèn o no del valor de <span class="math inline">\(X\)</span> sobre aquest individu. És a dir, volem contrastar si <span class="math inline">\(P(Y=Y_h|X=X_i)=P(Y=Y_h|X=X_j)\)</span> per a tots <span class="math inline">\(i,j,h\)</span>.</p>

<div class="example">
<p><span id="exm:colesterolhom2" class="example"><strong>Exemple 8.5  </strong></span>Tornem a la situació de l’Exemple <a href="contrastos-dindependència-i-homogeneïtat.html#exm:colesterolhom">8.4</a>. Volem comparar 3 tractaments, A, B i C, per baixar el nivell de colesterol, per veure si tenen taxes d’èxit diferents. Però ara, en lloc de considerar l’èxit com una variable binària (baixes dels 240 mg/dl o no) distingirem si al cap de 5 setmanes de tractament s’ha baixat dels 200 mg/dl (el nivell <em>desitjable</em> de colesterol), s’ha assolit un nivell entre 200 i 240 mg/dl (el nivell <em>límit</em>), o si no s’ha baixat de 240 (nivell <em>alt</em>).</p>
</div>
<p>Les dades de l’estudi esmentat a l’Exemple <a href="contrastos-dindependència-i-homogeneïtat.html#exm:colesterolhom">8.4</a> amb aquesta nova classificació dels resultats són:</p>
<p><span class="math display">\[
\begin{array}{l}
\hphantom{200-240AAaa}\text{Tractament}\\
\begin{array}{r|ccc|c}
\text{Nivell} &amp; A &amp; B &amp; C &amp; \text{Total} \\\hline
\text{Desitjable} &amp; 12 &amp; 21 &amp; 13 &amp; 46\\
\text{Límit} &amp; 31 &amp; 40 &amp; 40 &amp; 111\\
\text{Alt} &amp; 57 &amp; 39 &amp; 47 &amp; 143
\\\hline
\text{Total} &amp; 100 &amp; 100 &amp; 100 &amp; 300\\\hline
\end{array}
\end{array}
\]</span></p>
<p><em>Variables aleatòries</em>: Com abans, tenim dues interpretacions correctes:</p>
<ul>
<li><p><span class="math inline">\(X\)</span>: “Prenem un pacient i anotam quin tractament segueix”</p></li>
<li><p><span class="math inline">\(Y\)</span>: “Prenem un pacient i anotam al cap de 5 setmanes en quina classe està el seu nivell de colesterol”</p></li>
</ul>
<p>o</p>
<ul>
<li><p><span class="math inline">\(Y_A\)</span>: “Prenem un pacient tractat amb A i anotam al cap de 5 setmanes en quina classe està el seu nivell de colesterol”</p></li>
<li><p><span class="math inline">\(Y_B\)</span>: “Prenem un pacient tractat amb B i anotam al cap de 5 setmanes en quina classe està el seu nivell de colesterol”</p></li>
<li><p><span class="math inline">\(Y_C\)</span>: “Prenem un pacient tractat amb C i anotam al cap de 5 setmanes en quina classe està el seu nivell de colesterol”</p></li>
</ul>
<p>:
<span class="math display">\[
\left\{\begin{array}{l}
H_0:  P(Y=L|X=T)=P(Y=L|X=T&#39;)\\
\hphantom{H_0:  }\quad\text{ per a cada nivell $L$ de colesterol}\\
\hphantom{H_0:  }\quad \text{ i cada parell de tractaments $T,T&#39;$}\\
H_1: \mbox{Almenys una d&#39;aquestes igualtats és falsa}
\end{array}\right.
\]</span></p>
<p>És un test d’homogeneïtat, farem servir un test <span class="math inline">\(\chi^2\)</span>:</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb435-1" aria-hidden="true" tabindex="-1"></a>TaulaC2<span class="ot">=</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">12</span>,<span class="dv">21</span>,<span class="dv">13</span>,<span class="dv">31</span>,<span class="dv">40</span>,<span class="dv">40</span>,<span class="dv">57</span>,<span class="dv">39</span>,<span class="dv">47</span>), <span class="at">nrow=</span><span class="dv">3</span>, <span class="at">byrow=</span><span class="cn">TRUE</span>)</span>
<span id="cb435-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb435-2" aria-hidden="true" tabindex="-1"></a>TaulaC2</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]   12   21   13
## [2,]   31   40   40
## [3,]   57   39   47</code></pre>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb437-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(TaulaC2)</span></code></pre></div>
<pre><code>## 
## 	Pearson&#39;s Chi-squared test
## 
## data:  TaulaC2
## X-squared = 8.046, df = 4, p-value = 0.08991</code></pre>
<p><em>Conclusió</em>: No hem trobat evidència estadísticament significativa que sigui fals que A, B i C tenen el mateix efecte quan distingim tres classes de nivell de colesterol (test <span class="math inline">\(\chi^2\)</span> d’homogeneïtat, p-valor 0.09). La conclusió concreta ja dependria de si prenguéssim nivell de significació 0.05 o 0.1.</p>
</div>
<div id="test-chi2-de-tendència-opcional" class="section level2" number="8.3">
<h2><span class="header-section-number">8.3</span> Test <span class="math inline">\(\chi^2\)</span> de tendència (Opcional)</h2>
<p>Un <strong>contrast de tendència</strong> és una generalització del contrast d’homogeneïtat de proporcions. En el contrast de tendència, tenim
una variable aleatòria <em>ordinal</em> <span class="math inline">\(X\)</span> de nivells ordenats <span class="math inline">\(X_1&lt;\cdots&lt; X_k\)</span>, i una variable aleatòria Bernoulli <span class="math inline">\(Y\)</span> de nivells “Èxit” i “Fracàs”. Diguem <span class="math inline">\(p_i=P(Y=\text{Èxit}|X=X_i)\)</span>, per a tot <span class="math inline">\(i\)</span>. El contrast que volem realitzar és
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: \text{ $p_1=\cdots=p_k$}\\
H_1: \text{ $p_1\leqslant\cdots \leqslant p_k$ i almenys una }\\
\hphantom{H_1: } \text{ d&#39;aquestes desigualtats és estricta}
\end{array} 
\right.
\]</span></p>
<p>S’efectua amb un <strong>test <span class="math inline">\(\chi^2\)</span> de Cochran-Armitage</strong>, una variant del test <span class="math inline">\(\chi^2\)</span> explicat a les seccions anteriors.
Per utilitzar-lo, basta que la mostra total sigui gran (<span class="math inline">\(\geqslant 30\)</span>), no cal la condició de Cochran. (Si teniu curiositat sobre com es fa, podeu consultar <a href="https://en.wikipedia.org/wiki/Cochran–Armitage_test_for_trend">la seva entrada de la Wikipedia</a>)</p>
<p>Amb R s’efectua amb la funció <code>prop.trend.test</code>, aplicada al vector de freqüències d’èxits i el vector de freqüències de cada nivell de <span class="math inline">\(X\)</span>.</p>

<div class="example">
<p><span id="exm:tosfumar3" class="example"><strong>Exemple 8.6  </strong></span>Continuem amb l’Exemple <a href="contrastos-dindependència-i-homogeneïtat.html#exm:tosfumar">8.1</a>. Recordem que hi volíem determinar si hi ha associació entre l’hàbit de fumar i patir tos nocturna entre els nins. Les dades recollides varen ser:</p>
</div>
<p><span class="math display">\[
\begin{array}{l}
\hphantom{No fumador ocasional un }\text{Fumador}\\
\begin{array}{l|ccc|c}
&amp; \text{No fumador} &amp; \text{Ocasional} &amp; \text{Regular} &amp; \text{Total} \\\hline
\text{Tos} &amp; 266 &amp; 395 &amp; 80 &amp; 741\\
\text{No tos}&amp; 1037 &amp; 977 &amp; 92 &amp; 2106\\\hline
\text{Total} &amp;1303 &amp; 1372 &amp; 172 &amp; 2847\\
\end{array}
\end{array}
\]</span></p>
<p>Com que l’estatus de fumador és una variable ordinal i, naturalment, creiem que quant més se fuma, més probabilitat hi ha de patir de tos nocturna, ens pot interessar contrastar si la probabilitat de tos nocturna creix amb la freqüència de fumar.</p>
<p><em>Variables d’interès</em>:</p>
<ul>
<li><p><span class="math inline">\(X\)</span>: “Prenem un nin i anotam el seu estatus de fumador”; la considerarem una variable ordinal amb nivells “No fumador” &lt; “Ocasional” &lt; “Regular”</p></li>
<li><p><span class="math inline">\(Y\)</span>: “Prenem un nin i anotam si té tos nocturna o no”</p></li>
</ul>
<p><em>Contrast</em>: Si diem <span class="math inline">\(p_N\)</span>, <span class="math inline">\(p_O\)</span> i <span class="math inline">\(p_R\)</span> a la probabilitat que tengui tos nocturna un nin no fumador, un nin fumador ocasional i un nin fumador regular, respectivament,
<span class="math display">\[
\left\{
\begin{array}{ll}
H_0: \text{ $p_N=p_O=p_R$}\\
H_1: \text{ $p_N\leqslant p_O  \leqslant p_R$ i $p_N&lt;p_R$}
\end{array} 
\right.
\]</span></p>

<div class="rmdnote">
<p>Fixau-vos que, a la hipòtesi alternativa, dir</p>
<blockquote>
<p>“<span class="math inline">\(p_N\leqslant p_O \leqslant p_R\)</span> i almenys una d’aquestes desigualtats és estricta”</p>
</blockquote>
<p>és equivalent a dir</p>
<blockquote>
<p>“<span class="math inline">\(p_N\leqslant p_O \leqslant p_R\)</span> i <span class="math inline">\(p_N&lt;p_R\)</span>”</p>
</blockquote>
<p>només que aquesta darrera reformulació és més curta.</p>
</div>
<p>Emprarem un test <span class="math inline">\(\chi^2\)</span> de tendència:</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="contrastos-dindependència-i-homogeneïtat.html#cb439-1" aria-hidden="true" tabindex="-1"></a>Tos<span class="ot">=</span><span class="fu">c</span>(<span class="dv">266</span>,<span class="dv">395</span>,<span class="dv">80</span>)</span>
<span id="cb439-2"><a href="contrastos-dindependència-i-homogeneïtat.html#cb439-2" aria-hidden="true" tabindex="-1"></a>Fum<span class="ot">=</span><span class="fu">c</span>(<span class="dv">1303</span>,<span class="dv">1372</span>,<span class="dv">172</span>)</span>
<span id="cb439-3"><a href="contrastos-dindependència-i-homogeneïtat.html#cb439-3" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.trend.test</span>(Tos,Fum)</span></code></pre></div>
<pre><code>## 
## 	Chi-squared Test for Trend in Proportions
## 
## data:  Tos out of Fum ,
##  using scores: 1 2 3
## X-squared = 59.47, df = 1, p-value = 1.242e-14</code></pre>
<p><em>Conclusió</em>: Hem trobat evidència estadísticament significativa que la probabilitat de patir tos nocturna creix amb la freqüència de fumar (test <span class="math inline">\(\chi^2\)</span> de Cochran-Armitage, p-valor 10<sup>-14</sup>)</p>
</div>
<div id="test-de-la-lliçó-8" class="section level2" number="8.4">
<h2><span class="header-section-number">8.4</span> Test de la lliçó 8</h2>
<p><strong>(1)</strong> En un contrast d’independència, quina és la hipòtesi alternativa?</p>
<ol style="list-style-type: decimal">
<li>Que les dues variables són independents</li>
<li>Que hi ha associació entre les dues variables</li>
<li>Que les dues variables tenen distribucions diferents</li>
<li>Que les dues variables podrien ser dependents</li>
<li>Que les dues variables depenen d’una tercera</li>
</ol>
<p><strong>(2)</strong> Perquè el test khi quadrat per contrastar la independència de dues variables sigui vàlid, és <strong>necessari</strong> que (marcau totes les continuacions correctes):</p>
<ol style="list-style-type: decimal">
<li>Totes les freqüències esperades siguin més grans o iguals que 5</li>
<li>Totes les freqüències observades siguin més grans o iguals que 5</li>
<li>Les dues variables siguin independents</li>
<li>La mida total de la mostra sigui com a mínim 30</li>
<li>La mida total de la mostra sigui com a mínim 100.</li>
<li>Les dues variables siguin normals o les dues mostres siguin de mida <span class="math inline">\(\geqslant 40\)</span>.</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(3)</strong> Si fem un test khi quadrat per contrastar la independència d’una variable amb 5 possibles valors i una variable amb 3 possibles valors, a partir de la taula de contingència <span class="math inline">\(3\times 5\)</span>, quants graus de llibertat tendrà l’estadístic de contrast que hi hem d’emprar?</p>
<ol style="list-style-type: decimal">
<li>15</li>
<li>14</li>
<li>13</li>
<li>12</li>
<li>Cap dels nombres anteriors</li>
</ol>
<p><strong>(4)</strong> Quina o quines de les afirmacions següents sobre un test khi quadrat d’independència són vertaderes?</p>
<ol style="list-style-type: decimal">
<li>S’hi comparen les freqüències observades dels valors de cada variable amb les seves freqüències esperades si les variables fossin independents</li>
<li>S’hi comparen les freqüències observades de cada parella de valors de les variables, un de cada variable, amb les seves freqüències esperades si les variables fossin independents</li>
<li>S’hi comparen les freqüències observades dels valors de cada variable amb les seves freqüències esperades si les variables fossin dependents</li>
<li>S’hi comparen les freqüències observades de cada parella de valors, un de cada variable, de cada variable amb les seves freqüències esperades si les variables fossin dependents</li>
<li>És un cas particular de test khi quadrat de bondat d’ajust</li>
<li>És un cas particular de test khi quadrat de comparació de dues proporcions</li>
</ol>
<p><strong>(5)</strong> Volem contrastar la independència de dues variables de Bernoulli a partir de la taula següent:
<span class="math display">\[
\begin{array}{l}
\hphantom{\textbf{Variable 2}}\qquad \textbf{Variable 1}\\
\begin{array}{l|cc|c}
\textbf{Variable 2} &amp; \text{Èxit} &amp; \text{Fracàs} &amp; \text{Total}\\\hline
\text{Èxit} &amp; 100 &amp; 300 &amp; 400\\
\text{Fracàs} &amp; 400 &amp; 4200 &amp; 4600\\ \hline
\text{Total} &amp; 500 &amp; 4500 &amp; 5000
\end{array}
\end{array}
\]</span></p>
<p>Quina de les afirmacions següents és correcta?</p>
<ol style="list-style-type: decimal">
<li>Si les dues variables fossin independents, esperaríem que les quatre entrades de la taula central fossin iguals</li>
<li>Si hi hagués associació entre les dues variables, esperaríem que les quatre entrades de la taula central fossin iguals</li>
<li>Si les dues variables fossin independents, esperaríem que no hi hagués casos discordants</li>
<li>Si hi hagués associació entre les dues variables, esperaríem que no hi hagués casos discordants</li>
<li>Si les dues variables fossin independents, esperaríem que l’entrada corresponent a (Èxit,Èxit) fos 40</li>
<li>Si hi hagués associació entre les dues variables, esperaríem que l’entrada corresponent a (Èxit,Èxits) fos 40</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(6)</strong> A partir de la taula de la pregunta anterior (marcau totes les continuacions correctes)</p>
<ol style="list-style-type: decimal">
<li>Que existeixi o no associació entre la variable 1 i la variable 2 es pot contrastar amb un test khi quadrat</li>
<li>Que existeixi o no associació entre la variable 1 i la variable 2 es pot contrastar amb un test de McNemar</li>
<li>Que existeixi o no associació entre la variable 1 i la variable 2 es pot contrastar amb un test de Fisher</li>
<li>Que la probabilitat d’èxit de les dues variables sigui la mateixa o no es pot contrastar amb un test khi quadrat</li>
<li>Que la probabilitat d’èxit de les dues variables sigui la mateixa o no es pot contrastar amb un test de McNemar</li>
<li>Que la probabilitat d’èxit de les dues variables sigui la mateixa o no es pot contrastar amb un test de Fisher</li>
<li>Totes les altres continuacions són incorrectes</li>
</ol>
<p><strong>(7)</strong> Quina de les afirmacions següents és vertadera?</p>
<ol style="list-style-type: decimal">
<li>La diferència entre un contrast d’independència i un d’homogeneïtat està en la hipòtesi nul.la: que les variables siguin independents al contrast d’independència i que siguin homogènies al contrast d’homogeneïtat</li>
<li>La diferència entre un contrast d’independència i un d’homogeneïtat està en la hipòtesi alternativa: que hi hagi associació entre les variables al contrast d’independència i que hi hagi heterogeneïtat entre les variables al contrast d’homogeneïtat</li>
<li>La diferència entre un contrast d’independència i un d’homogeneïtat està en com prenem les mostres: transversal al contrast d’independència i estratificada al contrast d’homogeneïtat</li>
<li>La diferència entre un contrast d’independència i un d’homogeneïtat està en com prenem les mostres: transversal al contrast d’homogeneïtat i estratificada al contrast d’independència</li>
<li>La diferència entre un contrast d’independència i un d’homogeneïtat està en el nombre de graus de llibertat de l’estadístic: si les variables tenen <span class="math inline">\(s\)</span> nivells i <span class="math inline">\(t\)</span> nivells, respectivament, al d’independència hi empram <span class="math inline">\((s-1)(t-1)\)</span> graus de llibertat i al d’homogeneïtat n’hi empram <span class="math inline">\(st-1\)</span></li>
<li>Cap de les altres respostes és correcta</li>
</ol>
<p><strong>(8)</strong> Per contrastar si el percentatge de sanitaris infectats amb COVID-19 és el mateix a les diferents illes balears, prenem una mostra formada per 100 sanitaris de Mallorca, 50 sanitaris de Menorca i 50 sanitaris de les Pitiüses, i els fem un test d’anticossos per veure si han estat infectats o no. Marcau l’afirmació correcta:</p>
<ol style="list-style-type: decimal">
<li>Aquest contrast és d’independència, perquè la mostra és transversal</li>
<li>Aquest contrast no és d’homogeneïtat, perquè les mostres de les tres illes no tenen la mateixa mida</li>
<li>Aquest contrast no és d’homogeneïtat, perquè les mostres de les tres illes no s’adapten a les proporcions que representen les diferents illes en el total de les Balears</li>
<li>Aquest contrast no és d’independència, perquè les mostres de les tres illes no tenen la mateixa mida</li>
<li>Aquest contrast és d’homogeneïtat perquè hem pres una mostra específica de cada illa</li>
<li>Aquest contrast és d’homogeneïtat perquè la mostra és transversal</li>
<li>Aquest contrast no és ni d’independència ni homogeneïtat</li>
<li>Cap de les altres respostes és correcta</li>
</ol>
<p><strong>(9)</strong> Per contrastar si el percentatge de sanitaris infectats amb COVID-19 és el mateix a les diferents illes balears, prenem una mostra formada per 50 sanitaris de Mallorca, 50 sanitaris de Menorca i 50 sanitaris de les Pitiüses, i els fem un test d’anticossos per veure si han estat infectats o no. Marcau l’afirmació correcta:</p>
<ol style="list-style-type: decimal">
<li>Aquest contrast és d’independència, perquè la mostra és transversal</li>
<li>Aquest contrast és d’independència, perquè les mostres de les tres illes tenen la mateixa mida</li>
<li>Aquest contrast no és d’homogeneïtat, perquè les mostres de les tres illes no s’adapten a les proporcions que representen les diferents illes en el total de les Balears</li>
<li>Aquest contrast és d’homogeneïtat perquè hem pres una mostra específica de cada illa</li>
<li>Aquest contrast és d’homogeneïtat perquè la mostra és transversal</li>
<li>Aquest contrast és d’homogeneïtat, perquè les mostres de les tres illes tenen la mateixa mida</li>
<li>Aquest contrast no és ni d’independència ni homogeneïtat</li>
<li>Cap de les altres respostes és correcta</li>
</ol>
<p><strong>(10)</strong> Per contrastar si el percentatge de sanitaris infectats amb COVID-19 és el mateix a les diferents illes balears, prenem una mostra formada per 150 sanitaris extreta del llistat de tots el personal sanitari dels hospitals de les Balears, a continuació miram a quina illa treballen i els fem un test d’anticossos per veure si han estat infectats o no. Per casualitat, ens hi surten 50 de Mallorca, 50 de Menorca i 50 d’Eivissa/Formentera. Marcau l’afirmació correcta:</p>
<ol style="list-style-type: decimal">
<li>Aquest contrast és d’independència, perquè la mostra és transversal</li>
<li>Aquest contrast és d’independència, perquè les mostres de les tres illes tenen la mateixa mida</li>
<li>Aquest contrast no és d’homogeneïtat, perquè les mostres de les tres illes no s’adapten a les proporcions que representen les diferents illes en el total de les Balears</li>
<li>Aquest contrast és d’homogeneïtat perquè la mostra és transversal</li>
<li>Aquest contrast és d’homogeneïtat, perquè les mostres de les tres illes tenen la mateixa mida</li>
<li>Aquest contrast no és ni d’independència ni homogeneïtat</li>
<li>Cap de les altres respostes és correcta</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-bondat.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-ED.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
