<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tema 3 Estimació puntual | Matemàtiques II</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Tema 3 Estimació puntual | Matemàtiques II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 3 Estimació puntual | Matemàtiques II" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2021-02-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-conceptes.html"/>
<link rel="next" href="intervals-de-confiança.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="part"><span><b>Part 0: Preliminars</b></span></li>
<li class="chapter" data-level="1" data-path="chap-varal.html"><a href="chap-varal.html"><i class="fa fa-check"></i><b>1</b> Variables aleatòries</a><ul>
<li class="chapter" data-level="1.1" data-path="chap-varal.html"><a href="chap-varal.html#generalitats-sobre-variables-aleatòries"><i class="fa fa-check"></i><b>1.1</b> Generalitats sobre variables aleatòries</a></li>
<li class="chapter" data-level="1.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-discretes"><i class="fa fa-check"></i><b>1.2</b> Variables aleatòries discretes</a><ul>
<li class="chapter" data-level="1.2.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució"><i class="fa fa-check"></i><b>1.2.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="1.2.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança"><i class="fa fa-check"></i><b>1.2.2</b> Esperança</a></li>
<li class="chapter" data-level="1.2.3" data-path="chap-varal.html"><a href="chap-varal.html#variància-i-desviació-típica"><i class="fa fa-check"></i><b>1.2.3</b> Variància i desviació típica</a></li>
<li class="chapter" data-level="1.2.4" data-path="chap-varal.html"><a href="chap-varal.html#quantils"><i class="fa fa-check"></i><b>1.2.4</b> Quantils</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="chap-varal.html"><a href="chap-varal.html#famílies-importants-de-variables-aleatòries-discretes"><i class="fa fa-check"></i><b>1.3</b> Famílies importants de variables aleatòries discretes</a><ul>
<li class="chapter" data-level="1.3.1" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-binomials"><i class="fa fa-check"></i><b>1.3.1</b> Variables aleatòries binomials</a></li>
<li class="chapter" data-level="1.3.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-hipergeomètriques"><i class="fa fa-check"></i><b>1.3.2</b> Variables aleatòries hipergeomètriques</a></li>
<li class="chapter" data-level="1.3.3" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-de-poisson"><i class="fa fa-check"></i><b>1.3.3</b> Variables aleatòries de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-contínues"><i class="fa fa-check"></i><b>1.4</b> Variables aleatòries contínues</a><ul>
<li class="chapter" data-level="1.4.1" data-path="chap-varal.html"><a href="chap-varal.html#densitat-i-distribució-1"><i class="fa fa-check"></i><b>1.4.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="1.4.2" data-path="chap-varal.html"><a href="chap-varal.html#esperança-variància-quantils"><i class="fa fa-check"></i><b>1.4.2</b> Esperança, variància, quantils…</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="chap-varal.html"><a href="chap-varal.html#sec:normal"><i class="fa fa-check"></i><b>1.5</b> Variables aleatòries normals</a><ul>
<li class="chapter" data-level="1.5.1" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i><b>1.5.1</b> Amb R</a></li>
<li class="chapter" data-level="1.5.2" data-path="chap-varal.html"><a href="chap-varal.html#propietats-bàsiques"><i class="fa fa-check"></i><b>1.5.2</b> Propietats bàsiques</a></li>
<li class="chapter" data-level="1.5.3" data-path="chap-varal.html"><a href="chap-varal.html#intervals-de-referència"><i class="fa fa-check"></i><b>1.5.3</b> Intervals de referència</a></li>
<li class="chapter" data-level="1.5.4" data-path="chap-varal.html"><a href="chap-varal.html#variables-log-normals"><i class="fa fa-check"></i><b>1.5.4</b> Variables log-normals</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="chap-varal.html"><a href="chap-varal.html#test-de-la-lliçó-1"><i class="fa fa-check"></i><b>1.6</b> Test de la lliçó 1</a><ul>
<li class="chapter" data-level="1.6.1" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-discretes-1"><i class="fa fa-check"></i><b>1.6.1</b> Variables aleatòries discretes</a></li>
<li class="chapter" data-level="1.6.2" data-path="chap-varal.html"><a href="chap-varal.html#variables-aleatòries-contínues-1"><i class="fa fa-check"></i><b>1.6.2</b> Variables aleatòries contínues</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Part I: Estadística inferencial</b></span></li>
<li class="chapter" data-level="2" data-path="chap-conceptes.html"><a href="chap-conceptes.html"><i class="fa fa-check"></i><b>2</b> Alguns conceptes bàsics</a><ul>
<li class="chapter" data-level="2.1" data-path="chap-conceptes.html"><a href="chap-conceptes.html#unitat-dobservació"><i class="fa fa-check"></i><b>2.1</b> Unitat d’observació</a></li>
<li class="chapter" data-level="2.2" data-path="chap-conceptes.html"><a href="chap-conceptes.html#població"><i class="fa fa-check"></i><b>2.2</b> Població</a></li>
<li class="chapter" data-level="2.3" data-path="chap-conceptes.html"><a href="chap-conceptes.html#variable-aleatòria"><i class="fa fa-check"></i><b>2.3</b> Variable aleatòria</a></li>
<li class="chapter" data-level="2.4" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostra"><i class="fa fa-check"></i><b>2.4</b> Mostra</a></li>
<li class="chapter" data-level="2.5" data-path="chap-conceptes.html"><a href="chap-conceptes.html#sec:mostreig"><i class="fa fa-check"></i><b>2.5</b> Mostreig aleatori</a></li>
<li class="chapter" data-level="2.6" data-path="chap-conceptes.html"><a href="chap-conceptes.html#mostres-de-conveniència"><i class="fa fa-check"></i><b>2.6</b> Mostres de conveniència</a></li>
<li class="chapter" data-level="2.7" data-path="chap-conceptes.html"><a href="chap-conceptes.html#test-de-la-lliçó-2"><i class="fa fa-check"></i><b>2.7</b> Test de la lliçó 2</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="estimació-puntual.html"><a href="estimació-puntual.html"><i class="fa fa-check"></i><b>3</b> Estimació puntual</a><ul>
<li class="chapter" data-level="3.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#definicions-bàsiques"><i class="fa fa-check"></i><b>3.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="3.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#mitjana-mostral"><i class="fa fa-check"></i><b>3.2</b> Mitjana mostral</a></li>
<li class="chapter" data-level="3.3" data-path="estimació-puntual.html"><a href="estimació-puntual.html#proporció-mostral"><i class="fa fa-check"></i><b>3.3</b> Proporció mostral</a></li>
<li class="chapter" data-level="3.4" data-path="estimació-puntual.html"><a href="estimació-puntual.html#variància-mostral"><i class="fa fa-check"></i><b>3.4</b> Variància mostral</a></li>
<li class="chapter" data-level="3.5" data-path="estimació-puntual.html"><a href="estimació-puntual.html#la-distribució-t-de-student"><i class="fa fa-check"></i><b>3.5</b> La distribució t de Student</a></li>
<li class="chapter" data-level="3.6" data-path="estimació-puntual.html"><a href="estimació-puntual.html#bons-estimadors"><i class="fa fa-check"></i><b>3.6</b> “Bons” estimadors</a><ul>
<li class="chapter" data-level="3.6.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-no-esbiaixats"><i class="fa fa-check"></i><b>3.6.1</b> Estimadors no esbiaixats</a></li>
<li class="chapter" data-level="3.6.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-eficients"><i class="fa fa-check"></i><b>3.6.2</b> Estimadors eficients</a></li>
<li class="chapter" data-level="3.6.3" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimadors-màxim-versemblants"><i class="fa fa-check"></i><b>3.6.3</b> Estimadors màxim versemblants</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="estimació-puntual.html"><a href="estimació-puntual.html#sec:pobl"><i class="fa fa-check"></i><b>3.7</b> Estimació de poblacions</a><ul>
<li class="chapter" data-level="3.7.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#estimació-de-poblacions-numerades"><i class="fa fa-check"></i><b>3.7.1</b> Estimació de poblacions numerades</a></li>
<li class="chapter" data-level="3.7.2" data-path="estimació-puntual.html"><a href="estimació-puntual.html#marca-recaptura"><i class="fa fa-check"></i><b>3.7.2</b> Marca-recaptura</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="estimació-puntual.html"><a href="estimació-puntual.html#test-de-la-lliçó-3"><i class="fa fa-check"></i><b>3.8</b> Test de la lliçó 3</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html"><i class="fa fa-check"></i><b>4</b> Intervals de confiança</a><ul>
<li class="chapter" data-level="4.1" data-path="estimació-puntual.html"><a href="estimació-puntual.html#definicions-bàsiques"><i class="fa fa-check"></i><b>4.1</b> Definicions bàsiques</a></li>
<li class="chapter" data-level="4.2" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#exemple-interval-de-confiança-del-95-per-a-la-mitjana-duna-variable-aleatòria-normal"><i class="fa fa-check"></i><b>4.2</b> Exemple: Interval de confiança del 95% per a la mitjana d’una variable aleatòria normal</a></li>
<li class="chapter" data-level="4.3" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#interval-de-confiança-per-a-la-mitjana-basat-en-la-t-de-student"><i class="fa fa-check"></i><b>4.3</b> Interval de confiança per a la mitjana basat en la t de Student</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#la-fórmula"><i class="fa fa-check"></i>La fórmula</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#algunes-consideracions"><i class="fa fa-check"></i>Algunes consideracions</a></li>
<li class="chapter" data-level="" data-path="chap-varal.html"><a href="chap-varal.html#amb-r"><i class="fa fa-check"></i>Amb R</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#càlcul-de-la-mida-de-la-mostra-per-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#intervals-de-confiança-per-a-proporcions"><i class="fa fa-check"></i><b>4.4</b> Intervals de confiança per a proporcions</a><ul>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-exacte-de-clopper-pearson"><i class="fa fa-check"></i>Mètode “exacte” de Clopper-Pearson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-de-wilson"><i class="fa fa-check"></i>Mètode de Wilson</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#mètode-de-laplace"><i class="fa fa-check"></i>Mètode de Laplace</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#més-exemples"><i class="fa fa-check"></i>Més exemples</a></li>
<li class="chapter" data-level="" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#càlcul-de-la-mida-de-la-mostra-per-a-fixar-lerror"><i class="fa fa-check"></i>Càlcul de la mida de la mostra per a fixar l’error</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#intervals-de-confiança-per-a-la-variància-duna-variable-normal"><i class="fa fa-check"></i><b>4.5</b> Intervals de confiança per a la variància d’una variable normal</a></li>
<li class="chapter" data-level="4.6" data-path="intervals-de-confiança.html"><a href="intervals-de-confiança.html#poblacions-finites"><i class="fa fa-check"></i><b>4.6</b> “Poblacions finites”</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimació-puntual" class="section level1">
<h1><span class="header-section-number">Tema 3</span> Estimació puntual</h1>
<p>L’objectiu principal de la <strong>inferència estadística</strong> és obtenir informació sobre tota una població a partir de només una mostra, com quan volem saber si un brou és fat o salat tastant-ne només una cullerada. El primer tipus d’informació que ens sol interessar és què val qualque paràmetre d’alguna variable aleatòria poblacional (una proporció, una mitjana…), per exemple per poder escriure un titular com el següent:</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-133"></span>
<img src="Bioestadistica-II_files/figure-html/miopia.png" alt="https://www.efesalud.com/miopia-estudio-universitarios" width="70%" />
<p class="caption">
Figura 3.1: <a href="https://www.efesalud.com/miopia-estudio-universitarios" class="uri">https://www.efesalud.com/miopia-estudio-universitarios</a>
</p>
</div>
<p>Aquest 60% no s’ha obtingut fent passar a tots els universitaris espanyols un test de miopia, ni tan sols demanant-los a tots si són miops o no, sinó que simplement s’ha pres una mostra d’universitaris, s’hi ha observat un 60% de miops i s’ha extrapolat aquesta proporció a tot el col·lectiu d’universitaris espanyols.</p>
<p>El procés d’intentar endevinar el valor d’un paràmetre d’una població a partir d’una mostra se’n diu <strong>estimació puntual</strong>, i és el que tractarem en aquest tema. Al tema següent ens centrarem en intentar endevinar el valor d’un paràmetre amb un cert marge d’error i de seguretat.</p>

<div class="rmdimportant">
En aquest curs, sempre suposarem que empram <strong>mostres aleatòries</strong> i gairebé sempre que aquestes mostres aleatòries són a més <strong>simples</strong>. Per tant, si no diem el contrari, d’ara endavant quan parlem de mostres sempre suposarem que són mostres aleatòries simples, encara que no ho diguem explícitament per no carregar massa el text.
</div>

<div id="definicions-bàsiques" class="section level2">
<h2><span class="header-section-number">3.1</span> Definicions bàsiques</h2>
<p>Per estimar el valor d’un paràmetre d’una variable aleatòria poblacional, en prenem una mostra (aleatòria simple) i calculam qualque cosa amb els valors que la formen. Què calculam? Doncs un <strong>estimador</strong>: alguna funció adequada aplicada als valors de la mostra, i que dependrà del que volguem estimar.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-135"></span>
<img src="Bioestadistica-II_files/figure-html/poblaciomostra.png" alt="Població *versus* mostra" width="60%" />
<p class="caption">
Figura 3.2: Població <em>versus</em> mostra
</p>
</div>
<p>Per exemple:</p>
<ul>
<li><p>Si volem estimar l’alçada mitjana dels estudiants de la UIB, prendrem una mostra d’estudiants de la UIB, els amidarem i calcularem la <strong>mitjana aritmètica</strong> de les seves alçades.</p></li>
<li><p>Si volem estimar la proporció d’estudiants de la UIB que han passat la COVID-19, prendrem una mostra d’estudiants de la UIB, els farem un test d’anticossos i calcularem la <strong>proporció mostral</strong> de positius en la mostra.</p></li>
</ul>
<p>Formalment:</p>
<ul>
<li><p>Tenim una <strong>variable aleatòria poblacional</strong> <span class="math inline">\(X\)</span>, definida sobre una <strong>població</strong>.</p></li>
<li><p>Una <strong>mostra aleatòria simple</strong> de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span> és un vector <span class="math inline">\((X_1,\ldots,X_n)\)</span> format per <span class="math inline">\(n\)</span> còpies <em>independents</em> de <span class="math inline">\(X\)</span>.</p>
<p>Cada variable <span class="math inline">\(X_i\)</span> és una còpia de “Prenem un subjecte de la població i hi mesuram <span class="math inline">\(X\)</span>”.</p></li>
<li><p>Una <strong>realització</strong> de la mostra aleatòria simple <span class="math inline">\(X_1,\ldots,X_n\)</span> és un vector <span class="math inline">\((x_1,\ldots,x_n)\in \mathbb{R}^n\)</span> de valors presos per aquestes variables aleatòries.</p>
<p>És a dir, amb <span class="math inline">\((X_1,\ldots,X_n)\)</span> repetim <span class="math inline">\(n\)</span> vegades (independents les unes de les altres) el procés de prendre un subjecte de la població i mesurar-hi <span class="math inline">\(X\)</span>. Cada vegada que ho fem, obtenim un conjunt de números, al que formalment diem una <strong>realització</strong> de la mostra.</p>
<p>A la lliçó anterior a aquestes realitzacions les déiem directament “mostres aleatòries simples de valors de <span class="math inline">\(X\)</span>”; no passeu ànsia, en sortir d’aquest “formalment” els hi tornarem a dir.</p></li>
<li><p>Un <strong>estimador</strong> és una variable aleatòria <span class="math inline">\(f(X_1,\ldots,X_n)\)</span> obtinguda aplicant una funció <span class="math inline">\(f\)</span> a una mostra aleatòria simple <span class="math inline">\((X_1,\ldots,X_n)\)</span>.</p>
<p>Aquest estimador s’aplica a les realitzacions de la mostra i dóna nombres reals.</p></li>
</ul>

<div class="rmdimportant">
Un estimador és una <strong>variable aleatòria</strong>, definida sobre la població formada per les mostres aleatòries simples de la població de partida. Per tant, té funció de densitat, funció de distribució (que genèricament anomenarem <strong>distribució mostral</strong>, per indicar que refereix a la probabilitat que li passi qualque cosa al valor del estimador sobre una mostra), esperança, desviació típica, etc.
</div>


<div class="rmdnote">
<p>Com ja us hem dit, i com que no hi ha necessitat de filar tan prim, d’ara endavant cometrem l’abús de llenguatge de dir <strong>mostra aleatòria simple</strong> tant al vector de variables aleatòries <span class="math inline">\((X_1,\ldots,X_n)\)</span> com a una realització <span class="math inline">\((x_1,\ldots,x_n)\)</span>; i hi ometrem els parèntesis.</p>
</div>

<p>Com ja hem comentat a la Secció <a href="chap-conceptes.html#sec:mostreig">2.5</a>, si la mida <span class="math inline">\(N\)</span> de la població és MOLT més gran que la mida <span class="math inline">\(n\)</span> de la mostra (per fixar idees, si <span class="math inline">\(N\geq 1000n\)</span>), els resultats per a mostres aleatòries simples valen (aproximadament) per a mostres aleatòries sense reposició, perquè les variables aleatòries que formen la mostra sense reposició són gairebé idèntiques i independents i les repeticions són improbables.</p>

<div class="rmdcaution">
<p>Els estimadors tenen sempre sentit per a mostres en general, però gairebé tots els teoremes que estableixen les seves propietats són vertaders només sota determinades restriccions (mostra aleatòria simple, condicions extra sobre <span class="math inline">\(X\)</span>, …), per la qual cosa les seves conseqüències tan sols són segures sota aquestes restriccions.</p>
</div>

</div>
<div id="mitjana-mostral" class="section level2">
<h2><span class="header-section-number">3.2</span> Mitjana mostral</h2>
<p>Quan volem estimar el valor mitjà d’una variable sobre una població, en prenem una mostra de valors i calculam la seva mitjana aritmètica, no és ver? Doncs això és la mitjana mostral.</p>
<p>Donada una variable aleatòria <span class="math inline">\(X\)</span>, diem <strong>mitjana mostral de</strong> (mostres de) <strong>mida <span class="math inline">\(n\)</span></strong> a la variable aleatòria <span class="math inline">\(\overline{X}\)</span> “Prenem una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span> i calculam la mitjana aritmètica dels seus valors”. És a dir, formalment, la <strong>mitjana mostral</strong> de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span> és la variable aleatòria obtinguda prenent <span class="math inline">\(n\)</span> còpies independents <span class="math inline">\(X_1,\ldots,X_n\)</span> de la variable aleatòria <span class="math inline">\(X\)</span> i calculant
<span class="math display">\[
\overline{X}=\frac{X_1+\cdots+X_n}{n}
\]</span></p>

<div class="rmdcaution">
Fixau-vos que definim la mitjana mostral només per a mostres aleatòries simples. Naturalment, té sentit definir-la per a mostres qualssevol, però llavors la seva distribució mostral deixaria de complir les propietats que donem en aquesta secció. El mateix advertiment val per als estimadors que definim en les pròximes seccions.
</div>

<p>Com a conseqüència del comportament d’esperances i variàncies de combinacions lineals, tenim el següent resultat:</p>

<div class="theorem">
<p><span id="thm:mitjmostgral" class="theorem"><strong>Teorema 3.1  </strong></span>Siguin <span class="math inline">\(X\)</span> una variable aleatòria d’esperança <span class="math inline">\(\mu_X\)</span> i desviació típica <span class="math inline">\(\sigma_X\)</span>,
<span class="math inline">\(X_1,\ldots,X_n\)</span> una mostra aleatòria de <span class="math inline">\(X\)</span> i <span class="math inline">\(\overline{X}\)</span> la seva mitjana mostral. Aleshores</p>
<ol style="list-style-type: lower-alpha">
<li><p>El valor esperat de <span class="math inline">\(\overline{X}\)</span> és <span class="math inline">\(\mu_{\overline{X}}=\mu_X\)</span>.</p></li>
<li><p>Si la mostra aleatòria és simple, la desviació típica de <span class="math inline">\(\overline{X}\)</span> és <span class="math inline">\(\sigma_{\overline{X}}={\sigma_X}/{\sqrt{n}}\)</span>.</p></li>
</ol>
</div>


<div class="rmdcorbes">
<p>En efecte, com que
<span class="math display">\[
\overline{X}=\frac{1}{n}X_1+\cdots +\frac{1}{n}X_n
\]</span>
i les variables <span class="math inline">\(X_1,\ldots,X_n\)</span> són còpies de <span class="math inline">\(X\)</span>, i per tant tenen totes esperança <span class="math inline">\(\mu_X\)</span> i variància <span class="math inline">\(\sigma^2_X\)</span>, tenim que
<span class="math display">\[
\mu_{\overline{X}}=\overbrace{\frac{1}{n}\mu_X+\cdots +\frac{1}{n}\mu_X}^n=\mu_X
\]</span>
i, si <span class="math inline">\(X_1,\ldots,X_n\)</span> són independents,
<span class="math display">\[
\sigma_{\overline{X}}=\sqrt{\overbrace{\frac{1}{n^2}\sigma^2_X+\cdots+ \frac{1}{n^2}\sigma^2_X}^n}=\sqrt{\frac{n}{n^2}\sigma^2_X}=\frac{\sigma_X}{\sqrt{n}}
\]</span></p>
</div>

<p>Per tant:</p>
<ul>
<li><p><span class="math inline">\(\overline{X}\)</span> és un estimador puntual de <span class="math inline">\(\mu_X\)</span>.</p></li>
<li><p><span class="math inline">\(\mu_{\overline{X}}=\mu_X\)</span> (), la qual cosa significa que:</p>
<ul>
<li><p>La mitjana de les mitjanes mostrals de totes les mostres de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span> torna a ser la mitjana de <span class="math inline">\(X\)</span>.</p></li>
<li><p><em>Esperam que la mitjana mostral doni, de mitjana, <span class="math inline">\(\mu_X\)</span></em>: si repetíssim moltes vegades el procés de prendre una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> i calcular-ne la mitjana mostral, molt probablement el valor mitjà d’aquestes mitjanes s’acostaria molt a <span class="math inline">\(\mu_X\)</span>.</p></li>
</ul></li>
<li><p><span class="math inline">\(\sigma_{\overline{X}}= \sigma_X/\sqrt{n}\)</span> indica que la dispersió dels resultats de <span class="math inline">\(\overline{X}\)</span> creix amb la variabilitat de <span class="math inline">\(X\)</span> i decreix amb la mida <span class="math inline">\(n\)</span> de la mostra, tendint a 0 quan <span class="math inline">\(n\to\infty\)</span>.</p></li>
</ul>

<div class="rmdimportant">
A la desviació típica de <span class="math inline">\(\overline{X}\)</span> li diem
l’<strong>error estàndard</strong>, o <strong>típic</strong>, de <span class="math inline">\(\overline{X}\)</span>.
</div>


<div class="example">
<p><span id="exm:experimentTCL1" class="example"><strong>Exemple 3.1  </strong></span>El fitxer <strong>tests.txt</strong> que trobareu a l’url <a href="https://raw.githubusercontent.com/AprendeR-UIB/MatesII/master/Dades/tests.txt" class="uri">https://raw.githubusercontent.com/AprendeR-UIB/MatesII/master/Dades/tests.txt</a> conté les notes (sobre 100) de tests dels estudiants de Matemàtiques I de fa uns cursos. El guardam en un vector anomenat <code>tests</code>:</p>
</div>

<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="estimació-puntual.html#cb71-1"></a>tests=<span class="kw">scan</span>(<span class="st">&quot;https://raw.githubusercontent.com/AprendeR-UIB/MatesII/master/Dades/tests.txt&quot;</span>)</span>
<span id="cb71-2"><a href="estimació-puntual.html#cb71-2"></a><span class="kw">head</span>(tests)</span></code></pre></div>
<pre><code>## [1] 70 44 90 64 76 68</code></pre>
<p>la mida de la població és</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="estimació-puntual.html#cb73-1"></a>N=<span class="kw">length</span>(tests)</span>
<span id="cb73-2"><a href="estimació-puntual.html#cb73-2"></a>N</span></code></pre></div>
<pre><code>## [1] 185</code></pre>
<p>La seva mitjana, que és la mitjana poblacional, és</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="estimació-puntual.html#cb75-1"></a>mu=<span class="kw">mean</span>(tests)</span>
<span id="cb75-2"><a href="estimació-puntual.html#cb75-2"></a>mu</span></code></pre></div>
<pre><code>## [1] 55.4324</code></pre>
<p>Si en prenem una mostra aleatòria simple, per exemple de mida <span class="math inline">\(n=40\)</span>, la seva mitjana mostral no té per què coincidir amb la mitjana poblacional:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="estimació-puntual.html#cb77-1"></a>n=<span class="dv">40</span></span>
<span id="cb77-2"><a href="estimació-puntual.html#cb77-2"></a>MAS=<span class="kw">sample</span>(tests,n,<span class="dt">replace=</span><span class="ot">TRUE</span>) <span class="co"># Una mostra aelatòria simple</span></span>
<span id="cb77-3"><a href="estimació-puntual.html#cb77-3"></a>x.barra=<span class="kw">mean</span>(MAS) <span class="co"># La mitjana mostral</span></span>
<span id="cb77-4"><a href="estimació-puntual.html#cb77-4"></a>x.barra</span></code></pre></div>
<pre><code>## [1] 53.5</code></pre>
<p>Però si prenem <em>moltes</em> mostres aleatòries simples, la mitjana de les seves mitjanes és molt probable que sí que s’acosti a la mitjana poblacional. Vegem si tenim sort:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="estimació-puntual.html#cb79-1"></a>mitjanes=<span class="kw">replicate</span>(<span class="dv">10</span><span class="op">^</span><span class="dv">5</span>,<span class="kw">mean</span>(<span class="kw">sample</span>(tests,n,<span class="dt">replace=</span><span class="ot">TRUE</span>)))</span>
<span id="cb79-2"><a href="estimació-puntual.html#cb79-2"></a><span class="kw">mean</span>(mitjanes)</span></code></pre></div>
<pre><code>## [1] 55.4187</code></pre>
<p>Vegem ara que la desviació típica d’aquesta mostra de mitjanes s’acosta a l’error típic de la mitjana mostral, no a la desviació típica de la població:</p>
<ul>
<li>La desviació típica poblacional:</li>
</ul>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="estimació-puntual.html#cb81-1"></a>sigma=<span class="kw">sd</span>(tests)</span>
<span id="cb81-2"><a href="estimació-puntual.html#cb81-2"></a>sigma</span></code></pre></div>
<pre><code>## [1] 21.4404</code></pre>
<ul>
<li>La desviació típica de la mostra de mitjanes:</li>
</ul>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="estimació-puntual.html#cb83-1"></a><span class="kw">sd</span>(mitjanes)</span></code></pre></div>
<pre><code>## [1] 3.38468</code></pre>
<ul>
<li>L’error típic de la mitjana mostral:</li>
</ul>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="estimació-puntual.html#cb85-1"></a>sigma<span class="op">/</span><span class="kw">sqrt</span>(n)</span></code></pre></div>
<pre><code>## [1] 3.39003</code></pre>
<p>Recordau del Teorema <a href="chap-varal.html#thm:comblinnormals2">1.6</a> que una combinació lineal de variables aleatòries normals independents torna a ser normal. Com que la mitjana mostral d’una mostra aleatòria simple és una combinació lineal de variables aleatòries independents, obtenim el resultat següent:</p>

<div class="theorem">
<p><span id="thm:TCLnorm" class="theorem"><strong>Teorema 3.2  </strong></span>Siguin <span class="math inline">\(X\)</span> una variable aleatòria normal <span class="math inline">\(N(\mu_X,\sigma_X)\)</span> i <span class="math inline">\(X_1,\ldots, X_n\)</span> una mostra aleatòria simple de <span class="math inline">\(X\)</span>. Aleshores, la seva mitjana mostral <span class="math inline">\(\overline{X}\)</span> és normal, i en concret
<span class="math display">\[
\overline{X}\sim N\Big(\mu_X,\frac{\sigma_X}{\sqrt{n}}\Big).
\]</span></p>
</div>

<p>El teorema següent diu que la conclusió del teorema anterior és aproximadament vertadera si la mida <span class="math inline">\(n\)</span> de les mostres aleatòries simples és gran:</p>

<div class="theorem">
<p><span id="thm:TCL" class="theorem"><strong>Teorema 3.3  (Teorema Central del Límit)  </strong></span>Siguin <span class="math inline">\(X\)</span> una variable aleatòria <em>qualsevol</em> d’esperança <span class="math inline">\(\mu_X\)</span> i desviació típica <span class="math inline">\(\sigma_X\)</span> i <span class="math inline">\(X_1,\ldots, X_n\)</span> una mostra aleatòria simple de <span class="math inline">\(X\)</span>. Quan <span class="math inline">\(n\to \infty\)</span>, la distribució de probabilitats de la seva mitjana mostral <span class="math inline">\(\overline{X}\)</span> tendeix a la d’una variable normal
<span class="math display">\[
N\Big(\mu_X,\frac{\sigma_X}{\sqrt{n}}\Big).
\]</span></p>
</div>


<div class="rmdcaution">
Com us podeu imaginar, quan un resultat l’anomenen <strong>Teorema Central</strong> de qualque cosa és perquè és molt important.
</div>

<p>Normalment aplicarem el Teorema Central del Límit de la manera següent:</p>

<div class="rmdimportant">
<p>Siguin <span class="math inline">\(X\)</span> una variable aleatòria <em>qualsevol</em> d’esperança <span class="math inline">\(\mu_X\)</span> i desviació típica <span class="math inline">\(\sigma_X\)</span> i <span class="math inline">\(X_1,\ldots, X_n\)</span> una mostra aleatòria simple de <span class="math inline">\(X\)</span>. Si la mida <span class="math inline">\(n\)</span> de la mostra és gran, la seva mitjana mostral <span class="math inline">\(\overline{X}\)</span> és aproximadament normal
<span class="math inline">\(N(\mu_X,\sigma_X/\sqrt{n})\)</span>.</p>
<p>En aquest curs, entendrem que <span class="math inline">\(n\)</span> és prou gran com per poder aplicar aquest “resultat” si és més gran o igual que 30, potser menys com més se sembli <span class="math inline">\(X\)</span> a una normal i potser més si la <span class="math inline">\(X\)</span> és molt diferent d’una normal.</p>
</div>


<div class="rmdcaution">
A partir d’ara, sovint cometrem l’abús de llenguatge d’ometre l’adverbi “aproximadament” de l’expressió anterior, i direm simplement que si <span class="math inline">\(n\)</span> és gran, <span class="math inline">\(\overline{X}\)</span> és normal. Però heu de tenir present que aquest “és normal” en realitat vol dir “la seva distribució és aproximadament la d’una variable normal”.
</div>


<div class="example">
<span id="exm:unnamed-chunk-154" class="example"><strong>Exemple 3.2  </strong></span>Suposem que tenim una variable aleatòria <span class="math inline">\(X\)</span> de mitjana poblacional <span class="math inline">\(\mu_X=3\)</span> i desviació típica poblacional <span class="math inline">\(\sigma_X=0.2\)</span> i que en prenem mostres aleatòries simples de mida 100. Pel Teorema Central del Límit, la distribució de la mitjana mostral <span class="math inline">\(\overline{X}\)</span> és
<span class="math display">\[
N\Big(3,\frac{0.2}{\sqrt{100}}\Big)=N(3,0.02)
\]</span>
</div>


<div class="example">
<p><span id="exm:experimentTCL2" class="example"><strong>Exemple 3.3  </strong></span>Tornem a la situació de l’Exemple <a href="estimació-puntual.html#exm:experimentTCL1">3.1</a>. Teníem les notes guardades en un vector anomenat <strong>tests</strong>. Amb l’histograma següent podem veure que aquestes notes no tenen pinta de seguir una distribució normal.</p>
</div>

<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="estimació-puntual.html#cb87-1"></a>fact.trans=<span class="kw">hist</span>(tests,<span class="dt">plot=</span><span class="ot">FALSE</span>)<span class="op">$</span>counts[<span class="dv">1</span>]<span class="op">/</span><span class="kw">hist</span>(tests,<span class="dt">plot=</span><span class="ot">FALSE</span>)<span class="op">$</span>density[<span class="dv">1</span>]</span>
<span id="cb87-2"><a href="estimació-puntual.html#cb87-2"></a><span class="kw">hist</span>(tests,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Notes dels tests&quot;</span>,</span>
<span id="cb87-3"><a href="estimació-puntual.html#cb87-3"></a>     <span class="dt">ylab=</span><span class="st">&quot;Freqüències&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Histograma de notes de tests&quot;</span>)</span>
<span id="cb87-4"><a href="estimació-puntual.html#cb87-4"></a><span class="kw">curve</span>(fact.trans<span class="op">*</span><span class="kw">dnorm</span>(x,<span class="kw">mean</span>(tests),<span class="kw">sd</span>(tests)),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-155-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>A l’Exemple <a href="estimació-puntual.html#exm:experimentTCL1">3.1</a> també hem construit un vector anomenat <strong>mitjanes</strong> format per 10<sup>5</sup> mitjanes mostrals de mostres aleatòries simples de notes de mida 40. Pel Teorema Central del Límit, aquestes mitjanes mostrals haurien de seguir aproximadament una distribució normal, malgrat que la “població original” (les notes dels tests) no sigui normal. Vegem-ho amb un histograma, on hem afegit la densitat de la normal <span class="math inline">\(N(\mu_X,\sigma_X/\sqrt{n})\)</span> predita pel Teorema Central del Límit.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="estimació-puntual.html#cb88-1"></a>fact.trans.m=<span class="kw">hist</span>(mitjanes,<span class="dt">plot=</span><span class="ot">FALSE</span>)<span class="op">$</span>counts[<span class="dv">1</span>]<span class="op">/</span><span class="kw">hist</span>(mitjanes,<span class="dt">plot=</span><span class="ot">FALSE</span>)<span class="op">$</span>density[<span class="dv">1</span>]</span>
<span id="cb88-2"><a href="estimació-puntual.html#cb88-2"></a><span class="kw">hist</span>(mitjanes,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Mitjanes&quot;</span>,</span>
<span id="cb88-3"><a href="estimació-puntual.html#cb88-3"></a>     <span class="dt">ylab=</span><span class="st">&quot;Freqüències&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Histograma de la mostra de mitjanes&quot;</span>)</span>
<span id="cb88-4"><a href="estimació-puntual.html#cb88-4"></a><span class="kw">curve</span>(fact.trans.m<span class="op">*</span><span class="kw">dnorm</span>(x,mu,sigma<span class="op">/</span><span class="kw">sqrt</span>(n)),<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-156-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>L’exemple següent és un tipus de pregunta que més endavant ens preocuparà molt.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-157" class="example"><strong>Exemple 3.4  </strong></span>L’alçada d’una espècie de matolls té valor mitjà 115 cm, amb una desviació típica de 25 cm. Si prenem una mostra aleatòria simple de 100 matolls d’aquesta espècie, quina és la probabilitat que la mitjana mostral de les alçades sigui més petita que 110 cm?</p>
</div>

<p>Diguem <span class="math inline">\(X\)</span> a la variable aleatòria definida per les alçades d’aquests matolls. Pel Teorema Central del Límit, la mitjana mostral <span class="math inline">\(\overline{X}\)</span> de mostres aleatòries simples de 100 alçades segueix una distribució <span class="math inline">\(N(115,25/\sqrt{100})=N(115,2.5)\)</span>. Llavors, la probabilitat que ens demanen és
<span class="math display">\[
P(\overline{X}&lt; 110)
\]</span>
que podem calcular amb</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="estimació-puntual.html#cb89-1"></a><span class="kw">round</span>(<span class="kw">pnorm</span>(<span class="dv">110</span>,<span class="dv">115</span>,<span class="fl">2.5</span>),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.0228</code></pre>
<p>Un 2.28% de les mostra aleatòries simples de 100 matolls d’aquesta espècie tenen la mitjana de les alçades més petita que 110 cm.</p>
<!--
Sigui ara $X_1,\ldots, X_n$ una mostra aleatòria **sense reposició** de mida $n$ d'una variable aleatòria $X$ d'esperança $\mu_X$ i desviació típica $\sigma_X$.  Si $n$ és molt petit en relació a la mida $N$ de la població, ja hem explicat que podem suposar que aquesta mostra aleatòria és simple i per tant tot funciona com fins ara; en particular, en aquest cas entendrem que els tres teoremes anteriors són vertaders.


Si $n$ és gran en relació a $N$, aleshores el resultat per l'esperança segueix essent vertader (al Teorema \@ref(thm:mitjmostgral).a no suposàvem que la mostra fos simple), i per tant encara tenim que
$$
\mu_{\overline{X}}=\mu_X.
$$
Però en aquest cas cal modificar la fórmula del Teorema \@ref(thm:mitjmostgral).b per a la desviació típica, que ara és:
$$
\sigma_{\overline{X}}=\frac{\sigma_X}{\sqrt{n}}\cdot\sqrt{\frac{N-n}{N-1}}
$$
A més, en aquest cas les conclusions dels Teoremes \@ref(thm:TCLnorm) i \@ref(thm:TCL) no són certes, ni tan sols amb aquesta correcció de l'error típic.  

Al terme
$$
\sqrt{\frac{N-n}{N-1}}
$$
que apareix a la fórmula anterior li diuen el **factor de població finita**.

\BeginKnitrBlock{rmdcorbes}<div class="rmdcorbes">Si us en recordau, aquest factor de població finita és el factor que passava de la desviació típica d'una distribució binomial a la d'una hipergeomètrica. En efecte:

* Si $X_B\sim B(n,p)$, $\sigma^2_{X_B}=np(1-p)$ i per tant $\sigma_{X_B}=\sqrt{np(1-p)}$

* Si $X_H\sim H(A,B,n)$,  amb $A+B=N$ i $p=A/N$,

$$
\begin{array}{rl}
\sigma^2_{X_H} & \displaystyle =\dfrac{nAB}{(A+B)^2}\cdot\dfrac{A+B-n}{A+B-1}\\ & \displaystyle =n\cdot\frac{A}{N}\cdot\frac{N-A}{N}\cdot\dfrac{N-n}{N-1}\\ & \displaystyle =
np(1-p)\cdot \dfrac{N-n}{N-1}
\end{array}
$$
i per tant
$$
\sigma_{X_H}=\sqrt{np(1-p)}\cdot \sqrt{\dfrac{N-n}{N-1}}=\sigma_{X_B}\cdot \sqrt{\dfrac{N-n}{N-1}}.
$$
  </div>\EndKnitrBlock{rmdcorbes}

\BeginKnitrBlock{example}<div class="example"><span class="example" id="exm:unnamed-chunk-160"><strong>(\#exm:unnamed-chunk-160) </strong></span>Tornem a la situació dels Exemples \@ref(exm:experimentTCL1) i \@ref(exm:experimentTCL2). 
Què passa  si prenem les mostres aleatòries de notes de tests sense reposició?
  </div>\EndKnitrBlock{example}

Prenguem ara 10^5^ mostres aleatòries sense reposició de 40 notes de tests.

```r
mitjanes.norep=replicate(10^5,mean(sample(tests,40)))
```

Un altre cop, la mitjana d'aquest vector de mitjanes hauria de ser propera a la mitjana de la població original, que era 55.43:


```r
round(mean(mitjanes.norep),2)
```

```
## [1] 55.42
```

Calculem ara la desviació típica d'aquest vector de mitjanes:


```r
round(sd(mitjanes.norep),2)
```

```
## [1] 3
```

Aquesta desviació típica no s'apropa a la desviació típica de la població partida per l'arrel quadrada de la mida de les mostres, que hem calculat abans i era 3.39. 

Pel que acabam d'explicar, la desviació típica d'aquest vector de mitjanes de mostres sense reposició hauria de ser molt propera a la desviació típica de la població partida per l'arrel quadrada de la mida de les mostres *i tot multiplicat pel factor de  població finita* $\sqrt{(N-n)/(N-1)}$, on $N$ és la mida de la població, és a dir, la longitud del vector `tests`, i $n$ la mida de les mostres. Vegem si és veritat:


```r
round((sd(tests)/sqrt(n))*sqrt((N-n)/(N-1)),2)
```

```
## [1] 3.01
```

Això ja s'acosta més a la desviació típica del vector de mitjanes de mostres sense reposició, que ha valgut 3.

-->
</div>
<div id="proporció-mostral" class="section level2">
<h2><span class="header-section-number">3.3</span> Proporció mostral</h2>
<p>Suposem que ara tenim una variable aleatòria poblacional <span class="math inline">\(X\)</span> que és Bernoulli amb <strong>probabilitat d’èxit</strong> <span class="math inline">\(p_X\)</span>. <span class="math inline">\(X\)</span> pren els valors 1 (èxit) o 0 (fracàs). Recordau que <span class="math inline">\(E(X)=p_X\)</span> i <span class="math inline">\(\sigma_X=\sqrt{p_X(1-p_X)}\)</span>.</p>
<p>Sigui <span class="math inline">\(X_1,\ldots,X_n\)</span> una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span> i sigui <span class="math inline">\(S_n=\sum_{i=1}^n X_i\)</span> el nombre d’èxits observats en aquesta mostra.</p>
<p>La <strong>proporció mostral</strong> d’èxits de la nostra mostra és
<span class="math display">\[
\widehat{p}_X=\frac{S_n}{n}=\frac{\sum_{i=1}^n X_i}{n}.
\]</span></p>

<div class="rmdcaution">
Recordau que si prenem mostres aleatòries simples, <span class="math inline">\(S_n\)</span> és una variable aleatòria binomial <span class="math inline">\(B(n,p_X)\)</span>. Però és un doi dir que la proporció mostral <span class="math inline">\(\widehat{p}_X\)</span> és una variable aleatòria binomial, ni que només sigui perquè les variables aleatòries binomials prenen valors nombres naturals i els valors que pot prendre <span class="math inline">\(\widehat{p}_X\)</span> són fraccions entre 0 i 1.
</div>

<p>Fixau-vos que <span class="math inline">\(\widehat{p}_X\)</span> és un cas particular de la mitjana mostral <span class="math inline">\(\overline{X}\)</span>, per tant per a les proporcion mostrals val tot el que hem dit fins ara per a mitjanes mostrals:</p>

<div class="theorem">
<p><span id="thm:pX" class="theorem"><strong>Teorema 3.4  </strong></span>Si <span class="math inline">\(X\)</span> és una variable aleatòria Bernoulli amb probabilitat d’èxit <span class="math inline">\(p_X\)</span> i <span class="math inline">\(X_1,\ldots,X_n\)</span> és una mostra aleatòria de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span>, de proporció mostral <span class="math inline">\(\widehat{p}_X\)</span>, aleshores</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(\mu_{\widehat{p}_X}=p_X\)</span></p></li>
<li><p><span class="math inline">\(\sigma_{\widehat{p}_X}=\sqrt{\dfrac{p_X(1-p_X)}{n}}\)</span></p></li>
<li><p>Pel Teorema Central del Límit, si la mida <span class="math inline">\(n\)</span> de la mostra és gran, la distribució de <span class="math inline">\(\widehat{p}_X\)</span> és aproximadament la d’una variable normal
<span class="math display">\[
N\left({p}_X,\sqrt{\frac{{p}_X(1-{p}_X)}{n}}\right)
\]</span>
i per tant
<span class="math display">\[
\frac{\widehat{p}_X-p_X}{\sqrt{\frac{{p}_X(1-{p}_X)}{n}}}
\]</span>
és aproximadament <span class="math inline">\(N(0,1)\)</span>.</p></li>
</ol>
</div>

<p>Alguns comentaris:</p>
<ul>
<li><p><span class="math inline">\(\mu_{\widehat{p}_X}=p_X\)</span>: Si repetíssim moltes vegades el procés de prendre una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> d’una variable aleatòria de Bernoulli <span class="math inline">\(X\)</span> i calcular-ne la proporció mostral d’èxits, molt probablement la mitjana d’aquestes proporcions mostrals s’acostaria molt a <span class="math inline">\(p_X\)</span></p></li>
<li><p>En particular, <span class="math inline">\(\widehat{p}_X\)</span> serveix per estimar <span class="math inline">\(p_X\)</span></p></li>
<li><p><span class="math inline">\(\sigma_{\widehat{p}_X}= \sqrt{{p_X(1-p_X)}/{n}}\)</span>: la variabilitat dels resultats de <span class="math inline">\(\widehat{p}_X\)</span> decreix amb <span class="math inline">\(n\)</span> i tendeix a 0 quan <span class="math inline">\(n\to \infty\)</span>. Pel que fa a la dependència de <span class="math inline">\(\sigma_{\widehat{p}_X}\)</span> respecte de <span class="math inline">\(p_X\)</span> si la <span class="math inline">\(n\)</span> és fixada, observau al gràfic següent que <span class="math inline">\(\sqrt{p_X(1-p_X)}\)</span> creix entre 0 i 0.5 i decreix entre 0.5 i 1, assolint el valor màxim a <span class="math inline">\(p_X=0.5\)</span>.</p></li>
</ul>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="estimació-puntual.html#cb91-1"></a><span class="kw">curve</span>(<span class="kw">sqrt</span>(x<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>x)),<span class="dt">xlab=</span><span class="st">&quot;p&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;sqrt(p*(1-p))&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-166-1.png" width="50%" style="display: block; margin: auto;" /></p>
<ul>
<li><p><span class="math inline">\(\sqrt{{p_X(1-p_X)}/{n}}\)</span> és l’<strong>error estándard</strong>, o <strong>típic</strong>, de <span class="math inline">\(\widehat{p}_X\)</span>. L’estimam amb l’<strong>error estándard</strong>, o <strong>típic</strong>, <strong>de la mostra</strong> <span class="math inline">\(\sqrt{{\widehat{p}_X(1-\widehat{p}_X)}/{n}}\)</span>.</p></li>
<li><p>A partir d’ara, sovint cometrem l’abús de llenguatge d’ometre l’adverbi “aproximadament” de l’apartat (3) del teorema anterior, i direm simplement que si <span class="math inline">\(n\)</span> és gran, <span class="math inline">\(\widehat{p}_X\)</span> és normal. Però, repetim, hem de recordar que aquest “és normal” en realitat vol dir “la seva distribució és aproximadament la d’una variable normal”.</p></li>
</ul>

<div class="example">
<p><span id="exm:experimentTCLprop" class="example"><strong>Exemple 3.5  </strong></span>Tornem una altra vegada a la situació dels Exemples <a href="estimació-puntual.html#exm:experimentTCL1">3.1</a> i <a href="estimació-puntual.html#exm:experimentTCL2">3.3</a>. Traduïm el fitxer de notes de tests en un vector binari: 0 per suspens (haver tret menys de 50) i 1 per aprovat (haver tret 50 o més):</p>
</div>

<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="estimació-puntual.html#cb92-1"></a><span class="co"># Iniciam totes les notes a 1</span></span>
<span id="cb92-2"><a href="estimació-puntual.html#cb92-2"></a>aprovs=<span class="kw">rep</span>(<span class="dv">1</span>,<span class="kw">length</span>(tests))</span>
<span id="cb92-3"><a href="estimació-puntual.html#cb92-3"></a><span class="co"># Posam 0 on la nota del test és suspesa</span></span>
<span id="cb92-4"><a href="estimació-puntual.html#cb92-4"></a>aprovs[<span class="kw">which</span>(tests<span class="op">&lt;</span><span class="dv">50</span>)]=<span class="dv">0</span></span></code></pre></div>
<p>Aquest vector <code>aprovs</code> el podem entendre com una població de Bernoulli de probabilitat poblacional d’èxit (aprovat) <span class="math inline">\(p_X\)</span>. Les proporcions de suspesos i aprovats són:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="estimació-puntual.html#cb93-1"></a><span class="kw">round</span>(<span class="kw">prop.table</span>(<span class="kw">table</span>(aprovs)),<span class="dv">4</span>) </span></code></pre></div>
<pre><code>## aprovs
##      0      1 
## 0.4054 0.5946</code></pre>
<p>Per tant, <span class="math inline">\(p_X\)</span> és:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="estimació-puntual.html#cb95-1"></a>p_X=<span class="kw">as.numeric</span>(<span class="kw">prop.table</span>(<span class="kw">table</span>(aprovs))[<span class="dv">2</span>])</span>
<span id="cb95-2"><a href="estimació-puntual.html#cb95-2"></a><span class="kw">round</span>(p_X,<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.5946</code></pre>
<p>Ara n’extreurem 10<sup>5</sup> mostres aleatòries simples de mida 40, en calcularem les proporcions mostrals d’aprovats i comprovarem si es confirmen les conclusions del teorema anterior.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="estimació-puntual.html#cb97-1"></a><span class="kw">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb97-2"><a href="estimació-puntual.html#cb97-2"></a>props.mostrals=<span class="kw">replicate</span>(<span class="dv">10</span><span class="op">^</span><span class="dv">5</span>,<span class="kw">mean</span>(<span class="kw">sample</span>(aprovs,<span class="dv">40</span>,<span class="dt">rep=</span><span class="ot">TRUE</span>)))</span></code></pre></div>
<p>La mitjana d’aquest vector de proporcions hauria de ser propera a la proporció poblacional d’aprovats <span class="math inline">\(p_X=0.5946\)</span>.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="estimació-puntual.html#cb98-1"></a><span class="kw">round</span>(<span class="kw">mean</span>(props.mostrals),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.5942</code></pre>
<p>Vegem ara la seva desviació típica:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="estimació-puntual.html#cb100-1"></a><span class="kw">round</span>(<span class="kw">sd</span>(props.mostrals),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.0774</code></pre>
<p>Pel Teorema <a href="estimació-puntual.html#thm:pX">3.4</a>, sabem que això hauria de ser proper a <span class="math inline">\(\sqrt{p_X(1-p_X)/n}\)</span></p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="estimació-puntual.html#cb102-1"></a><span class="kw">round</span>(<span class="kw">sqrt</span>(p_X<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p_X)<span class="op">/</span><span class="dv">40</span>),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.0776</code></pre>
<p>I pel Teorema Central del Límit, aquestes proporcions mostrals haurien de seguir aproximadament una distribució normal $N(p_X,). Vegem-ho amb un histograma:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="estimació-puntual.html#cb104-1"></a>fact.trans.p=<span class="kw">hist</span>(props.mostrals,<span class="dt">plot=</span><span class="ot">FALSE</span>)<span class="op">$</span>counts[<span class="dv">1</span>]<span class="op">/</span><span class="kw">hist</span>(props.mostrals,<span class="dt">plot=</span><span class="ot">FALSE</span>)<span class="op">$</span>density[<span class="dv">1</span>]</span>
<span id="cb104-2"><a href="estimació-puntual.html#cb104-2"></a><span class="kw">hist</span>(props.mostrals,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Proporcions mostrals&quot;</span>,</span>
<span id="cb104-3"><a href="estimació-puntual.html#cb104-3"></a>     <span class="dt">ylab=</span><span class="st">&quot;Freqüències&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Histograma de la mostra de proporcions&quot;</span>)</span>
<span id="cb104-4"><a href="estimació-puntual.html#cb104-4"></a><span class="kw">curve</span>(fact.trans.p<span class="op">*</span><span class="kw">dnorm</span>(x,p_X,<span class="kw">sqrt</span>(p_X<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p_X)<span class="op">/</span><span class="dv">40</span>)),</span>
<span id="cb104-5"><a href="estimació-puntual.html#cb104-5"></a>      <span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-174-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>I això que la mida de les mostres, 40, no és especialment gran.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-175" class="example"><strong>Exemple 3.6  </strong></span>Un 59.1% dels estudiants de la UIB són dones. Hem pres una mostra més o menys aleatòria de 60 estudiants de la UIB i hi hem trobat 40 dones, un 66.67%. Ens demanam si 40 de 60 és una quantitat raonable de dones en una mostra aleatòria simple d’estudiants de la UIB, o si són moltes (atès que hi esperaríem al voltant d’un 59% de dones).</p>
</div>

<p>Aquesta pregunta, que serà molt típica d’aquí a pocs temes, la traduïm en la següent pregunta:</p>
<blockquote>
<p>Si prenem una mostra aleatòria simple de 60 estudiants, quina és la probabilitat que la proporció mostral de dones sigui superior al 66.67%?</p>
</blockquote>
<p>La manera més correcta de resoldre respondre aquesta qüestió és emprar que el nombre <span class="math inline">\(S_{60}\)</span> de dones en mostres aleatòries simples de 60 estudiants de la UIB segueix de manera exacta una distribució binomial <span class="math inline">\(B(60,0.591)\)</span>. Com que el 66.67% de la pregunta en realitat representa 40 dones, la probabilitat demanada és exactament</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="estimació-puntual.html#cb105-1"></a><span class="kw">round</span>(<span class="dv">1</span><span class="op">-</span><span class="kw">pbinom</span>(<span class="dv">39</span>,<span class="dv">60</span>,<span class="fl">0.591</span>),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.1441</code></pre>

<div class="rmdcaution">
Recordau que si <span class="math inline">\(X\)</span> és una variable aleatòria discreta que pren valors enters, com ara la binomial, <span class="math inline">\(P(X\geq 40)=1-P(X\leq 39)\)</span>.
</div>

<p>Això ens diu que, de mitjana, 1 de cada 7 mostres aleatòries simples de 60 estudiants de la UIB conté almenys 40 dones.</p>
<p>Una altra opció seria aprofitar el Teorema Central del Límit, segons el qual la proporció mostral <span class="math inline">\(\widehat{p}_X\)</span> de dones en mostres aleatòries simples de 60 estudiants de la UIB segueix una distribució aproximadament normal amb <span class="math inline">\(\mu=0.591\)</span> i
<span class="math display">\[
\sigma=\sqrt{\dfrac{0.591(1-0.591)}{60}}=0.0635
\]</span>
Per tant, la probabilitat que <span class="math inline">\(\widehat{p}_X\geq 0.6667\)</span> és (recordau, aproximadament)</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="estimació-puntual.html#cb107-1"></a><span class="kw">round</span>(<span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(<span class="fl">0.6667</span>,<span class="fl">0.591</span>,<span class="fl">0.0635</span>),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.1166</code></pre>
<p>Hauria estat més astut emprar a més la correcció de continuïtat. Com que <span class="math inline">\(\widehat{p}_X=S_{60}/60\)</span>, seria millor aproximar
<span class="math display">\[
P(S_{60}\geq 40)=1-P(S_{60}\leq 39)
\]</span>
per, si diem <span class="math inline">\(Y\)</span> a la normal <span class="math inline">\(N(0.591,0.0635)\)</span>,
<span class="math display">\[
1-P(Y\leq 39.5/60)
\]</span></p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="estimació-puntual.html#cb109-1"></a><span class="kw">round</span>(<span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(<span class="fl">39.5</span><span class="op">/</span><span class="dv">60</span>,<span class="fl">0.591</span>,<span class="fl">0.0635</span>),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.1445</code></pre>
<p>En el cas de la proporció mostral, de vegades permetrem prendre <strong>mostres aleatòries sense reposició</strong>. En aquest cas, la distribució del nombre d’èxits en una mostra segueix una distribució hipergeomètrica. D’aquí deduïm que seguim tenint que <span class="math inline">\(E(\widehat{p}_X)=p_X\)</span>, però ara,
si <span class="math inline">\(N\)</span> és la mida de la població,
<span class="math display">\[
\sigma({\widehat{p}_X})=\sqrt{\frac{p_X(1-p_X)}{n}}\cdot
\sqrt{\frac{\vphantom{(p_X}N-n}{N-1}}.
\]</span>
Recordau que al factor
<span class="math display">\[
\sqrt{\frac{N-n}{N-1}}
\]</span>
que transforma <span class="math inline">\(\sigma({\widehat{p}_X})\)</span> per a mostres aleatòries simples en la desviació típica de <span class="math inline">\({\widehat{p}_X}\)</span> per a mostres aleatòries sense reposició li diem el <strong>factor de població finita</strong>, i és el que transformava la desviació típica d’una variable binomial (que compta èxits en mostres aleatòries simples) en la desviació típica d’una variable hipergeomètrica (que compta èxits en mostres aleatòries sense reposició).</p>

<div class="rmdrecordau">
Però recordau que si la mida de la població <span class="math inline">\(N\)</span> és molt gran comparat amb <span class="math inline">\(n\)</span>, podem suposar que una mostra aleatòria sense reposició és simple.
</div>


<div class="example">
<span id="exm:unnamed-chunk-181" class="example"><strong>Exemple 3.7  </strong></span>Tornem a la situació de l’Exemple <a href="estimació-puntual.html#exm:experimentTCLprop">3.5</a>.
Què passa si prenem les mostres aleatòries de notes de tests sense reposició?
</div>

<p>Prenguem ara 10<sup>5</sup> mostres aleatòries sense reposició de 40 notes de tests.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="estimació-puntual.html#cb111-1"></a>props.norep=<span class="kw">replicate</span>(<span class="dv">10</span><span class="op">^</span><span class="dv">5</span>,<span class="kw">mean</span>(<span class="kw">sample</span>(aprovs,<span class="dv">40</span>)))</span></code></pre></div>
<p>Un altre cop, la mitjana d’aquest vector de proporcions mostrals hauria de ser propera a la proporció poblacional d’aprovats <span class="math inline">\(p_X=0.5946\)</span>.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="estimació-puntual.html#cb112-1"></a><span class="kw">round</span>(<span class="kw">mean</span>(props.norep),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.5942</code></pre>
<p>Calculem ara la desviació típica d’aquest vector:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="estimació-puntual.html#cb114-1"></a><span class="kw">round</span>(<span class="kw">sd</span>(props.norep),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.0691</code></pre>
<p>Pel que acabam d’explicar, la desviació típica d’aquest vector de proporcions mostrals de mostres sense reposició hauria de ser molt propera a
<span class="math display">\[
\sqrt{\frac{p_X(1-p_X)}{n}}\cdot\sqrt{\frac{\vphantom{(p_X}N-n}{N-1}}
\]</span>
on <span class="math inline">\(N\)</span> és la mida de la població, és a dir, la longitud del vector <code>aprovs</code>, i <span class="math inline">\(n\)</span> la mida de les mostres. Vegem si és veritat:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="estimació-puntual.html#cb116-1"></a>N=<span class="kw">length</span>(aprovs)</span>
<span id="cb116-2"><a href="estimació-puntual.html#cb116-2"></a>n=<span class="dv">40</span></span>
<span id="cb116-3"><a href="estimació-puntual.html#cb116-3"></a><span class="kw">round</span>(<span class="kw">sqrt</span>(p_X<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p_X)<span class="op">/</span>n)<span class="op">*</span><span class="kw">sqrt</span>((N<span class="op">-</span>n)<span class="op">/</span>(N<span class="dv">-1</span>)),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.0689</code></pre>
</div>
<div id="variància-mostral" class="section level2">
<h2><span class="header-section-number">3.4</span> Variància mostral</h2>
<p>Donada una variable aleatòria <span class="math inline">\(X\)</span>, direm:</p>
<ul>
<li><p><strong>Variància mostral de</strong> (mostres de) <strong>mida <span class="math inline">\(n\)</span></strong>, <span class="math inline">\(\widetilde{S}_{X}^2\)</span>, a la variable aleatòria que consisteix a prendre una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span> i calcular la variància mostral dels seus valors.</p></li>
<li><p><strong>Desviació típica mostral de</strong> (mostres de) <strong>mida <span class="math inline">\(n\)</span></strong>, <span class="math inline">\(\widetilde{S}_{X}\)</span>, a la variable aleatòria que consisteix a prendre una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> de <span class="math inline">\(X\)</span> i calcular la desviació típica mostral dels seus valors.</p></li>
</ul>
<p>Formalment, sigui <span class="math inline">\(X_1,\ldots, X_n\)</span> una mostra aleatòria simple de mida <span class="math inline">\(n\)</span> d’una variable aleatòria <span class="math inline">\(X\)</span> d’esperança <span class="math inline">\(\mu_X\)</span> i desviació típica <span class="math inline">\(\sigma_X\)</span>. Aleshores
<span class="math display">\[
\widetilde{S}_{X}^2=\frac{\sum_{i=1}^n (X_{i}-\overline{X})^2}{n-1},\quad 
\widetilde{S}_{X}=+\sqrt{\widetilde{S}_{X}^2}
\]</span>
A més, de tant en tant també farem servir la <strong>variància</strong> i la <strong>desviació típica</strong> <strong>“a seques”</strong>:
<span class="math display">\[
\begin{array}{l}
\displaystyle S^2_{X}=\frac{\sum_{i=1}^n (X_{i}-\overline{X})^2}{n}=\frac{(n-1)}{n}\widetilde{S}^2_{X}\\
\displaystyle S_X=+\sqrt{S_X^2}
\end{array}
\]</span></p>
<p>La variància (a seques) admet la següent expressió senzilla:
<span class="math display">\[
S^2_X=\frac{\sum_{i=1}^n X_{i}^2}{n}-\overline{X}^2
\]</span></p>

<div class="rmdcorbes">
<p>En efecte:
<span class="math display">\[
\begin{array}{l}
\displaystyle \frac{\sum_{i=1}^n (X_{i}-\overline{X})^2}{n}=\frac{1}{n}\sum_{i=1}^n (X_{i}^2-2\overline{X}X_i+\overline{X}^2)\\
\displaystyle\qquad = \frac{1}{n}\Big(\sum_{i=1}^n X_{i}^2-2\overline{X}\sum_{i=1}^n X_{i}+n\overline{X}^2\Big)\\
\displaystyle\qquad =\frac{\sum_{i=1}^n X_{i}^2}{n}-2\overline{X}\frac{\sum_{i=1}^n X_{i}}{n}+\frac{n\overline{X}^2}{n}\\
\displaystyle\qquad =\frac{\sum_{i=1}^n X_{i}^2}{n}-2\overline{X}\cdot\overline{X} + \overline{X}^2=\frac{\sum_{i=1}^n X_{i}^2}{n}- \overline{X}^2
\end{array}
\]</span></p>
</div>

<p>Tenim els dos resultats següents. El primer ens diu que <strong>esperam</strong> que la variància mostral d’una mostra aleatòria simple de <span class="math inline">\(X\)</span> valgui <span class="math inline">\(\sigma_{X}^2\)</span>, en el sentit usual que si prenem mostres aleatòries simples de <span class="math inline">\(X\)</span> de mida <span class="math inline">\(n\)</span> gran i calculam les seves variàncies mostrals, molt probablement obtenim de mitjana un valor molt proper a <span class="math inline">\(\sigma_{X}^2\)</span>.</p>

<div class="theorem">
<span id="thm:unnamed-chunk-187" class="theorem"><strong>Teorema 3.5  </strong></span>Si <span class="math inline">\(X\)</span> és una variable aleatòria de desviació típica <span class="math inline">\(\sigma_X\)</span>
<span class="math display">\[
E(\widetilde{S}_{X}^2})=\sigma_{X}^2
\]</span>
</div>


<div class="rmdcaution">
I per tant **no esperam* que la variància “a seques” d’una mostra aleatòria simple valgui <span class="math inline">\(\sigma_{X}^2\)</span>. Això ho podeu comprovar fàcilment, perquè <span class="math inline">\(S_X^2\)</span> s’obté a partir de <span class="math inline">\(\widetilde{S}_{X}^2\)</span> canviant el denominador,
<span class="math display">\[
S_X^2=\frac{n-1}{n} \widetilde{S}_{X}^2
\]</span>
i per tant
<span class="math display">\[
E(S_X^2)=\frac{n-1}{n}E(\widetilde{S}_{X}^2)=\frac{n-1}{n}\sigma^2_{X}
\]</span>
</div>

<p>El segon resultat ens diu que <strong>si la variable <span class="math inline">\(X\)</span> és normal</strong>, un múltiple adequat de <span class="math inline">\(\widetilde{S}_{X}^2\)</span> té distribució mostral coneguda, la qual cosa ens permetrà calcular probabilitats d’e successos’esdeveniments relatius a <span class="math inline">\(\widetilde{S}_{X}^2\)</span>..</p>

<div class="theorem">
<p><span id="thm:khi2" class="theorem"><strong>Teorema 3.6  </strong></span>Si <span class="math inline">\(X\)</span> es <span class="math inline">\(N(\mu_X,\sigma_X)\)</span> y prenem mostres de mida <span class="math inline">\(n\)</span>,
la variable aleatòria
<span class="math display">\[
\frac{(n-1)\widetilde{S}_{X}^2}{\sigma_{X}^2}
\]</span>
té distribució coneguda: <span class="math inline">\(\chi_{n-1}^2\)</span> (es llegeix <strong>khi quadrat amb <span class="math inline">\(n-1\)</span> graus de llibertat</strong>).</p>
</div>


<div class="rmdcaution">
La lletra <span class="math inline">\(\chi\)</span> en català es diu <em>khi</em>; en castellà, <em>ji</em>; i en anglès, <em>chi</em>, pronunciat <em>xai</em>.
</div>

<p><img src="Bioestadistica-II_files/figure-html/chihogar.png" width="40%" style="display: block; margin: auto;" /></p>
<p>De la distribució <span class="math inline">\(\chi_\nu^2\)</span>, on <span class="math inline">\(\nu\)</span> són els <strong>graus de llibertat</strong>, heu de saber que:</p>
<ul>
<li><p>Per definició, és la distribució de la suma dels quadrats de <span class="math inline">\(\nu\)</span> variables aleatòries normals estàndard independents. És a dir, si <span class="math inline">\(Z_{1},Z_{2},\ldots, Z_{\nu}\)</span> són variables <span class="math inline">\(N(0,1)\)</span> independents, la variable
<span class="math display">\[
Z_{1}^{2}+Z_{2}^{2}+\cdots +Z_{n}^{2}
\]</span>
té distribució <span class="math inline">\(\chi_\nu^2\)</span>.</p></li>
<li><p>Per tant, és una distribució contínua</p></li>
<li><p>La <span class="math inline">\(\nu\)</span> és el paràmetre del que depèn la seva densitat</p></li>
<li><p>Amb R és <code>chisq</code></p></li>
<li><p>Si <span class="math inline">\(X_\nu\)</span> és una variable aleatòria amb distribució <span class="math inline">\(\chi_\nu^2\)</span>, aleshores <span class="math inline">\(\mu_{X_\nu}=\nu\)</span> i <span class="math inline">\(\sigma_{X_\nu}^2=2 \nu\)</span></p></li>
<li><p>Per a <span class="math inline">\(\nu\)</span> petits, la distribució d’una <span class="math inline">\(\chi_{n}^2\)</span> és asimètrica amb una cua a la dreta, i a mida que <span class="math inline">\(\nu\)</span> creix, (com que és la distribució d’una suma de <span class="math inline">\(\nu\)</span> variables aleatòries) pel Teorema Central del Límit es va aproximant a una distribució normal <span class="math inline">\(N(n,\sqrt{2n})\)</span>, com podeu veure als gràfics següents</p></li>
</ul>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="estimació-puntual.html#cb118-1"></a><span class="kw">curve</span>(<span class="kw">dchisq</span>(x,<span class="dv">1</span>),<span class="dt">col=</span><span class="dv">1</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">20</span>),<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.3</span>),<span class="dt">main=</span><span class="st">&quot;Algunes khi quadrat&quot;</span>)</span>
<span id="cb118-2"><a href="estimació-puntual.html#cb118-2"></a><span class="kw">curve</span>(<span class="kw">dchisq</span>(x,<span class="dv">2</span>),<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb118-3"><a href="estimació-puntual.html#cb118-3"></a><span class="kw">curve</span>(<span class="kw">dchisq</span>(x,<span class="dv">3</span>),<span class="dt">col=</span><span class="dv">3</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb118-4"><a href="estimació-puntual.html#cb118-4"></a><span class="kw">curve</span>(<span class="kw">dchisq</span>(x,<span class="dv">4</span>),<span class="dt">col=</span><span class="dv">4</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb118-5"><a href="estimació-puntual.html#cb118-5"></a><span class="kw">curve</span>(<span class="kw">dchisq</span>(x,<span class="dv">5</span>),<span class="dt">col=</span><span class="dv">5</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb118-6"><a href="estimació-puntual.html#cb118-6"></a><span class="kw">curve</span>(<span class="kw">dchisq</span>(x,<span class="dv">10</span>),<span class="dt">col=</span><span class="dv">6</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb118-7"><a href="estimació-puntual.html#cb118-7"></a><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">col=</span><span class="dv">1</span><span class="op">:</span><span class="dv">6</span>,<span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb118-8"><a href="estimació-puntual.html#cb118-8"></a>       <span class="dt">lwd=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>),<span class="dt">legend=</span><span class="kw">paste</span>(<span class="st">&quot;n=&quot;</span>,<span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>,<span class="dv">10</span>),<span class="dt">sep=</span><span class="st">&quot;&quot;</span>),<span class="dt">cex=</span><span class="fl">0.8</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-191-1.png" width="50%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="estimació-puntual.html#cb119-1"></a><span class="kw">curve</span>(<span class="kw">dchisq</span>(x,<span class="dv">300</span>),<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">150</span>,<span class="dv">450</span>),<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Khi quadrat vs Normal&quot;</span>)</span>
<span id="cb119-2"><a href="estimació-puntual.html#cb119-2"></a><span class="kw">curve</span>(<span class="kw">dnorm</span>(x,<span class="dv">300</span>,<span class="kw">sqrt</span>(<span class="dv">600</span>)),<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb119-3"><a href="estimació-puntual.html#cb119-3"></a><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="dt">col=</span><span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;red&quot;</span>),<span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb119-4"><a href="estimació-puntual.html#cb119-4"></a>       <span class="dt">lwd=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>),<span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;Khi quadrat amb n=300&quot;</span>,<span class="st">&quot;Normal&quot;</span>),<span class="dt">cex=</span><span class="fl">0.7</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-192-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Tornem un instant a això dels <em>graus de llibertat</em>. Per què diem que la variància (mostral o a seques) té <span class="math inline">\(\nu-1\)</span> graus de llibertat?</p>
<p>Doncs perquè si volem construir un conjunt de <span class="math inline">\(n\)</span> nombres <span class="math inline">\(x_1,\ldots,x_\nu\)</span> que tenguin variància un valor donat, posem <span class="math inline">\(y_0\)</span>, aleshores en principi podem escollir <span class="math inline">\(\nu-1\)</span> d’ells, <span class="math inline">\(x_1,\ldots,x_{\nu-1}\)</span>, com volguem i aleshores el darrer, <span class="math inline">\(x_\nu\)</span>, queda bastant fixat. En matemàtiques això se sol expressar dient que “tenim <span class="math inline">\(\nu-1\)</span> graus de llibertat a l’hora d’escollir <span class="math inline">\(x_1,\ldots,x_\nu\)</span> amb variància fixada <span class="math inline">\(y_0\)</span>”.</p>

<div class="rmdcorbes">
<p>En efecte, si fixam el valor <span class="math inline">\(y_0\geq 0\)</span> de la variància i volem trobar <span class="math inline">\(x_1,\ldots,x_{\nu}\)</span>
tals que
<span class="math display">\[
y_0=\frac{\sum_{i=1}^\nu (x_i-\overline{x})^2}{n}=\frac{\sum_{i=1}^\nu x_i^2}{\nu}-\overline{x}^2
\]</span>
vegem que per a qualssevol valors de <span class="math inline">\(x_1,\ldots,x_{\nu-1}\)</span>, el valor de <span class="math inline">\(x_\nu\)</span> queda fixat per una equació quadràtica:
<span class="math display">\[
\begin{array}{l}
\nu y_0 &amp; =\displaystyle \sum_{i=1}^\nu x_i^2-\nu\overline{x}^2= \sum_{i=1}^\nu x_i^2-\nu\Big(\frac{\sum_{i=1}^\nu x_i}{\nu}\Big)^2\\
&amp; =\displaystyle \sum_{i=1}^\nu x_i^2-\frac{(\sum_{i=1}^\nu x_i)^2}{\nu}\\
&amp; \displaystyle =\frac{1}{\nu}\left(\nu\sum_{i=1}^\nu x_i^2-\Big(\sum_{i=1}^{\nu} x_i\Big)^2\right)\\
&amp; =\displaystyle \frac{1}{\nu}\left(\nu\sum_{i=1}^{\nu-1} x_i^2+\nu\mathbf{x_\nu}^2-\Big(\sum_{i=1}^{\nu-1} x_i\Big)^2\right.\\
&amp; \displaystyle\qquad\qquad \left. -2\Big(\sum_{i=1}^{\nu-1} x_i\Big)\mathbf{x_\nu}-\mathbf{x_\nu}^2\right)\\
&amp; =\displaystyle \frac{1}{\nu}\left((\nu-1)\mathbf{x_\nu}^2-2\Big(\sum_{i=1}^{\nu-1} x_i\Big)\mathbf{x_\nu}\right.\\
&amp; \displaystyle\qquad\qquad \left.+\nu\sum_{i=1}^{\nu-1} x_i^2-\Big(\sum_{i=1}^{\nu-1} x_i\Big)^2 \right)
\end{array}
\]</span>
d’on (multiplicant els dos costats de la igualtat per <span class="math inline">\(\nu\)</span> i dividint-los per <span class="math inline">\(\nu-1\)</span>) obtenim, finalment, l’equació de segon grau en <span class="math inline">\(\mathbf{x_\nu}\)</span>
<span class="math display">\[
\mathbf{x_\nu}^2-\frac{2\sum_{i=1}^{\nu-1} x_i}{\nu-1}\mathbf{x_\nu}+\frac{\nu\sum_{i=1}^{\nu-1} x_i^2-\Big(\sum_{i=1}^{\nu-1} x_i\Big)^2-\nu^2y_0^2}{\nu-1}=0
\]</span>
Per tant, fixat <span class="math inline">\(y_0\)</span> i un cop escollits <span class="math inline">\(x_1,\ldots,x_{\nu-1}\)</span>, el darrer valor <span class="math inline">\(x_\nu\)</span> ha de ser per força una solució d’aquesta equació de segon grau.</p>
Fixau-vos que aquesta equació no sempre té solució real, perquè pot tenir el discriminant negatiu. Per tant exageràvem un poc dient que podíem triar <span class="math inline">\(x_1,\ldots,x_{\nu-1}\)</span> “com volguem”. Per exemple, si voleu que la variància sigui 0 i preneu <span class="math inline">\(x_1,\ldots,x_{\nu-1}\)</span> no tots iguals, podeu estar ben segurs que no trobareu cap <span class="math inline">\(x_\nu\)</span> que satisfaci aquesta equació: per tenir variància 0, <span class="math inline">\(x_1,\ldots,x_\nu\)</span> han de ser tots iguals. Però el que ha de quedar clar és que un cop escollits <span class="math inline">\(x_1,\ldots,x_{\nu-1}\)</span>, el valor de <span class="math inline">\(x_\nu\)</span> ja no pot ser qualsevol, pot prendre com a màxim dos valors diferents.
</div>


<div class="rmdcaution">
<p>Anau alerta:</p>
<ul>
<li><p>Si la variable poblacional <span class="math inline">\(X\)</span> no és normal, la conclusió del Teorema <a href="estimació-puntual.html#thm:khi2">3.6</a> no és vertadera.</p></li>
<li><p>Encara que <span class="math inline">\(X\)</span> sigui normal, <span class="math inline">\(E(\widetilde{S}_{X})\neq \sigma_{X}\)</span>.</p></li>
<li><p>Ja ho hem comentat abans. Si <span class="math inline">\(S^2_{X}\)</span> és la variància “a seques” (dividint per <span class="math inline">\(n\)</span> en comptes de per <span class="math inline">\(n-1\)</span>), <span class="math inline">\(E(S^2_{X})\neq \sigma^2_{X}\)</span>.</p></li>
</ul>
</div>


<div class="example">
<span id="exm:pesosnadonsSIDA" class="example"><strong>Exemple 3.8  </strong></span>Suposem que el pes en néixer dels nadons segueix una distribució normal, i s’estima que la seva desviació típica (en g) és 800. Hem anotat els pesos de tots els recent nats amb SIDA d’una ciutat durant 2 anys. El teniu al vector <code>pesos.SIDA</code> següent:
</div>

<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="estimació-puntual.html#cb120-1"></a>pesos.SIDA=<span class="kw">c</span>(<span class="dv">2466</span>, <span class="dv">3941</span>, <span class="dv">2807</span>, <span class="dv">3118</span>, <span class="dv">2098</span>, <span class="dv">3175</span>, <span class="dv">3515</span>, <span class="dv">3317</span>, <span class="dv">3742</span>, <span class="dv">3062</span>, <span class="dv">3033</span>, <span class="dv">2353</span>, <span class="dv">2013</span>, <span class="dv">3515</span>, <span class="dv">3260</span>, <span class="dv">2892</span>, <span class="dv">1616</span>, <span class="dv">4423</span>, <span class="dv">3572</span>, <span class="dv">2750</span>, <span class="dv">2807</span>, <span class="dv">2807</span>, <span class="dv">3005</span>, <span class="dv">3374</span>, <span class="dv">2722</span>, <span class="dv">2495</span>, <span class="dv">3459</span>, <span class="dv">3374</span>, <span class="dv">1984</span>, <span class="dv">2495</span>, <span class="dv">3062</span>, <span class="dv">3005</span>, <span class="dv">2608</span>, <span class="dv">2353</span>, <span class="dv">4394</span>, <span class="dv">3232</span>, <span class="dv">2013</span>, <span class="dv">2551</span>, <span class="dv">2977</span>, <span class="dv">3118</span>, <span class="dv">2637</span>, <span class="dv">1503</span>, <span class="dv">2438</span>, <span class="dv">2722</span>, <span class="dv">2863</span>, <span class="dv">2013</span>, <span class="dv">3232</span>, <span class="dv">2863</span>)</span></code></pre></div>
<p>Quina és la probabilitat que una mostra (aleatòria simple) de pesos de recent nats de la mateixa mida que aquesta tengui una desviació típica mostral més petita que la d’aquesta mostra?</p>
<p>La variable d’interès és <span class="math inline">\(X\)</span>: Prenem un recent nat i pesam el seu pes en g. Ens diuen que és normal amb <span class="math inline">\(\sigma=800\)</span>. Mirem la nostra mostra de pesos:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="estimació-puntual.html#cb121-1"></a>n=<span class="kw">length</span>(pesos.SIDA)</span>
<span id="cb121-2"><a href="estimació-puntual.html#cb121-2"></a>n</span></code></pre></div>
<pre><code>## [1] 48</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="estimació-puntual.html#cb123-1"></a>DTM=<span class="kw">round</span>(<span class="kw">sd</span>(pesos.SIDA),<span class="dv">1</span>)</span>
<span id="cb123-2"><a href="estimació-puntual.html#cb123-2"></a>DTM</span></code></pre></div>
<pre><code>## [1] 623.4</code></pre>
<p>Sigui <span class="math inline">\(\widetilde{S}_X\)</span> la desviació típica mostral de mida 48 de la variable <span class="math inline">\(X\)</span>. Ens demanen <span class="math inline">\(P(\widetilde{S}_X&lt;623.4)\)</span>. Això tal qual no ho sabem calcular, perquè no sabem la distribució de probabilitats de <span class="math inline">\(\widetilde{S}_X\)</span>. Però sí que sabem la distribució de
<span class="math display">\[
\frac{(n-1)\widetilde{S}_{X}^2}{\sigma_{X}^2}=
\frac{47\widetilde{S}_{X}^2}{800^2}
\]</span>
Aquesta variable té distribució <span class="math inline">\(\chi_{47}^2\)</span>. Per tant el que hem de fer és traduir la probabilitat que volem calcular en termes d’aquesta variable:
<span class="math display">\[
P(\widetilde{S}_X&lt;623.4)=P\Big(\frac{47\widetilde{S}_{X}^2}{800^2}&lt;\frac{47\cdot 623.4^2}{800^2}\Big)=P(\chi_{47}^2&lt;28.54)
\]</span>
i això val</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="estimació-puntual.html#cb125-1"></a><span class="kw">round</span>(<span class="kw">pchisq</span>(<span class="kw">round</span>((n<span class="dv">-1</span>)<span class="op">*</span>DTM<span class="op">^</span><span class="dv">2</span><span class="op">/</span><span class="dv">800</span><span class="op">^</span><span class="dv">2</span>,<span class="dv">2</span>),n<span class="dv">-1</span>),<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 0.0153</code></pre>
<p>Per tant, només un 1.5% de les mostres de 47 recent nats tenen una desviació típica mostral més petita que la de la nostra mostra de recent nats amb SIDA.</p>
</div>
<div id="la-distribució-t-de-student" class="section level2">
<h2><span class="header-section-number">3.5</span> La distribució t de Student</h2>
<p>Recordau que si la variable poblacional <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu_X,\sigma_X)\)</span> i prenem mostres aleatòries simples de mida <span class="math inline">\(n\)</span>, la variable
<span class="math display">\[
\frac{\overline{X}-\mu_X}{\sigma_{X}/\sqrt{n}}
\]</span>
és normal estàndard. Des del punt de vista teòric això és útil per obtenir fórmules, però normalment no ens serveix per calcular la probabilitat que a <span class="math inline">\(\overline{X}\)</span> li passi qualque cosa, perquè gairebé mai sabrem la desviació típica poblacional <span class="math inline">\(\sigma_{X}\)</span>. Què passa si l’estimam per mitjà de <span class="math inline">\(\widetilde{S}_{X}\)</span> amb la mateixa mostra amb la qual calculam <span class="math inline">\(\overline{X}\)</span>? Doncs que el resultat següent ens salva el dia, perquè la variable que obtenim té distribució coneguda.</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-198" class="theorem"><strong>Teorema 3.7  </strong></span>Sigui <span class="math inline">\(X\)</span> una variable <span class="math inline">\(N(\mu_X, \sigma_X)\)</span>. Si prenem mostres aleatòries simples de mida <span class="math inline">\(n\)</span>, la variable aleatòria
<span class="math display">\[
T=\frac{\overline{X}-\mu_X}{\widetilde{S}_{X}/\sqrt{n}}
\]</span>
segueix una distribució coneguda, anomenada <strong>t de Student amb <span class="math inline">\(n-1\)</span> graus de llibertat</strong>, <span class="math inline">\(t_{n-1}\)</span>.</p>
</div>


<div class="rmdimportant">
Al denominador <span class="math inline">\(\widetilde{S}_{X}/\sqrt{n}\)</span> li diem l’<strong>error estàndard</strong>, o <strong>típic</strong>, <strong>de la mostra</strong>: estima l’error típic <span class="math inline">\(\sigma_X/\sqrt{n}\)</span> de <span class="math inline">\(\overline{X}\)</span>.
</div>

<p>De la distribució t de Student amb <span class="math inline">\(n\)</span> graus de llibertat, <span class="math inline">\(t_{\nu}\)</span>, heu de saber que:</p>
<ul>
<li><p>És contínua</p></li>
<li><p>Amb R és <code>t</code></p></li>
<li><p>El <strong>nombre de graus de llibertat</strong> <span class="math inline">\(\nu\)</span> és un paràmetre del que depèn la seva distribució</p></li>
<li><p>Si <span class="math inline">\(T_{\nu}\)</span> és una variable amb distribució <span class="math inline">\(t_{\nu}\)</span>, aleshores <span class="math inline">\(\mu_{T_{\nu}}=0\)</span> i <span class="math inline">\(\sigma_{T_{\nu}}^2=\nu/(\nu-2)\)</span> (en realitat això només és veritat si <span class="math inline">\(\nu\geq 3\)</span>, però no fa falta recordar-ho).</p></li>
<li><p>La funció de densitat d’una variable <span class="math inline">\(T_{\nu}\)</span> és simètrica al voltant de 0 (com la d’una <span class="math inline">\(N(0,1)\)</span>):
<span class="math display">\[
P(T_{\nu}\leq -x)=P(T_{\nu}\geq x)=1-P(T_{\nu}\leq x)
\]</span></p></li>
<li><p>Si <span class="math inline">\(\nu\)</span> és gran, la distribució d’una variable <span class="math inline">\(T_{\nu}\)</span> és aproximadament la d’una <span class="math inline">\(N(0,1)\)</span> (però amb més variància: un poc més aplatada), com podeu veure als gràfics següents:</p></li>
</ul>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="estimació-puntual.html#cb127-1"></a><span class="kw">curve</span>(<span class="kw">dnorm</span>(x),<span class="dt">col=</span><span class="dv">1</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>,<span class="dv">4</span>),<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.4</span>),</span>
<span id="cb127-2"><a href="estimació-puntual.html#cb127-2"></a>      <span class="dt">main=</span><span class="st">&quot;Algunes t de Student&quot;</span>)</span>
<span id="cb127-3"><a href="estimació-puntual.html#cb127-3"></a><span class="kw">curve</span>(<span class="kw">dt</span>(x,<span class="dv">2</span>),<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb127-4"><a href="estimació-puntual.html#cb127-4"></a><span class="kw">curve</span>(<span class="kw">dt</span>(x,<span class="dv">3</span>),<span class="dt">col=</span><span class="dv">3</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb127-5"><a href="estimació-puntual.html#cb127-5"></a><span class="kw">curve</span>(<span class="kw">dt</span>(x,<span class="dv">4</span>),<span class="dt">col=</span><span class="dv">4</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb127-6"><a href="estimació-puntual.html#cb127-6"></a><span class="kw">curve</span>(<span class="kw">dt</span>(x,<span class="dv">5</span>),<span class="dt">col=</span><span class="dv">5</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb127-7"><a href="estimació-puntual.html#cb127-7"></a><span class="kw">curve</span>(<span class="kw">dt</span>(x,<span class="dv">10</span>),<span class="dt">col=</span><span class="dv">6</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb127-8"><a href="estimació-puntual.html#cb127-8"></a><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="dt">col=</span><span class="dv">1</span><span class="op">:</span><span class="dv">6</span>,<span class="dt">lty=</span><span class="kw">rep</span>(<span class="dv">1</span>,<span class="dv">6</span>), <span class="dt">lwd=</span><span class="kw">rep</span>(<span class="dv">2</span>,<span class="dv">6</span>),</span>
<span id="cb127-9"><a href="estimació-puntual.html#cb127-9"></a><span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;N(0,1)&quot;</span>, <span class="kw">paste</span>(<span class="st">&quot;t amb g.l.=&quot;</span>,<span class="kw">c</span>(<span class="dv">2</span><span class="op">:</span><span class="dv">5</span>,<span class="dv">10</span>),<span class="dt">sep=</span><span class="st">&quot;&quot;</span>)),<span class="dt">cex=</span><span class="fl">0.7</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-200-1.png" width="50%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="estimació-puntual.html#cb128-1"></a><span class="kw">curve</span>(<span class="kw">dnorm</span>(x),<span class="dt">col=</span><span class="dv">1</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>,<span class="dv">4</span>),<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.4</span>),</span>
<span id="cb128-2"><a href="estimació-puntual.html#cb128-2"></a>      <span class="dt">main=</span><span class="st">&quot;t vs Normal estàndard&quot;</span>)</span>
<span id="cb128-3"><a href="estimació-puntual.html#cb128-3"></a><span class="kw">curve</span>(<span class="kw">dt</span>(x,<span class="dv">50</span>),<span class="dt">col=</span><span class="dv">2</span>,<span class="dt">lwd=</span><span class="dv">2</span>,<span class="dt">add=</span><span class="ot">TRUE</span>)</span>
<span id="cb128-4"><a href="estimació-puntual.html#cb128-4"></a><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,<span class="dt">col=</span><span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,<span class="dt">lty=</span><span class="kw">rep</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">lwd=</span><span class="kw">rep</span>(<span class="dv">2</span>,<span class="dv">2</span>),</span>
<span id="cb128-5"><a href="estimació-puntual.html#cb128-5"></a>       <span class="dt">legend=</span><span class="kw">c</span>(<span class="st">&quot;N(0,1)&quot;</span>, <span class="st">&quot;t amb g.l.=50&quot;</span>),<span class="dt">cex=</span><span class="fl">0.7</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-201-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>El fet que una t de Student sigui més aplatada que una normal estàndard <span class="math inline">\(Z\)</span> implica que les cues de la t tenen major probabilitat que les de <span class="math inline">\(Z\)</span> (fixau-vos que als gràfics anteriors els extrems de les densitats de les t estan per damunt dels de la de <span class="math inline">\(Z\)</span>), la qual cosa es tradueix en el fet que és més probable obtenir valors lluny del 0 amb una t de Student que amb una <span class="math inline">\(N(0,1)\)</span>.</p>
<p>Indicarem amb <span class="math inline">\(t_{\nu,q}\)</span> el <span class="math inline">\(q\)</span>-quantil d’una variable aleatòria <span class="math inline">\(T_{\nu}\)</span> que segueix una distribució <span class="math inline">\(t_\nu\)</span>. És a dir, <span class="math inline">\(t_{\nu,q}\)</span> és el valor tal que
<span class="math display">\[
P(T_{\nu}\leq t_{\nu,q})=q
\]</span>
Per la simetria de la distribució <span class="math inline">\(t_\nu\)</span>,
<span class="math display">\[
t_{\nu,q}=-t_{\nu,1-q}.
\]</span></p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-202-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Hi ha algunes propietats dels quantils de la t de Student que heu de saber, per poder aplicar-les quan no tengueu a l’abast R o una apli per calcular quantils:</p>
<ul>
<li><span class="math inline">\(t_{\nu ,q}\approx z_{q}\)</span> si <span class="math inline">\(\nu\)</span> és molt gran, posem <span class="math inline">\(\nu \geq 200\)</span>. Per exemple</li>
</ul>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="estimació-puntual.html#cb129-1"></a><span class="kw">qt</span>(<span class="fl">0.975</span>,<span class="dv">200</span>) <span class="co"># t_{300,0.975}</span></span></code></pre></div>
<pre><code>## [1] 1.9719</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="estimació-puntual.html#cb131-1"></a><span class="kw">qnorm</span>(<span class="fl">0.975</span>)  <span class="co"># z_0.975</span></span></code></pre></div>
<pre><code>## [1] 1.95996</code></pre>
<ul>
<li><p><span class="math inline">\(t_{\nu,0.95}\)</span> (per a <span class="math inline">\(10\leq \nu\leq 200\)</span>) està entre 1.65 i 1.8; ho podeu aproximar <span class="math inline">\(t_{n,0.95}\approx 1.7\)</span></p></li>
<li><p><span class="math inline">\(t_{n,0.975}\)</span> (per a <span class="math inline">\(10\leq n\leq 200\)</span>) està entre 1.97 i 2.2; ho podeu aproximar <span class="math inline">\(t_{n,0.975}\approx 2\)</span></p></li>
</ul>

<div class="rmdexercici">
Comprovau amb R les afirmacions sobr els quantils de la t de Student dels darrers dos punts.
</div>


<div class="rmdcaution">
<p>Abans de tancar aquesta secció, recordau que, donada una variable aleatòria <span class="math inline">\(X\)</span>, no heu de confondre:</p>
<ul>
<li><p><strong>Desviació típica</strong> (o <strong>estàndard</strong>) <em>de la variable aleatòria</em>, <span class="math inline">\(\sigma_X\)</span>: El paràmetre poblacional, normalment desconegut</p></li>
<li><p><strong>Desviació típica</strong> (o <strong>estàndard</strong>) (sigui mostral, <span class="math inline">\(\widetilde{S}_X\)</span>, o a seques, <span class="math inline">\(S_X\)</span>) <em>d’una mostra</em>: L’estadístic que calculam sobre la mostra i que quantifica la dispersió de la mostra</p></li>
<li><p><strong>Error típic</strong> (o <strong>estàndard</strong>) <em>d’un estimador</em>: La desviació típica de la variable aleatòria que defineix l’estimador, normalment desconeguda</p></li>
<li><p><strong>Error típic</strong> (o <strong>estàndard</strong>) <em>d’una mostra</em>: Estimació de l’error típic de la mitjana mostral (o de la proporció mostral) a partir d’una mostra; servirà per calcular intervals de confiança. És <span class="math inline">\(\widetilde{S}_X/\sqrt{n}\)</span>.</p></li>
</ul>
</div>

</div>
<div id="bons-estimadors" class="section level2">
<h2><span class="header-section-number">3.6</span> “Bons” estimadors</h2>
<div id="estimadors-no-esbiaixats" class="section level3">
<h3><span class="header-section-number">3.6.1</span> Estimadors no esbiaixats</h3>
<p>Un estimador puntual <span class="math inline">\(\widehat{\theta}\)</span> d’un paràmetre poblacional <span class="math inline">\(\theta\)</span> és <strong>no esbiaixat</strong> (<strong>insesgado</strong>, en castellà) quan el seu valor esperat és precisament el valor poblacional del paràmetre, és a dir, quan
<span class="math display">\[
\mu_\widehat{\theta}=\theta
\]</span>
Es diu aleshores que l’estimació puntual és <strong>no esbiaixada</strong>.</p>
<p>El <strong>biaix</strong> d’un estimador <span class="math inline">\(\widehat{\theta}\)</span> d’un paràmetre <span class="math inline">\(\theta\)</span> és la diferència <span class="math inline">\(\mu_\widehat{\theta}-\theta\)</span></p>
<p><strong>Exemples:</strong> Ja hem vist a les seccions anteriors que</p>
<ul>
<li><p><span class="math inline">\(\mu_{\overline{X}}=\mu_X\)</span>. Per tant, <span class="math inline">\(\overline{X}\)</span> és sempre un estimador no esbiaixat de <span class="math inline">\(\mu_X\)</span></p></li>
<li><p><span class="math inline">\(\mu_{\widehat{p}_X}=p_X\)</span>. Per tant, <span class="math inline">\(\widehat{p}_X\)</span> és sempre un estimador no esbiaixat de <span class="math inline">\(p_X\)</span></p></li>
<li><p><span class="math inline">\(\mu_{\widetilde{S}_{X}^2}=\sigma_X^2\)</span> si <span class="math inline">\(X\)</span> és normal. Per tant, <span class="math inline">\(\widetilde{S}_{X}^2\)</span> és un estimador no esbiaixat de <span class="math inline">\(\sigma_X^2\)</span> quan <span class="math inline">\(X\)</span> és normal</p></li>
<li><p>Com que <span class="math inline">\({S}_{X}^2=\dfrac{n-1}{n}\widetilde{S}_{X}^2\)</span>, tenim que <span class="math inline">\(\mu_{{S}_{X}^2}=\dfrac{n-1}{n}\sigma_X^2\)</span> si <span class="math inline">\(X\)</span> és normal. Per tant, en aquest cas,
<span class="math inline">\({S}_{X}^2\)</span> <em>és un estimador esbiaixat de</em> <span class="math inline">\(\sigma_X^2\)</span>, amb biaix
<span class="math display">\[
\mu_{{S}_{X}^2}-\sigma_X^2=\dfrac{n-1}{n}\sigma_X^2-\sigma_X^2=-\dfrac{\sigma_X^2}{n}\ \mathop{\longrightarrow}_{\scriptscriptstyle
n\to\infty}\ 0
\]</span>
Diem en aquest cas que <strong>el biaix tendeix a 0</strong>.</p></li>
<li><p><span class="math inline">\(\mu_{\widetilde{S}_{X}}, \mu_{{S}_{X}}\neq \sigma_X\)</span> ni tan sols quan <span class="math inline">\(X\)</span> és normal. Per tant, <span class="math inline">\(\widetilde{S}_{X}\)</span> i <span class="math inline">\({S}_{X}\)</span> són estimadors <em>esbiaixats</em> de <span class="math inline">\(\sigma_X\)</span></p></li>
</ul>
</div>
<div id="estimadors-eficients" class="section level3">
<h3><span class="header-section-number">3.6.2</span> Estimadors eficients</h3>
<p>Donats dos estimadors <span class="math inline">\(\widehat{\theta}_1\)</span>, <span class="math inline">\(\widehat{\theta}_2\)</span> del mateix paràmetre <span class="math inline">\(\theta\)</span>, direm que <span class="math inline">\(\widehat{\theta}_1\)</span> és <strong>més eficient</strong>, o <strong>més precís</strong>, que <span class="math inline">\(\widehat{\theta}_2\)</span> quan l’error típic de <span class="math inline">\(\widehat{\theta}_1\)</span> és més petit que el de <span class="math inline">\(\widehat{\theta}_2\)</span>:
<span class="math display">\[
\sigma(\widehat{\theta}_1)&lt; \sigma(\widehat{\theta}_2).
\]</span></p>
<p>Normalment, només comparam l’eficiència de dos estimadors quan són no esbiaixats (o, com a molt, quan el seu biaix tendeix a 0). En aquest cas, que <span class="math inline">\(\widehat{\theta}_1\)</span> sigui més eficient que <span class="math inline">\(\widehat{\theta}_2\)</span> significa que la seva variabilitat és menor i que per tant <em>les estimacions amb <span class="math inline">\(\widehat{\theta}_1\)</span> es concentren més al voltant del seu valor esperat, que és el paràmetre <span class="math inline">\(\theta\)</span> que volem estimar, que les estimacions amb <span class="math inline">\(\widehat{\theta}_2\)</span></em>.</p>
<p><strong>Exemples:</strong></p>
<ul>
<li><p>Si <span class="math inline">\(X\)</span> és normal, <span class="math inline">\(\overline{X}\)</span> és l’estimador no esbiaixat més eficient de la mitjana poblacional <span class="math inline">\(\mu_X\)</span>.</p></li>
<li><p>Si <span class="math inline">\(X\)</span> és Bernoulli, <span class="math inline">\(\widehat{p}_X\)</span> és l’estimador
no esbiaixat més eficient de la proporció poblacional <span class="math inline">\(p_X\)</span>.</p></li>
<li><p>Si <span class="math inline">\(X\)</span> és normal, <span class="math inline">\(\widetilde{S}_X^2\)</span> és l’estimador
no esbiaixat més eficient de la variància poblacional <span class="math inline">\(\sigma_X^2\)</span>.</p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-206" class="example"><strong>Exemple 3.9  </strong></span>Sigui <span class="math inline">\(X\)</span> una variable aleatòria normal <span class="math inline">\(N(\mu_X,\sigma_X)\)</span>.
Considerem la mediana <span class="math inline">\(\mathit{Me}=Q_{0.5}\)</span> d’una mostra aleatòria simple de <span class="math inline">\(X\)</span> com a estimador puntual de <span class="math inline">\(\mu_X\)</span>, que coincideix amb la mediana de <span class="math inline">\(X\)</span> per la simetria de les variables normals.</p>
</div>

<p>Resulta que <span class="math inline">\(\mu_{\mathit{Me}}=\mu_X\)</span> però
<span class="math display">\[
\sigma^2(\mathit{Me})\approx \dfrac{\pi}{2}\cdot
     \dfrac{\sigma_{X}^2}{n}\approx 1.57 \cdot \frac{\sigma_{X}^2}{n}=1.57\sigma^2_{\overline{X}}
\]</span></p>
<p>Per tant, si <span class="math inline">\(X\)</span> és normal, la mediana <span class="math inline">\(\mathit{Me}\)</span> és un estimador no esbiaixat de <span class="math inline">\(\mu_X\)</span>, però menys eficient que <span class="math inline">\(\overline{X}\)</span>. Per això preferim emprar la mitjana mostral per estimar <span class="math inline">\(\mu_X\)</span>.</p>

<div class="rmdnote">
<p>Hem dit que si la població és normal, <span class="math inline">\(\widetilde{S}_X^2\)</span> és l’estimador no esbiaixat més eficient de la variància poblacional <span class="math inline">\(\sigma_X^2\)</span>. La variància a seques
<span class="math display">\[
S_X^2=\frac{(n-1)}{n} \widetilde{S}_X^2
\]</span><br />
és més eficient, perquè
<span class="math display">\[
\sigma(S_X^2)=\sqrt{\frac{(n-1)}{n}}\sigma(\widetilde{S}_X^2)&lt;\sigma(\widetilde{S}_X^2),
\]</span><br />
però és un estimador esbiaixat de <span class="math inline">\(\sigma_X^2\)</span>, amb biaix que tendeix a 0.</p>
Si <span class="math inline">\(n\)</span> és petit (per davall de 30), és millor fer servir la variància mostral <span class="math inline">\(\widetilde{S}_X^2\)</span> per estimar la variància, ja que el biaix pot desplaçar l’estimació, però si <span class="math inline">\(n\)</span> és gran, el biaix de <span class="math inline">\(S_X^2\)</span> ja és petit i es pot fer servir <span class="math inline">\(S_X^2\)</span>: de fet, si <span class="math inline">\(n\)</span> és molt gran, dividir per <span class="math inline">\(n\)</span> o per <span class="math inline">\(n-1\)</span> no varia gaire el resultat i per tant <span class="math inline">\(\widetilde{S}_X^2\)</span> i <span class="math inline">\(S_X^2\)</span> donen valors molt semblants.
</div>

</div>
<div id="estimadors-màxim-versemblants" class="section level3">
<h3><span class="header-section-number">3.6.3</span> Estimadors màxim versemblants</h3>
<p>Un estimador d’un paràmetre és <strong>màxim versemblant</strong> quan, aplicat a una mostra aleatòria simple d’una mida <span class="math inline">\(n\)</span> fixada,
dóna el valor del paràmetre que fa màxima la probabilitat d’obtenir aquesta mostra.</p>

<div class="rmdcorbes">
<p>En realitat, el que fa màxim l’estimació màxim versemblant d’un paràmetre és el producte dels valors de la funció densitat de la variable aleatòria poblacional aplicada als elements de la mostra. Quan la variable aleatòria és discreta, això coincideix amb el que hem dit, perquè la probabilitat d’obtenir un valor concret és la funció densitat aplicada a aquest valor. Però quan la variable aleatòria poblacional és contínua, la probabilitat d’obtenir una mostra concreta és sempre 0 i no té sentit parlar de maximitzar aquest 0. Per això es pren la funció densitat.</p>
En aquest curs no ens complicarem la vida i entendrem que el que maximitzam és la probabilitat d’obtenir la mostra.
</div>


<div class="example">
<p><span id="exm:unnamed-chunk-209" class="example"><strong>Exemple 3.10  </strong></span>Suposem que tenim una variable aleatòria Bernoulli <span class="math inline">\(X\)</span> de probabilitat d’èxit <span class="math inline">\(p_X\)</span> desconeguda. Donada una mostra aleatòria simple <span class="math inline">\(x_1,\ldots,x_n\)</span> de <span class="math inline">\(X\)</span>, siguin <span class="math inline">\(\widehat{p}_x\)</span> la seva proporció mostral i<br />
<span class="math display">\[
P(x_1,\ldots,x_n\mid p_X=p)
\]</span>
la probabilitat d’obtenir la mostra quan la probabilitat poblacional <span class="math inline">\(p_X\)</span> és igual <span class="math inline">\(p\)</span>. Un estimador per a <span class="math inline">\(p_X\)</span> és màxim versemblant quan, aplicat a cada mostra aleatòria simple <span class="math inline">\(x_1,\ldots,x_n\)</span> de <span class="math inline">\(X\)</span>, ens dóna el valor de <span class="math inline">\(p\)</span> que fa que
<span class="math display">\[
P(x_1,\ldots,x_n\mid p_X=p)
\]</span>
sigui el màxim possible.</p>
</div>

<p>Quin creieu que és l’estimador màxim versemblant de <span class="math inline">\(p_X\)</span>? Doncs sí, la proporció mostral <span class="math inline">\(\widehat{p}_X\)</span>.</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-210" class="theorem"><strong>Teorema 3.8  </strong></span>El valor de <span class="math inline">\(p\)</span> per al qual <span class="math inline">\(P(x_1,\ldots,x_n\mid p)\)</span> és màxim és <span class="math inline">\(\widehat{p}_x\)</span>.</p>
</div>


<div class="rmdcorbes">
La demostració és senzilla. Suposau que dins <span class="math inline">\(x_1,\ldots,x_n\)</span> hi ha <span class="math inline">\(m\)</span> 1s i <span class="math inline">\(n-m\)</span> 0s, de manera que <span class="math inline">\(\widehat{p}_X=m/n\)</span>. Aleshores, la probabilitat d’obtenir <span class="math inline">\(x_1,\ldots,x_n\)</span> és
<span class="math display">\[
P(x_1,\ldots,x_n\mid p)=p^m(1-p)^{n-m}
\]</span>
Per trobar el valor de <span class="math inline">\(p\)</span> que fa aquest probabilitat màxima, derivau respecte de <span class="math inline">\(p\)</span> i estudiau el signe de la derivada, i concloureu que el màxim es dóna efectivament a <span class="math inline">\(p=m/n\)</span>.
</div>


<div class="rmdimportant">
La proporció <span class="math inline">\(\widehat{p}_x\)</span> és el valor que fa màxima la probabilitat d’obtenir la nostra mostra, no a l’enrevés: <strong>No és el valor més probable de <span class="math inline">\(p_X\)</span> condicionat a la nostra mostra</strong>. Vaja, no confongueu
<span class="math display">\[
P(x_1,\ldots,x_n\mid p_X=p)\text{ amb }P(p_X=p\mid x_1,\ldots,x_n).
\]</span>
D’això darrer no en sabem trobar el màxim sense alguna hipòtesi sobre la distribució de probabilitat dels valors possibles de <span class="math inline">\(p_X\)</span>.
</div>

<p>Alguns altres estimadors màxim versemblants:</p>
<ul>
<li><p><span class="math inline">\(\overline{X}\)</span> és l’estimador màxim versemblant del paràmetre <span class="math inline">\(\lambda\)</span> d’una variable aleatòria Poisson</p></li>
<li><p><span class="math inline">\(\overline{X}\)</span> és l’estimador màxim versemblant de la mitjana <span class="math inline">\(\mu\)</span> d’una variable aleatòria normal</p></li>
</ul>
</div>
</div>
<div id="sec:pobl" class="section level2">
<h2><span class="header-section-number">3.7</span> Estimació de poblacions</h2>
<div id="estimació-de-poblacions-numerades" class="section level3">
<h3><span class="header-section-number">3.7.1</span> Estimació de poblacions numerades</h3>

<div class="example">
<p><span id="exm:taxi1" class="example"><strong>Exemple 3.11  </strong></span>Un dia vaig voler estimar quants taxis hi havia a Palma.
Per fer-ho, assegut en un bar del Passeig Marítim vaig apuntar les llicències dels 40 primers taxis que passaren. Els entraré directament en un vector de R.</p>
</div>

<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="estimació-puntual.html#cb133-1"></a>taxis=<span class="kw">c</span>(<span class="dv">1217</span>,<span class="dv">600</span>,<span class="dv">883</span>,<span class="dv">1026</span>,<span class="dv">150</span>,<span class="dv">715</span>,<span class="dv">297</span>,<span class="dv">137</span>,<span class="dv">508</span>,<span class="dv">134</span>,<span class="dv">38</span>,<span class="dv">961</span>,<span class="dv">538</span>,<span class="dv">1154</span>,<span class="dv">314</span>,<span class="dv">1121</span>,<span class="dv">823</span>,<span class="dv">158</span>,<span class="dv">940</span>,<span class="dv">99</span>,</span>
<span id="cb133-2"><a href="estimació-puntual.html#cb133-2"></a>  <span class="dv">977</span>,<span class="dv">286</span>,<span class="dv">1006</span>,<span class="dv">1207</span>,<span class="dv">264</span>,<span class="dv">1183</span>,<span class="dv">1120</span>,<span class="dv">498</span>,<span class="dv">606</span>,<span class="dv">566</span>,<span class="dv">1239</span>,<span class="dv">860</span>,<span class="dv">114</span>,<span class="dv">701</span>,<span class="dv">381</span>,<span class="dv">836</span>,<span class="dv">561</span>,<span class="dv">494</span>,<span class="dv">858</span>,<span class="dv">187</span>)</span>
<span id="cb133-3"><a href="estimació-puntual.html#cb133-3"></a><span class="kw">sort</span>(taxis)</span></code></pre></div>
<pre><code>##  [1]   38   99  114  134  137  150  158  187  264  286  297  314  381  494  498
## [16]  508  538  561  566  600  606  701  715  823  836  858  860  883  940  961
## [31]  977 1006 1026 1120 1121 1154 1183 1207 1217 1239</code></pre>
<p>Puc estimar quants taxis hi ha a Palma a partir d’aquesta mostra? Us pot semblar una beneitura de pregunta, però aquest és un problema de rellevància històrica, com podeu consultar en <a href="https://www.investigacionyciencia.es/files/14469.pdf">aquest article</a>.</p>
<p>La solució d’aquest problema és donada pel resultat següent:</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-214" class="theorem"><strong>Teorema 3.9  </strong></span>Sigui <span class="math inline">\(X\)</span> una variable aleatòria uniforme sobre <span class="math inline">\(\{1,2,\ldots,N\}\)</span>, i sigui <span class="math inline">\(x_1,\ldots,x_n\)</span> una mostra aleatòria de <span class="math inline">\(X\)</span>. Sigui <span class="math inline">\(m=\max(x_1,\ldots,x_n)\)</span>. Aleshores, l’estimador no esbiaixat més eficient de <span class="math inline">\(N\)</span> és
<span class="math display">\[
\widehat{N}=m+\frac{m-n}{n}
\]</span></p>
</div>


<div class="rmdcorbes">
La idea que hi ha sota aquesta fórmula és que si suposau que teniu <span class="math inline">\(x_1,\ldots,x_n\)</span> ordenats en ordre creixent, de manera que <span class="math inline">\(x_n=m\)</span>, i calculau la mitjana de la longitud dels “forats” a l’esquerra de cada valor <span class="math inline">\(x_i\)</span>, tenim que a l’esquerra de <span class="math inline">\(x_1\)</span> hi ha <span class="math inline">\(x_1-1\)</span> nombres i entre cada <span class="math inline">\(x_{i-1}\)</span> i <span class="math inline">\(x_{i}\)</span> hi ha <span class="math inline">\(x_{i}-x_{i-1}-1\)</span> nombres, i per tant aquesta mitjana és
<span class="math display">\[
\begin{array}{l}
\displaystyle \frac{(x_1-1)+(x_2-x_1-1)+\cdots+(x_{n}-x_{n-1}-1)}{n}\\
\displaystyle \qquad\quad =\frac{x_n-n}{n}=\frac{m-n}{n}
\end{array}
\]</span>
i el que fa l’estimador <span class="math inline">\(\widehat{N}\)</span> és sumar al màxim de la mostra, <span class="math inline">\(m\)</span>, la mitjana dels forats entre membres de la mostra. És a dir, estimam que la mida de la població és tal que a la dreta del màxim de la nostra mostra hi ha un “forat” de mida la mitjana dels forats de la mostra.
</div>


<div class="example">
<p><span id="exm:unnamed-chunk-216" class="example"><strong>Exemple 3.12  </strong></span>Continuem amb l’Exemple <a href="estimació-puntual.html#exm:taxi1">3.11</a>. Emprant la fórmula anterior, obtenim</p>
</div>

<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="estimació-puntual.html#cb135-1"></a><span class="kw">max</span>(taxis)<span class="op">+</span>(<span class="kw">max</span>(taxis)<span class="op">-</span><span class="kw">length</span>(taxis))<span class="op">/</span><span class="kw">length</span>(taxis)</span></code></pre></div>
<pre><code>## [1] 1268.97</code></pre>
<p>la qual cosa ens permet estimar que hi havia 1269 taxis a Palma.
En realitat, consultant la web de l’Ajuntament, després vaig saber que en aquell moment n’hi havia 1246.</p>

<div class="example">
<p><span id="exm:simultancs" class="example"><strong>Exemple 3.13  </strong></span>Fem un experiment. Generarem a l’atzar una mida N d’una població grandeta, i suposarem que els individus de la població estan numerats de l’1 a l’N. A continuació, prendrem 100 mostres aleaòries sense reposició de la nostra població i amb cada una d’aquestes mostres estimarem la N emprant la fórmula que hem donat. Al final, calcularem la mitjana d’aquestes estimacions i la compararem amb el valor real de N, que no descobrirem fins el final.</p>
</div>

<p>Perquè l’experiment sigui reproductible, fixarem la llavor d’aleatorietat, però perquè no cregueu que fem trampes amb aquesta llavor, el que farem serà generar a l’atzar la llavor d’aleatorietat amb la funció <code>sample</code>.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="estimació-puntual.html#cb137-1"></a>Llavor=<span class="kw">sample</span>(<span class="dv">10000</span>,<span class="dv">1</span>)</span>
<span id="cb137-2"><a href="estimació-puntual.html#cb137-2"></a>Llavor</span></code></pre></div>
<pre><code>## [1] 6283</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="estimació-puntual.html#cb139-1"></a><span class="kw">set.seed</span>(Llavor)</span></code></pre></div>
<p>Ara generam la mida N de la població com un nombre a l’atzar entre 5000 i 10000.</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="estimació-puntual.html#cb140-1"></a>N=<span class="kw">sample</span>(<span class="dv">5000</span><span class="op">:</span><span class="dv">10000</span>,<span class="dv">1</span>)</span></code></pre></div>
<p>Suposarem per tant que hi ha N individus a la nostra població, numerats de l’1 a l’N. Ara generarem 100 mostres aleatòries sense reposició d’aquesta població, i ens quedarem amb la mida i el valor màxim de cada una d’elles, que és l’únic que necessitam saber. Les mides les generarem a l’atzar entre, posem, 25 i 75:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="estimació-puntual.html#cb141-1"></a>Mostra=<span class="cf">function</span>(a,b,P){</span>
<span id="cb141-2"><a href="estimació-puntual.html#cb141-2"></a>  <span class="co">#a i b: mides màxima i mínima de la mostra; P: mida de la població</span></span>
<span id="cb141-3"><a href="estimació-puntual.html#cb141-3"></a>  n=<span class="kw">sample</span>(a<span class="op">:</span>b,<span class="dv">1</span>)  <span class="co">#Mida de la mostra</span></span>
<span id="cb141-4"><a href="estimació-puntual.html#cb141-4"></a>  X=<span class="kw">sample</span>(P,n,<span class="dt">rep=</span><span class="ot">FALSE</span>)  <span class="co"># Mostra aleatòria </span></span>
<span id="cb141-5"><a href="estimació-puntual.html#cb141-5"></a>  <span class="kw">c</span>(n,<span class="kw">max</span>(X)) <span class="co">#Parell (mida, màxim)</span></span>
<span id="cb141-6"><a href="estimació-puntual.html#cb141-6"></a>}</span>
<span id="cb141-7"><a href="estimació-puntual.html#cb141-7"></a>Mostres=<span class="kw">replicate</span>(<span class="dv">100</span>,<span class="kw">Mostra</span>(<span class="dv">25</span>,<span class="dv">75</span>,N))</span>
<span id="cb141-8"><a href="estimació-puntual.html#cb141-8"></a>Mostres</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
## [1,]   67   42   75   67   39   69   26   30   30    46    34    50    59    65
## [2,] 6442 6320 6346 6403 5805 6410 6326 6398 6365  6354  6337  6371  5932  6439
##      [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
## [1,]    55    58    74    41    28    40    39    50    52    46    74    52
## [2,]  6274  6433  6426  5795  6213  6367  6066  5903  6219  6187  6393  6333
##      [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
## [1,]    43    31    45    55    63    46    73    74    45    45    53    63
## [2,]  6243  6295  6406  6409  6308  6421  6327  6354  6319  6282  6255  6430
##      [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
## [1,]    54    28    36    61    52    53    37    29    65    75    37    43
## [2,]  6335  6002  6310  6331  6381  6338  6235  6304  6292  6394  6309  6362
##      [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
## [1,]    73    30    70    55    45    31    62    54    36    50    28    67
## [2,]  6302  6426  6278  6265  6191  6442  6389  6242  6260  6406  5937  6235
##      [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
## [1,]    25    71    40    49    65    65    55    67    55    33    39    74
## [2,]  5673  6285  6269  6200  6381  6414  6183  6304  6433  6426  6442  6372
##      [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
## [1,]    29    63    39    57    51    55    61    33    33    58    71    44
## [2,]  5602  6371  6412  6369  6374  6412  6307  5945  6259  6095  6397  6361
##      [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
## [1,]    62    68    34    68    37    39    63    65    66    68    64    36
## [2,]  6379  6435  5956  6373  6335  6285  6426  6437  6438  6403  6406  5954
##      [,99] [,100]
## [1,]    55     32
## [2,]  6271   5993</code></pre>
<p>En aquesta matriu <code>Mostres</code>, cada columna correspon a una mostra aleatòria: la primera filera és la seva mida <span class="math inline">\(n\)</span> i la segona filera el màxim <span class="math inline">\(m\)</span>. Ara, amb cada una d’aquestes mostres, podem estimar la mida N de la població per mitjà de la fórmula <span class="math inline">\(m+(m-n)/n\)</span>. Donarem aquestes estimacions ordenades de menor a major.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="estimació-puntual.html#cb143-1"></a>Estimacions=Mostres[<span class="dv">2</span>,]<span class="op">+</span>(Mostres[<span class="dv">2</span>,]<span class="op">-</span>Mostres[<span class="dv">1</span>,])<span class="op">/</span>Mostres[<span class="dv">1</span>,]</span>
<span id="cb143-2"><a href="estimació-puntual.html#cb143-2"></a><span class="kw">round</span>(<span class="kw">sort</span>(Estimacions),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##   [1] 5794.2 5898.9 5935.3 5952.8 6020.1 6031.5 6118.4 6124.2 6130.2 6148.0
##  [11] 6179.3 6199.1 6215.4 6220.5 6294.4 6320.5 6325.5 6327.1 6327.6 6337.6
##  [21] 6356.6 6366.7 6372.0 6372.5 6377.9 6384.0 6387.1 6387.2 6387.3 6387.8
##  [31] 6397.1 6402.5 6407.1 6409.4 6412.7 6420.6 6424.7 6429.6 6432.9 6433.8
##  [41] 6433.9 6438.9 6445.2 6447.7 6451.3 6453.8 6456.6 6457.1 6458.4 6465.7
##  [51] 6469.5 6471.1 6478.2 6478.3 6478.4 6478.5 6479.7 6480.9 6484.3 6486.1
##  [61] 6491.0 6491.1 6496.2 6497.1 6497.4 6497.6 6498.0 6501.9 6502.7 6504.6
##  [71] 6505.1 6505.2 6509.0 6511.7 6511.8 6520.4 6522.4 6524.5 6525.2 6527.0
##  [81] 6527.6 6528.6 6531.1 6533.1 6534.5 6535.0 6537.1 6537.1 6542.9 6547.4
##  [91] 6549.0 6559.6 6568.3 6575.4 6576.2 6606.2 6610.3 6619.7 6639.2 6648.8</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="estimació-puntual.html#cb145-1"></a><span class="kw">hist</span>(Estimacions, <span class="dt">breaks=</span><span class="dv">20</span>,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Estimacions de N&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Freqüències&quot;</span>,<span class="dt">main=</span><span class="st">&quot;&quot;</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-221-1.png" width="50%" style="display: block; margin: auto;" />
Com veieu, obtenim estimacions que van de 5794.2 a 6648.8. La mitjana d’aquestes estimacions és</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="estimació-puntual.html#cb146-1"></a><span class="kw">round</span>(<span class="kw">mean</span>(Estimacions),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 6415.9</code></pre>
<p>És hora de descobrir el valor de N, per veure si ens hi hem fet a prop:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="estimació-puntual.html#cb148-1"></a>N</span></code></pre></div>
<pre><code>## [1] 7134</code></pre>
<p>No hem fet molt enfora, com veieu.</p>
</div>
<div id="marca-recaptura" class="section level3">
<h3><span class="header-section-number">3.7.2</span> Marca-recaptura</h3>
<p>Suposem que en una població hi ha <span class="math inline">\(N\)</span> individus, en capturam <span class="math inline">\(K\)</span> (tots diferents), els marcam i els tornam a amollar. Al cap de poc temps, en capturam <span class="math inline">\(n\)</span>, dels quals <span class="math inline">\(k\)</span> estan marcats. A partir d’aquestes dades, volem estimar <span class="math inline">\(N\)</span>.</p>
<p>Si suposam que <span class="math inline">\(N\)</span> i <span class="math inline">\(K\)</span> no han canviat de la primera a la segona captura (cap individu no ha abandonat la població ni s’hi ha incorporat), aleshores la variable aleatòria
<span class="math inline">\(X\)</span> definida per “Capturam un individu i miram si està marcat” és Bernoulli <span class="math inline">\(Be(p)\)</span> amb <span class="math inline">\(p=K/N\)</span>, on coneixem la <span class="math inline">\(K\)</span> i volem estimar la <span class="math inline">\(N\)</span>.</p>
<p>Sigui ara <span class="math inline">\(x_1,\ldots,x_n\)</span> la mostra capturada en segon lloc. La seva proporció mostral d’individus marcats és <span class="math inline">\(\widehat{p}_X=k/n\)</span>. Com que <span class="math inline">\(\widehat{p}_X\)</span> és l’estimador màxim versemblant de <span class="math inline">\(p\)</span>, estimam que
<span class="math display">\[
\dfrac{K}{N}=\dfrac{k}{n}
\]</span>
d’on, aïllant la <span class="math inline">\(N\)</span>, estimam que
<span class="math display">\[
N=\frac{n\cdot K}{k}.
\]</span></p>
<p>En resum, l’estimador
<span class="math display">\[
\widehat{N}=\frac{n\cdot K}{k}
\]</span>
maximitza la probabilitat d’obtenir <span class="math inline">\(k\)</span> individus marcats en una mostra aleatòria de <span class="math inline">\(n\)</span> individus. És l’<strong>estimador màxim versemblant</strong> de <span class="math inline">\(N\)</span> a partir de <span class="math inline">\(K\)</span>, <span class="math inline">\(k\)</span> i <span class="math inline">\(n\)</span>; també se li diu <strong>estimador de Lincoln-Petersen</strong>. Fixau-vos que aquest estimador no fa res més que traduir la proporció “Si he trobat <span class="math inline">\(k\)</span> individus marcats en un conjunt de <span class="math inline">\(n\)</span> individus, què ha de valer el nombre total <span class="math inline">\(N\)</span> de individus perquè hi hagi en total <span class="math inline">\(K\)</span> individus marcats?”</p>

<div class="example">
<p><span id="exm:MR" class="example"><strong>Exemple 3.14  </strong></span>Suposem que hem marcat 15 peixos d’un llac, i que en una captura posterior de 10 peixos, n’hi ha 4 de marcats. Quants peixos conté el llac?</p>
</div>

<p>Ho estimarem amb l’estimador de Lincoln-Petersen:
<span class="math display">\[
\widehat{N}=\frac{15\cdot 10}{4}=37.5
\]</span>
Per tant, estimam que hi haurà entre 37 i 38 peixos al llac.</p>
<p>En aquest cas podem comprovar la màxima versemblança d’aquesta estimació, calculant la probabilitat d’obtenir 4 individus marcats en una mostra aleatòria de 10 individus d’una població de <span class="math inline">\(N\)</span> individus on n’hi ha 15 de marcats i trobant la <span class="math inline">\(N\)</span> que maximitza aquesta probabilitat. Per fer-ho, recordem que si una població està formada per <span class="math inline">\(K\)</span> subjectes marcats i <span class="math inline">\(N-K\)</span> subjectes no marcats, el nombre de subjectes marcats en mostres aleatòries sense reposició de mida <span class="math inline">\(n\)</span> segueix una distribució hipergeomètrica <span class="math inline">\(H(K, N-K,n)\)</span>. Per tant, per a cada possible <span class="math inline">\(N\)</span>, la probabilitat que en una mostra de 10 peixos del nostre llac n’hi hagi 4 de marcats serà <code>dhyper(4,15,N-15,10)</code>.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="estimació-puntual.html#cb150-1"></a>N=<span class="dv">15</span><span class="op">:</span><span class="dv">1000</span>  <span class="co">#Rang de possibles valors de N</span></span>
<span id="cb150-2"><a href="estimació-puntual.html#cb150-2"></a>p=<span class="kw">dhyper</span>(<span class="dv">4</span>,<span class="dv">15</span>,N<span class="dv">-15</span>,<span class="dv">10</span>)  <span class="co">#Probabilitats de 4 marcats en 10</span></span>
<span id="cb150-3"><a href="estimació-puntual.html#cb150-3"></a>Nmax=N[<span class="kw">which</span>(p<span class="op">==</span><span class="kw">max</span>(p))] <span class="co"># N que maximitza la probabilitat</span></span>
<span id="cb150-4"><a href="estimació-puntual.html#cb150-4"></a>Nmax</span></code></pre></div>
<pre><code>## [1] 37</code></pre>
<p>Aquest <code>Nmax</code> és la <span class="math inline">\(N\)</span> que fa màxima la probabilitat que en una mostra de 10 peixos del nostre llac n’hi hagi 4 de marcats. Vegem-ho amb un gràfic:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="estimació-puntual.html#cb152-1"></a><span class="kw">plot</span>(N[<span class="dv">1</span><span class="op">:</span><span class="dv">86</span>],p[<span class="dv">1</span><span class="op">:</span><span class="dv">86</span>],<span class="dt">type=</span><span class="st">&quot;h&quot;</span>,<span class="dt">xaxp=</span><span class="kw">c</span>(<span class="dv">15</span>,<span class="dv">100</span>,<span class="dv">17</span>),<span class="dt">xlab=</span><span class="st">&quot;N&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;p&quot;</span>)</span>
<span id="cb152-2"><a href="estimació-puntual.html#cb152-2"></a><span class="kw">points</span>(Nmax,<span class="kw">dhyper</span>(<span class="dv">4</span>,<span class="dv">15</span>,Nmax<span class="dv">-15</span>,<span class="dv">10</span>),<span class="dt">type=</span><span class="st">&quot;h&quot;</span>,<span class="dt">col=</span><span class="st">&quot;red&quot;</span>,<span class="dt">lwd=</span><span class="fl">1.5</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-225-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Un altre estimador per a <span class="math inline">\(N\)</span> a partir de <span class="math inline">\(K\)</span>, <span class="math inline">\(n\)</span> i <span class="math inline">\(k\)</span> és l’<strong>estimador de Chapman</strong>:
<span class="math display">\[
\widehat{N}=\frac{(n+1)\cdot (K+1)}{k+1}-1
\]</span></p>
<p>La idea és que afegim a la població un individu extra i marcat, que suposam que també capturam a la segona mostra. Llavors, aplicam l’estimador anterior i finalment restam 1, per descomptar l’individu marcat extra que realment no pertany a la població que volem estimar.</p>
<p>En la situació de l’Exemple <a href="estimació-puntual.html#exm:MR">3.14</a>, aquest estimador dóna
<span class="math display">\[
\widehat{N}=\frac{16\cdot 11}{5}-1=34.2
\]</span>
i ens fa estimar una població total d’uns 34 peixos. Abans hem obtingut entre 37 i 38 peixos.</p>

<div class="rmdnote">
Quina de les dues estimacions s’acosta més a la realitat? Ni idea, no ho podem saber. Amb una altra recaptura segurament haguéssim obtingut resultats diferents.
</div>

<p>L’estimador de Lincoln-Petersen
<span class="math display">\[
\widehat{N}=\frac{n\cdot K}{k}
\]</span>
és esbiaixat, amb biaix que tendeix a 0. L’estimador de Chapman és menys esbiaixat però no és màxim versemblant.</p>

<div class="example">
<p><span id="exm:simulpeixos" class="example"><strong>Exemple 3.15  </strong></span>Fem un experiment similar al de l’Exemple <a href="estimació-puntual.html#exm:simultancs">3.13</a>. Generarem a l’atzar una mida N d’una població grandeta i en marcarem una certa quantitat K. A continuació, prendrem 50 mostres aleaòries sense reposició de la nostra població i amb cada una d’aquestes mostres estimarem la N emprant els dos estimadors que hem explicat en aquesta subsecció. Al final, calcularem les mitjanes d’aquestes estimacions i les compararem amb el valor real de N, que no descobrirem fins el final. Com a l’Exemple <a href="estimació-puntual.html#exm:simultancs">3.13</a>, fixarem la llavor d’aleatorietat a l’atzar.</p>
</div>

<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="estimació-puntual.html#cb153-1"></a>Llavor2=<span class="kw">sample</span>(<span class="dv">10000</span>,<span class="dv">1</span>)</span>
<span id="cb153-2"><a href="estimació-puntual.html#cb153-2"></a>Llavor2</span></code></pre></div>
<pre><code>## [1] 6244</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="estimació-puntual.html#cb155-1"></a><span class="kw">set.seed</span>(Llavor2)</span></code></pre></div>
<p>Ara generam la mida N de la població com un nombre a l’atzar entre 5000 i 10000.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="estimació-puntual.html#cb156-1"></a>N=<span class="kw">sample</span>(<span class="dv">5000</span><span class="op">:</span><span class="dv">10000</span>,<span class="dv">1</span>)</span></code></pre></div>
<p>Ara en capturam i marcam K; per fixar idees, prendrem K=200.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="estimació-puntual.html#cb157-1"></a>K=<span class="dv">200</span></span></code></pre></div>
<p>Per simplificar, suposarem que els N individus de la nostra població estan numerats de l’1 a l’N i que els marcats són els K primers. Ara generarem 100 mostres aleatòries sense reposició d’aquesta població, i ens quedarem amb la mida i el nombre d’individus marcats (és a dir, el nombre de valors menor o iguals a K=100 en la mostra). Les mides les generarem a l’atzar entre, posem, 50 i 150:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="estimació-puntual.html#cb158-1"></a>Mostra=<span class="cf">function</span>(a,b,P,M){</span>
<span id="cb158-2"><a href="estimació-puntual.html#cb158-2"></a>  <span class="co">#a i b: mides màxima i mínima de la mostra; P: mida de la població;</span></span>
<span id="cb158-3"><a href="estimació-puntual.html#cb158-3"></a>  <span class="co">#M: nombre de marcats</span></span>
<span id="cb158-4"><a href="estimació-puntual.html#cb158-4"></a>  n=<span class="kw">sample</span>(a<span class="op">:</span>b,<span class="dv">1</span>)  <span class="co">#Mida de la mostra</span></span>
<span id="cb158-5"><a href="estimació-puntual.html#cb158-5"></a>  X=<span class="kw">sample</span>(P,n,<span class="dt">rep=</span><span class="ot">FALSE</span>)  <span class="co"># Mostra aleatòria </span></span>
<span id="cb158-6"><a href="estimació-puntual.html#cb158-6"></a>  <span class="kw">c</span>(n,<span class="kw">length</span>(<span class="kw">which</span>(X<span class="op">&lt;=</span>M))) <span class="co">#Parell (mida, nombre de marcats)</span></span>
<span id="cb158-7"><a href="estimació-puntual.html#cb158-7"></a>}</span>
<span id="cb158-8"><a href="estimació-puntual.html#cb158-8"></a>Mostres=<span class="kw">replicate</span>(<span class="dv">100</span>,<span class="kw">Mostra</span>(<span class="dv">50</span>,<span class="dv">150</span>,N,K))</span>
<span id="cb158-9"><a href="estimació-puntual.html#cb158-9"></a>Mostres</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
## [1,]   79   94  110  116  128  127   68   59  144   135   147    86    89    51
## [2,]    2    2    1    2    1    3    2    1    4     2    10     8     4     0
##      [,15] [,16] [,17] [,18] [,19] [,20] [,21] [,22] [,23] [,24] [,25] [,26]
## [1,]   121    95    50    54    71    67   113   141    65   129   111    97
## [2,]     4     4     0     2     3     0     0     4     3     3     5     2
##      [,27] [,28] [,29] [,30] [,31] [,32] [,33] [,34] [,35] [,36] [,37] [,38]
## [1,]    74   102    88    82   112    92   120   138    82    65   103   114
## [2,]     1     2     3     9     1     6     1     2     1     3     6     5
##      [,39] [,40] [,41] [,42] [,43] [,44] [,45] [,46] [,47] [,48] [,49] [,50]
## [1,]   106    72    57    54   123    68    51    52    81    75   121    90
## [2,]     1     0     0     2     3     1     2     2     2     2     3     3
##      [,51] [,52] [,53] [,54] [,55] [,56] [,57] [,58] [,59] [,60] [,61] [,62]
## [1,]    87   123   128    73   139   115   130    50   102    80    90    92
## [2,]     1     1     3     2     5     2     1     2     2     3     2     1
##      [,63] [,64] [,65] [,66] [,67] [,68] [,69] [,70] [,71] [,72] [,73] [,74]
## [1,]   143   125   141   132    54   102    79   100   107   137   113   118
## [2,]     3     5     6     1     1     4     3     2     4     4     2     4
##      [,75] [,76] [,77] [,78] [,79] [,80] [,81] [,82] [,83] [,84] [,85] [,86]
## [1,]   106   101    78    56    99    82   118   131   102   108    63   136
## [2,]     4     3     6     3     3     2     4     6     0     4     1     5
##      [,87] [,88] [,89] [,90] [,91] [,92] [,93] [,94] [,95] [,96] [,97] [,98]
## [1,]    60    73    81   107   130    70    70    54   103    77   115   133
## [2,]     4     0     1     3     4     1     1     2     3     3     1     5
##      [,99] [,100]
## [1,]    75    100
## [2,]     1      3</code></pre>
<p>En aquesta matriu <code>Mostres</code>, cada columna correspon a una mostra aleatòria: la primera filera és la seva mida <span class="math inline">\(n\)</span> i la segona filera el nombre d’individus marcats a la mostra. Ara, amb cada una d’aquestes mostres, podem estimar la mida N de la població per mitjà de l’estimador de Lincoln-Petersen.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="estimació-puntual.html#cb160-1"></a>EstimacionsLP=Mostres[<span class="dv">1</span>,]<span class="op">*</span>K<span class="op">/</span>Mostres[<span class="dv">2</span>,]</span>
<span id="cb160-2"><a href="estimació-puntual.html#cb160-2"></a><span class="kw">round</span>(<span class="kw">sort</span>(EstimacionsLP),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##   [1]  1822.2  2150.0  2600.0  2940.0  3000.0  3066.7  3433.3  3733.3  4333.3
##  [10]  4333.3  4366.7  4440.0  4450.0  4560.0  4700.0  4733.3  4750.0  5000.0
##  [19]  5000.0  5100.0  5100.0  5133.3  5200.0  5266.7  5300.0  5320.0  5333.3
##  [28]  5350.0  5400.0  5400.0  5400.0  5400.0  5440.0  5560.0  5866.7  5900.0
##  [37]  5900.0  6000.0  6050.0  6500.0  6600.0  6666.7  6733.3  6800.0  6850.0
##  [46]  6866.7  7050.0  7133.3  7200.0  7300.0  7500.0  7900.0  8066.7  8100.0
##  [55]  8200.0  8200.0  8466.7  8533.3  8600.0  9000.0  9400.0  9533.3  9700.0
##  [64] 10000.0 10200.0 10200.0 10800.0 11300.0 11500.0 11600.0 11800.0 12600.0
##  [73] 13500.0 13600.0 13800.0 14000.0 14000.0 14800.0 15000.0 16200.0 16400.0
##  [82] 17400.0 18400.0 21200.0 22000.0 22400.0 23000.0 24000.0 24600.0 25600.0
##  [91] 26000.0 26400.0     Inf     Inf     Inf     Inf     Inf     Inf     Inf
## [100]     Inf</code></pre>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="estimació-puntual.html#cb162-1"></a><span class="kw">hist</span>(EstimacionsLP, <span class="dt">breaks=</span><span class="dv">20</span>,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Estimacions de N&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Freqüències&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Estimador de Lincoln-Petersen&quot;</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-231-1.png" width="50%" style="display: block; margin: auto;" />
Com veieu, obtenim estimacions que van de 1822.2 a <span class="math inline">\(\infty\)</span>, que corresponen a mostres on no ens ha sortit cap individu marcat. La mitjana de les estimacions finites és</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="estimació-puntual.html#cb163-1"></a><span class="kw">round</span>(<span class="kw">mean</span>(EstimacionsLP[<span class="kw">is.finite</span>(EstimacionsLP)]),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 9261.2</code></pre>
<p>També podem emprar l’estimador de Chapman:</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="estimació-puntual.html#cb165-1"></a>EstimacionsCh=(Mostres[<span class="dv">1</span>,]<span class="op">+</span><span class="dv">1</span>)<span class="op">*</span>(K<span class="op">+</span><span class="dv">1</span>)<span class="op">/</span>(Mostres[<span class="dv">2</span>,]<span class="op">+</span><span class="dv">1</span>)<span class="op">-</span><span class="dv">1</span></span>
<span id="cb165-2"><a href="estimació-puntual.html#cb165-2"></a><span class="kw">round</span>(<span class="kw">sort</span>(EstimacionsCh),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##   [1]  1667.3  1942.0  2267.4  2451.2  2669.4  2703.4  2863.2  2985.3  3315.5
##  [10]  3315.5  3416.0  3483.0  3550.0  3617.0  3617.0  3684.0  3684.0  3684.0
##  [19]  3751.0  3789.3  3851.5  3858.2  3918.5  4019.0  4069.2  4076.4  4139.6
##  [28]  4220.0  4300.4  4340.6  4380.8  4471.2  4488.0  4571.8  4588.5  4622.0
##  [37]  4689.0  4782.8  4782.8  4903.4  4957.0  5024.0  5074.2  5091.0  5124.5
##  [46]  5225.0  5265.2  5359.0  5426.0  5493.0  5526.5  5546.6  5560.0  5707.4
##  [55]  5828.0  6029.0  6096.0  6129.5  6230.0  6364.0  6431.0  6431.0  6481.2
##  [64]  6531.5  6565.0  6766.0  6900.0  6900.0  6933.5  7134.5  7134.5  7235.0
##  [73]  7536.5  7637.0  7637.0  7771.0  7838.0  8240.0  8340.5  8843.0  9111.0
##  [82]  9312.0  9345.5 10250.0 10451.0 10752.5 11154.5 11355.5 11657.0 11657.0
##  [91] 12159.5 12461.0 12963.5 13164.5 13365.5 13667.0 14672.0 14873.0 20702.0
## [100] 22913.0</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="estimació-puntual.html#cb167-1"></a><span class="kw">hist</span>(EstimacionsCh, <span class="dt">breaks=</span><span class="dv">20</span>,<span class="dt">col=</span><span class="st">&quot;light blue&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;Estimacions de N&quot;</span>,<span class="dt">ylab=</span><span class="st">&quot;Freqüències&quot;</span>,<span class="dt">main=</span><span class="st">&quot;Estimador de Chapman&quot;</span>)</span></code></pre></div>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-233-1.png" width="50%" style="display: block; margin: auto;" />
Com veieu, obtenim estimacions que van de 1667.3 a 22913; per construcció, no hi ha estimacions infinites. La mitjana d’aquestes estimacions és</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="estimació-puntual.html#cb168-1"></a><span class="kw">round</span>(<span class="kw">mean</span>(EstimacionsCh),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 6618.6</code></pre>
<p>És hora de descobrir el valor de N, per veure si ens hi hem fet a prop:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="estimació-puntual.html#cb170-1"></a>N</span></code></pre></div>
<pre><code>## [1] 7134</code></pre>
</div>
</div>
<div id="test-de-la-lliçó-3" class="section level2">
<h2><span class="header-section-number">3.8</span> Test de la lliçó 3</h2>
<p><strong>(1)</strong> Tenim una variable aleatòria <span class="math inline">\(X\)</span> normal de mitjana <span class="math inline">\(\mu\)</span> i desviació típica <span class="math inline">\(\sigma\)</span>. Prenem mostres aleatòries simples de mida <span class="math inline">\(n\)</span>, i indicam amb <span class="math inline">\(\widetilde{S}_X\)</span> la seva desviació típica mostral. Quines de les afirmacions següents són vertaderes? Marca totes les respostes vertaderes:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(E(\widetilde{S}_X^2)=\sigma^2\)</span>.</li>
<li><span class="math inline">\(E(\widetilde{S}_X)=\sigma\)</span>.</li>
<li><span class="math inline">\(\widetilde{S}_X^2\)</span> segueix una distribució <span class="math inline">\(\chi^2\)</span> amb <span class="math inline">\(n-1\)</span> graus de llibertat.</li>
<li><span class="math inline">\((n-1)\widetilde{S}_X^2/\sigma^2\)</span> segueix una distribució <span class="math inline">\(\chi^2\)</span> amb <span class="math inline">\(n-1\)</span> graus de llibertat.</li>
<li>Totes les altres respostes són falses.</li>
</ol>
<p><strong>(2)</strong> Quina o quines de les afirmacions següents sobre la mitjana mostral són vertaderes?</p>
<ol style="list-style-type: decimal">
<li>Si la distribució poblacional és normal, sempre coincideix amb la mediana de la mostra.</li>
<li>Sempre serveix per estimar la mitjana poblacional.</li>
<li>Sempre serveix per estimar la mediana poblacional.</li>
<li>Si la distribució poblacional és normal, serveix per estimar la mediana poblacional.</li>
<li>Cap de les altres respostes és correcta.</li>
</ol>
<p><strong>(3)</strong> L’error estàndard de la mitjana mostral (marca totes les continuacions correctes):</p>
<ol style="list-style-type: decimal">
<li>Mesura la variabilitat de les observacions que formen la mostra.</li>
<li>És l’exactitud amb què es mesura cada observació de la mostra.</li>
<li>Mesura la variabilitat de les mitjanes mostrals de mostres aleatòries simples.</li>
<li>És proporcional a la mitjana mostral.</li>
<li>És més gran que la desviació típica de la població.</li>
<li>Sobre cada mostra val la desviació típica de la mostra.</li>
<li>Cap de les altres respostes és correcta.</li>
</ol>
<p><strong>(4)</strong> La proporció d’afectats per una determinada malaltia en una població és del 10%. Si estimam aquesta proporció poblacional repetidament a partir de mostres de mida 1000, aquestes estimacions segueixen una distribució que (marca totes les afirmacions correctes):</p>
<ol style="list-style-type: decimal">
<li>És una distribució mostral.</li>
<li>És aproximadament normal.</li>
<li>Té mitjana 0.1.</li>
<li>Té variància 90.</li>
<li>És binomial.</li>
<li>Cap de les altres respostes és correcta.</li>
</ol>
<p><strong>(5)</strong> Si volem disminuir a la meitat l’error estàndard d’una proporció mostral (marcau una sola resposta):</p>
<ol style="list-style-type: decimal">
<li>Hem d’augmentar en un 50% la mida de la mostra</li>
<li>Hem de doblar la mida de la mostra.</li>
<li>Hem de quadruplicar la mida de la mostra.<br />
</li>
<li>Hem de dividir per 2 la mida de la mostra.</li>
<li>Hem de dividir per 4 la mida de la mostra.</li>
<li>Cap de les altres respostes és correcta.</li>
</ol>
<p><strong>(6)</strong> La probabilitat que els individus d’una determinada població tenguin una determinada característica <span class="math inline">\(C\)</span> és <span class="math inline">\(p\)</span>. Prenem mostres aleatòries simples de mida <span class="math inline">\(n\)</span> d’aquesta població, i indicam amb <span class="math inline">\(\widehat{p}_X\)</span> la seva proporció mostral. Quina o quines de les afirmacions següents són vertaderes?</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\widehat{p}_X\)</span> té sempre distribució binomial <span class="math inline">\(B(n,p)\)</span>.</li>
<li><span class="math inline">\(\widehat{p}_X\)</span> té sempre distribució normal.</li>
<li>Si <span class="math inline">\(n\)</span> és gran, <span class="math inline">\(\widehat{p}_X\)</span> té distribució aproximadament binomial <span class="math inline">\(B(n,p)\)</span>.</li>
<li>Si <span class="math inline">\(n\)</span> és gran, <span class="math inline">\(\widehat{p}_X\)</span> té distribució aproximadament normal.</li>
<li>L’error estàndard de <span class="math inline">\(\widehat{p}_X\)</span> és <span class="math inline">\(\sqrt{p(1-p)/n}\)</span>.</li>
</ol>
<p><strong>(7)</strong> Si prenem mostres aleatòries simples més grans (marca totes les continuacions correctes):</p>
<ol style="list-style-type: decimal">
<li>La mitjana mostral sempre disminueix.</li>
<li>L’error estàndard de la mitjana sempre disminueix.</li>
<li>L’error estàndard de la mitjana sempre augmenta.<br />
</li>
<li>La variància mostral sempre augmenta.</li>
<li>El nombre de graus de llibertat de l’estimador <span class="math inline">\(\chi^2\)</span> associat a la variància mostral sempre augmenta.</li>
<li>Cap de les altres respostes és correcta.</li>
</ol>
<p><strong>(8)</strong> La longitud d’una determinada espècie d’animalons té un valor mitjà de <span class="math inline">\(\mu\)</span> cm. Si prenem mostres aleatòries simples de 20 exemplars, calculam la seva mitjana mostral <span class="math inline">\(\overline{X}\)</span> i la seva desviació típica mostral <span class="math inline">\(\widetilde{S}_X\)</span> (marca la continuació més correcta):</p>
<ol style="list-style-type: decimal">
<li>L’estadístic <span class="math inline">\(\frac{\overline{X}-\mu}{\widetilde{S}_X/\sqrt{20}}\)</span> segueix sempre una llei normal.</li>
<li>L’estadístic <span class="math inline">\(\frac{\overline{X}-\mu}{\widetilde{S}_X/\sqrt{20}}\)</span> segueix sempre una llei t de Student.</li>
<li>L’estadístic <span class="math inline">\(\frac{\overline{X}-\mu}{\widetilde{S}_X/\sqrt{20}}\)</span> segueix una llei normal si la longitud segueix una llei normal.</li>
<li>L’estadístic <span class="math inline">\(\frac{\overline{X}-\mu}{\widetilde{S}_X/\sqrt{20}}\)</span> segueix una llei t de Student si la longitud segueix una llei normal.</li>
<li>L’estadístic <span class="math inline">\(\frac{\overline{X}-\mu}{\widetilde{S}_X/\sqrt{20}}\)</span> no segueix mai ni una llei normal ni una llei t de Student, perquè les mostres no són prou grans.</li>
</ol>
<p><strong>(9)</strong> Sobre una mostra de 100 dones es va obtenir una concentració mitjana d’hemoglobina en sang de 10 amb una desviació típica de 2. Quin és l’error típic de la mostra?</p>
<ol style="list-style-type: decimal">
<li>0.02</li>
<li>0.04</li>
<li>0.2</li>
<li>0.4</li>
<li>1</li>
<li>Cap dels valors anteriors</li>
</ol>
<p><strong>(10)</strong> Què significa que un estimador d’un paràmetre d’una variable aleatòria sigui no esbiaixat?</p>
<ol style="list-style-type: decimal">
<li>Que la distribució mostral de l’estimador és normal.</li>
<li>Que aplicat a una m.a.s. sempre dóna el valor poblacional del paràmetre.</li>
<li>Que el seu valor esperat és igual al valor poblacional del paràmetre.</li>
<li>Que aplicat a una m.a.s. sempre dóna el valor esperat del paràmetre.</li>
<li>Que el seu error típic és petit.</li>
</ol>
<p><strong>(11)</strong> La concentració en sang a les persones d’un determinat metabolit (en mg/ml) té una distribució <span class="math inline">\(N(23,3)\)</span>. Quina de les afirmacions següents és vertadera?</p>
<ol style="list-style-type: decimal">
<li>Aproximadament un 90% de les mostres aleatòries de 100 individus tindran la seva mitjana entre 22.4 i 23.6 mg/ml.</li>
<li>Aproximadament un 95% de les mostres aleatòries de 100 individus tindran la seva mitjana entre 22.4 i 23.6 mg/ml.</li>
<li>Aproximadament un 99% de les mostres aleatòries de 100 individus tindran la seva mitjana entre 22.4 i 23.6 mg/ml.</li>
<li>Més d’un 99% de les mostres aleatòries de 100 individus tindran mitjana igual a 23.</li>
<li>Cap de les afirmacions anteriors és vertadera.</li>
</ol>
<p><strong>(12)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria <span class="math inline">\(N(\mu_X,2)\)</span> i sigui <span class="math inline">\(\overline{X}\)</span> la mitjana mostral de mida <span class="math inline">\(10\)</span> de <span class="math inline">\(X\)</span>. Quina de les afirmacions següents és vertadera?</p>
<ol style="list-style-type: decimal">
<li>La desviació típica de <span class="math inline">\(\overline{X}\)</span> és igual a 2.</li>
<li>La desviació típica de <span class="math inline">\(\overline{X}\)</span> és menor que 2.</li>
<li>La desviació típica de <span class="math inline">\(\overline{X}\)</span> és major que 2.</li>
<li>Que la desviació típica de <span class="math inline">\(\overline{X}\)</span> sigui major, menor o
igual que 2 depèn de <span class="math inline">\(\mu_X\)</span>.</li>
<li>Cap de les afirmacions anteriors és vertadera.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-conceptes.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="intervals-de-confiança.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
