<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Tema 1 Més ANOVA | Matemàtiques II</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Tema 1 Més ANOVA | Matemàtiques II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 1 Més ANOVA | Matemàtiques II" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2020-03-18">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="index.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="chapter" data-level="1" data-path="mes-anova.html"><a href="mes-anova.html"><i class="fa fa-check"></i><b>1</b> Més ANOVA</a><ul>
<li class="chapter" data-level="1.1" data-path="mes-anova.html"><a href="mes-anova.html#anova-de-blocs"><i class="fa fa-check"></i><b>1.1</b> ANOVA de blocs</a><ul>
<li class="chapter" data-level="1.1.1" data-path="mes-anova.html"><a href="mes-anova.html#contrast-basic"><i class="fa fa-check"></i><b>1.1.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="1.1.2" data-path="mes-anova.html"><a href="mes-anova.html#amb-r"><i class="fa fa-check"></i><b>1.1.2</b> Amb R</a></li>
<li class="chapter" data-level="1.1.3" data-path="mes-anova.html"><a href="mes-anova.html#comparacions-posteriors-per-parelles"><i class="fa fa-check"></i><b>1.1.3</b> Comparacions posteriors per parelles</a></li>
<li class="chapter" data-level="1.1.4" data-path="mes-anova.html"><a href="mes-anova.html#contrast-no-parametric"><i class="fa fa-check"></i><b>1.1.4</b> Contrast no paramètric</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="mes-anova.html"><a href="mes-anova.html#anova-de-2-vies"><i class="fa fa-check"></i><b>1.2</b> ANOVA de 2 vies</a><ul>
<li class="chapter" data-level="1.2.1" data-path="mes-anova.html"><a href="mes-anova.html#contrast-basic-1"><i class="fa fa-check"></i><b>1.2.1</b> Contrast bàsic</a></li>
<li class="chapter" data-level="1.2.2" data-path="mes-anova.html"><a href="mes-anova.html#amb-r-1"><i class="fa fa-check"></i><b>1.2.2</b> Amb R</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="mes-anova" class="section level1">
<h1><span class="header-section-number">Tema 1</span> Més ANOVA</h1>
<div id="anova-de-blocs" class="section level2">
<h2><span class="header-section-number">1.1</span> ANOVA de blocs</h2>
<p>De la mateixa manera que l’ANOVA d’1 via generalitza a més de dues mitjanes el contrast d’igualtat de dues mitjanes emprant mostres independents, l’<strong>ANOVA de blocs</strong> generalitza a més de dues mitjanes el contrast d’igualtat de dues mitjanes emprant mostres <strong>aparellades</strong>.</p>
<div id="contrast-basic" class="section level3">
<h3><span class="header-section-number">1.1.1</span> Contrast bàsic</h3>
<p>Comencem amb un exemple</p>

<div class="example">
<p><span id="exm:esports" class="example"><strong>Exemple 1.1  </strong></span>Volem determinar si l’energia que es requereix per dur a terme tres activitats físiques (córrer, caminar i muntar amb bicicleta) és la mateixa o no. Quantificam aquesta energia amb el nombre de Kcal consumides per Km recorregut.</p>
</div>

<p><img src="Bioestadistica-II_files/figure-html/esports.png" width="40%" style="display: block; margin: auto;" /></p>
<p>Les diferències metabòliques entre els individus poden afectar l’energia requerida per dur a terme una determinada activitat. Per tant, no és aconsellable triar tres grups d’individus i a cada grup fer-li fer una de les tres activitats físiques: les diferències metabòliques entre els individus triats podrien afectar els resultats i amagar l’efecte real.</p>
<p>Ens decidim per un <strong>disseny experimental en paral·lel</strong>: Seleccionam alguns individus i demanam a cadascun que corri, camini i recorri amb bicicleta una distància fixada en tres moments diferents, seleccionant l’ordre de les activitats de cada individu a l’atzar, i mesuram per a cada individu i cada activitat el consum de Kca/Km.</p>

<div class="rmdcaution">
Si a tots els individus els féssim fer les tres activitats en el mateix ordre, podria ser que qualque factor extern que no controlàssim influís en el resultat. Per exemple, si tots caminen al mateix temps, després corren al mateix temps i després pedalen al mateix temps, i hi ha grans diferències de temperatura ambient entre els tres moments, això podria influir en el resultat final. Si, en canvi, aleatoritzam l’ordre de les activitats, en principi aquestes diferències es compensen.
</div>

<p>Aquests són els resultats obtinguts per a 8 individus:</p>
<p><span class="math display">\[
\begin{array}{c}
\hphantom{Individu}\text{Activitat}\\
\begin{array}{c|ccc}
\text{Individu} &amp;\text{1 (corrent)} &amp;\text{2 (caminant)}&amp;\text{3 (pedalant)}\\
\hline
1&amp;1.4&amp;1.1&amp;0.7\\
2&amp;1.5&amp;1.2&amp;0.8\\
3&amp;1.8&amp;1.3&amp;0.7\\
4&amp;1.7&amp;1.3&amp;0.8\\
5&amp;1.6&amp;0.7&amp;0.1\\
6&amp;1.5&amp;1.2&amp;0.7\\
7&amp;1.7&amp;1.1&amp;0.4\\
8&amp;2.0&amp;1.3&amp;0.6\\
\end{array}
\end{array}
\]</span></p>
<p>En aquest estudi, fixau-vos que empram els nivells d’un factor (tipus de desplaçament) per classificar la població (els consums energètics) en tres subpoblacions, però ara les mostres que hem pres no són independents sinó <strong>aparellades</strong>: hem mesurat els consums energètics dels tres esports sobre els mateixos individus. Per tant no podem realitzar una ANOVA d’1 via per analitzar els resultats.</p>
<p>L’<strong>ANOVA de blocs</strong> (<strong>complets aleatoris</strong>, però ometrem aquests adjectius perquè és l’únic que veurem) generalitza el contrast de 2 mitjanes amb mostres aparellades a <span class="math inline">\(k\)</span> mitjanes amb mostres aparellades.</p>
<p>La situació general és la següent. Tenim una variable aleatòria <span class="math inline">\(X\)</span> i un factor de <span class="math inline">\(k\)</span> nivells, o <strong>tractaments</strong>, que classifica la població en <span class="math inline">\(k\)</span> subpoblacions (a les que, recordau, identificam amb els tractaments). Diguem <span class="math inline">\(\mu_i\)</span> a la mitjana de <span class="math inline">\(X\)</span> en els individus del nivell <span class="math inline">\(i\)</span>-èssim. Volem comparar aquestes mitjanes <span class="math inline">\(\mu_1\)</span>,…,<span class="math inline">\(\mu_k\)</span> i en concret decidir si són totes iguals o no. És a dir, el contrast és
<span class="math display">\[
\left\{
\begin{array}{l}
H_0 : \mu_{1} =\mu_{2} =\cdots =\mu_{k} \\
H_1 : \text{Hi ha } i,j \text{ tals que }  \mu_{i} \not=\mu_{j}
\end{array}
\right.
\]</span></p>
<p>En un <strong>experiment de disseny d’ANOVA de blocs</strong>:</p>
<ol style="list-style-type: decimal">
<li><p>Escollim una mostra aleatòria de <span class="math inline">\(b\)</span> <strong>blocs</strong>: conjunts de <span class="math inline">\(k\)</span> subjectes aparellats (per exemple, escollim <span class="math inline">\(b\)</span> subjectes i entenem cada bloc com a format per <span class="math inline">\(k\)</span> còpies del mateix subjecte), on fixau-vos que <span class="math inline">\(k\)</span> és el nombre de tractaments.</p></li>
<li><p>Dins cada bloc, assignam aleatòriament a cada subjecte un tractament, de manera que cada tractament s’empri exactament un cop dins cada bloc.</p></li>
</ol>
<p>Així, el disseny de l’Exemple <a href="mes-anova.html#exm:esports">1.1</a> és d’una ANOVA de blocs:</p>
<ul>
<li><p>La variable aleatòria és l’energia consumida (en Kcal) per una persona en recórrer un km</p></li>
<li><p>Els tractaments són els tres tipus de desplaçament</p></li>
<li><p>Prenem 8 persones de manera raonablement aleatòria i interpretam cada una com un bloc</p></li>
<li><p>Assignam a cada persona el tres tractaments en un ordre escollit a l’atzar per a cada un d’elles</p></li>
</ul>
<p>La filosofia del contrast serà similar a la de l’ANOVA d’1 via, comparant variabilitats.</p>
<p>En una ANOVA de blocs, les dades se solen representar en forma d’una taula com la següent
<span class="math display">\[
\begin{array}{c}
\hphantom{Bloc}\text{Tractament}\\
\begin{array}{ccccc}
\text{Bloc} &amp;\text{Tract. 1} &amp;\text{Tract. 2}&amp;\ldots &amp; \text{Tract. $k$}\\
\hline
 1 &amp; X_{11} &amp; X_{21} &amp; \ldots &amp; X_{k1} \\
 2 &amp; X_{12} &amp; X_{22} &amp; \ldots &amp; X_{k2} \\
 \vdots &amp; \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
 b &amp; X_{1b} &amp; X_{2b} &amp; \ldots &amp; X_{kb} \\
\hline
\end{array}
\end{array}
\]</span></p>
<p>on cada <span class="math inline">\(X_{ij}\)</span> és el valor del tractament <span class="math inline">\(i\)</span>-èsim en l’individu corresponent del bloc <span class="math inline">\(j\)</span>-èsim. Com en les taules emprades en l’ANOVA d’1 via, observau que no és la notació usual de les taules de dades, sinó la transposada: a <span class="math inline">\(X_{{i}{j}}\)</span>, <span class="math inline">\(i\)</span> hi indica la <strong>columna</strong>, el tractament, i <span class="math inline">\(j\)</span> hi indica la <strong>filera</strong>, és a dir, el bloc. D’aquesta manera, cada filera <span class="math inline">\((X_{1j},\ldots,X_{kj})\)</span> representa un bloc.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-12" class="example"><strong>Exemple 1.2  </strong></span>Tornant al nostre Exemple <a href="mes-anova.html#exm:esports">1.1</a> inicial, els blocs són els 8 individus (<span class="math inline">\(b=8\)</span>) i els tractaments, les diferents activitats (<span class="math inline">\(k=3\)</span>). Si</p>
<ul>
<li><span class="math inline">\(\mu_{1}\)</span> representa el nombre mitjà de Kca que es consumeixen corrent 1 km</li>
<li><span class="math inline">\(\mu_{2}\)</span> representa el nombre mitjà de Kca que es consumeixen caminant 1 km</li>
<li><span class="math inline">\(\mu_{3}\)</span> representa el nombre mitjà de Kca que es consumeixen pedalant 1 km</li>
</ul>
<p>el contrast que volem realitzar és
<span class="math display">\[
\left\{
\begin{array}{l}
H_0 : \mu_{1} = \mu_{2} = \mu_{3} \\
H_1 : \mu_{1} \neq \mu_{2}\text{ o } \mu_{1} \neq \mu_{3}\text{ o } \mu_{2} \neq \mu_{3}
\end{array}
\right.
\]</span></p>
</div>

<p>Per que les conclusions d’una ANOVA de blocs tenguin sentit cal que:</p>
<ul>
<li><p>Les <span class="math inline">\(k\cdot b\)</span> observacions constitueixin mostres aleatòries, cadascuna de mida 1, de les <span class="math inline">\(k\cdot b\)</span> poblacions definides per les parelles (tractament,bloc)</p></li>
<li><p>Aquestes <span class="math inline">\(k\cdot b\)</span> poblacions són totes normals, cada una amb mitjana <span class="math inline">\(\mu_{ij}\)</span>, on <span class="math inline">\(i\)</span> indica el tractament i <span class="math inline">\(j\)</span> indica el bloc, i totes amb la mateixa variància <span class="math inline">\(\sigma^2\)</span></p></li>
<li><p>No hi ha <strong>interacció</strong> entre els blocs i els tractaments. Això significa que l’efecte dels blocs i els tractaments és <strong>additiu</strong>:
la diferència entre les mitjanes poblacionals de cada parella concreta de tractaments és la mateixa a cada bloc
<span class="math display">\[
\mu_{i_1j_1}-\mu_{i_2j_1}=\mu_{i_1j_2}-\mu_{i_2j_2}
\]</span>
on aquí <span class="math inline">\(j_1\)</span> i <span class="math inline">\(j_2\)</span> no indiquen només blocs de la nostra mostra, sinó possibles blocs que haguéssim pogut escollir.</p>
<p>Per exemple, que no hi hagi interacció entre els blocs i els tractaments a l’Exemple <a href="mes-anova.html#exm:esports">1.1</a> significa que:</p>
<ul>
<li>La diferència entre el consum energètic mitjà en córrer i en caminar és la mateixa a cada individu (del món mundial, no de la mostra)</li>
<li>La diferència entre el consum energètic mitjà en córrer i en pedalar és la mateixa a cada individu</li>
<li>La diferència entre el consum energètic mitjà en caminar i en pedalar és la mateixa a cada individu</li>
</ul></li>
</ul>
<p>En canvi, hi hauria interacció si, per exemple, la diferència entre el consum energètic mitjà en córrer i en caminar depengués de l’individu: si en uns la diferència fos més gran que en d’altres.</p>
<p>Amb un sol valor per cada parell (tractament,bloc), cap d’aquestes condicions necessàries per poder realitzar una ANOVA de blocs no es pot contrastar i per tant l’experimentador ha de decidir si se satisfan o no segons la seva experiència</p>

<div class="rmdnote">
<p>Què significa això de la interacció entre dues variables?</p>
<p>Imaginau que podem administrar dos analgèsics, A i B, a dones i homes, i mesuram el temps que triguen en fer efecte. Diguem</p>
<ul>
<li><span class="math inline">\(\mu_{AD}\)</span>: temps mitjà que triga en fer efecte l’analgèsic A sobre les dones</li>
<li><span class="math inline">\(\mu_{BD}\)</span>: temps mitjà que triga en fer efecte l’analgèsic B sobre les dones</li>
<li><span class="math inline">\(\mu_{AH}\)</span>: temps mitjà que triga en fer efecte l’analgèsic A sobre els homes</li>
<li><span class="math inline">\(\mu_{BH}\)</span>: temps mitjà que triga en fer efecte l’analgèsic B sobre els homes</li>
</ul>
<p>Aleshores:</p>
<ul>
<li><p>No hi ha interacció entre els analgèsics i el sexe si la diferència en el temps mitjà en fer efecte A i B és la mateixa en les dones que en els homes:
<span class="math display">\[
\mu_{AD}-\mu_{BD}=  \mu_{AH}-\mu_{BH}
\]</span></p></li>
<li><p>En canvi, sí que hi ha interacció entre els analgèsics i el sexe quan aquestes dues diferències són diferents, la qual cosa significaria que la diferència d’efectivitat entre els dos analgèsics no és la mateixa en els homes que en les dones:
<span class="math display">\[
\mu_{AD}-\mu_{BD}\neq  \mu_{AH}-\mu_{BH}
\]</span></p></li>
</ul>
Fixau-vos que això no és exactament equivalent al fet que un analgèsic sigui més efectiu en un sexe que en l’altre, per exemple més en les dones que en els homes: si l’altre analgèsic també és més efectiu en les dones que en els homes, pot ser que la diferència entre les mitjanes se mantengui i no hi hagi interacció.
</div>

<p>Recordarem algunes notacions, i n’introduïm algunes altres. Pel que fa a la població:</p>
<ul>
<li>Direm <span class="math inline">\(\mu_i\)</span> a la mitjana de la variable d’interès sobre la població definida pel tractament <span class="math inline">\(i\)</span>-èssim</li>
<li>Direm <span class="math inline">\(\mu\)</span> a la mitjana de la variable d’interès sobre el total de la població, sense distingir tractaments</li>
<li>Direm <span class="math inline">\(\mu_{\bullet j}\)</span> a la mitjana de la variable d’interès sobre el bloc <span class="math inline">\(j\)</span>-èssim</li>
</ul>
<p>Pel que fa a la nostra mostra:</p>
<ul>
<li><p><span class="math inline">\(\overline{X}_{i}\)</span> és la mitjana mostral de la mostra del tractament <span class="math inline">\(i\)</span>-èsim
<span class="math display">\[
\overline{X}_{i}=\dfrac{\sum_{j=1}^b X_{ij}}{b}
\]</span></p></li>
<li><p><span class="math inline">\(\overline{X}_{\bullet j}\)</span> és la mitjana mostral de les mesures preses sobre el bloc <span class="math inline">\(j\)</span>-èsim
<span class="math display">\[
\overline{X}_{\bullet j}=\dfrac{\sum_{i=1}^k X_{ij}}{k}
\]</span></p></li>
<li><p><span class="math inline">\(\overline{X}\)</span> és la mitjana mostral de tota la mostra
<span class="math display">\[
\overline{X}=\dfrac{\sum_{i=1}^k\sum_{j=1}^b X_{ij}}{k\cdot b}
\]</span></p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-14" class="example"><strong>Exemple 1.3  </strong></span>Tornem a l’Exemple <a href="mes-anova.html#exm:esports">1.1</a>. Recordem que les dades eren</p>
</div>

<p><span class="math display">\[
\begin{array}{c}
\hphantom{Individu}\text{Tractament}\\
\begin{array}{c|ccc}
\text{Individu} &amp;\text{1 (corrent)} &amp;\text{2 (caminant)}&amp;\text{3 (pedalant)}\\
\hline
1&amp;1.4&amp;1.1&amp;0.7\\
2&amp;1.5&amp;1.2&amp;0.8\\
3&amp;1.8&amp;1.3&amp;0.7\\
4&amp;1.7&amp;1.3&amp;0.8\\
5&amp;1.6&amp;0.7&amp;0.1\\
6&amp;1.5&amp;1.2&amp;0.7\\
7&amp;1.7&amp;1.1&amp;0.4\\
8&amp;2.0&amp;1.3&amp;0.6\\ 
\end{array}
\end{array}
\]</span></p>
<p>Per tant les mitjanes serien, amb aquestes notacions</p>
<p><span class="math display">\[
\begin{array}{c}
\text{Tractament}\\
\begin{array}{c|ccc|c}
\text{Individu} &amp;\text{1 (corrent)} &amp;\text{2 (caminant)}&amp;\text{3 (pedalant)} &amp; \text{Mitjanes}\\
\hline
1&amp;1.4&amp;1.1&amp;0.7 &amp; \overline{X}_{\bullet1}\\
2&amp;1.5&amp;1.2&amp;0.8 &amp; \overline{X}_{\bullet2}\\
3&amp;1.8&amp;1.3&amp;0.7 &amp; \overline{X}_{\bullet3}\\
4&amp;1.7&amp;1.3&amp;0.8 &amp; \overline{X}_{\bullet4}\\
5&amp;1.6&amp;0.7&amp;0.1 &amp; \overline{X}_{\bullet5}\\
6&amp;1.5&amp;1.2&amp;0.7 &amp; \overline{X}_{\bullet6}\\
7&amp;1.7&amp;1.1&amp;0.4 &amp; \overline{X}_{\bullet7}\\
8&amp;2.0&amp;1.3&amp;0.6 &amp; \overline{X}_{\bullet8}\\ \hline
\text{Mitjanes} &amp; \overline{X}_{1} &amp; \overline{X}_{2} &amp; \overline{X}_{3} &amp; \overline{X}
\end{array}
\end{array}
\]</span></p>
<p>Anem a calcular-les. Emmagatzemarem les dades en un <em>dataframe</em> <code>Dades</code> de tres variables:</p>
<ul>
<li><strong>kilocal</strong>: les Kcal/Km consumides</li>
<li><strong>blocs</strong>: l’individu</li>
<li><strong>tracts</strong>: l’activitat</li>
</ul>
<p>Per poder després fer l’ANOVA, aquests dos darrers han de ser factors. Com que entrarem les dades de la taula per fileres:</p>
<ul>
<li>el factor <strong>tracts</strong> ha d’estar format per 8 còpies del vector (1,2,3), on 1 representa córrer, 2, caminar i 3, pedalar</li>
<li>el factor <strong>blocs</strong> ha de tenir la forma (1,1,1,2,2,2,3,3,3,…)</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">kilocal=<span class="kw">c</span>(<span class="fl">1.4</span>,<span class="fl">1.1</span>,<span class="fl">0.7</span>,<span class="fl">1.5</span>,<span class="fl">1.2</span>,<span class="fl">0.8</span>,<span class="fl">1.8</span>,<span class="fl">1.3</span>,<span class="fl">0.7</span>,<span class="fl">1.7</span>,<span class="fl">1.3</span>,<span class="fl">0.8</span>,
          <span class="fl">1.6</span>,<span class="fl">0.7</span>,<span class="fl">0.1</span>,<span class="fl">1.5</span>,<span class="fl">1.2</span>,<span class="fl">0.7</span>,<span class="fl">1.7</span>,<span class="fl">1.1</span>,<span class="fl">0.4</span>,<span class="fl">2.0</span>,<span class="fl">1.3</span>,<span class="fl">0.6</span>)
blocs=<span class="kw">as.factor</span>(<span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">8</span>,<span class="dt">each=</span><span class="dv">3</span>))
blocs</code></pre>
<pre><code>##  [1] 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8
## Levels: 1 2 3 4 5 6 7 8</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">tracts=<span class="kw">as.factor</span>(<span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>,<span class="dt">times=</span><span class="dv">8</span>))
tracts</code></pre>
<pre><code>##  [1] 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3
## Levels: 1 2 3</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">Dades=<span class="kw">data.frame</span>(kilocal,tracts,blocs)
<span class="kw">str</span>(Dades)</code></pre>
<pre><code>## &#39;data.frame&#39;:    24 obs. of  3 variables:
##  $ kilocal: num  1.4 1.1 0.7 1.5 1.2 0.8 1.8 1.3 0.7 1.7 ...
##  $ tracts : Factor w/ 3 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;: 1 2 3 1 2 3 1 2 3 1 ...
##  $ blocs  : Factor w/ 8 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 1 1 2 2 2 3 3 3 4 ...</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(Dades)</code></pre>
<pre><code>##   kilocal tracts blocs
## 1     1.4      1     1
## 2     1.1      2     1
## 3     0.7      3     1
## 4     1.5      1     2
## 5     1.2      2     2
## 6     0.8      3     2</code></pre>
<ul>
<li>Calculem les mitjanes mostrals dels tractaments, <span class="math inline">\(\overline{X}_i\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">mean.tracts=<span class="kw">aggregate</span>(kilocal<span class="op">~</span>tracts,<span class="dt">data=</span>Dades,mean)
mean.tracts</code></pre>
<pre><code>##   tracts kilocal
## 1      1    1.65
## 2      2    1.15
## 3      3    0.60</code></pre>
<ul>
<li>Calculem les mitjanes mostrals dels blocs, <span class="math inline">\(\overline{X}_{\bullet j}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">mean.blocs=<span class="kw">aggregate</span>(kilocal<span class="op">~</span>blocs,<span class="dt">data=</span>Dades,mean)
mean.blocs</code></pre>
<pre><code>##   blocs  kilocal
## 1     1 1.066667
## 2     2 1.166667
## 3     3 1.266667
## 4     4 1.266667
## 5     5 0.800000
## 6     6 1.133333
## 7     7 1.066667
## 8     8 1.300000</code></pre>
<ul>
<li>Calculem la mitjana mostral global <span class="math inline">\(\overline{X}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">mean.tot=<span class="kw">mean</span>(Dades<span class="op">$</span>kilocal)
mean.tot</code></pre>
<pre><code>## [1] 1.133333</code></pre>
<p>A l’ANOVA de blocs s’hi té la identitat següent:</p>

<div class="theorem">
<p><span id="thm:SSblocs" class="theorem"><strong>Teorema 1.1  (Identitat de les sumes de quadrats)  </strong></span><span class="math display">\[
SS_{Total}=SS_{Tr}+SS_{Blocs}+SS_E
\]</span>
on</p>
<ul>
<li><p><span class="math inline">\(SS_{Total}=\displaystyle\sum\limits_{i=1}^k\sum\limits_{j=1}^b (X_{ij}- \overline{X})^2\)</span>; és la <strong>Suma Total de Quadrats</strong></p></li>
<li><p><span class="math inline">\(SS_{Tr}=\displaystyle b\sum\limits_{i=1}^k (\overline{X}_{i}-\overline{X})^2\)</span>; és la <strong>Suma de Quadrats dels Tractaments</strong></p></li>
<li><p><span class="math inline">\(SS_{Blocs}=\displaystyle k\sum\limits_{j=1}^b (\overline{X}_{\bullet j}-\overline{X})^2\)</span>; és la <strong>Suma de Quadrats dels Blocs</strong></p></li>
<li><p><span class="math inline">\(SS_E=\displaystyle\sum\limits_{i=1}^k\sum\limits_{j=1}^b (X_{ij} - \overline{X}_{i}- \overline{X}_{\bullet j}+\overline{X})^2\)</span>; és la <strong>Suma de Quadrats dels Residus</strong> o <strong>dels Errors</strong></p>
</div></li>
</ul>
<p>En aquesta identitat</p>
<ul>
<li><p><span class="math inline">\(SS_{Total}\)</span> representa la variabilitat total de les dades: és el numerador de la variància de la mostra total</p></li>
<li><p><span class="math inline">\(SS_{Tr}\)</span> representa la variabilitat de les mitjanes dels tractaments: és <span class="math inline">\(b\)</span> vegades el numerador de la variància de <span class="math inline">\((\overline{X}_1,\overline{X}_2,\ldots,\overline{X}_k)\)</span></p></li>
<li><p><span class="math inline">\(SS_{Tr}\)</span> representa la variabilitat de les mitjanes dels blocs: és <span class="math inline">\(k\)</span> vegades el numerador de la variància de <span class="math inline">\((\overline{X}_{\bullet 1},\overline{X}_{\bullet 2},\ldots,\overline{X}_{\bullet b})\)</span></p></li>
<li><p><span class="math inline">\(SS_E\)</span> representa la “resta de la variabilitat”</p></li>
</ul>

<div class="rmdnote">
<p>Fixau-vos que podeu escriure
<span class="math display">\[
X_{ij}=\mu+ (\mu_{i}-\mu) +(\mu_{\bullet j}-\mu) + (X_{ij}-\mu_{i}-\mu_{\bullet j}+\mu)
\]</span>
Aquesta igualtat diu que la diferència entre cada <span class="math inline">\(X_{ij}\)</span> i la mitjana global <span class="math inline">\(\mu\)</span> és la suma de tres contribucions:</p>
<ul>
<li><p>La diferència entre la mitjana del tractament <span class="math inline">\(i\)</span> i la mitjana global; aquesta és la part de la diferència entre <span class="math inline">\(X_{ij}\)</span> i <span class="math inline">\(\mu\)</span> deguda a que <span class="math inline">\(X_{ij}\)</span> és una mesura sota el tractament <span class="math inline">\(i\)</span>, i per tant representa la contribució d’aquest tractament a <span class="math inline">\(X_{ij}\)</span></p></li>
<li><p>La diferència entre la mitjana del bloc <span class="math inline">\(j\)</span> i la mitjana global; aquesta és la part de la diferència entre <span class="math inline">\(X_{ij}\)</span> i <span class="math inline">\(\mu\)</span> deguda a que <span class="math inline">\(X_{ij}\)</span> és una mesura sobre el bloc <span class="math inline">\(j\)</span>, i per tant representa la contribució a <span class="math inline">\(X_{ij}\)</span> del fet d’haver estat mesurat sobre aquest bloc</p></li>
<li><p><span class="math inline">\(X_{ij}-\mu_{i}-\mu_{\bullet j}+\mu\)</span>, que és “la part de la diferència entre <span class="math inline">\(X_{ij}\)</span> i <span class="math inline">\(\mu\)</span> que no explica ni el tractament ni el bloc”; en diem el <strong>residu</strong>, o l’<strong>error</strong></p></li>
</ul>
<p>Doncs bé,</p>
<ul>
<li><p><span class="math inline">\(SS_{Total}\)</span> és la suma dels quadrats de les estimacions de les diferències <span class="math inline">\(X_{ij}-\mu\)</span></p></li>
<li><p><span class="math inline">\(SS_{Tr}\)</span> és la suma dels quadrats de les estimacions de les diferències <span class="math inline">\(\mu_{i}-\mu\)</span></p></li>
<li><p><span class="math inline">\(SS_{Tr}\)</span> és la suma dels quadrats de les estimacions de les diferències <span class="math inline">\(\mu_{\bullet j}-\mu\)</span></p></li>
<li><p><span class="math inline">\(SS_E\)</span> és la suma dels quadrats de les estimacions del residus</p></li>
</ul>
</div>

<p>Per tant
<span class="math display">\[
SS_{Total}=SS_{Tr}+SS_{Blocs}+SS_E
\]</span>
bàsicament diu que en una ANOVA de blocs</p>
<blockquote>
<p>la variabilitat total descompon en la suma de la variabilitat de les mitjanes dels tractaments més la variabilitat de les mitjanes dels blocs més la variabilitat “residual”.</p>
</blockquote>

<div class="example">
<p><span id="exm:unnamed-chunk-20" class="example"><strong>Exemple 1.4  </strong></span>Tornem a l’Exemple <a href="mes-anova.html#exm:esports">1.1</a></p>
</div>

<p>Recordem les dades que ja tenim</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(Dades)</code></pre>
<pre><code>## &#39;data.frame&#39;:    24 obs. of  3 variables:
##  $ kilocal: num  1.4 1.1 0.7 1.5 1.2 0.8 1.8 1.3 0.7 1.7 ...
##  $ tracts : Factor w/ 3 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;: 1 2 3 1 2 3 1 2 3 1 ...
##  $ blocs  : Factor w/ 8 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 1 1 1 2 2 2 3 3 3 4 ...</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">k=<span class="dv">3</span>  <span class="co">#Nombre de tractaments</span>
b=<span class="dv">8</span>  <span class="co">#Nombre de blocs</span>
mean.tracts  <span class="co">#Mitjanes de tractaments</span></code></pre>
<pre><code>##   tracts kilocal
## 1      1    1.65
## 2      2    1.15
## 3      3    0.60</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">mean.blocs  <span class="co">#Mitjanes de blocs</span></code></pre>
<pre><code>##   blocs  kilocal
## 1     1 1.066667
## 2     2 1.166667
## 3     3 1.266667
## 4     4 1.266667
## 5     5 0.800000
## 6     6 1.133333
## 7     7 1.066667
## 8     8 1.300000</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">mean.tot  <span class="co"># Mitjana global</span></code></pre>
<pre><code>## [1] 1.133333</code></pre>
<ul>
<li>Calculem la suma total de quadrats
<span class="math display">\[
SS_{Total}=\sum\limits_{i=1}^k\sum\limits_{j=1}^b (X_{ij}- \overline{X})^2
\]</span></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SS.Tot=<span class="kw">sum</span>((kilocal<span class="op">-</span>mean.tot)<span class="op">^</span><span class="dv">2</span>)
SS.Tot</code></pre>
<pre><code>## [1] 5.353333</code></pre>
<ul>
<li>Calculem la suma de quadrats dels tractaments
<span class="math display">\[
SS_{Tr}=b\sum\limits_{i=1}^k (\overline{X}_{i}-\overline{X})^2
\]</span>
Fixau-vos que el vector <span class="math inline">\((\overline{X}_{1},\overline{X}_{2},\overline{X}_{3})\)</span> és la variable <strong>kilocal</strong> de <code>mean.tracts</code>.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SS.Tr=b<span class="op">*</span><span class="kw">sum</span>((mean.tracts<span class="op">$</span>kilocal<span class="op">-</span>mean.tot)<span class="op">^</span><span class="dv">2</span>)
SS.Tr</code></pre>
<pre><code>## [1] 4.413333</code></pre>
<ul>
<li>Calculem la suma de quadrats dels blocs
<span class="math display">\[
SS_{Blocs}=k\sum\limits_{j=1}^b (\overline{X}_{\bullet j}-\overline{X})^2
\]</span>
Fixau-vos que el vector <span class="math inline">\((\overline{X}_{\bullet 1},\ldots,\overline{X}_{\bullet b})\)</span> és la variable <strong>kilocal</strong> de <code>mean.blocs</code>.</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SS.Bl=k<span class="op">*</span><span class="kw">sum</span>((mean.blocs<span class="op">$</span>kilocal<span class="op">-</span>mean.tot)<span class="op">^</span><span class="dv">2</span>)
SS.Bl</code></pre>
<pre><code>## [1] 0.5533333</code></pre>
<ul>
<li><p>Calculem la suma de quadrats dels residus
<span class="math display">\[
SS_E=\sum\limits_{i=1}^k\sum\limits_{j=1}^b (X_{ij} - \overline{X}_{i}- \overline{X}_{\bullet j}+\overline{X})^2
\]</span>
Per calcular aquesta suma, actuarem com al càlcul de la <span class="math inline">\(SS_E\)</span> de l’ANOVA d’1 via, tenint en compte que</p>
<ul>
<li><p>Les entrades de <code>Dades$kilocal</code> que difereixen en un múltiple de 3 són del mateix tractament: per exemple, la 1a, la 4a, la 7a etc. corresponen al tractament 1 (córrer). Si a <code>Dades$kilocal</code> li restam el vector de les mitjanes del tractaments, <code>mean.tracts$kilocal</code>, en realitat estam dient a R que li resti 8 còpies consecutives d’aquest vector, i per tant a cada entrada de <code>Dades$kilocal</code> li restam la mitjana del seu tractament.</p></li>
<li><p>Cada grup de 3 entrades consecutives de <code>Dades$kilocal</code> corresponen a un bloc: les tres primeres al bloc 1, les tres següents al bloc 2 etc. Per tant, per restar a cada entrada de <code>Dades$kilocal</code> la mitjana del bloc corresponent, li hem de restar <code>rep(mean.blocs$kilocal,each=3)</code>.</p></li>
</ul></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SSE=<span class="kw">sum</span>((Dades<span class="op">$</span>kilocal<span class="op">-</span>mean.tracts<span class="op">$</span>kilocal<span class="op">-</span><span class="kw">rep</span>(mean.blocs<span class="op">$</span>kilocal,<span class="dt">each=</span><span class="dv">3</span>)<span class="op">+</span>mean.tot)<span class="op">^</span><span class="dv">2</span>)
SSE</code></pre>
<pre><code>## [1] 0.3866667</code></pre>
<p>Comprovem la identitat de les sumes de quadrats:</p>
<pre class="sourceCode r"><code class="sourceCode r">SS.Tot</code></pre>
<pre><code>## [1] 5.353333</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">SS.Tr<span class="op">+</span>SS.Bl<span class="op">+</span>SSE</code></pre>
<pre><code>## [1] 5.353333</code></pre>
<p>A partir d’aquí, tot funciona com a l’ANOVA d’1 via. Per realitzar el contrast
<span class="math display">\[
\left\{
\begin{array}{l}
H_0 :  \mu_{1}=\cdots =\mu_{k} \\
H_1 : \text{Hi ha } i,j=1,\ldots ,k \text{ tals que }  \mu_{i}\neq \mu_{j}
\end{array}
\right.
\]</span>
emprarem els estadístics següents:</p>
<ul>
<li><p><strong>Quadrat mitjà dels tractaments</strong>:
<span class="math display">\[
MS_{Tr}=\dfrac{SS_{Tr}}{k-1}
\]</span></p></li>
<li><p><strong>Quadrat mitjà dels errors</strong>:
<span class="math display">\[
MS_E = \dfrac{SS_E}{(b-1) (k-1)}
\]</span>
Fixau-vos que el denominador és diferent que al <span class="math inline">\(MS_E\)</span> de l’ANOVA d’1 via</p></li>
<li><p>A més, R calcula el <strong>Quadrat mitjà dels blocs</strong>, que nosaltres no farem servir però que donam per si de cas:
<span class="math display">\[
MS_{Blocs}=\dfrac{SS_{Blocs}}{b-1}
\]</span></p></li>
</ul>
<p>Si se satisfan les condicions necessàries que hem esmentat per que l’ANOVA es pugui realitzar, es té que
<span class="math display">\[
\begin{array}{l}
E(MS_{Tr})=\sigma^2 + \dfrac{b}{k-1}\sum\limits_{i=1}^k (\mu_{i}-\mu)^2 \\
E(MS_E)=\sigma^2
\end{array}
\]</span></p>

<div class="rmdnote">
I <span class="math inline">\(MS_E\)</span> torna a estimar la variància comuna de totes les poblacions definides per les parelles (tractament,bloc).
</div>

<p>Aleshores, com a l’ANOVA d’1 via, si <span class="math inline">\(H_0:\mu_{1}=\cdots =\mu_{k}(=\mu)\)</span> és certa,
<span class="math display">\[
\sum\limits_{i=1}^k (\mu_{i}-\mu)^2 = 0,
\]</span>
mentre que si <span class="math inline">\(H_0\)</span> no és certa
<span class="math display">\[
\sum\limits_{i=1}^k (\mu_{i}-\mu)^2 &gt; 0
\]</span></p>
<p>Aleshores prendrem com a <strong>estadístic de contrast</strong> el quocient
<span class="math display">\[
F=\frac{MS_{Tr}}{MS_E}
\]</span>
Si <span class="math inline">\(H_0\)</span> és certa:</p>
<ul>
<li>La seva distribució és de tipus F de Fisher amb <span class="math inline">\(k-1\)</span> i <span class="math inline">\((k-1)(b-1)\)</span> graus de llibertat, <span class="math inline">\(F_{k-1,(k-1)(b-1)}\)</span></li>
</ul>

<div class="rmdimportant">
En general, els graus de llibertat de l’estadístic F d’una ANOVA, sigui del tipus que sigui, són els denominadors emprats en les definicions dels quadrats mitjans del numerador i el denominador.
</div>

<ul>
<li>El seu valor és proper a 1</li>
</ul>
<p>I per tant rebutjarem la hipòtesi nul·la si el valor <span class="math inline">\(F_0\)</span> de <span class="math inline">\(F\)</span> sobre la nostra mostra és prou més gran que 1, la qual cosa decidirem comparant el p-valor <span class="math inline">\(P(F_{k-1,(k-1)(b-1)}\geqslant F_0)\)</span> amb el nivell de significació <span class="math inline">\(\alpha\)</span>.</p>
<p>En resum, per realitzar una ANOVA de blocs a partir d’una mostra:</p>
<ul>
<li><p>Calculam <span class="math inline">\(SS_{Tr},SS_E\)</span></p></li>
<li><p>Calculam <span class="math inline">\(MS_{Tr},MS_E\)</span></p></li>
<li><p>Calculam el valor <span class="math inline">\(F_0\)</span> de l’estadístic de contrast
<span class="math display">\[
F=\frac{MS_{Tr}}{MS_E}
\]</span></p></li>
<li><p>Calculam el p-valor
<span class="math display">\[
P(F_{k-1,(k-1)(b-1)}\geqslant F_0)
\]</span></p></li>
<li><p>Si aquest p-valor és més petit que el nivell de significació <span class="math inline">\(\alpha\)</span>, rebutjam <span class="math inline">\(H_0\)</span> i concloem que no totes les mitjanes són iguals. En cas contrari, acceptam que totes les mitjanes són iguals.</p></li>
</ul>
<p>Totes aquestes dades se solen recollir en la taula següent:
<span class="math display">\[
\begin{array}{llllll}
\hline
\text{Origen de la}&amp;\text{Graus de}&amp;\text{Sumes de}&amp;\text{Quadrats} &amp; \text{Estadístic de}&amp;\text{p-valor}\\[-0.5ex]
\text{variabilitat}&amp;\text{llibertat}&amp;\text{quadrats}&amp;\text{mitjans}&amp;\text{contrast} &amp; \\\hline
\text{Tractaments} &amp; k-1 &amp; SS_{Tr}&amp; MS_{Tr}  &amp; F &amp; \text{p-valor} \\
\text{Blocs} &amp; b-1 &amp; SS_{Blocs} &amp; MS_{Blocs} &amp; \\ 
\text{Residus} &amp; (k-1)(b-1) &amp; SS_E &amp; MS_E &amp; \\\hline
\end{array}
\]</span></p>

<div class="example">
<p><span id="exm:unnamed-chunk-29" class="example"><strong>Exemple 1.5  </strong></span>Tornem al nostre Exemple <a href="mes-anova.html#exm:esports">1.1</a>. Ja hem calculat:</p>
</div>

<p><span class="math display">\[
\begin{array}{cccccc}
k &amp; b &amp; SS_{Total} &amp; SS_{Tr} &amp; SS_{Blocs} &amp; SS_E\\ \hline
3 &amp; 8 &amp; 5.3533  &amp; 4.4133 &amp; 0.5533  &amp; 0.3867
\end{array}
\]</span>
Aleshores:</p>
<ul>
<li><p><span class="math inline">\(MS_{Tr}=\dfrac{SS_{Tr}}{k-1}=2.2066\)</span></p></li>
<li><p><span class="math inline">\(MS_{Blocs}=\dfrac{SS_{Blocs}}{b-1}=0.079\)</span></p></li>
<li><p><span class="math inline">\(MS_E = \dfrac{SS_E}{(b-1) (k-1)}=0.0276\)</span></p></li>
<li><p><span class="math inline">\(F=\dfrac{MS_{Tr}}{MS_E}=79.949\)</span></p></li>
<li><p>p-valor: <span class="math inline">\(P(F_{2,14}\geqslant 79.949)=2\cdot 10^{-8}\)</span></p></li>
<li><p><em>Conclusió</em>: Hem obtingut evidència estadísticament significativa que no és veritat que les tres activitats tenguin el mateix consum energètic mitjà per km (ANOVA de blocs, p-valor 2·10<sup>-8</sup>)</p></li>
</ul>
<p>La taula ANOVA d’aquest exemple és</p>
<p><span class="math display">\[
\begin{array}{llllll}
\hline
\text{Origen de la}&amp;\text{Graus de}&amp;\text{Sumes de}&amp;\text{Quadrats} &amp; \text{Estadístic de}&amp;\text{p-valor}\\[-0.5ex]
\text{variabilitat}&amp;\text{llibertat}&amp;\text{quadrats}&amp;\text{mitjans}&amp;\text{contrast} &amp; \\\hline
\text{Tractaments} &amp; 2 &amp;  4.4133&amp;2.2067&amp;79.949 &amp; 2\cdot 10^{-8} \\
\text{Blocs} &amp; 7 &amp; 0.5533&amp;0.079&amp; &amp; \\ 
\text{Residus} &amp; 14 &amp; 0.3867&amp;0.0276&amp; &amp; \\\hline
\end{array}
\]</span></p>
</div>
<div id="amb-r" class="section level3">
<h3><span class="header-section-number">1.1.2</span> Amb R</h3>
<p>L’ANOVA de blocs s’efectua amb R aplicant <code>summary(aov( ))</code> a la fórmula que separa la variable numèrica per la <strong>suma dels factors que representen els tractaments i els blocs</strong>. Així, l’ANOVA de blocs de l’Exemple <a href="mes-anova.html#exm:esports">1.1</a> es fa amb</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(Dades<span class="op">$</span>kilocal<span class="op">~</span>Dades<span class="op">$</span>tracts<span class="op">+</span>Dades<span class="op">$</span>blocs))</code></pre>
<pre><code>##              Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## Dades$tracts  2  4.413  2.2067  79.897 2.2e-08 ***
## Dades$blocs   7  0.553  0.0790   2.862  0.0446 *  
## Residuals    14  0.387  0.0276                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>o, equivalentment, amb</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(kilocal<span class="op">~</span>tracts<span class="op">+</span>blocs, <span class="dt">data=</span>Dades))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## tracts       2  4.413  2.2067  79.897 2.2e-08 ***
## blocs        7  0.553  0.0790   2.862  0.0446 *  
## Residuals   14  0.387  0.0276                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Obtenim la taula d’abans (llevat d’una petita diferència en la <span class="math inline">\(F\)</span> deguda a que als càlculs a mà anàvem arrodonint pel camí) amb dues entrades més: l’estadístic de contrast i el p-valor de la filera <code>blocs</code>, que corresponen al contrast sobre hi ha diferència o no entre les mitjanes dels blocs (en aquest exemple, els consums mitjans energètics per km dels individus de la mostra en desplaçar-se de qualsevol de les tres maneres).</p>
</div>
<div id="comparacions-posteriors-per-parelles" class="section level3">
<h3><span class="header-section-number">1.1.3</span> Comparacions posteriors per parelles</h3>
<p>Com en el cas d’1 via, si rebutjam la hipòtesi nul·la, podem demanar-nos quins són els tractaments que tenen mitjanes diferents.
Ho podem respondre fent un test t per a cada parella de tractaments <strong>emprant mostres aparellades</strong> i aplicant un ajust del p-valor (Bonferroni, Holm…). No donarem els detalls de les fórmules, simplement heu de saber que amb R es fa com a l’ANOVA d’1 via: amb la funció <code>pairwise.t.test</code>, però ara indicant-hi que <code>paired=TRUE</code>.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-32" class="example"><strong>Exemple 1.6  </strong></span>A l’experiment de l’Exemple <a href="mes-anova.html#exm:esports">1.1</a> hem arribat a la conclusió que no totes les mitjanes són iguals.
Emprem un contrast posterior per parelles amb l’ajust de Bonferroni per mirar quines són diferents.</p>
</div>

<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pairwise.t.test</span>(Dades<span class="op">$</span>kilocal, Dades<span class="op">$</span>tracts, <span class="dt">paired=</span><span class="ot">TRUE</span>, <span class="dt">p.adjust.method=</span><span class="st">&quot;bonferroni&quot;</span>)</code></pre>
<pre><code>## 
##  Pairwise comparisons using paired t tests 
## 
## data:  Dades$kilocal and Dades$tracts 
## 
##   1       2      
## 2 0.00108 -      
## 3 0.00011 1.1e-05
## 
## P value adjustment method: bonferroni</code></pre>
<p><em>Conclusió</em>: Hem obtingut evidència estadísticament significativa que les tres activitats tenen diferent consum energètic mitjà per km (ANOVA de blocs, test posterior de Bonferroni, p-valors ajustats inferiors a 0.0011)</p>
</div>
<div id="contrast-no-parametric" class="section level3">
<h3><span class="header-section-number">1.1.4</span> Contrast no paramètric</h3>
<p>Si en un experiment amb disseny d’ANOVA de blocs no podem aplicar l’ANOVA perquè sospitem que no se satisfan les condicions necessàries, <strong>cal emprar un test no paramètric</strong>. El més popular és el <strong>test de Friedman</strong>, que generalitza el test de Wilcoxon a més de 2 mostres. En R està implementat en la funció <code>friedman.test</code> que s’aplica a la mateixa fórmula que <code>summary(aov( ))</code> excepte que cal substituir-hi la suma “+” per una barra vertical “|”. Per exemple:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">friedman.test</span>(kilocal<span class="op">~</span>tracts<span class="op">|</span>blocs,<span class="dt">data=</span>Dades)</code></pre>
<pre><code>## 
##  Friedman rank sum test
## 
## data:  kilocal and tracts and blocs
## Friedman chi-squared = 16, df = 2, p-value = 0.0003355</code></pre>
<p>La conclusió és la mateixa que abans: No tots els consums energètics mitjans són iguals (test de Friedman, p-valor 0.0003).</p>
<p>Si ara volem realitzar els tests posteriors per parelles, el més adient és emprar en tots ells el test de Wilcoxon, amb la funció <code>pairwise.wilcox.test</code> que ja empràvem a l’ANOVA d’1 via, però ara amb <code>paired=TRUE</code>:</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pairwise.wilcox.test</span>(Dades<span class="op">$</span>kilocal, Dades<span class="op">$</span>tracts, <span class="dt">paired =</span><span class="ot">TRUE</span>)</code></pre>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon signed rank test 
## 
## data:  Dades$kilocal and Dades$tracts 
## 
##   1     2    
## 2 0.042 -    
## 3 0.042 0.042
## 
## P value adjustment method: holm</code></pre>
<p>Obtenim evidència estadísticament significativa que les tres activitats tenen consums energètics mitjans diferents (test de Friedman, test posterior per parelles de Wilcoxon amb ajust de Holm, p-valors ajustats 0.042).</p>
</div>
</div>
<div id="anova-de-2-vies" class="section level2">
<h2><span class="header-section-number">1.2</span> ANOVA de 2 vies</h2>
<p>Amb l’ANOVA d’1 via comparàvem les mitjanes de més de 2 subpoblacions definides pels nivells d’un únic factor. Ara ens interessa el cas en què aquestes subpoblacions estan definides combinant els nivells de més d’un factor. Es diu en aquest cas que el disseny de l’experiment és d’<strong>ANOVA factorial</strong>. Nosaltres aquí considerarem només el cas més senzill, quan s’empren només 2 factors (2 vies). A més, per simplificar, només estudiarem el cas en què totes les mostres de cada combinació de nivells d’un factor i de l’altre tenen la mateixa mida.</p>
<p>Per tant, en un experiment amb <strong>disseny d’ANOVA de 2 vies</strong>:</p>
<ul>
<li><p>Tenim una variable aleatòria <span class="math inline">\(X\)</span></p></li>
<li><p>Classificam la població segons les combinacions dels nivells de dos factors</p></li>
<li><p>Prenem una m.a.s. de cada combinació de nivells, independents i totes de la mateixa mida, i hi mesuram la variable <span class="math inline">\(X\)</span></p></li>
</ul>
<div id="contrast-basic-1" class="section level3">
<h3><span class="header-section-number">1.2.1</span> Contrast bàsic</h3>
<p>Comencem amb un exemple.</p>

<div class="example">
<p><span id="exm:gupis" class="example"><strong>Exemple 1.7  </strong></span>S’havien observat diferències estacionals en el desenvolupament de les gònades d’una espècie de peixos que viuen als llacs africans, i es volia saber si això era conseqüència de la diferència entre estacions en hores de llum o en temperatura. Per decidir-ho, en un experiment s’intentà determinar l’efecte de la llum i la temperatura sobre l’índex gonadosomàtic o <em>GSI</em> (una mesura de creixement de l’ovari) d’aquesta espècie de peixos, es van utilitzar dos fotoperíodes (l’estival, 14 hores de llum i 10 hores de foscor; i l’hivernal, 9 hores de llum-15 hores de foscor) i dues temperatures (l’estival, 27<sup>o</sup> C, i l’hivernal, 16<sup>o</sup> C). En concret, com diem, es volia determinar si el GSI mitjà depèn del fotoperíode, o de la temperatura, o de la combinació dels dos tractaments, i si a més hi ha interacció entre ells.</p>
</div>

<p>L’experiment es va realitzar sobre 20 femelles. Es van dividir aleatòriament en 4 subgrups de 5 exemplars cadascun. Cada grup va rebre una combinació diferent de llum i temperatura. Als 3 mesos es mesuraren els GSI dels peixos</p>
<p>Els resultats obtinguts varen ser:</p>
<p><span class="math display">\[
\begin{array}{c}
\hphantom{(temperatura)}\text{Factor A}\\
\hphantom{(temperatura)}\text{(hores de llum)}\\
\begin{array}{c|cc}
\text{Factor B} &amp; \text{9 hores}&amp;  \text{14 hores}\\
\text{(temperatura)}&amp; &amp;\\\hline
16^\circ &amp;1.30&amp;1.01\\
&amp;2.88&amp;1.52\\
&amp;2.42&amp;1.02\\
&amp;2.66&amp;1.32\\
&amp;2.94&amp;1.63\\\hline
27^\circ &amp;0.90&amp;0.83\\
&amp;1.06&amp;0.67\\
&amp;0.98&amp;0.57\\
&amp;1.29&amp;0.47\\
&amp;1.12&amp;0.66\\ 
\end{array}
\end{array}
\]</span></p>
<p>El disseny experimental d’aquest estudi és d’ANOVA de 2 vies:</p>
<ul>
<li><p>La variable aleatòria d’interés és el GSI d’un peix (femella) als 3 mesos</p></li>
<li><p>Classificam la població (els peixos) segons les combinacions dels nivells de dos factors (A: el fotoperíode; B: la temperatura)</p></li>
<li><p>Prenem una m.a.s. de cada combinació de nivells, independents i totes de la mateixa mida, i mesuram el GSI dels individus seleccionats</p></li>
</ul>
<p>La situació general en una ANOVA de 2 vies serà la següent:</p>
<ul>
<li><p>Tenim en compte dos factors, A i B. El factor A té <span class="math inline">\(a\)</span> nivells (o <strong>tractaments</strong>, recordau) i el factor B, <span class="math inline">\(b\)</span>
nivells.</p>
<p>En el nostre exemple, <span class="math inline">\(a=b=2\)</span></p></li>
<li><p>Fem <span class="math inline">\(n\)</span> observacions de cada combinació de tractaments, un de cada factor. El nombre total d’observacions serà per tant <span class="math inline">\(N=n\cdot a\cdot b\)</span>.</p>
<p>En el nostre exemple, <span class="math inline">\(n=5\)</span> i <span class="math inline">\(N=20\)</span></p></li>
<li><p>Indicarem amb <span class="math inline">\(X_{ijk}\)</span>, <span class="math inline">\(i=1,\ldots,a\)</span>, <span class="math inline">\(j=1,\ldots,b\)</span>, <span class="math inline">\(k=1,\ldots,n\)</span>, el valor de la variable <span class="math inline">\(X\)</span> en el <span class="math inline">\(k\)</span>-èsim subjecte de la mostra corresponent al nivell <span class="math inline">\(i\)</span>-èsim del factor A i el nivell <span class="math inline">\(j\)</span>-èsim del factor B</p></li>
<li><p>Donarem les dades en una taula d’aquest estil:</p></li>
</ul>
<p><span class="math display">\[
\begin{array}{c}
\hphantom{Factor B}\text{Factor A}\\
\begin{array}{c|cccc}
\text{Factor B} &amp; 1&amp; 2 &amp; \ldots &amp; a\\
\hline
1&amp;X_{111}&amp;X_{211}&amp;\cdots&amp;X_{a11}\\
&amp;X_{112}&amp;X_{212}&amp;\cdots&amp;X_{a12}\\
&amp;\cdots&amp;\cdots&amp;\cdots&amp;\cdots\\
&amp;X_{11n}&amp;X_{21n}&amp;\cdots&amp;X_{a1n}\\\hline
2&amp;X_{121}&amp;X_{221}&amp;\cdots&amp;X_{a21}\\
&amp;X_{122}&amp;X_{222}&amp;\cdots&amp;X_{a22}\\
&amp;\cdots&amp;\cdots&amp;\cdots&amp;\cdots\\
&amp;X_{12n}&amp;X_{22n}&amp;\cdots&amp;X_{a2n}\\\hline
\vdots&amp;\vdots&amp;\vdots&amp;\vdots&amp;\vdots\\ 
\vdots&amp;\vdots&amp;\vdots&amp;\vdots&amp;\vdots\\\hline
b&amp;X_{1b1}&amp;X_{2b1}&amp;\cdots&amp;X_{ab1}\\
&amp;X_{1b2}&amp;X_{2b2}&amp;\cdots&amp;X_{ab2}\\
&amp;\cdots&amp;\cdots&amp;\cdots&amp;\cdots\\
&amp;X_{1bn}&amp;X_{2bn}&amp;\cdots&amp;X_{abn}\\\hline
\end{array}
\end{array}
\]</span></p>
<p>Per que tengui sentit realitzar una ANOVA de 2 vies sobre aquestes dades, s’han de satisfer les condicions següents:</p>
<ul>
<li><p>Les observacions per a cada combinació de nivells constitueixen mostres aleatòries simples independents, totes de la mateixa mida <span class="math inline">\(n\)</span></p></li>
<li><p>Cadascuna de les <span class="math inline">\(a\cdot b\)</span> subpoblacions definides per les combinacions de tractaments, un de cada factor, és normal</p></li>
<li><p><strong>Homocedasticitat</strong>: Totes aquestes subpoblacions tenen la mateixa variància, que indicarem amb <span class="math inline">\(\sigma^2\)</span></p></li>
</ul>
<p>Els paràmetres que intervindran en el contrast són:</p>
<ul>
<li><p><span class="math inline">\(\mu\)</span>: la mitjana poblacional global</p></li>
<li><p><span class="math inline">\(\mu_{i\bullet}\)</span>: la mitjana poblacional del nivell <span class="math inline">\(i\)</span>-èsim del factor A</p></li>
<li><p><span class="math inline">\(\mu_{\bullet j}\)</span>: mitjana poblacional del nivell <span class="math inline">\(j\)</span>-èsim del factor B</p></li>
<li><p><span class="math inline">\(\mu_{ij}\)</span>: mitjana poblacional de la combinació <span class="math inline">\((i,j)\)</span> de nivells de A i B</p></li>
</ul>
<p>Passem ara a la mostra amb la que volem realitzar el contrast. Siguin:</p>
<ul>
<li><p><span class="math inline">\(\overline{X}_{ij}=\dfrac{\sum_{k=1}^n X_{ijk}}{n}\)</span>: la mitjana mostral de la combinació <span class="math inline">\((i,j)\)</span> de nivells de A i B; estima <span class="math inline">\(\mu_{ij}\)</span></p></li>
<li><p><span class="math inline">\(\overline{X}_{i\bullet}=\dfrac{\sum_{j=1}^b\sum_{k=1}^n X_{ijk}}{bn}\)</span>: la mitjana mostral del nivell <span class="math inline">\(i\)</span>-èsim del factor A; estima <span class="math inline">\(\mu_{i\bullet}\)</span></p></li>
<li><p><span class="math inline">\(\overline{X}_{\bullet j}=\dfrac{\sum_{i=1}^a\sum_{k=1}^n X_{ijk}}{an}\)</span>: la mitjana mostral del nivell <span class="math inline">\(j\)</span>-èsim del factor B estima <span class="math inline">\(\mu_{\bullet j}\)</span></p></li>
<li><p><span class="math inline">\(\overline{X}=\dfrac{\sum_{i=1}^{a}\sum_{j=1}^b\sum_{k=1}^n X_{ijk}}{a b n}\)</span>: la mitjana mostral de tota la mostra; estima <span class="math inline">\(\mu\)</span></p></li>
</ul>

<div class="example">
<p><span id="exm:unnamed-chunk-36" class="example"><strong>Exemple 1.8  </strong></span>Les mitjanes de la taula de l’Exemple <a href="mes-anova.html#exm:gupis">1.7</a> correspondrien a</p>
</div>

<p><span class="math display">\[
\begin{array}{c}
\text{Factor A}\\
\begin{array}{c|cc|cc|c}
\text{Factor B}&amp;\text{9 hores} &amp; &amp;\text{14 hores} &amp; &amp; \\ \hline
16^\circ &amp;1.30&amp; &amp; 1.01&amp; &amp;\\
&amp;2.88&amp; &amp; 1.52&amp; &amp;\\
&amp;2.42&amp; \!\!\!\!\!\!\overline{X}_{11} &amp; 1.02&amp;\!\!\!\!\!\!\! \overline{X}_{21} &amp;\overline{X}_{\bullet1}\\
&amp;2.66&amp; &amp; 1.32&amp; &amp;\\
&amp;2.94&amp; &amp; 1.63&amp; &amp;\\\hline
27^\circ &amp;0.90&amp; &amp; 0.83&amp; &amp;\\ 
&amp;1.06&amp; &amp; 0.67&amp; &amp;\\
&amp;0.98&amp;\!\!\!\!\!\!  \overline{X}_{12} &amp; 0.57&amp;\!\!\!\!\!\!\! \overline{X}_{22} &amp;\overline{X}_{\bullet2}\\
&amp;1.29&amp; &amp; 0.47&amp; &amp;\\
&amp;1.12&amp; &amp; 0.66&amp; &amp;\\\hline
&amp; \overline{X}_{1\bullet} &amp; &amp; \overline{X}_{2\bullet} &amp; &amp;
\end{array}
\end{array}
\]</span></p>
<p>Anem a calcular-les. Organitzarem les dades en un dataframe <code>peixos</code> amb 3 variables:</p>
<ul>
<li><p><strong>GSI</strong>, quantitativa, contendrà el GSI de cada peix</p></li>
<li><p><strong>llum</strong>, un factor que contendrà el valor del nivell del factor A (fotoperíode) per a cada peix</p></li>
<li><p><strong>temp</strong>, un factor que contendrà el valor del nivell del factor B (temperatura) per a cada peix</p></li>
</ul>
<p>Com a tots els ANOVA, els factors que s’empren per classificar la població han de ser això, factors, al <em>dataframe</em> si volem després emprar la funció <code>aov</code> per fer l’ANOVA.</p>
<p>Entrarem les dades de la taula per fileres. Per tant el factor <strong>llum</strong> ha d’estar format per 10 còpies consecutives del vector (9,14) i el factor <strong>temp</strong> ha d’estar format per 10 còpies de 16 seguides de 10 còpies de 27.</p>
<pre class="sourceCode r"><code class="sourceCode r">GSI=<span class="st"> </span><span class="kw">c</span>(<span class="fl">1.30</span>,<span class="fl">1.01</span>,<span class="fl">2.88</span>,<span class="fl">1.52</span>,<span class="fl">2.42</span>,<span class="fl">1.02</span>,<span class="fl">2.66</span>,<span class="fl">1.32</span>,<span class="fl">2.94</span>,<span class="fl">1.63</span>,<span class="fl">0.90</span>,
       <span class="fl">0.83</span>,<span class="fl">1.06</span>,<span class="fl">0.67</span>,<span class="fl">0.98</span>,<span class="fl">0.57</span>,<span class="fl">1.29</span>,<span class="fl">0.47</span>,<span class="fl">1.12</span>,<span class="fl">0.66</span>)
llum=<span class="kw">as.factor</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">9</span>,<span class="dv">14</span>),<span class="dv">10</span>))
llum</code></pre>
<pre><code>##  [1] 9  14 9  14 9  14 9  14 9  14 9  14 9  14 9  14 9  14 9  14
## Levels: 9 14</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">temp=<span class="kw">as.factor</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">16</span>,<span class="dv">27</span>),<span class="dt">each=</span><span class="dv">10</span>))
temp</code></pre>
<pre><code>##  [1] 16 16 16 16 16 16 16 16 16 16 27 27 27 27 27 27 27 27 27 27
## Levels: 16 27</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">peixos=<span class="kw">data.frame</span>(GSI,llum,temp)
<span class="kw">str</span>(peixos)</code></pre>
<pre><code>## &#39;data.frame&#39;:    20 obs. of  3 variables:
##  $ GSI : num  1.3 1.01 2.88 1.52 2.42 1.02 2.66 1.32 2.94 1.63 ...
##  $ llum: Factor w/ 2 levels &quot;9&quot;,&quot;14&quot;: 1 2 1 2 1 2 1 2 1 2 ...
##  $ temp: Factor w/ 2 levels &quot;16&quot;,&quot;27&quot;: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(peixos)</code></pre>
<pre><code>##    GSI llum temp
## 1 1.30    9   16
## 2 1.01   14   16
## 3 2.88    9   16
## 4 1.52   14   16
## 5 2.42    9   16
## 6 1.02   14   16</code></pre>
<p>Calculem les mitjanes:</p>
<ul>
<li>Les <span class="math inline">\(\overline{X}_{ij}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">Xb.i.j.bullet=<span class="kw">aggregate</span>(GSI<span class="op">~</span>llum<span class="op">+</span>temp, <span class="dt">data=</span>peixos,mean)
Xb.i.j.bullet</code></pre>
<pre><code>##   llum temp  GSI
## 1    9   16 2.44
## 2   14   16 1.30
## 3    9   27 1.07
## 4   14   27 0.64</code></pre>
<p>Hem obtingut aquesta taula:
<span class="math display">\[
\begin{array}{c|cc}
\overline{X}_{ij} &amp; 9 &amp; 14\\ \hline
16 &amp; 2.44 &amp; 1.30\\
27 &amp;  1.07 &amp; 0.64
\end{array}
\]</span></p>
<ul>
<li>Les <span class="math inline">\(\overline{X}_{i\bullet}\)</span></li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">Xb.A=<span class="kw">aggregate</span>(GSI<span class="op">~</span>llum,<span class="dt">data=</span>peixos,mean)
Xb.A</code></pre>
<pre><code>##   llum   GSI
## 1    9 1.755
## 2   14 0.970</code></pre>
<ul>
<li>Les <span class="math inline">\(\overline{X}_{\bullet j}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">Xb.B=<span class="kw">aggregate</span>(GSI<span class="op">~</span>temp,<span class="dt">data=</span>peixos,mean)
Xb.B</code></pre>
<pre><code>##   temp   GSI
## 1   16 1.870
## 2   27 0.855</code></pre>
<ul>
<li>La <span class="math inline">\(\overline{X}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(peixos<span class="op">$</span>GSI)</code></pre>
<pre><code>## [1] 1.3625</code></pre>
<p>Hem obtingut la taula següent:
<span class="math display">\[
\begin{array}{cc|cc|c}
\overline{X}_{1\bullet} &amp; \overline{X}_{2\bullet} &amp; \overline{X}_{\bullet 1} &amp; \overline{X}_{\bullet 2} &amp; \overline{X} \\ \hline
1.755 &amp;  0.970 &amp; 1.870  &amp; 0.855 &amp; 1.3625
\end{array}
\]</span></p>
<p>En l’ANOVA de 2 vies hi tenim les identitats següents:</p>

<div class="theorem">
<p><span id="thm:SS2vies" class="theorem"><strong>Teorema 1.2  (Identitat de les sumes de quadrats)  </strong></span><span class="math display">\[
\begin{array}{l}
SS_{Total} = SS_{Tr}+SS_E\\[1ex]
SS_{Tr} = SS_A+SS_B+SS_{AB}
\end{array}
\]</span>
on</p>
<ul>
<li><p><span class="math inline">\(SS_{Total}=\displaystyle\sum\limits_{i=1}^a\sum\limits_{j=1}^b\sum\limits_{k=1}^n (X_{ijk}-\overline{X})^2\)</span>; és la <strong>Suma Total de Quadrats</strong></p></li>
<li><p><span class="math inline">\(SS_{Tr}=\displaystyle n\sum\limits_{i=1}^a\sum\limits_{j=1}^b (\overline{X}_{ij}-\overline{X})^2\)</span>; és la <strong>Suma de Quadrats dels Tractaments</strong></p></li>
<li><p><span class="math inline">\(SS_{A}=\displaystyle b n\sum\limits_{i=1}^a (\overline{X}_{i\bullet}-\overline{X})^2\)</span>; és la <strong>Suma de Quadrats del Factor A</strong></p></li>
<li><p><span class="math inline">\(SS_{B}=\displaystyle a n\sum\limits_{i=1}^b (\overline{X}_{\bullet j}-\overline{X})^2\)</span>; és la <strong>Suma de Quadrats del Factor B</strong></p></li>
<li><p><span class="math inline">\({SS_{AB}}=n \sum\limits_{i=1}^a\sum\limits_{j=1}^b (\overline{X}_{ij}-\overline{X}_{i\bullet}-\overline{X}_{\bullet j}+\overline{X})^2\)</span>; és la <strong>Suma de Quadrats de la Interacció</strong></p></li>
<li><p><span class="math inline">\(SS_E=\displaystyle\sum\limits_{i=1}^a\sum\limits_{j=1}^b\sum\limits_{k=1}^n (X_{ijk}-\overline{X}_{ij})^2\)</span>; és la <strong>Suma de Quadrats dels Residus</strong> o <strong>dels Errors</strong></p></li>
</ul>
</div>

<p>Com als ANOVA anteriors, aquestes sumes de quadrats representen les diferents fonts de variabilitat de les dades:</p>
<ul>
<li><p><span class="math inline">\(SS_{Total}\)</span> representa la variabilitat total de les dades</p></li>
<li><p><span class="math inline">\(SS_{Tr}\)</span> representa la variabilitat de les mitjanes de les combinacions de nivells</p></li>
<li><p><span class="math inline">\(SS_{A}\)</span> representa la variabilitat de les mitjanes dels nivells del factor A</p></li>
<li><p><span class="math inline">\(SS_{B}\)</span> representa la variabilitat de les mitjanes dels nivells del factor B</p></li>
<li><p><span class="math inline">\(SS_E\)</span> representa la suma de les variabilitats dins cada combinació de nivells</p></li>
<li><p><span class="math inline">\(SS_{AB}\)</span> representa la variabilitat deguda a la interacció.</p></li>
</ul>

<div class="rmdcorbes">
Recordau que, si no hi hagués interacció, per a cada parella de nivells <span class="math inline">\(j,j&#39;\)</span> de B, les diferències
<span class="math display">\[
\mu_{ij}-\mu_{ij&#39;}
\]</span>
serien totes la mateixa, independentment del nivell <span class="math inline">\(i\)</span> de <span class="math inline">\(A\)</span>. Diguem a aquesta diferència <span class="math inline">\(\delta_{jj&#39;}\)</span>. Si ara calculam la mitjana per a tots els nivells <span class="math inline">\(j&#39;\)</span> de B tenim
<span class="math display">\[
\mu_{ij}-\mu_{i\bullet}=\mu_{ij}-\frac{1}{b}\sum_{j&#39;=1}^b \mu_{ij&#39;}=
\frac{1}{b}  \sum_{j&#39;=1}^b(\mu_{ij}-\mu_{ij&#39;})=
  \frac{1}{b}\sum_{j&#39;=1}^b \delta_{jj&#39;}
\]</span>
Aquest valor no depèn del nivell <span class="math inline">\(i\)</span>. Per tant, si ara calculam la mitjana per a tots els nivells <span class="math inline">\(i\)</span> de A
<span class="math display">\[
\mu_{\bullet j}-\mu=\frac{1}{a}\sum_{i=1}^a(\mu_{ij}-\mu_{i\bullet})=\frac{1}{b}\sum_{j&#39;=1}^b \delta_{jj&#39;}
\]</span>
En resum, si no hi hagués interacció entre els dos factors, tendríem que
<span class="math display">\[
\begin{array}{l}
\mu_{ij}-\mu_{i\bullet}-\mu_{\bullet j}+\mu=(\mu_{ij}-\mu_{i\bullet})-(\mu_{\bullet j}-\mu)\\
\qquad\displaystyle \frac{1}{b}\sum_{j&#39;=1}^b \delta_{jj&#39;}-\frac{1}{b}\sum_{j&#39;=1}^b \delta_{jj&#39;}=0
\end{array}
\]</span>
i per tant, sobre la nostra mostra, esperaríem que
<span class="math display">\[
\overline{X}_{ij}-\overline{X}_{i\bullet}-\overline{X}_{\bullet j}+\overline{X}=0
\]</span>
Aleshores, <span class="math inline">\(SS_{AB}\)</span> és la suma dels quadrats de les divergències, per a cada parell <span class="math inline">\((i,j)\)</span>, d’aquests valors a la nostra mostra respecte del que esperaríem si no hi hagués interacció.
</div>

<p>Observau que de
<span class="math display">\[
\begin{array}{l}
SS_{Total} = SS_{Tr}+SS_E\\[1ex]
SS_{Tr} = SS_A+SS_B+SS_{AB}
\end{array}
\]</span>
s’en dedueix que
<span class="math display">\[
SS_{Total} = SS_A+SS_B+SS_{AB}+SS_E
\]</span></p>
<blockquote>
<p>La variabilitat total descompon en la suma de la variabilitat de les mitjanes del factor A més la variabilitat de les mitjanes del factor B més la variabilitat deguda a la interacció més la variabilitat de les mitjanes de les combinacions de tractaments, un de cada factor.</p>
</blockquote>

<div class="example">
<p><span id="exm:unnamed-chunk-43" class="example"><strong>Exemple 1.9  </strong></span>Comprovem aquestes identitats amb les dades de l’Exemple <a href="mes-anova.html#exm:gupis">1.7</a>.</p>
</div>


<div class="rmdexercici">
Procurau entendre com calculam les sumes de quadrats; hem donat els raonaments detallats als altres dos tipus d’ANOVA.
</div>

<pre class="sourceCode r"><code class="sourceCode r">n=<span class="dv">5</span>
a=<span class="dv">2</span>
b=<span class="dv">2</span>
X.barra=<span class="kw">mean</span>(peixos<span class="op">$</span>GSI)</code></pre>
<ul>
<li>La <span class="math inline">\(SS_{Total}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SS.Tot=<span class="kw">sum</span>((peixos<span class="op">$</span>GSI<span class="op">-</span>X.barra)<span class="op">^</span><span class="dv">2</span>)
SS.Tot</code></pre>
<pre><code>## [1] 11.13377</code></pre>
<ul>
<li>La <span class="math inline">\(SS_{A}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SS.A=b<span class="op">*</span>n<span class="op">*</span><span class="kw">sum</span>((Xb.A<span class="op">$</span>GSI<span class="op">-</span>X.barra)<span class="op">^</span><span class="dv">2</span>)
SS.A</code></pre>
<pre><code>## [1] 3.081125</code></pre>
<ul>
<li>La <span class="math inline">\(SS_{B}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SS.B=a<span class="op">*</span>n<span class="op">*</span><span class="kw">sum</span>((Xb.B<span class="op">$</span>GSI<span class="op">-</span>X.barra)<span class="op">^</span><span class="dv">2</span>)
SS.B</code></pre>
<pre><code>## [1] 5.151125</code></pre>
<ul>
<li>La <span class="math inline">\(SS_{AB}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SS.AB=n<span class="op">*</span><span class="kw">sum</span>((Xb.i.j.bullet<span class="op">$</span>GSI<span class="op">-</span>Xb.A<span class="op">$</span>GSI<span class="op">-</span><span class="kw">rep</span>(Xb.B<span class="op">$</span>GSI,<span class="dt">each=</span>a)<span class="op">+</span>X.barra)<span class="op">^</span><span class="dv">2</span>)
SS.AB</code></pre>
<pre><code>## [1] 0.630125</code></pre>
<ul>
<li>La <span class="math inline">\(SS_{Tr}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SS.Tr=n<span class="op">*</span><span class="kw">sum</span>((Xb.i.j.bullet<span class="op">$</span>GSI<span class="op">-</span>X.barra)<span class="op">^</span><span class="dv">2</span>)
SS.Tr</code></pre>
<pre><code>## [1] 8.862375</code></pre>
<ul>
<li>La <span class="math inline">\(SS_{E}\)</span>:</li>
</ul>
<pre class="sourceCode r"><code class="sourceCode r">SS.E=<span class="kw">sum</span>((peixos<span class="op">$</span>GSI<span class="op">-</span><span class="kw">c</span>(<span class="kw">rep</span>(Xb.i.j.bullet[<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>,<span class="dv">3</span>],n),<span class="kw">rep</span>(Xb.i.j.bullet[<span class="dv">3</span><span class="op">:</span><span class="dv">4</span>,<span class="dv">3</span>],n)))<span class="op">^</span><span class="dv">2</span>)
SS.E    </code></pre>
<pre><code>## [1] 2.2714</code></pre>
<p>Comprovem les igualtats de sumes de quadrats</p>
<pre class="sourceCode r"><code class="sourceCode r">SS.Tr</code></pre>
<pre><code>## [1] 8.862375</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">SS.A<span class="op">+</span>SS.B<span class="op">+</span>SS.AB</code></pre>
<pre><code>## [1] 8.862375</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">SS.Tot</code></pre>
<pre><code>## [1] 11.13377</code></pre>
<pre class="sourceCode r"><code class="sourceCode r">SS.Tr<span class="op">+</span>SS.E</code></pre>
<pre><code>## [1] 11.13377</code></pre>
<p>Emprarem els quadrats mitjans següents:</p>
<ul>
<li><p><strong>Quadrat mitjà del factor A</strong>:
<span class="math display">\[
MS_A =\dfrac{SS_A}{a-1}
\]</span></p></li>
<li><p><strong>Quadrat mitjà del factor B</strong>:
<span class="math display">\[
MS_B =\dfrac{SS_B}{b-1}
\]</span></p></li>
<li><p><strong>Quadrat mitjà de la interacció</strong>:
<span class="math display">\[
MS_{AB}=\dfrac{SS_{AB}}{(a-1)(b-1)}
\]</span></p></li>
<li><p><strong>Quadrat mitjà dels tractaments</strong>:
<span class="math display">\[
MS_{Tr}=\dfrac{SS_{Tr}}{ab-1}
\]</span></p></li>
<li><p><strong>Quadrat mitjà dels errors</strong>:
<span class="math display">\[
MS_E=\dfrac{SS_E}{ab (n-1)}
\]</span></p></li>
</ul>
<p>Un altre cop, fixau-vos que els denominadors són diferents dels dels quadrats mitjans homònims en les altres ANOVA.</p>

<div class="example">
<p><span id="exm:unnamed-chunk-53" class="example"><strong>Exemple 1.10  </strong></span>Al nostre Exemple <a href="mes-anova.html#exm:gupis">1.7</a>, on <span class="math inline">\(n=5\)</span> i <span class="math inline">\(a=b=2\)</span>, hem obtingut les sumes de quadrats següents:</p>
</div>

<p><span class="math display">\[
\begin{array}{cccccc}
SS_{Total} &amp; SS_A &amp; SS_B &amp;   SS_{AB} &amp;SS_{Tr} &amp;  SS_E\\ \hline
11.1338 &amp; 3.0811  &amp;  5.1511  &amp;    0.6301  &amp; 8.8624  &amp;  2.2714
\end{array}
\]</span></p>
<p>Per tant:</p>
<p><span class="math display">\[
\begin{array}{ccccc}
MS_A &amp; MS_B &amp; MS_{AB} &amp; MS_{Tr} &amp; MS_E\\ \hline
3.0811  &amp;  5.1511 &amp; 0.6301 &amp; 2.9541 &amp; 0.142
\end{array}
\]</span></p>
<p>En una ANOVA de 2 vies, ens poden interessar els quatre contrastos següents:</p>
<ul>
<li><p><strong>Contrast de mitjanes del factor A</strong>: Contrastam si hi ha diferències entre les mitjanes dels tractaments del factor A:
<span class="math display">\[
\left\{
\begin{array}{l}
H_0 : \mu_{1\bullet}=\mu_{2\bullet}=\cdots
=\mu_{a\bullet} \\
H_1 :  \text{Hi ha } i,i&#39;\text{ tals que }  \mu_{i\bullet}
\not = \mu_{i&#39;\bullet}
\end{array}
\right.
\]</span>
L’estadístic de contrast és
<span class="math display">\[
F_A=\frac{MS_A}{MS_E},
\]</span>
el qual, si <span class="math inline">\(H_0\)</span> és certa, té distribució <span class="math inline">\(F\)</span> de Fisher amb <span class="math inline">\(a-1\)</span> i <span class="math inline">\(ab(n-1)\)</span> graus de llibertat i valor proper a 1</p></li>
<li><p><strong>Contrast de mitjanes del factor B</strong>: Contrastam si hi ha diferències entre les mitjanes dels tractaments del factor B:
<span class="math display">\[
\left\{
\begin{array}{l}
H_0 : \mu_{\bullet 1}=\mu_{\bullet 2}=\cdots =\mu_{ \bullet
b} \\
H_1 :  \text{Hi ha } j,j&#39;\text{ tals que }  \mu_{\bullet j}
\not = \mu_{\bullet j&#39;}
\end{array}
\right.
\]</span>
L’estadístic de contrast és
<span class="math display">\[
F_B=\frac{MS_B}{MS_E},
\]</span>
el qual, si <span class="math inline">\(H_0\)</span> és certa, té distribució <span class="math inline">\(F\)</span> de Fisher amb <span class="math inline">\(b-1\)</span> i <span class="math inline">\(ab(n-1)\)</span> graus de llibertat i valor proper a 1</p></li>
<li><p><strong>Contrast dels tractaments</strong>: Contrastam si hi ha diferències entre les mitjanes de les parelles (nivell de A, nivell de B):
<span class="math display">\[
\left\{
\begin{array}{l}
H_0 : \text{Per a tots }i,j,i&#39;,j&#39;,\ \mu_{ij}=\mu_{i&#39;j&#39;} \\
H_1 :  \text{Hi ha } i,j,i&#39;,j&#39;\text{ tals que } \mu_{ij}\neq \mu_{i&#39;j&#39;}
\end{array}
\right.
\]</span>
L’estadístic de contrast és
<span class="math display">\[
F_{Tr}=\frac{MS_{Tr}}{MS_E},
\]</span>
el qual, si <span class="math inline">\(H_0\)</span> és certa, té distribució <span class="math inline">\(F\)</span> de Fisher amb <span class="math inline">\(ab-1\)</span> i <span class="math inline">\(ab(n-1)\)</span> graus de llibertat i valor proper a 1</p></li>
<li><p><strong>Contrast de no interacció</strong>: Contrastam si hi ha interacció entre els factors A i B:
<span class="math display">\[
\left\{
\begin{array}{l}
H_0 :  \text{No hi ha interacció entre cap parella de nivells d&#39;$A$ i $B$} \\
H_1 :  \text{Hi ha interacció entre alguna parella de nivells d&#39;$A$ i $B$}
\end{array}
\right.
\]</span>
L’estadístic de contrast és
<span class="math display">\[
F_{AB} = \frac{MS_{AB}}{MS_E},
\]</span>
el qual, si <span class="math inline">\(H_0\)</span> és certa, té distribució <span class="math inline">\(F\)</span> de Fisher amb <span class="math inline">\((a-1)(b-1)\)</span> i <span class="math inline">\(ab(n-1)\)</span> graus de llibertat i valor proper a 1</p></li>
</ul>
<p>En els quatre contrastos, el p-valor és
<span class="math display">\[
P(F_{x,y}\geqslant\text{valor de l&#39;estadístic sobre la mostra})
\]</span>
on <span class="math inline">\(F_{x,y}\)</span> representa la distribució <span class="math inline">\(F\)</span> de Fisher amb els graus de llibertat que pertoquin al contrast.</p>

<div class="rmdcaution">
Com fins ara, els graus de llibertat de cada estadístic de contrast F són els denominadors emprats en les definicions dels quadrats mitjans del numerador i el denominados.
</div>

<p>Tota aquesta informació se recull en la taula ANOVA següent:</p>
<p><span class="math display">\[
\begin{array}{llllll}
\hline
\text{Origen de la}&amp;\text{Graus de}&amp;\text{Sumes de}&amp;\text{Quadrats} &amp; \text{Estadístic de}&amp;\text{p-valor}\\[-0.5ex]
\text{variabilitat}&amp;\text{llibertat}&amp;\text{quadrats}&amp;\text{mitjans}&amp;\text{contrast} &amp; \\\hline
\text{Tractaments} &amp; ab-1 &amp; SS_{Tr}&amp; MS_{Tr}  &amp; F_{Tr} &amp; \text{p-valor}_{Tr} \\
\text{Factor A} &amp; a-1 &amp; SS_{A}&amp; MS_{A}  &amp; F_A &amp; \text{p-valor}_A \\
\text{Factor B} &amp; b-1 &amp; SS_{B}&amp; MS_{B}  &amp; F_B &amp; \text{p-valor}_B \\
\text{Interacció AB} &amp; (a-1)(b-1) &amp; SS_{AB}&amp; MS_{AB}  &amp; F_{AB} &amp; \text{p-valor}_{AB} \\
\text{Residus} &amp; ab(n-1) &amp; SS_E &amp; MS_E &amp; \\\hline
\end{array}
\]</span></p>

<div class="example">
<p><span id="exm:unnamed-chunk-55" class="example"><strong>Exemple 1.11  </strong></span>Tornant a l’Exemple <a href="mes-anova.html#exm:gupis">1.7</a>, tenim que <span class="math inline">\(n=5\)</span>, <span class="math inline">\(a=b=2\)</span> i ja hem calculat els quadrats mitjans següents:</p>
</div>

<p><span class="math display">\[
\begin{array}{ccccc}
MS_A &amp; MS_B &amp; MS_{AB} &amp; MS_{Tr} &amp; MS_E\\ \hline
3.0811  &amp;  5.1511 &amp; 0.6301 &amp; 2.9541 &amp; 0.142
\end{array}
\]</span></p>
<p>Realitzem els quatre contrastos:</p>
<ul>
<li><p>Hi ha diferència en la mitjana del GSI segons el fotoperíode?
<span class="math display">\[
\begin{array}{l}
F_A=\dfrac{MS_{A}}{MS_E}=21.7\\
\text{p-valor}_A=P(F_{1,16}\geqslant 21.7)=\texttt{1-pf(21.7,1,16)}=0.0003
\end{array}
\]</span>
<em>Conclusió</em>: Hem trobat evidència estadísticament significativa que el GSI mitjà és diferent segons el fotoperíode (ANOVA de blocs, p-valor 0.0003)</p></li>
<li><p>Hi ha diferència en la mitjana del GSI segons la temperatura?
<span class="math display">\[
\begin{array}{l}
F_B=\dfrac{MS_{B}}{MS_E}=36.3\\
\text{p-valor}_B=P(F_{1,16}\geqslant 36.3)=\texttt{1-pf(36.3,1,16)}=2\cdot 10^{-5}
\end{array}
\]</span>
<em>Conclusió</em>: Hem trobat evidència estadísticament significativa que el GSI mitjà és diferent segons la temperatura (ANOVA de blocs, p-valor 2·10<sup>-5</sup>)</p></li>
<li><p>Hi ha diferència en la mitjana del GSI segons les combinacions de fotoperíode i temperatura?
<span class="math display">\[
\begin{array}{l}
F_{Tr}=\dfrac{MS_{Tr}}{MS_E}=20.8\\
\text{p-valor}_{Tr}=P(F_{3,16}\geqslant 20.8)=\texttt{1-pf(20.8,3,16)}=9\cdot 10^{-6}
\end{array}
\]</span>
<em>Conclusió</em>: Hem trobat evidència estadísticament significativa que no tots els GSI mitjans per a les combinacions de fotoperíode i temperatura són iguals (ANOVA de blocs, p-valor 9·10<sup>-6</sup>)</p></li>
<li><p>Hi ha interacció entre el fotoperíode i la temperatura?
<span class="math display">\[
\begin{array}{l}
F_{AB}=\dfrac{MS_{AB}}{MS_E}=4.437\\
\text{p-valor}_{AB}=P(F_{1,16}\geqslant 4.437)=\texttt{1-pf(4.437,1,16)}=0.051
\end{array}
\]</span>
<em>Conclusió</em>: No hem trobat evidència estadísticament significativa que hi hagi interacció entre el fotoperíode i la temperatura (ANOVA de blocs, p-valor 0.051)</p></li>
</ul>
<p>La taula ANOVA és</p>
<p><span class="math display">\[
\begin{array}{llllll}
\hline
\text{Origen de la}&amp;\text{Graus de}&amp;\text{Sumes de}&amp;\text{Quadrats} &amp; \text{Estadístic de}&amp;\text{p-valor}\\[-0.5ex]
\text{variabilitat}&amp;\text{llibertat}&amp;\text{quadrats}&amp;\text{mitjans}&amp;\text{contrast} &amp; \\\hline
\text{Tractaments} &amp;3&amp;8.862&amp;2.954&amp;20.8 &amp; 9\cdot 10^{-6} \\
\text{Factor A} &amp;1&amp;3.081&amp;3.081&amp;21.7 &amp; 0.0003 \\
\text{Factor B} &amp; 1&amp;5.151&amp;5.151&amp;36.3 &amp; 2\cdot 10^{-5} \\
\text{Interacció AB} &amp; 1&amp;0.630&amp;0.630&amp;4.44 &amp; 0.051 \\
\text{Residus} &amp; 19&amp;11.134&amp;&amp; &amp; \\\hline
\end{array}
\]</span></p>
</div>
<div id="amb-r-1" class="section level3">
<h3><span class="header-section-number">1.2.2</span> Amb R</h3>
<p>A l’ANOVA de 2 vies:</p>
<ul>
<li><p>Els contrastos de les mitjanes de cada un dels factors i de no interacció s’efectuen aplicant <code>summary(aov( ))</code> a la fórmula que separa la variable numèrica pel <strong>producte dels dos factors</strong>, indicat amb un asterisc *.</p></li>
<li><p>El contrast dels tractaments, és a dir, de les mitjanes de les subpoblacions definides per les combinacions de nivells, un de cada factor, s’efectua aplicant <code>summary(aov( ))</code> a la fórmula que separa la variable numèrica per la <strong>combinació dels dos factors</strong>, indicada amb dos punts :.</p></li>
</ul>
<p>Així, l’ANOVA de blocs de l’Exemple <a href="mes-anova.html#exm:esports">1.1</a> es fa amb</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(GSI<span class="op">~</span>llum<span class="op">*</span>temp,<span class="dt">data=</span>peixos))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## llum         1  3.081   3.081  21.704 0.000262 ***
## temp         1  5.151   5.151  36.285 1.77e-05 ***
## llum:temp    1  0.630   0.630   4.439 0.051268 .  
## Residuals   16  2.271   0.142                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(GSI<span class="op">~</span>llum<span class="op">:</span>temp,<span class="dt">data=</span>peixos))</code></pre>
<pre><code>##             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## llum:temp    3  8.862   2.954   20.81 9.06e-06 ***
## Residuals   16  2.271   0.142                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>La primera funció calcula les fileres “Factor A”, “Factor B”, “Interacció AB” i “Residus” de la taula ANOVA, i de la segona funció us heu de quedar amb la primera filera, que us dóna la filera “Tractaments” de la taula ANOVA. No confongueu les fileres <code>llum:temp</code> de la primera taula, que és la de les Interaccions, amb la de la segona, que és la dels Tractaments.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
