<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Tema 2 Variables aleatòries contínues | Matemàtiques II</title>
  <meta name="description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Tema 2 Variables aleatòries contínues | Matemàtiques II" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  <meta name="github-repo" content="cescrossello/MatesII" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Tema 2 Variables aleatòries contínues | Matemàtiques II" />
  
  <meta name="twitter:description" content="Apunts Matemàtiques II bookdown::gitbook." />
  



<meta name="date" content="2021-01-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="variables-aleatòries-discretes.html"/>
<link rel="next" href="chap-conceptes.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Bioestadística II</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentació</a></li>
<li class="chapter" data-level="1" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html"><i class="fa fa-check"></i><b>1</b> Variables aleatòries discretes</a><ul>
<li class="chapter" data-level="1.1" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#generalitats-sobre-variables-aleatòries"><i class="fa fa-check"></i><b>1.1</b> Generalitats sobre variables aleatòries</a></li>
<li class="chapter" data-level="1.2" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#variables-aleatòries-discretes-1"><i class="fa fa-check"></i><b>1.2</b> Variables aleatòries discretes</a><ul>
<li class="chapter" data-level="1.2.1" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#densitat-i-distribució"><i class="fa fa-check"></i><b>1.2.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="1.2.2" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#esperança"><i class="fa fa-check"></i><b>1.2.2</b> Esperança</a></li>
<li class="chapter" data-level="1.2.3" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#variància-i-desviació-típica"><i class="fa fa-check"></i><b>1.2.3</b> Variància i desviació típica</a></li>
<li class="chapter" data-level="1.2.4" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#quantils"><i class="fa fa-check"></i><b>1.2.4</b> Quantils</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#famílies-importants-de-variables-aleatòries-discretes"><i class="fa fa-check"></i><b>1.3</b> Famílies importants de variables aleatòries discretes</a><ul>
<li class="chapter" data-level="1.3.1" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#variables-aleatòries-binomials"><i class="fa fa-check"></i><b>1.3.1</b> Variables aleatòries binomials</a></li>
<li class="chapter" data-level="1.3.2" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#variables-aleatòries-hipergeomètriques"><i class="fa fa-check"></i><b>1.3.2</b> Variables aleatòries hipergeomètriques</a></li>
<li class="chapter" data-level="1.3.3" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#variables-aleatòries-de-poisson"><i class="fa fa-check"></i><b>1.3.3</b> Variables aleatòries de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#test"><i class="fa fa-check"></i><b>1.4</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="variables-aleatòries-contínues.html"><a href="variables-aleatòries-contínues.html"><i class="fa fa-check"></i><b>2</b> Variables aleatòries contínues</a><ul>
<li class="chapter" data-level="2.1" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#densitat-i-distribució"><i class="fa fa-check"></i><b>2.1</b> Densitat i distribució</a></li>
<li class="chapter" data-level="2.2" data-path="variables-aleatòries-contínues.html"><a href="variables-aleatòries-contínues.html#esperança-variància-quantils"><i class="fa fa-check"></i><b>2.2</b> Esperança, variància, quantils…</a></li>
<li class="chapter" data-level="2.3" data-path="variables-aleatòries-contínues.html"><a href="variables-aleatòries-contínues.html#sec:normal"><i class="fa fa-check"></i><b>2.3</b> Variables aleatòries normals</a></li>
<li class="chapter" data-level="2.4" data-path="variables-aleatòries-contínues.html"><a href="variables-aleatòries-contínues.html#amb-r"><i class="fa fa-check"></i><b>2.4</b> Amb R</a><ul>
<li class="chapter" data-level="2.4.1" data-path="variables-aleatòries-contínues.html"><a href="variables-aleatòries-contínues.html#propietats-bàsiques"><i class="fa fa-check"></i><b>2.4.1</b> Propietats bàsiques</a></li>
<li class="chapter" data-level="2.4.2" data-path="variables-aleatòries-contínues.html"><a href="variables-aleatòries-contínues.html#intervals-de-referència"><i class="fa fa-check"></i><b>2.4.2</b> Intervals de referència</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="variables-aleatòries-discretes.html"><a href="variables-aleatòries-discretes.html#test"><i class="fa fa-check"></i><b>2.5</b> Test</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chap-conceptes.html"><a href="chap-conceptes.html"><i class="fa fa-check"></i><b>3</b> Alguns conceptes bàsics</a><ul>
<li class="chapter" data-level="3.1" data-path="chap-conceptes.html"><a href="chap-conceptes.html#unitat-dobservació"><i class="fa fa-check"></i><b>3.1</b> Unitat d’observació</a></li>
<li class="chapter" data-level="3.2" data-path="chap-conceptes.html"><a href="chap-conceptes.html#població-i-mostra"><i class="fa fa-check"></i><b>3.2</b> Població i mostra</a></li>
<li class="chapter" data-level="3.3" data-path="chap-conceptes.html"><a href="chap-conceptes.html#sec:mostreig"><i class="fa fa-check"></i><b>3.3</b> Mostreig aleatori</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Matemàtiques II</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="variables-aleatòries-contínues" class="section level1">
<h1><span class="header-section-number">Tema 2</span> Variables aleatòries contínues</h1>
<p>Quan una variable aleatòria pot prendre molts valors, les probabilitats individuals poden ser molt petites ja que la probabilitat total, 1, s’ha de repartir entre tots els possibles valors. Comparau en el gràfic següent les probabilitats d’una binomial <span class="math inline">\(B(0.5,5)\)</span>, que només pot prendre 6 valors (de 0 a 5), i una binomial <span class="math inline">\(B(0.5,500)\)</span>, que pot prendre 501 valors (de 0 a 500). La probabilitat mínima en el primer cas és més gran que la probabilitat màxima en el segon.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-52-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Com vos podeu imaginar, les variables aleatòries contínues, que poden prendre tot un continu de valors reals (i per tant infinits), tendran probabilitats individuals molt, molt petites.</p>
<p>En aquest curs ens restringirem a variables aleatòries contínues <span class="math inline">\(X: \Omega\to \mathbb{R}\)</span> que satisfan la propietat extra següent: la seva <strong>funció de distribució</strong>
<span class="math display">\[
\begin{array}{rcl}
F_X: \mathbb{R} &amp; \to &amp; [0,1]\\
x &amp;\mapsto &amp;P(X\leq x)
\end{array}
\]</span>
és contínua. Totes les variables aleatòries contínues que us puguin interessar en algun moment satisfan aquesta propietat, així que no perdem res imposant-la. I què guanyam?</p>
<p>Doncs que si <span class="math inline">\(X\)</span> és una variable aleatòria contínua amb funció de distribució contínua, la probabilitat que prengui cada valor concret és 0:
<span class="math display">\[
P(X=a)=0 \text{ per a tot $a \in \mathbb{R}$}.
\]</span></p>

<div class="rmdcorbes">
Per si passa per aquí qualcú que en necessiti una demostració:
<span class="math display">\[
\begin{array}{l}
\displaystyle P(X=a) = P(X\leq a)-P(X&lt;a)=P(X\leq a)-P\Big(\bigcup_{n\geq 1} \Big(X\leq a-\frac{1}{n}\Big)\Big)\\
\displaystyle \qquad= P(X\leq a)-\lim_{n\geq 1}P\Big(X\leq a-\frac{1}{n}\Big)\\
\displaystyle \qquad= F_X(a)-\lim_{n\geq 1}F_X\Big(a-\frac{1}{n}\Big)=0
\end{array}
\]</span>
perquè <span class="math inline">\(F_X\)</span> és contínua.
</div>

<p>En particular, per a una variable aleatòria contínua:</p>
<blockquote>
<p><strong>Probabilitat 0 no significa impossible.</strong></p>
</blockquote>
<p>Cada valor de <span class="math inline">\(X\)</span> té probabilitat 0, però quan mesuram <span class="math inline">\(X\)</span> sobre un subjecte, prendrà qualque valor, no? Per tant, aquest valor de <span class="math inline">\(X\)</span> és possible, malgrat tengui probabilitat 0.</p>
<p>De <span class="math inline">\(P(X=a)=0\)</span> es dedueix que la probabilitat d’un esdeveniment definit amb una desigualtat és exactament la mateixa que la de l’esdeveniment corresponent definit amb una desigualtat estricta. En particular, contràriament al que passava a les variables aleatòries discretes, per a una variable aleatòria contínua sempre tenim que
<span class="math display">\[
P(X\leq a)=P(X&lt;a)
\]</span>
perquè
<span class="math display">\[
P(X\leq a)=P(X&lt;a)+P(X=a)=P(X&lt;a)+0=P(X&lt;a).
\]</span></p>
<p>Més exemples:</p>
<ul>
<li><span class="math inline">\(P(X\geq a)=P(X&gt; a)+P(X=a)=P(X&gt; a)\)</span></li>
<li><span class="math inline">\(P(a \leq X\leq b)=P(a&lt;X &lt;b)+P(X=a)+P(X=b)\)</span> <span class="math inline">\(=P(a&lt;X &lt;b)\)</span></li>
</ul>
<div id="densitat-i-distribució" class="section level2">
<h2><span class="header-section-number">2.1</span> Densitat i distribució</h2>
<p>Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua. Com ja hem dit, la seva <strong>funció de distribució</strong> <span class="math inline">\(F_X\)</span> torna a ser
<span class="math display">\[
x\mapsto F_X(x)=P(X\leq x)
\]</span></p>
<p>Però com que ara tenim que <span class="math inline">\(P(X=x)=0\)</span> per a tot <span class="math inline">\(x\in \mathbb{R}\)</span>, no podem definir la funció de densitat de <span class="math inline">\(X\)</span> com a <span class="math inline">\(f_X(x)=P(X=x)\)</span>. Què podem fer?</p>
<p>Recordau que, a les variables aleatòries discretes,
<span class="math display">\[
F_X(a)=\sum_{x\leq a} f_X(x)
\]</span></p>
<p>En el context de matemàtiques “contínues”, la suma <span class="math inline">\(\sum\)</span> es tradueix en una integral <span class="math inline">\(\int\)</span>. Definim aleshores la <strong>funció de densitat</strong> d’una variable aleatòria contínua <span class="math inline">\(X\)</span> com la funció <span class="math inline">\(f_X:\mathbb{R}\to \mathbb{R}\)</span> tal que:</p>
<ul>
<li><p><span class="math inline">\(f_X(x)\geq 0\)</span>, per a tot <span class="math inline">\(x\in \mathbb{R}\)</span></p></li>
<li><p><span class="math inline">\(\displaystyle F_X(a)=\int_{-\infty}^a f_{X}(x)\, dx\)</span> per a tot <span class="math inline">\(a \in \mathbb{R}\)</span>.</p></li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/dontpanic.png" width="30%" style="display: block; margin: auto;" /></p>
<p>Recordau que la integral té una interpretació senzilla en termes d’àrees. En concret, donats <span class="math inline">\(a \in \mathbb{R}\)</span> i una funció <span class="math inline">\(f(x)\)</span>, la integral
<span class="math display">\[
\int_{-\infty}^a f(x)\, dx
\]</span>
és igual a l’àrea de la regió compresa entre la corba <span class="math inline">\(y=f(x)\)</span> i l’eix d’abscisses <span class="math inline">\(y=0\)</span> a l’esquerra de la recta vertical <span class="math inline">\(x=a\)</span>. Per tant, la funció de densitat <span class="math inline">\(f_X\)</span> de <span class="math inline">\(X\)</span> és la funció positiva tal que, per a tot <span class="math inline">\(a\in \mathbb{R}\)</span>, <span class="math inline">\(F_X(a)\)</span> és igual a <strong>l’àrea sota la corba</strong> <span class="math inline">\(y=f_X(x)\)</span> (és a dir, entre aquesta corba i l’eix d’abscisses) a l’esquerra de <span class="math inline">\(x=a\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/graficadensidad3.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Quina és la idea intuïtiva que hi ha al darrere d’aquesta definició de densitat? Suposau que dibuixam histogrames de freqüències relatives dels valors de <span class="math inline">\(X\)</span> sobre tota la població. Recordau que, en un histograma de freqüències relatives, la freqüència relativa de cada classe (ara la <strong>probabilitat</strong>, ja que parlam de tota la població) és l’amplada de la classe per l’alçada de la seva barra, i que anomenam a aquesta alçada la <strong>densitat</strong> de la classe (i per tant, qualque cosa tendrà a veure amb la densitat de <span class="math inline">\(X\)</span>, no trobau?).</p>
<p>Si dibuixam els histogrames de <span class="math inline">\(X\)</span> prenent classes cada vegada més estretes, els seus polígons de freqüències tendeixen a dibuixar una corba, que hem acolorit en vermell al darrer histograma de la seqüència següent:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-56-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Quan l’amplada de les classes tendeix a 0, obtenim una corba que és el límit d’aquests polígons de freqüències:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-57-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>Aquesta corba és precisament <span class="math inline">\(y=f_X(x)\)</span>. És a dir, la <strong>funció de densitat</strong> <span class="math inline">\(f_X\)</span> d’una variable aleatòria contínua <span class="math inline">\(X\)</span> és la funció límit dels polígons de freqüències d’histogrames de <span class="math inline">\(X\)</span> quan l’amplada de les classes tendeix a 0.</p>
<p>Vegem algunes propietats que es dedueixen del fet que <span class="math inline">\(F_X(a)=P(X\leq a)\)</span> sigui igual a <strong>l’àrea sota la corba</strong> <span class="math inline">\(y=f_X(x)\)</span> a l’esquerra de <span class="math inline">\(x=a\)</span>:</p>
<ul>
<li><p>Com que <span class="math inline">\(P(X&lt;\infty)=P(\Omega)=1\)</span>, <strong>l’àrea total sota la curva <span class="math inline">\(y=f_X(x)\)</span> és 1.</strong></p></li>
<li><p><span class="math inline">\(P(a\leq X\leq b)=P(X\leq b)-P(X&lt;a)\)</span> és l’àrea sota la corba <span class="math inline">\(y=f_X(x)\)</span> a l’esquerra de <span class="math inline">\(x=b\)</span> <strong>menys</strong> l’àrea sota la corba <span class="math inline">\(y=f_X(x)\)</span> a l’esquerra de <span class="math inline">\(x=a\)</span>. Per tant, <span class="math inline">\(P(a\leq X\leq b)\)</span> és igual a <strong>l’àrea sota la corba <span class="math inline">\(y=f_X(x)\)</span> entre <span class="math inline">\(x=a\)</span> i <span class="math inline">\(x=b\)</span>.</strong></p></li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/entreaib.png" width="60%" style="display: block; margin: auto;" /></p>
<ul>
<li><p>Si <span class="math inline">\(\varepsilon&gt;0\)</span> és molt, molt petit, l’àrea sota la corba <span class="math inline">\(y=f_X(x)\)</span> entre <span class="math inline">\(a-\varepsilon\)</span> i <span class="math inline">\(a+\varepsilon\)</span> és aproximadament <span class="math inline">\(2\varepsilon\cdot f_X(a)\)</span> (vegeu la Figura <a href="#fig:epsilon"><strong>??</strong></a>. És a dir,
<span class="math display">\[
P(a-\varepsilon\leq X\leq a+\varepsilon)\approx 2\varepsilon\cdot f_X(a).
\]</span></p>
<p>Per tant, <span class="math inline">\(f_X(a)\)</span> ens dóna una indicació de la probabilitat que <span class="math inline">\(X\)</span> valgui aproximadament <span class="math inline">\(a\)</span> (però <strong>no és</strong> <span class="math inline">\(P(X=a)\)</span>, que val 0). És a dir, per exemple, si <span class="math inline">\(f_X(a)=0.1\)</span> i <span class="math inline">\(f_X(b)=0.5\)</span>, la probabilitat que <span class="math inline">\(X\)</span> prengui un valor al voltant de <span class="math inline">\(b\)</span> proper a <span class="math inline">\(b\)</span> és 5 vegades més gran que la probabilitat que prengui un valor al voltant d’<span class="math inline">\(a\)</span>.</p></li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/density.png" width="60%" style="display: block; margin: auto;" /></p>

<div class="rmdrecordau">
Però <span class="math inline">\(P(X=a)=P(X=b)=0\)</span>, així que, per favor, evitau dir que “la probabilitat que <span class="math inline">\(X\)</span> valgui <span class="math inline">\(b\)</span> <strong>és 5 vegades més gran</strong> que la probabilitat que valgui <span class="math inline">\(a\)</span>”. Sí, ja sabem que <span class="math inline">\(5\cdot 0=0\)</span>, però la frase és enganyosa.
</div>

<p>A les variables aleatòries discretes, definíem la moda com el valor (o els valors) més probable. Però ara no té sentit definir la moda d’una variable contínua <span class="math inline">\(X\)</span> com el valor <span class="math inline">\(x_0\)</span> tal que <span class="math inline">\(P(X=x_0)\)</span> sigui màxim, perquè <span class="math inline">\(P(X=x)=0\)</span> per a tot <span class="math inline">\(x\in \mathbb{R}\)</span>. Aleshores, es defineix la <strong>moda</strong> d’una variable aleatòria contínua <span class="math inline">\(X\)</span> com el valor (o els valors) <span class="math inline">\(x_0\)</span> tal que <span class="math inline">\(f_X(x_0)\)</span> és màxim. Com que <span class="math inline">\(f_X(x_0)\)</span> mesura la probabilitat que <span class="math inline">\(X\)</span> valgui aproximadament <span class="math inline">\(x_0\)</span>, tenim que la moda de <span class="math inline">\(X\)</span> és el valor prop del qual és més probable que caigui el valor de <span class="math inline">\(X\)</span>.</p>
<p>Unes consideracions finals:</p>
<ul>
<li>Ho hem dit en la definició, i ho hem emprat implícitament en tota la secció, però ho tornam a repetir: <span class="math inline">\(f_X(x)\geq 0\)</span> per a tot <span class="math inline">\(x\in \mathbb{R}\)</span>.</li>
</ul>

<div class="rmdcorbes">
En realitat, que <span class="math inline">\(f_X(x)\)</span> sigui <span class="math inline">\(\geq 0\)</span> per a tot <span class="math inline">\(x\in \mathbb{R}\)</span> és conseqüència del fet que <span class="math inline">\(F_X(x)\)</span> sigui positiva i creixent (les funcions de distribució són sempre creixents, perquè si <span class="math inline">\(x&lt;y\)</span>, <span class="math inline">\(F_X(x)=P(X\leq x)\leq P(X\leq i)=F_X(y)\)</span>) i coincideixi amb <span class="math inline">\(\int_{-\infty}^x f_X(x)\,dx\)</span>. Però és més senzill donar-ho com a part de la definició i així ens estalviam la demostració.
</div>

<ul>
<li><span class="math inline">\(f_X(x)\)</span> no és una probabilitat, i per tant pot ser més gran que 1. Per exemple, el gràfic següent mostra la densitat d’una variable normal <span class="math inline">\(N(0,0.01)\)</span> (vegeu la Secció <a href="variables-aleatòries-contínues.html#sec:normal">2.3</a>), que arriba a valer gairebé 40.</li>
</ul>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-61-1.png" width="60%" style="display: block; margin: auto;" /></p>
<ul>
<li>La funció de densitat <span class="math inline">\(f_X\)</span> no té per què ser contínua, encara que la funció de distribució <span class="math inline">\(F_X\)</span> ho sigui.</li>
</ul>
</div>
<div id="esperança-variància-quantils" class="section level2">
<h2><span class="header-section-number">2.2</span> Esperança, variància, quantils…</h2>
<p>L’esperança i la variància d’una variable aleatòria contínua <span class="math inline">\(X\)</span>, amb funció de densitat <span class="math inline">\(f_X\)</span>, es defineixen com en el cas discret, substituint la suma <span class="math inline">\(\sum_{x\in D_x}\)</span> per una integral.</p>
<p>La <strong>mitjana</strong>, o <strong>esperança</strong> (o <strong>valor mitjà</strong>, <strong>valor esperat</strong>…), de <span class="math inline">\(X\)</span> és
<span class="math display">\[
E(X)=\int_{-\infty}^{\infty}x \cdot f_{X}(x)\, dx
\]</span>
És a dir, és l’àrea compresa entre l’eix d’abscisses i la corba <span class="math inline">\(y=xf_X(x)\)</span>.
Com en el cas discret, també la indicarem de vegades amb <span class="math inline">\(\mu_X\)</span>.</p>
<p>Aquest valor té la mateixa interpretació que en el cas discret:</p>
<ul>
<li><p>Representa el valor mitjà de <span class="math inline">\(X\)</span> sobre el total de la població.</p></li>
<li><p>És (amb probabilitat 1) el límit de la mitjana aritmètica dels valors de <span class="math inline">\(X\)</span> sobre mostres aleatòries de mida <span class="math inline">\(n\)</span>, quan <span class="math inline">\(n\to \infty\)</span>.</p></li>
</ul>
<p>Si <span class="math inline">\(g:\mathbb{R}\to \mathbb{R}\)</span> és una funció contínua, l’<strong>esperança</strong> de <span class="math inline">\(g(X)\)</span> és
<span class="math display">\[
E(g(X))=\int_{-\infty}^{+\infty} g(x) f_X(x)dx
\]</span></p>
<p>La <strong>variància</strong> de <span class="math inline">\(X\)</span> és
<span class="math display">\[
\sigma(X)^2=E((X-\mu_X)^2)=\int_{-\infty}^{+\infty} (x-\mu_X)^2 f_X(x)dx
\]</span>
i es pot demostrar que és igual a
<span class="math display">\[
\sigma(X)^2=E(X^2)-\mu_X^2.
\]</span>
També la indicarem de vegades amb <span class="math inline">\(\sigma_X^2\)</span>.</p>
<p>La <strong>desviació típica</strong> de <span class="math inline">\(X\)</span> és
<span class="math display">\[
\sigma(X)=+\sqrt{\sigma(X)^2}
\]</span>
i també la indicarem de vegades amb <span class="math inline">\(\sigma_X\)</span>.</p>
<p>Com en el cas discret, la variància i la desviació típica quantifiquen la variabilitat dels resultats de <span class="math inline">\(X\)</span> respecte del seu valor mitjà <span class="math inline">\(\mu_X\)</span>.</p>
<p>Aquests paràmetres de <span class="math inline">\(X\)</span> tenen les <strong>mateixes propietats</strong> en el cas continu que en el discret. Les recordam:</p>
<ul>
<li><p>Si <span class="math inline">\(b\)</span> és una variable aleatòria constant, <span class="math inline">\(E(b)=b\)</span> i <span class="math inline">\(\sigma(b)^2=0\)</span>.</p></li>
<li><p><span class="math inline">\(E(a X+b)=a E(X)+b\)</span>.</p></li>
<li><p><span class="math inline">\(E(X+Y)=E(X)+E(Y)\)</span>.</p></li>
<li><p>Si <span class="math inline">\(X\leq Y\)</span>, llavors <span class="math inline">\(E(X)\leq E(Y)\)</span>.</p></li>
<li><p>Si <span class="math inline">\(a,b\in \mathbb{R}\)</span>, <span class="math inline">\(\sigma(aX+b)^2=a^2 \sigma(X)^2\)</span> i <span class="math inline">\(\sigma(aX+b)=|a|\cdot \sigma(X)\)</span>.</p></li>
<li><p>Si <span class="math inline">\(X,Y\)</span> són <strong>independents</strong>, <span class="math inline">\(\sigma(X+Y)^2=\sigma(X)^2+\sigma(Y)^2\)</span>. Si no són independents, aquesta igualtat pot ser falsa.</p></li>
</ul>
<p>El <strong>quantil d’ordre <span class="math inline">\(p\)</span></strong> (o <strong><span class="math inline">\(p\)</span>-quantil</strong>) d’una variable aleatòria contínua <span class="math inline">\(X\)</span> és el valor <span class="math inline">\(x_p\in \mathbb{R}\)</span> més petit tal que
<span class="math display">\[
F_X(x_p)=P(X\leq x_p)=p
\]</span></p>

<div class="rmdcorbes">
Observau que, com que <span class="math inline">\(F_X(x)\)</span> tendeix a 0 (la probabilitat del conjunt buit) quan <span class="math inline">\(x\to -\infty\)</span> i tendeix a 1 (la probabilitat de tot <span class="math inline">\(\mathbb{R}\)</span>) quan <span class="math inline">\(x\to +\infty\)</span> i és contínua, pel Teorema del Valor Mitjà de les funcions contínues (que diu, bàsicament, que les funcions contínues no peguen bots) pren tots els valors de l’interval <span class="math inline">\((0,1)\)</span> i per tant, donat qualsevol <span class="math inline">\(p\in (0,1)\)</span>, existeix qualque <span class="math inline">\(x\)</span> tal que <span class="math inline">\(F_X(x)=p\)</span>.
</div>

<p>La <strong>mediana</strong> de <span class="math inline">\(X\)</span> és el seu 0.5-quantil, el <strong>primer</strong> i <strong>tercer quartils</strong> són el seu 0.25-quantil i el seu 0.75-quantil, etc.</p>
</div>
<div id="sec:normal" class="section level2">
<h2><span class="header-section-number">2.3</span> Variables aleatòries normals</h2>
<p>Una variable aleatòria contínua <span class="math inline">\(X\)</span> és <strong>normal</strong> (o té distribució normal) de paràmetres <span class="math inline">\(\mu\)</span> i <span class="math inline">\(\sigma\)</span> (és <span class="math inline">\(N(\mu,\sigma)\)</span>, per a abreujar) quan la seva funció de densitat és
<span class="math display">\[
f_{X}(x)=\frac{1}{\sqrt{2\pi}\sigma} e^{{-(x-\mu)^2}/{2\sigma^{2}}} \mbox{
per a tot } x\in \mathbb{R}
\]</span></p>
<p>Naturalment, no us heu de saber aquesta fórmula.</p>
<p><img src="Bioestadistica-II_files/figure-html/censored.png" width="35%" style="display: block; margin: auto;" /></p>
<p>Però sí que heu de saber que:</p>
<ul>
<li><p>Una variable aleatòria normal <span class="math inline">\(X\)</span> és contínua, i per tant <span class="math inline">\(P(X=x)=0\)</span>, <span class="math inline">\(P(X\leq x)=P(X&lt;x)\)</span> etc.</p></li>
<li><p>Si <span class="math inline">\(X\)</span> és normal, la seva funció de distribució <span class="math inline">\(F_X\)</span> és <strong>injectiva i creixent</strong>: si <span class="math inline">\(x&lt;y\)</span>, <span class="math inline">\(F_X(x)&lt;F_X(y)\)</span>.</p></li>
</ul>
<p>Una variable aleatòria normal diem que és <strong>estàndard</strong> (o <strong>típica</strong>) quan és <span class="math inline">\(N(0,1)\)</span>. Normalment indicarem les variables normals estàndard amb <span class="math inline">\(Z\)</span>.</p>
<p>La gràfica de la densitat d’una variable aleatòria normal és la famosa <strong>campana de Gauss</strong>:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-64-1.png" width="50%" style="display: block; margin: auto;" /></p>
<p>La distribució normal és una distribució teòrica, no la trobareu exacta en la vida real. I malgrat el seu nom, no és més “normal” que altres distribucions contínues.</p>
<p><img src="Bioestadistica-II_files/figure-html/paranormal.png" width="40%" style="display: block; margin: auto;" /></p>
<p>Però és molt important, pel fet que moltes distribucions de la vida real són aproximadament normals. El motiu és que:</p>
<blockquote>
<p>Si una variable aleatòria consisteix a prendre un nombre <strong>molt gran</strong> <span class="math inline">\(n\)</span> de mesures independents d’una o diverses variables aleatòries i sumar-les, aleshores té distribució aproximadament normal, encara que les variables aleatòries de partida no ho siguin.</p>
</blockquote>

<div class="example">
<p><span id="exm:unnamed-chunk-66" class="example"><strong>Exemple 2.1  </strong></span>Una variable binomial <span class="math inline">\(B(n,p)\)</span> s’obté prenent <span class="math inline">\(n\)</span> mesures independents d’una variable Bernoulli <span class="math inline">\(Be(p)\)</span> i sumant-les. Per tant, per la “regla” anterior, una <span class="math inline">\(B(n,p)\)</span> hauria de ser aproximadament normal si <span class="math inline">\(n\)</span> és gran. Doncs sí, si <span class="math inline">\(n\)</span> és gran (posem més gran que 40, encara que si <span class="math inline">\(p\)</span> és molt propera a 0 o 1 la mida de les mostres ha de ser més gran), la distribució d’una variable <span class="math inline">\(X\)</span> binomial <span class="math inline">\(B(n,p)\)</span> s’acosta molt a la d’una normal <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>, on, recordau que si <span class="math inline">\(X\)</span> és <span class="math inline">\(B(n,p)\)</span>, aleshores <span class="math inline">\(\mu_X=np\)</span> i <span class="math inline">\(\sigma_X=\sqrt{np(1-p)}\)</span>.</p>
</div>

<p>Per exemple, el gràfic següent compara les funcions de distribució d’una binomial <span class="math inline">\(B(40,0.3)\)</span> i una normal <span class="math inline">\(N(40\cdot 0.3,\sqrt{40\cdot 0.3\cdot 0.7})\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-67-1.png" width="50%" style="display: block; margin: auto;" /></p>

<div class="rmdrecordau">
En els propers temes emprarem sovint que una variable <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(n\)</span> és gran és aproximadament <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>.
</div>

</div>
<div id="amb-r" class="section level2">
<h2><span class="header-section-number">2.4</span> Amb R</h2>
<p>Per calcular probabilitats d’una <span class="math inline">\(N(\mu,\sigma)\)</span>, cal calcular les integrals a mà.</p>
<p><img src="Bioestadistica-II_files/figure-html/emorisa.png" width="20%" style="display: block; margin: auto;" /></p>
<p>O podeu usar R o alguna aplicació per a mòbil o tauleta. Per a R, la normal és <code>norm</code>. Per tant, si <span class="math inline">\(X\sim N(\mu,\sigma)\)</span>:</p>
<ul>
<li><p><code>dnorm(x,mu,sigma)</code> dóna el valor de la densitat <span class="math inline">\(f_X(x)\)</span></p></li>
<li><p><code>pnorm(x,mu,sigma)</code> dóna el valor de la distribució <span class="math inline">\(F_X(x)=P(X\leq x)\)</span>; afegint-hi el paràmetre <code>lower.tail=FALSE</code> dóna el valor de <span class="math inline">\(P(X\geq x)\)</span></p></li>
<li><p><code>qnorm(q,mu,sigma)</code> dóna el <span class="math inline">\(q\)</span>-quantil de <span class="math inline">\(X\)</span></p></li>
<li><p><code>rnorm(n,mu,sigma)</code> dóna un vector de <span class="math inline">\(n\)</span> nombres aleatoris generats amb aquesta distribució</p></li>
</ul>
<p>Així, per exemple, si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(1,2)\)</span></p>
<ul>
<li><span class="math inline">\(P(X\leq 1.5)\)</span> és</li>
</ul>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="variables-aleatòries-contínues.html#cb25-1"></a><span class="kw">pnorm</span>(<span class="fl">1.5</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.5987063</code></pre>
<ul>
<li>El 0.4-quantil de <span class="math inline">\(X\)</span>, és a dir, el valor <span class="math inline">\(q\)</span> tal que <span class="math inline">\(P(X\leq q)=0.4\)</span> és</li>
</ul>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="variables-aleatòries-contínues.html#cb27-1"></a><span class="kw">qnorm</span>(<span class="fl">0.4</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.4933058</code></pre>
<ul>
<li><span class="math inline">\(P(X=1.5)\)</span> és</li>
</ul>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="variables-aleatòries-contínues.html#cb29-1"></a><span class="kw">dnorm</span>(<span class="fl">1.5</span>,<span class="dv">1</span>,<span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 0.1933341</code></pre>

<div class="rmderror">
No! Com que <span class="math inline">\(X\)</span> és contínua, <span class="math inline">\(P(X=1.5)=0\)</span>. El que us dóna <code>dnorm(1.5,1,2)</code> és el valor de la funció de densitat de <span class="math inline">\(X\)</span> en 1.5, que no creiem que us interessi gaire.
</div>

<p>Si la normal és estàndard, no fa falta entrar la <span class="math inline">\(\mu=0\)</span> i la <span class="math inline">\(\sigma=1\)</span> (són els valors per defecte d’aquests paràmetres per a <code>norm</code>). Així, si <span class="math inline">\(Z\)</span> és <span class="math inline">\(N(0,1)\)</span>:</p>
<ul>
<li><span class="math inline">\(P(Z\leq 1.5)\)</span> és</li>
</ul>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="variables-aleatòries-contínues.html#cb31-1"></a><span class="kw">pnorm</span>(<span class="fl">1.5</span>)</span></code></pre></div>
<pre><code>## [1] 0.9331928</code></pre>
<ul>
<li>El seu 0.95-quantil és</li>
</ul>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="variables-aleatòries-contínues.html#cb33-1"></a><span class="kw">qnorm</span>(<span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## [1] 1.644854</code></pre>
<ul>
<li><p>Si <span class="math inline">\(X\sim N(0,1)\)</span>, què val <span class="math inline">\(P(-1\leq X\leq 1)\)</span>?</p>
<p>Com que <span class="math inline">\(P(-1\leq X\leq 1)=P(X\leq 1)-P(X\leq -1)\)</span>,</p></li>
</ul>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="variables-aleatòries-contínues.html#cb35-1"></a><span class="kw">pnorm</span>(<span class="dv">1</span>)<span class="op">-</span><span class="kw">pnorm</span>(<span class="op">-</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.6826895</code></pre>

<div class="example">
<p><span id="exm:corrcont1" class="example"><strong>Exemple 2.2  </strong></span>A la secció anterior, us hem dit que una variable binomial <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(n\)</span> gran s’aproxima per mitjà d’una variable normal <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>. Així, per exemple, una variable <span class="math inline">\(X\)</span> binomial <span class="math inline">\(B(400,0.2)\)</span> s’aproxima per mitjà d’una variable <span class="math inline">\(Y\)</span> normal <span class="math inline">\(N(400\cdot 0.2,\sqrt{400\cdot 0.2\cdot 0.8})=N(80,8)\)</span>. Aquest “s’aproxima” significa que <span class="math inline">\(F_X\approx F_Y\)</span> i que <span class="math inline">\(f_X(m)\approx f_Y(m)\)</span> per als <span class="math inline">\(m\in D_X\)</span>.</p>
</div>

<p>Vegem alguns exemples:</p>
<ul>
<li><span class="math inline">\(P(X\leq 70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="variables-aleatòries-contínues.html#cb37-1"></a><span class="kw">pbinom</span>(<span class="dv">70</span>,<span class="dv">400</span>,<span class="fl">0.2</span>)</span></code></pre></div>
<pre><code>## [1] 0.1163917</code></pre>
<ul>
<li><span class="math inline">\(P(Y\leq 70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="variables-aleatòries-contínues.html#cb39-1"></a><span class="kw">pnorm</span>(<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.1056498</code></pre>
<ul>
<li><span class="math inline">\(f_X(70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="variables-aleatòries-contínues.html#cb41-1"></a><span class="kw">dbinom</span>(<span class="dv">70</span>,<span class="dv">400</span>,<span class="fl">0.2</span>) </span></code></pre></div>
<pre><code>## [1] 0.02338443</code></pre>
<ul>
<li><span class="math inline">\(f_Y(70)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="variables-aleatòries-contínues.html#cb43-1"></a><span class="kw">dnorm</span>(<span class="dv">70</span>,<span class="dv">80</span>,<span class="dv">8</span>) </span></code></pre></div>
<pre><code>## [1] 0.02283114</code></pre>

<div class="rmdexercici">
El fet que una variable <span class="math inline">\(X\)</span> binomial <span class="math inline">\(B(n,p)\)</span> s’aproximi per mitjà d’una variable <span class="math inline">\(Y\)</span> normal <span class="math inline">\(N(np,\sqrt{np(1-p)})\)</span>, creieu que implica que <span class="math inline">\(P(X=m)\approx P(Y=m)\)</span> per als <span class="math inline">\(m\in D_X\)</span>?
</div>

<p>Quan aproximam una variable discreta, com ara una binomial, per mitjà d’una variable contínua, com ara una normal, hi sol haver alguna <strong>correcció de continuïtat</strong> que millora l’aproximació. En el cas de l’aproximació normal de la binomial, aquesta correcció consisteix en entendre que l’esdeveniment <span class="math inline">\(X=a\)</span> correspon a l’esdeveniment <span class="math inline">\(Y\in (a-1/2,a+1/2)\)</span>. Vegem amb alguns exemples que aplicant aquesta correcció de continuïtat obtenim aproximacions millors. Seguim amb la <span class="math inline">\(X\)</span> i la seva aproximación normal <span class="math inline">\(Y\)</span> d’abans.</p>
<ul>
<li>Hem vist que <span class="math inline">\(P(X\leq 70)=0.1163917\)</span> i <span class="math inline">\(P(Y\leq 70)=0.1056498\)</span>. L’aproximació de continuïtat ens diu que és millor aproximar <span class="math inline">\(P(X\leq 70)\)</span> per mitjà de <span class="math inline">\(P(Y&lt; 70+1/2)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="variables-aleatòries-contínues.html#cb45-1"></a><span class="kw">pnorm</span>(<span class="fl">70.5</span>,<span class="dv">80</span>,<span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.1175152</code></pre>
<ul>
<li>Hem vist que <span class="math inline">\(P(X=70)=0.0233844\)</span>. Vegem que això s’aproxima molt bé amb <span class="math inline">\(P(70-1/2&lt; Y&lt; 70+1/2)\)</span>:</li>
</ul>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="variables-aleatòries-contínues.html#cb47-1"></a><span class="kw">pnorm</span>(<span class="fl">70.5</span>,<span class="dv">80</span>,<span class="dv">8</span>)<span class="op">-</span><span class="kw">pnorm</span>(<span class="fl">69.5</span>,<span class="dv">80</span>,<span class="dv">8</span>) </span></code></pre></div>
<pre><code>## [1] 0.02283949</code></pre>

<div class="example">
<p><span id="exm:exhiperhipo" class="example"><strong>Exemple 2.3  </strong></span>La pressió sistòlica, mesurada en mm Hg, es distribueix com una variable normal amb valor mitjà i desviació típica que depenen del sexe i l’edat. Per a la franja d’edat 16-24 anys, aquests valors (s’estima que) són:</p>
<ul>
<li>Per a homes, <span class="math inline">\(\mu=124\)</span> i <span class="math inline">\(\sigma=13.7\)</span></li>
<li>Per a dones, <span class="math inline">\(\mu=117\)</span> i <span class="math inline">\(\sigma=13.7\)</span></li>
</ul>
<p>El model d’hipertensió-hipotensió acceptat és el descrit en la Figura <a href="variables-aleatòries-contínues.html#fig:hiperhipo">2.1</a>. Volem calcular els límits de cada classe per a cada sexe en aquest grup d’edat.</p>
</div>

<div class="figure" style="text-align: center"><span id="fig:hiperhipo"></span>
<img src="Bioestadistica-II_files/figure-html/hiperhipo.png" alt="Model d'hipertensió-hipotensió." width="80%" />
<p class="caption">
Figura 2.1: Model d’hipertensió-hipotensió.
</p>
</div>
<p>Vegem:</p>
<ul>
<li>El límit superior del grup d’hipotensió serà el valor que deixa a l’esquerra un 5% de les tensions: el 0.05-quantil de la distribució.</li>
<li>El límit superior del grup de risc d’hipotensió serà el valor que deixa a l’esquerra un 10% de les tensions: el 0.1-quantil de la distribució.</li>
<li>El límit inferior del grup de risc d’hipertensió serà el valor que deixa a l’esquerra un 90% de les tensions: el 0.9-quantil de la distribució.</li>
<li>El límit inferior del grup d’hipertensió serà el valor que deixa a l’esquerra un 95% de les tensions: el 0.95-quantil de la distribució.</li>
</ul>
<p>En els homes, la tensió sistòlica és una variable aleatòria <span class="math inline">\(N(124,13.7)\)</span>. Aleshores, aquests quantils són:</p>
<ul>
<li>El 0.05-quantil:</li>
</ul>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="variables-aleatòries-contínues.html#cb49-1"></a><span class="kw">qnorm</span>(<span class="fl">0.05</span>,<span class="dv">124</span>,<span class="fl">13.7</span>)</span></code></pre></div>
<pre><code>## [1] 101.4655</code></pre>
<ul>
<li>El 0.1-quantil:</li>
</ul>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="variables-aleatòries-contínues.html#cb51-1"></a><span class="kw">qnorm</span>(<span class="fl">0.1</span>,<span class="dv">124</span>,<span class="fl">13.7</span>)</span></code></pre></div>
<pre><code>## [1] 106.4427</code></pre>
<ul>
<li>El 0.9-quantil:</li>
</ul>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="variables-aleatòries-contínues.html#cb53-1"></a><span class="kw">qnorm</span>(<span class="fl">0.9</span>,<span class="dv">124</span>,<span class="fl">13.7</span>)</span></code></pre></div>
<pre><code>## [1] 141.5573</code></pre>
<ul>
<li>El 0.95-quantil:</li>
</ul>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="variables-aleatòries-contínues.html#cb55-1"></a><span class="kw">qnorm</span>(<span class="fl">0.95</span>,<span class="dv">124</span>,<span class="fl">13.7</span>)</span></code></pre></div>
<pre><code>## [1] 146.5345</code></pre>
<p>En resum, per als homes de 16 a 24 anys:
<span class="math display">\[
\begin{array}{|ll|}
\hline
\text{Grup} &amp; \text{Interval}\\ \hline
\text{Hipotens} &amp; &lt;101.5\\
\text{Prehipotens} &amp; 101.5\text{ a }106.4\\
\text{Normotens} &amp; 106.4\text{ a }141.6\\
\text{Prehipertens} &amp; 141.6\text{ a }146.5\\
\text{Hipertens} &amp; &gt; 146.5\\ \hline
\end{array}
\]</span></p>

<div class="rmdexercici">
Calculau els límits per a les dones.
</div>

<div id="propietats-bàsiques" class="section level3">
<h3><span class="header-section-number">2.4.1</span> Propietats bàsiques</h3>
<p>Per començar:</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, el seu valor esperat és <span class="math inline">\(E(X)=\mu\)</span> i la seva desviació típica és <span class="math inline">\(\sigma_X=\sigma\)</span>.
</div>

<p>Per tant, si <span class="math inline">\(Z\)</span> és una normal estàndard, <span class="math inline">\(E(Z)=0\)</span> i <span class="math inline">\(\sigma(Z)=1\)</span>.</p>
<p>Una de les propietats clau de la distribució normal és la seva simetria:</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, la seva densitat <span class="math inline">\(f_X\)</span> és simètrica respecte de <span class="math inline">\(\mu\)</span>, és a dir,
<span class="math display">\[
f_{X}(\mu-x)=f_{X}(\mu+x),
\]</span>
i pren el valor màxim a <span class="math inline">\(x=\mu\)</span>. És a dir, <span class="math inline">\(\mu\)</span> és la <strong>moda</strong> de <span class="math inline">\(X\)</span>.
</div>

<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-91-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Per tant, el valor al voltant del qual és més probable que una variable normal <span class="math inline">\(N(\mu,\sigma)\)</span> caigui és el seu valor esperat <span class="math inline">\(\mu\)</span>.</p>
<p>En particular, si <span class="math inline">\(Z\)</span> és <span class="math inline">\(N(0,1)\)</span>, llavors <span class="math inline">\(f_Z\)</span> és simètrica al voltant de 0, és a dir, <span class="math inline">\(f_{Z}(-x)=f_{Z}(x)\)</span>, i la moda de <span class="math inline">\(Z\)</span> és <span class="math inline">\(x=0\)</span>.</p>
<p>Recordau que la funció de distribució d’una variable aleatòria contínua <span class="math inline">\(X\)</span>,
<span class="math display">\[
F_X(x)=P(X\leq x)
\]</span>
és l’àrea compresa entre la densitat <span class="math inline">\(y=f_X(x)\)</span> i l’eix d’abscisses a l’esquerra de <span class="math inline">\(x\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-92-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Llavors, la simetria de <span class="math inline">\(f_X\)</span> fa que, per a tot <span class="math inline">\(x\geq 0\)</span>, les àrees a l’esquerra de <span class="math inline">\(\mu-x\)</span> i a la dreta de <span class="math inline">\(\mu+x\)</span> siguin iguals.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-93-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>És a dir,
<span class="math display">\[
P(X\leq \mu-x)=P(X\geq \mu+x)=1-P(X\leq \mu+x)
\]</span></p>
<p>En particular (prenent <span class="math inline">\(x=0\)</span>)
<span class="math display">\[
P(X\leq \mu)=1-P(X\leq \mu)\Rightarrow P(X\leq \mu)=0.5
\]</span>
i per tant, <span class="math inline">\(\mu\)</span> és també la <strong>mediana</strong> de <span class="math inline">\(X\)</span>.</p>

<div class="rmdimportant">
Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, <span class="math inline">\(\mu\)</span> és la mitjana, la mediana i la moda de <span class="math inline">\(X\)</span>.
</div>

<p>En el cas concret de la normal estàndard <span class="math inline">\(Z\)</span>, per a qualsevol <span class="math inline">\(z\geq 0\)</span> es té que les àrees a l’esquerra de <span class="math inline">\(-z\)</span> i a la dreta de <span class="math inline">\(z\)</span> són iguals
<span class="math display">\[
P(Z\leq -z)=P(Z\geq z)=1-P(Z\leq z)
\]</span>
i la mediana de <span class="math inline">\(Z\)</span> és 0.</p>

<div class="rmdnote">
Ara que sabem més coses de la normal, a l’Exemple <a href="variables-aleatòries-contínues.html#exm:exhiperhipo">2.3</a> ens haguéssim pogut estalviar la meitat de la feina: per la simetria, el 0.95-quantil ha d’estar a la mateixa distància de <span class="math inline">\(\mu\)</span> que el 0.05-quantil, però a la dreta. És a dir, com que <span class="math inline">\(\mu=124\)</span> i el 0.05-quantil havia estat 101.4655, el 0.95-quantil ha de ser el valor a la dreta de 124 i a la mateixa distància d’aquest que 101.4655:
<span class="math display">\[
124+(124-101.4655)=126.5345
\]</span>
El mateix passa amb el 0.9-quantil i el 0.1-quantil, comprovau-ho.
</div>

<p>Si <span class="math inline">\(\mu\)</span> creix, desplaça a la dreta l’eix vertical de simetria de la densitat, i amb ell tota la corba.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-97-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Si <span class="math inline">\(\sigma\)</span> creix, la corba s’aplana: en augmentar la desviació típica, els valors són més variats i augmenta la probabilitat que prenguin valors més llunays de <span class="math inline">\(\mu\)</span>.</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-98-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>El gràfic següent mostra l’efecte combinat:</p>
<p><img src="Bioestadistica-II_files/figure-html/unnamed-chunk-99-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Denotarem per <span class="math inline">\(z_q\)</span> el <strong><span class="math inline">\(q\)</span>-quantil</strong> d’una variable normal estàndard <span class="math inline">\(Z\)</span>. És a dir, <span class="math inline">\(z_q\)</span> és el valor tal que <span class="math inline">\(P(Z\leq z_q)=q\)</span>.</p>
<p>A banda del fet que <span class="math inline">\(z_{0.5}=0\)</span> (la mediana de <span class="math inline">\(Z\)</span> és 0), hi ha dos quantils més de la normal estàndard <span class="math inline">\(Z\)</span> que hauríeu de recordar:</p>
<ul>
<li><p><span class="math inline">\(z_{0.95}=1.64\)</span>; és a dir, <span class="math inline">\(P(Z\leq 1.64)=0.95\)</span> i per tant <span class="math inline">\(P(Z\leq -1.64)=P(Z\geq 1.64)=0.05\)</span> i
<span class="math display">\[
P(-1.64\leq Z\leq 1.64)=0.9.
\]</span></p></li>
<li><p><span class="math inline">\(z_{0.975}=1.96\)</span>; és a dir, <span class="math inline">\(P(Z\leq 1.96)=0.975\)</span> i per tant <span class="math inline">\(P(Z\leq -1.96)=P(Z\geq 1.96)=0.025\)</span> i
<span class="math display">\[
P(-1.96\leq Z\leq 1.96)=0.95.
\]</span></p></li>
</ul>

<div class="rmdmercifulgod">
Molt sovint el valor 1.96 de <span class="math inline">\(z_{0.975}\)</span> s’aproxima per 2. Teniu permís per a fer-ho quan no disposeu de mitjans (R, aplis de mòbil) per a calcular quantils i us considereu incapaços de recordar “1.96”. Però només en aquest cas.
</div>

<p>Una de les propietats de la distribució normal que ens faciliten molt la vida és que <strong>tota combinació lineal de variables aleatòries normals independents és normal</strong>. En concret, tenim els dos resultats següents:</p>

<div class="theorem">
<p><span id="thm:comblinnormals" class="theorem"><strong>Teorema 2.1  </strong></span>Sigui <span class="math inline">\(X\)</span> una variable <span class="math inline">\(N(\mu,\sigma)\)</span>.</p>
<ol style="list-style-type: decimal">
<li><p>Per a tots <span class="math inline">\(a,b\in \mathbb{R}\)</span>, <span class="math inline">\(aX+b\)</span> és normal <span class="math inline">\(N(a\mu+b,|a|\cdot\sigma)\)</span>.</p></li>
<li><p>En particular, la <strong>tipificada</strong> de <span class="math inline">\(X\)</span>
<span class="math display">\[
Z=\dfrac{X-\mu}{\sigma}
\]</span>
és normal estàndard.</p>
</div></li>
</ol>
<p>Més en general:</p>

<div class="theorem">
<span id="thm:comblinnormals2" class="theorem"><strong>Teorema 2.2  </strong></span>Si <span class="math inline">\(X_1,\ldots,X_n\)</span> són variables aleatòries normals <strong>independents</strong> i <span class="math inline">\(a_1,\ldots,a_n,b\in \mathbb{R}\)</span>, llavors <span class="math inline">\(a_1X_1+\cdots +a_nX_n+b\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span> amb
<span class="math display">\[
\mu=a_1\mu_1+\cdots +a_n\mu_n+b,\ 
\sigma=\sqrt{a_1^2\sigma^2_1+\cdots +a_n^2\sigma^2_n}
\]</span>
</div>


<div class="rmdnote">
Que tota combinació lineal de variables normals torni a ser del mateix tipus, és a dir, normal, és una propietat molt útil de les variables normals que poques famílies de distribucions comparteixen. Per exemple, si <span class="math inline">\(X\)</span> és una variable binomial <span class="math inline">\(B(n,p)\)</span> amb <span class="math inline">\(p\neq 0\)</span>, la variable <span class="math inline">\(2X\)</span> no és binomial, perquè només pren valors parells, mentre que una variable binomial <span class="math inline">\(B(m,q)\)</span> ha de poder prendre tots els valors entre 0 i <span class="math inline">\(m\)</span>.
</div>

<p>Les probabilitats de la normal tipificada determinen les de la normal original, perquè si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>:
<span class="math display">\[
\begin{array}{rl}
P(a\leq X\leq b)\!\!\!\!\! &amp; \displaystyle =P\Big( \frac{a-\mu}{\sigma}\leq \frac{X-\mu}{\sigma}\leq \frac{b-\mu}{\sigma}\Big)\\ &amp; \displaystyle =P\Big(\frac{a-\mu}{\sigma}\leq Z\leq \frac{b-\mu}{\sigma}\Big)
\end{array}
\]</span>
Això serveix per deduir fórmules, i els vostres pares ho empraven per calcular probabilitats de normals (amb taules de probabilitats de la normal estàndard); ara és més còmode usar una apli.</p>
</div>
<div id="intervals-de-referència" class="section level3">
<h3><span class="header-section-number">2.4.2</span> Intervals de referència</h3>
<p>Un <strong>interval de referència</strong> del <span class="math inline">\(100q\%\)</span> per a una variable aleatòria <span class="math inline">\(X\)</span> és un interval <span class="math inline">\([a,b]\)</span> tal que
<span class="math display">\[
P(a\leq X\leq b)=q.
\]</span>
És a dir, un interval de referència del <span class="math inline">\(100q\%\)</span> per a <span class="math inline">\(X\)</span> és un interval que conté els valors de <span class="math inline">\(X\)</span> del <span class="math inline">\(100q\%\)</span> dels subjectes de la població.</p>
<p>Per exemple, hem vist en la secció anterior que [-1.64,1.64] i [-1.96,1.96] són intervals de referència del 90% i del 95%, respectivament, per a una variable normal estàndard <span class="math inline">\(Z\)</span>.</p>
<p>Els més comuns són els intervals de referència del 95% (<span class="math inline">\(q=0.95\)</span>), que satisfan que
<span class="math display">\[
P(a\leq X\leq b)=0.95
\]</span>
i són els, que per exemple, us donen com a valors de referència en les analítiques:</p>
<p><img src="Bioestadistica-II_files/figure-html/analit.png" width="80%" style="display: block; margin: auto;" /></p>

<div class="rmdnote">
Quan es parla d’un <strong>interval de referència</strong> sense donar la probabilitat, se sobreentén sempre que és l’interval de referència del 95%.
</div>

<p>Quan <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, aquests intervals de referència es prenen sempre <strong>centrats en la mitjana</strong> <span class="math inline">\(\mu\)</span>, és a dir, de la forma
<span class="math display">\[
[\mu-\text{alguna cosa},\mu+\text{aquesta mateixa cosa}].
\]</span>
Es calculen fàcilment amb el resultat següent:</p>

<div class="theorem">
<p><span id="thm:unnamed-chunk-104" class="theorem"><strong>Teorema 2.3  </strong></span>Si <span class="math inline">\(X\)</span> és <span class="math inline">\(N(\mu,\sigma)\)</span>, un interval de referència del <span class="math inline">\(100q\%\)</span> per a <span class="math inline">\(X\)</span> és
<span class="math display">\[
[\mu- z_{(1+q)/2}\cdot \sigma, \mu+ z_{(1+q)/2}\cdot \sigma]
\]</span>
on <span class="math inline">\(z_{(1+q)/2}\)</span> indica el <span class="math inline">\((1+q)/2\)</span>-quantil de la normal estàndard <span class="math inline">\(Z\)</span>. Normalment escriurem aquest interval
<span class="math display">\[
\mu\pm z_{(1+q)/2}\cdot \sigma.
\]</span></p>
</div>


<div class="rmdcorbes">
<p>En efecte:
<span class="math display">\[
\begin{array}{l}
P(\mu-x\leq X\leq \mu+x)=q\\
\qquad \Longleftrightarrow \displaystyle P\Big(\frac{\mu-x-\mu}{\sigma}\leq \frac{X-\mu}{\sigma}\leq \frac{\mu+x-\mu}{\sigma}\Big)=q\\
\qquad \Longleftrightarrow \displaystyle P(-x/{\sigma}\leq Z\leq {x}/{\sigma})=q\\
\qquad \Longleftrightarrow \displaystyle P(Z\leq {x}/{\sigma})-P(Z\leq -{x}/{\sigma})=q\\
\qquad \Longleftrightarrow \displaystyle P(Z\leq {x}/{\sigma})-(1-P(Z\leq {x}/{\sigma}))=q\\
\qquad \text{(per la simetria de $f_Z$ al voltant de 0)}\\
\qquad \Longleftrightarrow \displaystyle 2P(Z\leq {x}/{\sigma})=q+1\\
\qquad \Longleftrightarrow P(Z\leq {x}/{\sigma})=(1+q)/2\\
\qquad \Longleftrightarrow x/\sigma=
z_{(1+q)/2}\\
\qquad \Longleftrightarrow x=z_{(1+q)/2}\cdot \sigma
\end{array}
\]</span></p>
</div>

<p>Si <span class="math inline">\(q=0.95\)</span>, llavors <span class="math inline">\((1+q)/2=0.975\)</span> i <span class="math inline">\(z_{0.975}=1.96\)</span>. Per tant, l’interval de referència del 95% per a una variable <span class="math inline">\(X\)</span> normal <span class="math inline">\(N(\mu,\sigma)\)</span> és
<span class="math display">\[
\mu\pm 1.96\sigma.
\]</span>
I com que aquest 1.96 sovint s’aproxima per 2, l’interval de referència del 95% d’una <span class="math inline">\(N(\mu,\sigma)\)</span> se sol simplificar a
<span class="math display">\[
\mu\pm 2\sigma.
\]</span>
Això diu, bàsicament, que</p>
<blockquote>
<p>Si una població segueix una distribució normal <span class="math inline">\(N(\mu,\sigma)\)</span>, un 95% dels seus individus tenen el seu valor de <span class="math inline">\(X\)</span> a distància com a màxim <span class="math inline">\(2\sigma\)</span> (“a dues sigmes”) de <span class="math inline">\(\mu\)</span>.</p>
</blockquote>

<div class="example">
<p><span id="exm:unnamed-chunk-106" class="example"><strong>Exemple 2.4  </strong></span>Segons l’OMS, les altures (en cm) de les dones europees de 18 anys segueixen una llei <span class="math inline">\(N(163.1,18.53)\)</span>. Quin és l’interval d’altures centrat en la mitjana que conté a la meitat les europees de 18 anys?</p>
</div>

<p>Fixau-vos que, si diem <span class="math inline">\(X\)</span> a la variable aleatòria “Altura d’una dona europea de 18 anys en cm”, el que volem saber és l’interval centrat en la seva mitjana, 163.1, tal que la probabilitat que l’alçada d’una europea de 18 anys triada a l’atzar pertanyi a aquest interval sigui 0.5. És a dir, l’interval de referència del 50% per a <span class="math inline">\(X\)</span>.</p>
<p>Ens diuen que <span class="math inline">\(X\)</span> és <span class="math inline">\(N(163.1,18.53)\)</span>. Si <span class="math inline">\(q=0.5\)</span>, llavors <span class="math inline">\((1+q)/2=0.75\)</span>. El 0.75-quantil <span class="math inline">\(z_{0.75}\)</span> d’una normal estàndard és</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="variables-aleatòries-contínues.html#cb57-1"></a><span class="kw">qnorm</span>(<span class="fl">0.75</span>)</span></code></pre></div>
<pre><code>## [1] 0.6744898</code></pre>
<p>Per tant, l’interval de referència demanat és <span class="math inline">\(163.1\pm 0.6745\cdot 18.53\)</span>, és a dir, arrodonint a mm, <span class="math inline">\([150.6, 175.6]\)</span>. Això ens diu que la meitat de les dones europees de 18 anys fan entre 150.6 i 175.6 cm.</p>
<!--
El **z-score** d'un valor $x_0\in \mathbb{R}$ respecte d'una distribució $N(\mu,\sigma)$ és
$$
\frac{x_0-\mu}{\sigma}
$$

És a dir, el z-score de $x_0$ és el resultat de "tipificar" $x_0$ en el sentit del Teorema \@ref(thm:comblinnormals).2.

Si la variable poblacional és normal, com més gran és el valor absolut del z-score de $x_0$, més "rar" és $x_0$; el signe ens diu si és més gran o més petit que el valor esperat $\mu$.

\BeginKnitrBlock{example}<div class="example"><span class="example" id="exm:unnamed-chunk-108"><strong>(\#exm:unnamed-chunk-108) </strong></span>Recordau que, segons l'OMS, les altures de les dones europees de 18 anys segueixen una llei $N(163.1,18.53)$. Quin seria el z-score d'una jugadora de bàsquet de 18 anys que fes 191 cm?
</div>\EndKnitrBlock{example}

Seria
$$ 
\frac{191-163.1}{18.53}=1.5
$$

Això se sol llegir dient que l'alçada d'aquesta jugadora està **1.5 sigmes per sobre de l'alçada mitjana**.

-->
</div>
</div>
<div id="test" class="section level2">
<h2><span class="header-section-number">2.5</span> Test</h2>
<p><strong>(1)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua de funció de densitat:
<span class="math display">\[
f_X(x)=\left\{\begin{array}{ll}
0 &amp; \mbox{si $x&lt;0$}\\
\frac{2\sqrt{2}}{\sqrt{\pi}} e^{-2x^2} &amp; \mbox{si $x\geq 0$}
\end{array}
\right.
\]</span>
És cert que <span class="math inline">\(P(X=1)=2\sqrt{2}e^{-2}/\sqrt{\pi}\)</span>?</p>
<ol style="list-style-type: decimal">
<li>Sí</li>
<li>No: en realitat <span class="math inline">\(P(X=1)=\int_{-\infty}^1 \frac{2\sqrt{2}}{\sqrt{\pi}} e^{-2x^2}\,dx\)</span> però no sé calcular aquesta integral, o sí que sé calcular-la, però em fa mandra fer-ho.</li>
<li>Això no és la funció de densitat d’una variable aleatòria contínua, perquè no és una funció contínua (en el 0 bota de 0 a <span class="math inline">\(2\sqrt{2}/\sqrt{\pi}\)</span>)</li>
<li>Totes les altres respostes són incorrectes</li>
</ol>
<p><strong>(2)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua de mitjana <span class="math inline">\(\mu\)</span>. Què val <span class="math inline">\(P(X=\mu)\)</span>?</p>
<ol style="list-style-type: decimal">
<li>0.5</li>
<li><span class="math inline">\(\mu\)</span></li>
<li>0</li>
<li>Depèn de la variable aleatòria</li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(3)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria contínua de moda <span class="math inline">\(M\)</span>. Què val <span class="math inline">\(P(X=M)\)</span>?</p>
<ol style="list-style-type: decimal">
<li>1</li>
<li>0.5</li>
<li>0</li>
<li>Depèn de la variable aleatòria, però és el valor màxim de <span class="math inline">\(P(X=x)\)</span></li>
<li>Depèn de la variable aleatòria, però és el valor màxim de la funció de densitat de <span class="math inline">\(X\)</span>.</li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(4)</strong> Sigui <span class="math inline">\(Z\)</span> una variable aleatòria normal estàndard. Marca les afirmacions vertaderes.</p>
<ol style="list-style-type: decimal">
<li>És asimètrica a l’esquerra.</li>
<li>La seva mitjana és 1.</li>
<li>La seva desviació típica és 0.</li>
<li>La seva variància és 1.</li>
<li>La seva mitjana és 0.</li>
</ol>
<p><strong>(5))</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria <span class="math inline">\(N(\mu,\sigma)\)</span> i <span class="math inline">\(f_X\)</span> la seva funció de densitat. Què val l’àrea entre la corba <span class="math inline">\(y=f_X(x)\)</span> i l’eix d’abscisses?</p>
<ol style="list-style-type: decimal">
<li>0</li>
<li><span class="math inline">\(\mu\)</span></li>
<li><span class="math inline">\(\sigma\)</span></li>
<li>1</li>
<li>Totes les altres respostes són falses</li>
</ol>
<p><strong>(6)</strong> Sigui <span class="math inline">\(X\)</span> una variable aleatòria <span class="math inline">\(N(\mu,\sigma)\)</span> i <span class="math inline">\(f_X\)</span> la seva funció de densitat. Quina de les afirmacions següents és vertadera?</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(\mu\)</span> és la mitjana de <span class="math inline">\(X\)</span>, però no la seva mediana</li>
<li><span class="math inline">\(\mu\)</span> és la mitjana i la mediana de <span class="math inline">\(X\)</span>, però no la seva moda</li>
<li><span class="math inline">\(\mu\)</span> és la mitjana, la mediana i la moda de <span class="math inline">\(X\)</span>, però no és veritat que <span class="math inline">\(P(X=\mu)&gt;P(X=a)\)</span> per a tot <span class="math inline">\(a\neq \mu\)</span></li>
<li><span class="math inline">\(\mu\)</span> és la mitjana, la mediana i la moda de <span class="math inline">\(X\)</span> i <span class="math inline">\(P(X=\mu)&gt;P(X=a)\)</span> per a tot <span class="math inline">\(a\neq \mu\)</span></li>
</ol>
<p><strong>(7)</strong> El FME (Flux Màxim d’Expiració) de les al·lotes d’11 anys segueix una distribució aproximadament normal de mitjana 300 l/min i desviació típica 20 l/min. Marca les afirmacions veritables:</p>
<ol style="list-style-type: decimal">
<li>Aproximadament la meitat de les al·lotes d’11 anys tenen un FME entre 280 l/min i 320 l/min.</li>
<li>Al voltant del 95% de les al·lotes d’11 anys tenen un FME entre 280 l/min i 320 l/min.</li>
<li>Al voltant del 95% de les al·lotes d’11 anys tenen un FME entre 260 l/min i 340 l/min.</li>
<li>Al voltant del 5% de les al·lotes d’11 anys tenen un FME inferior a 260 l/min.</li>
<li>Cap al·lota d’11 anys té FME superior a 360 l/min.</li>
</ol>
<p><strong>(8)</strong> En una mostra aleatòria extreta de població sana es troba que una variable bioquímica té com a mitjana 90 i desviació típica 10. Si prenem una mostra d’individus sans, és raonable esperar que aproximadament el 95% d’ells tenguin un valor d’aquesta variable comprès entre 70 i 110? (marca totes les respostes correctes):</p>
<ol style="list-style-type: decimal">
<li>Sí, sempre.</li>
<li>No, mai.</li>
<li>Si la variable té distribució normal, sí.</li>
<li>Si la mostra és prou gran, sí.</li>
<li>Si la variable té distribució normal i la mostra és prou gran, sí.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="variables-aleatòries-discretes.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-conceptes.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"download": ["pdf", "epub"]
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
